### PR TITLE
resource/aws_nat_gateway: Remove network_interface_id, private_ip, and public_ip as configurable

### LINKED ISSUE #6223: terraform not assigning private ip to nat gateway both on creation and on modification
### terraform version

terraform -v
Terraform v0.11.8

### actual code 

variable "nat_gw_ip_st" {
  default = "10.119.20.161"
}

resource "aws_nat_gateway" "nat_gw" {
  allocation_id = "${aws_eip.nat.id}"
  subnet_id = "${aws_subnet.subnet.0.id}"
  private_ip = "${var.nat_gw_ip_st}"
  depends_on = ["aws_internet_gateway.internet_gateway"]
  tags {
    Name = "${local.prefix}:nat-gw"
  }
}

### terraform output

aws_nat_gateway.nat_gw: Modifying... (ID: nat-041b6751664f1f305)
  private_ip: "10.119.20.161" => "10.119.0.11"

### observed behavior

private ip of the nat gateway is still  10.119.20.161

### expected behavior

ip of the gateway should be 10.119.0.11

### PR DESCRIPTION
**Pull request by bflad**
Fixes #6223 

The API nor the resource actually support configuring these attributes.

Changes proposed in this pull request:

* Remove `Optional` from `network_interface_id`, `private_ip`, and `public_ip` attributes
* tests/resource/aws_nat_gateway: Perform import testing in all acceptance tests and remove bespoke importBasic test

Output from acceptance testing:

```
--- PASS: TestAccAWSNatGateway_basic (221.42s)
--- PASS: TestAccAWSNatGateway_tags (259.84s)
```

### CODE REVIEW

File: aws/resource_aws_nat_gateway.go [hunk 1]
```diff
@@ -38,19 +38,16 @@ func resourceAwsNatGateway() *schema.Resource {
...
 
 			"private_ip": {
 				Type:     schema.TypeString,
-				Optional: true,
 				Computed: true,
 			},
 
 			"public_ip": {
 				Type:     schema.TypeString,
-				Optional: true,
```
Comment (tombuildsstuff) [inline aws/resource_aws_nat_gateway.go]: should these be moved in the docs too?

Comment (bflad) [reply aws/resource_aws_nat_gateway.go]: They are correctly listed only as attributes in the current documentation, unless I'm missing something 😄 

https://www.terraform.io/docs/providers/aws/r/nat_gateway.html
