### PR TITLE
resource/aws_dynamodb_table: Fix DynamoDB TTL state detection

### LINKED ISSUE #3463: DynamoDB TTL Infinitely Out of Sync
DynamoDB tables that have a `ttl` block with `enabled = false` will never be able to have their state in sync with the infrastructure.

### Terraform Version
```
Terraform v0.11.3
+ provider.aws v1.9.0
+ provider.template v1.0.0
```

### Affected Resource(s)
- aws_dynamodb_table

### Terraform Configuration Files
```hcl
provider "aws" {
  region = "us-west-2"
}

resource "aws_dynamodb_table" "dynamodb-composite-gsi-composite" {
  count = 1
  name  = "glen-test-ignore"

  read_capacity  = 10
  write_capacity = 10
  hash_key       = "hi"
  range_key      = "me"

  attribute {
    name = "hi"
    type = "S"
  }

  attribute {
    name = "me"
    type = "N"
  }

  attribute {
    name = "x"
    type = "S"
  }

  attribute {
    name = "y"
    type = "N"
  }

  ttl {
    enabled        = false
    attribute_name = ""
  }

  global_secondary_index {
    name            = "glen-test"
    hash_key        = "x"
    range_key       = "y"
    write_capacity  = "10"
    read_capacity   = "10"
    projection_type = "ALL"
  }
}
```

### Debug Output
https://gist.github.com/goakley/c682bf633544bc71cfbe4367df30bfbf

### Expected Behavior
Terraform should have determined that no changes needed to be applied, since the DyanmoDB TTL feature is already disabled on the table.

### Actual Behavior
Terraform wants to change the TTL to DISABLED, which will end up being a noop.  If this is run (and it will succeed), Terraform will determine that the exact same set of changes will need to be made on the next Terraform run.  That is, it will never think that the DynamoDB TTL feature is disabled even though it is.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform apply`

### Important Factoids
This example is a simplified version of our production code, which references variables to set the `enabled` property of the `ttl` block.  Many of our tables don't use TTL, so `enabled` is set to `false`, but this causes Terraform to forever think that the DynamoDB table is out of sync with the Terraform state.

### References
None.

### PR DESCRIPTION
**Pull request by goakley**
Fixes #3463 

DynamoDB has TTL state always set to DISABLED unless it is otherwise enabled.  The terraform logic decided that this meant if TTL is set to DISABLED, then there should be no `ttl {}` block at all.  This is incorrect, as there can be a `ttl {}` block with the setting `enabled = false`.  This change fixes that issue.

DynamoDB acceptance tests have been updated and run.

### CODE REVIEW

**Comment by goakley** [comment]
@radeksimko Is there anything that could be improved to make this change more amicable?

**Comment by danieladams456** [comment]
bump

File: aws/resource_aws_dynamodb_table.go [hunk 1]
```diff
@@ -111,6 +111,7 @@ func resourceAwsDynamoDbTable() *schema.Resource {
 			"ttl": {
 				Type:     schema.TypeSet,
 				Optional: true,
+				Computed: true,
```
Comment (bflad) [inline aws/resource_aws_dynamodb_table.go]: Generally speaking: setting `Computed: true` is not an ideal situation because it prevents Terraform from being able to detect any sort of API drift when an attribute is not defined in the configuration. In this case, people would most likely be expecting that Terraform let's them know when TTL is enabled on a DynamoDB table outside of Terraform when its disabled by default and its not defined in their configuration.

We'll need to figure out how to support this without `Computed: true` most likely. An option might be setting this attribute up like how the `aws_codebuild_project` `cache` attribute is with a `DiffSuppressFunc` and changing `enabled` to `Optional: true` (and potentially `Default: false`).

Comment (goakley) [reply aws/resource_aws_dynamodb_table.go]: Are the `Computed`, `DiffSuppressFunc`, etc properties documented anywhere?  I could not find them and was not actually sure what `Computed` means.  I didn't know about `DiffSuppressFunc` - I copied this strategy from the `aws_s3_bucket` resource, but could take that approach instead.

**Comment by goakley** [comment]
@bflad the CR now uses `DiffSuppressFunc` and still works as expected.

**Comment by goakley** [comment]
Any chance this is acceptable now?

**Comment by goakley** [comment]
@bflad Are there any issues with this approach?

**Comment by goakley** [comment]
Is this something that shouldn't be fixed by design?

**Comment by danieladams456** [comment]
This fix would be very useful.

**Comment by pshastry** [comment]
This would be very helpful

**Comment by goakley** [comment]
@bflad is there any chance this can get looked at again?

**Comment by goakley** [comment]
Thanks @bflad!  I've been away until this week and I'm glad to see this was addressed.

**Comment by bflad** [comment]
This has been released in [version 2.1.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#210-march-07-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by inge4pres** [comment]
Added some info regarding the TTL problem [here](https://github.com/terraform-providers/terraform-provider-aws/issues/10304#issuecomment-557541148)
