### PR TITLE
resource/aws_sqs_queue_policy: Prevent missing policy error on read

### LINKED ISSUE #2669: SQS Queue created without Policy cannot have policy attached
When attempting to plan a config that attaches a policy to an SQS queue, the plan fails if the SQS queue does not already have a policy attached.

https://github.com/terraform-providers/terraform-provider-aws/blob/8994a3474b02dd6f76cc5ecef2d1cfc6ba2e5def/aws/resource_aws_sqs_queue_policy.go#L79-L82

### Terraform Version
`0.10.7`
aws provider `1.2.0` (but bug still exists in master)

### Affected Resource(s)
`aws_sqs_queue_policy`

### Terraform Configuration Files
There are a few other resources, but they aren't relevant.
```hcl
resource "aws_sqs_queue_policy" "sqs_policy" {
  queue_url = "${aws_sqs_queue.q.id}"

  policy = <<POLICY
{
  "Version": "2012-10-17",
  "Id": "${aws_sqs_queue.q.id}/SQSDefaultPolicy",
  "Statement": [
    {
      "Sid": "SidNNNNNNNNNNN",
      "Effect": "Allow",
      "Principal": {
        "AWS": "${module.svc.task_role_arn}"
      },
      "Action": [
        "SQS:SendMessage",
        "SQS:PurgeQueue"
      ],
      "Resource": "${aws_sqs_queue.q.arn}"
    }
  ]
}
POLICY
}
```

### Expected Behavior
The plan succeeds with changes showing the policy being added.

### Actual Behavior
The plan fails with `SQS Queue policy not found for sqs-policy-https://sqs.us-west-2.amazonaws.com/NNNNNNNNN/sqs_queue`

### Steps to Reproduce
1. Create an SQS queue without a Policy attached
2. Add policy to terraform config and plan

### PR DESCRIPTION
**Pull request by bflad**
SQS attribute creation/updates can take up to 60 seconds for propagation. This PR addresses two facets:
* Most importantly, new queue policies can currently error out when the new Policy attribute may not have propagated everywhere yet, which is a bad user experience. Instead of raising error, we can just set the policy to empty string in the state. Likely the next read will pick up the correct policy.
* To help mitigate eventual consistency issues, add a `resource.StateChangeConf` on upsert to try to wait for the new/updated policy. Arguably this could be removed or moved into the read as well.

Closes #2669

```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSSQSQueuePolicy'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSSQSQueuePolicy -timeout 120m
=== RUN   TestAccAWSSQSQueuePolicy_basic
--- PASS: TestAccAWSSQSQueuePolicy_basic (17.68s)
=== RUN   TestAccAWSSQSQueuePolicy_import
--- PASS: TestAccAWSSQSQueuePolicy_import (16.96s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	34.673s
```

### CODE REVIEW

File: aws/resource_aws_sqs_queue_policy.go [hunk 1]
```diff
@@ -40,18 +43,51 @@ func resourceAwsSqsQueuePolicy() *schema.Resource {
...
+				equivalent, err := awspolicy.PoliciesAreEquivalent(*queuePolicy, policy)
+				if err != nil || !equivalent {
+					return out, "", nil
+				}
+				return out, "SQS queue policy updated", nil
+			}
+			return out, "", nil
+		},
+	}
+	_, err = wait.WaitForState()
```
Comment (radeksimko) [inline aws/resource_aws_sqs_queue_policy.go]: Have you considered using the `resource.Retry` helper instead of this wrapper? We'd still need to make up the error message when policies aren't equivalent, but I feel that it'd be a little bit cleaner as the whole thing isn't really "stateful". 🤔

Comment (radeksimko) [reply aws/resource_aws_sqs_queue_policy.go]: Also we're catching _all errors_ here and treating them as "retryable" which (IMO) isn't ideal. I assume the goal is to only catch `AWS.SimpleQueueService.NonExistentQueue`?

Comment (bflad) [reply aws/resource_aws_sqs_queue_policy.go]: Good call on both of these -- I'll get this PR updated shortly.

**Comment by bflad** [comment]
Updated 😄 

```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSSQSQueuePolicy'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSSQSQueuePolicy -timeout 120m
=== RUN   TestAccAWSSQSQueuePolicy_basic
--- PASS: TestAccAWSSQSQueuePolicy_basic (14.96s)
=== RUN   TestAccAWSSQSQueuePolicy_import
--- PASS: TestAccAWSSQSQueuePolicy_import (15.16s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	30.173s
```

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.8.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#180-january-29-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
