### PR TITLE
Adjust aws_dynamodb_table CreateTable LimitExceededException handling for different error messaging

### LINKED ISSUE #1776: DynamoDB table creation fails due to concurrency limit
### Terraform Version
Terraform: 0.10.6
AWS Provider: 1.0.0

### Affected Resource(s)
- aws_dynamodb_table

### Actual Behavior
AWS Error creating DynamoDB table: LimitExceededException: Subscriber limit exceeded: Only 10 tables can be created, updated, or deleted simultaneously

### LINKED ISSUE #2146: Creating 10+ dynamo tables now causes LimitExceededException
_This issue was originally opened by @grayaii as hashicorp/terraform#16525. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version

`Terraform v0.10.7`

### Terraform Configuration Files
```hcl
resource "aws_dynamodb_table" "tab1" {
    name           = "${var.environment}_cron"
    read_capacity  = "${var.cron_read_capacity}"
    write_capacity = "${var.cron_write_capacity}"
    hash_key       = "task_arn"
    attribute {
      name = "task_arn"
      type = "S"
    }
}
resource "aws_dynamodb_table" "tab2" {
    name           = "${var.environment}_cron"
    read_capacity  = "${var.cron_read_capacity}"
    write_capacity = "${var.cron_write_capacity}"
    hash_key       = "task_arn"
    attribute {
      name = "task_arn"
      type = "S"
    }
}
// ETC ETC... all the way up to 15 tables.
```

### Expected Behavior
Dynamo tables should have been created without throwing a LimitExceededException, and without terraform failing.

### Actual Behavior

```
 * aws_dynamodb_table.change_in_condition: AWS Error creating DynamoDB table: LimitExceededException: Subscriber limit exceeded: You have exceeded the maximum number of indexed tables that can be created simultaneously
 	status code: 400, request id: BJLQQ32VNNT0C3SF1OJ28ES3QFVV4KQNSO5AEMVJF66Q9ASUAAJG
 * aws_dynamodb_table.cron: 1 error(s) occurred:

 * aws_dynamodb_table.cron: AWS Error creating DynamoDB table: LimitExceededException: Subscriber limit exceeded: Only 10 tables can be created, updated, or deleted simultaneously
 	status code: 400, request id: 2HBQDGSJJQ2740DD08G9KPF8GJVV4KQNSO5AEMVJF66Q9ASUAAJG
 * aws_dynamodb_table.es_wotc_pay_period: 1 error(s) occurred:
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

This only started happening when we upgraded terraform from v0.8.8 to v0.10.7.  It seems to be that terraform is creating all the tables in parallel, not sequentially, or at least it's failing now where it used to work before.

### PR DESCRIPTION
**Pull request by bflad**
The AWS API is returning multiple, similar messages for DynamoDB throttling vs hitting the account limit. This "regression" was introduced in 130cdfe987a29a58b7ad4495dccdef236d64ce9e.

Closes #1776
Closes #2146

### CODE REVIEW

File: aws/resource_aws_dynamodb_table.go [hunk 1]
```diff
@@ -331,8 +331,11 @@ func resourceAwsDynamoDbTableCreate(d *schema.ResourceData, meta interface{}) er
 					time.Sleep(DYNAMODB_THROTTLE_SLEEP)
 					attemptCount += 1
 				case "LimitExceededException":
-					// If we're at resource capacity, error out without retry
-					if strings.Contains(awsErr.Message(), "Subscriber limit exceeded:") {
+					// If we're at resource capacity, error out without retry. e.g.
+					// Subscriber limit exceeded: There is a limit of 256 tables per subscriber
+					// Do not error out on this similar throttling message:
+					// Subscriber limit exceeded: Only 10 tables can be created, updated, or deleted simultaneously
+					if strings.Contains(awsErr.Message(), "Subscriber limit exceeded:") && !strings.Contains(awsErr.Message(), "simultaneously") {
```
Comment (radeksimko) [inline aws/resource_aws_dynamodb_table.go]: Do you mind tightening this a little bit, just to make sure we don't match an error we don't want to match? e.g. `can be created, updated, or deleted simultaneously`?

Comment (bflad) [reply aws/resource_aws_dynamodb_table.go]: Not a problem at all - will update shortly

Comment (bflad) [reply aws/resource_aws_dynamodb_table.go]: Not a problem at all - will update shortly

**Comment by bflad** [comment]
Updated message matching pushed. 👍
