### PR TITLE
r/spot_fleet_request - zero capacity update

### LINKED ISSUE #9322: Plan does not identify change in Capacity for SpotFleet request.
_This issue was originally opened by @udayanms as hashicorp/terraform#22050. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._
    
<hr>
    

### Terraform Version

```
...
```

### Terraform Configuration Files

```hcl
...vars.tfvars
```SpotFleetTargetCapacity  = "9"



   resource "aws_spot_fleet_request" "SymphonySpotFleet" {
   count = length(var.SpotFleetRequests)
   iam_fleet_role      = "${var.SpotFleetIamFleetRole}"
  #  spot_price          = "0.03"
   allocation_strategy = "diversified"
   target_capacity     = 2
   valid_until         = "2019-11-04T20:44:20Z"
   dynamic "launch_specification" {
     iterator = instanceType
     for_each = var.SpotFleetRequests[count.index].SpotFleetInstanceTypes
     content {
          instance_type            = instanceType.value
          ami                      = "${var.SpotFleetimageId}"
          key_name                 = "${var.SpotFleetKey}"
          spot_price               = "${var.SpotFleetPrice}"
          iam_instance_profile_arn = "${var.SpotFleetIamInstanceProfile}"
          subnet_id                = "${var.SpotFleetSubnetId}"
          weighted_capacity        = "${var.SpotFleetRequests[count.index].SpotFleetWeightedCapacity}"
          tags = var.SpotFleetInstanceTags
    }
   }
  }

Once the SpotFleet was created with SpotFleetTargetCapacity  = "4". I changed the value to 9 but re-running the plan and apply. Nothing changed. 




### Debug Output
<!--
Full debug output can be obtained by running Terraform with the environment variable `TF_LOG=trace`. Please create a GitHub Gist containing the debug output. Please do _not_ paste the debug output in the issue, since debug output is long.
No changes. Infrastructure is up-to-date.

Debug output may contain sensitive information. Please review it before posting publicly, and if you are concerned feel free to encrypt the files using the HashiCorp security public key.
-->

### Crash Output
<!--
If the console output indicates that Terraform crashed, please share a link to a GitHub Gist containing the output of the `crash.log` file.
-->

### Expected Behavior
<!--
What should have happened?
-->

### Actual Behavior
<!--
What actually happened?
-->
No changes. Infrastructure is up-to-date.

### Steps to Reproduce
<!--
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`
-->

### Additional Context
<!--
Are there anything atypical about your situation that we should know? For example: is Terraform running in a wrapper script or in a CI system? Are you passing any unusual command line options or environment variables to opt-in to non-default behavior?
-->

### References
<!--
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

- hashicorp/terraform#6017

-->

### LINKED ISSUE #12757: Changing the SpotFleet capacity to 0 returns an error (bug in the AWS provider)
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.12.24

### Affected Resource(s)

* aws_spot_fleet_request

### Terraform Configuration Files

```hcl
resource "aws_spot_fleet_request" "eks_spot_fleet" {
  iam_fleet_role                     = data.aws_iam_role.aws-ec2-spot-fleet-tagging-role.arn

  target_capacity                    = var.spotfleet_capacity
 
 replace_unhealthy_instances        = true
  excess_capacity_termination_policy = "Default"
  fleet_type                         = "maintain"
  allocation_strategy                = "diversified"
  valid_until                        = "2050-01-01T00:00:00Z"

  launch_specification {
    instance_type            = var.worker_instance_type
    ami                      = var.kuberenets_worker_image_id
    key_name                 = var.key_pair_name
    iam_instance_profile_arn = aws_iam_instance_profile.instance-profile.arn
    availability_zone        = data.aws_availability_zones.available.names[0]
    subnet_id                = aws_subnet.private-subnet_a.id
    vpc_security_group_ids   = [aws_security_group.worker-security-group.id]
    user_data                = base64encode(local.spotfleet-node-userdata)

    root_block_device {
      volume_size           = var.ebs_volume_size
      volume_type           = "gp2"
      delete_on_termination = true
    }

    tags = {
      "Name"                                      = "${var.cluster-name}-worker"
      "kubernetes.io/cluster/${var.cluster-name}" = "shared"
      "Cluster"                                   = var.cluster-name
      "SpotFleet"                                 = "true"
    }
  }
  }
```

### Debug Output

https://gist.github.com/Shalgo/75e16468971ee065cdafcbf95ea2fbef

### Expected Behavior

The capacity of the SpotFleet should be changed to 0 spots.
In AWS provider 2.51.0 it works.

### Actual Behavior

After changing the capacity to "0" I got this error:
```hcl
Error: error updating spot request (sfr-5a212ca5-c970-4beb-895c-93281ccd527b): InvalidParameterCombinationException: No attributes specified.
status code: 400, request id: bc707986-d852-4e66-b190-ca640ce42dd0
```
**In aws provider version 2.51.0 it works.**

### Steps to Reproduce

1. Specify the AWS provider to 2.57.0
2. Create a configuration of **maintain** spot fleet with some capacity >0 (like my example)
3. `terraform apply`
4. Change the Capacity to "0"
5. 'terraform apply'

### Important Factoids

none

### References

* #0000

### PR DESCRIPTION
**Pull request by DrFaust92**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #12757
Closes #9322  (possibly, as now there is a wait for modification to complete i have encountered a similar issue when working on this) 

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource_aws_spot_fleet_request: allow updating capacity to zero
resource_aws_spot_fleet_request: wait for modification to complete
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSSpotFleetRequest_zero_capacity'
--- PASS: TestAccAWSSpotFleetRequest_zero_capacity (452.08s)
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
Verified acceptance tests:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSSpotFleetRequest_zero_capacity'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -count 1 -parallel 20 -run=TestAccAWSSpotFleetRequest_zero_capacity -timeout 120m
=== RUN   TestAccAWSSpotFleetRequest_zero_capacity
=== PAUSE TestAccAWSSpotFleetRequest_zero_capacity
=== CONT  TestAccAWSSpotFleetRequest_zero_capacity
--- PASS: TestAccAWSSpotFleetRequest_zero_capacity (341.44s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	341.483s
```

**Comment by DrFaust92** [comment]
needs rebasing for import test

**Comment by ewbankkit** [comment]
```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSSpotFleetRequest_zero_capacity'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -count 1 -parallel 20 -run=TestAccAWSSpotFleetRequest_zero_capacity -timeout 120m
=== RUN   TestAccAWSSpotFleetRequest_zero_capacity
=== PAUSE TestAccAWSSpotFleetRequest_zero_capacity
=== CONT  TestAccAWSSpotFleetRequest_zero_capacity
panic: interface conversion: interface {} is nil, not string

goroutine 587 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.hashLaunchSpecification(0x59ad280, 0xc0014aa4b0, 0xc000000001)
	/home/kit/wrk/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_spot_fleet_request.go:1627 +0x6bf
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Set).hash(0xc000a25040, 0x59ad280, 0xc0014aa4b0, 0x434b2ac, 0x59ad280)
	/home/kit/wrk/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.9.0/helper/schema/set.go:221 +0x3d
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Set).add(0xc000a25040, 0x59ad280, 0xc0014aa4b0, 0xc000c8e000, 0x0, 0x0)
	/home/kit/wrk/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.9.0/helper/schema/set.go:198 +0x83
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Set).Add(...)
	/home/kit/wrk/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.9.0/helper/schema/set.go:75
github.com/terraform-providers/terraform-provider-aws/aws.launchSpecsToSet(0xc001c865f0, 0x1, 0x1, 0xc000470888, 0xc001701e20, 0x0, 0x0)
	/home/kit/wrk/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_spot_fleet_request.go:1275 +0x7b
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsSpotFleetRequestRead(0xc000839f80, 0x5ba81c0, 0xc000267900, 0x0, 0x0)
	/home/kit/wrk/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_spot_fleet_request.go:1192 +0x43f
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsSpotFleetRequestCreate(0xc000839f80, 0x5ba81c0, 0xc000267900, 0x2, 0xb11fca0)
	/home/kit/wrk/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_spot_fleet_request.go:1017 +0x1089
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0007ce120, 0xc000ef66e0, 0xc000eece40, 0x5ba81c0, 0xc000267900, 0xc0010ae201, 0xc00105cf30, 0xc0010ae308)
	/home/kit/wrk/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.9.0/helper/schema/resource.go:310 +0x365
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000110b80, 0xc000b879c8, 0xc000ef66e0, 0xc000eece40, 0xc001041948, 0xc00133b0f0, 0x59ad280)
	/home/kit/wrk/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.9.0/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00133bc10, 0x75a0f00, 0xc000ef43c0, 0xc000839a40, 0xc00133bc10, 0xc000ef43c0, 0xc000a7fb30)
	/home/kit/wrk/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.9.0/internal/helper/plugin/grpc_provider.go:885 +0x8b4
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x659fe40, 0xc00133bc10, 0x75a0f00, 0xc000ef43c0, 0xc000dbf7a0, 0x0, 0x75a0f00, 0xc000ef43c0, 0xc001028800, 0x79e)
	/home/kit/wrk/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.9.0/internal/tfplugin5/tfplugin5.pb.go:3305 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000f78f00, 0x75cd860, 0xc000f79080, 0xc0001ea600, 0xc000f85680, 0xb0da8a0, 0x0, 0x0, 0x0)
	/home/kit/wrk/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1024 +0x4f4
google.golang.org/grpc.(*Server).handleStream(0xc000f78f00, 0x75cd860, 0xc000f79080, 0xc0001ea600, 0x0)
	/home/kit/wrk/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1313 +0xd97
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000ecabd0, 0xc000f78f00, 0x75cd860, 0xc000f79080, 0xc0001ea600)
	/home/kit/wrk/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:722 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/kit/wrk/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:720 +0xa1
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	64.768s
FAIL
GNUmakefile:26: recipe for target 'testacc' failed
make: *** [testacc] Error 1
```

This happened in 2 regions I tested in.

**Comment by DrFaust92** [comment]
@ewbankkit. ill check it out but it seems unrelated to my change as its stemming from `hashLaunchSpecification`. can it be related to #13577 ? ill take a closer look

**Comment by ewbankkit** [comment]
@DrFaust92 Yes it does look related; I'll retest now you have rebased.

**Comment by ewbankkit** [comment]
Acceptance test passes now:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSSpotFleetRequest_zero_capacity'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSSpotFleetRequest_zero_capacity -timeout 120m
=== RUN   TestAccAWSSpotFleetRequest_zero_capacity
=== PAUSE TestAccAWSSpotFleetRequest_zero_capacity
=== CONT  TestAccAWSSpotFleetRequest_zero_capacity
--- PASS: TestAccAWSSpotFleetRequest_zero_capacity (384.21s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	384.261s
```

File: aws/resource_aws_spot_fleet_request_test.go [hunk 1]
```diff
@@ -2330,3 +2373,23 @@ resource "aws_spot_fleet_request" "test" {
 }
 `, rName, validUntil)
 }
+
+func testAccAWSSpotFleetRequestZeroCapacityConfig(rName string, rInt int, validUntil string) string {
+	return testAccAWSSpotFleetRequestConfigBase(rName, rInt) + fmt.Sprintf(`
+resource "aws_spot_fleet_request" "test" {
+    iam_fleet_role = "${aws_iam_role.test-role.arn}"
+    spot_price = "0.005"
```
Comment (ewbankkit) [inline aws/resource_aws_spot_fleet_request_test.go:2381]: See #14083, #13091; `0.005` is not a valid Gov Cloud value.

```suggestion
    spot_price = "0.05"
```

**Comment by DrFaust92** [comment]
Fixed!

**Comment by ewbankkit** [comment]
@DrFaust92 #13091 was just merged. Although no conflict is showing I think you will have to modify the call to `testAccAWSSpotFleetRequestConfig()` in your new acceptance test.
Could you please rebase and see if that is the case?
Thanks.

**Comment by DrFaust92** [comment]
rebased and tested

File: aws/resource_aws_spot_fleet_request_test.go [hunk 2]
```diff
@@ -2308,3 +2350,23 @@ resource "aws_spot_fleet_request" "test" {
 }
 `, rName, validUntil)
 }
+
+func testAccAWSSpotFleetRequestZeroCapacityConfig(rName string, validUntil string) string {
+	return testAccAWSSpotFleetRequestConfigBase(rName) + fmt.Sprintf(`
+resource "aws_spot_fleet_request" "test" {
+    iam_fleet_role = "${aws_iam_role.test.arn}"
+    spot_price = "0.005"
```
Comment (ewbankkit) [inline aws/resource_aws_spot_fleet_request_test.go:2358]: `spot_price` seems to have reverted.

```suggestion
    spot_price = "0.05"
```

**Comment by ewbankkit** [comment]
Re-verified in `us-west-2`:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSSpotFleetRequest_zero_capacity'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSSpotFleetRequest_zero_capacity -timeout 120m
=== RUN   TestAccAWSSpotFleetRequest_zero_capacity
=== PAUSE TestAccAWSSpotFleetRequest_zero_capacity
=== CONT  TestAccAWSSpotFleetRequest_zero_capacity
--- PASS: TestAccAWSSpotFleetRequest_zero_capacity (361.04s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	361.094s
```
