### PR TITLE
resource/aws_iam_user_group_membership: allow non-exclusive group memberships

### LINKED ISSUE #2881: State being written incorrectly for IAM group membership?
### Terraform Version
Terraform v0.11.1
+ provider.aws v1.6.0
+ provider.template v1.0.0

### Affected Resource(s)
aws_iam_group_membership

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
module "dev-user1" {
  "source" = "setup-users"
  "local_dev_group" = "${var.iam_dev_group}"
  "local_dev_username" = "user1"
}
module "dev-user2" {
  "source" = "setup-users"
  "local_dev_group" = "${var.iam_dev_group}"
  "local_dev_username" = "user2"
}

# In module setup-users

variable "dev_username" {}
variable "dev_group" {}

resource "aws_iam_user" "user" {
  name = "${var.dev_username}"
}

resource "aws_iam_group_membership" "group_membership" {
  name = "dev"
  users = ["${aws_iam_user.user.name}"]
  group = "${var.dev_group}"
}
```

### Debug Output
Unless this is absolutely necessary, can we skip this for now? Providing this would be difficult since the terraform config provided is sanitized, and I can't really run it without creating a bunch of bogus config in our AWS account.

### Panic Output
n/a

### Expected Behavior
Users get added to group once, and stay in group.

### Actual Behavior
If you run `terraform apply` several times in a row, the first time, it adds everyone to the group. Then (without changing any config), it removes everyone the second time you run terraform apply. Then, when you run it again, it adds everyone back.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform apply`

### Important Factoids
- Nothing special.

### References
None that I could find.

### PR DESCRIPTION
**Pull request by devonbleak**
Resolves #2881 - allows multiple aws_iam_group_memberships to co-exist peacefully by adding a new computed field `group_members` to manage adding/removing users.

Adds a `remove_unmanaged_members` property that can be set to true to restore previous functionality and documentation caveat about flapping with that setting.

### CODE REVIEW

File: aws/resource_aws_iam_group_membership.go [hunk 1]
```diff
@@ -35,6 +36,18 @@ func resourceAwsIamGroupMembership() *schema.Resource {
 				Required: true,
 				ForceNew: true,
 			},
+
+			"remove_unmanaged_members": &schema.Schema{
+				Type:     schema.TypeBool,
+				Optional: true,
+				Default:  false,
```
Comment (bflad) [inline aws/resource_aws_iam_group_membership.go]: This is a breaking change for the resource as written. It should default to `true` to keep backwards compatibility.

File: aws/resource_aws_iam_group_membership.go [hunk 2]
```diff
@@ -35,6 +36,18 @@ func resourceAwsIamGroupMembership() *schema.Resource {
 				Required: true,
 				ForceNew: true,
 			},
+
+			"remove_unmanaged_members": &schema.Schema{
```
Comment (bflad) [inline aws/resource_aws_iam_group_membership.go]: Minor nitpick: As of Go 1.7+, the `&schema.Schema` after the attribute name declarations are unnecessary

File: aws/resource_aws_iam_group_membership_test.go [hunk 3]
```diff
@@ -242,3 +324,14 @@ resource "aws_iam_user" "user" {
 }
 `, groupName, membershipName, userNamePrefix)
 }
+
+func testAccAWSGroupMemberAddUnmanagedUser(groupName string, userName string) func() {
```
Comment (bflad) [inline aws/resource_aws_iam_group_membership_test.go]: We should probably create a complimentary `testAccAWSGroupMemberRemoveManagedUser`

**Comment by devonbleak** [comment]
Thanks @bflad, this makes sense and I'll get the feedback incorporated.

**Comment by devonbleak** [comment]
@bflad thinking about this more, would it make sense to just create a new `aws_iam_user_group_membership` resource rather than having a single resource that may conflict with itself even with the changes to user vs users?

**Comment by devonbleak** [comment]
@bflad the more I think about having a 1:1 user-group membership resource the more it breaks down.  Consider the case where we have a list of users and a list of groups - there wouldn't be a way to add all the users to all the groups if the lengths of those lists has a common factor.  I'm going to go ahead with creating a new resource that will take a list of users and a single group and will be non-exclusive with group memberships.

**Comment by bflad** [comment]
@devonbleak sorry for my lack of reply earlier. Do you need any help?

Just to confirm the use case you're thinking about, it is something like this?

```hcl
variable "users" {
  default = [
    "a",
    "b",
  ]
}

variable "groups" {
  default = [
    "z",
    "y",
    "x",
  ]
}

resource "aws_iam_user" "example" {
  count = "${length(var.users)}"
  # ... other configuration ...
}

resource "aws_iam_group" "example" {
  count = "${length(var.groups)}"
  # ... other configuration ...
}

resource "aws_iam_user_group_membership" "example" {
  # yikes what would we put here? :)
}
```

What do you think about a `groups` attribute on `aws_iam_user` instead? The above becomes something like:

```hcl
variable "users" {
  default = [
    "a",
    "b",
  ]
}

variable "groups" {
  default = [
    "z",
    "y",
    "x",
  ]
}

resource "aws_iam_user" "example" {
  count = "${length(var.users)}"
  # ... other configuration ...
  # add user to all groups
  groups = ["${aws_iam_group.example.*.id}"]
}

resource "aws_iam_group" "example" {
  count = "${length(var.groups)}"
  # ... other configuration ...
}
```

**Comment by devonbleak** [comment]
@bflad The `aws_iam_user_group_membership` would basically work the same as `aws_iam_group_membership` except it wouldn't touch user memberships that were added outside of it (similar to how the original PR works here with `remove_unmanaged_users = false` but without requiring the extra logic in CustomizeDiff or the sidecar).  It would probably need a better name.

Adding a groups argument to `aws_iam_user` is an interesting solution but I think we'll still be missing a resource that just adds a list of users to a group and keeps them there without doing anything else (or vice versa adding a list of groups to a user).

**Comment by bflad** [comment]
@devonbleak I guess we have come full circle. 😄  Do you think you could implement this PR without the sidecar and defaulting the flag attribute to keep existing behavior (exclusive management)?

**Comment by devonbleak** [comment]
@bflad been thinking about this again the past couple days and thinking about implementing something like an `aws_iam_user_group_memberships` that would do the non-exclusive thing without the sidecar or the CustomizeDiff.  The analogy I have in my head is like `aws_iam_policy_attachment` vs `aws_iam_{group,role,user}_policy_attachment` - the former behaves like `aws_iam_group_membership` while the latter ignores things it doesn't know about.

My original implementation of this basically just ignored things it didn't know about in the `Read` function and worked great except that it took two applies for a change to `remove_unmanaged_users` to actually complete which is why I ended up going the sidecar/CustomizeDiff route.  It looks like we have what we need from the Go SDK in [ListGroupsForUser](https://docs.aws.amazon.com/sdk-for-go/api/service/iam/#IAM.ListGroupsForUser).

I'll start working on this approach, but let me know if you'd like to see something different.

```hcl
resource "aws_iam_user_group_memberships" "test" {
  user   = "${aws_iam_user.test.name}"
  groups = [
    "${aws_iam_group.test1.name}", 
    "${aws_iam_group.test2.name}"
  ]
}
```

**Comment by bflad** [comment]
I'd drop the `s` pluralization on the resource name, but sounds good.

**Comment by devonbleak** [comment]
@bflad implementation is done on resource/aws_iam_user_group_membership.  I also added a note to aws_iam_group_membership about the conflicts behavior so new users aren't caught by surprise with it.  Let me know if you'd like any additional changes!

File: aws/resource_aws_iam_user_group_membership_test.go [hunk 4]
```diff
@@ -0,0 +1,331 @@
...
+		PreCheck:     func() { testAccPreCheck(t) },
+		Providers:    testAccProviders,
+		CheckDestroy: testAccAWSUserGroupMembershipDestroy,
+		Steps: []resource.TestStep{
+			// simplest test
+			resource.TestStep{
+				Config: usersAndGroupsConfig + testAccAWSUserGroupMembershipConfigInit(membershipName),
+				Check: resource.ComposeTestCheckFunc(
+					resource.TestCheckResourceAttr("aws_iam_user_group_membership.user1_test1", "user", userName1),
+					testAccAWSUserGroupMembershipCheckGroupListForUser(userName1, []string{groupName1}, []string{groupName2, groupName3}),
```
Comment (bflad) [inline aws/resource_aws_iam_user_group_membership_test.go]: It'd probably be good to also test that `userName2` is not attached to anything 👍

**Comment by bflad** [comment]
This has been released in [version 1.17.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1170-may-02-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
