### PR TITLE
provider: Fix updated govet composites and nilness checks

### LINKED ISSUE #7992: Fix Updated govet Checks
## Description

`golangci-lint` has updated the `govet` tool, which is showing a few valid check failures, e.g.

```
aws/config_test.go:14:14: composites: `github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/aws-sdk-go-base.MockRequest` composite literal uses unkeyed fields (govet)
      Request: &awsbase.MockRequest{"POST", "/", "Action=DescribeAccountAttributes&" +
                ^
aws/config_test.go:16:15: composites: `github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/aws-sdk-go-base.MockResponse` composite literal uses unkeyed fields (govet)
      Response: &awsbase.MockResponse{200, test_ec2_describeAccountAttributes_response, "text/xml"},
                 ^
aws/resource_aws_db_instance.go:1549:10: nilness: impossible condition: nil != nil (govet)
    if err != nil {
           ^
aws/resource_aws_docdb_cluster_instance.go:461:10: nilness: impossible condition: nil != nil (govet)
    if err != nil {
           ^
aws/resource_aws_egress_only_internet_gateway.go:42:9: nilness: impossible condition: nil != nil (govet)
  if err != nil {
         ^
aws/resource_aws_emr_security_configuration_test.go:70:10: nilness: tautological condition: non-nil != nil (govet)
    if err != nil {
           ^
aws/resource_aws_gamelift_game_session_queue_test.go:60:9: nilness: impossible condition: nil != nil (govet)
  if err != nil {
         ^
aws/resource_aws_organizations_account_test.go:74:26: nilness: nil dereference in field selection (govet)
    if resp == nil && resp.Account != nil {
                           ^
aws/resource_aws_organizations_policy_test.go:108:26: nilness: nil dereference in field selection (govet)
    if resp == nil && resp.Policy != nil {
                           ^
aws/resource_aws_vpn_connection_test.go:229:11: nilness: tautological condition: non-nil != nil (govet)
      if err != nil {
             ^
aws/resource_aws_vpn_gateway_test.go:386:11: nilness: tautological condition: non-nil != nil (govet)
      if err != nil {
             ^
```

## Action Items

- [ ] Fix new `govet` failures
- [ ] Re-run broken TravisCI builds

### PR DESCRIPTION
**Pull request by bflad**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #7992

Output from acceptance testing (test failures unrelated):

```
--- PASS: TestAccAWSDBInstance_iamAuth (433.73s)
--- PASS: TestAccAWSDBInstance_generatedName (433.85s)
--- PASS: TestAccAWSDBInstance_kmsKey (472.91s)
--- PASS: TestAccAWSDBInstance_IsAlreadyBeingDeleted (474.40s)
--- PASS: TestAccAWSDBInstance_basic (504.75s)
--- PASS: TestAccAWSDBInstance_namePrefix (515.35s)
--- PASS: TestAccAWSDBInstance_DeletionProtection (519.84s)
--- PASS: TestAccAWSDBInstance_optionGroup (524.56s)
--- PASS: TestAccAWSDBInstance_FinalSnapshotIdentifier_SkipFinalSnapshot (615.45s)
--- PASS: TestAccAWSDBInstance_FinalSnapshotIdentifier (889.07s)
--- PASS: TestAccAWSDBInstance_subnetGroup (941.03s)
--- FAIL: TestAccAWSDBInstance_S3Import (670.42s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb (1325.20s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_AutoMinorVersionUpgrade (1335.22s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_IamDatabaseAuthenticationEnabled (1397.87s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_Monitoring (1427.89s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_BackupWindow (1467.48s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_MaintenanceWindow (1505.86s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_BackupRetentionPeriod (1597.63s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_AvailabilityZone (1620.53s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_AutoMinorVersionUpgrade (1070.32s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier (1230.49s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_VpcSecurityGroupIds (1306.43s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_AllocatedStorage (1788.44s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_AllocatedStorage (1331.92s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_AvailabilityZone (1041.75s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_Port (1516.69s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_Io1Storage (1562.85s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_ParameterGroupName (1655.35s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_BackupRetentionPeriod (1422.63s)
--- PASS: TestAccAWSDBInstance_enhancedMonitoring (668.86s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_IamDatabaseAuthenticationEnabled (1123.73s)
--- PASS: TestAccAWSDBInstance_portUpdate (532.58s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_MultiAZ (2112.96s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_BackupWindow (1260.79s)
--- PASS: TestAccAWSDBInstance_separate_iops_update (698.74s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_DeletionProtection (1337.11s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_MaintenanceWindow (1322.37s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_ParameterGroupName (1211.08s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_Monitoring (1406.51s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_Port (1190.56s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_Tags (1130.64s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_BackupRetentionPeriod_Unset (1703.38s)
--- PASS: TestAccAWSDBInstance_diffSuppressInitialState (452.04s)
--- PASS: TestAccAWSDBInstance_ec2Classic (429.38s)
--- PASS: TestAccAWSDBInstance_MinorVersion (462.68s)
--- PASS: TestAccAWSEgressOnlyInternetGateway_basic (9.07s)
--- PASS: TestAccAWSEmrSecurityConfiguration_basic (11.70s)
--- PASS: TestAccAWSEmrSecurityConfiguration_importBasic (15.62s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_VpcSecurityGroupIds (1223.74s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_VpcSecurityGroupIds_Tags (1232.99s)
--- PASS: TestAccAWSVpnGateway_disappears (22.85s)
--- PASS: TestAccAWSVpnConnection_disappears (159.00s)
--- FAIL: TestAccAWSDBInstance_cloudwatchLogsExportConfigurationUpdate (560.67s)
--- PASS: TestAccAWSDBInstance_cloudwatchLogsExportConfiguration (700.56s)
--- PASS: TestAccAWSDBInstance_EnabledCloudwatchLogsExports_Oracle (745.47s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_MultiAZ (1935.89s)
--- PASS: TestAccAWSDBInstance_EnabledCloudwatchLogsExports_Postgresql (766.60s)
--- PASS: TestAccAWSDocDBClusterInstance_namePrefix (649.47s)
--- PASS: TestAccAWSDocDBClusterInstance_generatedName (659.47s)
--- PASS: TestAccAWSDocDBClusterInstance_az (676.29s)
--- PASS: TestAccAWSDocDBClusterInstance_kmsKey (694.98s)
--- PASS: TestAccAWSDocDBClusterInstance_disappears (640.17s)
--- PASS: TestAccAWSDBInstance_MSSQL_TZ (1792.55s)
--- PASS: TestAccAWSDocDBClusterInstance_basic (1339.75s)
--- PASS: TestAccAWSDBInstance_MySQL_SnapshotRestoreWithEngineVersion (2067.04s)
--- PASS: TestAccAWSDBInstance_MSSQL_DomainSnapshotRestore (3150.09s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_MultiAZ_SQLServer (4083.21s)
--- PASS: TestAccAWSDBInstance_MSSQL_Domain (3593.05s)
```

### CODE REVIEW

File: aws/resource_aws_gamelift_game_session_queue_test.go [hunk 1]
```diff
@@ -57,14 +58,6 @@ func testSweepGameliftGameSessionQueue(region string) error {
 		}
 	}
 
-	if err != nil {
```
Comment (bflad) [inline aws/resource_aws_gamelift_game_session_queue_test.go]: Removing duplicate logic.

File: aws/resource_aws_vpn_connection_test.go [hunk 2]
```diff
@@ -222,13 +222,9 @@ func testAccAWSVpnConnectionDisappears(connection *ec2.VpnConnection) resource.T
 		_, err := conn.DeleteVpnConnection(&ec2.DeleteVpnConnectionInput{
 			VpnConnectionId: connection.VpnConnectionId,
 		})
+
 		if err != nil {
-			if ec2err, ok := err.(awserr.Error); ok && ec2err.Code() == "InvalidVpnConnectionID.NotFound" {
```
Comment (bflad) [inline aws/resource_aws_vpn_connection_test.go]: The acceptance test should fail if this error is returned here.

File: aws/resource_aws_vpn_gateway_test.go [hunk 3]
```diff
@@ -374,18 +374,7 @@ func testAccAWSVpnGatewayDisappears(gateway *ec2.VpnGateway) resource.TestCheckF
 			VpcId:        gateway.VpcAttachments[0].VpcId,
 		})
 		if err != nil {
-			ec2err, ok := err.(awserr.Error)
-			if ok {
-				if ec2err.Code() == "InvalidVpnGatewayID.NotFound" {
```
Comment (bflad) [inline aws/resource_aws_vpn_gateway_test.go]: The acceptance test should fail if either of these errors are returned here.

File: .travis.yml [hunk 4]
```diff
@@ -1,34 +1,33 @@
-dist: trusty
+dist: xenial
```
Comment (bflad) [inline .travis.yml]: This was updated to see if it helped with the memory issue since TravisCI does not start services by default on the newer OS. It didn't make the memory issue disappear, but the update is helpful anyways.

File: .golangci.yml [hunk 5]
```diff
@@ -11,7 +11,6 @@ linters:
     - gosimple
     - ineffassign
     - misspell
-    - staticcheck
```
Comment (bflad) [inline .golangci.yml]: Temporary for now to fix out of memory issue. We can consider adding a separate TravisCI matrix job, running staticcheck by itself, or waiting for `staticcheck` 2019.1.1 support in `golangci-lint`:
* https://github.com/golangci/golangci-lint/pull/445
* https://github.com/dominikh/go-tools/releases/tag/2019.1.1

File: aws/resource_aws_emr_security_configuration_test.go [hunk 6]
```diff
@@ -58,21 +58,20 @@ func testAccCheckEmrSecurityConfigurationDestroy(s *terraform.State) error {
 		resp, err := conn.DescribeSecurityConfiguration(&emr.DescribeSecurityConfigurationInput{
 			Name: aws.String(rs.Primary.ID),
 		})
-		if err == nil {
```
Comment (bflad) [inline aws/resource_aws_emr_security_configuration_test.go]: Invert logic here to match preferred style across codebase of error checking first.

File: .golangci.yml (hunk 5 above)
Comment (bflad) [reply .golangci.yml]: Here's the memory usage difference locally for me:

```
# golangci-lint on master
6227824640  maximum resident set size
# golangci-lint 1.15.0
5142007808  maximum resident set size
```

We should also watch: https://github.com/dominikh/go-tools/issues/419

Comment (jirfag) [reply .golangci.yml]: Hi! https://github.com/golangci/golangci-lint/pull/445 was merged. Also, I've added [the section](https://github.com/golangci/golangci-lint#memory-usage-of-golangci-lint) about memory usage into README. You can try to set `GOGC=30` for example to trade memory for CPU.

Comment (bflad) [reply .golangci.yml]: Thanks so much @jirfag 😄 This should be a huge help for us.
