### PR TITLE
resource_aws_kinesis_firehose_delivery_stream: Avoid invalid state on refresh (cont.)

### LINKED ISSUE #4392: Incorrect reporting of processing_configuration using AWS Provider 1.16.0
Hi

We have an AWS firehose that uses elasticsearch as an endpoint under terraform with AWS provider 1.10.0 that does *not* use transformation:
```
resource "aws_kinesis_firehose_delivery_stream" "agevents-es-stream" {
  name        = "agevents-es"
  destination = "elasticsearch"

  s3_configuration {
    role_arn           = "${aws_iam_role.agevents-firehose-role.arn}"
    bucket_arn         = "${aws_s3_bucket.agevents-bucket.arn}"
    buffer_size        = 5
    buffer_interval    = 60
    compression_format = "GZIP"
  }

  elasticsearch_configuration {
    domain_arn     = "${aws_elasticsearch_domain.events.arn}"
    role_arn       = "${aws_iam_role.agevents-firehose-role.arn}"
    index_name     = "${aws_elasticsearch_domain.events.domain_name}"
    type_name      = "event"
    s3_backup_mode = "AllDocuments"
  }
}
```
Last week we upgraded the AWS Provider to 1.16.0 in order to use lambda transformations in a new firehose with redshift as the endpoint.  
Since doing this, running `plan` always returns:
elasticsearch_configuration.0.processing_configuration.#: "1" => "0"
for the original firehose.
If I apply the change and run plan again, it gives the same change it wants to make.

### Terraform Version
0.11.7

### Affected Resource(s)
elasticsearch_configuration.0.processing_configuration.#

### Debug Output
no errors thrown

### Panic Output
no panic

### Expected Behavior
a) Running plan should not have seen that elasticsearch_configuration.0.processing_configuration.# was 1 as there was never any transformation included in the spec. 
b) After applying the change I would expect not to see it surfaced again by running plan.

### Actual Behavior
terraform indicated there was a processing_configuration when there wasn't and seems not to have updated it's state on applying the change and still sees empty config as containing a processing config.

### Steps to Reproduce
import a pre-existing pipeline with no transformation into terraform using AWS provider 1.10.0.  Upgrade provider to 1.16.0.
Run plan
See the above indicated.
Run apply
Run plan
See the above still indicated

### LINKED ISSUE #6053: aws_kinesis_firehose_delivery_stream can become permanently dirty
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.7
+ provider.aws v1.34.0
+ provider.template v1.0.0
```

### Affected Resource(s)

* aws_kinesis_firehose_delivery_stream

### Terraform Configuration Files

```hcl
resource "aws_kinesis_firehose_delivery_stream" "logs" {
  name        = "${aws_s3_bucket.logs.bucket}-firehose"
  destination = "extended_s3"

  kinesis_source_configuration {
    kinesis_stream_arn = "${aws_kinesis_stream.cloudwatch-logs.arn}"
    role_arn = "${aws_iam_role.firehose_role.arn}"
  }

  extended_s3_configuration {
    role_arn = "${aws_iam_role.firehose_role.arn}"
    bucket_arn = "${aws_s3_bucket.logs.arn}"
    buffer_size        = 30
    buffer_interval    = 900 # we prefer high interval (fewer files); 900 seconds is the max allowed
    compression_format = "GZIP"

    processing_configuration = [
      {
        enabled = "true"
        processors = [
          {
            type = "Lambda"
            parameters = [
              {
                parameter_name = "LambdaArn"
                parameter_value = "${aws_lambda_function.kinesis-cloudwatch-newline.arn}"
              }
            ]
          }
        ]
      }
    ]

    cloudwatch_logging_options {
      enabled = true
      log_group_name = "${aws_cloudwatch_log_group.logs-firehose-logs.name}"
      log_stream_name = "S3Delivery"
    }
  }
}
```

### Debug Output

Too long to anonymize. Will try to provide if absolutely required.

### Expected Behavior

Terraform should converge the stack such that when `plan` is run immediately after `apply` there should be no changes necessary.

### Actual Behavior

Once the Firehose delivery stream is "dirty" there is no way to mark it as clean again in Terraform, short of actually deleting and re-creating the Firehose delivery stream. This is what it looks like when dirty:

```
  ~ aws_kinesis_firehose_delivery_stream.logs
      extended_s3_configuration.0.data_format_conversion_configuration.#:         "1" => "0"
      extended_s3_configuration.0.data_format_conversion_configuration.0.enabled: "false" => "true"
```

### Steps to Reproduce

1. Define a new `aws_kinesis_firehose_delivery_stream` in Terraform
2. `terraform apply`
3. Change one of the firehose settings in AWS Console (eg. set buffer time to 90 seconds)
4. [optional] Use AWS Console to revert settings. (doesn't matter either way)
5. `terraform apply`
6. `terraform plan` will be dirty, despite the fact that `apply` was just run

### LINKED ISSUE #8982: Error on plan refreshing firehose state: insufficient items for attribute output_format_configuration
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.1
+ provider.aws v2.14.0
```

### Affected Resource(s)

* aws_kinesis_firehose_delivery_stream

### Terraform Configuration Files

```hcl
resource "aws_kinesis_firehose_delivery_stream" "brandslangen" {
  name        = "brandslangen"
  destination = "extended_s3"

  extended_s3_configuration {
    role_arn   = "${aws_iam_role.rollen.arn}"
    bucket_arn = "${aws_s3_bucket.hinken.arn}"
  }
}

resource "aws_s3_bucket" "hinken" {
  bucket = "hinken.supercorp.io"
}

resource "aws_iam_role" "rollen" {
  name               = "rollen"
  assume_role_policy = "${data.aws_iam_policy_document.rollen_trust.json}"
}

data "aws_iam_policy_document" "rollen_trust" {
  statement {
    principals {
      type        = "Service"
      identifiers = ["firehose.amazonaws.com"]
    }

    actions = [
      "sts:AssumeRole",
    ]
  }
}
```

#### Full log

https://gist.github.com/staffan-einarsson/c7394b5fc331ffc7ff08f2f8ae48d5ca

#### Error lines

```
2019/06/13 08:46:04 [DEBUG] ReferenceTransformer: "aws_kinesis_firehose_delivery_stream.brandslangen" references: []
2019/06/13 08:46:04 [TRACE] Completed graph transform *terraform.ReferenceTransformer (no changes)
2019/06/13 08:46:04 [TRACE] Executing graph transform *terraform.RootTransformer
2019/06/13 08:46:04 [TRACE] Completed graph transform *terraform.RootTransformer (no changes)
2019/06/13 08:46:04 [TRACE] vertex "aws_kinesis_firehose_delivery_stream.brandslangen": entering dynamic subgraph
2019/06/13 08:46:04 [TRACE] dag/walk: updating graph
2019/06/13 08:46:04 [ERROR] <root>: eval: *terraform.EvalReadState, err: insufficient items for attribute "output_format_configuration"; must have at least 1
2019/06/13 08:46:04 [ERROR] <root>: eval: *terraform.EvalSequence, err: insufficient items for attribute "output_format_configuration"; must have at least 1
2019/06/13 08:46:04 [TRACE] [walkRefresh] Exiting eval tree: aws_kinesis_firehose_delivery_stream.brandslangen
2019/06/13 08:46:04 [TRACE] vertex "aws_kinesis_firehose_delivery_stream.brandslangen": visit complete
2019/06/13 08:46:04 [TRACE] vertex "aws_kinesis_firehose_delivery_stream.brandslangen": dynamic subgraph encountered errors
```

### Expected Behavior

No errors. In-memory state should be refreshed and plan should be shown.

### Actual Behavior

In-memory state refresh produces error.

```
Error: insufficient items for attribute "output_format_configuration"; must have at least 1
```

### Steps to Reproduce

Assuming an empty initial terraform state and the configuration file shown above. For actual logs and state see https://gist.github.com/staffan-einarsson/c7394b5fc331ffc7ff08f2f8ae48d5ca.

1. `terraform apply` to create the firehose, bucket and role, and produce the terraform state shown in `before_manual_touch.tfstate`.
2. (Optional) `aws firehose describe-delivery-stream --delivery-stream-name brandslangen` to print AWS description of the firehose, shown in `describe_api_call_before_manual_touch.log`.
3. Open AWS Console and navigate to the firehose `brandslangen`.
4. Click on the Edit button, then immediately on the Save button, without making any changes.
5. (Optional) `aws firehose describe-delivery-stream --delivery-stream-name brandslangen` to print AWS description of the firehose, shown in `describe_api_call_after_manual_touch.log`.
6. (Optional) `terraform refresh` to refresh the state file, shown in `after_manual_touch.tfstate`.
7. `terraform plan` which will fail to parse the terraform state.

### Additional details

Diffing `describe_api_call_before_manual_touch.log` and `describe_api_call_after_manual_touch.log` shows that during the manual modification AWS has added some attributes to the firehose configuration, even though it means the same thing.

```
10c10
<         "VersionId": "1",
---
>         "VersionId": "2",
11a12
>         "LastUpdateTimestamp": 1560407082.658,
18a20
>                     "ErrorOutputPrefix": "",
34a37
>                     "ErrorOutputPrefix": "",
46c49,56
<                     "S3BackupMode": "Disabled"
---
>                     "ProcessingConfiguration": {
>                         "Enabled": false,
>                         "Processors": []
>                     },
>                     "S3BackupMode": "Disabled",
>                     "DataFormatConversionConfiguration": {
>                         "Enabled": false
>                     }
```

Diffing `before_manual_touch.tfstate` and `after_manual_touch.tfstate` shows that terraform does not interpret these configurations as equivalent, but instead records state that in some cases would lead to unintended state diffs, and in this case even produces corrupt state (`input_format_configuration`, `output_format_configuration` and `schema_configuration` are required attributes that can not be empty).

```
4c4
<   "serial": 21,
---
>   "serial": 22,
69c69
<             "tags": null,
---
>             "tags": {},
104c104,111
<                 "data_format_conversion_configuration": [],
---
>                 "data_format_conversion_configuration": [
>                   {
>                     "enabled": false,
>                     "input_format_configuration": [],
>                     "output_format_configuration": [],
>                     "schema_configuration": []
>                   }
>                 ],
108c115,120
<                 "processing_configuration": [],
---
>                 "processing_configuration": [
>                   {
>                     "enabled": false,
>                     "processors": []
>                   }
>                 ],
120,121c132,133
<             "tags": null,
<             "version_id": "1"
---
>             "tags": {},
>             "version_id": "2"
158c170
<             "tags": null,
---
>             "tags": {},
```

Here we can also see the same thing happening with `processors` in `processing_configuration`, which seems to be what #4392 is about.

### References

* Very likely related to #6053 and #4392

### PR DESCRIPTION
**Pull request by staffan-einarsson**
Continued from #9016 due to a mess up on my part.

When refreshing the state of a aws_kinesis_firehose_delivery_stream
resource, the AWS SDK may have more that one way to describe the same
configuration. In the case of ProcessingConfiguration, this can lead to
perpetual diffs and for DataFormatConversionConfiguration it can lead to
invalid state that causes later refresh and plan operations to crash.

We have solved these two situations here by detecting the alternative
representation of the "disabled" configuration, and disambiguated the
terraform state data.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Fixes #8982
Fixes #6053 
Fixes #4392

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_kinesis_firehose_delivery_stream: After manual edit in AWS console, refresh no longer causes invalid state file.
```

### CODE REVIEW

**Comment by mattk42** [comment]
Any word on if this will get merged?

File: aws/resource_aws_kinesis_firehose_delivery_stream.go [hunk 1]
```diff
@@ -328,11 +328,25 @@ func flattenFirehoseDataFormatConversionConfiguration(dfcc *firehose.DataFormatC
...
+	enabled := aws.BoolValue(dfcc.Enabled)
+	ifc := flattenFirehoseInputFormatConfiguration(dfcc.InputFormatConfiguration)
+	ofc := flattenFirehoseOutputFormatConfiguration(dfcc.OutputFormatConfiguration)
+	sc := flattenFirehoseSchemaConfiguration(dfcc.SchemaConfiguration)
+
+	// The AWS SDK can represent "no data format conversion configuration" in two ways:
+	// 1. With a nil value
+	// 2. With enabled set to false and nil for ALL the config sections.
+	// These two cases are equivalent so we use the same state description, to avoid diffs.
+	if !enabled && len(ifc) == 0 && len(ofc) == 0 && len(sc) == 0 {
```
Comment (bflad) [inline aws/resource_aws_kinesis_firehose_delivery_stream.go]: After various testing and investigation, even though we prefer to not introduce logic like this since it changes the behavior of the configuration when its returned from the API, this seems to be one of the few options we have for now since the configuration block `enabled` attribute has `Default: true`. 👍

File: aws/resource_aws_kinesis_firehose_delivery_stream.go [hunk 2]
```diff
@@ -328,11 +328,25 @@ func flattenFirehoseDataFormatConversionConfiguration(dfcc *firehose.DataFormatC
...
+		log.Printf("Found ambiguous AWS response")
```
Comment (bflad) [inline aws/resource_aws_kinesis_firehose_delivery_stream.go]: Extraneous log line can be removed

File: aws/resource_aws_kinesis_firehose_delivery_stream.go [hunk 3]
```diff
@@ -531,6 +545,16 @@ func flattenProcessingConfiguration(pc *firehose.ProcessingConfiguration, roleAr
 		return []map[string]interface{}{}
 	}
 
+	enabled := aws.BoolValue(pc.Enabled)
+
+	// The AWS SDK can represent "no processing configuration" in two ways:
+	// 1. With a nil value
+	// 2. With an empty processor list and enabled set to false.
+	// These are equivalent so we use the same state description, to avoid diffs.
+	if !enabled && len(pc.Processors) == 0 {
```
Comment (bflad) [inline aws/resource_aws_kinesis_firehose_delivery_stream.go]: Typically, if the configuration block contains a nested "enabled" or similar attribute that we appropriately handle the default case, we prefer to actually pass through the API response into the state as-is (e.g. 1 list item and enabled = false) and then introduce `DiffSuppressFunc: suppressMissingOptionalConfigurationBlock,` on the configuration block attribute. This means the Terraform resource can accept a configuration with `enabled = false` and no processors without showing a difference, while also ignoring the configuration block if all the underlying attribute defaults match. 

This change was good to revert back to how it was. If for some reason this does need to be changed, we should add a covering acceptance test to show the errant behavior in a future change request. 👍

File: aws/resource_aws_kinesis_firehose_delivery_stream.go [hunk 4]
```diff
@@ -1402,8 +1426,12 @@ func createExtendedS3Config(d *schema.ResourceData) *firehose.ExtendedS3Destinat
 		configuration.CloudWatchLoggingOptions = extractCloudWatchLoggingConfiguration(s3)
 	}
 
-	if v, ok := s3["error_output_prefix"]; ok && v.(string) != "" {
+	if v, ok := s3["error_output_prefix"]; ok {
 		configuration.ErrorOutputPrefix = aws.String(v.(string))
+	} else {
+		// It is possible to just pass nil here, but this seems to be the
```
Comment (bflad) [inline aws/resource_aws_kinesis_firehose_delivery_stream.go]: We haven't found an AWS API that has required this additional logic so we would prefer to leave this in its original form. If there is some errant behavior with the original logic, let's add a covering acceptance test to show the errant behavior in a future change request. 👍

File: aws/resource_aws_kinesis_firehose_delivery_stream.go [hunk 5]
```diff
@@ -1487,8 +1515,12 @@ func updateExtendedS3Config(d *schema.ResourceData) *firehose.ExtendedS3Destinat
...
```
Comment (bflad) [inline aws/resource_aws_kinesis_firehose_delivery_stream.go]: Same here. 👍

File: aws/resource_aws_kinesis_firehose_delivery_stream_test.go [hunk 6]
```diff
@@ -339,6 +339,60 @@ func TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3_DataFormatConversionConf
 	})
 }
 
+func TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3_ExternalUpdate(t *testing.T) {
```
Comment (bflad) [inline aws/resource_aws_kinesis_firehose_delivery_stream_test.go]: Thank you very much for adding this acceptance test! 💯

File: aws/resource_aws_kinesis_firehose_delivery_stream.go [hunk 7]
```diff
@@ -1501,7 +1533,11 @@ func updateExtendedS3Config(d *schema.ResourceData) *firehose.ExtendedS3Destinat
 
 func expandFirehoseDataFormatConversionConfiguration(l []interface{}) *firehose.DataFormatConversionConfiguration {
 	if len(l) == 0 || l[0] == nil {
-		return nil
+		// It is possible to just pass nil here, but this seems to be the
```
Comment (bflad) [inline aws/resource_aws_kinesis_firehose_delivery_stream.go]: We typically do not need to normalize information when sending requests to the API. This doesn't appear to hurt anything here though, so will leave this in for now.
