### PR TITLE
resource/aws_security_group_rule: Prevent sg rule recreation when source_security_group_id has accountId prefix

### LINKED ISSUE #159: aws_security_group_rule doesn't seem to support security groups from multiple aws accounts.
_This issue was originally opened by @rayzorinc as hashicorp/terraform#6571. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version

```
terraform --version
Terraform v0.6.15
```
### Affected Resource(s)

Please list the resources as a list, for example:
- aws_security_group_rule
- aws_security_group
### Terraform Configuration Files

```
resource "aws_security_group" "default" {
    name        = "default-group"
    vpc_id      = "${aws_vpc.vpc.id}"
}
resource "aws_security_group" "internal" {
    name        = "internal-access"
    vpc_id      = "${aws_vpc.vpc.id}"
}

resource "aws_security_group_rule" "port443" {
     type  = "ingress"
     from_port = 443
     to_port = 443
     protocol = "tcp"
     security_group_id = "${aws_security_group.internal.id}"
     source_security_group_id = "${aws_security_group.default.id}"
}

resource "aws_security_group_rule" "peer_access" {
     type  = "ingress"
     from_port = 443
     to_port = 443
     protocol = "tcp"
     security_group_id = "${aws_security_group.internal.id}"
     source_security_group_id = "123456789012/sg-12345678"
}
```
### Expected Behavior

After running `terraform apply`, and it successfully ran, there should be no more infrastructure changes when running `terraform plan`
### Actual Behavior

Running `terraform plan` keeps showing `aws_security_group_rule.peer_access` needs to be added.
output is:

```
-/+ module.network.aws_security_group_rule.peer_access
    from_port:                "443" => "443"
    protocol:                 "tcp" => "tcp"
    security_group_id:        "sg-12345678" => "sg-12345678"
    self:                     "false" => "0"
    source_security_group_id: "sg-12345678" => "123456789012/sg-12345678" (forces new resource)
    to_port:                  "443" => "443"
    type:                     "ingress" => "ingress"
```
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform plan`
### Important Factoids

This errors only when we're trying to allow access from different aws accounts that are vpc peered to each other.

In the `terraform.tfstate` file, I see it stores it without the other aws account number and just the security group id.

```
                "aws_security_group_rule.peer_access": {
                    "type": "aws_security_group_rule",
                    "depends_on": [
                        "aws_security_group.internal"
                    ],
                    "primary": {
                        "id": "sgrule-261220255",
                        "attributes": {
                            "cidr_blocks.#": "0",
                            "from_port": "443",
                            "id": "sgrule-261220255",
                            "protocol": "tcp",
                            "security_group_id": "sg-12345678",
                            "self": "false",
                            "source_security_group_id": "sg-12345678",
                            "to_port": "443",
                            "type": "ingress"
                        },
                        "meta": {
                            "schema_version": "2"
                        }
                    }
                },
```

### PR DESCRIPTION
**Pull request by ktham**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #159 and #141

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_security_group_rule: Prevent sg rule recreation when source_security_group_id has accountId prefix
```

Output from acceptance testing (with code change):

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSSecurityGroupRule_Ingress_Source_With_Account_Id'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSSecurityGroupRule_Ingress_Source_With_Account_Id -timeout 120m
=== RUN   TestAccAWSSecurityGroupRule_Ingress_Source_With_Account_Id
=== PAUSE TestAccAWSSecurityGroupRule_Ingress_Source_With_Account_Id
=== CONT  TestAccAWSSecurityGroupRule_Ingress_Source_With_Account_Id
--- PASS: TestAccAWSSecurityGroupRule_Ingress_Source_With_Account_Id (42.54s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	45.092s
```

Output from acceptance test prior to code change, which reproduces #159/#141 (account id is redacted in the output):
```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSSecurityGroupRule_Ingress_Source_With_Account_Id'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSSecurityGroupRule_Ingress_Source_With_Account_Id -timeout 120m
=== RUN   TestAccAWSSecurityGroupRule_Ingress_Source_With_Account_Id
=== PAUSE TestAccAWSSecurityGroupRule_Ingress_Source_With_Account_Id
=== CONT  TestAccAWSSecurityGroupRule_Ingress_Source_With_Account_Id
--- FAIL: TestAccAWSSecurityGroupRule_Ingress_Source_With_Account_Id (30.98s)
    testing.go:640: Step 0 error: After applying this step and refreshing, the plan was not empty:

        DIFF:

        DESTROY/CREATE: aws_security_group_rule.allow_self
          cidr_blocks.#:            "0" => ""
          description:              "" => ""
          from_port:                "0" => "0"
          id:                       "sgrule-2081816794" => "<computed>"
          ipv6_cidr_blocks.#:       "0" => ""
          prefix_list_ids.#:        "0" => ""
          protocol:                 "-1" => "-1"
          security_group_id:        "sg-0752efed0ad3f0d34" => "sg-0752efed0ad3f0d34"
          self:                     "false" => "false"
          source_security_group_id: "sg-0752efed0ad3f0d34" => "[REDACTED]/sg-0752efed0ad3f0d34" (forces new resource)
          to_port:                  "0" => "0"
          type:                     "ingress" => "ingress"
```

### CODE REVIEW

**Comment by ketzacoatl** [comment]
Is there an easy way for someone to plug this update into a stack for testing?

I have only used upstream/stable/released versions of Terraform and it's providers, but I'd be happy to assist with testing if that's useful.

**Comment by ktham** [comment]
> Is there an easy way for someone to plug this update into a stack for testing?

What you can do, is make a local build of the provider using my branch and place it in your local terraform plugins directory at `YOUR_WORKSPACE_DIR/.terraform.d/plugins/linux_amd64/terraform-provider-aws_vX.Y.Z` (or `YOUR_WORKSPACE_DIR/.terraform.d/plugins/darwin_amd64/terraform-provider-aws_vX.Y.Z` for Macs)

Instructions for making a local build is here: https://github.com/terraform-providers/terraform-provider-aws#developing-the-provider

**Comment by ktham** [comment]
Sorry to mention you @bflad - since I saw you participated in the referenced issues - would it be possible for you to take a quick look at this PR and share what you think? Hopefully this is small enough such that it doesn't take too much of your time

We've been experiencing slight downtime each time we apply Terraform because of this issue and am hoping in the next provider release that it can be addressed.

File: aws/resource_aws_security_group_rule.go [hunk 1]
```diff
@@ -759,7 +759,19 @@ func setFromIPPerm(d *schema.ResourceData, sg *ec2.SecurityGroup, rule *ec2.IpPe
 		s := rule.UserIdGroupPairs[0]
 
 		if isVPC {
-			d.Set("source_security_group_id", s.GroupId)
+			if existingSourceSgId, ok := d.GetOk("source_security_group_id"); ok {
```
Comment (anGie44) [inline aws/resource_aws_security_group_rule.go:762]: looks good 👍 
as an alternative, you could even use the value of the `s.UserId` to handle the if/else as it'll be an empty string for security groups not tied to a specific accountId prefix
```suggestion
			if userId := aws.StringValue(s.UserId); len(userId) > 0 {
				d.Set("source_security_group_id", fmt.Sprintf("%s/%s", userId, aws.StringValue(s.GroupId)))
			} else {
				d.Set("source_security_group_id", s.GroupId)
			}
```

Comment (ktham) [reply aws/resource_aws_security_group_rule.go:762]: Thanks for the review!

> as it'll be an empty string for security groups not tied to a specific accountId prefix

I believe that is not true. I believe `s.UserId` always has a value defined as the AWS API always returns a value for it whether or not we have a accoundId prefix or not in `source_security_group_id`

Comment (bflad) [reply aws/resource_aws_security_group_rule.go:762]: 😅 Using `d.Get()` or `d.GetOk()` to influence `d.Set()` calls is _generally_ discouraged since there are different semantics between resources created versus imported, however in this case, we don't have any options other than maybe #4454 (a `DiffSuppressFunc`) since the API seems to be very ambiguous about how it requires canonicalization. I'm hesitantly thinking this change to base the decision of `d.Set()` value is fine in principle since it should keep the existing resource behavior for previous configurations.

File: aws/resource_aws_security_group_rule.go [hunk 2]
```diff
@@ -759,7 +759,19 @@ func setFromIPPerm(d *schema.ResourceData, sg *ec2.SecurityGroup, rule *ec2.IpPe
...
+				sgIdComponents := strings.Split(existingSourceSgId.(string), "/")
+				hasAccountIdPrefix := len(sgIdComponents) == 2
+
+				if hasAccountIdPrefix {
+					// then ensure on refresh that we prefix the account id
+					d.Set("source_security_group_id", *s.UserId+"/"+*s.GroupId)
```
Comment (bflad) [inline aws/resource_aws_security_group_rule.go:768]: To prevent potential panics (as recommended above), we should use the AWS Go SDK conversion functions, in case the new requirement of `s.UserId` does happen to be `nil` in some environments:

```suggestion
					d.Set("source_security_group_id", fmt.Sprintf("%s/%s", aws.StringValue(s.UserId), aws.StringValue(s.GroupId))
```

File: aws/resource_aws_security_group_rule_test.go [hunk 3]
```diff
@@ -154,6 +154,32 @@ func TestAccAWSSecurityGroupRule_Ingress_VPC(t *testing.T) {
...
+				Check: resource.ComposeTestCheckFunc(
+					testAccCheckAWSSecurityGroupRuleExists("aws_security_group.web", &group),
+				),
+			},
+			// Ensure plan shows no difference after state is refreshed
+			{
+				Config:             testAccAWSSecurityGroupRule_Ingress_Source_with_AccountId(rInt),
+				PlanOnly:           true,
+				ExpectNonEmptyPlan: false,
+			},
```
Comment (bflad) [inline aws/resource_aws_security_group_rule_test.go:178]: This is extraneous as the acceptance testing framework automatically checks a refresh plan for differences after applying a `Config` 👍 

```suggestion
```

**Comment by ktham** [comment]
Thanks @bflad ! I've updated the PR

**Comment by jnonino** [comment]
Hi, I'm using version 2.65 of the AWS provider and the issue still present.

```
10:37:22  * provider.aws: version = "~> 2.65"
10:37:22  * provider.random: version = "~> 2.2"
10:37:22  * provider.template: version = "~> 2.1"
```

```
10:37:33    # module.<MY_MODULE>.aws_security_group_rule.<MY_RULE>[1] must be replaced
10:37:33  -/+ resource "aws_security_group_rule" "rule" {
10:37:33        - cidr_blocks              = [] -> null
10:37:33          description              = "ACCOUNT/sg-ID"
10:37:33          from_port                = 80
10:37:33        ~ id                       = "sgrule-ID" -> (known after apply)
10:37:33        - ipv6_cidr_blocks         = [] -> null
10:37:33        - prefix_list_ids          = [] -> null
10:37:33          protocol                 = "tcp"
10:37:33          security_group_id        = "sg-ID"
10:37:33          self                     = false
10:37:33        ~ source_security_group_id = "sg-ID" -> "ACCOUNT/sg-ID" # forces replacement
10:37:33          to_port                  = 80
10:37:33          type                     = "ingress"
10:37:33      }
```

**Comment by ktham** [comment]
Hi @jnonino , is that problem still repeatedly happening for you? Do note, that, right after upgrading to the provider version that contains the fix, depending on what your workaround beforehand was (e.g. if you had a lifecycle ignore rule on `soruce_security_group_id`) there may still be 1 more TF plan that will have the sg rule re-creation because the `soruce_security_group_id` got modified to not include `"ACCOUNT/"`.

**Comment by jnonino** [comment]
Thanks, I applied the change and seems the state was updated and it working as expected now. Thanks
