### PR TITLE
resource/ssm_association: remove resource from state in case of external deletion

### LINKED ISSUE #3416: AssociationDoesNotExist:
Hello,

We are facinf an issue where we can't plan or apply anything due to something that seems to be a bug regarding the refresh of aws_ssm_association.

### Terraform Version
Terraform v0.11.3

### Affected Resource(s)
aws_ssm_association

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
* Create an aws_ssm_association with Terraform. (plan, apply, the whole stuff)
* Manually delete it from AWS Console.
* Try to refresh, plan or apply and get the error

**Error reading SSM association: AssociationDoesNotExist: Association xxxx does not exist.**

### Workaround:
Remove item from state using "state rm" command.
```bash
terraform state rm aws_ssm_association.assocname
```

### PR DESCRIPTION
**Pull request by loivis**
fix #3416

### CODE REVIEW

File: aws/resource_aws_ssm_association_test.go [hunk 1]
```diff
@@ -412,9 +450,37 @@ resource "aws_ssm_association" "foo" {
 
 func testAccAWSSSMAssociationBasicConfig(rName string) string {
 	return fmt.Sprintf(`
+variable "name" { default = "%s" }
+
+data "aws_availability_zones" "available" {}
+
+data "aws_ami" "amzn" {
```
Comment (bflad) [inline aws/resource_aws_ssm_association_test.go]: ❤️

**Comment by bflad** [comment]
This has been released in [version 1.12.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1120-march-23-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
