### PR TITLE
d/rds_engine_version: New data source

### LINKED ISSUE #15224: d/rds_engine_version: New data source
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Ease the practitioner burden of working across regions and partitions by providing access to information on database engine versions and specifically the default version. In addition, the `preferred_versions` argument should allow selecting a version from a list of acceptable options.

This data source is part of helping practitioners to avoid this error:

```
Error creating DB Instance: InvalidParameterCombination: RDS does not support creating a DB instance with the
following combination: DBInstanceClass=db.t1.micro, Engine=mysql, EngineVersion=5.6.27,
LicenseModel=general-public-license. For supported combinations of instance class and database engine version,
see the documentation.
```

### New Data Source

* aws_rds_engine_version

### Potential Terraform Configuration

```hcl
data "aws_rds_engine_version" "test" {
  engine = "mysql"
}
```

### References

* hashicorp/terraform#17013
* #15205
* [d/rds_orderable_db_instance](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/rds_orderable_db_instance)

### PR DESCRIPTION
**Pull request by YakDriver**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #15224
Relates #15253, #15259

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
d/rds_engine_version: New data source
```

The output from acceptance testing (GovCloud):

```
--- PASS: TestAccAWSRDSEngineVersionDataSource_defaultOnly (16.47s)
--- PASS: TestAccAWSRDSEngineVersionDataSource_basic (16.47s)
--- PASS: TestAccAWSRDSEngineVersionDataSource_preferred (16.65s)
```

The output from acceptance testing (commercial):

```
--- PASS: TestAccAWSRDSEngineVersionDataSource_defaultOnly (11.33s)
--- PASS: TestAccAWSRDSEngineVersionDataSource_basic (11.34s)
--- PASS: TestAccAWSRDSEngineVersionDataSource_preferred (11.71s)
```

### CODE REVIEW

File: aws/data_source_aws_rds_engine_version.go [hunk 1]
```diff
@@ -0,0 +1,251 @@
...
+	d.SetId(aws.StringValue(found.EngineVersion))
+
+	if found.DefaultCharacterSet != nil {
+		d.Set("default_character_set", found.DefaultCharacterSet.CharacterSetName)
+	}
+
+	d.Set("engine", found.Engine)
+	d.Set("engine_description", found.DBEngineDescription)
+	d.Set("exportable_log_types", found.ExportableLogTypes)
+	d.Set("parameter_group_name", found.DBParameterGroupFamily)
```
Comment (bflad) [inline aws/data_source_aws_rds_engine_version.go:218]:
```suggestion
	d.Set("parameter_group_family", found.DBParameterGroupFamily)
```

File: aws/data_source_aws_rds_engine_version_test.go [hunk 2]
```diff
@@ -0,0 +1,157 @@
...
+		PreCheck:     func() { testAccPreCheck(t); testAccAWSRDSEngineVersionPreCheck(t) },
+		Providers:    testAccProviders,
+		CheckDestroy: nil,
+		Steps: []resource.TestStep{
+			{
+				Config: testAccAWSRDSEngineVersionDataSourceBasicConfig(engine, version, paramGroup),
+				Check: resource.ComposeTestCheckFunc(
+					resource.TestCheckResourceAttr(dataSourceName, "engine", engine),
+					resource.TestCheckResourceAttr(dataSourceName, "version", version),
+					resource.TestCheckResourceAttr(dataSourceName, "parameter_group_name", paramGroup),
```
Comment (bflad) [inline aws/data_source_aws_rds_engine_version_test.go:29]:
```suggestion
					resource.TestCheckResourceAttr(dataSourceName, "parameter_group_family", paramGroup),
```

File: website/docs/d/rds_engine_version.markdown [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+  preferred_versions = ["5.7.42", "5.7.19", "5.7.17"]
+}
+```
+
+## Argument Reference
+
+The following arguments are supported:
+
+* `engine` - (Required) DB engine. Engine values include `aurora`, `aurora-mysql`, `aurora-postgresql`, `docdb`, `mariadb`, `mysql`, `neptune`, `oracle-ee`, `oracle-se`, `oracle-se1`, `oracle-se2`, `postgres`, `sqlserver-ee`, `sqlserver-ex`, `sqlserver-se`, and `sqlserver-web`.
+* `parameter_group_name` - (Optional) The name of a specific DB parameter group family. Examples of parameter group families are `mysql8.0`, `mariadb10.4`, and `postgres12`.
```
Comment (bflad) [inline website/docs/d/rds_engine_version.markdown:27]:
```suggestion
* `parameter_group_family` - (Optional) The name of a specific DB parameter group family. Examples of parameter group families are `mysql8.0`, `mariadb10.4`, and `postgres12`.
```

File: website/docs/d/rds_engine_version.markdown [hunk 4]
```diff
@@ -0,0 +1,48 @@
...
+* `preferred_versions` - (Optional) Ordered list of preferred engine versions. The first match in this list will be returned. If no preferred matches are found and the original search returned more than one result, an error is returned.
+* `version` - (Optional) Version of the DB engine. For example, `5.7.22`, `10.1.34`, and `12.3`.
```
Comment (bflad) [inline website/docs/d/rds_engine_version.markdown:29]: We should mention the behavior here that if both version arguments are unspecified, the data source will return the default version.

```suggestion
* `version` - (Optional) Version of the DB engine. For example, `5.7.22`, `10.1.34`, and `12.3`. If both the `version` and `preferred_versions` arguments are not configured, the data source will return the default version for the engine.
```

File: website/docs/d/rds_engine_version.markdown [hunk 5]
```diff
@@ -0,0 +1,48 @@
...
+* `status` - The status of the DB engine version, either available or deprecated.
+* `supported_character_sets` - A list of the character sets supported by this engine.
+* `supported_feature_names` - A list of features supported by the DB engine.
+* `supported_modes` - A list of the supported DB engine modes.
+* `supported_timezones` - A list of the time zones supported by this engine.
+* `supports_global_databases` - Indicates whether you can use Aurora global databases with a specific DB engine version.
+* `supports_log_exports_to_cloudwatch` - Indicates whether the engine version supports exporting the log types specified by `exportable_log_types` to CloudWatch Logs.
+* `supports_parallel_query` - Indicates whether you can use Aurora parallel query with a specific DB engine version.
+* `supports_read_replica` - Indicates whether the database engine version supports read replicas.
+* `valid_upgrade_targets` - A list of engine versions that this database engine version can be upgraded to.
```
Comment (bflad) [inline website/docs/d/rds_engine_version.markdown:47]: Nit: In Terraform 0.12 and later, the "list" versus "set" terminology is significant, so we should be careful to denote the correct type:

```suggestion
* `exportable_log_types` - Set of log types that the database engine has available for export to CloudWatch Logs.
* `status` - The status of the DB engine version, either available or deprecated.
* `supported_character_sets` - Set of the character sets supported by this engine.
* `supported_feature_names` - Set of features supported by the DB engine.
* `supported_modes` - Set of the supported DB engine modes.
* `supported_timezones` - Set of the time zones supported by this engine.
* `supports_global_databases` - Indicates whether you can use Aurora global databases with a specific DB engine version.
* `supports_log_exports_to_cloudwatch` - Indicates whether the engine version supports exporting the log types specified by `exportable_log_types` to CloudWatch Logs.
* `supports_parallel_query` - Indicates whether you can use Aurora parallel query with a specific DB engine version.
* `supports_read_replica` - Indicates whether the database engine version supports read replicas.
* `valid_upgrade_targets` - Set of engine versions that this database engine version can be upgraded to.
```

**Review by bflad — APPROVED** [review]
Overall looks good to me, just suggestions around family versus name and other small documentation fixes. 🚀 

Output from acceptance testing:

```
--- PASS: TestAccAWSRDSEngineVersionDataSource_defaultOnly (14.38s)
--- PASS: TestAccAWSRDSEngineVersionDataSource_upgradeTargets (15.19s)
--- PASS: TestAccAWSRDSEngineVersionDataSource_basic (15.51s)
--- PASS: TestAccAWSRDSEngineVersionDataSource_preferred (16.05s)
```
