### PR TITLE
resource/aws_ecs_service: Add plan-time validation and prevent panics with empty `type` argument in `ordered_placement_strategy` configuration block

### LINKED ISSUE #13146: Passing empty strings to ordered_placement_strategy blocks causes panic.
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_ecs_service

### Panic Output

```
2020-04-23T06:32:35.308-0400 [DEBUG] plugin.terraform-provider-aws_v2.58.0_x4.exe: panic: interface conversion: interface {} is nil, not map[string]interface {}
2020-04-23T06:32:35.308-0400 [DEBUG] plugin.terraform-provider-aws_v2.58.0_x4.exe: 
2020-04-23T06:32:35.308-0400 [DEBUG] plugin.terraform-provider-aws_v2.58.0_x4.exe: goroutine 72 [running]:
2020-04-23T06:32:35.308-0400 [DEBUG] plugin.terraform-provider-aws_v2.58.0_x4.exe: github.com/terraform-providers/terraform-provider-aws/aws.expandPlacementStrategy(0xc000a8a4e0, 0x3, 0x3, 0x4761800, 0xc000a3f6a0, 0x1, 0xc000a820d0, 0x1)
2020-04-23T06:32:35.308-0400 [DEBUG] plugin.terraform-provider-aws_v2.58.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_ecs_service.go:822 +0x43d
2020-04-23T06:32:35.308-0400 [DEBUG] plugin.terraform-provider-aws_v2.58.0_x4.exe: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsEcsServiceCreate(0xc000890690, 0x4f00f20, 0xc0004faa00, 0x2, 0x969c460)
2020-04-23T06:32:35.308-0400 [DEBUG] plugin.terraform-provider-aws_v2.58.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_ecs_service.go:460 +0x8b1
2020-04-23T06:32:35.308-0400 [DEBUG] plugin.terraform-provider-aws_v2.58.0_x4.exe: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0005b62d0, 0xc000c226e0, 0xc0009518a0, 0x4f00f20, 0xc0004faa00, 0xc000715101, 0xc000ab0120, 0xc0007151a0)
2020-04-23T06:32:35.308-0400 [DEBUG] plugin.terraform-provider-aws_v2.58.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:310 +0x36c
2020-04-23T06:32:35.308-0400 [DEBUG] plugin.terraform-provider-aws_v2.58.0_x4.exe: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000134b80, 0xc000d7f9c8, 0xc000c226e0, 0xc0009518a0, 0xc000715198, 0xc000006e48, 0x4d17c40)
2020-04-23T06:32:35.308-0400 [DEBUG] plugin.terraform-provider-aws_v2.58.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:294 +0xa0
2020-04-23T06:32:35.308-0400 [DEBUG] plugin.terraform-provider-aws_v2.58.0_x4.exe: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000006b08, 0x6396960, 0xc0007f7c80, 0xc0007e55e0, 0xc000006b08, 0xc0007f7c80, 0xc000d93b30)
2020-04-23T06:32:35.308-0400 [DEBUG] plugin.terraform-provider-aws_v2.58.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:885 +0x8bb
2020-04-23T06:32:35.308-0400 [DEBUG] plugin.terraform-provider-aws_v2.58.0_x4.exe: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x587f680, 0xc000006b08, 0x6396960, 0xc0007f7c80, 0xc000ba44e0, 0x0, 0x6396960, 0xc0007f7c80, 0xc00090d200, 0x83f)
2020-04-23T06:32:35.308-0400 [DEBUG] plugin.terraform-provider-aws_v2.58.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3305 +0x21e
2020-04-23T06:32:35.308-0400 [DEBUG] plugin.terraform-provider-aws_v2.58.0_x4.exe: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000059e00, 0x63b8780, 0xc000e9a180, 0xc000bc4e00, 0xc0007a9e60, 0x966d3c0, 0x0, 0x0, 0x0)
2020-04-23T06:32:35.308-0400 [DEBUG] plugin.terraform-provider-aws_v2.58.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:1024 +0x4fb
2020-04-23T06:32:35.308-0400 [DEBUG] plugin.terraform-provider-aws_v2.58.0_x4.exe: google.golang.org/grpc.(*Server).handleStream(0xc000059e00, 0x63b8780, 0xc000e9a180, 0xc000bc4e00, 0x0)
2020-04-23T06:32:35.308-0400 [DEBUG] plugin.terraform-provider-aws_v2.58.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:1313 +0xd9e
2020-04-23T06:32:35.317-0400 [DEBUG] plugin.terraform-provider-aws_v2.58.0_x4.exe: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00003a0e0, 0xc000059e00, 0x63b8780, 0xc000e9a180, 0xc000bc4e00)
2020-04-23T06:32:35.317-0400 [DEBUG] plugin.terraform-provider-aws_v2.58.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:722 +0xc2
2020-04-23T06:32:35.317-0400 [DEBUG] plugin.terraform-provider-aws_v2.58.0_x4.exe: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-04-23T06:32:35.317-0400 [DEBUG] plugin.terraform-provider-aws_v2.58.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:720 +0xa8
2020/04/23 06:32:35 [DEBUG] aws_ecs_service.ecs-service: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2020/04/23 06:32:35 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
```

### Steps to Reproduce

1. `terraform apply`

### PR DESCRIPTION
**Pull request by bflad**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #13146

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
* resource/aws_ecs_service: Add plan-time validation and prevent panics with empty `type` argument in `ordered_placement_strategy` configuration block
```

Previously (before code update):

```
=== CONT  TestAccAWSEcsService_withPlacementStrategy_Type_Missing
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 489 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.expandPlacementStrategy(0xc001864060, 0x1, 0x1, 0x5df3d20, 0xc001066980, 0x1, 0xc001883a20, 0x1)
  /Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_ecs_service.go:860 +0x433
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsEcsServiceCreate(0xc0004863f0, 0x65fc000, 0xc0005aaa00, 0x2, 0xbb2a100)
  /Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_ecs_service.go:468 +0x13e5
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000a8b320, 0xc00133de50, 0xc000559660, 0x65fc000, 0xc0005aaa00, 0x6470d01, 0xc001db8018, 0xc002373590)
  /Users/bflad/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.14.0/helper/schema/resource.go:310 +0x365
```

Previously (after `expandPlacementStrategy` adjustments, before validation and `ExpectError` testing):

```
=== CONT  TestAccAWSEcsService_withPlacementStrategy_Type_Missing
    TestAccAWSEcsService_withPlacementStrategy_Type_Missing: testing.go:684: Step 0 error: After applying this step, the plan was not empty:
```

Output from acceptance testing:

```
--- PASS: TestAccAWSEcsService_basicImport (80.94s)
--- PASS: TestAccAWSEcsService_disappears (66.82s)
--- PASS: TestAccAWSEcsService_healthCheckGracePeriodSeconds (352.62s)
--- PASS: TestAccAWSEcsService_ManagedTags (87.33s)
--- PASS: TestAccAWSEcsService_PropagateTags (200.33s)
--- PASS: TestAccAWSEcsService_Tags (104.81s)
--- PASS: TestAccAWSEcsService_withAlb (295.55s)
--- PASS: TestAccAWSEcsService_withARN (91.67s)
--- PASS: TestAccAWSEcsService_withCapacityProviderStrategy (214.86s)
--- PASS: TestAccAWSEcsService_withDaemonSchedulingStrategy (58.37s)
--- PASS: TestAccAWSEcsService_withDaemonSchedulingStrategySetDeploymentMinimum (47.94s)
--- PASS: TestAccAWSEcsService_withDeploymentController_Type_CodeDeploy (306.46s)
--- PASS: TestAccAWSEcsService_withDeploymentController_Type_External (50.35s)
--- PASS: TestAccAWSEcsService_withDeploymentMinimumZeroMaximumOneHundred (80.13s)
--- PASS: TestAccAWSEcsService_withDeploymentValues (90.43s)
--- PASS: TestAccAWSEcsService_withEcsClusterName (79.67s)
--- PASS: TestAccAWSEcsService_withFamilyAndRevision (89.23s)
--- PASS: TestAccAWSEcsService_withForceNewDeployment (92.52s)
--- PASS: TestAccAWSEcsService_withIamRole (150.57s)
--- PASS: TestAccAWSEcsService_withLaunchTypeEC2AndNetworkConfiguration (114.09s)
--- PASS: TestAccAWSEcsService_withLaunchTypeFargate (168.82s)
--- PASS: TestAccAWSEcsService_withLaunchTypeFargateAndPlatformVersion (168.07s)
--- PASS: TestAccAWSEcsService_withLbChanges (268.47s)
--- PASS: TestAccAWSEcsService_withMultipleCapacityProviderStrategies (134.81s)
--- PASS: TestAccAWSEcsService_withMultipleTargetGroups (308.29s)
--- PASS: TestAccAWSEcsService_withPlacementConstraints (94.08s)
--- PASS: TestAccAWSEcsService_withPlacementConstraints_emptyExpression (79.71s)
--- PASS: TestAccAWSEcsService_withPlacementStrategy (83.37s)
--- PASS: TestAccAWSEcsService_withPlacementStrategy_Type_Missing (1.45s)
--- PASS: TestAccAWSEcsService_withRenamedCluster (173.49s)
--- PASS: TestAccAWSEcsService_withReplicaSchedulingStrategy (79.00s)
--- PASS: TestAccAWSEcsService_withServiceRegistries (185.70s)
--- PASS: TestAccAWSEcsService_withServiceRegistries_container (175.98s)
--- PASS: TestAccAWSEcsService_withUnnormalizedPlacementStrategy (89.54s)
```

### CODE REVIEW

File: aws/resource_aws_ecs_service.go [hunk 1]
```diff
@@ -857,9 +862,24 @@ func expandPlacementStrategy(s []interface{}) ([]*ecs.PlacementStrategy, error)
 	}
 	pss := make([]*ecs.PlacementStrategy, 0)
 	for _, raw := range s {
-		p := raw.(map[string]interface{})
-		t := p["type"].(string)
-		f := p["field"].(string)
+		p, ok := raw.(map[string]interface{})
```
Comment (anGie44) [inline aws/resource_aws_ecs_service.go:865]: interesting, I didn't know that you could get a slice with nil map`[nil...]` from a config where a required field was sent, even if as an empty string.

Comment (bflad) [reply aws/resource_aws_ecs_service.go:865]: 😅  Yeah, its a surprising feature of the Terraform Plugin SDK. If all nested attributes match the zero value for their type, then the map itself is `nil` and type assertion panics.
