### PR TITLE
 Fix and enable tfproviderlint R005 check: Combine multiple d.HasChange() calls with d.HasChanges() call 

### LINKED ISSUE #11863: Fix and enable tfproviderlint R005 check: Combine multiple d.HasChange() calls with d.HasChanges() call
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Terraform Plugin SDK recently introduced a simplifying `d.HasChanges()` call to replace multiple OR'd `d.HasChange()`. See also: https://github.com/bflad/tfproviderlint/blob/master/passes/R005/README.md

e.g.

```
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/autoscaling_tags.go:59:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_acm_certificate.go:295:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_cloudtrail.go:318:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_codedeploy_deployment_group.go:676:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_datasync_task.go:279:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_db_instance.go:1468:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_db_instance.go:1625:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_db_instance.go:1633:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_db_subnet_group.go:169:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_dms_endpoint.go:423:6: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_dms_endpoint.go:461:6: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_docdb_subnet_group.go:154:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_dynamodb_table.go:476:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_dynamodb_table.go:492:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_ec2_transit_gateway_vpc_attachment.go:213:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_ec2_transit_gateway_vpc_attachment.go:243:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_ec2_transit_gateway_vpc_attachment_accepter.go:192:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_ecs_cluster.go:259:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_ecs_service.go:910:6: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_efs_file_system.go:204:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_eip.go:294:14: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_eip.go:311:13: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_eks_cluster.go:366:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_eks_node_group.go:340:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_eks_node_group.go:372:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_elasticache_subnet_group.go:130:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_elasticsearch_domain.go:724:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_elb.go:584:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_elb.go:628:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_emr_instance_group.go:289:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_gamelift_fleet.go:338:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_globalaccelerator_accelerator.go:239:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_glue_catalog_database.go:111:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_glue_crawler.go:461:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_glue_job.go:302:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_glue_trigger.go:306:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_iam_group.go:101:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_iam_user.go:141:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_lambda_function.go:192:9: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_media_convert_queue.go:175:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_mq_broker.go:405:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_neptune_subnet_group.go:165:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_ram_resource_share.go:134:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_rds_cluster_instance.go:498:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_redshift_cluster.go:664:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_redshift_subnet_group.go:139:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_route53_health_check.go:180:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_route53_resolver_rule.go:193:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_s3_bucket_object.go:449:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_secretsmanager_secret.go:261:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_secretsmanager_secret.go:307:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_storagegateway_gateway.go:400:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_transfer_server.go:213:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_vpc_peering_connection.go:230:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_waf_web_acl.go:283:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_wafregional_rate_based_rule.go:174:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_wafregional_web_acl.go:300:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_worklink_fleet.go:237:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
```

### Definition of Done

- Fix R005 reports
- In `GNUmakefile`, add `-R005` to `tfproviderlint` command under lint target and have TravisCI testing pass

### PR DESCRIPTION
**Pull request by jbarnes7952**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #11863

```
autoscaling_tags.go:59:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_acm_certificate.go:295:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_cloudtrail.go:318:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_datasync_task.go:279:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_db_instance.go:1465:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_db_instance.go:1598:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_db_instance.go:1604:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_db_subnet_group.go:169:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_dms_endpoint.go:423:6: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_dms_endpoint.go:461:6: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_docdb_subnet_group.go:154:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_dynamodb_table.go:476:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_dynamodb_table.go:492:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_ec2_transit_gateway_vpc_attachment.go:213:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_ec2_transit_gateway_vpc_attachment.go:243:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_ec2_transit_gateway_vpc_attachment_accepter.go:192:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_ecs_cluster.go:259:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_ecs_service.go:910:6: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_efs_file_system.go:204:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_eip.go:294:14: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_eip.go:311:13: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_eks_cluster.go:408:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_eks_node_group.go:340:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_eks_node_group.go:372:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_elasticache_subnet_group.go:130:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_elasticsearch_domain.go:724:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_elb.go:569:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_elb.go:609:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_emr_instance_group.go:289:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_gamelift_fleet.go:355:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_globalaccelerator_accelerator.go:265:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_glue_catalog_database.go:111:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_glue_crawler.go:461:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_glue_job.go:324:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_glue_trigger.go:306:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_iam_group.go:101:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_iam_user.go:141:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_lambda_function.go:195:9: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_media_convert_queue.go:175:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_mq_broker.go:405:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_msk_cluster.go:539:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_neptune_subnet_group.go:165:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_ram_resource_share.go:134:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_rds_cluster_instance.go:497:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_redshift_cluster.go:661:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_redshift_subnet_group.go:136:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_route53_health_check.go:189:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_route53_resolver_rule.go:191:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_s3_bucket_object.go:456:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_secretsmanager_secret.go:261:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_secretsmanager_secret.go:307:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_storagegateway_gateway.go:400:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_transfer_server.go:230:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_vpc_peering_connection.go:239:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_waf_web_acl.go:283:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_wafregional_rate_based_rule.go:174:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_wafregional_web_acl.go:300:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
resource_aws_worklink_fleet.go:237:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call

```

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```
NONE

```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by bflad** [comment]
Hey @jbarnes7952 👋 Thank you for picking this up! Do you intend on working on this more? Just trying to gauge if the team should review it, running testing, finish it up, etc. Thanks. 😄

File: aws/resource_aws_dms_endpoint.go [hunk 1]
```diff
@@ -420,17 +420,7 @@ func resourceAwsDmsEndpointUpdate(d *schema.ResourceData, meta interface{}) erro
...
-			d.HasChange("server_name") ||
-			d.HasChange("port") ||
-			d.HasChange("database_name") ||
-			d.HasChange("mongodb_settings.0.auth_type") ||
-			d.HasChange("mongodb_settings.0.auth_mechanism") ||
-			d.HasChange("mongodb_settings.0.nesting_level") ||
-			d.HasChange("mongodb_settings.0.extract_doc_id") ||
-			d.HasChange("mongodb_settings.0.docs_to_investigate") ||
-			d.HasChange("mongodb_settings.0.auth_source") {
+		if d.HasChanges("username", "password", "server_name", "port", "database_name", "mongodb_settings.0.auth_type", "mongodb_settings.0.auth_mechanism", "mongodb_settings.0.nesting_level", "mongodb_settings.0.extract_doc_id", "mongodb_settings.0.docs_to_investigate", "mongodb_settings.0.auth_source") {
```
Comment (gdavison) [inline aws/resource_aws_dms_endpoint.go:423]: For readability, this might be better broken over several lines

File: aws/resource_aws_dms_endpoint.go [hunk 2]
```diff
@@ -458,13 +448,7 @@ func resourceAwsDmsEndpointUpdate(d *schema.ResourceData, meta interface{}) erro
...
 		}
 	case "s3":
-		if d.HasChange("s3_settings.0.service_access_role_arn") ||
-			d.HasChange("s3_settings.0.external_table_definition") ||
-			d.HasChange("s3_settings.0.csv_row_delimiter") ||
-			d.HasChange("s3_settings.0.csv_delimiter") ||
-			d.HasChange("s3_settings.0.bucket_folder") ||
-			d.HasChange("s3_settings.0.bucket_name") ||
-			d.HasChange("s3_settings.0.compression_type") {
+		if d.HasChanges("s3_settings.0.service_access_role_arn", "s3_settings.0.external_table_definition", "s3_settings.0.csv_row_delimiter", "s3_settings.0.csv_delimiter", "s3_settings.0.bucket_folder", "s3_settings.0.bucket_name", "s3_settings.0.compression_type") {
```
Comment (gdavison) [inline aws/resource_aws_dms_endpoint.go:451]: This could be split over several lines as well

File: aws/resource_aws_glue_crawler.go [hunk 3]
```diff
@@ -458,18 +458,7 @@ func resourceAwsGlueCrawlerUpdate(d *schema.ResourceData, meta interface{}) erro
...
-		d.HasChange("description") ||
-		d.HasChange("dynamodb_target") ||
-		d.HasChange("jdbc_target") ||
-		d.HasChange("role") ||
-		d.HasChange("s3_target") ||
-		d.HasChange("schedule") ||
-		d.HasChange("schema_change_policy") ||
-		d.HasChange("security_configuration") ||
-		d.HasChange("table_prefix") {
+	if d.HasChanges("catalog_target", "classifiers", "configuration", "description", "dynamodb_target", "jdbc_target", "role", "s3_target", "schedule", "schema_change_policy", "security_configuration", "table_prefix") {
```
Comment (gdavison) [inline aws/resource_aws_glue_crawler.go:461]: This can be broken over several lines
