### PR TITLE
r/aws_redshift_snapshot_copy_grant: Remove extraneous Exists function

### LINKED ISSUE #9953: Fix and enable tfproviderlint R003 check: Remove extraneous Exists functions
## Description
As per `tfproviderlint` check `R003`, we want to remove extraneous `Exists` functions from resources. This logic can be handled inside `Read` functions instead to prevent duplication. 

Failing example:
```
func resourceExampleThingExists(d *schema.ResourceData, meta interface{}) (bool, error) { /* ... */ }

func resourceExampleThingRead(d *schema.ResourceData, meta interface{}) error { /* ... */ }

&schema.Resource{
    Exists: resourceExampleThingExists,
    Read:   resourceExampleThingRead,
    /* ... */
}
```

Should become:
```


func resourceExampleThingRead(d *schema.ResourceData, meta interface{}) error { /* ... */ }

&schema.Resource{
    Read: resourceExampleThingRead,
    /* ... */
}
```

## Definition of Done
* In `GNUmakefile`, add `-R003` to `tfproviderlint` command under `lint` target and have TravisCI testing pass

### PR DESCRIPTION
**Pull request by ewbankkit**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #9953.

Includes `testAccCheckResourceDisappears()` from https://github.com/terraform-providers/terraform-provider-aws/pull/12864.

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Output from acceptance testing:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSRedshiftSnapshotCopyGrant_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -count 1 -parallel 20 -run=TestAccAWSRedshiftSnapshotCopyGrant_ -timeout 120m
=== RUN   TestAccAWSRedshiftSnapshotCopyGrant_Basic
=== PAUSE TestAccAWSRedshiftSnapshotCopyGrant_Basic
=== RUN   TestAccAWSRedshiftSnapshotCopyGrant_Update
=== PAUSE TestAccAWSRedshiftSnapshotCopyGrant_Update
=== RUN   TestAccAWSRedshiftSnapshotCopyGrant_disappears
=== PAUSE TestAccAWSRedshiftSnapshotCopyGrant_disappears
=== CONT  TestAccAWSRedshiftSnapshotCopyGrant_Basic
=== CONT  TestAccAWSRedshiftSnapshotCopyGrant_disappears
=== CONT  TestAccAWSRedshiftSnapshotCopyGrant_Update
--- PASS: TestAccAWSRedshiftSnapshotCopyGrant_disappears (18.83s)
--- PASS: TestAccAWSRedshiftSnapshotCopyGrant_Basic (24.47s)
--- PASS: TestAccAWSRedshiftSnapshotCopyGrant_Update (39.32s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	39.376s
```

### CODE REVIEW

**Comment by bflad** [comment]
#12864 has been merged so that functionality does not need to be reviewed again. 👍

File: aws/resource_aws_redshift_snapshot_copy_grant.go [hunk 1]
```diff
@@ -269,16 +209,5 @@ func findAwsRedshiftSnapshotCopyGrant(conn *redshift.Redshift, grantName string,
...
-	} else if out.Marker != nil {
-		log.Printf("[DEBUG] Snapshot copy grant not found but marker returned, getting next page via marker: %s", aws.StringValue(out.Marker))
-		return findAwsRedshiftSnapshotCopyGrant(conn, grantName, out.Marker)
-	}
-
-	return nil, &resource.NotFoundError{
-		Message:     fmt.Sprintf("[DEBUG] Grant %s not found", grantName),
-		LastRequest: input,
-	}
+	return out.SnapshotCopyGrants[0], nil
```
Comment (appilon) [inline aws/resource_aws_redshift_snapshot_copy_grant.go:212]: if err == nil is it guaranteed this slice has at least 1 item?

Comment (ewbankkit) [reply aws/resource_aws_redshift_snapshot_copy_grant.go:212]: In all my testing that was the case, `err != nil` => `out != nil && len(out.SnapshotCopyGrants)`, but you are correct in that the previous code would have handled opposite by returning `nil` for the grant. It's minor to add that back (plus change some of the callers to check for a `nil` grant).

Comment (appilon) [reply aws/resource_aws_redshift_snapshot_copy_grant.go:212]: Okay if you don't mind, once that change is made this will get merged! Thank you for helping with all the tech debt.

**Comment by ewbankkit** [comment]
@appilon Made the suggested changes and add the additional check to `make lint` as this now closes  #9953.

Acceptance tests:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSRedshiftSnapshotCopyGrant_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -count 1 -parallel 20 -run=TestAccAWSRedshiftSnapshotCopyGrant_ -timeout 120m
=== RUN   TestAccAWSRedshiftSnapshotCopyGrant_Basic
=== PAUSE TestAccAWSRedshiftSnapshotCopyGrant_Basic
=== RUN   TestAccAWSRedshiftSnapshotCopyGrant_Update
=== PAUSE TestAccAWSRedshiftSnapshotCopyGrant_Update
=== RUN   TestAccAWSRedshiftSnapshotCopyGrant_disappears
=== PAUSE TestAccAWSRedshiftSnapshotCopyGrant_disappears
=== CONT  TestAccAWSRedshiftSnapshotCopyGrant_Update
=== CONT  TestAccAWSRedshiftSnapshotCopyGrant_Basic
=== CONT  TestAccAWSRedshiftSnapshotCopyGrant_disappears
--- PASS: TestAccAWSRedshiftSnapshotCopyGrant_disappears (18.44s)
--- PASS: TestAccAWSRedshiftSnapshotCopyGrant_Basic (23.83s)
--- PASS: TestAccAWSRedshiftSnapshotCopyGrant_Update (53.29s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	53.354s
```
