### PR TITLE
re-create lambda policy when permission sid not found

### LINKED ISSUE #11008: Error finding Lambda policy statement: Failed to find statement
_This issue was originally opened by @wubigo as hashicorp/terraform#23480. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._
    
<hr>
    

### Terraform Version

```
Terraform v0.12.16
+ provider.aws v2.39.0
```

### Terraform Configuration Files

```hcl
...
```

### Debug Output

https://gist.github.com/wubigo/0c7afe6822135b917d9fedc2ca5916a3

### Steps to Reproduce

https://learn.hashicorp.com/terraform/aws/lambda-api-gateway

### PR DESCRIPTION
**Pull request by ansoni**
Hello,
   Please find the small change to blank out the Id for proper remediation when the policy SID goes missing.

Thanks,

Anthony

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #11008

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
lambda policy SIDs that are deleted out-of-band are now properly drift detected and restored.
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestLambdaPermission'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -count 1 -parallel 20 -run=TestLambdaPermission -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestLambdaPermissionUnmarshalling
--- PASS: TestLambdaPermissionUnmarshalling (0.00s)
=== RUN   TestLambdaPermissionGetQualifierFromLambdaAliasOrVersionArn_alias
--- PASS: TestLambdaPermissionGetQualifierFromLambdaAliasOrVersionArn_alias (0.00s)
=== RUN   TestLambdaPermissionGetQualifierFromLambdaAliasOrVersionArn_govcloud
--- PASS: TestLambdaPermissionGetQualifierFromLambdaAliasOrVersionArn_govcloud (0.00s)
=== RUN   TestLambdaPermissionGetQualifierFromLambdaAliasOrVersionArn_version
--- PASS: TestLambdaPermissionGetQualifierFromLambdaAliasOrVersionArn_version (0.00s)
=== RUN   TestLambdaPermissionGetQualifierFromLambdaAliasOrVersionArn_invalid
--- PASS: TestLambdaPermissionGetQualifierFromLambdaAliasOrVersionArn_invalid (0.00s)
=== RUN   TestLambdaPermissionGetFunctionNameFromLambdaArn_invalid
--- PASS: TestLambdaPermissionGetFunctionNameFromLambdaArn_invalid (0.00s)
=== RUN   TestLambdaPermissionGetFunctionNameFromLambdaArn_valid
--- PASS: TestLambdaPermissionGetFunctionNameFromLambdaArn_valid (0.00s)
=== RUN   TestLambdaPermissionGetFunctionNameFromGovCloudLambdaArn
--- PASS: TestLambdaPermissionGetFunctionNameFromGovCloudLambdaArn (0.00s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	0.062s
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/flatmap	0.023s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags	0.101s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/batch/equivalency	0.034s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/eks/token	0.035s [no tests to run]
?   	github.com/terraform-providers/terraform-provider-aws/awsproviderlint	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes	0.068s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSAT001	0.048s [no tests to run]
...
```

### CODE REVIEW

File: aws/resource_aws_lambda_permission.go [hunk 1]
```diff
@@ -394,11 +403,7 @@ func getLambdaPolicyStatement(out *lambda.GetPolicyOutput, statemendId string) (
 		return nil, fmt.Errorf("Error unmarshalling Lambda policy: %s", err)
 	}
 
-	statement, psErr := findLambdaPolicyStatementById(&policy, statemendId)
-	if psErr != nil {
-		return nil, fmt.Errorf("Error finding Lambda policy statement: %s", psErr)
-	}
-	return statement, nil
+	return findLambdaPolicyStatementById(&policy, statemendId)
```
Comment (ansoni) [inline aws/resource_aws_lambda_permission.go]: re-casting the error to a human readable string is unnecessary since we are a tool that can do something about it.

File: aws/resource_aws_lambda_permission.go [hunk 2]
```diff
@@ -225,6 +225,16 @@ func resourceAwsLambdaPermissionRead(d *schema.ResourceData, meta interface{}) e
 		if err == nil {
 			var psErr error
 			statement, psErr = getLambdaPolicyStatement(out, d.Id())
+
+			// handle the resource not existing
+			if awsErr, ok := psErr.(awserr.Error); ok {
```
Comment (ansoni) [inline aws/resource_aws_lambda_permission.go]: Pattern taken from existing code a few lines below.  I don't believe we were ever hitting that case, but left just to be sure.

**Comment by ansoni** [comment]
FYI @bflad, this hard fail caused us a lot of grief today.  If we can get this drift-remediation update included then our work-around for the modified lambda policies will be a terraform upgrade instead of us having to modify 40-50 TFE project state files or out-of-band edit of lambda permissions.

File: aws/resource_aws_lambda_permission.go (hunk 1 above)
Comment (gdavison) [reply aws/resource_aws_lambda_permission.go]: Agreed, there's no need to wrap this again

**Comment by scottwinkler** [comment]
@gdavison I wrote an acceptance test for this

Running tool: /usr/local/bin/go test -timeout 30s github.com/terraform-providers/terraform-provider-aws/aws -run ^(TestAccAWSLambdaPermission_disappears)$
ok      github.com/terraform-providers/terraform-provider-aws/aws   2.518s
Success: Tests passed.

File: aws/resource_aws_lambda_permission_test.go [hunk 3]
```diff
@@ -315,6 +316,37 @@ func TestAccAWSLambdaPermission_withQualifier(t *testing.T) {
...
+		CheckDestroy: testAccCheckAWSLambdaPermissionDestroy,
+		Steps: []resource.TestStep{
+			{
+				Config: testAccAWSLambdaPermissionConfig(funcName, roleName),
+				Check: resource.ComposeTestCheckFunc(
+					testAccCheckLambdaPermissionExists("aws_lambda_permission.allow_cloudwatch", &statement),
+				),
+			},
+			// Here we delete the Lambda permission to verify the follow-on refresh after this step
+			// should not error.
```
Comment (gdavison) [inline aws/resource_aws_lambda_permission_test.go]: This first step can be removed

File: aws/resource_aws_lambda_permission_test.go [hunk 4]
```diff
@@ -315,6 +316,37 @@ func TestAccAWSLambdaPermission_withQualifier(t *testing.T) {
...
+			{
+				Config: testAccAWSLambdaPermissionConfig(funcName, roleName),
```
Comment (gdavison) [inline aws/resource_aws_lambda_permission_test.go]: The error only shows up when there are still permission elements left. We can use `testAccAWSLambdaPermissionConfig_multiplePerms()` instead, and then remove `aws_lambda_permission.first`.

File: aws/resource_aws_lambda_permission_test.go (hunk 3 above)
Comment (scottwinkler) [reply aws/resource_aws_lambda_permission_test.go]: removed

**Comment by scottwinkler** [comment]
@gdavison  I made the changes you requested. Please let me know if there is anything else you

**Comment by gdavison** [comment]
LGTM 🚀 

--- PASS: TestAccAWSLambdaPermission_basic (24.64s)
--- PASS: TestAccAWSLambdaPermission_withIAMRole (33.33s)
--- PASS: TestAccAWSLambdaPermission_withQualifier (33.23s)
--- PASS: TestAccAWSLambdaPermission_withStatementIdPrefix (33.43s)
--- PASS: TestAccAWSLambdaPermission_withRawFunctionName (33.53s)
--- PASS: TestAccAWSLambdaPermission_withSNS (33.73s)
--- PASS: TestAccAWSLambdaPermission_withS3 (33.70s)
--- PASS: TestAccAWSLambdaPermission_multiplePerms (40.61s)
--- PASS: TestAccAWSLambdaPermission_StatementId_Duplicate (89.63s)
--- PASS: TestAccAWSLambdaPermission_disappears (91.56s)
