### PR TITLE
resource/aws_db_option_group: Fix error when creating db_option_group with new IAM role

### LINKED ISSUE #763: DB option groups with a failed IAM-related option apply do not detect missing options in subsqeuent plan
_This issue was originally opened by @mattzimmerman as hashicorp/terraform#14417. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version
0.9.4

### Affected Resource(s)
- aws_db_option_group

### Terraform Configuration Files
```hcl
resource "aws_db_option_group" "sql-server-options" {
  name = "sql-server-${var.environment}-options"
  option_group_description = "SQL Server backup options"
  engine_name = "${var.db-engine}"
  major_engine_version = "${var.db-major-engine-version}"
  option {
    option_name = "SQLSERVER_BACKUP_RESTORE"
      option_settings {
        name = "IAM_ROLE_ARN"
        value = "${aws_iam_role.sql-server.arn}"
      }
  }
}

resource "aws_iam_instance_profile" "sql-server" {
  name = "sql-server.${var.namespace}"
  role = "${aws_iam_role.sql-server.id}"
}

resource "aws_iam_role" "sql-server" {
  name = "sql-server.${var.namespace}"
  path = "/"
  assume_role_policy = <removed for brevity
}

resource "aws_iam_role_policy" "sql-server-backup" {
  name = "sql-server-backup.${var.namespace}"
  role = "${aws_iam_role.sql-server.id}"
  policy = <removed for brevity>
}
```

### Description
DB option groups with a failed option apply (I frequently see this on SQL Server DB option groups with an option that includes an IAM role for backing up/restoring to/from S3 buckets). 

Terraform successfully creates my new IAM role, immediately applies that as part of an option to the `aws_db_option_group`, but then that apply fails because the IAM resource isn't available from the AWS API yet. 

As an aside, it would be nice if terraform apply could wait for the role to become available before attempting to use it in a `aws_db_option_group` (but that is easy to work around by creating it and tracking the IAM role used for the option group in another terraform run prior to creating the option group).

However, when the Terraform run fails in this way (due to the newly-created IAM role and eventual consistency):

```
Error applying plan:
1 error(s) occurred:
* aws_db_option_group.sql-server-backup-options: 1 error(s) occurred:
* aws_db_option_group.sql-server-backup-options: Error modifying DB Option Group: InvalidParameterValue: IAM role ARN value is invalid or does not include the required permissions for: SQLSERVER_BACKUP_RESTORE
status code: 400, request id: d11b2c48-3426-11e7-977c-ddb68cb08401
```

I noticed that Terraform has lost track of the state of the option it was adding. Subsequent plan/apply attempts do not detect any changes, and the option group that is created from the initial run never actually gets the option added to it.

### PR DESCRIPTION
**Pull request by pvanbuijtene**
Fixes #763

Added retry to fix eventual consistency error when referring to new IAM role.

Output from acceptance testing:

```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -run .*AWSDBOptionGroup.* -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSDBOptionGroup_importBasic
--- PASS: TestAccAWSDBOptionGroup_importBasic (30.90s)
=== RUN   TestAccAWSDBOptionGroup_basic
--- PASS: TestAccAWSDBOptionGroup_basic (26.91s)
=== RUN   TestAccAWSDBOptionGroup_timeoutBlock
--- PASS: TestAccAWSDBOptionGroup_timeoutBlock (28.20s)
=== RUN   TestAccAWSDBOptionGroup_namePrefix
--- PASS: TestAccAWSDBOptionGroup_namePrefix (26.76s)
=== RUN   TestAccAWSDBOptionGroup_generatedName
--- PASS: TestAccAWSDBOptionGroup_generatedName (32.78s)
=== RUN   TestAccAWSDBOptionGroup_defaultDescription
--- PASS: TestAccAWSDBOptionGroup_defaultDescription (27.49s)
=== RUN   TestAccAWSDBOptionGroup_basicDestroyWithInstance
--- PASS: TestAccAWSDBOptionGroup_basicDestroyWithInstance (501.20s)
=== RUN   TestAccAWSDBOptionGroup_OptionSettings
--- PASS: TestAccAWSDBOptionGroup_OptionSettings (49.78s)
=== RUN   TestAccAWSDBOptionGroup_OptionSettingsIAMRole
--- PASS: TestAccAWSDBOptionGroup_OptionSettingsIAMRole (48.33s)
=== RUN   TestAccAWSDBOptionGroup_sqlServerOptionsUpdate
--- PASS: TestAccAWSDBOptionGroup_sqlServerOptionsUpdate (48.33s)
=== RUN   TestAccAWSDBOptionGroup_OracleOptionsUpdate
--- PASS: TestAccAWSDBOptionGroup_OracleOptionsUpdate (60.62s)
=== RUN   TestAccAWSDBOptionGroup_multipleOptions
--- PASS: TestAccAWSDBOptionGroup_multipleOptions (28.57s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	909.939s
```

### CODE REVIEW

File: aws/resource_aws_db_option_group.go [hunk 1]
```diff
@@ -273,12 +273,24 @@ func resourceAwsDbOptionGroupUpdate(d *schema.ResourceData, meta interface{}) er
 		}
 
 		log.Printf("[DEBUG] Modify DB Option Group: %s", modifyOpts)
-		_, err = rdsconn.ModifyOptionGroup(modifyOpts)
+
+		err = resource.Retry(5*time.Minute, func() *resource.RetryError {
```
Comment (bflad) [inline aws/resource_aws_db_option_group.go]: IAM eventual consistency is usually on the magnitude of 1-2 minutes (very rarely the latter). Can you please lower this retry timeout to prevent bad user experience when there might be an actual issue?

File: aws/resource_aws_db_option_group.go [hunk 2]
```diff
@@ -273,12 +273,24 @@ func resourceAwsDbOptionGroupUpdate(d *schema.ResourceData, meta interface{}) er
...
+			var err error
+
+			_, err = rdsconn.ModifyOptionGroup(modifyOpts)
+			if err != nil {
+				if isAWSErr(err, "InvalidParameterValue", "SQLSERVER_BACKUP_RESTORE") {
```
Comment (bflad) [inline aws/resource_aws_db_option_group.go]: Two things:
* Can you please add a comment with the full error message?
* Can you adjust the string checking for the relevant IAM part, instead of just the parameter in question? We don't want to retry on non-IAM messages for `SQLSERVER_BACKUP_RESTORE` and we also would love to proactively catch IAM issues for other parameters if we can.

e.g.

```go
// InvalidParameterValue: IAM role ARN value is invalid or does not include the required permissions for: SQLSERVER_BACKUP_RESTORE
if isAWSErr(err, "InvalidParameterValue", "IAM role ARN value is invalid or does not include the required permissions") {
```

**Comment by pvanbuijtene** [comment]
@bflad thanks for the review, review comments are applied.

**Comment by bflad** [comment]
This has been released in [version 1.30.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1300-august-02-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
