### PR TITLE
Fix S3 bucket lifecycle rule filters with a single tag and no prefix

### LINKED ISSUE #7156: s3: Ignored lifecycle_policy is changed anyway
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.11.11
+ provider.archive v1.1.0
+ provider.aws v1.30.0
+ provider.null v1.0.0
+ provider.template v1.0.0
```

### Affected Resource(s)

* aws_s3_bucket

### Terraform Configuration Files

```hcl
resource "aws_s3_bucket" "nexus" {
  bucket = "s3.${local.suffix}"
  acl    = "private"

  lifecycle {
    ignore_changes = ["lifecycle_rule"]
  }

  tags = "${merge(
              map("Name", "s3.${local.infix}",
                  "Environnement", var.environment,
                  "Stack", var.stack),
                  var.extra_tags)}"
}
```

Lifecycle policy as configured by Nexus:
```
{
"xmlns": "http://s3.amazonaws.com/doc/2006-03-01/","
Rule": {
  "Status": "Enabled",
  "Filter": {
    "Prefix": ""
  },
  "Tags": {
    "deleted" : "true"
  }
  "Expiration": {
    "Days": 3
  },
  "ID": "Expire soft-deleted blobstore objects"
  }
}
```
### Debug Output
```
tfwrapper plan -- -target module.nexus-s3
INFO    tfwrapper : Getting state session
INFO    tfwrapper : Getting stack session

Warning: output "igw_id": must use splat syntax to access aws_internet_gateway.basic attribute "id", because it has "count" set; use aws_internet_gateway.basic.*.id to obtain a list of the attributes across all instances



Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

aws_s3_bucket.nexus: Refreshing state... (ID: s3.nexus)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ module.nexus-s3.aws_s3_bucket.nexus
      tags.Environment: "DEV" => "dev"


Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behavior

We were changing bucket tags so only bucket tags should have changed.

### Actual Behavior
Lifecycle policy was changed to:
```
{
"xmlns": "http://s3.amazonaws.com/doc/2006-03-01/","
Rule": {
  "Status": "Enabled",
  "Filter": {
    "Prefix": ""
  },
  "Expiration": {
    "Days": 3
  },
  "ID": "Expire soft-deleted blobstore objects"
  }
}
```
The `  "Tags": {     "deleted" : "true"  }` filter was removed **which led to all files in the bucket to be removed** after 3 days. We were lucky this happened on a test env.

### Steps to Reproduce

1. Create bucket with terraform and ignore lifecycle change
2. Manually set a lifecycle policy such as:
```
{
"xmlns": "http://s3.amazonaws.com/doc/2006-03-01/","
Rule": {
  "Status": "Enabled",
  "Filter": {
    "Prefix": ""
  },
  "Tags": {
    "deleted" : "true"
  }
  "Expiration": {
    "Days": 3
  },
  "ID": "Expire soft-deleted blobstore objects"
  }
}
```
3. In terraform, change the set of tags for the bucket
4. `terraform plan` only show changes to the bucket tags
5. `terraform apply` change tags **and lifecycle policy**

### References

* #0000

### PR DESCRIPTION
**Pull request by pdecat**
Fixes #7156 

Changes proposed in this pull request:

* support S3 bucket lifecycle rule filters with a single tag and no prefix

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSS3Bucket_LifecycleBasic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSS3Bucket_LifecycleBasic -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]

=== RUN   TestAccAWSS3Bucket_LifecycleBasic
=== PAUSE TestAccAWSS3Bucket_LifecycleBasic
=== CONT  TestAccAWSS3Bucket_LifecycleBasic
--- PASS: TestAccAWSS3Bucket_LifecycleBasic (141.42s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       141.443s
```

TODO:
- [ ] verify fix in real situation
- [x] generate lifecycle rules with a single tag and no prefix the same way the web console does

Notes:

* Rather than trying to add an acceptance test that creates a lifecycle rule with a single tag and no prefix the same way the web console would have done, I've settled to adapt the provider's update implementation to match the web console behavior.

* Adding unit tests would probably be a good thing but this would require extracting lifecycle rules expanding/flattening code into functions and make the diff way less readable.

### CODE REVIEW

**Comment by pdecat** [comment]
Fix not working in real situation using the terraform configuration from #7156 :(

**Comment by pdecat** [comment]
Re-tested with more debug logs.

Read during plan phase:
```
2019-01-16T23:37:34.123+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351: <LifecycleConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Rule><ID>test</ID><Filter><Tag><Key>testtagname</Key><Value>testtagvalue</Value></Tag></Filter><Status>Enabled</Status><Transition><Days>30</Days><StorageClass>STANDARD_IA</StorageClass></Transition></Rule></LifecycleConfiguration>
2019-01-16T23:37:34.123+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351: 2019/01/16 23:37:34 [DEBUG] S3 bucket: s3.tf-test-pdecat-feeea921a342cce4687c932ed9e2, read lifecycle rule: {
2019-01-16T23:37:34.123+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351:   Filter: {
2019-01-16T23:37:34.123+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351:     Tag: {
2019-01-16T23:37:34.123+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351:       Key: "testtagname",
2019-01-16T23:37:34.123+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351:       Value: "testtagvalue"
2019-01-16T23:37:34.123+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351:     }
2019-01-16T23:37:34.123+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351:   },
2019-01-16T23:37:34.123+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351:   ID: "test",
2019-01-16T23:37:34.123+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351:   Status: "Enabled",
2019-01-16T23:37:34.123+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351:   Transitions: [{
2019-01-16T23:37:34.123+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351:       Days: 30,
2019-01-16T23:37:34.123+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351:       StorageClass: "STANDARD_IA"
2019-01-16T23:37:34.124+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351:     }]
2019-01-16T23:37:34.124+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351: }
```

Written during apply phase:
```
2019-01-16T23:37:43.554+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351: <LifecycleConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Rule><Filter><And><Prefix></Prefix><Tag><Key>testtagname</Key><Value>testtagvalue</Value></Tag></And></Filter><ID>test</ID><Status>Enabled</Status><Transition><Days>30</Days><StorageClass>STANDARD_IA</StorageClass></Transition></Rule></LifecycleConfiguration>
```

Re-read after apply phase:
```
2019-01-16T23:37:49.576+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351: <LifecycleConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Rule><ID>test</ID><Filter><And><Prefix></Prefix><Tag><Key>testtagname</Key><Value>testtagvalue</Value></Tag></And></Filter><Status>Enabled</Status><Transition><Days>30</Days><StorageClass>STANDARD_IA</StorageClass></Transition></Rule></LifecycleConfiguration>
2019-01-16T23:37:49.576+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351: 2019/01/16 23:37:49 [DEBUG] S3 bucket: s3.tf-test-pdecat-feeea921a342cce4687c932ed9e2, read lifecycle rule: {
2019-01-16T23:37:49.576+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351:   Filter: {
2019-01-16T23:37:49.576+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351:     And: {
2019-01-16T23:37:49.576+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351:       Prefix: "",
2019-01-16T23:37:49.576+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351:       Tags: [{
2019-01-16T23:37:49.576+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351:           Key: "testtagname",
2019-01-16T23:37:49.576+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351:           Value: "testtagvalue"
2019-01-16T23:37:49.576+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351:         }]
2019-01-16T23:37:49.576+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351:     }
2019-01-16T23:37:49.576+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351:   },
2019-01-16T23:37:49.576+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351:   ID: "test",
2019-01-16T23:37:49.576+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351:   Status: "Enabled",
2019-01-16T23:37:49.576+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351:   Transitions: [{
2019-01-16T23:37:49.576+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351:       Days: 30,
2019-01-16T23:37:49.576+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351:       StorageClass: "STANDARD_IA"
2019-01-16T23:37:49.576+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351:     }]
2019-01-16T23:37:49.576+0100 [DEBUG] plugin.terraform-provider-aws_v1.57.0-ee4ae351: }
```

File: aws/resource_aws_s3_bucket_test.go [hunk 1]
```diff
@@ -755,7 +755,7 @@ func TestAccAWSS3Bucket_Logging(t *testing.T) {
 	})
 }
 
-func TestAccAWSS3Bucket_Lifecycle(t *testing.T) {
+func TestAccAWSS3Bucket_LifecycleBasic(t *testing.T) {
```
Comment (pdecat) [inline aws/resource_aws_s3_bucket_test.go]: Note for reviewers: this allows to target this acceptance test without also matching the `TestAccAWSS3Bucket_LifecycleExpireMarkerOnly` test.

**Comment by pdecat** [comment]
Also worth noting, this case is somewhat documented in the vendored AWS SDK:

```
	// The Filter is used to identify objects that a Lifecycle Rule applies to.
	// A Filter must have exactly one of Prefix, Tag, or And specified.
	Filter *LifecycleRuleFilter `type:"structure"`
```
cf. https://github.com/terraform-providers/terraform-provider-aws/blob/v1.57.0/vendor/github.com/aws/aws-sdk-go/service/s3/api.go#L15319

**Comment by pdecat** [comment]
Acceptance test results:

```
# make testacc TESTARGS='-run=TestAccAWSS3Bucket_Lifecycle.*'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSS3Bucket_Lifecycle.* -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSS3Bucket_LifecycleBasic
=== PAUSE TestAccAWSS3Bucket_LifecycleBasic
=== RUN   TestAccAWSS3Bucket_LifecycleExpireMarkerOnly
=== PAUSE TestAccAWSS3Bucket_LifecycleExpireMarkerOnly
=== CONT  TestAccAWSS3Bucket_LifecycleBasic
=== CONT  TestAccAWSS3Bucket_LifecycleExpireMarkerOnly
--- PASS: TestAccAWSS3Bucket_LifecycleExpireMarkerOnly (95.62s)
--- PASS: TestAccAWSS3Bucket_LifecycleBasic (140.29s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       140.319s
```

**Comment by pdecat** [comment]
Hi @bflad, would you mind having a look at this one?

**Comment by pdecat** [comment]
Rebased on master.

**Comment by pdecat** [comment]
Rebased on master.

**Comment by pdecat** [comment]
Rebased on master, acceptance tests are no longer passing ;( :

```
# make testacc TEST=./aws TESTARGS='-run=TestAccAWSS3Bucket_LifecycleBasic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSS3Bucket_LifecycleBasic -timeout 120m
=== RUN   TestAccAWSS3Bucket_LifecycleBasic
=== PAUSE TestAccAWSS3Bucket_LifecycleBasic
=== CONT  TestAccAWSS3Bucket_LifecycleBasic
--- FAIL: TestAccAWSS3Bucket_LifecycleBasic (155.63s)
    testing.go:568: Step 2 error: After applying this step and refreshing, the plan was not empty:

        DIFF:

        UPDATE: aws_s3_bucket.bucket
          acceleration_status:                                            "" => ""
          acl:                                                            "public-read" => "public-read"
          arn:                                                            "arn:aws:s3:::tf-test-bucket-2576925322492803950" => "arn:aws:s3:::tf-test-bucket-2576925322492803950"
          bucket:                                                         "tf-test-bucket-2576925322492803950" => "tf-test-bucket-2576925322492803950"
          bucket_domain_name:                                             "tf-test-bucket-2576925322492803950.s3.amazonaws.com" => "tf-test-bucket-2576925322492803950.s3.amazonaws.com"
          bucket_regional_domain_name:                                    "tf-test-bucket-2576925322492803950.s3.us-west-2.amazonaws.com" => "tf-test-bucket-2576925322492803950.s3.us-we
st-2.amazonaws.com"
          cors_rule.#:                                                    "0" => "0"
          force_destroy:                                                  "false" => "false"
          hosted_zone_id:                                                 "Z3BJ6K6RIION7M" => "Z3BJ6K6RIION7M"
          id:                                                             "tf-test-bucket-2576925322492803950" => "tf-test-bucket-2576925322492803950"
          lifecycle_rule.#:                                               "3" => "0"
          lifecycle_rule.0.abort_incomplete_multipart_upload_days:        "0" => ""
          lifecycle_rule.0.enabled:                                       "true" => ""
          lifecycle_rule.0.expiration.#:                                  "0" => ""
          lifecycle_rule.0.id:                                            "id1" => ""
          lifecycle_rule.0.noncurrent_version_expiration.#:               "1" => ""
          lifecycle_rule.0.noncurrent_version_expiration.0.days:          "365" => ""
          lifecycle_rule.0.noncurrent_version_transition.#:               "2" => ""
          lifecycle_rule.0.noncurrent_version_transition.0.days:          "30" => ""
          lifecycle_rule.0.noncurrent_version_transition.0.storage_class: "STANDARD_IA" => ""
          lifecycle_rule.0.noncurrent_version_transition.1.days:          "60" => ""
          lifecycle_rule.0.noncurrent_version_transition.1.storage_class: "GLACIER" => ""
          lifecycle_rule.0.prefix:                                        "path1/" => ""
          lifecycle_rule.0.transition.#:                                  "0" => ""
          lifecycle_rule.1.abort_incomplete_multipart_upload_days:        "0" => ""
          lifecycle_rule.1.enabled:                                       "false" => ""
          lifecycle_rule.1.expiration.#:                                  "0" => ""
          lifecycle_rule.1.id:                                            "id2" => ""
          lifecycle_rule.1.noncurrent_version_expiration.#:               "1" => ""
          lifecycle_rule.1.noncurrent_version_expiration.0.days:          "365" => ""
          lifecycle_rule.1.noncurrent_version_transition.#:               "0" => ""
          lifecycle_rule.1.prefix:                                        "path2/" => ""
          lifecycle_rule.1.transition.#:                                  "0" => ""
          lifecycle_rule.2.abort_incomplete_multipart_upload_days:        "0" => ""
          lifecycle_rule.2.enabled:                                       "true" => ""
          lifecycle_rule.2.expiration.#:                                  "0" => ""
          lifecycle_rule.2.id:                                            "id3" => ""
          lifecycle_rule.2.noncurrent_version_expiration.#:               "0" => ""
          lifecycle_rule.2.noncurrent_version_transition.#:               "1" => ""
          lifecycle_rule.2.noncurrent_version_transition.0.days:          "0" => ""
          lifecycle_rule.2.noncurrent_version_transition.0.storage_class: "GLACIER" => ""
          lifecycle_rule.2.prefix:                                        "path3/" => ""
          lifecycle_rule.2.transition.#:                                  "0" => ""
          logging.#:                                                      "0" => "0"
          object_lock_configuration.#:                                    "0" => "0"
          region:                                                         "us-west-2" => "us-west-2"
          replication_configuration.#:                                    "0" => "0"
          request_payer:                                                  "BucketOwner" => "BucketOwner"
          server_side_encryption_configuration.#:                         "0" => "0"
          versioning.#:                                                   "1" => "1"
          versioning.0.enabled:                                           "false" => "false"
          versioning.0.mfa_delete:                                        "false" => "false"
          website.#:                                                      "0" => "0"



        STATE:

        aws_s3_bucket.bucket:
          ID = tf-test-bucket-2576925322492803950
          provider = provider.aws
          acceleration_status =
          acl = public-read
          arn = arn:aws:s3:::tf-test-bucket-2576925322492803950
          bucket = tf-test-bucket-2576925322492803950
          bucket_domain_name = tf-test-bucket-2576925322492803950.s3.amazonaws.com
          bucket_regional_domain_name = tf-test-bucket-2576925322492803950.s3.us-west-2.amazonaws.com
          force_destroy = false
          hosted_zone_id = Z3BJ6K6RIION7M
          lifecycle_rule.# = 3
          lifecycle_rule.0.abort_incomplete_multipart_upload_days = 0
          lifecycle_rule.0.enabled = true
          lifecycle_rule.0.id = id1
          lifecycle_rule.0.noncurrent_version_expiration.# = 1
          lifecycle_rule.0.noncurrent_version_expiration.0.days = 365
          lifecycle_rule.0.noncurrent_version_transition.# = 2
          lifecycle_rule.0.noncurrent_version_transition.0.days = 30
          lifecycle_rule.0.noncurrent_version_transition.0.storage_class = STANDARD_IA
          lifecycle_rule.0.noncurrent_version_transition.1.days = 60
          lifecycle_rule.0.noncurrent_version_transition.1.storage_class = GLACIER
          lifecycle_rule.0.prefix = path1/
          lifecycle_rule.1.abort_incomplete_multipart_upload_days = 0
          lifecycle_rule.1.enabled = false
          lifecycle_rule.1.id = id2
          lifecycle_rule.1.noncurrent_version_expiration.# = 1
          lifecycle_rule.1.noncurrent_version_expiration.0.days = 365
          lifecycle_rule.1.prefix = path2/
          lifecycle_rule.2.abort_incomplete_multipart_upload_days = 0
          lifecycle_rule.2.enabled = true
          lifecycle_rule.2.id = id3
          lifecycle_rule.2.noncurrent_version_transition.# = 1
          lifecycle_rule.2.noncurrent_version_transition.0.days = 0
          lifecycle_rule.2.noncurrent_version_transition.0.storage_class = GLACIER
          lifecycle_rule.2.prefix = path3/
          region = us-west-2
          request_payer = BucketOwner
          versioning.# = 1
          versioning.0.enabled = false
          versioning.0.mfa_delete = false
FAIL
FAIL    github.com/terraform-providers/terraform-provider-aws/aws       155.668s
make: *** [GNUmakefile:20: testacc] Error 1
```

**Comment by pdecat** [comment]
Rectification, they do pass:

```
# make testacc TEST=./aws TESTARGS='-run=TestAccAWSS3Bucket_LifecycleBasic'                                                                                                            
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSS3Bucket_LifecycleBasic -timeout 120m
=== RUN   TestAccAWSS3Bucket_LifecycleBasic
=== PAUSE TestAccAWSS3Bucket_LifecycleBasic
=== CONT  TestAccAWSS3Bucket_LifecycleBasic
--- PASS: TestAccAWSS3Bucket_LifecycleBasic (162.92s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       162.950s
```

**Comment by pdecat** [comment]
I've been running the test in a loop for a while and it is quite flaky and fails from time to time:

```
# while true ; do make testacc TEST=./aws TESTARGS='-run=TestAccAWSS3Bucket_LifecycleBasic -count=1' ; done
==> Checking that code complies with gofmt requirements...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSS3Bucket_LifecycleBasic -count=1 -timeout 120m
=== RUN   TestAccAWSS3Bucket_LifecycleBasic
=== PAUSE TestAccAWSS3Bucket_LifecycleBasic
=== CONT  TestAccAWSS3Bucket_LifecycleBasic
--- PASS: TestAccAWSS3Bucket_LifecycleBasic (159.71s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       159.746s
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSS3Bucket_LifecycleBasic -count=1 -timeout 120m
=== RUN   TestAccAWSS3Bucket_LifecycleBasic
=== PAUSE TestAccAWSS3Bucket_LifecycleBasic
=== CONT  TestAccAWSS3Bucket_LifecycleBasic
--- FAIL: TestAccAWSS3Bucket_LifecycleBasic (101.05s)
    testing.go:568: Step 1 error: After applying this step and refreshing, the plan was not empty:

        DIFF:

        UPDATE: aws_s3_bucket.bucket
          acceleration_status:                                            "" => ""
          acl:                                                            "private" => "private"
          arn:                                                            "arn:aws:s3:::tf-test-bucket-3908849865632763027" => "arn:aws:s3:::tf-test-bucket-3908849865632763027"
          bucket:                                                         "tf-test-bucket-3908849865632763027" => "tf-test-bucket-3908849865632763027"
          bucket_domain_name:                                             "tf-test-bucket-3908849865632763027.s3.amazonaws.com" => "tf-test-bucket-3908849865632763027.s3.amazonaws.com"
          bucket_regional_domain_name:                                    "tf-test-bucket-3908849865632763027.s3.us-west-2.amazonaws.com" => "tf-test-bucket-3908849865632763027.s3.us-we
st-2.amazonaws.com"
          cors_rule.#:                                                    "0" => "0"
          force_destroy:                                                  "false" => "false"
          hosted_zone_id:                                                 "Z3BJ6K6RIION7M" => "Z3BJ6K6RIION7M"
          id:                                                             "tf-test-bucket-3908849865632763027" => "tf-test-bucket-3908849865632763027"
          lifecycle_rule.#:                                               "6" => "3"
          lifecycle_rule.0.abort_incomplete_multipart_upload_days:        "0" => "0"
          lifecycle_rule.0.enabled:                                       "true" => "true"
          lifecycle_rule.0.expiration.#:                                  "1" => "0"
          lifecycle_rule.0.expiration.0.date:                             "" => ""
          lifecycle_rule.0.expiration.0.days:                             "365" => ""
          lifecycle_rule.0.expiration.0.expired_object_delete_marker:     "false" => ""
          lifecycle_rule.0.id:                                            "id1" => "id1"
          lifecycle_rule.0.noncurrent_version_expiration.#:               "0" => "1"
          lifecycle_rule.0.noncurrent_version_expiration.0.days:          "" => "365"
          lifecycle_rule.0.noncurrent_version_transition.#:               "0" => "2"
          lifecycle_rule.0.noncurrent_version_transition.0.days:          "" => "30"
          lifecycle_rule.0.noncurrent_version_transition.0.storage_class: "" => "STANDARD_IA"
          lifecycle_rule.0.noncurrent_version_transition.1.days:          "" => "60"
          lifecycle_rule.0.noncurrent_version_transition.1.storage_class: "" => "GLACIER"
          lifecycle_rule.0.prefix:                                        "path1/" => "path1/"
          lifecycle_rule.0.transition.#:                                  "5" => "0"
          lifecycle_rule.0.transition.0.date:                             "" => ""
          lifecycle_rule.0.transition.0.days:                             "210" => ""
          lifecycle_rule.0.transition.0.storage_class:                    "DEEP_ARCHIVE" => ""
          lifecycle_rule.0.transition.1.date:                             "" => ""
          lifecycle_rule.0.transition.1.days:                             "90" => ""
          lifecycle_rule.0.transition.1.storage_class:                    "ONEZONE_IA" => ""
          lifecycle_rule.0.transition.2.date:                             "" => ""
          lifecycle_rule.0.transition.2.days:                             "120" => ""
          lifecycle_rule.0.transition.2.storage_class:                    "GLACIER" => ""
          lifecycle_rule.0.transition.3.date:                             "" => ""
          lifecycle_rule.0.transition.3.days:                             "30" => ""
          lifecycle_rule.0.transition.3.storage_class:                    "STANDARD_IA" => ""
          lifecycle_rule.0.transition.4.date:                             "" => ""
          lifecycle_rule.0.transition.4.days:                             "60" => ""
          lifecycle_rule.0.transition.4.storage_class:                    "INTELLIGENT_TIERING" => ""
          lifecycle_rule.1.abort_incomplete_multipart_upload_days:        "0" => "0"
          lifecycle_rule.1.enabled:                                       "true" => "false"
          lifecycle_rule.1.expiration.#:                                  "1" => "0"
          lifecycle_rule.1.expiration.0.date:                             "2016-01-12" => ""
          lifecycle_rule.1.expiration.0.days:                             "0" => ""
          lifecycle_rule.1.expiration.0.expired_object_delete_marker:     "false" => ""
          lifecycle_rule.1.id:                                            "id2" => "id2"
          lifecycle_rule.1.noncurrent_version_expiration.#:               "0" => "1"
          lifecycle_rule.1.noncurrent_version_expiration.0.days:          "" => "365"
          lifecycle_rule.1.noncurrent_version_transition.#:               "0" => "0"
          lifecycle_rule.1.prefix:                                        "path2/" => "path2/"
          lifecycle_rule.1.transition.#:                                  "0" => "0"
          lifecycle_rule.2.abort_incomplete_multipart_upload_days:        "0" => "0"
          lifecycle_rule.2.enabled:                                       "true" => "true"
          lifecycle_rule.2.expiration.#:                                  "0" => "0"
          lifecycle_rule.2.id:                                            "id3" => "id3"
          lifecycle_rule.2.noncurrent_version_expiration.#:               "0" => "0"
          lifecycle_rule.2.noncurrent_version_transition.#:               "0" => "1"
          lifecycle_rule.2.noncurrent_version_transition.0.days:          "" => "0"
          lifecycle_rule.2.noncurrent_version_transition.0.storage_class: "" => "GLACIER"
          lifecycle_rule.2.prefix:                                        "path3/" => "path3/"
          lifecycle_rule.2.transition.#:                                  "1" => "0"
          lifecycle_rule.2.transition.0.date:                             "" => ""
          lifecycle_rule.2.transition.0.days:                             "0" => ""
          lifecycle_rule.2.transition.0.storage_class:                    "GLACIER" => ""
          lifecycle_rule.3.abort_incomplete_multipart_upload_days:        "0" => ""
          lifecycle_rule.3.enabled:                                       "true" => ""
          lifecycle_rule.3.expiration.#:                                  "1" => ""
          lifecycle_rule.3.expiration.0.date:                             "2016-01-12" => ""
          lifecycle_rule.3.expiration.0.days:                             "0" => ""
          lifecycle_rule.3.expiration.0.expired_object_delete_marker:     "false" => ""
          lifecycle_rule.3.id:                                            "id4" => ""
          lifecycle_rule.3.noncurrent_version_expiration.#:               "0" => ""
          lifecycle_rule.3.noncurrent_version_transition.#:               "0" => ""
          lifecycle_rule.3.prefix:                                        "path4/" => ""
          lifecycle_rule.3.tags.tagKey:                                   "tagValue" => ""
          lifecycle_rule.3.tags.terraform:                                "hashicorp" => ""
          lifecycle_rule.3.transition.#:                                  "0" => ""
          lifecycle_rule.4.abort_incomplete_multipart_upload_days:        "0" => ""
          lifecycle_rule.4.enabled:                                       "true" => ""
          lifecycle_rule.4.expiration.#:                                  "0" => ""
          lifecycle_rule.4.id:                                            "id5" => ""
          lifecycle_rule.4.noncurrent_version_expiration.#:               "0" => ""
          lifecycle_rule.4.noncurrent_version_transition.#:               "0" => ""
          lifecycle_rule.4.prefix:                                        "" => ""
          lifecycle_rule.4.tags.tagKey:                                   "tagValue" => ""
          lifecycle_rule.4.tags.terraform:                                "hashicorp" => ""
          lifecycle_rule.4.transition.#:                                  "1" => ""
          lifecycle_rule.4.transition.0.date:                             "" => ""
          lifecycle_rule.4.transition.0.days:                             "0" => ""
          lifecycle_rule.4.transition.0.storage_class:                    "GLACIER" => ""
          lifecycle_rule.5.abort_incomplete_multipart_upload_days:        "0" => ""
          lifecycle_rule.5.enabled:                                       "true" => ""
          lifecycle_rule.5.expiration.#:                                  "0" => ""
          lifecycle_rule.5.id:                                            "id6" => ""
          lifecycle_rule.5.noncurrent_version_expiration.#:               "0" => ""
          lifecycle_rule.5.noncurrent_version_transition.#:               "0" => ""
          lifecycle_rule.5.prefix:                                        "" => ""
          lifecycle_rule.5.tags.tagKey:                                   "tagValue" => ""
          lifecycle_rule.5.transition.#:                                  "1" => ""
          lifecycle_rule.5.transition.0.date:                             "" => ""
          lifecycle_rule.5.transition.0.days:                             "0" => ""
          lifecycle_rule.5.transition.0.storage_class:                    "GLACIER" => ""
          logging.#:                                                      "0" => "0"
          object_lock_configuration.#:                                    "0" => "0"
          region:                                                         "us-west-2" => "us-west-2"
          replication_configuration.#:                                    "0" => "0"
          request_payer:                                                  "BucketOwner" => "BucketOwner"
          server_side_encryption_configuration.#:                         "0" => "0"
          versioning.#:                                                   "1" => "1"
          versioning.0.enabled:                                           "false" => "false"
          versioning.0.mfa_delete:                                        "false" => "false"
          website.#:                                                      "0" => "0"



        STATE:

        aws_s3_bucket.bucket:
          ID = tf-test-bucket-3908849865632763027
          provider = provider.aws
          acceleration_status =
          acl = private
          arn = arn:aws:s3:::tf-test-bucket-3908849865632763027
          bucket = tf-test-bucket-3908849865632763027
          bucket_domain_name = tf-test-bucket-3908849865632763027.s3.amazonaws.com
          bucket_regional_domain_name = tf-test-bucket-3908849865632763027.s3.us-west-2.amazonaws.com
          force_destroy = false
          hosted_zone_id = Z3BJ6K6RIION7M
          lifecycle_rule.# = 6
          lifecycle_rule.0.abort_incomplete_multipart_upload_days = 0
          lifecycle_rule.0.enabled = true
          lifecycle_rule.0.expiration.# = 1
          lifecycle_rule.0.expiration.0.date =
          lifecycle_rule.0.expiration.0.days = 365
          lifecycle_rule.0.expiration.0.expired_object_delete_marker = false
          lifecycle_rule.0.id = id1
          lifecycle_rule.0.prefix = path1/
          lifecycle_rule.0.transition.# = 5
          lifecycle_rule.0.transition.0.date =
          lifecycle_rule.0.transition.0.days = 210
          lifecycle_rule.0.transition.0.storage_class = DEEP_ARCHIVE
          lifecycle_rule.0.transition.1.date =
          lifecycle_rule.0.transition.1.days = 90
          lifecycle_rule.0.transition.1.storage_class = ONEZONE_IA
          lifecycle_rule.0.transition.2.date =
          lifecycle_rule.0.transition.2.days = 120
          lifecycle_rule.0.transition.2.storage_class = GLACIER
          lifecycle_rule.0.transition.3.date =
          lifecycle_rule.0.transition.3.days = 30
          lifecycle_rule.0.transition.3.storage_class = STANDARD_IA
          lifecycle_rule.0.transition.4.date =
          lifecycle_rule.0.transition.4.days = 60
          lifecycle_rule.0.transition.4.storage_class = INTELLIGENT_TIERING
          lifecycle_rule.1.abort_incomplete_multipart_upload_days = 0
          lifecycle_rule.1.enabled = true
          lifecycle_rule.1.expiration.# = 1
          lifecycle_rule.1.expiration.0.date = 2016-01-12
          lifecycle_rule.1.expiration.0.days = 0
          lifecycle_rule.1.expiration.0.expired_object_delete_marker = false
          lifecycle_rule.1.id = id2
          lifecycle_rule.1.prefix = path2/
          lifecycle_rule.2.abort_incomplete_multipart_upload_days = 0
          lifecycle_rule.2.enabled = true
          lifecycle_rule.2.id = id3
          lifecycle_rule.2.prefix = path3/
          lifecycle_rule.2.transition.# = 1
          lifecycle_rule.2.transition.0.date =
          lifecycle_rule.2.transition.0.days = 0
          lifecycle_rule.2.transition.0.storage_class = GLACIER
          lifecycle_rule.3.abort_incomplete_multipart_upload_days = 0
          lifecycle_rule.3.enabled = true
          lifecycle_rule.3.expiration.# = 1
          lifecycle_rule.3.expiration.0.date = 2016-01-12
          lifecycle_rule.3.expiration.0.days = 0
          lifecycle_rule.3.expiration.0.expired_object_delete_marker = false
          lifecycle_rule.3.id = id4
          lifecycle_rule.3.prefix = path4/
          lifecycle_rule.3.tags.tagKey = tagValue
          lifecycle_rule.3.tags.terraform = hashicorp
          lifecycle_rule.4.abort_incomplete_multipart_upload_days = 0
          lifecycle_rule.4.enabled = true
          lifecycle_rule.4.id = id5
          lifecycle_rule.4.prefix =
          lifecycle_rule.4.tags.tagKey = tagValue
          lifecycle_rule.4.tags.terraform = hashicorp
          lifecycle_rule.4.transition.# = 1
          lifecycle_rule.4.transition.0.date =
          lifecycle_rule.4.transition.0.days = 0
          lifecycle_rule.4.transition.0.storage_class = GLACIER
          lifecycle_rule.5.abort_incomplete_multipart_upload_days = 0
          lifecycle_rule.5.enabled = true
          lifecycle_rule.5.id = id6
          lifecycle_rule.5.prefix =
          lifecycle_rule.5.tags.tagKey = tagValue
          lifecycle_rule.5.transition.# = 1
          lifecycle_rule.5.transition.0.date =
          lifecycle_rule.5.transition.0.days = 0
          lifecycle_rule.5.transition.0.storage_class = GLACIER
          region = us-west-2
          request_payer = BucketOwner
          versioning.# = 1
          versioning.0.enabled = false
          versioning.0.mfa_delete = false
FAIL
FAIL    github.com/terraform-providers/terraform-provider-aws/aws       101.090s
make: *** [GNUmakefile:20: testacc] Error 1
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSS3Bucket_LifecycleBasic -count=1 -timeout 120m
=== RUN   TestAccAWSS3Bucket_LifecycleBasic
=== PAUSE TestAccAWSS3Bucket_LifecycleBasic
=== CONT  TestAccAWSS3Bucket_LifecycleBasic
--- PASS: TestAccAWSS3Bucket_LifecycleBasic (150.63s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       150.663s
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSS3Bucket_LifecycleBasic -count=1 -timeout 120m
=== RUN   TestAccAWSS3Bucket_LifecycleBasic
=== PAUSE TestAccAWSS3Bucket_LifecycleBasic
=== CONT  TestAccAWSS3Bucket_LifecycleBasic
--- PASS: TestAccAWSS3Bucket_LifecycleBasic (148.47s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       148.490s
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSS3Bucket_LifecycleBasic -count=1 -timeout 120m
=== RUN   TestAccAWSS3Bucket_LifecycleBasic
=== PAUSE TestAccAWSS3Bucket_LifecycleBasic
=== CONT  TestAccAWSS3Bucket_LifecycleBasic
--- PASS: TestAccAWSS3Bucket_LifecycleBasic (149.58s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       149.626s
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSS3Bucket_LifecycleBasic -count=1 -timeout 120m
=== RUN   TestAccAWSS3Bucket_LifecycleBasic
=== PAUSE TestAccAWSS3Bucket_LifecycleBasic
=== CONT  TestAccAWSS3Bucket_LifecycleBasic
--- PASS: TestAccAWSS3Bucket_LifecycleBasic (148.51s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       148.546s
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSS3Bucket_LifecycleBasic -count=1 -timeout 120m
=== RUN   TestAccAWSS3Bucket_LifecycleBasic
=== PAUSE TestAccAWSS3Bucket_LifecycleBasic
=== CONT  TestAccAWSS3Bucket_LifecycleBasic
--- PASS: TestAccAWSS3Bucket_LifecycleBasic (148.21s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       148.249s
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSS3Bucket_LifecycleBasic -count=1 -timeout 120m
=== RUN   TestAccAWSS3Bucket_LifecycleBasic
=== PAUSE TestAccAWSS3Bucket_LifecycleBasic
=== CONT  TestAccAWSS3Bucket_LifecycleBasic
--- PASS: TestAccAWSS3Bucket_LifecycleBasic (150.35s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       150.392s
[...]
```

**Comment by pdecat** [comment]
Running the same test from master reveals similar issues (the test is named `TestAccAWSS3Bucket_Lifecycle` in master because I renamed it to `TestAccAWSS3Bucket_LifecycleBasic` for easier targeting, did not find a easy way to pass the trailing `$` to `make testacc`).

```
# while true ; do TF_ACC=1 go test ./aws -v -parallel 20 -run='TestAccAWSS3Bucket_Lifecycle$' -count=1 -timeout 120m ; done                                                            
=== RUN   TestAccAWSS3Bucket_Lifecycle
=== PAUSE TestAccAWSS3Bucket_Lifecycle
=== CONT  TestAccAWSS3Bucket_Lifecycle
--- FAIL: TestAccAWSS3Bucket_Lifecycle (84.85s)
    testing.go:568: Step 1 error: Check failed: Check 5/17 error: aws_s3_bucket.bucket: Attribute 'lifecycle_rule.0.noncurrent_version_expiration.80908210.days' not found
FAIL
FAIL    github.com/terraform-providers/terraform-provider-aws/aws       84.880s
=== RUN   TestAccAWSS3Bucket_Lifecycle
=== PAUSE TestAccAWSS3Bucket_Lifecycle
=== CONT  TestAccAWSS3Bucket_Lifecycle
        --- PASS: TestAccAWSS3Bucket_Lifecycle (159.00s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       159.041s
=== RUN   TestAccAWSS3Bucket_Lifecycle
=== PAUSE TestAccAWSS3Bucket_Lifecycle
=== CONT  TestAccAWSS3Bucket_Lifecycle
[...]
```

It looks like the `resourceAwsS3BucketLifecycleUpdate()` function should wait until the updates are effective on the AWS side.

**Comment by pdecat** [comment]
Also from master:

```
=== RUN   TestAccAWSS3Bucket_Lifecycle
=== PAUSE TestAccAWSS3Bucket_Lifecycle
=== CONT  TestAccAWSS3Bucket_Lifecycle
--- FAIL: TestAccAWSS3Bucket_Lifecycle (160.76s)
    testing.go:568: Step 2 error: After applying this step and refreshing, the plan was not empty:

        DIFF:

        UPDATE: aws_s3_bucket.bucket
          acceleration_status:                                            "" => ""
          acl:                                                            "public-read" => "public-read"
          arn:                                                            "arn:aws:s3:::tf-test-bucket-3907504849674326409" => "arn:aws:s3:::tf-test-bucket-3907504849674326409"
          bucket:                                                         "tf-test-bucket-3907504849674326409" => "tf-test-bucket-3907504849674326409"
          bucket_domain_name:                                             "tf-test-bucket-3907504849674326409.s3.amazonaws.com" => "tf-test-bucket-3907504849674326409.s3.amazonaws.com"
          bucket_regional_domain_name:                                    "tf-test-bucket-3907504849674326409.s3.us-west-2.amazonaws.com" => "tf-test-bucket-3907504849674326409.s3.us-we
st-2.amazonaws.com"
          cors_rule.#:                                                    "0" => "0"
          force_destroy:                                                  "false" => "false"
          hosted_zone_id:                                                 "Z3BJ6K6RIION7M" => "Z3BJ6K6RIION7M"
          id:                                                             "tf-test-bucket-3907504849674326409" => "tf-test-bucket-3907504849674326409"
          lifecycle_rule.#:                                               "3" => "0"
          lifecycle_rule.0.abort_incomplete_multipart_upload_days:        "0" => ""
          lifecycle_rule.0.enabled:                                       "true" => ""
          lifecycle_rule.0.expiration.#:                                  "0" => ""
          lifecycle_rule.0.id:                                            "id1" => ""
          lifecycle_rule.0.noncurrent_version_expiration.#:               "1" => ""
          lifecycle_rule.0.noncurrent_version_expiration.0.days:          "365" => ""
          lifecycle_rule.0.noncurrent_version_transition.#:               "2" => ""
          lifecycle_rule.0.noncurrent_version_transition.0.days:          "30" => ""
          lifecycle_rule.0.noncurrent_version_transition.0.storage_class: "STANDARD_IA" => ""
          lifecycle_rule.0.noncurrent_version_transition.1.days:          "60" => ""
          lifecycle_rule.0.noncurrent_version_transition.1.storage_class: "GLACIER" => ""
          lifecycle_rule.0.prefix:                                        "path1/" => ""
          lifecycle_rule.0.transition.#:                                  "0" => ""
          lifecycle_rule.1.abort_incomplete_multipart_upload_days:        "0" => ""
          lifecycle_rule.1.enabled:                                       "false" => ""
          lifecycle_rule.1.expiration.#:                                  "0" => ""
          lifecycle_rule.1.id:                                            "id2" => ""
          lifecycle_rule.1.noncurrent_version_expiration.#:               "1" => ""
          lifecycle_rule.1.noncurrent_version_expiration.0.days:          "365" => ""
          lifecycle_rule.1.noncurrent_version_transition.#:               "0" => ""
          lifecycle_rule.1.prefix:                                        "path2/" => ""
          lifecycle_rule.1.transition.#:                                  "0" => ""
          lifecycle_rule.2.abort_incomplete_multipart_upload_days:        "0" => ""
          lifecycle_rule.2.enabled:                                       "true" => ""
          lifecycle_rule.2.expiration.#:                                  "0" => ""
          lifecycle_rule.2.id:                                            "id3" => ""
          lifecycle_rule.2.noncurrent_version_expiration.#:               "0" => ""
          lifecycle_rule.2.noncurrent_version_transition.#:               "1" => ""
          lifecycle_rule.2.noncurrent_version_transition.0.days:          "0" => ""
          lifecycle_rule.2.noncurrent_version_transition.0.storage_class: "GLACIER" => ""
          lifecycle_rule.2.prefix:                                        "path3/" => ""
          lifecycle_rule.2.transition.#:                                  "0" => ""
          logging.#:                                                      "0" => "0"
          object_lock_configuration.#:                                    "0" => "0"
          region:                                                         "us-west-2" => "us-west-2"
          replication_configuration.#:                                    "0" => "0"
          request_payer:                                                  "BucketOwner" => "BucketOwner"
          server_side_encryption_configuration.#:                         "0" => "0"
          versioning.#:                                                   "1" => "1"
          versioning.0.enabled:                                           "false" => "false"
          versioning.0.mfa_delete:                                        "false" => "false"
          website.#:                                                      "0" => "0"



        STATE:

        aws_s3_bucket.bucket:
          ID = tf-test-bucket-3907504849674326409
          provider = provider.aws
          acceleration_status =
          acl = public-read
          arn = arn:aws:s3:::tf-test-bucket-3907504849674326409
          bucket = tf-test-bucket-3907504849674326409
          bucket_domain_name = tf-test-bucket-3907504849674326409.s3.amazonaws.com
          bucket_regional_domain_name = tf-test-bucket-3907504849674326409.s3.us-west-2.amazonaws.com
          force_destroy = false
          hosted_zone_id = Z3BJ6K6RIION7M
          lifecycle_rule.# = 3
          lifecycle_rule.0.abort_incomplete_multipart_upload_days = 0
          lifecycle_rule.0.enabled = true
          lifecycle_rule.0.id = id1
          lifecycle_rule.0.noncurrent_version_expiration.# = 1
          lifecycle_rule.0.noncurrent_version_expiration.0.days = 365
          lifecycle_rule.0.noncurrent_version_transition.# = 2
          lifecycle_rule.0.noncurrent_version_transition.0.days = 30
          lifecycle_rule.0.noncurrent_version_transition.0.storage_class = STANDARD_IA
          lifecycle_rule.0.noncurrent_version_transition.1.days = 60
          lifecycle_rule.0.noncurrent_version_transition.1.storage_class = GLACIER
          lifecycle_rule.0.prefix = path1/
          lifecycle_rule.1.abort_incomplete_multipart_upload_days = 0
          lifecycle_rule.1.enabled = false
          lifecycle_rule.1.id = id2
          lifecycle_rule.1.noncurrent_version_expiration.# = 1
          lifecycle_rule.1.noncurrent_version_expiration.0.days = 365
          lifecycle_rule.1.prefix = path2/
          lifecycle_rule.2.abort_incomplete_multipart_upload_days = 0
          lifecycle_rule.2.enabled = true
          lifecycle_rule.2.id = id3
          lifecycle_rule.2.noncurrent_version_transition.# = 1
          lifecycle_rule.2.noncurrent_version_transition.0.days = 0
          lifecycle_rule.2.noncurrent_version_transition.0.storage_class = GLACIER
          lifecycle_rule.2.prefix = path3/
          region = us-west-2
          request_payer = BucketOwner
          versioning.# = 1
          versioning.0.enabled = false
          versioning.0.mfa_delete = false
FAIL
FAIL    github.com/terraform-providers/terraform-provider-aws/aws       160.793s
```

**Comment by pdecat** [comment]
Here's a complete debug output when it is failing on master: https://gist.github.com/pdecat/8a74f9b2a8d3bc1fd075b747f1e15549

**Comment by pdecat** [comment]
Rebased on master to resolve conflicts.

**Comment by pdecat** [comment]
Thanks @nywilken!

**Comment by bflad** [comment]
This has been released in [version 2.19.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2190-july-11-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

For further feature requests or bug reports with this functionality, please create a [new GitHub issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new/choose) following the template for triage. Thanks!
