### PR TITLE
resource/aws_cloudfront_distribution: Ignore attribute ordering of cache behavior forwarded values `headers` and cookies `whitelisted_names` arguments

### LINKED ISSUE #7867: Cloudfront Distribution changes ForwardedValues Headers for Behaviours
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.11

### Affected Resource(s)

* aws_cloudfront_distribution

AWS Provider version: 2.1.0

### Terraform Configuration Files

```hcl
resource "aws_cloudfront_distribution" "self" {
  enabled         = true
  is_ipv6_enabled = true
  comment         = "public assets"
  price_class     = "PriceClass_100"
  aliases         = ["${aws_acm_certificate.cdn_cert.domain_name}"]
# ...
  ordered_cache_behavior {
    allowed_methods        = ["GET", "HEAD", "OPTIONS"]
    cached_methods         = ["GET", "HEAD"]
    target_origin_id       = "${local.s3_origin_id}"
    viewer_protocol_policy = "allow-all"
    compress               = true
    default_ttl            = 86400
    min_ttl                = 3600
    max_ttl                = 2592000

    path_pattern = "/foo/*"

    forwarded_values {
      query_string = false

      headers = [
        "Origin",
        "Access-Control-Request-Headers",
        "Access-Control-Request-Method",
      ]

      cookies {
        forward = "none"
      }
    }
  }
# ...
}
```

### Expected Behavior

A clean diff, since the code wasn't changed.

### Actual Behavior

There's always a diff for the `forwarwarded values headers`: 

screenshot 2019-03-08 at 11 48 59

### Steps to Reproduce

1. `terraform plan`
1. `terraform apply`
1. `terraform plan`

### PR DESCRIPTION
**Pull request by bflad**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #7867

Output from acceptance testing prior to code updates:

```
--- FAIL: TestAccAWSCloudFrontDistribution_DefaultCacheBehavior_ForwardedValues_Cookies_WhitelistedNames (528.44s)
    testing.go:538: Step 0 error: After applying this step, the plan was not empty:

        DIFF:

        UPDATE: aws_cloudfront_distribution.test
          default_cache_behavior.0.forwarded_values.0.cookies.0.whitelisted_names.0: "test1" => "test2"
          default_cache_behavior.0.forwarded_values.0.cookies.0.whitelisted_names.1: "test2" => "test3"
          default_cache_behavior.0.forwarded_values.0.cookies.0.whitelisted_names.2: "test3" => "test1"

--- FAIL: TestAccAWSCloudFrontDistribution_DefaultCacheBehavior_ForwardedValues_Headers (528.49s)
    testing.go:538: Step 0 error: After applying this step, the plan was not empty:

        DIFF:

        UPDATE: aws_cloudfront_distribution.test
          default_cache_behavior.0.forwarded_values.0.headers.0: "Access-Control-Request-Headers" => "Origin"
          default_cache_behavior.0.forwarded_values.0.headers.1: "Access-Control-Request-Method" => "Access-Control-Request-Headers"
          default_cache_behavior.0.forwarded_values.0.headers.2: "Origin" => "Access-Control-Request-Method"

--- FAIL: TestAccAWSCloudFrontDistribution_OrderedCacheBehavior_ForwardedValues_Cookies_WhitelistedNames (528.46s)
    testing.go:538: Step 0 error: After applying this step, the plan was not empty:

        DIFF:

        UPDATE: aws_cloudfront_distribution.test
          ordered_cache_behavior.0.forwarded_values.0.cookies.0.whitelisted_names.0: "test1" => "test2"
          ordered_cache_behavior.0.forwarded_values.0.cookies.0.whitelisted_names.1: "test2" => "test3"
          ordered_cache_behavior.0.forwarded_values.0.cookies.0.whitelisted_names.2: "test3" => "test1"

--- FAIL: TestAccAWSCloudFrontDistribution_OrderedCacheBehavior_ForwardedValues_Headers (528.43s)
    testing.go:538: Step 0 error: After applying this step, the plan was not empty:

        DIFF:

        UPDATE: aws_cloudfront_distribution.test
          ordered_cache_behavior.0.forwarded_values.0.headers.0: "Access-Control-Request-Headers" => "Origin"
          ordered_cache_behavior.0.forwarded_values.0.headers.1: "Access-Control-Request-Method" => "Access-Control-Request-Headers"
          ordered_cache_behavior.0.forwarded_values.0.headers.2: "Origin" => "Access-Control-Request-Method"
```

Output from acceptance testing:

```
--- PASS: TestAccAWSCloudFrontDistribution_Origin_EmptyOriginID (2.56s)
--- PASS: TestAccAWSCloudFrontDistribution_Origin_EmptyDomainName (2.56s)
--- PASS: TestAccAWSCloudFrontDistribution_OrderedCacheBehavior_ForwardedValues_Cookies_WhitelistedNames (543.49s)
--- PASS: TestAccAWSCloudFrontDistribution_DefaultCacheBehavior_ForwardedValues_Headers (544.62s)
--- PASS: TestAccAWSCloudFrontDistribution_OrderedCacheBehavior_ForwardedValues_Headers (546.32s)
--- PASS: TestAccAWSCloudFrontDistribution_disappears (550.45s)
--- PASS: TestAccAWSCloudFrontDistribution_DefaultCacheBehavior_ForwardedValues_Cookies_WhitelistedNames (580.39s)
--- PASS: TestAccAWSCloudFrontDistribution_IsIPV6EnabledConfig (1173.77s)
--- PASS: TestAccAWSCloudFrontDistribution_RetainOnDelete (1178.86s)
--- PASS: TestAccAWSCloudFrontDistribution_orderedCacheBehavior (1181.80s)
--- PASS: TestAccAWSCloudFrontDistribution_noCustomErrorResponseConfig (1183.92s)
--- PASS: TestAccAWSCloudFrontDistribution_customOrigin (1270.14s)
--- PASS: TestAccAWSCloudFrontDistribution_S3Origin (1270.44s)
--- PASS: TestAccAWSCloudFrontDistribution_OriginGroups (1268.27s)
--- PASS: TestAccAWSCloudFrontDistribution_noOptionalItemsConfig (1271.35s)
--- PASS: TestAccAWSCloudFrontDistribution_multiOrigin (1272.23s)
--- PASS: TestAccAWSCloudFrontDistribution_WaitForDeployment (1269.96s)
--- PASS: TestAccAWSCloudFrontDistribution_HTTP11Config (1275.52s)
--- PASS: TestAccAWSCloudFrontDistribution_ViewerCertificate_AcmCertificateArn (1276.02s)
--- PASS: TestAccAWSCloudFrontDistribution_ViewerCertificate_AcmCertificateArn_ConflictsWithCloudFrontDefaultCertificate (1284.86s)
--- PASS: TestAccAWSCloudFrontDistribution_Enabled (1736.60s)
--- PASS: TestAccAWSCloudFrontDistribution_S3OriginWithTags (1886.36s)
```

### CODE REVIEW

File: aws/resource_aws_cloudfront_distribution_test.go [hunk 1]
```diff
@@ -1627,11 +1795,111 @@ resource "aws_cloudfront_distribution" "failover_distribution" {
 }
 `
 
-func testAccAWSCloudFrontDistributionConfigEnabled(enabled, retainOnDelete bool) string {
+func testAccAWSCloudFrontDistributionConfigDefaultCacheBehaviorForwardedValuesCookiesWhitelistedNamesUnordered2(retainOnDelete bool) string {
```
Comment (nywilken) [inline aws/resource_aws_cloudfront_distribution_test.go]: Try to say that three times fast :wink:

**Comment by bflad** [comment]
This has been released in [version 2.5.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#250-april-05-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
