### PR TITLE
Separate aws_default_security_group definition from aws_security_group

### LINKED ISSUE #14559: resource/aws_default_security_group: Re-use of aws_security_group Read Causing SDKv2 Acceptance Test Panics
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Terraform Plugin SDK version 2 is more aggressive (in a good way) about reporting resources that are incorrectly attempting to set Terraform state. Any errors with `(*github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceData).Set()` are automatically promoted to a panic in acceptance testing so they are more visible in cases where error checking in the resource logic is not being performed.

In this case, the `aws_default_security_group` resource is reporting:

```
=== CONT  TestAccAWSDefaultSecurityGroup_basic
------- Stderr: -------
panic: Invalid address to set: []string{"name_prefix"}
goroutine 397 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).Set(0xc0011e3400, 0x667770f, 0xb, 0x5320ea0, 0xb0c60e0, 0x0, 0x0)
  /opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource_data.go:188 +0x388
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsSecurityGroupRead(0xc0011e3400, 0x5ab8820, 0xc0006c4000, 0x5ab8801, 0xc0006c4000)
  /opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_security_group.go:386 +0x89d
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsSecurityGroupUpdate(0xc0011e3400, 0x5ab8820, 0xc0006c4000, 0x0, 0x0)
  /opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_security_group.go:447 +0x22c
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsDefaultSecurityGroupCreate(0xc0011e3400, 0x5ab8820, 0xc0006c4000, 0x6, 0xffffffffffffffff)
  /opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_default_security_group.go:104 +0x889

=== CONT  TestAccAWSDefaultSecurityGroup_classic
------- Stderr: -------
panic: Invalid address to set: []string{"name_prefix"}
goroutine 246 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).Set(0xc001300800, 0x667770f, 0xb, 0x5320ea0, 0xb0c60e0, 0x0, 0x0)
  /opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource_data.go:188 +0x388
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsSecurityGroupRead(0xc001300800, 0x5ab8820, 0xc00090a000, 0x5ab8801, 0xc00090a000)
  /opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_security_group.go:386 +0x89d
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsSecurityGroupUpdate(0xc001300800, 0x5ab8820, 0xc00090a000, 0x0, 0x0)
  /opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_security_group.go:447 +0x22c
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsDefaultSecurityGroupCreate(0xc001300800, 0x5ab8820, 0xc00090a000, 0x3, 0xffffffffffffffff)
  /opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_default_security_group.go:104 +0x889
```

EC2 Default Security Groups cannot have a configurable name, so the code removes the schema attribute:

https://github.com/terraform-providers/terraform-provider-aws/blob/d148d85330ff4cc95700043d8e6947fa71db7f2f/aws/resource_aws_default_security_group.go#L25-L30

While reusing the `Read` function of the `aws_security_group` resource:

https://github.com/terraform-providers/terraform-provider-aws/blob/d148d85330ff4cc95700043d8e6947fa71db7f2f/aws/resource_aws_default_security_group.go#L14-L15

We generally discourage this type of re-use of both the schema and resource functions across multiple resources. In this case re-implementing the correct, separate logic in the `aws_default_security_group` resource would fix the panics although re-implementing the correct, separate schema would also be nice.

### Affected Resource(s)

* aws_default_security_group

### Definition of Done

* [ ] `TestAccAWSDefaultSecurityGroup_` testing passes

### References

* [Contributing Guide on Running/Writing Acceptance Testing](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/contributing/running-and-writing-acceptance-tests.md)

### PR DESCRIPTION
**Pull request by gdavison**
Separates aws_default_security_group definition from aws_security_group.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #14559

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSDefaultSecurityGroup_'

--- PASS: TestAccAWSDefaultSecurityGroup_Vpc_basic (107.00s)
--- PASS: TestAccAWSDefaultSecurityGroup_Classic_basic (76.73s)
--- PASS: TestAccAWSDefaultSecurityGroup_Vpc_empty (57.64s)
```

### CODE REVIEW

File: GNUmakefile [hunk 1]
```diff
@@ -5,6 +5,7 @@ GOFMT_FILES?=$$(find . -name '*.go' |grep -v vendor)
 PKG_NAME=aws
 WEBSITE_REPO=github.com/hashicorp/terraform-website
 TEST_COUNT?=1
+ACCTEST_PARALLEL?=20
```
Comment (bflad) [inline GNUmakefile:8]: FYI, the parameter in TeamCity is `ACCTEST_PARALLELISM`

File: aws/internal/service/ec2/waiter/status.go [hunk 2]
```diff
@@ -85,12 +85,7 @@ const (
 // ClientVpnAuthorizationRuleStatus fetches the Client VPN authorization rule and its Status
 func ClientVpnAuthorizationRuleStatus(conn *ec2.EC2, authorizationRuleID string) resource.StateRefreshFunc {
 	return func() (interface{}, string, error) {
-		endpointID, targetNetworkCidr, accessGroupID, err := tfec2.ClientVpnAuthorizationRuleParseID(authorizationRuleID)
```
Comment (bflad) [inline aws/internal/service/ec2/waiter/status.go:88]: These changes for EC2 Client VPN look unrelated and I'm not sure their impact.

File: aws/internal/service/ec2/waiter/status.go [hunk 3]
```diff
@@ -124,12 +119,7 @@ const (
 // ClientVpnRouteStatus fetches the Client VPN route and its Status
 func ClientVpnRouteStatus(conn *ec2.EC2, routeID string) resource.StateRefreshFunc {
 	return func() (interface{}, string, error) {
-		endpointID, targetSubnetID, destinationCidr, err := tfec2.ClientVpnRouteParseID(routeID)
```
Comment (bflad) [inline aws/internal/service/ec2/waiter/status.go:127]: Same here.

File: aws/resource_aws_default_security_group.go [hunk 4]
```diff
@@ -1,40 +1,188 @@
...
+	return &schema.Resource{
+		Create: resourceAwsDefaultSecurityGroupCreate,
+		Read:   resourceAwsDefaultSecurityGroupRead,
+		Update: resourceAwsDefaultSecurityGroupUpdate,
+		Delete: resourceAwsDefaultSecurityGroupDelete,
+		Importer: &schema.ResourceImporter{
+			State: schema.ImportStatePassthrough,
+		},
+
+		SchemaVersion: 1,
```
Comment (bflad) [inline aws/resource_aws_default_security_group.go:30]: We need to include the matching `MigrateState:  resourceAwsSecurityGroupMigrateState,` here as well, or it can generate errors for existing states that upgrade provider versions.

File: aws/resource_aws_default_security_group.go [hunk 5]
```diff
@@ -87,21 +236,111 @@ func resourceAwsDefaultSecurityGroupCreate(d *schema.ResourceData, meta interfac
...
+	}
+
+	d.Set("arn", sgArn.String())
+	d.Set("description", group.Description)
+	d.Set("name", group.GroupName)
+	d.Set("owner_id", group.OwnerId)
+	d.Set("vpc_id", group.VpcId)
+
+	if err := d.Set("ingress", ingressRules); err != nil {
+		log.Printf("[WARN] Error setting Ingress rule set for (%s): %s", d.Id(), err)
```
Comment (bflad) [inline aws/resource_aws_default_security_group.go:296]: Ah legacy code, at some point these should return errors instead.

File: aws/resource_aws_default_security_group.go [hunk 6]
```diff
@@ -87,21 +236,111 @@ func resourceAwsDefaultSecurityGroupCreate(d *schema.ResourceData, meta interfac
...
+			return fmt.Errorf("error adding EC2 Default Security Group (%s) tags: %w", d.Id(), err)
 		}
 	}
 
 	if err := revokeDefaultSecurityGroupRules(meta, g); err != nil {
-		return fmt.Errorf("%s", err)
+		return err
+	}
+
+	return resourceAwsDefaultSecurityGroupUpdate(d, meta)
```
Comment (bflad) [inline aws/resource_aws_default_security_group.go:253]: Not for this PR but we should get these two resources switched from calling Create -> Update and instead Create -> Read. 👍

File: aws/resource_aws_default_security_group_test.go [hunk 7]
```diff
@@ -12,66 +12,167 @@ import (
...
+					resource.TestCheckResourceAttr(resourceName, "egress.#", "1"),
+					tfawsresource.TestCheckTypeSetElemNestedAttrs(resourceName, "egress.*", map[string]string{
+						"protocol":      "tcp",
+						"from_port":     "80",
+						"to_port":       "8000",
+						"cidr_blocks.#": "1",
+						"cidr_blocks.0": "10.0.0.0/8",
+					}),
+					testAccCheckAWSDefaultSecurityGroupARN(resourceName, &group),
+					testAccCheckAWSDefaultSecurityGroupOwnerID(resourceName),
```
Comment (bflad) [inline aws/resource_aws_default_security_group_test.go:50]: This can be replaced with the existing function:

```suggestion
					testAccCheckResourceAttrAccountID(resourceName, "owner_id"),
```

File: aws/resource_aws_default_security_group_test.go [hunk 8]
```diff
@@ -12,66 +12,167 @@ import (
...
+					tfawsresource.TestCheckTypeSetElemNestedAttrs(resourceName, "ingress.*", map[string]string{
 						"protocol":      "tcp",
 						"from_port":     "80",
 						"to_port":       "8000",
 						"cidr_blocks.#": "1",
 						"cidr_blocks.0": "10.0.0.0/8",
 					}),
+					resource.TestCheckResourceAttr(resourceName, "egress.#", "0"),
+					testAccCheckAWSDefaultSecurityGroupARN(resourceName, &group),
+					testAccCheckAWSDefaultSecurityGroupOwnerID(resourceName),
```
Comment (bflad) [inline aws/resource_aws_default_security_group_test.go:128]: Samesies:

```suggestion
					testAccCheckResourceAttrAccountID(resourceName, "owner_id"),
```

File: aws/resource_aws_default_security_group_test.go [hunk 9]
```diff
@@ -12,66 +12,167 @@ import (
...
+				ImportStateVerifyIgnore: []string{"revoke_rules_on_delete"},
+			},
 		},
 	})
 }
 
+// This test currently fails because it does not clear tags when adopting the resource, resulting
+// in a non-empty plan.
+// https://github.com/terraform-providers/terraform-provider-aws/issues/14631
+// func TestAccAWSDefaultSecurityGroup_Classic_empty(t *testing.T) {
```
Comment (bflad) [inline aws/resource_aws_default_security_group_test.go:150]: Instead of commenting this out, it can be implemented and the comment moved to `TestAccSkip("...")` as the first line. 👍

File: aws/internal/service/ec2/waiter/status.go (hunk 2 above)
Comment (gdavison) [reply aws/internal/service/ec2/waiter/status.go:88]: Heh, yeah. I saw these when I was creating `SecurityGroupStatus()` and `finder. SecurityGroupByID()`. It inlines what already exists in `finder.ClientVpnAuthorizationRuleByID()` maybe shouldn't really be included here.
