### PR TITLE
r/user_pool_domain - remove from state when deleted + move waiters to their own package

### LINKED ISSUE #5313: Cognito domain doesn't delete during destroy
### Terraform Version

Terraform v0.10.8
AWS provider 1.21.0

### Affected Resource(s)

aws_cognito_user_pool_domain

### Terraform Configuration Files

Below is an excerpt from terraform file to create aws_cognito_user_pool_domain .

```hcl
# Pool domain
resource "aws_cognito_user_pool_domain" "domain" {
  domain       = "${var.userpooldomain}"
  user_pool_id = "${aws_cognito_user_pool.pool.id}"
}
```

### Expected Behavior

domain should be deleted by terraform apply, when the resource is marked for destroy.

### Actual Behavior

Domain isn't deleted and throws error message

aws_cognito_user_pool_domain.domain: InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, DeleteUserPoolDomainInput.UserPoolId.

### Steps to Reproduce

1. Change the module name
2. Run terraform plan and apply(Module name is changed and existing pool is deleted and a new user pool(with new name) is created.
4. Modify any change for the new user pool
5. terraform plan
6. terraform apply

### PR DESCRIPTION
**Pull request by DrFaust92**
improve check for disappears + test

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #5313

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource_aws_user_pool_domain - remove from state when deleted
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSCognitoUserPoolDomain_'
--- PASS: TestAccAWSCognitoUserPoolDomain_basic (54.56s)
--- SKIP: TestAccAWSCognitoUserPoolDomain_custom (0.00s)
--- PASS: TestAccAWSCognitoUserPoolDomain_disappears (46.92s)
```

### CODE REVIEW

File: aws/internal/service/cognitoidentityprovider/waiter/status.go [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+func UserPoolDomainStatus(conn *cognitoidentityprovider.CognitoIdentityProvider, domain string) resource.StateRefreshFunc {
+	return func() (interface{}, string, error) {
+		input := &cognitoidentityprovider.DescribeUserPoolDomainInput{
+			Domain: aws.String(domain),
+		}
+
+		output, err := conn.DescribeUserPoolDomain(input)
+
+		if err != nil {
+			return nil, "", err
```
Comment (ewbankkit) [inline aws/internal/service/cognitoidentityprovider/waiter/status.go:19]: I suggest a pattern of

```go
const (
	userPoolDomainStatusNotFound = "NotFound"
	userPoolDomainStatusUnknown  = "Unknown"
)

...

		if err != nil {
			return nil, userPoolDomainStatusUnknown, err
		}

		if output == nil {
			return nil, userPoolDomainStatusNotFound, nil
		}
```

Although these statuses are never explicitly tested I think having a value other than `""` helps with logging etc.
Having the constant names lowercase ensures they're not used outside this package.

File: aws/internal/service/cognitoidentityprovider/waiter/waiter.go [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+)
+
+// UserPoolDomainDeleted waits for an Operation to return Success
+func UserPoolDomainDeleted(conn *cognitoidentityprovider.CognitoIdentityProvider, domain string) (*cognitoidentityprovider.DescribeUserPoolDomainOutput, error) {
+	stateConf := &resource.StateChangeConf{
+		Pending: []string{
+			cognitoidentityprovider.DomainStatusTypeUpdating,
+			cognitoidentityprovider.DomainStatusTypeDeleting,
+		},
+		Target:  []string{""},
```
Comment (ewbankkit) [inline aws/internal/service/cognitoidentityprovider/waiter/waiter.go:23]: I think the "correct" way to do this is `Target: []string{},`:

https://github.com/terraform-providers/terraform-provider-aws/blob/691d0645ceed9453a8fc77a88e7fb0fce29b1ad3/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource/state.go#L122-L131

Comment (DrFaust92) [reply aws/internal/service/cognitoidentityprovider/waiter/waiter.go:23]: this failed for me 
```
        Error: error waiting for User Pool Domain (tf-acc-test-domain-3112558782247577448) deletion: unexpected state '', wanted target ''. last error: %!s(<nil>)
```

Comment (ewbankkit) [reply aws/internal/service/cognitoidentityprovider/waiter/waiter.go:23]: Now worried about how other code works 😄 ...

Comment (ewbankkit) [reply aws/internal/service/cognitoidentityprovider/waiter/waiter.go:23]: Yes, that's what's happening here:

```
2020/08/19 10:14:59 [DEBUG] [aws-sdk-go] DEBUG: Response cognito-idp/DescribeUserPoolDomain Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Connection: close
Content-Length: 24
Content-Type: application/x-amz-json-1.1
Date: Wed, 19 Aug 2020 14:14:59 GMT
X-Amzn-Requestid: abe5941d-5d1e-4153-a926-84cfbfce7f91


-----------------------------------------------------
2020/08/19 10:14:59 [DEBUG] [aws-sdk-go] {"DomainDescription":{}}
```

File: aws/internal/service/cognitoidentityprovider/waiter/waiter.go [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+	stateConf := &resource.StateChangeConf{
+		Pending: []string{
+			cognitoidentityprovider.DomainStatusTypeCreating,
+			cognitoidentityprovider.DomainStatusTypeUpdating,
+		},
+		Target: []string{
+			cognitoidentityprovider.DomainStatusTypeActive,
+		},
+		Refresh:    UserPoolDomainStatus(conn, domain),
+		MinTimeout: UserPoolDomainCreateTimeout,
```
[the remark this answers is not in the document]
Comment (DrFaust92) [reply aws/internal/service/cognitoidentityprovider/waiter/waiter.go:47]: removed! tests are passing
