### PR TITLE
aws_acm_certificate: fix subject_alternative_names forces recreation

### LINKED ISSUE #8531: aws_acm_certificate subject_alternative_names & domain_validation_options get returned in a different order each time
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.13
+ provider.aws v2.8.0
```

### Affected Resource(s)

* [aws_acm_certificate](https://www.terraform.io/docs/providers/aws/r/acm_certificate.html)

### Terraform Configuration Files

```hcl
resource "aws_acm_certificate" "main" {
  domain_name = "example.com"
  validation_method = "DNS"

  subject_alternative_names = [
    "one.example.com",
    "two.example.com",
    "three.example.com",
    "four.example.com",
    "five.example.com",
    "six.example.com",
    "seven.example.com",
    "eight.example.com",
    "nine.example.com",
  ]
}

output "domain_validation_options" {
  value = "${aws_acm_certificate.main.domain_validation_options}"
}

```

### Expected Behavior

* There should be no diff after creating the certificate.
* The `domain_validation_options` output should contain the same results, in the same order, each time it is refreshed.

### Actual Behavior

The `subject_alternative_names` re-order on each apply, presenting a diff that would recreate the certificate:

```
-/+ aws_acm_certificate.main (new resource required)
      id:                          "arn:aws:acm:ap-southeast-2:xxxxxxxxxx:certificate/4c16e4c2-b77e-46f7-82e4-37aa5145c95f" => <computed> (forces new resource)
      arn:                         "arn:aws:acm:ap-southeast-2:xxxxxxxxxx:certificate/4c16e4c2-b77e-46f7-82e4-37aa5145c95f" => <computed>
      domain_name:                 "example.com" => "example.com"
      domain_validation_options.#: "10" => <computed>
      subject_alternative_names.#: "9" => "9"
      subject_alternative_names.0: "five.example.com" => "one.example.com" (forces new resource)
      subject_alternative_names.1: "seven.example.com" => "two.example.com" (forces new resource)
      subject_alternative_names.2: "nine.example.com" => "three.example.com" (forces new resource)
      subject_alternative_names.3: "two.example.com" => "four.example.com" (forces new resource)
      subject_alternative_names.4: "one.example.com" => "five.example.com" (forces new resource)
      subject_alternative_names.5: "six.example.com" => "six.example.com"
      subject_alternative_names.6: "three.example.com" => "seven.example.com" (forces new resource)
      subject_alternative_names.7: "eight.example.com" => "eight.example.com"
      subject_alternative_names.8: "four.example.com" => "nine.example.com" (forces new resource)
      validation_emails.#:         "0" => <computed>
      validation_method:           "DNS" => "DNS"
```

The `domain_validation_options` appear to come back in a random order each time:

```
$ terraform refresh

aws_acm_certificate.main: Refreshing state... (ID: arn:aws:acm:ap-southeast-2:xxxxxxxxxxxxx...e/bb1b08f5-5abe-48a3-9479-4b7c23e6464e)

Outputs:

domain_validation_options = [
    {
        domain_name = four.example.com,
        resource_record_name = _6fc87df20d798c2330866e8e4e6a2abe.four.example.com.,
        resource_record_type = CNAME,
        resource_record_value = _5117e7221b4e3be0f089f19fc2b80e92.xxxxxxxx.acm-validations.aws.
    },
    {
        domain_name = one.example.com,
        resource_record_name = _23da223716d9e50d20216ab5e1402512.one.example.com.,
        resource_record_type = CNAME,
        resource_record_value = _614bc43713333339cdb429184b55fdb7.xxxxxxxx.acm-validations.aws.
    },
    {
        domain_name = six.example.com,
        resource_record_name = _0e4cf2b93667f979f63b22ce9021b8ab.six.example.com.,
        resource_record_type = CNAME,
        resource_record_value = _934e8faf2368c3b6ea042d5c143c7594.xxxxxxxx.acm-validations.aws.
    },
    {
        domain_name = three.example.com,
        resource_record_name = _2e7945ed996c75e8ef734df732a80528.three.example.com.,
        resource_record_type = CNAME,
        resource_record_value = _00b32a7cc13f40d59ee96b85bc57d5c5.xxxxxxxx.acm-validations.aws.
    },
    {
        domain_name = eight.example.com,
        resource_record_name = _8a675b2ea5f2339e8f7acf281c06a5fe.eight.example.com.,
        resource_record_type = CNAME,
        resource_record_value = _c3cad235d292a1b6ee6e4c91398a7881.xxxxxxxx.acm-validations.aws.
    },
    {
        domain_name = seven.example.com,
        resource_record_name = _b396e6867067ac23789c5a3b65215035.seven.example.com.,
        resource_record_type = CNAME,
        resource_record_value = _c5faed2e8c55f794a00090356d37e307.xxxxxxxx.acm-validations.aws.
    },
    {
        domain_name = two.example.com,
        resource_record_name = _4e8c7cf4d0490efdc1ab31e04591b7f4.two.example.com.,
        resource_record_type = CNAME,
        resource_record_value = _b6145ef70687d93ffdf53666aa303c6f.xxxxxxxx.acm-validations.aws.
    },
    {
        domain_name = five.example.com,
        resource_record_name = _be7d2d75a8694d7647f2f741e0e232c4.five.example.com.,
        resource_record_type = CNAME,
        resource_record_value = _a8a0e9d5062c56ff1a8e72795edce8cf.xxxxxxxx.acm-validations.aws.
    },
    {
        domain_name = example.com,
        resource_record_name = _a1cc787c0f947dd4cd843e9f55547513.example.com.,
        resource_record_type = CNAME,
        resource_record_value = _bc7930c6cc7fefddf297a10a8447e537.acm-validations.aws.
    },
    {
        domain_name = nine.example.com,
        resource_record_name = _a2f03d4faba00b7e3a472adc39918941.nine.example.com.,
        resource_record_type = CNAME,
        resource_record_value = _453f55ee2c7489dd8664f00f40cba240.xxxxxxxx.acm-validations.aws.
    }
]

$ terraform refresh

aws_acm_certificate.main: Refreshing state... (ID: arn:aws:acm:ap-southeast-2:xxxxxxxxxxxxx...e/bb1b08f5-5abe-48a3-9479-4b7c23e6464e)

Outputs:

domain_validation_options = [
    {
        domain_name = example.com,
        resource_record_name = _a1cc787c0f947dd4cd843e9f55547513.example.com.,
        resource_record_type = CNAME,
        resource_record_value = _bc7930c6cc7fefddf297a10a8447e537.acm-validations.aws.
    },
    {
        domain_name = six.example.com,
        resource_record_name = _0e4cf2b93667f979f63b22ce9021b8ab.six.example.com.,
        resource_record_type = CNAME,
        resource_record_value = _934e8faf2368c3b6ea042d5c143c7594.xxxxxxxx.acm-validations.aws.
    },
    {
        domain_name = one.example.com,
        resource_record_name = _23da223716d9e50d20216ab5e1402512.one.example.com.,
        resource_record_type = CNAME,
        resource_record_value = _614bc43713333339cdb429184b55fdb7.xxxxxxxx.acm-validations.aws.
    },
    {
        domain_name = five.example.com,
        resource_record_name = _be7d2d75a8694d7647f2f741e0e232c4.five.example.com.,
        resource_record_type = CNAME,
        resource_record_value = _a8a0e9d5062c56ff1a8e72795edce8cf.xxxxxxxx.acm-validations.aws.
    },
    {
        domain_name = four.example.com,
        resource_record_name = _6fc87df20d798c2330866e8e4e6a2abe.four.example.com.,
        resource_record_type = CNAME,
        resource_record_value = _5117e7221b4e3be0f089f19fc2b80e92.xxxxxxxx.acm-validations.aws.
    },
    {
        domain_name = nine.example.com,
        resource_record_name = _a2f03d4faba00b7e3a472adc39918941.nine.example.com.,
        resource_record_type = CNAME,
        resource_record_value = _453f55ee2c7489dd8664f00f40cba240.xxxxxxxx.acm-validations.aws.
    },
    {
        domain_name = two.example.com,
        resource_record_name = _4e8c7cf4d0490efdc1ab31e04591b7f4.two.example.com.,
        resource_record_type = CNAME,
        resource_record_value = _b6145ef70687d93ffdf53666aa303c6f.xxxxxxxx.acm-validations.aws.
    },
    {
        domain_name = eight.example.com,
        resource_record_name = _8a675b2ea5f2339e8f7acf281c06a5fe.eight.example.com.,
        resource_record_type = CNAME,
        resource_record_value = _c3cad235d292a1b6ee6e4c91398a7881.xxxxxxxx.acm-validations.aws.
    },
    {
        domain_name = three.example.com,
        resource_record_name = _2e7945ed996c75e8ef734df732a80528.three.example.com.,
        resource_record_type = CNAME,
        resource_record_value = _00b32a7cc13f40d59ee96b85bc57d5c5.xxxxxxxx.acm-validations.aws.
    },
    {
        domain_name = seven.example.com,
        resource_record_name = _b396e6867067ac23789c5a3b65215035.seven.example.com.,
        resource_record_type = CNAME,
        resource_record_value = _c5faed2e8c55f794a00090356d37e307.xxxxxxxx.acm-validations.aws.
    }
]
```

### Steps to Reproduce

1. Use the code supplied above (PLEASE NOTE: you may need to change `example.com` to a domain that you own/control)
1. `terraform apply` and enter `yes` when prompted
1. `terraform apply` again to note the different order for the `subject_alternative_names`
1. `terraform refresh` a couple of times to see the different orders for the `domain_validation_options`

### Important Factoids

The diff on the `subject_alternative_names` is easy to workaround - simply use:
```
lifecycle {
  ignore_changes = ["subject_alternative_names"]
}
```
They can't ever change out-of-band anyway, so there's no need to monitor this field for changes.

However, the issue with the `domain_validation_options` is a little harder to work around. I'm using it as input to multiple `aws_route53_record` resources, and when the order changes, I'm getting perpetual diffs as Terraform is wanting to replace each of the records with the new order.

Of note - this didn't used to happen. I haven't run this particular workflow for ~6 months so it's possible something has changed in this provider in the meantime (there are a few potentially related entries in the changelog [here](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1560-january-16-2019) and [here](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1540-december-21-2018) and maybe also [here](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1520-december-13-2018)), but I've also only just started seeing these diffs in the last week so I'm wondering if it's possible something has changed in the the relevant AWS API.

### References

_Might_ be related to another SAN issue I just lodged: #8530

### LINKED ISSUE #8714: aws_acm_certificate_validation forces new resource every time we run terraform plan
Hi,

I am facing an issue where my aws_acm_certificate_validation is forcing new resource every time I do a `terraform plan` or `terraform apply` and as a result even the route 53 records are updated with their Guids

To replicate the issue below is a sample code:
```terraform
resource "aws_acm_certificate" "cert" {
  domain_name               = "${var.domain_name}"
  validation_method         = "DNS"
  subject_alternative_names = "${var.subject_alternative_names}"

  lifecycle {
    create_before_destroy = true
  }
}

# Creates route 53 records for validation of DNS
resource "aws_route53_record" "cert_validation" {
  # The number of records to be created
  count   = "${length(var.subject_alternative_names) + 1}"
  name    = "${lookup(aws_acm_certificate.cert.domain_validation_options[count.index], "resource_record_name")}"
  type    = "${lookup(aws_acm_certificate.cert.domain_validation_options[count.index], "resource_record_type")}"
  records = ["${lookup(aws_acm_certificate.cert.domain_validation_options[count.index], "resource_record_value")}"]
  zone_id = "${var.zone_id}"
  ttl     = 60
}

#  Validates the ACM certificate
resource "aws_acm_certificate_validation" "cert" {
  certificate_arn         = "${aws_acm_certificate.cert.arn}"
  validation_record_fqdns = ["${aws_route53_record.cert_validation.*.fqdn}"]
}

resource "null_resource" "dependency_setter" {
  depends_on = [
    "aws_acm_certificate_validation.cert",
  ]
}
```

This was not happening until a week back but we are facing these issues since then

### LINKED ISSUE #10959: ACM Certificate - Recreating every-time when I have multiple subject alternative names in the cert
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.14

### Affected Resource(s)

aws_acm_certificate

### Terraform Configuration Files

```hcl
resource "aws_acm_certificate" "xxxx-xxxxx-broker-int-cert" {
  provider                  = "aws.local"
  domain_name               = "${aws_route53_record.strimzi-bootstrap-broker-int-dns.name}"
  subject_alternative_names = ["${local.broker_subject_alternative_names}"]
  validation_method         = "EMAIL"
  tags = "${local.tags}"

}
```

### Debug Output
aws_acm_certificate.strimzi-bootstrap-broker-int-cert [31m[1m(new resource required)[0m
[0m      id:                          "arn:aws:acm:us-east-1:690947714100:certificate/824bde02-ebd6-4553-94b5-4e00464f5703" => <computed> [31m(forces new resource)[0m
      arn:                         "arn:aws:acm:us-east-1:690947714100:certificate/824bde02-ebd6-4553-94b5-4e00464f5703" => <computed>
      domain_name:                 "int-kafka-bootstrap.dev.us-east-1.ncpgismdic.nadq.ci" => "int-kafka-bootstrap.dev.us-east-1.ncpgismdic.nadq.ci"
      domain_validation_options.#: "0" => <computed>
      subject_alternative_names.#: "5" => "5"
      subject_alternative_names.0: "kafka-broker-2.dev.us-east-1.ncpgismdic.nadq.ci" => "kafka-broker-0.dev.us-east-1.ncpgismdic.nadq.ci" [31m(forces new resource)[0m
      subject_alternative_names.1: "kafka-broker-1.dev.us-east-1.ncpgismdic.nadq.ci" => "kafka-broker-1.dev.us-east-1.ncpgismdic.nadq.ci"
      subject_alternative_names.2: "kafka-broker-0.dev.us-east-1.ncpgismdic.nadq.ci" => "kafka-broker-2.dev.us-east-1.ncpgismdic.nadq.ci" [31m(forces new resource)[0m
      subject_alternative_names.3: "kafka-broker-4.dev.us-east-1.ncpgismdic.nadq.ci" => "kafka-broker-3.dev.us-east-1.ncpgismdic.nadq.ci" [31m(forces new resource)[0m
      subject_alternative_names.4: "kafka-broker-3.dev.us-east-1.ncpgismdic.nadq.ci" => "kafka-broker-4.dev.us-east-1.ncpgismdic.nadq.ci" [31m(forces new resource)[0m

### Expected Behavior
Basically, whenever there is a change to the SAN and/or domain names the ACM should force a new resource. 
### Actual Behavior
But each time Terraform build is run the ACM is forcing a new resource even when there are no changes to the domain name and/or SAN names. 

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### LINKED ISSUE #13317: DNS validation records are always created and destroyed when creating aws_acm_certificate with aws_route53_record
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
$ terraform -v
Terraform v0.12.24
+ provider.aws v2.50.0
+ provider.local v1.2.2
+ provider.null v2.1.2

### Affected Resource(s)

* aws_acm_certificate with aws_acm_certificate_validation and aws_route53_record

### Terraform Configuration Files

The following has been created as a module based on various examples on the internet and an attempt to use for_each to avoid a changing order triggering the resources to be tainted on every run. It didn't work.  This does as much autodiscovery as I could possibly get it to do, but it still always creates and destroys validation records even when nothing has changed.  This works similar to:  

https://github.com/cloudposse/terraform-aws-acm-request-certificate

vars.tf
```hcl
variable "create_certificate" {
  type        = bool
  default     = true
  description = "Set to false to prevent the module from creating or accessing any resources"
}

variable "zone_name" {
  type        = string
  default     = ""
  description = "The name of the desired Route53 Hosted Zone"
}

variable "domain_name" {
  type        = string
  description = "A domain name for which the certificate should be issued"
}

variable "subject_alternative_names" {
  type        = list(string)
  default     = []
  description = "A list of domains that should be SANs in the issued certificate"
}

variable "process_domain_validation_records" {
  type        = bool
  default     = true
  description = "Flag to enable/disable processing of the record to add to the DNS zone to complete certificate validation"
}

variable "wait_for_certificate_validation" {
  type        = bool
  default     = false
  description = "Flag to enable/disable waiting for validation of the certificate (the certificate status changed from `Pending Validation` to `Issued`)"
}

variable "validation_method" {
  type        = string
  default     = "DNS"
  description = "Method to use for validation, DNS or EMAIL"
}

variable "validation_record_ttl" {
  type        = string
  default     = "60"
  description = "The TTL of the record to add to the DNS zone to complete certificate validation"
}

variable "validation_allow_overwrite_records" {
  type        = bool
  default     = true
  description = "Whether or not to allow overwrite of Route53 validation records"
}

variable "acm_certificate_tags" {
  type        = map(string)
  default     = {}
  description = "Tags to attach to the ACM certificate"
}
```

main.tf
```hcl
resource "aws_acm_certificate" "this" {
  count = var.create_certificate ? 1 : 0

  domain_name               = var.domain_name
  # using sort here to try to get anything to not trigger it to recreate
  subject_alternative_names = sort(var.subject_alternative_names)
  validation_method         = var.validation_method

  tags = var.acm_certificate_tags

  # Ignore changes on id, which is the date/time and forces validation on an unchanged cert, but this didn't seem to help.
  lifecycle {
    create_before_destroy = true
    ignore_changes = [id]
  }
}

resource "null_resource" "update_validation_records" {
  triggers = {
    validation_domains    = md5( join("", local.distinct_domain_names) )
  }
  depends_on = [ aws_acm_certificate.this[0] ]
}

resource "aws_route53_record" "validation" {
  # key = domain, value = zone
  for_each = local.zones_for_domain

  zone_id = each.value.zone_id

  name    = local.validation_records[each.key].resource_record_name
  type    = local.validation_records[each.key].resource_record_type
  ttl     = var.validation_record_ttl

  records = [
    local.validation_records[each.key].resource_record_value
  ]

  allow_overwrite = var.validation_allow_overwrite_records

  # try to tie this to a null_resource... still no luck.
  depends_on = [ null_resource.update_validation_records ]
}

resource "aws_acm_certificate_validation" "this" {
  count = local.process_domain_validation_records && var.wait_for_certificate_validation ? 1 : 0

  certificate_arn         = aws_acm_certificate.this[0].arn
  validation_record_fqdns = [for record in aws_route53_record.validation : record.fqdn]

  # Ignore changes on id, but this didn't seem to help.
  lifecycle {
      ignore_changes = [ id ]
  }
}
```

locals.tf
```hcl
data "aws_route53_zone" "public_zones" {
  for_each = toset(local.distinct_zone_names)
  name  = each.value
}

locals {
  // Get distinct list of domains and SANs
  distinct_domain_names = flatten(distinct(concat([var.domain_name], [for s in var.subject_alternative_names : replace(s, "*.", "")])))

  // Get distinct list of domains and SANs
  distinct_zone_names = flatten(distinct([for d in local.distinct_domain_names : "${regex("[^\\.]+\\.(.+)", d)[0]}."]))

  // Create set of distinct_domain_names -> aws_route53_zone
  zones_for_domain = { 
    for d in local.distinct_domain_names : d => data.aws_route53_zone.public_zones["${regex("[^\\.]+\\.(.+)", d)[0]}."]
  }

  # Get validation options mapped to distinct_domain_names to match zones_for_domain
  # Set:  domain_name => data.aws_rout53_zone associated with the domain
  validation_records = {
      for validation_option in aws_acm_certificate.this[0].domain_validation_options :
        replace(validation_option.domain_name, "*.", "") => validation_option if contains(local.distinct_domain_names, replace(validation_option.domain_name, "*.", ""))
    }

  // Boolean to determine if DNS validation records are required
  process_domain_validation_records = var.create_certificate && var.process_domain_validation_records && var.validation_method == "DNS"
}
```
### Debug Output

Just running the terraform multiple times causes all validation records to always destroy and create, even when using for_each. I've tried everything... I don't know what debug output here can do to help.

### Panic Output

N/A
### Expected Behavior

The acm certificate and validation records should only be recreated and destroyed when they change.

### Actual Behavior

The acm certification and validation records are recreated and destroyed on every run even when nothing has changed.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Nothing important to note.

### References

* #8531  - this is exactly the issue that drove me to write the above terraform, but for_each still causes revalidation.
* #13053 - I would love whatever mechanism is chosen to work with for_each.

* edit: typos and clarity

### PR DESCRIPTION
**Pull request by n3ph**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Reference #8531
Closes #10959
Closes #13317

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
* resource/aws_acm_certificate: Prevent ordering differences with `subject_alternative_names` argument
```

## Acceptance testing:

```
$ export AWS_PROFILE=devops
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSAcmCertificate'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSAcmCertificate -timeout 120m
=== RUN   TestAccAWSAcmCertificateDataSource_singleIssued
=== PAUSE TestAccAWSAcmCertificateDataSource_singleIssued
=== RUN   TestAccAWSAcmCertificateDataSource_multipleIssued
=== PAUSE TestAccAWSAcmCertificateDataSource_multipleIssued
=== RUN   TestAccAWSAcmCertificateDataSource_noMatchReturnsError
=== PAUSE TestAccAWSAcmCertificateDataSource_noMatchReturnsError
=== RUN   TestAccAWSAcmCertificateDataSource_KeyTypes
=== PAUSE TestAccAWSAcmCertificateDataSource_KeyTypes
=== RUN   TestAccAWSAcmCertificate_emailValidation
=== PAUSE TestAccAWSAcmCertificate_emailValidation
=== RUN   TestAccAWSAcmCertificate_dnsValidation
=== PAUSE TestAccAWSAcmCertificate_dnsValidation
=== RUN   TestAccAWSAcmCertificate_root
=== PAUSE TestAccAWSAcmCertificate_root
=== RUN   TestAccAWSAcmCertificate_privateCert
=== PAUSE TestAccAWSAcmCertificate_privateCert
=== RUN   TestAccAWSAcmCertificate_root_TrailingPeriod
=== PAUSE TestAccAWSAcmCertificate_root_TrailingPeriod
=== RUN   TestAccAWSAcmCertificate_rootAndWildcardSan
=== PAUSE TestAccAWSAcmCertificate_rootAndWildcardSan
=== RUN   TestAccAWSAcmCertificate_san_single
=== PAUSE TestAccAWSAcmCertificate_san_single
=== RUN   TestAccAWSAcmCertificate_san_multiple
=== PAUSE TestAccAWSAcmCertificate_san_multiple
=== RUN   TestAccAWSAcmCertificate_san_TrailingPeriod
=== PAUSE TestAccAWSAcmCertificate_san_TrailingPeriod
=== RUN   TestAccAWSAcmCertificate_wildcard
=== PAUSE TestAccAWSAcmCertificate_wildcard
=== RUN   TestAccAWSAcmCertificate_wildcardAndRootSan
=== PAUSE TestAccAWSAcmCertificate_wildcardAndRootSan
=== RUN   TestAccAWSAcmCertificate_disableCTLogging
=== PAUSE TestAccAWSAcmCertificate_disableCTLogging
=== RUN   TestAccAWSAcmCertificate_tags
=== PAUSE TestAccAWSAcmCertificate_tags
=== RUN   TestAccAWSAcmCertificate_imported_DomainName
=== PAUSE TestAccAWSAcmCertificate_imported_DomainName
=== RUN   TestAccAWSAcmCertificate_imported_IpAddress
=== PAUSE TestAccAWSAcmCertificate_imported_IpAddress
=== RUN   TestAccAWSAcmCertificateValidation_basic
=== PAUSE TestAccAWSAcmCertificateValidation_basic
=== RUN   TestAccAWSAcmCertificateValidation_timeout
=== PAUSE TestAccAWSAcmCertificateValidation_timeout
=== RUN   TestAccAWSAcmCertificateValidation_validationRecordFqdns
=== PAUSE TestAccAWSAcmCertificateValidation_validationRecordFqdns
=== RUN   TestAccAWSAcmCertificateValidation_validationRecordFqdnsEmail
=== PAUSE TestAccAWSAcmCertificateValidation_validationRecordFqdnsEmail
=== RUN   TestAccAWSAcmCertificateValidation_validationRecordFqdnsRoot
=== PAUSE TestAccAWSAcmCertificateValidation_validationRecordFqdnsRoot
=== RUN   TestAccAWSAcmCertificateValidation_validationRecordFqdnsRootAndWildcard
=== PAUSE TestAccAWSAcmCertificateValidation_validationRecordFqdnsRootAndWildcard
=== RUN   TestAccAWSAcmCertificateValidation_validationRecordFqdnsSan
=== PAUSE TestAccAWSAcmCertificateValidation_validationRecordFqdnsSan
=== RUN   TestAccAWSAcmCertificateValidation_validationRecordFqdnsWildcard
=== PAUSE TestAccAWSAcmCertificateValidation_validationRecordFqdnsWildcard
=== RUN   TestAccAWSAcmCertificateValidation_validationRecordFqdnsWildcardAndRoot
=== PAUSE TestAccAWSAcmCertificateValidation_validationRecordFqdnsWildcardAndRoot
=== CONT  TestAccAWSAcmCertificateDataSource_singleIssued
=== CONT  TestAccAWSAcmCertificateValidation_validationRecordFqdnsRootAndWildcard
=== CONT  TestAccAWSAcmCertificate_san_TrailingPeriod
=== CONT  TestAccAWSAcmCertificate_imported_DomainName
=== CONT  TestAccAWSAcmCertificate_tags
=== CONT  TestAccAWSAcmCertificateValidation_validationRecordFqdnsEmail
=== CONT  TestAccAWSAcmCertificateValidation_validationRecordFqdns
=== CONT  TestAccAWSAcmCertificate_imported_IpAddress
=== CONT  TestAccAWSAcmCertificate_disableCTLogging
=== CONT  TestAccAWSAcmCertificateValidation_basic
=== CONT  TestAccAWSAcmCertificateValidation_validationRecordFqdnsWildcardAndRoot
=== CONT  TestAccAWSAcmCertificateValidation_timeout
=== CONT  TestAccAWSAcmCertificateValidation_validationRecordFqdnsWildcard
=== CONT  TestAccAWSAcmCertificateValidation_validationRecordFqdnsRoot
=== CONT  TestAccAWSAcmCertificateValidation_validationRecordFqdnsSan
=== CONT  TestAccAWSAcmCertificate_wildcardAndRootSan
=== CONT  TestAccAWSAcmCertificate_root
=== CONT  TestAccAWSAcmCertificate_wildcard
=== CONT  TestAccAWSAcmCertificate_san_multiple
=== CONT  TestAccAWSAcmCertificate_san_single
--- FAIL: TestAccAWSAcmCertificateDataSource_singleIssued (27.89s)
    provider_test.go:67: No valid credential sources found for AWS Provider.
        	Please see https://terraform.io/docs/providers/aws/index.html for more information on
        	providing credentials for the AWS Provider
=== CONT  TestAccAWSAcmCertificateDataSource_KeyTypes
--- FAIL: TestAccAWSAcmCertificateValidation_timeout (27.89s)
    provider_test.go:67: No valid credential sources found for AWS Provider.
        	Please see https://terraform.io/docs/providers/aws/index.html for more information on
        	providing credentials for the AWS Provider
=== CONT  TestAccAWSAcmCertificate_dnsValidation
--- FAIL: TestAccAWSAcmCertificateValidation_validationRecordFqdnsWildcardAndRoot (27.89s)
    provider_test.go:67: No valid credential sources found for AWS Provider.
        	Please see https://terraform.io/docs/providers/aws/index.html for more information on
        	providing credentials for the AWS Provider
--- FAIL: TestAccAWSAcmCertificateValidation_validationRecordFqdnsEmail (27.89s)
    provider_test.go:67: No valid credential sources found for AWS Provider.
        	Please see https://terraform.io/docs/providers/aws/index.html for more information on
        	providing credentials for the AWS Provider
=== CONT  TestAccAWSAcmCertificate_rootAndWildcardSan
--- FAIL: TestAccAWSAcmCertificate_san_multiple (27.89s)
    provider_test.go:67: No valid credential sources found for AWS Provider.
        	Please see https://terraform.io/docs/providers/aws/index.html for more information on
        	providing credentials for the AWS Provider
--- FAIL: TestAccAWSAcmCertificateValidation_validationRecordFqdnsWildcard (27.89s)
    provider_test.go:67: No valid credential sources found for AWS Provider.
        	Please see https://terraform.io/docs/providers/aws/index.html for more information on
        	providing credentials for the AWS Provider
--- FAIL: TestAccAWSAcmCertificateValidation_validationRecordFqdnsRoot (27.89s)
    provider_test.go:67: No valid credential sources found for AWS Provider.
        	Please see https://terraform.io/docs/providers/aws/index.html for more information on
        	providing credentials for the AWS Provider
=== CONT  TestAccAWSAcmCertificate_root_TrailingPeriod
--- FAIL: TestAccAWSAcmCertificate_wildcardAndRootSan (27.89s)
    provider_test.go:67: No valid credential sources found for AWS Provider.
        	Please see https://terraform.io/docs/providers/aws/index.html for more information on
        	providing credentials for the AWS Provider
=== CONT  TestAccAWSAcmCertificate_privateCert
--- FAIL: TestAccAWSAcmCertificateValidation_basic (27.89s)
    provider_test.go:67: No valid credential sources found for AWS Provider.
        	Please see https://terraform.io/docs/providers/aws/index.html for more information on
        	providing credentials for the AWS Provider
--- FAIL: TestAccAWSAcmCertificateValidation_validationRecordFqdnsSan (27.89s)
    provider_test.go:67: No valid credential sources found for AWS Provider.
        	Please see https://terraform.io/docs/providers/aws/index.html for more information on
        	providing credentials for the AWS Provider
=== CONT  TestAccAWSAcmCertificate_emailValidation
--- FAIL: TestAccAWSAcmCertificate_wildcard (27.89s)
    provider_test.go:67: No valid credential sources found for AWS Provider.
        	Please see https://terraform.io/docs/providers/aws/index.html for more information on
        	providing credentials for the AWS Provider
--- FAIL: TestAccAWSAcmCertificateValidation_validationRecordFqdnsRootAndWildcard (27.89s)
    provider_test.go:67: No valid credential sources found for AWS Provider.
        	Please see https://terraform.io/docs/providers/aws/index.html for more information on
        	providing credentials for the AWS Provider
--- FAIL: TestAccAWSAcmCertificate_san_TrailingPeriod (27.89s)
    provider_test.go:67: No valid credential sources found for AWS Provider.
        	Please see https://terraform.io/docs/providers/aws/index.html for more information on
        	providing credentials for the AWS Provider
--- FAIL: TestAccAWSAcmCertificate_imported_IpAddress (28.20s)
    provider_test.go:67: No valid credential sources found for AWS Provider.
        	Please see https://terraform.io/docs/providers/aws/index.html for more information on
        	providing credentials for the AWS Provider
=== CONT  TestAccAWSAcmCertificateDataSource_noMatchReturnsError
--- FAIL: TestAccAWSAcmCertificate_root (27.89s)
    provider_test.go:67: No valid credential sources found for AWS Provider.
        	Please see https://terraform.io/docs/providers/aws/index.html for more information on
        	providing credentials for the AWS Provider
--- FAIL: TestAccAWSAcmCertificate_tags (27.89s)
    provider_test.go:67: No valid credential sources found for AWS Provider.
        	Please see https://terraform.io/docs/providers/aws/index.html for more information on
        	providing credentials for the AWS Provider
=== CONT  TestAccAWSAcmCertificateDataSource_multipleIssued
--- FAIL: TestAccAWSAcmCertificate_disableCTLogging (27.89s)
    provider_test.go:67: No valid credential sources found for AWS Provider.
        	Please see https://terraform.io/docs/providers/aws/index.html for more information on
        	providing credentials for the AWS Provider
--- FAIL: TestAccAWSAcmCertificate_san_single (27.89s)
    provider_test.go:67: No valid credential sources found for AWS Provider.
        	Please see https://terraform.io/docs/providers/aws/index.html for more information on
        	providing credentials for the AWS Provider
--- FAIL: TestAccAWSAcmCertificateValidation_validationRecordFqdns (27.89s)
    provider_test.go:67: No valid credential sources found for AWS Provider.
        	Please see https://terraform.io/docs/providers/aws/index.html for more information on
        	providing credentials for the AWS Provider
--- FAIL: TestAccAWSAcmCertificate_imported_DomainName (28.47s)
    provider_test.go:67: No valid credential sources found for AWS Provider.
        	Please see https://terraform.io/docs/providers/aws/index.html for more information on
        	providing credentials for the AWS Provider
--- FAIL: TestAccAWSAcmCertificate_root_TrailingPeriod (27.65s)
    provider_test.go:67: No valid credential sources found for AWS Provider.
        	Please see https://terraform.io/docs/providers/aws/index.html for more information on
        	providing credentials for the AWS Provider
--- FAIL: TestAccAWSAcmCertificateDataSource_KeyTypes (30.11s)
    provider_test.go:67: No valid credential sources found for AWS Provider.
        	Please see https://terraform.io/docs/providers/aws/index.html for more information on
        	providing credentials for the AWS Provider
--- FAIL: TestAccAWSAcmCertificateDataSource_multipleIssued (27.65s)
    provider_test.go:67: No valid credential sources found for AWS Provider.
        	Please see https://terraform.io/docs/providers/aws/index.html for more information on
        	providing credentials for the AWS Provider
--- FAIL: TestAccAWSAcmCertificate_rootAndWildcardSan (27.65s)
    provider_test.go:67: No valid credential sources found for AWS Provider.
        	Please see https://terraform.io/docs/providers/aws/index.html for more information on
        	providing credentials for the AWS Provider
--- FAIL: TestAccAWSAcmCertificateDataSource_noMatchReturnsError (27.65s)
    provider_test.go:67: No valid credential sources found for AWS Provider.
        	Please see https://terraform.io/docs/providers/aws/index.html for more information on
        	providing credentials for the AWS Provider
--- FAIL: TestAccAWSAcmCertificate_privateCert (27.65s)
    provider_test.go:67: No valid credential sources found for AWS Provider.
        	Please see https://terraform.io/docs/providers/aws/index.html for more information on
        	providing credentials for the AWS Provider
--- FAIL: TestAccAWSAcmCertificate_dnsValidation (27.65s)
    provider_test.go:67: No valid credential sources found for AWS Provider.
        	Please see https://terraform.io/docs/providers/aws/index.html for more information on
        	providing credentials for the AWS Provider
--- FAIL: TestAccAWSAcmCertificate_emailValidation (27.65s)
    provider_test.go:67: No valid credential sources found for AWS Provider.
        	Please see https://terraform.io/docs/providers/aws/index.html for more information on
        	providing credentials for the AWS Provider
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	58.917s
FAIL
make: *** [GNUmakefile:24: testacc] Error 1
```

Could someone please shed some light here? I do not see why `AWS_PROFILE` is not working for acceptance tests anymore...

## Example Code

```hcl
provider "aws" {
  max_retries = 1337
  region      = "eu-central-1"
  profile     = "devops"
}

resource "aws_acm_certificate" "test" {
  domain_name       = "test.dev.reservix.cloud"
  validation_method = "DNS"

  subject_alternative_names = [
    "one.test.dev.reservix.cloud",
    "two.test.dev.reservix.cloud",
    "three.test.dev.reservix.cloud",
    "four.test.dev.reservix.cloud",
    "five.test.dev.reservix.cloud",
    "six.test.dev.reservix.cloud",
    "seven.test.dev.reservix.cloud",
    "eight.test.dev.reservix.cloud",
    "nine.test.dev.reservix.cloud",
  ]
}
```

```console
tf apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_acm_certificate.test will be created
  + resource "aws_acm_certificate" "test" {
      + arn                       = (known after apply)
      + domain_name               = "test.dev.reservix.cloud"
      + domain_validation_options = (known after apply)
      + id                        = (known after apply)
      + subject_alternative_names = [
          + "eight.test.dev.reservix.cloud",
          + "five.test.dev.reservix.cloud",
          + "four.test.dev.reservix.cloud",
          + "nine.test.dev.reservix.cloud",
          + "one.test.dev.reservix.cloud",
          + "seven.test.dev.reservix.cloud",
          + "six.test.dev.reservix.cloud",
          + "three.test.dev.reservix.cloud",
          + "two.test.dev.reservix.cloud",
        ]
      + validation_emails         = (known after apply)
      + validation_method         = "DNS"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_acm_certificate.test: Creating...
aws_acm_certificate.test: Still creating... [10s elapsed]
aws_acm_certificate.test: Still creating... [20s elapsed]
aws_acm_certificate.test: Still creating... [30s elapsed]
aws_acm_certificate.test: Still creating... [40s elapsed]
aws_acm_certificate.test: Still creating... [50s elapsed]
aws_acm_certificate.test: Creation complete after 52s [id=arn:aws:acm:eu-central-1:159388291991:certificate/7821b026-fe75-4391-977d-ea721ed02a56]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
$ tf apply
aws_acm_certificate.test: Refreshing state... [id=arn:aws:acm:eu-central-1:159388291991:certificate/7821b026-fe75-4391-977d-ea721ed02a56]

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
$ tf destroy
aws_acm_certificate.test: Refreshing state... [id=arn:aws:acm:eu-central-1:159388291991:certificate/7821b026-fe75-4391-977d-ea721ed02a56]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # aws_acm_certificate.test will be destroyed
  - resource "aws_acm_certificate" "test" {
      - arn                       = "arn:aws:acm:eu-central-1:159388291991:certificate/7821b026-fe75-4391-977d-ea721ed02a56" -> null
      - domain_name               = "test.dev.reservix.cloud" -> null
      - domain_validation_options = [
          - {
              - domain_name           = "test.dev.reservix.cloud"
              - resource_record_name  = "_5f73fbc90b619a65895a4dffbacddfd7.test.dev.reservix.cloud."
              - resource_record_type  = "CNAME"
              - resource_record_value = "_eeccaa8d5151bfd6357930ad538b0b28.mzlfeqexyx.acm-validations.aws."
            },
          - {
              - domain_name           = "nine.test.dev.reservix.cloud"
              - resource_record_name  = "_d0b6b365ab587df1952c2df1e1087314.nine.test.dev.reservix.cloud."
              - resource_record_type  = "CNAME"
              - resource_record_value = "_29f21634897e69eb0d5fdcf8270f6a0c.mzlfeqexyx.acm-validations.aws."
            },
          - {
              - domain_name           = "three.test.dev.reservix.cloud"
              - resource_record_name  = "_3f1ed51a71c6868705bbfcfd312025ff.three.test.dev.reservix.cloud."
              - resource_record_type  = "CNAME"
              - resource_record_value = "_9e05a42d23907dd06acfc39c33474579.mzlfeqexyx.acm-validations.aws."
            },
          - {
              - domain_name           = "two.test.dev.reservix.cloud"
              - resource_record_name  = "_bcb7a37d8016410f717e3861d880b246.two.test.dev.reservix.cloud."
              - resource_record_type  = "CNAME"
              - resource_record_value = "_95e3ff8ba342f8d95916c0fbf5a7f426.mzlfeqexyx.acm-validations.aws."
            },
          - {
              - domain_name           = "one.test.dev.reservix.cloud"
              - resource_record_name  = "_ecb6ce42d1ef425e027d56f896892a42.one.test.dev.reservix.cloud."
              - resource_record_type  = "CNAME"
              - resource_record_value = "_6cdfde15f0ed0a234cb4f5691ce1d5a8.mzlfeqexyx.acm-validations.aws."
            },
          - {
              - domain_name           = "eight.test.dev.reservix.cloud"
              - resource_record_name  = "_38cf8495690716eece0b96323571cf65.eight.test.dev.reservix.cloud."
              - resource_record_type  = "CNAME"
              - resource_record_value = "_abbd0d5a6d7e4279c69401c09b65b50e.mzlfeqexyx.acm-validations.aws."
            },
          - {
              - domain_name           = "seven.test.dev.reservix.cloud"
              - resource_record_name  = "_a99a6433d8441811df0cf59bbfcb9331.seven.test.dev.reservix.cloud."
              - resource_record_type  = "CNAME"
              - resource_record_value = "_fdd1bb8eac7cca3db127c4ba313418df.mzlfeqexyx.acm-validations.aws."
            },
          - {
              - domain_name           = "six.test.dev.reservix.cloud"
              - resource_record_name  = "_189e80929f9fb54bb310bc70a00929b7.six.test.dev.reservix.cloud."
              - resource_record_type  = "CNAME"
              - resource_record_value = "_f1ad70f2f2d5723b89e3ef8c853a7ba4.mzlfeqexyx.acm-validations.aws."
            },
          - {
              - domain_name           = "five.test.dev.reservix.cloud"
              - resource_record_name  = "_ef19704d46946c309cec8d8ed148af7e.five.test.dev.reservix.cloud."
              - resource_record_type  = "CNAME"
              - resource_record_value = "_3fa16610ad17df0a595b1e651d82dba4.mzlfeqexyx.acm-validations.aws."
            },
          - {
              - domain_name           = "four.test.dev.reservix.cloud"
              - resource_record_name  = "_5c90a857aeb3c49005725446e3000e9b.four.test.dev.reservix.cloud."
              - resource_record_type  = "CNAME"
              - resource_record_value = "_c73a6232e9d56e0ab5df70eb480fbf12.mzlfeqexyx.acm-validations.aws."
            },
        ] -> null
      - id                        = "arn:aws:acm:eu-central-1:159388291991:certificate/7821b026-fe75-4391-977d-ea721ed02a56" -> null
      - subject_alternative_names = [
          - "eight.test.dev.reservix.cloud",
          - "five.test.dev.reservix.cloud",
          - "four.test.dev.reservix.cloud",
          - "nine.test.dev.reservix.cloud",
          - "one.test.dev.reservix.cloud",
          - "seven.test.dev.reservix.cloud",
          - "six.test.dev.reservix.cloud",
          - "three.test.dev.reservix.cloud",
          - "two.test.dev.reservix.cloud",
        ] -> null
      - tags                      = {} -> null
      - validation_emails         = [] -> null
      - validation_method         = "DNS" -> null

      - options {
          - certificate_transparency_logging_preference = "ENABLED" -> null
        }
    }

Plan: 0 to add, 0 to change, 1 to destroy.

Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

aws_acm_certificate.test: Destroying... [id=arn:aws:acm:eu-central-1:159388291991:certificate/7821b026-fe75-4391-977d-ea721ed02a56]
aws_acm_certificate.test: Destruction complete after 0s

Destroy complete! Resources: 1 destroyed.
```

### CODE REVIEW

**Comment by n3ph** [comment]
This is a breaking change as `subject_alternative_names` would be a set. How to introduce something like this? What is the process? Should we introduce a new variable and set a deprecation waring on the old one?

Any comments, ideas and requirements are welcome!

**Comment by kcburge** [comment]
I don't believe this change will actually resolve the problem. The problem is that the subject_alternative_names and domain_validation_options order must be predictable and consistent, due in part to aws_route53_records referencing this output from the aws_acm_certificate based on the count of SANs provided.  

As I understand it, the AWS API for describing the certificate does not guarantee the order of the returned subject_alternative_names, nor the order of the domain_validation_options.  So, some order must be used that, once set, never changes.

So, merely changing the SANs to a Set won't help. A Set, I believe, conveys that order does not matter.  But, actually, order is *critical* here.  So, our solution ensures that any responses from AWS are re-ordered to the order provided by the user.  If the user changes the order, then, yes, it will force re-creation of resources.  But, at least it allows them to control that order and prevent resource re-creation.

**Comment by n3ph** [comment]
By all respect - I do not see the need for an ordering... 

```hcl
provider "aws" {
  max_retries = 1337
  region      = "eu-central-1"
  profile     = "devops"
}

data "aws_route53_zone" "zone" {
  name         = "test.dev.reservix.cloud."
  private_zone = false
}

locals {
  domain = trimsuffix(data.aws_route53_zone.zone.name, ".")
  subject_alternative_names = flatten([
    for subdomain in [
      "one",
      "two",
      "three",
      "four",
      "fife",
      "six",
      "seven",
      "eight",
      "nine"
    ] : format("%s.%s", subdomain, local.domain)
  ])
}

resource "aws_acm_certificate" "cert" {
  domain_name       = data.aws_route53_zone.zone.name
  validation_method = "DNS"

  subject_alternative_names = local.subject_alternative_names
}

resource "aws_route53_record" "cert_validation" {
  for_each = { for n in flatten([local.domain, local.subject_alternative_names]) : n => n }

  name = [for domain_validation_options in aws_acm_certificate.cert.domain_validation_options :
    domain_validation_options.resource_record_name if domain_validation_options.domain_name == each.value
  ][0]
  type = [for domain_validation_options in aws_acm_certificate.cert.domain_validation_options :
    domain_validation_options.resource_record_type if domain_validation_options.domain_name == each.value
  ][0]
  records = [for domain_validation_options in aws_acm_certificate.cert.domain_validation_options :
    domain_validation_options.resource_record_value if domain_validation_options.domain_name == each.value
  ]
  zone_id = data.aws_route53_zone.zone.id
  ttl     = 60
}

resource "aws_acm_certificate_validation" "cert" {
  certificate_arn = aws_acm_certificate.cert.arn
  validation_record_fqdns = [
    for cert_validation in aws_route53_record.cert_validation :
    cert_validation.fqdn
  ]
}
```

```console
19:25 n3ph@mag-xps ~/tmp ✔  tf apply
data.aws_route53_zone.zone: Refreshing state...

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_acm_certificate.cert will be created
  + resource "aws_acm_certificate" "cert" {
      + arn                       = (known after apply)
      + domain_name               = "test.dev.reservix.cloud"
      + domain_validation_options = (known after apply)
      + id                        = (known after apply)
      + subject_alternative_names = [
          + "eight.test.dev.reservix.cloud",
          + "fife.test.dev.reservix.cloud",
          + "four.test.dev.reservix.cloud",
          + "nine.test.dev.reservix.cloud",
          + "one.test.dev.reservix.cloud",
          + "seven.test.dev.reservix.cloud",
          + "six.test.dev.reservix.cloud",
          + "three.test.dev.reservix.cloud",
          + "two.test.dev.reservix.cloud",
        ]
      + validation_emails         = (known after apply)
      + validation_method         = "DNS"
    }

  # aws_acm_certificate_validation.cert will be created
  + resource "aws_acm_certificate_validation" "cert" {
      + certificate_arn         = (known after apply)
      + id                      = (known after apply)
      + validation_record_fqdns = (known after apply)
    }

  # aws_route53_record.cert_validation["eight.test.dev.reservix.cloud"] will be created
  + resource "aws_route53_record" "cert_validation" {
      + allow_overwrite = true
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = (known after apply)
      + records         = (known after apply)
      + ttl             = 60
      + type            = (known after apply)
      + zone_id         = "Z28B3YX20SREXV"
    }

  # aws_route53_record.cert_validation["fife.test.dev.reservix.cloud"] will be created
  + resource "aws_route53_record" "cert_validation" {
      + allow_overwrite = true
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = (known after apply)
      + records         = (known after apply)
      + ttl             = 60
      + type            = (known after apply)
      + zone_id         = "Z28B3YX20SREXV"
    }

  # aws_route53_record.cert_validation["four.test.dev.reservix.cloud"] will be created
  + resource "aws_route53_record" "cert_validation" {
      + allow_overwrite = true
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = (known after apply)
      + records         = (known after apply)
      + ttl             = 60
      + type            = (known after apply)
      + zone_id         = "Z28B3YX20SREXV"
    }

  # aws_route53_record.cert_validation["nine.test.dev.reservix.cloud"] will be created
  + resource "aws_route53_record" "cert_validation" {
      + allow_overwrite = true
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = (known after apply)
      + records         = (known after apply)
      + ttl             = 60
      + type            = (known after apply)
      + zone_id         = "Z28B3YX20SREXV"
    }

  # aws_route53_record.cert_validation["one.test.dev.reservix.cloud"] will be created
  + resource "aws_route53_record" "cert_validation" {
      + allow_overwrite = true
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = (known after apply)
      + records         = (known after apply)
      + ttl             = 60
      + type            = (known after apply)
      + zone_id         = "Z28B3YX20SREXV"
    }

  # aws_route53_record.cert_validation["seven.test.dev.reservix.cloud"] will be created
  + resource "aws_route53_record" "cert_validation" {
      + allow_overwrite = true
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = (known after apply)
      + records         = (known after apply)
      + ttl             = 60
      + type            = (known after apply)
      + zone_id         = "Z28B3YX20SREXV"
    }

  # aws_route53_record.cert_validation["six.test.dev.reservix.cloud"] will be created
  + resource "aws_route53_record" "cert_validation" {
      + allow_overwrite = true
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = (known after apply)
      + records         = (known after apply)
      + ttl             = 60
      + type            = (known after apply)
      + zone_id         = "Z28B3YX20SREXV"
    }

  # aws_route53_record.cert_validation["test.dev.reservix.cloud"] will be created
  + resource "aws_route53_record" "cert_validation" {
      + allow_overwrite = true
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = (known after apply)
      + records         = (known after apply)
      + ttl             = 60
      + type            = (known after apply)
      + zone_id         = "Z28B3YX20SREXV"
    }

  # aws_route53_record.cert_validation["three.test.dev.reservix.cloud"] will be created
  + resource "aws_route53_record" "cert_validation" {
      + allow_overwrite = true
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = (known after apply)
      + records         = (known after apply)
      + ttl             = 60
      + type            = (known after apply)
      + zone_id         = "Z28B3YX20SREXV"
    }

  # aws_route53_record.cert_validation["two.test.dev.reservix.cloud"] will be created
  + resource "aws_route53_record" "cert_validation" {
      + allow_overwrite = true
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = (known after apply)
      + records         = (known after apply)
      + ttl             = 60
      + type            = (known after apply)
      + zone_id         = "Z28B3YX20SREXV"
    }

Plan: 12 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_acm_certificate.cert: Creating...
aws_acm_certificate.cert: Still creating... [10s elapsed]
aws_acm_certificate.cert: Still creating... [20s elapsed]
aws_acm_certificate.cert: Creation complete after 20s [id=arn:aws:acm:eu-central-1:159388291991:certificate/003a08ce-9c40-400f-b765-3c56daa6e5d7]
aws_route53_record.cert_validation["seven.test.dev.reservix.cloud"]: Creating...
aws_route53_record.cert_validation["one.test.dev.reservix.cloud"]: Creating...
aws_route53_record.cert_validation["eight.test.dev.reservix.cloud"]: Creating...
aws_route53_record.cert_validation["three.test.dev.reservix.cloud"]: Creating...
aws_route53_record.cert_validation["six.test.dev.reservix.cloud"]: Creating...
aws_route53_record.cert_validation["four.test.dev.reservix.cloud"]: Creating...
aws_route53_record.cert_validation["fife.test.dev.reservix.cloud"]: Creating...
aws_route53_record.cert_validation["two.test.dev.reservix.cloud"]: Creating...
aws_route53_record.cert_validation["nine.test.dev.reservix.cloud"]: Creating...
aws_route53_record.cert_validation["test.dev.reservix.cloud"]: Creating...
aws_route53_record.cert_validation["seven.test.dev.reservix.cloud"]: Still creating... [10s elapsed]
aws_route53_record.cert_validation["one.test.dev.reservix.cloud"]: Still creating... [10s elapsed]
aws_route53_record.cert_validation["three.test.dev.reservix.cloud"]: Still creating... [10s elapsed]
aws_route53_record.cert_validation["fife.test.dev.reservix.cloud"]: Still creating... [10s elapsed]
aws_route53_record.cert_validation["six.test.dev.reservix.cloud"]: Still creating... [10s elapsed]
aws_route53_record.cert_validation["four.test.dev.reservix.cloud"]: Still creating... [10s elapsed]
aws_route53_record.cert_validation["eight.test.dev.reservix.cloud"]: Still creating... [10s elapsed]
aws_route53_record.cert_validation["two.test.dev.reservix.cloud"]: Still creating... [10s elapsed]
aws_route53_record.cert_validation["test.dev.reservix.cloud"]: Still creating... [10s elapsed]
aws_route53_record.cert_validation["nine.test.dev.reservix.cloud"]: Still creating... [10s elapsed]
aws_route53_record.cert_validation["seven.test.dev.reservix.cloud"]: Still creating... [20s elapsed]
aws_route53_record.cert_validation["one.test.dev.reservix.cloud"]: Still creating... [20s elapsed]
aws_route53_record.cert_validation["fife.test.dev.reservix.cloud"]: Still creating... [20s elapsed]
aws_route53_record.cert_validation["three.test.dev.reservix.cloud"]: Still creating... [20s elapsed]
aws_route53_record.cert_validation["six.test.dev.reservix.cloud"]: Still creating... [20s elapsed]
aws_route53_record.cert_validation["four.test.dev.reservix.cloud"]: Still creating... [20s elapsed]
aws_route53_record.cert_validation["eight.test.dev.reservix.cloud"]: Still creating... [20s elapsed]
aws_route53_record.cert_validation["two.test.dev.reservix.cloud"]: Still creating... [20s elapsed]
aws_route53_record.cert_validation["test.dev.reservix.cloud"]: Still creating... [20s elapsed]
aws_route53_record.cert_validation["nine.test.dev.reservix.cloud"]: Still creating... [20s elapsed]
aws_route53_record.cert_validation["seven.test.dev.reservix.cloud"]: Still creating... [30s elapsed]
aws_route53_record.cert_validation["one.test.dev.reservix.cloud"]: Still creating... [30s elapsed]
aws_route53_record.cert_validation["fife.test.dev.reservix.cloud"]: Still creating... [30s elapsed]
aws_route53_record.cert_validation["six.test.dev.reservix.cloud"]: Still creating... [30s elapsed]
aws_route53_record.cert_validation["three.test.dev.reservix.cloud"]: Still creating... [30s elapsed]
aws_route53_record.cert_validation["four.test.dev.reservix.cloud"]: Still creating... [30s elapsed]
aws_route53_record.cert_validation["eight.test.dev.reservix.cloud"]: Still creating... [30s elapsed]
aws_route53_record.cert_validation["two.test.dev.reservix.cloud"]: Still creating... [30s elapsed]
aws_route53_record.cert_validation["test.dev.reservix.cloud"]: Still creating... [30s elapsed]
aws_route53_record.cert_validation["nine.test.dev.reservix.cloud"]: Still creating... [30s elapsed]
aws_route53_record.cert_validation["seven.test.dev.reservix.cloud"]: Creation complete after 37s [id=Z28B3YX20SREXV__a99a6433d8441811df0cf59bbfcb9331.seven.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation["two.test.dev.reservix.cloud"]: Creation complete after 39s [id=Z28B3YX20SREXV__bcb7a37d8016410f717e3861d880b246.two.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation["four.test.dev.reservix.cloud"]: Creation complete after 39s [id=Z28B3YX20SREXV__5c90a857aeb3c49005725446e3000e9b.four.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation["test.dev.reservix.cloud"]: Creation complete after 39s [id=Z28B3YX20SREXV__5f73fbc90b619a65895a4dffbacddfd7.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation["fife.test.dev.reservix.cloud"]: Creation complete after 40s [id=Z28B3YX20SREXV__95d3634f83e0657d8a6468e04e7fb092.fife.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation["one.test.dev.reservix.cloud"]: Still creating... [40s elapsed]
aws_route53_record.cert_validation["three.test.dev.reservix.cloud"]: Still creating... [40s elapsed]
aws_route53_record.cert_validation["six.test.dev.reservix.cloud"]: Still creating... [40s elapsed]
aws_route53_record.cert_validation["eight.test.dev.reservix.cloud"]: Still creating... [40s elapsed]
aws_route53_record.cert_validation["nine.test.dev.reservix.cloud"]: Still creating... [40s elapsed]
aws_route53_record.cert_validation["one.test.dev.reservix.cloud"]: Creation complete after 40s [id=Z28B3YX20SREXV__ecb6ce42d1ef425e027d56f896892a42.one.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation["nine.test.dev.reservix.cloud"]: Creation complete after 41s [id=Z28B3YX20SREXV__d0b6b365ab587df1952c2df1e1087314.nine.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation["six.test.dev.reservix.cloud"]: Creation complete after 41s [id=Z28B3YX20SREXV__189e80929f9fb54bb310bc70a00929b7.six.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation["eight.test.dev.reservix.cloud"]: Creation complete after 41s [id=Z28B3YX20SREXV__38cf8495690716eece0b96323571cf65.eight.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation["three.test.dev.reservix.cloud"]: Creation complete after 41s [id=Z28B3YX20SREXV__3f1ed51a71c6868705bbfcfd312025ff.three.test.dev.reservix.cloud._CNAME]
aws_acm_certificate_validation.cert: Creating...
aws_acm_certificate_validation.cert: Still creating... [10s elapsed]
aws_acm_certificate_validation.cert: Still creating... [20s elapsed]
aws_acm_certificate_validation.cert: Still creating... [30s elapsed]
aws_acm_certificate_validation.cert: Still creating... [40s elapsed]
aws_acm_certificate_validation.cert: Still creating... [50s elapsed]
aws_acm_certificate_validation.cert: Still creating... [1m0s elapsed]
aws_acm_certificate_validation.cert: Still creating... [1m10s elapsed]
aws_acm_certificate_validation.cert: Still creating... [1m20s elapsed]
aws_acm_certificate_validation.cert: Still creating... [1m30s elapsed]
aws_acm_certificate_validation.cert: Still creating... [1m40s elapsed]
aws_acm_certificate_validation.cert: Still creating... [1m50s elapsed]
aws_acm_certificate_validation.cert: Still creating... [2m0s elapsed]
aws_acm_certificate_validation.cert: Still creating... [2m10s elapsed]
aws_acm_certificate_validation.cert: Still creating... [2m20s elapsed]
aws_acm_certificate_validation.cert: Still creating... [2m30s elapsed]
aws_acm_certificate_validation.cert: Still creating... [2m40s elapsed]
aws_acm_certificate_validation.cert: Still creating... [2m50s elapsed]
aws_acm_certificate_validation.cert: Still creating... [3m0s elapsed]
aws_acm_certificate_validation.cert: Still creating... [3m10s elapsed]
aws_acm_certificate_validation.cert: Still creating... [3m20s elapsed]
aws_acm_certificate_validation.cert: Still creating... [3m30s elapsed]
aws_acm_certificate_validation.cert: Still creating... [3m40s elapsed]
aws_acm_certificate_validation.cert: Creation complete after 3m46s [id=2019-12-15 18:31:22 +0000 UTC]

Apply complete! Resources: 12 added, 0 changed, 0 destroyed.
19:31 n3ph@mag-xps ~/tmp ✔  tf apply
data.aws_route53_zone.zone: Refreshing state...
aws_acm_certificate.cert: Refreshing state... [id=arn:aws:acm:eu-central-1:159388291991:certificate/003a08ce-9c40-400f-b765-3c56daa6e5d7]
aws_route53_record.cert_validation["seven.test.dev.reservix.cloud"]: Refreshing state... [id=Z28B3YX20SREXV__a99a6433d8441811df0cf59bbfcb9331.seven.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation["test.dev.reservix.cloud"]: Refreshing state... [id=Z28B3YX20SREXV__5f73fbc90b619a65895a4dffbacddfd7.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation["nine.test.dev.reservix.cloud"]: Refreshing state... [id=Z28B3YX20SREXV__d0b6b365ab587df1952c2df1e1087314.nine.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation["four.test.dev.reservix.cloud"]: Refreshing state... [id=Z28B3YX20SREXV__5c90a857aeb3c49005725446e3000e9b.four.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation["eight.test.dev.reservix.cloud"]: Refreshing state... [id=Z28B3YX20SREXV__38cf8495690716eece0b96323571cf65.eight.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation["one.test.dev.reservix.cloud"]: Refreshing state... [id=Z28B3YX20SREXV__ecb6ce42d1ef425e027d56f896892a42.one.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation["two.test.dev.reservix.cloud"]: Refreshing state... [id=Z28B3YX20SREXV__bcb7a37d8016410f717e3861d880b246.two.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation["three.test.dev.reservix.cloud"]: Refreshing state... [id=Z28B3YX20SREXV__3f1ed51a71c6868705bbfcfd312025ff.three.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation["six.test.dev.reservix.cloud"]: Refreshing state... [id=Z28B3YX20SREXV__189e80929f9fb54bb310bc70a00929b7.six.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation["fife.test.dev.reservix.cloud"]: Refreshing state... [id=Z28B3YX20SREXV__95d3634f83e0657d8a6468e04e7fb092.fife.test.dev.reservix.cloud._CNAME]
aws_acm_certificate_validation.cert: Refreshing state... [id=2019-12-15 18:31:22 +0000 UTC]

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
19:34 n3ph@mag-xps ~/tmp ✔  
```

**Comment by kcburge** [comment]
I am glad you were able to work around the problem using terraform 0.12.  However, what you've shown is just that: a workaround. Your example is non-intuitive and violates the principle of least surprise. My translation for 0.11 is below, which I believe is consistent with what most people have submitted and demonstrates the way most would expect this to behave.

And also, consider that not everyone has the luxury of migrating to 0.12, which is not backward compatible.

Can you confirm the below would work with your change?

```terraform
provider "aws" {
  max_retries = 1337
  region      = "eu-central-1"
  profile     = "devops"
}

data "aws_route53_zone" "zone" {
  name         = "test.dev.reservix.cloud."
  private_zone = false
}

locals {
  domain = "${substr(data.aws_route53_zone.zone.name, 0, length(data.aws_route53_zone.zone.name) - 1)}"

  subdomains = ["one", "two", "three", "four", "fife", "six", "seven", "eight", "nine"]

  subject_alternative_names = "${flatten(formatlist("%s.%s", local.subdomains, local.domain))}"
}

resource "aws_acm_certificate" "cert" {
  domain_name       = "${data.aws_route53_zone.zone.name}"
  validation_method = "DNS"

  subject_alternative_names = ["${local.subject_alternative_names}"]
}

resource "aws_route53_record" "cert_validation" {
  count = "${length(local.subject_alternative_names)}"

  name    = "${lookup(aws_acm_certificate.cert.domain_validation_options[count.index], "resource_record_name")}"
  type    = "${lookup(aws_acm_certificate.cert.domain_validation_options[count.index], "resource_record_type")}"
  records = ["${lookup(aws_acm_certificate.cert.domain_validation_options[count.index], "resource_record_value")}"]
  zone_id = "${data.aws_route53_zone.zone.id}"
  ttl     = 60
}

resource "aws_acm_certificate_validation" "cert" {
  certificate_arn = "${aws_acm_certificate.cert.arn}"

  validation_record_fqdns = ["${aws_route53_record.cert_validation.*.fqdn}"]
}
```

**Comment by n3ph** [comment]
For sure. With some minor changes - Here we go:

```hcl
provider "aws" {
  max_retries = 1337
  region      = "eu-central-1"
  profile     = "devops"
}

data "aws_route53_zone" "zone" {
  name         = "test.dev.reservix.cloud."
  private_zone = false
}

locals {
  domain                    = "${substr(data.aws_route53_zone.zone.name, 0, length(data.aws_route53_zone.zone.name) - 1)}"
  subdomains                = ["one", "two", "three", "four", "fife", "six", "seven", "eight", "nine"]
  subject_alternative_names = "${flatten(formatlist("%s.%s", local.subdomains, local.domain))}"
}

resource "aws_acm_certificate" "cert" {
  domain_name               = "${data.aws_route53_zone.zone.name}"
  subject_alternative_names = "${local.subject_alternative_names}"
  validation_method         = "DNS"
}

resource "aws_route53_record" "cert_validation" {
  count = "${length(aws_acm_certificate.cert.domain_validation_options)}"

  name    = "${lookup(aws_acm_certificate.cert.domain_validation_options[count.index], "resource_record_name")}"
  type    = "${lookup(aws_acm_certificate.cert.domain_validation_options[count.index], "resource_record_type")}"
  records = "${lookup(aws_acm_certificate.cert.domain_validation_options[count.index], "resource_record_value")}"
  zone_id = "${data.aws_route53_zone.zone.id}"
  ttl     = 60
}

resource "aws_acm_certificate_validation" "cert" {
  certificate_arn         = "${aws_acm_certificate.cert.arn}"
  validation_record_fqdns = "${aws_route53_record.cert_validation[*].fqdn}"
}
```

```console
$ tf apply

Warning: Interpolation-only expressions are deprecated

  on test.tf line 19, in resource "aws_acm_certificate" "cert":
  19:   domain_name               = "${data.aws_route53_zone.zone.name}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.


Warning: Interpolation-only expressions are deprecated

  on test.tf line 20, in resource "aws_acm_certificate" "cert":
  20:   subject_alternative_names = "${local.subject_alternative_names}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.

(and 6 more similar warnings elsewhere)

data.aws_route53_zone.zone: Refreshing state...

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_acm_certificate.cert will be created
  + resource "aws_acm_certificate" "cert" {
      + arn                       = (known after apply)
      + domain_name               = "test.dev.reservix.cloud"
      + domain_validation_options = (known after apply)
      + id                        = (known after apply)
      + subject_alternative_names = [
          + "eight.test.dev.reservix.cloud",
          + "fife.test.dev.reservix.cloud",
          + "four.test.dev.reservix.cloud",
          + "nine.test.dev.reservix.cloud",
          + "one.test.dev.reservix.cloud",
          + "seven.test.dev.reservix.cloud",
          + "six.test.dev.reservix.cloud",
          + "three.test.dev.reservix.cloud",
          + "two.test.dev.reservix.cloud",
        ]
      + validation_emails         = (known after apply)
      + validation_method         = "DNS"
    }

  # aws_acm_certificate_validation.cert will be created
  + resource "aws_acm_certificate_validation" "cert" {
      + certificate_arn         = (known after apply)
      + id                      = (known after apply)
      + validation_record_fqdns = (known after apply)
    }

  # aws_route53_record.cert_validation[0] will be created
  + resource "aws_route53_record" "cert_validation" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = (known after apply)
      + records         = (known after apply)
      + ttl             = 60
      + type            = (known after apply)
      + zone_id         = "Z28B3YX20SREXV"
    }

  # aws_route53_record.cert_validation[1] will be created
  + resource "aws_route53_record" "cert_validation" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = (known after apply)
      + records         = (known after apply)
      + ttl             = 60
      + type            = (known after apply)
      + zone_id         = "Z28B3YX20SREXV"
    }

  # aws_route53_record.cert_validation[2] will be created
  + resource "aws_route53_record" "cert_validation" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = (known after apply)
      + records         = (known after apply)
      + ttl             = 60
      + type            = (known after apply)
      + zone_id         = "Z28B3YX20SREXV"
    }

  # aws_route53_record.cert_validation[3] will be created
  + resource "aws_route53_record" "cert_validation" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = (known after apply)
      + records         = (known after apply)
      + ttl             = 60
      + type            = (known after apply)
      + zone_id         = "Z28B3YX20SREXV"
    }

  # aws_route53_record.cert_validation[4] will be created
  + resource "aws_route53_record" "cert_validation" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = (known after apply)
      + records         = (known after apply)
      + ttl             = 60
      + type            = (known after apply)
      + zone_id         = "Z28B3YX20SREXV"
    }

  # aws_route53_record.cert_validation[5] will be created
  + resource "aws_route53_record" "cert_validation" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = (known after apply)
      + records         = (known after apply)
      + ttl             = 60
      + type            = (known after apply)
      + zone_id         = "Z28B3YX20SREXV"
    }

  # aws_route53_record.cert_validation[6] will be created
  + resource "aws_route53_record" "cert_validation" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = (known after apply)
      + records         = (known after apply)
      + ttl             = 60
      + type            = (known after apply)
      + zone_id         = "Z28B3YX20SREXV"
    }

  # aws_route53_record.cert_validation[7] will be created
  + resource "aws_route53_record" "cert_validation" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = (known after apply)
      + records         = (known after apply)
      + ttl             = 60
      + type            = (known after apply)
      + zone_id         = "Z28B3YX20SREXV"
    }

  # aws_route53_record.cert_validation[8] will be created
  + resource "aws_route53_record" "cert_validation" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = (known after apply)
      + records         = (known after apply)
      + ttl             = 60
      + type            = (known after apply)
      + zone_id         = "Z28B3YX20SREXV"
    }

  # aws_route53_record.cert_validation[9] will be created
  + resource "aws_route53_record" "cert_validation" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = (known after apply)
      + records         = (known after apply)
      + ttl             = 60
      + type            = (known after apply)
      + zone_id         = "Z28B3YX20SREXV"
    }

Plan: 12 to add, 0 to change, 0 to destroy.


Warning: Interpolation-only expressions are deprecated

  on test.tf line 19, in resource "aws_acm_certificate" "cert":
  19:   domain_name               = "${data.aws_route53_zone.zone.name}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.


Warning: Interpolation-only expressions are deprecated

  on test.tf line 20, in resource "aws_acm_certificate" "cert":
  20:   subject_alternative_names = "${local.subject_alternative_names}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.

(and 6 more similar warnings elsewhere)

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_acm_certificate.cert: Creating...
aws_acm_certificate.cert: Still creating... [10s elapsed]
aws_acm_certificate.cert: Creation complete after 19s [id=arn:aws:acm:eu-central-1:159388291991:certificate/df21c899-13b4-42d0-9dce-58815d472ee4]
aws_route53_record.cert_validation[4]: Creating...
aws_route53_record.cert_validation[5]: Creating...
aws_route53_record.cert_validation[8]: Creating...
aws_route53_record.cert_validation[6]: Creating...
aws_route53_record.cert_validation[9]: Creating...
aws_route53_record.cert_validation[1]: Creating...
aws_route53_record.cert_validation[7]: Creating...
aws_route53_record.cert_validation[3]: Creating...
aws_route53_record.cert_validation[0]: Creating...
aws_route53_record.cert_validation[2]: Creating...
aws_route53_record.cert_validation[5]: Still creating... [10s elapsed]
aws_route53_record.cert_validation[8]: Still creating... [10s elapsed]
aws_route53_record.cert_validation[6]: Still creating... [10s elapsed]
aws_route53_record.cert_validation[4]: Still creating... [10s elapsed]
aws_route53_record.cert_validation[9]: Still creating... [10s elapsed]
aws_route53_record.cert_validation[7]: Still creating... [10s elapsed]
aws_route53_record.cert_validation[3]: Still creating... [10s elapsed]
aws_route53_record.cert_validation[1]: Still creating... [10s elapsed]
aws_route53_record.cert_validation[0]: Still creating... [10s elapsed]
aws_route53_record.cert_validation[2]: Still creating... [10s elapsed]
aws_route53_record.cert_validation[5]: Still creating... [20s elapsed]
aws_route53_record.cert_validation[8]: Still creating... [20s elapsed]
aws_route53_record.cert_validation[6]: Still creating... [20s elapsed]
aws_route53_record.cert_validation[4]: Still creating... [20s elapsed]
aws_route53_record.cert_validation[9]: Still creating... [20s elapsed]
aws_route53_record.cert_validation[7]: Still creating... [20s elapsed]
aws_route53_record.cert_validation[3]: Still creating... [20s elapsed]
aws_route53_record.cert_validation[1]: Still creating... [20s elapsed]
aws_route53_record.cert_validation[0]: Still creating... [20s elapsed]
aws_route53_record.cert_validation[2]: Still creating... [20s elapsed]
aws_route53_record.cert_validation[5]: Still creating... [30s elapsed]
aws_route53_record.cert_validation[8]: Still creating... [30s elapsed]
aws_route53_record.cert_validation[6]: Still creating... [30s elapsed]
aws_route53_record.cert_validation[4]: Still creating... [30s elapsed]
aws_route53_record.cert_validation[9]: Still creating... [30s elapsed]
aws_route53_record.cert_validation[1]: Still creating... [30s elapsed]
aws_route53_record.cert_validation[7]: Still creating... [30s elapsed]
aws_route53_record.cert_validation[3]: Still creating... [30s elapsed]
aws_route53_record.cert_validation[0]: Still creating... [30s elapsed]
aws_route53_record.cert_validation[2]: Still creating... [30s elapsed]
aws_route53_record.cert_validation[0]: Creation complete after 33s [id=Z28B3YX20SREXV__5f73fbc90b619a65895a4dffbacddfd7.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[6]: Creation complete after 33s [id=Z28B3YX20SREXV__ecb6ce42d1ef425e027d56f896892a42.one.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[7]: Creation complete after 33s [id=Z28B3YX20SREXV__bcb7a37d8016410f717e3861d880b246.two.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[5]: Creation complete after 33s [id=Z28B3YX20SREXV__a99a6433d8441811df0cf59bbfcb9331.seven.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[3]: Creation complete after 33s [id=Z28B3YX20SREXV__38cf8495690716eece0b96323571cf65.eight.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[4]: Creation complete after 34s [id=Z28B3YX20SREXV__d0b6b365ab587df1952c2df1e1087314.nine.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[9]: Creation complete after 34s [id=Z28B3YX20SREXV__95d3634f83e0657d8a6468e04e7fb092.fife.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[8]: Creation complete after 34s [id=Z28B3YX20SREXV__3f1ed51a71c6868705bbfcfd312025ff.three.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[1]: Creation complete after 35s [id=Z28B3YX20SREXV__5c90a857aeb3c49005725446e3000e9b.four.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[2]: Still creating... [40s elapsed]
aws_route53_record.cert_validation[2]: Creation complete after 41s [id=Z28B3YX20SREXV__189e80929f9fb54bb310bc70a00929b7.six.test.dev.reservix.cloud._CNAME]
aws_acm_certificate_validation.cert: Creating...
aws_acm_certificate_validation.cert: Still creating... [10s elapsed]
aws_acm_certificate_validation.cert: Still creating... [20s elapsed]
aws_acm_certificate_validation.cert: Still creating... [30s elapsed]
aws_acm_certificate_validation.cert: Still creating... [40s elapsed]
aws_acm_certificate_validation.cert: Still creating... [50s elapsed]
aws_acm_certificate_validation.cert: Still creating... [1m0s elapsed]
aws_acm_certificate_validation.cert: Still creating... [1m10s elapsed]
aws_acm_certificate_validation.cert: Still creating... [1m20s elapsed]
aws_acm_certificate_validation.cert: Still creating... [1m30s elapsed]
aws_acm_certificate_validation.cert: Still creating... [1m40s elapsed]
aws_acm_certificate_validation.cert: Still creating... [1m50s elapsed]
aws_acm_certificate_validation.cert: Still creating... [2m0s elapsed]
aws_acm_certificate_validation.cert: Still creating... [2m10s elapsed]
aws_acm_certificate_validation.cert: Still creating... [2m20s elapsed]
aws_acm_certificate_validation.cert: Still creating... [2m30s elapsed]
aws_acm_certificate_validation.cert: Creation complete after 2m33s [id=2019-12-15 20:11:57 +0000 UTC]

Apply complete! Resources: 12 added, 0 changed, 0 destroyed.
$ tf apply

Warning: Interpolation-only expressions are deprecated

  on test.tf line 19, in resource "aws_acm_certificate" "cert":
  19:   domain_name               = "${data.aws_route53_zone.zone.name}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.


Warning: Interpolation-only expressions are deprecated

  on test.tf line 20, in resource "aws_acm_certificate" "cert":
  20:   subject_alternative_names = "${local.subject_alternative_names}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.

(and 6 more similar warnings elsewhere)

data.aws_route53_zone.zone: Refreshing state...
aws_acm_certificate.cert: Refreshing state... [id=arn:aws:acm:eu-central-1:159388291991:certificate/df21c899-13b4-42d0-9dce-58815d472ee4]
aws_route53_record.cert_validation[8]: Refreshing state... [id=Z28B3YX20SREXV__3f1ed51a71c6868705bbfcfd312025ff.three.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[4]: Refreshing state... [id=Z28B3YX20SREXV__d0b6b365ab587df1952c2df1e1087314.nine.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[2]: Refreshing state... [id=Z28B3YX20SREXV__189e80929f9fb54bb310bc70a00929b7.six.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[3]: Refreshing state... [id=Z28B3YX20SREXV__38cf8495690716eece0b96323571cf65.eight.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[1]: Refreshing state... [id=Z28B3YX20SREXV__5c90a857aeb3c49005725446e3000e9b.four.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[5]: Refreshing state... [id=Z28B3YX20SREXV__a99a6433d8441811df0cf59bbfcb9331.seven.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[6]: Refreshing state... [id=Z28B3YX20SREXV__ecb6ce42d1ef425e027d56f896892a42.one.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[0]: Refreshing state... [id=Z28B3YX20SREXV__5f73fbc90b619a65895a4dffbacddfd7.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[7]: Refreshing state... [id=Z28B3YX20SREXV__bcb7a37d8016410f717e3861d880b246.two.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[9]: Refreshing state... [id=Z28B3YX20SREXV__95d3634f83e0657d8a6468e04e7fb092.fife.test.dev.reservix.cloud._CNAME]
aws_acm_certificate_validation.cert: Refreshing state... [id=2019-12-15 20:11:57 +0000 UTC]

Warning: Interpolation-only expressions are deprecated

  on test.tf line 19, in resource "aws_acm_certificate" "cert":
  19:   domain_name               = "${data.aws_route53_zone.zone.name}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.


Warning: Interpolation-only expressions are deprecated

  on test.tf line 20, in resource "aws_acm_certificate" "cert":
  20:   subject_alternative_names = "${local.subject_alternative_names}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.

(and 6 more similar warnings elsewhere)


Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
$ tf destroy

Warning: Interpolation-only expressions are deprecated

  on test.tf line 19, in resource "aws_acm_certificate" "cert":
  19:   domain_name               = "${data.aws_route53_zone.zone.name}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.


Warning: Interpolation-only expressions are deprecated

  on test.tf line 20, in resource "aws_acm_certificate" "cert":
  20:   subject_alternative_names = "${local.subject_alternative_names}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.

(and 6 more similar warnings elsewhere)

data.aws_route53_zone.zone: Refreshing state...
aws_acm_certificate.cert: Refreshing state... [id=arn:aws:acm:eu-central-1:159388291991:certificate/df21c899-13b4-42d0-9dce-58815d472ee4]
aws_route53_record.cert_validation[2]: Refreshing state... [id=Z28B3YX20SREXV__189e80929f9fb54bb310bc70a00929b7.six.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[5]: Refreshing state... [id=Z28B3YX20SREXV__a99a6433d8441811df0cf59bbfcb9331.seven.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[1]: Refreshing state... [id=Z28B3YX20SREXV__5c90a857aeb3c49005725446e3000e9b.four.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[4]: Refreshing state... [id=Z28B3YX20SREXV__d0b6b365ab587df1952c2df1e1087314.nine.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[0]: Refreshing state... [id=Z28B3YX20SREXV__5f73fbc90b619a65895a4dffbacddfd7.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[7]: Refreshing state... [id=Z28B3YX20SREXV__bcb7a37d8016410f717e3861d880b246.two.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[8]: Refreshing state... [id=Z28B3YX20SREXV__3f1ed51a71c6868705bbfcfd312025ff.three.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[9]: Refreshing state... [id=Z28B3YX20SREXV__95d3634f83e0657d8a6468e04e7fb092.fife.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[3]: Refreshing state... [id=Z28B3YX20SREXV__38cf8495690716eece0b96323571cf65.eight.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[6]: Refreshing state... [id=Z28B3YX20SREXV__ecb6ce42d1ef425e027d56f896892a42.one.test.dev.reservix.cloud._CNAME]
aws_acm_certificate_validation.cert: Refreshing state... [id=2019-12-15 20:11:57 +0000 UTC]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # aws_acm_certificate.cert will be destroyed
  - resource "aws_acm_certificate" "cert" {
      - arn                       = "arn:aws:acm:eu-central-1:159388291991:certificate/df21c899-13b4-42d0-9dce-58815d472ee4" -> null
      - domain_name               = "test.dev.reservix.cloud" -> null
      - domain_validation_options = [
          - {
              - domain_name           = "test.dev.reservix.cloud"
              - resource_record_name  = "_5f73fbc90b619a65895a4dffbacddfd7.test.dev.reservix.cloud."
              - resource_record_type  = "CNAME"
              - resource_record_value = "_eeccaa8d5151bfd6357930ad538b0b28.mzlfeqexyx.acm-validations.aws."
            },
          - {
              - domain_name           = "four.test.dev.reservix.cloud"
              - resource_record_name  = "_5c90a857aeb3c49005725446e3000e9b.four.test.dev.reservix.cloud."
              - resource_record_type  = "CNAME"
              - resource_record_value = "_c73a6232e9d56e0ab5df70eb480fbf12.mzlfeqexyx.acm-validations.aws."
            },
          - {
              - domain_name           = "six.test.dev.reservix.cloud"
              - resource_record_name  = "_189e80929f9fb54bb310bc70a00929b7.six.test.dev.reservix.cloud."
              - resource_record_type  = "CNAME"
              - resource_record_value = "_f1ad70f2f2d5723b89e3ef8c853a7ba4.mzlfeqexyx.acm-validations.aws."
            },
          - {
              - domain_name           = "eight.test.dev.reservix.cloud"
              - resource_record_name  = "_38cf8495690716eece0b96323571cf65.eight.test.dev.reservix.cloud."
              - resource_record_type  = "CNAME"
              - resource_record_value = "_abbd0d5a6d7e4279c69401c09b65b50e.mzlfeqexyx.acm-validations.aws."
            },
          - {
              - domain_name           = "nine.test.dev.reservix.cloud"
              - resource_record_name  = "_d0b6b365ab587df1952c2df1e1087314.nine.test.dev.reservix.cloud."
              - resource_record_type  = "CNAME"
              - resource_record_value = "_29f21634897e69eb0d5fdcf8270f6a0c.mzlfeqexyx.acm-validations.aws."
            },
          - {
              - domain_name           = "seven.test.dev.reservix.cloud"
              - resource_record_name  = "_a99a6433d8441811df0cf59bbfcb9331.seven.test.dev.reservix.cloud."
              - resource_record_type  = "CNAME"
              - resource_record_value = "_fdd1bb8eac7cca3db127c4ba313418df.mzlfeqexyx.acm-validations.aws."
            },
          - {
              - domain_name           = "one.test.dev.reservix.cloud"
              - resource_record_name  = "_ecb6ce42d1ef425e027d56f896892a42.one.test.dev.reservix.cloud."
              - resource_record_type  = "CNAME"
              - resource_record_value = "_6cdfde15f0ed0a234cb4f5691ce1d5a8.mzlfeqexyx.acm-validations.aws."
            },
          - {
              - domain_name           = "two.test.dev.reservix.cloud"
              - resource_record_name  = "_bcb7a37d8016410f717e3861d880b246.two.test.dev.reservix.cloud."
              - resource_record_type  = "CNAME"
              - resource_record_value = "_95e3ff8ba342f8d95916c0fbf5a7f426.mzlfeqexyx.acm-validations.aws."
            },
          - {
              - domain_name           = "three.test.dev.reservix.cloud"
              - resource_record_name  = "_3f1ed51a71c6868705bbfcfd312025ff.three.test.dev.reservix.cloud."
              - resource_record_type  = "CNAME"
              - resource_record_value = "_9e05a42d23907dd06acfc39c33474579.mzlfeqexyx.acm-validations.aws."
            },
          - {
              - domain_name           = "fife.test.dev.reservix.cloud"
              - resource_record_name  = "_95d3634f83e0657d8a6468e04e7fb092.fife.test.dev.reservix.cloud."
              - resource_record_type  = "CNAME"
              - resource_record_value = "_482d1920318797f2c3e4b7c5dd929198.mzlfeqexyx.acm-validations.aws."
            },
        ] -> null
      - id                        = "arn:aws:acm:eu-central-1:159388291991:certificate/df21c899-13b4-42d0-9dce-58815d472ee4" -> null
      - subject_alternative_names = [
          - "eight.test.dev.reservix.cloud",
          - "fife.test.dev.reservix.cloud",
          - "four.test.dev.reservix.cloud",
          - "nine.test.dev.reservix.cloud",
          - "one.test.dev.reservix.cloud",
          - "seven.test.dev.reservix.cloud",
          - "six.test.dev.reservix.cloud",
          - "three.test.dev.reservix.cloud",
          - "two.test.dev.reservix.cloud",
        ] -> null
      - tags                      = {} -> null
      - validation_emails         = [] -> null
      - validation_method         = "DNS" -> null

      - options {
          - certificate_transparency_logging_preference = "ENABLED" -> null
        }
    }

  # aws_acm_certificate_validation.cert will be destroyed
  - resource "aws_acm_certificate_validation" "cert" {
      - certificate_arn         = "arn:aws:acm:eu-central-1:159388291991:certificate/df21c899-13b4-42d0-9dce-58815d472ee4" -> null
      - id                      = "2019-12-15 20:11:57 +0000 UTC" -> null
      - validation_record_fqdns = [
          - "_189e80929f9fb54bb310bc70a00929b7.six.test.dev.reservix.cloud",
          - "_38cf8495690716eece0b96323571cf65.eight.test.dev.reservix.cloud",
          - "_3f1ed51a71c6868705bbfcfd312025ff.three.test.dev.reservix.cloud",
          - "_5c90a857aeb3c49005725446e3000e9b.four.test.dev.reservix.cloud",
          - "_5f73fbc90b619a65895a4dffbacddfd7.test.dev.reservix.cloud",
          - "_95d3634f83e0657d8a6468e04e7fb092.fife.test.dev.reservix.cloud",
          - "_a99a6433d8441811df0cf59bbfcb9331.seven.test.dev.reservix.cloud",
          - "_bcb7a37d8016410f717e3861d880b246.two.test.dev.reservix.cloud",
          - "_d0b6b365ab587df1952c2df1e1087314.nine.test.dev.reservix.cloud",
          - "_ecb6ce42d1ef425e027d56f896892a42.one.test.dev.reservix.cloud",
        ] -> null
    }

  # aws_route53_record.cert_validation[0] will be destroyed
  - resource "aws_route53_record" "cert_validation" {
      - fqdn    = "_5f73fbc90b619a65895a4dffbacddfd7.test.dev.reservix.cloud" -> null
      - id      = "Z28B3YX20SREXV__5f73fbc90b619a65895a4dffbacddfd7.test.dev.reservix.cloud._CNAME" -> null
      - name    = "_5f73fbc90b619a65895a4dffbacddfd7.test.dev.reservix.cloud" -> null
      - records = [
          - "_eeccaa8d5151bfd6357930ad538b0b28.mzlfeqexyx.acm-validations.aws.",
        ] -> null
      - ttl     = 60 -> null
      - type    = "CNAME" -> null
      - zone_id = "Z28B3YX20SREXV" -> null
    }

  # aws_route53_record.cert_validation[1] will be destroyed
  - resource "aws_route53_record" "cert_validation" {
      - fqdn    = "_5c90a857aeb3c49005725446e3000e9b.four.test.dev.reservix.cloud" -> null
      - id      = "Z28B3YX20SREXV__5c90a857aeb3c49005725446e3000e9b.four.test.dev.reservix.cloud._CNAME" -> null
      - name    = "_5c90a857aeb3c49005725446e3000e9b.four.test.dev.reservix.cloud" -> null
      - records = [
          - "_c73a6232e9d56e0ab5df70eb480fbf12.mzlfeqexyx.acm-validations.aws.",
        ] -> null
      - ttl     = 60 -> null
      - type    = "CNAME" -> null
      - zone_id = "Z28B3YX20SREXV" -> null
    }

  # aws_route53_record.cert_validation[2] will be destroyed
  - resource "aws_route53_record" "cert_validation" {
      - fqdn    = "_189e80929f9fb54bb310bc70a00929b7.six.test.dev.reservix.cloud" -> null
      - id      = "Z28B3YX20SREXV__189e80929f9fb54bb310bc70a00929b7.six.test.dev.reservix.cloud._CNAME" -> null
      - name    = "_189e80929f9fb54bb310bc70a00929b7.six.test.dev.reservix.cloud" -> null
      - records = [
          - "_f1ad70f2f2d5723b89e3ef8c853a7ba4.mzlfeqexyx.acm-validations.aws.",
        ] -> null
      - ttl     = 60 -> null
      - type    = "CNAME" -> null
      - zone_id = "Z28B3YX20SREXV" -> null
    }

  # aws_route53_record.cert_validation[3] will be destroyed
  - resource "aws_route53_record" "cert_validation" {
      - fqdn    = "_38cf8495690716eece0b96323571cf65.eight.test.dev.reservix.cloud" -> null
      - id      = "Z28B3YX20SREXV__38cf8495690716eece0b96323571cf65.eight.test.dev.reservix.cloud._CNAME" -> null
      - name    = "_38cf8495690716eece0b96323571cf65.eight.test.dev.reservix.cloud" -> null
      - records = [
          - "_abbd0d5a6d7e4279c69401c09b65b50e.mzlfeqexyx.acm-validations.aws.",
        ] -> null
      - ttl     = 60 -> null
      - type    = "CNAME" -> null
      - zone_id = "Z28B3YX20SREXV" -> null
    }

  # aws_route53_record.cert_validation[4] will be destroyed
  - resource "aws_route53_record" "cert_validation" {
      - fqdn    = "_d0b6b365ab587df1952c2df1e1087314.nine.test.dev.reservix.cloud" -> null
      - id      = "Z28B3YX20SREXV__d0b6b365ab587df1952c2df1e1087314.nine.test.dev.reservix.cloud._CNAME" -> null
      - name    = "_d0b6b365ab587df1952c2df1e1087314.nine.test.dev.reservix.cloud" -> null
      - records = [
          - "_29f21634897e69eb0d5fdcf8270f6a0c.mzlfeqexyx.acm-validations.aws.",
        ] -> null
      - ttl     = 60 -> null
      - type    = "CNAME" -> null
      - zone_id = "Z28B3YX20SREXV" -> null
    }

  # aws_route53_record.cert_validation[5] will be destroyed
  - resource "aws_route53_record" "cert_validation" {
      - fqdn    = "_a99a6433d8441811df0cf59bbfcb9331.seven.test.dev.reservix.cloud" -> null
      - id      = "Z28B3YX20SREXV__a99a6433d8441811df0cf59bbfcb9331.seven.test.dev.reservix.cloud._CNAME" -> null
      - name    = "_a99a6433d8441811df0cf59bbfcb9331.seven.test.dev.reservix.cloud" -> null
      - records = [
          - "_fdd1bb8eac7cca3db127c4ba313418df.mzlfeqexyx.acm-validations.aws.",
        ] -> null
      - ttl     = 60 -> null
      - type    = "CNAME" -> null
      - zone_id = "Z28B3YX20SREXV" -> null
    }

  # aws_route53_record.cert_validation[6] will be destroyed
  - resource "aws_route53_record" "cert_validation" {
      - fqdn    = "_ecb6ce42d1ef425e027d56f896892a42.one.test.dev.reservix.cloud" -> null
      - id      = "Z28B3YX20SREXV__ecb6ce42d1ef425e027d56f896892a42.one.test.dev.reservix.cloud._CNAME" -> null
      - name    = "_ecb6ce42d1ef425e027d56f896892a42.one.test.dev.reservix.cloud" -> null
      - records = [
          - "_6cdfde15f0ed0a234cb4f5691ce1d5a8.mzlfeqexyx.acm-validations.aws.",
        ] -> null
      - ttl     = 60 -> null
      - type    = "CNAME" -> null
      - zone_id = "Z28B3YX20SREXV" -> null
    }

  # aws_route53_record.cert_validation[7] will be destroyed
  - resource "aws_route53_record" "cert_validation" {
      - fqdn    = "_bcb7a37d8016410f717e3861d880b246.two.test.dev.reservix.cloud" -> null
      - id      = "Z28B3YX20SREXV__bcb7a37d8016410f717e3861d880b246.two.test.dev.reservix.cloud._CNAME" -> null
      - name    = "_bcb7a37d8016410f717e3861d880b246.two.test.dev.reservix.cloud" -> null
      - records = [
          - "_95e3ff8ba342f8d95916c0fbf5a7f426.mzlfeqexyx.acm-validations.aws.",
        ] -> null
      - ttl     = 60 -> null
      - type    = "CNAME" -> null
      - zone_id = "Z28B3YX20SREXV" -> null
    }

  # aws_route53_record.cert_validation[8] will be destroyed
  - resource "aws_route53_record" "cert_validation" {
      - fqdn    = "_3f1ed51a71c6868705bbfcfd312025ff.three.test.dev.reservix.cloud" -> null
      - id      = "Z28B3YX20SREXV__3f1ed51a71c6868705bbfcfd312025ff.three.test.dev.reservix.cloud._CNAME" -> null
      - name    = "_3f1ed51a71c6868705bbfcfd312025ff.three.test.dev.reservix.cloud" -> null
      - records = [
          - "_9e05a42d23907dd06acfc39c33474579.mzlfeqexyx.acm-validations.aws.",
        ] -> null
      - ttl     = 60 -> null
      - type    = "CNAME" -> null
      - zone_id = "Z28B3YX20SREXV" -> null
    }

  # aws_route53_record.cert_validation[9] will be destroyed
  - resource "aws_route53_record" "cert_validation" {
      - fqdn    = "_95d3634f83e0657d8a6468e04e7fb092.fife.test.dev.reservix.cloud" -> null
      - id      = "Z28B3YX20SREXV__95d3634f83e0657d8a6468e04e7fb092.fife.test.dev.reservix.cloud._CNAME" -> null
      - name    = "_95d3634f83e0657d8a6468e04e7fb092.fife.test.dev.reservix.cloud" -> null
      - records = [
          - "_482d1920318797f2c3e4b7c5dd929198.mzlfeqexyx.acm-validations.aws.",
        ] -> null
      - ttl     = 60 -> null
      - type    = "CNAME" -> null
      - zone_id = "Z28B3YX20SREXV" -> null
    }

Plan: 0 to add, 0 to change, 12 to destroy.


Warning: Interpolation-only expressions are deprecated

  on test.tf line 19, in resource "aws_acm_certificate" "cert":
  19:   domain_name               = "${data.aws_route53_zone.zone.name}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.


Warning: Interpolation-only expressions are deprecated

  on test.tf line 20, in resource "aws_acm_certificate" "cert":
  20:   subject_alternative_names = "${local.subject_alternative_names}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.

(and 6 more similar warnings elsewhere)

Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

aws_acm_certificate_validation.cert: Destroying... [id=2019-12-15 20:11:57 +0000 UTC]
aws_acm_certificate_validation.cert: Destruction complete after 0s
aws_route53_record.cert_validation[3]: Destroying... [id=Z28B3YX20SREXV__38cf8495690716eece0b96323571cf65.eight.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[4]: Destroying... [id=Z28B3YX20SREXV__d0b6b365ab587df1952c2df1e1087314.nine.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[8]: Destroying... [id=Z28B3YX20SREXV__3f1ed51a71c6868705bbfcfd312025ff.three.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[6]: Destroying... [id=Z28B3YX20SREXV__ecb6ce42d1ef425e027d56f896892a42.one.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[0]: Destroying... [id=Z28B3YX20SREXV__5f73fbc90b619a65895a4dffbacddfd7.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[9]: Destroying... [id=Z28B3YX20SREXV__95d3634f83e0657d8a6468e04e7fb092.fife.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[1]: Destroying... [id=Z28B3YX20SREXV__5c90a857aeb3c49005725446e3000e9b.four.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[7]: Destroying... [id=Z28B3YX20SREXV__bcb7a37d8016410f717e3861d880b246.two.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[2]: Destroying... [id=Z28B3YX20SREXV__189e80929f9fb54bb310bc70a00929b7.six.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[5]: Destroying... [id=Z28B3YX20SREXV__a99a6433d8441811df0cf59bbfcb9331.seven.test.dev.reservix.cloud._CNAME]
aws_route53_record.cert_validation[3]: Still destroying... [id=Z28B3YX20SREXV__38cf8495690716eece0b963...5.eight.test.dev.reservix.cloud._CNAME, 10s elapsed]
aws_route53_record.cert_validation[4]: Still destroying... [id=Z28B3YX20SREXV__d0b6b365ab587df1952c2df...14.nine.test.dev.reservix.cloud._CNAME, 10s elapsed]
aws_route53_record.cert_validation[6]: Still destroying... [id=Z28B3YX20SREXV__ecb6ce42d1ef425e027d56f...a42.one.test.dev.reservix.cloud._CNAME, 10s elapsed]
aws_route53_record.cert_validation[8]: Still destroying... [id=Z28B3YX20SREXV__3f1ed51a71c6868705bbfcf...f.three.test.dev.reservix.cloud._CNAME, 10s elapsed]
aws_route53_record.cert_validation[0]: Still destroying... [id=Z28B3YX20SREXV__5f73fbc90b619a65895a4dffbacddfd7.test.dev.reservix.cloud._CNAME, 10s elapsed]
aws_route53_record.cert_validation[9]: Still destroying... [id=Z28B3YX20SREXV__95d3634f83e0657d8a6468e...92.fife.test.dev.reservix.cloud._CNAME, 10s elapsed]
aws_route53_record.cert_validation[1]: Still destroying... [id=Z28B3YX20SREXV__5c90a857aeb3c4900572544...9b.four.test.dev.reservix.cloud._CNAME, 10s elapsed]
aws_route53_record.cert_validation[7]: Still destroying... [id=Z28B3YX20SREXV__bcb7a37d8016410f717e386...246.two.test.dev.reservix.cloud._CNAME, 10s elapsed]
aws_route53_record.cert_validation[5]: Still destroying... [id=Z28B3YX20SREXV__a99a6433d8441811df0cf59...1.seven.test.dev.reservix.cloud._CNAME, 10s elapsed]
aws_route53_record.cert_validation[2]: Still destroying... [id=Z28B3YX20SREXV__189e80929f9fb54bb310bc7...9b7.six.test.dev.reservix.cloud._CNAME, 10s elapsed]
aws_route53_record.cert_validation[3]: Still destroying... [id=Z28B3YX20SREXV__38cf8495690716eece0b963...5.eight.test.dev.reservix.cloud._CNAME, 20s elapsed]
aws_route53_record.cert_validation[4]: Still destroying... [id=Z28B3YX20SREXV__d0b6b365ab587df1952c2df...14.nine.test.dev.reservix.cloud._CNAME, 20s elapsed]
aws_route53_record.cert_validation[6]: Still destroying... [id=Z28B3YX20SREXV__ecb6ce42d1ef425e027d56f...a42.one.test.dev.reservix.cloud._CNAME, 20s elapsed]
aws_route53_record.cert_validation[8]: Still destroying... [id=Z28B3YX20SREXV__3f1ed51a71c6868705bbfcf...f.three.test.dev.reservix.cloud._CNAME, 20s elapsed]
aws_route53_record.cert_validation[0]: Still destroying... [id=Z28B3YX20SREXV__5f73fbc90b619a65895a4dffbacddfd7.test.dev.reservix.cloud._CNAME, 20s elapsed]
aws_route53_record.cert_validation[9]: Still destroying... [id=Z28B3YX20SREXV__95d3634f83e0657d8a6468e...92.fife.test.dev.reservix.cloud._CNAME, 20s elapsed]
aws_route53_record.cert_validation[1]: Still destroying... [id=Z28B3YX20SREXV__5c90a857aeb3c4900572544...9b.four.test.dev.reservix.cloud._CNAME, 20s elapsed]
aws_route53_record.cert_validation[7]: Still destroying... [id=Z28B3YX20SREXV__bcb7a37d8016410f717e386...246.two.test.dev.reservix.cloud._CNAME, 20s elapsed]
aws_route53_record.cert_validation[5]: Still destroying... [id=Z28B3YX20SREXV__a99a6433d8441811df0cf59...1.seven.test.dev.reservix.cloud._CNAME, 20s elapsed]
aws_route53_record.cert_validation[2]: Still destroying... [id=Z28B3YX20SREXV__189e80929f9fb54bb310bc7...9b7.six.test.dev.reservix.cloud._CNAME, 20s elapsed]
aws_route53_record.cert_validation[4]: Still destroying... [id=Z28B3YX20SREXV__d0b6b365ab587df1952c2df...14.nine.test.dev.reservix.cloud._CNAME, 30s elapsed]
aws_route53_record.cert_validation[3]: Still destroying... [id=Z28B3YX20SREXV__38cf8495690716eece0b963...5.eight.test.dev.reservix.cloud._CNAME, 30s elapsed]
aws_route53_record.cert_validation[6]: Still destroying... [id=Z28B3YX20SREXV__ecb6ce42d1ef425e027d56f...a42.one.test.dev.reservix.cloud._CNAME, 30s elapsed]
aws_route53_record.cert_validation[8]: Still destroying... [id=Z28B3YX20SREXV__3f1ed51a71c6868705bbfcf...f.three.test.dev.reservix.cloud._CNAME, 30s elapsed]
aws_route53_record.cert_validation[0]: Still destroying... [id=Z28B3YX20SREXV__5f73fbc90b619a65895a4dffbacddfd7.test.dev.reservix.cloud._CNAME, 30s elapsed]
aws_route53_record.cert_validation[9]: Still destroying... [id=Z28B3YX20SREXV__95d3634f83e0657d8a6468e...92.fife.test.dev.reservix.cloud._CNAME, 30s elapsed]
aws_route53_record.cert_validation[1]: Still destroying... [id=Z28B3YX20SREXV__5c90a857aeb3c4900572544...9b.four.test.dev.reservix.cloud._CNAME, 30s elapsed]
aws_route53_record.cert_validation[7]: Still destroying... [id=Z28B3YX20SREXV__bcb7a37d8016410f717e386...246.two.test.dev.reservix.cloud._CNAME, 30s elapsed]
aws_route53_record.cert_validation[5]: Still destroying... [id=Z28B3YX20SREXV__a99a6433d8441811df0cf59...1.seven.test.dev.reservix.cloud._CNAME, 30s elapsed]
aws_route53_record.cert_validation[2]: Still destroying... [id=Z28B3YX20SREXV__189e80929f9fb54bb310bc7...9b7.six.test.dev.reservix.cloud._CNAME, 30s elapsed]
aws_route53_record.cert_validation[2]: Destruction complete after 34s
aws_route53_record.cert_validation[0]: Destruction complete after 37s
aws_route53_record.cert_validation[9]: Destruction complete after 38s
aws_route53_record.cert_validation[1]: Destruction complete after 38s
aws_route53_record.cert_validation[7]: Destruction complete after 38s
aws_route53_record.cert_validation[8]: Destruction complete after 38s
aws_route53_record.cert_validation[4]: Destruction complete after 38s
aws_route53_record.cert_validation[5]: Destruction complete after 38s
aws_route53_record.cert_validation[6]: Destruction complete after 38s
aws_route53_record.cert_validation[3]: Destruction complete after 39s
aws_acm_certificate.cert: Destroying... [id=arn:aws:acm:eu-central-1:159388291991:certificate/df21c899-13b4-42d0-9dce-58815d472ee4]
aws_acm_certificate.cert: Destruction complete after 0s

Destroy complete! Resources: 12 destroyed.
```

**Comment by n3ph** [comment]
The point you are probably missing here is that, no matter in which order `aws_acm_certificate.cert.domain_validation_options` is, the records only need to be created to successfully create `aws_acm_certificate_validation.cert`.

**Comment by kcburge** [comment]
Are you testing what comes *after* you've applied this once?  That is where things start to go wrong.  A subsequent plan can show that the resources need to be re-created.  Maybe not the next time. Could be the 100th time.  We know that the first apply works correctly.  It is the *subsequent* plans that demonstrate the problem -- the plan will falsely report changes when in fact nothing has changed.  Try looping the plan 100 or so times after the first apply.  Without the fix, it randomly (or consistently) does the wrong thing.  Also, I believe there is a need to test in different regions -- I believe AWS has addressed some of the community concerns regarding the results of describe certificate in some regions.

**Comment by n3ph** [comment]
> Are you testing what comes _after_ you've applied this once?
Yes I did - once - but I will repeat the test. Let me have a look.

**Comment by n3ph** [comment]
But rethinking what you said, it makes no sence, as `aws_acm_certificate.cert.domain_validation_options` is already nailed in the remote state. I do not see the point why that would change after reapplying multiple times.... But I am about to try that within a loop...

**Comment by kcburge** [comment]
Apply once, then repeat a "plan" over and over.  I agree that it makes no sense that anything would change, when nothing had changed -- it is due to the return order varying from the describe certificate API -- since the order is different, it detects a change when comparing to what is stored in the state.  That is the problem.

You cannot predict when that order will change.  And, even if it works for you 100% of your attempts, that doesn't mean it will work for everyone else.  I'd be happy to test your change on Monday to see if it resolves the problems we saw.

**Comment by n3ph** [comment]
So far:
```console
 for i in $(seq 10); do echo -n "Run $i"; time $(tf apply 2>&1 > /dev/null); echo; done
Run 1
real	0m15.389s
user	0m3.957s
sys	0m0.341s

Run 2
real	0m14.480s
user	0m4.006s
sys	0m0.295s

Run 3
real	0m14.668s
user	0m4.092s
sys	0m0.349s

Run 4
real	0m14.529s
user	0m3.734s
sys	0m0.271s

Run 5
real	0m14.705s
user	0m3.811s
sys	0m0.358s

Run 6
real	0m16.646s
user	0m3.791s
sys	0m0.364s

Run 7
real	0m14.706s
user	0m4.115s
sys	0m0.349s

Run 8
real	0m14.920s
user	0m4.303s
sys	0m0.269s

Run 9
real	0m14.914s
user	0m4.513s
sys	0m0.340s

Run 10
real	0m14.766s
user	0m3.961s
sys	0m0.267s
```

**Comment by n3ph** [comment]
Maybe AWS fixed that one on their side already?

**Comment by Bharathkumarraju** [comment]
is this been released already?

**Comment by nhnicwaller** [comment]
I have observed that sometimes when AWS ACM is automatically renewing a certificate, the subjectAlternateNames on the renewed certificate do not appear in the same order as they did prior to automated renewal. This requires me to update my code in Terraform every few months to match the new ordering as shown in ACM.

This seems to indicate that AWS treats subjectAlternateNames as a set, and does not guarantee the ordering will be consistent.

**Comment by kcburge** [comment]
I see this still has not been decided upon. Just reviewing the output of the proposed solution again....if you look at the "Example Code" output above, you can see three different orders:

Terrform file:

<pre>
  subject_alternative_names = [
    "one.test.dev.reservix.cloud",
    "two.test.dev.reservix.cloud",
    "three.test.dev.reservix.cloud",
    "four.test.dev.reservix.cloud",
    "five.test.dev.reservix.cloud",
    "six.test.dev.reservix.cloud",
    "seven.test.dev.reservix.cloud",
    "eight.test.dev.reservix.cloud",
    "nine.test.dev.reservix.cloud",
  ]
</pre>

The plan:

<pre>
      + subject_alternative_names = [
          + "eight.test.dev.reservix.cloud",
          + "five.test.dev.reservix.cloud",
          + "four.test.dev.reservix.cloud",
          + "nine.test.dev.reservix.cloud",
          + "one.test.dev.reservix.cloud",
          + "seven.test.dev.reservix.cloud",
          + "six.test.dev.reservix.cloud",
          + "three.test.dev.reservix.cloud",
          + "two.test.dev.reservix.cloud",
        ]
</pre>

And then during the destroy, you can see the Domain Validation Options in the state have yet a third order:

<pre>
     - domain_validation_options = [
              - domain_name           = "test.dev.reservix.cloud"
              - domain_name           = "nine.test.dev.reservix.cloud"
              - domain_name           = "three.test.dev.reservix.cloud"
              - domain_name           = "two.test.dev.reservix.cloud"
              - domain_name           = "one.test.dev.reservix.cloud"
              - domain_name           = "eight.test.dev.reservix.cloud"
              - domain_name           = "seven.test.dev.reservix.cloud"
              - domain_name           = "six.test.dev.reservix.cloud"
              - domain_name           = "five.test.dev.reservix.cloud"
              - domain_name           = "four.test.dev.reservix.cloud"
    ]
</pre>

As I've said before, order is relevant, so, a set is not a good solution for either the dvos or the sans. The order is relevant, because: 1) dvos are referenced outside of the resource, used to construct route53 records *based on the order of the dvos*, and 2) sans is the only input value indicating the "order" that the dvos should be returned in, so it also must be maintained, ordered.

Which all leads to my fix #10791, which maintains consistent ordering for both domain validation options and subject alternatives throughout this process.  And, as stated before, and in my experience, the fact that the subject_alternate_names was in the correct order during the "Example Code" destroy plan, was just luck (unless AWS really fixed this). There's no assurance that the order would be the same as any prior plan, which is what causes the certificate to want to be recreated.  The domain validation order being inconsistent is what causes your route53_records to need to be recreated, when in fact they haven't changed.

In the months since I pushed #10791, we have not had a single issue with regard to any acm related resources wanting to be recreated.

File: aws/resource_aws_acm_certificate.go [hunk 1]
```diff
@@ -60,11 +60,9 @@ func resourceAwsAcmCertificate() *schema.Resource {
 				},
 			},
 			"subject_alternative_names": {
-				Type:          schema.TypeList,
-				Optional:      true,
-				Computed:      true,
```
Comment (bflad) [inline aws/resource_aws_acm_certificate.go:65]: Can you please leave the `Computed: true` field set for this attribute? This is here due to our `ImportCertificate` API support in this resource. Thanks!

Comment (n3ph) [reply aws/resource_aws_acm_certificate.go:65]: ACK
