### PR TITLE
resource/aws_cloudfront_distribution: Fix `active_trusted_signers` attribute for Terraform 0.12

### LINKED ISSUE #8902: resource/aws_cloudfront_distribution: Get rid of flatmap dependency
As part of some preparation work for SDK decoupling I found this provider imports a legacy `flatmap` package - this isn't the way we plan to represent data in the SDK in the future anymore and it would be awesome if we could reduce the "core surface" exposed to providers by removing this dependency/import.

The CloudFront Distribution resource apparently uses this for "flattening" SDK struct into a map here

https://github.com/terraform-providers/terraform-provider-aws/blob/b13ffce6248b6eadda3cd9ffd1664ac1aafe5f39/aws/cloudfront_distribution_configuration_structure.go#L1100-L1116

the affected field `active_trusted_signers` is `TypeMap`
https://github.com/terraform-providers/terraform-provider-aws/blob/b13ffce6248b6eadda3cd9ffd1664ac1aafe5f39/aws/resource_aws_cloudfront_distribution.go#L697-L700

which makes me doubt whether this actually ever worked - there isn't any test to prove it and I don't think we have much successful history of using TypeMap for nested structures.

I suppose the easiest way to resolve this would be migrate the schema to `TypeList` & `MaxItems: 1`?

### PR DESCRIPTION
**Pull request by bflad**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #8902

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
* resource/aws_cloudfront_distribution: Support accessing `active_trusted_signers` attribute `items` in Terraform 0.12
```

This attribute implemented a legacy Terraform library (`flatmap`), which does not work with Terraform 0.12's data types and whose only usage was on this single attribute. This was missed during the Terraform 0.12 upgrade since there were no covering acceptance tests and the CloudFront setup itself is fairly esoteric (requires root AWS account login to manage CloudFront Keys).

The attribute now correctly implements (in the closest approximation) the standard Terraform Provider SDK types and methodology for saved nested object data to the Terraform state. The `items` subattribute list is now accessible again in Terraform 0.12. It does, however, unavoidably switch the root `active_trusted_signers` attribute to `TypeList` instead of `TypeMap` (which does not support map elements of different types in the current Terraform Provider SDK), so any potential references to nested attributes will need to be changed in user configurations, e.g.

Previously:

```
aws_cloudfront_distribution.example.active_trusted_signers.enabled
```

Now:

```
aws_cloudfront_distribution.example.active_trusted_signers.0.enabled
```

Output from acceptance testing:

```
--- PASS: TestAccAWSCloudFrontDistribution_DefaultCacheBehavior_TrustedSigners (611.33s)
```

### CODE REVIEW

File: aws/cloudfront_distribution_configuration_structure.go [hunk 1]
```diff
@@ -1097,20 +1096,30 @@ func flattenViewerCertificate(vc *cloudfront.ViewerCertificate) []interface{} {
...
+	return []interface{}{m}
+}
 
-	for _, v := range ats.Items {
-		signer := make(map[string]interface{})
-		signer["aws_account_number"] = *v.AwsAccountNumber
-		signer["key_pair_ids"] = aws.StringValueSlice(v.KeyPairIds.Items)
-		s = append(s, signer)
+func flattenCloudfrontSigners(signers []*cloudfront.Signer) []interface{} {
+	result := make([]interface{}, 0, len(signers))
```
Comment (nywilken) [inline aws/cloudfront_distribution_configuration_structure.go]: :100:

**Comment by bflad** [comment]
> Is this something we should add a not to the changelog for?
Indeed! Definitely will call out this one.
