### PR TITLE
resource/aws_route53_health_check: Validate reference_name

### LINKED ISSUE #7248: Provider is appending a time stamp onto an aws_route_53_health_check reference_name causing an error on apply.
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.10
AWS Provider v1.54.0 

### Affected Resource(s)

`aws_route_53_health_check`

### Terraform Configuration Files

```
resource "aws_route53_health_check" "volker-health-check" {
  reference_name        = "${var.domain} status"
  fqdn                  = "${var.domain}"
  port                  = 443
  type                  = "HTTPS"
  failure_threshold     = "3"
  request_interval      = "30"
}

resource "aws_cloudwatch_metric_alarm" "volker-health-check-alarm" {
  alarm_name          = "Volker Domain Status"
  comparison_operator = "LessThanThreshold"
  evaluation_periods  = "1"
  metric_name         = "HealthCheckStatus"
  namespace           = "AWS/Route53"
  period              = "60"
  threshold           = "1"
  statistic           = "Minimum"
  alarm_actions       = ["${aws_sns_topic.volker-health-check-topic.arn}"]
  dimensions {
    HealthCheckId = "${aws_route53_health_check.volker-health-check.id}"
  }
}

resource "aws_sns_topic" "volker-health-check-topic" {
  name = "volker-domain-status"
}
```

### Debug Output

https://gist.github.com/ebower12/a7b1587bf00f7b6baf432943310e1da0

### Panic Output

None that I could find

### Expected Behavior

Terraform stood up my health check, metric alarm, and sns topic.

### Actual Behavior

Terraform is appending a timestamp onto my health check reference_name resulting in a value of `staging.volker.candidlabs.io status-terraform-20190122200019880700000001` that exceeds the max length for that field, causing the apply to fail with the error

```
* module.health-checks.aws_route53_health_check.volker-health-check: 1 error(s) occurred:

* aws_route53_health_check.volker-health-check: InvalidInput: Invalid XML ; cvc-maxLength-valid: Value 'staging.volker.candidlabs.io status-terraform-20190122200019880700000001' with length = '72' is not facet-valid with respect to maxLength '64' for type 'HealthCheckNonce'.
	status code: 400, request id: 5873c542-1e80-11e9-8f99-b1eb6ac0391b
```

If I remove the `reference_name` field all together the apply builds with no issues.

### Steps to Reproduce

1. Configure a `aws_route_53_health_check` resource with a `reference_name` property
2. `terraform apply`

### Important Factoids

None

### References

None

### PR DESCRIPTION
**Pull request by timoguin**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Support plan-time validation for the length of the `reference_name argument`. Since this resource auto-appends a unique string to the provided argument, this is necessary to avoid obtuse errors on apply. This ensures the provided `reference_name` plus the generated string is no longer than 64 chars, the actual API limit.

Since the generated unique ID is 26 chars, the `reference_name` argument cannot exceed 38 characters.

Closes #7248

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_route53_health_check: Support plan-time validation for `reference_name` argument
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

Output from Terraform run with patched build:

```
Error: expected length of reference_name to be in the range (0 - 38), got test-long-reference-name-1111111111111111111111111

  on example.tf line 880, in resource "aws_route53_health_check" "example":
 880: resource "aws_route53_health_check" "example" {
```

### CODE REVIEW

File: aws/resource_aws_route53_health_check.go [hunk 1]
```diff
@@ -125,9 +125,10 @@ func resourceAwsRoute53HealthCheck() *schema.Resource {
 				}, true),
 			},
 			"reference_name": {
-				Type:     schema.TypeString,
-				Optional: true,
-				ForceNew: true,
+				Type:         schema.TypeString,
+				Optional:     true,
+				ForceNew:     true,
+				ValidateFunc: validation.StringLenBetween(0, resource.UniqueIDSuffixLength),
```
Comment (bflad) [inline aws/resource_aws_route53_health_check.go:131]: Hi @timoguin 👋

The maximum length of the [`CallerReference` parameter of the `CreateHealthCheck` API call is 64](https://docs.aws.amazon.com/Route53/latest/APIReference/API_CreateHealthCheck.html#Route53-CreateHealthCheck-request-CallerReference) while the resource creation code sets it to the configuration value hyphen and a 26 character random identifier:

```go
	callerRef := resource.UniqueId()
	if v, ok := d.GetOk("reference_name"); ok {
		callerRef = fmt.Sprintf("%s-%s", v.(string), callerRef)
	}
```

Did you mean the following?

```suggestion
				ValidateFunc: validation.StringLenBetween(0, (64 - resource.UniqueIDSuffixLength - 11), // resource.UniqueIdPrefix and hyphen prefix (-terraform-)
```

Comment (timoguin) [reply aws/resource_aws_route53_health_check.go:131]: Yes, I did intend to limit the argument to 27 chars. My mistake.

After perusing the API documentation some more (and https://github.com/terraform-providers/terraform-provider-aws/issues/7248#issuecomment-509663287), the only requirement is that the `CallerRef` is unique for each request.

The one benefit I've found to creating a descriptive `CallerRef` is that the `CreateRoute53HealthCheck` API call can be [logged to CloudTrail](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/logging-using-cloudtrail.html), which contains the `callerReference` in the request parameters.

Example snippet from that doc:
```
            "requestParameters": {
                "callerReference": "2014-05-06 64832",
                "healthCheckConfig": {
                    "iPAddress": "192.0.2.249",
                    "port": 80,
                    "type": "TCP"
                }
            },
```

From the standpoint of security and auditing, it would be beneficial for the `callerReference` to be as descriptive as possible.  This could be improved by allowing as much descriptive text as possible for the `reference_name` argument. Instead of taking up 26 characters for the Terraform-generated suffix, perhaps we could do something like create a trimmed sha1 hash from the current timestamp?

For example, if the generated suffix is `-tf-9e10ab` (first 6 chars from the sha1) then the max length for the  `reference_name` argument could be up to 54 chars.

Full example: `foobar-service-dev-alb-cw-alarm-httpcode-elb-5xx-high-tf-9e10ab` offers descriptive text that could be used to correlate the API request with other other events.

Thoughts?

**Comment by timoguin** [comment]
Hey @bflad, is there anything I need for this PR?

File: aws/resource_aws_route53_health_check.go [hunk 2]
```diff
@@ -128,6 +128,12 @@ func resourceAwsRoute53HealthCheck() *schema.Resource {
 				Type:     schema.TypeString,
 				Optional: true,
 				ForceNew: true,
+				// The max length of the reference name is 64 characters for the API.
+				// Terraform appends a 26-character unique ID to the provided
+				// reference_name. This limits the length of the resource argument to 38.
+				//
+				// Example generated suffix: -terraform-20190122200019880700000001
+				ValidateFunc: validation.StringLenBetween(0, (64 - resource.UniqueIDSuffixLength)),
```
Comment (bflad) [inline aws/resource_aws_route53_health_check.go:136]: The validation should be subtracting 11 still 😉 `resource.UniqueIDSuffixLength` only represents the digits after the `-terraform-` part that's being added.

```suggestion
				// The max length of the reference name is 64 characters for the API.
				// Terraform appends a 37-character unique ID to the provided
				// reference_name. This limits the length of the resource argument to 27.
				//
				// Example generated suffix: -terraform-20190122200019880700000001
				ValidateFunc: validation.StringLenBetween(0, (64 - resource.UniqueIDSuffixLength - 11)),
```

**Comment by timoguin** [comment]
Ooof! Okay, it should be good now. Thanks!
