### PR TITLE
r/aws_instance: Set placement_group in state on read if available

### LINKED ISSUE #2392: placement_group attribute is not always present on aws_instance
Hi there,

### Terraform Version
```
Terraform v0.11.0
+ provider.aws v1.3.1
```

### Affected Resource(s)
- aws_instance

### Expected Behavior
`placement_group` is not set on `aws_instance` resource when it was not specified during creation, so we can't make generic output in a module [terraform-aws-ec2-instance](https://github.com/terraform-aws-modules/terraform-aws-ec2-instance) like this:

```hcl
output "placement_group" {
  description = "List of placement groups of instances"
  value       = ["${element(concat(aws_instance.this.*.placement_group, list("")), 0)}"]
}
```

### Actual Behavior
```
* module.ec2.output.placement_group: Resource 'aws_instance.this' does not have attribute 'placement_group' for variable 'aws_instance.this.*.placement_group'
```

### Steps to Reproduce
1. `terraform apply`

### PR DESCRIPTION
**Pull request by bflad**
Closes #2392.

New test:
```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSInstance_placementGroup'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSInstance_placementGroup -timeout 120m
=== RUN   TestAccAWSInstance_placementGroup
--- PASS: TestAccAWSInstance_placementGroup (76.91s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	76.948s
```

Hopefully passing other tests still, e.g.
```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSInstance_vpc'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSInstance_vpc -timeout 120m
=== RUN   TestAccAWSInstance_vpc
--- PASS: TestAccAWSInstance_vpc (95.32s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	95.352s
```

### CODE REVIEW

File: aws/resource_aws_instance_test.go [hunk 1]
```diff
@@ -1686,6 +1711,38 @@ resource "aws_instance" "foo" {
 }
 `
 
+const testAccInstanceConfigPlacementGroup = `
+resource "aws_vpc" "foo" {
+	cidr_block = "10.1.0.0/16"
```
Comment (Ninir) [inline aws/resource_aws_instance_test.go]: Can you use 2 spaces for indentations?

File: aws/resource_aws_instance_test.go [hunk 2]
```diff
@@ -1686,6 +1711,38 @@ resource "aws_instance" "foo" {
...
+	}
+}
+
+resource "aws_subnet" "foo" {
+	cidr_block = "10.1.1.0/24"
+	vpc_id = "${aws_vpc.foo.id}"
+}
+
+resource "aws_placement_group" "foo" {
+	name = "testAccInstanceConfigPlacementGroup"
```
Comment (Ninir) [inline aws/resource_aws_instance_test.go]: We would need some randomization here to avoid conflicts when running tests

**Comment by bflad** [comment]
Comments addressed, thanks! Still passes local testing for me:
```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSInstance_placementGroup'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSInstance_placementGroup -timeout 120m
=== RUN   TestAccAWSInstance_placementGroup
--- PASS: TestAccAWSInstance_placementGroup (76.04s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	76.085s
```
