### PR TITLE
resource/aws_lambda_function: Ignore the VPC configuration if it is empty

### LINKED ISSUE #443: aws_lambda_function.vpc_config always detects a change when empty
_This issue was originally opened by @rochdev as hashicorp/terraform#10900. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version
0.8.2

### Affected Resource(s)
aws_lambda_function

### Terraform Configuration Files
```hcl
# Only relevant parts shown

variable "subnet_ids" {
  default = []
}

variable "security_group_ids" {
  default = []
}

resource "aws_lambda_function" "lambda" {
  vpc_config {
    subnet_ids         = ["${var.subnet_ids}"]
    security_group_ids = ["${var.security_group_ids}"]
  }
}
```

### Expected Behavior
Right after applying, `terraform plan` should not detect any change since there aren't any.

### Actual Behavior
Right after applying, `terraform plan` detects a change in `vpc_config`. If you apply the change, `terraform plan` will still detect the same change over and over again.

Relevant part of the output:

```text
-/+ module.auth.authorizer.authorizer_lambda.aws_lambda_function.lambda
    vpc_config.#:        "0" => "1" (forces new resource)
    vpc_config.0.vpc_id: "" => "<computed>"
```

### Steps to Reproduce
1. `terraform plan`
2. `terraform apply`
3. repeat

### References
Seem to be related:
- https://github.com/hashicorp/terraform/pull/6157
- https://github.com/hashicorp/terraform/pull/6191

### PR DESCRIPTION
**Pull request by joshuaspence**
I have a `lambda_function` module, which supports both EC2 classic and VPC. The problem I have, however, is that there is no way to specify a null configuration for `vpc_config`. This pull request changes the behavior so that the following Terraform configuration is //ignored//, instead of failing with an error (the current behavior):

```
resource "aws_lambda_function" "test" {
  # ...

  vpc_config {
    security_group_ids = []
    subnet_ids         = []
  }
}
```

See also #1187 and #1190.
Fixes #443

### CODE REVIEW

**Comment by joshuaspence** [comment]
```
make testacc TESTARGS='-run=TestAccAWSLambdaFunction_EmptyVpcConfig'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccAWSLambdaFunction_EmptyVpcConfig -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSLambdaFunction_EmptyVpcConfig
--- PASS: TestAccAWSLambdaFunction_EmptyVpcConfig (78.56s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	78.618s
```

**Comment by johnjelinek** [comment]
ETA on this merge?

**Comment by queeno** [comment]
+1

**Comment by radeksimko** [comment]
Hi @joshuaspence 
sorry for the delay in reviewing this.

There's an ongoing effort in the core of Terraform to improve the language so we don't need to fix such things on resource-level and can specify `nil` in the syntax anywhere. This will take time to ship, but I thought it's something that should be mentioned.

I'm ok with patching this locally for the time being, but there's one particular use case which is _already broken_ and needs to be fixed first before we consider this patch. See my example below.

```hcl
resource "aws_vpc" "main" {
  cidr_block = "10.10.0.0/16"
}

resource "aws_subnet" "test" {
  cidr_block = "10.10.0.0/24"
  vpc_id = "${aws_vpc.main.id}"
}

resource "aws_security_group" "test" {
  vpc_id = "${aws_vpc.main.id}"
  name = "radek-test"
}

resource "aws_lambda_function" "test" {
    filename      = "lambda.zip"
    function_name = "radek-test"
    role          = "${aws_iam_role.iam_for_lambda.arn}"
    handler       = "exports.example"
    runtime       = "nodejs4.3"

    vpc_config {
        subnet_ids         = ["${aws_subnet.test.id}"]
        security_group_ids = ["${aws_security_group.test.id}"]
    }
}

resource "aws_iam_role_policy" "iam_policy_for_lambda" {
    name = "iam_policy_for_lambda_radek"
    role = "${aws_iam_role.iam_for_lambda.id}"
    policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
            ],
            "Resource": "arn:aws:logs:*:*:*"
        },
    {
      "Effect": "Allow",
      "Action": [
        "ec2:CreateNetworkInterface",
        "ec2:DescribeNetworkInterfaces",
        "ec2:DeleteNetworkInterface"
      ],
      "Resource": [
        "*"
      ]
    }
  ]
}
EOF
}
resource "aws_iam_role" "iam_for_lambda" {
    name = "iam_for_lambda_radek"
    assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}
```
now remove the VPC configuration:
```
...
    vpc_config {
        subnet_ids         = []
        security_group_ids = []
    }
...
```
and try `terraform apply && terraform plan` - it's impossible to remove the VPC configuration.

This is a valid use-case we need to support.

While it wasn't caused by this PR, your PR is likely touching the same codepath and also needs to take this into consideration.

I hope it makes sense.

**Comment by mataneine** [comment]
any updates on this? or any workaround?

**Comment by grahamlyons** [comment]
@radeksimko, I'm not sure why we need to consider the other bug when merging this pull request. There is an existing bug and it's impossible to remove the VPC config but - as you say - it wasn't caused by this PR.

This config breaks if it is run twice:
```hcl
resource "aws_lambda_function" "test" {                                            
    filename      = "lambda.zip"                                                   
    function_name = "radek-test"                                                   
    role          = "${aws_iam_role.iam_for_lambda.arn}"                           
    handler       = "index.example"                                                
    runtime       = "nodejs4.3"                                                    
                                                                                   
    vpc_config {                                                                   
        subnet_ids         = []                                                    
        security_group_ids = []                                                    
    }                                                                              
}                                                                                  
                                                                                   
resource "aws_iam_role" "iam_for_lambda" {                                         
    name = "iam_for_lambda_radek"                                                  
    assume_role_policy = <<EOF                                                     
{                                                                                  
  "Version": "2012-10-17",                                                         
  "Statement": [                                                                   
    {                                                                              
      "Action": "sts:AssumeRole",                                                  
      "Principal": {                                                               
        "Service": "lambda.amazonaws.com"                                          
      },                                                                           
      "Effect": "Allow",                                                           
      "Sid": ""                                                                    
    }                                                                              
  ]                                                                                
}                                                                                  
EOF                                                                                
}
```

Like so:
```shell
echo 'exports.example = (event, context)=>(null)' > index.js && zip lambda.zip index.js
terraform apply -auto-approve && terraform apply -auto-approve
...
aws_lambda_function.test: Modifying... (ID: radek-test)
  vpc_config.#: "0" => "1"

Error: Error applying plan:

1 error(s) occurred:

* aws_lambda_function.test: 1 error(s) occurred:

* aws_lambda_function.test: vpc_config is <nil>
```

Could you explain why this prevents us from merging this pull request?

**Comment by mdlavin** [comment]
We've been using this patch for our terraform deployments at work and it'd very useful. But, today we hit a case of the `panic: runtime error: index out of range` when trying to remove a Lambda function VPC configuration. Today, I'm going to take this work, rebase it onto master, add a testcase for the VPC removal and then try fixing it.

**Comment by mdlavin** [comment]
I've updated the branch in this PR as described in my last comment and I think I've addressed all the issues. I've added some testcases that used to trigger the panic and fixed that failure. I also made sure that the old non-VPC related tests pass (because they failed after rebasing on master).

My branch is https://github.com/mdlavin/terraform-provider-aws/tree/lambda-empty_vpc_config

@grahamlyons if you want to update your PR branch with my changes, then this PR will get the updates
@radeksimko if you have the ability to change which branch this PR points at that could work too

**Comment by mdlavin** [comment]
Is there anything I can do to help this PR get merged? This PR is showing as having merge conflicts, by the branch that I pointed at in the comment from a month ago does not seem to be conflicting. I think that either the original PR owner @grahamlyons or a admin can update the branch on this PR

**Comment by grahamlyons** [comment]
@mdlavin, the original owner of this is actually @joshuaspence but I'm flattered that you thought it was me 😊

Perhaps rebasing the upstream master against your branch, @joshuaspence, will resolve the conflicts.

@radeksimko, will that be sufficient to get this merged?

**Comment by jarro2783** [comment]
@joshuaspence can you update your PR?

**Comment by joshuaspence** [comment]
Sorry about the silence here, I keep forgetting to come back to this. I'll rebase it now.

**Comment by loivis** [comment]
The issue mentioned by @radeksimko is in PR #3473. We should be able to move forward with both.

**Comment by mdlavin** [comment]
@loivis  the changes in this PR address the crash as well, so if this merges then nothing else should be needed.

@radeksimko a fix for this problem has been available for a long time, I've been testing with it since I submitted my branch. Is there any hope of getting it merged in so we can avoid more rebasing?

**Comment by cdimitroulas** [comment]
Just commenting here to say that it would be much appreciated if these fixes could get merged and released in the next version as it would be great not to have to use two different modules for VPC and non-VPC lambda functions!

**Comment by ricoli** [comment]
just stumbled into the same issue - anything preventing this from being merged @radeksimko?

**Comment by ricoli** [comment]
Maybe @bflad?

**Comment by ricoli** [comment]
sorry to be a pain, but this is a huge must have for a lot of folks, and has been ready for a very long time... ping @bflad

**Comment by mdlavin** [comment]
To make merging as easy as possible, I've updated my branch to be rebased on master. The branch with fixes is https://github.com/mdlavin/terraform-provider-aws/tree/lambda-empty_vpc_config.

That branch includes both the original fixes and a fix for the problem in https://github.com/terraform-providers/terraform-provider-aws/pull/1341#issuecomment-353103245 above too

**Comment by joshuaspence** [comment]
I don't mind rebasing this, I just haven't bothered doing so because it seems that the upstream is not interested in this change.

**Comment by mdlavin** [comment]
If anybody is interested in testing out this feature in a patched v1.21.0 version, I've made some Alpine Linux x64 binaries available here: https://github.com/lifeomic/terraform-provider-aws/releases/tag/v1.21.0_patched_5f7d0def

**Comment by giuliocalzolari** [comment]
any ETA on merge?
Thanks to @mdlavin I tried the patch! but will be awesome to have in the official repo

**Comment by bflad** [comment]
The fixes for properly handling `aws_lambda_function` resource `vpc_config` removal has been merged into master and will be released with version 1.35.0 of the AWS provider, likely later today. With that out of the way, we can now focus on just this specific issue.

Given that the empty list configuration for `security_group_ids` and `subnet_ids` is actually what is required to remove VPC configuration from an existing Lambda function, it seems like we should pull this in as it not only provides the workaround for supporting one module for both VPC and non-VPC functions, but also is a valid configuration.

I'm reviewing this pull request right now and will likely merge this in with one panic prevention fix in a followup commit, which I'll note in my review.

File: aws/resource_aws_lambda_function.go [hunk 1]
```diff
@@ -139,6 +139,31 @@ func resourceAwsLambdaFunction() *schema.Resource {
 						},
 					},
 				},
+
+				// Suppress diffs if the VPC configuration is empty.
+				DiffSuppressFunc: func(k, old, new string, d *schema.ResourceData) bool {
+					if v, ok := d.GetOk("vpc_config"); ok {
+						configs := v.([]interface{})
+						config, ok := configs[0].(map[string]interface{})
```
Comment (bflad) [inline aws/resource_aws_lambda_function.go]: Thanks @joshuaspence for submitting this with an acceptance test! This was definitely on the right track.

One note here: to prevent potential panics, we should ensure the length of `configs` before trying to reference the first element, e.g.

```go
if v, ok := d.GetOk("vpc_config"); ok && len(v.([]interface{})) > 0 {
```

Style nitpick: Also, we can remove the nesting if return early:

```
if old != "0" && new != "1" {
  return false
}
v, ok := d.GetOk("vpc_config")
if !ok || len(v.([]interface{})) == 0 {
  return false
}
// other logic :)
```

I'll be rebasing this PR and applying a followup commit so we can get this released today, rather then making you do any additional work or having this linger further. 👍

**Comment by bflad** [comment]
This has been released in [version 1.35.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1350-september-06-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
