### PR TITLE
d/neptune_engine_version: New data source

### LINKED ISSUE #15257: d/neptune_engine_version: New data source
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Ease the practitioner burden of working across regions and partitions by providing access to information on Neptune database engine versions and specifically the default version. In addition, the `preferred_versions` argument should allow selecting a version from a list of acceptable options.

This data source is part of helping practitioners to avoid this error:

```
Error creating DB Instance: InvalidParameterCombination: Neptune does not support creating a DB instance with the
following combination: DBInstanceClass=db.t1.micro, Engine=neptune, EngineVersion=5.6.27,
LicenseModel=general-public-license. For supported combinations of instance class and database engine version,
see the documentation.
```

### New Data Source

* aws_neptune_engine_version

### Potential Terraform Configuration

```hcl
data "aws_neptune_engine_version" "test" {}
```

### References

* hashicorp/terraform#17013
* #15205
* [d/docdb_orderable_db_instance](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/docdb_orderable_db_instance)

### PR DESCRIPTION
**Pull request by YakDriver**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #15257
Relates #15228, #15253

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
d/neptune_engine_version: New data source
```

The output from acceptance testing (GovCloud):

```
--- PASS: TestAccAWSNeptuneEngineVersionDataSource_basic (16.39s)
--- PASS: TestAccAWSNeptuneEngineVersionDataSource_defaultOnly (17.58s)
--- PASS: TestAccAWSNeptuneEngineVersionDataSource_preferred (18.74s)
```

The output from acceptance testing (commercial):

```
--- PASS: TestAccAWSNeptuneEngineVersionDataSource_basic (11.06s)
--- PASS: TestAccAWSNeptuneEngineVersionDataSource_defaultOnly (12.57s)
--- PASS: TestAccAWSNeptuneEngineVersionDataSource_preferred (13.10s)
```

### CODE REVIEW

**Comment by YakDriver** [comment]
Should we note an AWS bug in the docs? This seems to uncover a bug in the AWS API. If `DBParameterGroupFamily` is set to a valid value, AWS does not return any versions. This holds true for AWS SDK Go and the AWS CLI:

```console
% aws neptune describe-db-engine-versions --engine neptune \
 --query "DBEngineVersions[] [Engine, EngineVersion, DBParameterGroupFamily]" \
 --output text | sort -u
neptune	1.0.1.0	neptune1
neptune	1.0.1.1	neptune1
neptune	1.0.1.2	neptune1
neptune	1.0.2.1	neptune1
neptune	1.0.2.2	neptune1
neptune	1.0.3.0	neptune1
% aws neptune describe-db-engine-versions --db-parameter-group-family neptune1
{
    "DBEngineVersions": []
}
% aws docdb describe-db-engine-versions --db-parameter-group-family neptune1 --engine neptune
{
    "DBEngineVersions": []
}
% aws docdb describe-db-engine-versions --db-parameter-group-family neptune1 --engine neptune --engine-version 1.0.2.2
{
    "DBEngineVersions": []
}
% aws docdb describe-db-engine-versions --engine neptune --engine-version 1.0.2.2
{
    "DBEngineVersions": [
        {
            "Engine": "neptune",
            "EngineVersion": "1.0.2.2",
            "DBParameterGroupFamily": "neptune1",
            "DBEngineDescription": "neptune",
            "DBEngineVersionDescription": "Neptune 1.0.2.2.R4",
            "ValidUpgradeTarget": [
                {
                    "Engine": "neptune",
                    "EngineVersion": "1.0.3.0",
                    "Description": "Neptune 1.0.3.0.R1",
                    "AutoUpgrade": false,
                    "IsMajorVersionUpgrade": false
                }
            ],
            "ExportableLogTypes": [
                "audit"
            ],
            "SupportsLogExportsToCloudwatchLogs": true
        }
    ]
}
```

File: aws/data_source_aws_neptune_engine_version.go [hunk 1]
```diff
@@ -0,0 +1,191 @@
...
+				Computed: true,
+			},
+
+			"exportable_log_types": {
+				Type:     schema.TypeList,
+				Elem:     &schema.Schema{Type: schema.TypeString},
+				Computed: true,
+			},
+
+			"parameter_group_name": {
```
Comment (bflad) [inline aws/data_source_aws_neptune_engine_version.go:33]: Similar note as #15228 here and the rest of this pull request:

```suggestion
			"parameter_group_family": {
```

File: website/docs/d/neptune_engine_version.markdown [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+```
+
+## Argument Reference
+
+The following arguments are supported:
+
+* `engine` - (Optional) DB engine. (Default: `neptune`)
+* `parameter_group_name` - (Optional) The name of a specific DB parameter group family. An example parameter group family is `neptune1`.
+* `preferred_versions` - (Optional) Ordered list of preferred engine versions. The first match in this list will be returned. If no preferred matches are found and the original search returned more than one result, an error is returned.
+* `version` - (Optional) Version of the DB engine. For example, `1.0.1.0`, `1.0.2.2`, and `1.0.3.0`.
```
Comment (bflad) [inline website/docs/d/neptune_engine_version.markdown:28]: Similar note as #15228 here about mentioning that the default version will be returned otherwise 👍

File: website/docs/d/neptune_engine_version.markdown [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+## Attribute Reference
+
+In addition to all arguments above, the following attributes are exported:
+
+* `engine_description` - The description of the database engine.
+* `exportable_log_types` - The types of logs that the database engine has available for export to CloudWatch Logs.
+* `supported_timezones` - A list of the time zones supported by this engine.
+* `supports_log_exports_to_cloudwatch` - Indicates whether the engine version supports exporting the log types specified by `exportable_log_types` to CloudWatch Logs.
+* `supports_read_replica` - Indicates whether the database engine version supports read replicas.
+* `valid_upgrade_targets` - A list of engine versions that this database engine version can be upgraded to.
```
Comment (bflad) [inline website/docs/d/neptune_engine_version.markdown:39]: Similar note as #15228 here:

```suggestion
* `exportable_log_types` - Set of log types that the database engine has available for export to CloudWatch Logs.
* `supported_timezones` - Set of the time zones supported by this engine.
* `supports_log_exports_to_cloudwatch` - Indicates whether the engine version supports exporting the log types specified by `exportable_log_types` to CloudWatch Logs.
* `supports_read_replica` - Indicates whether the database engine version supports read replicas.
* `valid_upgrade_targets` - Set of engine versions that this database engine version can be upgraded to.
```

**Review by bflad — APPROVED** [review]
Looks good! Similar comments as #15228 🚀 

Output from acceptance testing:

```
--- PASS: TestAccAWSNeptuneEngineVersionDataSource_defaultOnly (13.67s)
--- PASS: TestAccAWSNeptuneEngineVersionDataSource_basic (13.92s)
--- PASS: TestAccAWSNeptuneEngineVersionDataSource_preferred (14.09s)
```
