### PR TITLE
data-source/aws_rds_orderable_db_instance: New data source

### LINKED ISSUE #14834: data-source/aws_rds_orderable_db_instance: New data source
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Relates #14882, Fixed by #14853 

### Description

Knowing which combinations of DB instance class, engine, engine version, and license model are available is non-trivial especially in GovCloud and other specialty partitions. For example, attempting to use a `t3.small` on GovCloud, a valid option for `us-west-2` in the standard partition, gives this error:

```
Error creating DB Instance: InvalidParameterCombination: RDS does not support creating a DB instance with the following combination: DBInstanceClass=db.t3.small, Engine=mysql, EngineVersion=5.6.41, LicenseModel=general-public-license. For supported combinations of instance class and database engine version, see the documentation.
```

I envision something similar to `aws_ec2_instance_type_offering`.

### New or Affected Resource(s)

* aws_rds_orderable_db_instance

### Potential Terraform Configuration

```hcl
data "aws_rds_orderable_db_instance" "test" {
  availability_zone_group = "us-west-2-lax-1"
  db_instance_class = "db.t2.small"
  engine = "mysql"
  engine_version = "5.7"
  license_model = "general-public-license"

  preferred_instance_types = ["t3.micro", "t2.micro"]
}

resource "aws_db_instance" "source" {
  allocated_storage   = 5
  engine              = data.aws_rds_orderable_db_instance.test.engine    # "mysql"
  engine_version      = data.aws_rds_orderable_db_instance.test.engine_version    # "5.7.22"
  identifier          = "db-source"
  instance_class      = data.aws_rds_orderable_db_instance.test.instance_class    # "db.m3.medium"
  password            = "avoid-plaintext-passwords"
  username            = "tfacctest"
  skip_final_snapshot = true
}
```

### References

* [resource/db_instance](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance)
* [data-source/db_instance](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/db_instance)
* [data-source/ec2_instance_type_offering](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ec2_instance_type_offering)

### PR DESCRIPTION
**Pull request by YakDriver**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #14834 

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
* data-source/aws_rds_orderable_db_instance: New data source to find valid RDS DB instance parameter
combinations
```

Output from acceptance testing:

Testing on GovCloud:
```
--- PASS: TestAccAWSRdsOrderableDbInstanceDataSource_basic (17.07s)
--- PASS: TestAccAWSRdsOrderableDbInstanceDataSource_preferred (17.53s)
--- PASS: TestAccAWSRdsOrderableDbInstanceDataSource_versionPrefix (17.54s)
--- PASS: TestAccAWSRdsOrderableDbInstanceDataSource_preferredVersionPrefix (37.74s)
```

Testing on commercial/standard partition:
```
--- PASS: TestAccAWSRdsOrderableDbInstanceDataSource_basic (13.75s)
--- PASS: TestAccAWSRdsOrderableDbInstanceDataSource_versionPrefix (15.11s)
--- PASS: TestAccAWSRdsOrderableDbInstanceDataSource_preferred (15.60s)
--- PASS: TestAccAWSRdsOrderableDbInstanceDataSource_preferredVersionPrefix (178.14s)
```

### CODE REVIEW

File: aws/data_source_aws_rds_orderable_db_instance.go [hunk 1]
```diff
@@ -0,0 +1,368 @@
...
+		input.Vpc = aws.Bool(v.(bool))
+	}
+
+	log.Printf("[DEBUG] Reading RDS Orderable DB Instance Options: %v", input)
+	var instanceClassResults []string
+	var instanceEngineVersions []string
+	instanceInfo := make(map[string]interface{})
+
+	for {
+		output, err := conn.DescribeOrderableDBInstanceOptions(input)
```
Comment (bflad) [inline aws/data_source_aws_rds_orderable_db_instance.go:206]: The AWS Go SDK provides a paginator for this API call 👍  [`DescribeOrderableDBInstanceOptionsPages`](https://docs.aws.amazon.com/sdk-for-go/api/service/rds/#RDS.DescribeOrderableDBInstanceOptionsPages)

File: aws/data_source_aws_rds_orderable_db_instance.go [hunk 2]
```diff
@@ -0,0 +1,368 @@
...
+
+	if foundInstanceClass == "" && len(instanceClassResults) == 1 {
+		foundInstanceClass = instanceClassResults[0]
+	}
+
+	if foundInstanceClass == "" {
+		return fmt.Errorf("no RDS DB Instance Classes match the criteria; try a different search")
+	}
+
+	d.SetId(resource.UniqueId())
```
Comment (bflad) [inline aws/data_source_aws_rds_orderable_db_instance.go:310]: To prevent future issues (https://github.com/terraform-providers/terraform-provider-aws/issues/14579), this should likely be set to the instance class for now:

```suggestion
	d.SetId(foundInstanceClass)
```

File: aws/data_source_aws_rds_orderable_db_instance.go [hunk 3]
```diff
@@ -0,0 +1,368 @@
...
+
+	d.Set("db_instance_class", foundInstanceClass)
+
+	instanceOption := *instanceInfo[foundInstanceClass].(*rds.OrderableDBInstanceOption)
+
+	d.Set("availability_zone_group", aws.StringValue(instanceOption.AvailabilityZoneGroup))
```
Comment (bflad) [inline aws/data_source_aws_rds_orderable_db_instance.go:316]: Nit: Here and below, `d.Set()` automatically handles pointers, so we don't need to add the conversion functions. This will ensure that references will be missing for things the API doesn't return.

```suggestion
	d.Set("availability_zone_group", instanceOption.AvailabilityZoneGroup)
```

File: aws/data_source_aws_rds_orderable_db_instance_test.go [hunk 4]
```diff
@@ -0,0 +1,167 @@
...
+	resource.ParallelTest(t, resource.TestCase{
+		PreCheck:     func() { testAccPreCheck(t); testAccPreCheckAWSRdsOrderableDbInstance(t) },
+		Providers:    testAccProviders,
+		CheckDestroy: nil,
+		Steps: []resource.TestStep{
+			{
+				Config: testAccAWSRdsOrderableDbInstanceDataSourceConfigVersionPrefix(engine, engineVersionPrefix),
+				Check: resource.ComposeTestCheckFunc(
+					resource.TestCheckResourceAttr(dataSourceName, "engine", engine),
+					resource.TestCheckResourceAttr(dataSourceName, "engine_version", "5.7.30"),
```
Comment (bflad) [inline aws/data_source_aws_rds_orderable_db_instance_test.go:70]: I would be concerned that this value may update regularly over time and that we might want to fetch the true value in a PreCheck, but I have additional comments about this functionality that I'll write up separately.

File: website/docs/d/rds_orderable_db_instance.markdown [hunk 5]
```diff
@@ -0,0 +1,61 @@
...
+
+## Argument Reference
+
+The following arguments are supported:
+
+* `engine` - (Required) DB engine. Engine values include `aurora`, `aurora-mysql`, `aurora-postgresql`, `docdb`, `mariadb`, `mysql`, `neptune`, `oracle-ee`, `oracle-se`, `oracle-se1`, `oracle-se2`, `postgres`, `sqlserver-ee`, `sqlserver-ex`, `sqlserver-se`, and `sqlserver-web`.
+* `availability_zone_group` - (Optional) Availability zone group.
+* `db_instance_class` - (Optional) DB instance class. Examples of classes are `db.m3.2xlarge`, `db.t2.small`, and `db.m3.medium`.
+* `engine_version` - (Optional) Version of the DB engine.
+* `engine_version_prefix` - (Optional) Prefix of the version of the DB engine. NOTE: This attempts to return only the latest version with the given prefix but may not understand version numbers for all engines.
```
Comment (bflad) [inline website/docs/d/rds_orderable_db_instance.markdown:33]: While I totally understand the nice utility this would provide, this functionality seems farther away from our normal "we only support want to support what the API supports" design principle in the provider. In particular, I have some concerns about the upkeep of this functionality because RDS has very inconsistent engine version naming across engines that is not necessarily just numbers or alphabetical. I think this would be much better suited as a feature request to AWS itself, rather than something we try to support client-side in the provider.

Let's remove this for now. 👍

**Comment by YakDriver** [comment]
Post changes:

Gov cloud:
```
--- PASS: TestAccAWSRdsOrderableDbInstanceDataSource_basic (16.33s)
--- PASS: TestAccAWSRdsOrderableDbInstanceDataSource_preferred (15.86s)
```

Commercial:
```
```

File: website/docs/d/rds_orderable_db_instance.markdown (hunk 5 above)
Comment (YakDriver) [reply website/docs/d/rds_orderable_db_instance.markdown:33]: Done.

File: aws/data_source_aws_rds_orderable_db_instance.go [hunk 6]
```diff
@@ -0,0 +1,301 @@
...
+		input.LicenseModel = aws.String(v.(string))
+	}
+
+	if v, ok := d.GetOk("vpc"); ok {
+		input.Vpc = aws.Bool(v.(bool))
+	}
+
+	log.Printf("[DEBUG] Reading RDS Orderable DB Instance Options: %v", input)
+	var instanceClassResults []string
+	var instanceEngineVersions []string
```
Comment (bflad) [inline aws/data_source_aws_rds_orderable_db_instance.go:194]: This variable is now extraneous 🎉

File: aws/data_source_aws_rds_orderable_db_instance.go [hunk 7]
```diff
@@ -0,0 +1,301 @@
...
+	instanceInfo := make(map[string]interface{})
```
Comment (bflad) [inline aws/data_source_aws_rds_orderable_db_instance.go:195]: Rather than creating this as an interface variable along with type assertions, etc, it may be easier to do one of the following:

* Make this a `map[string]*rds.OrderableDBInstanceOption` instead
* Make `instanceClassResults` a `[]*rds.OrderableDBInstanceOption` and use it directly for logic instead of creating this extra variable

👍
