### PR TITLE
resource/aws_route: Support route import

### LINKED ISSUE #2270: Updating network_interface_id in aws_route fails
### Terraform Version
Terraform v0.10.8
provider.aws 1.2.0

### Affected Resource(s)
- aws_route

### Terraform Configuration Files
Config 1:
```hcl
provider "aws" {
  version             = "~>1.2.0"
}

resource "aws_route" "route_to_eni" {
  route_table_id         = "rtb-ba9acbbb"
  destination_cidr_block = "1.2.3.0/24"

  network_interface_id = "eni-35cadddd"
}
```
Config 2 (updated network_interface_id):
```hcl
provider "aws" {
  version             = "~>1.2.0"
}

resource "aws_route" "route_to_eni" {
  route_table_id         = "rtb-ba9acbbb"
  destination_cidr_block = "1.2.3.0/24"

  network_interface_id = "eni-35cadddd"
}
```

### Debug Output
https://gist.github.com/lethalpaga/28714fe7180b2debce09489c77ba1556

### Expected Behavior
The route should have been updated with the new ENI id

### Actual Behavior
The apply fails with
```
* aws_route.route_to_eni: InvalidInstanceID: There are multiple interfaces attached to instance 'i-0ec77fe2cdde1'. Please specify an interface ID for the operation instead.
	status code: 400, request id: 060b4661-c5e8-4254-92c0-ac1d13f21df7
```

### Steps to Reproduce

1. `terraform apply` with config1 to create the route
2. `terraform apply` with config2 to attempt updating it

### Important Factoids

* The route creation works fine. Updating it fails.
* In both config1 and config2 the ENI is attached to an instance that has 2 network interfaces attached.

### References
- Possibly related to GH-1426

### LINKED ISSUE #5689: Add support for importing VPC route table routes
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Allow `aws_route` resources to be imported into the current state.

### New or Affected Resource(s)

* aws_route

### Potential Terraform Configuration

```hcl
resource "aws_route" "internal-default-route" {
  route_table_id = "${aws_route_table.client-routes.id}"
  destination_cidr_block = "0.0.0.0/0"
  network_interface_id = "${aws_network_interface.router-internal.id}"
}
```

To import the route:
```console
$ terraform import aws_route.my_route r-rtb-656C65616E6F72_0.0.0.0/0
```

### References

* #704
* #5687
* #5631

### PR DESCRIPTION
**Pull request by YakDriver**
* Fixes #5689 
* Fixes #2270
* (Originally part of PR #5657)

Changes proposed in this pull request:

* Support importing AWS_ROUTE resources

Output from acceptance testing:

```console
$ make testacc TESTARGS='-run=TestAccAWSRoute_import'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -run=TestAccAWSRoute_import -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSRoute_importBasic
--- PASS: TestAccAWSRoute_importBasic (51.13s)
=== RUN   TestAccAWSRoute_importIPv6IGW
--- PASS: TestAccAWSRoute_importIPv6IGW (51.61s)
=== RUN   TestAccAWSRoute_importIPv6NetworkInterface
--- PASS: TestAccAWSRoute_importIPv6NetworkInterface (192.53s)
=== RUN   TestAccAWSRoute_importWithMultipleRTs
--- PASS: TestAccAWSRoute_importWithMultipleRTs (45.24s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	340.554s
```

### CODE REVIEW

File: aws/resource_aws_route.go [hunk 1]
```diff
@@ -250,27 +254,33 @@ func resourceAwsRouteCreate(d *schema.ResourceData, meta interface{}) error {
...
-	d.SetId(routeIDHash(d, route))
+	d.SetId(resourceAwsRouteID(d, route))
 	resourceAwsRouteSetResourceData(d, route)
 	return nil
 }
 
 func resourceAwsRouteRead(d *schema.ResourceData, meta interface{}) error {
 	conn := meta.(*AWSClient).ec2conn
+
+	err := resourceAwsRouteCheckForImport(d)
```
Comment (bflad) [inline aws/resource_aws_route.go]: The `Importer.State` and `Create` functions should handle ID errors and setting the appropriate Terraform state required for read unless we switch to using `schema.ImportStatePassthrough` for `Importer.State`. The same applies to other usage in `Update`/`Delete`/`Exists`.

File: website/docs/r/route.html.markdown [hunk 2]
```diff
@@ -89,3 +89,29 @@ will be exported as an attribute once the resource is created.
 
 - `create` - (Default `2 minutes`) Used for route creation
 - `delete` - (Default `5 minutes`) Used for route deletion
+
+## Import
+
+Individual routes can be imported using a pseudo ID defined as r-ROUTETABLEID_DESTINATION.
```
Comment (bflad) [inline website/docs/r/route.html.markdown]: If we simplify the using something like the example import function mentioned earlier, we can remove `r-` from import. 👍

File: website/docs/r/route.html.markdown [hunk 3]
```diff
@@ -89,3 +89,29 @@ will be exported as an attribute once the resource is created.
...
+
+For example, to import a route in a route table with ID rtb-656C65616E6F72 and an IPv4 CIDR destination of 10.42.0.0/16,
+the import ID would be as follows:
```
Comment (bflad) [inline website/docs/r/route.html.markdown]: Nitpick: We can remove the indirection of calling something the "import ID" and just show what we mean:

``````md
For example, to import a route in a route table with ID `rtb-656C65616E6F72` and an IPv4 CIDR destination of `10.42.0.0/16`:

```
$ terraform import aws_route.my_route rtb-656C65616E6F72_10.42.0.0/16
```

To import a route from route table `rtb-656C65616E6F72` with an IPv6 destination CIDR of `2620:0:2d0:200::8/125`:

```
$ terraform import aws_route.my_route rtb-656C65616E6F72_2620:0:2d0:200::8/125
```
``````

File: aws/resource_aws_route.go [hunk 4]
```diff
@@ -28,6 +27,9 @@ func resourceAwsRoute() *schema.Resource {
 		Update: resourceAwsRouteUpdate,
 		Delete: resourceAwsRouteDelete,
 		Exists: resourceAwsRouteExists,
+		Importer: &schema.ResourceImporter{
+			State: resourceAwsRouteImportState,
```
[the remark this answers is not in the document]
Comment (YakDriver) [reply aws/resource_aws_route.go]: Cool! I was referencing the `aws_route53_record` so that's where some of the outdated stuff comes from. This way is cleaner.

**Comment by YakDriver** [comment]
@bflad I've implemented the changes. Let me know if you see anything else.

**Comment by YakDriver** [comment]
New tests...

```console
$ make testacc TESTARGS='-run=TestAccAWSRoute_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -run=TestAccAWSRoute_ -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSRoute_basic
--- PASS: TestAccAWSRoute_basic (50.57s)
=== RUN   TestAccAWSRoute_ipv6Support
--- PASS: TestAccAWSRoute_ipv6Support (41.06s)
=== RUN   TestAccAWSRoute_ipv6ToInternetGateway
--- PASS: TestAccAWSRoute_ipv6ToInternetGateway (45.98s)
=== RUN   TestAccAWSRoute_ipv6ToInstance
--- PASS: TestAccAWSRoute_ipv6ToInstance (139.54s)
=== RUN   TestAccAWSRoute_ipv6ToNetworkInterface
--- PASS: TestAccAWSRoute_ipv6ToNetworkInterface (179.74s)
=== RUN   TestAccAWSRoute_ipv6ToPeeringConnection
--- PASS: TestAccAWSRoute_ipv6ToPeeringConnection (41.01s)
=== RUN   TestAccAWSRoute_changeRouteTable
--- PASS: TestAccAWSRoute_changeRouteTable (75.50s)
=== RUN   TestAccAWSRoute_changeCidr
--- PASS: TestAccAWSRoute_changeCidr (80.10s)
=== RUN   TestAccAWSRoute_noopdiff
--- PASS: TestAccAWSRoute_noopdiff (120.35s)
=== RUN   TestAccAWSRoute_doesNotCrashWithVPCEndpoint
--- PASS: TestAccAWSRoute_doesNotCrashWithVPCEndpoint (55.98s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	829.873s
```

**Comment by bflad** [comment]
This has been released in [version 1.34.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1340-august-30-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
