### PR TITLE
resource/aws_api_gateway_usag_plan: Fixed setting of rate_limit

### LINKED ISSUE #2057: aws_api_gateway_usage_plan rate_limit does not "take" the first time
### Terraform Version
Terraform v0.10.7

### Terraform Configuration Files
```hcl
terraform {
    required_version = ">= 0.10.7"
    backend "s3" {}
}

provider "aws" {
    region = "${var.region}"
}

resource "aws_api_gateway_api_key" "api_key" {
    name = "${var.key_name}"
    description = "${var.key_description}"
    enabled = true
}

resource "aws_api_gateway_usage_plan" "usage_plan" {
    name         = "${var.key_name}"
    description  = "Usage plan specific to the ${var.key_name} API key"
    quota_settings {
        limit  = "${var.quota_limit}"
        period = "${var.quota_period}"
    }
    throttle_settings {
        burst_limit = "${var.burst_limit}"
        rate_limit  = "${var.steady_state_limit}"
    }
    api_stages {
        api_id = "${var.api_gateway_id}"
        stage  = "${var.deployment_stage_name}"
    }
}

resource "aws_api_gateway_usage_plan_key" "usage_plan_key" {
    key_id        = "${aws_api_gateway_api_key.api_key.id}"
    key_type      = "API_KEY"
    usage_plan_id = "${aws_api_gateway_usage_plan.usage_plan.id}"
}
```

### Debug Output
Due to the nature of the reproduction scenario, I've lost my debug file but could try and create it if it is deemed important.

### Crash Output
None.

### Expected Behavior
The first `apply` of the module should set the `rate_limit` attribute to the specified value.

### Actual Behavior
The `rate_limit` attribute is set to 0.  

### Steps to Reproduce
1. `terraform init`
1. `terraform plan`
1. `terraform apply`
1. `terraform plan`
1. `terraform apply`

You should notice that the second `apply` correctly sets the desired value.  You have to apply twice in order for the value to take.  The other attributes appear to be correctly on the first `apply`.

### Important Factoids
Running on Ubuntu 16.04

### References
None found.

### PR DESCRIPTION
**Pull request by Ninir**
Fixes #2057

This fixes the fact to correctly send the value on creation, due to the casting made: as the schema type is of type int and we try to check if the value cast as a float64 is ok, the check was always ignored on creation.

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSAPIGatewayUsagePlan_'                               
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSAPIGatewayUsagePlan_ -timeout 120m
=== RUN   TestAccAWSAPIGatewayUsagePlan_importBasic
--- PASS: TestAccAWSAPIGatewayUsagePlan_importBasic (18.08s)
=== RUN   TestAccAWSAPIGatewayUsagePlan_basic
--- PASS: TestAccAWSAPIGatewayUsagePlan_basic (98.03s)
=== RUN   TestAccAWSAPIGatewayUsagePlan_description
--- PASS: TestAccAWSAPIGatewayUsagePlan_description (83.69s)
=== RUN   TestAccAWSAPIGatewayUsagePlan_productCode
--- PASS: TestAccAWSAPIGatewayUsagePlan_productCode (78.23s)
=== RUN   TestAccAWSAPIGatewayUsagePlan_throttling
--- PASS: TestAccAWSAPIGatewayUsagePlan_throttling (59.58s)
=== RUN   TestAccAWSAPIGatewayUsagePlan_quota
--- PASS: TestAccAWSAPIGatewayUsagePlan_quota (73.80s)
=== RUN   TestAccAWSAPIGatewayUsagePlan_apiStages
--- PASS: TestAccAWSAPIGatewayUsagePlan_apiStages (87.80s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	499.266s
```

### CODE REVIEW

File: aws/resource_aws_api_gateway_usage_plan.go [hunk 1]
```diff
@@ -355,7 +355,7 @@ func resourceAwsApiGatewayUsagePlanUpdate(d *schema.ResourceData, meta interface
 				operations = append(operations, &apigateway.PatchOperation{
 					Op:    aws.String("replace"),
 					Path:  aws.String("/throttle/rateLimit"),
-					Value: aws.String(strconv.Itoa(d["rate_limit"].(int))),
+					Value: aws.String(strconv.FormatFloat(d["rate_limit"].(float64), 'E', -1, 64)),
```
Comment (radeksimko) [inline aws/resource_aws_api_gateway_usage_plan.go]: Maybe a nitpick, but is there any value in exposing the exponent? i.e. in using `E`? Is the API actually going to parse it correctly and do something with it?

File: aws/resource_aws_api_gateway_usage_plan.go [hunk 2]
```diff
@@ -369,7 +369,7 @@ func resourceAwsApiGatewayUsagePlanUpdate(d *schema.ResourceData, meta interface
 				operations = append(operations, &apigateway.PatchOperation{
 					Op:    aws.String("add"),
 					Path:  aws.String("/throttle/rateLimit"),
-					Value: aws.String(strconv.Itoa(d["rate_limit"].(int))),
+					Value: aws.String(strconv.FormatFloat(d["rate_limit"].(float64), 'E', -1, 64)),
```
Comment (radeksimko) [inline aws/resource_aws_api_gateway_usage_plan.go]: Same question here ^

File: aws/resource_aws_api_gateway_usage_plan.go (hunk 1 above)
Comment (Ninir) [reply aws/resource_aws_api_gateway_usage_plan.go]: Probably no value, preferred the use of the `f` format instead

**Comment by Ninir** [comment]
Here we go! 
```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSAPIGatewayUsagePlan_throttlingInitialRateLimit'      
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSAPIGatewayUsagePlan_throttlingInitialRateLimit -timeout 120m
=== RUN   TestAccAWSAPIGatewayUsagePlan_throttlingInitialRateLimit
--- PASS: TestAccAWSAPIGatewayUsagePlan_throttlingInitialRateLimit (18.69s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	18.739s
```
