### PR TITLE
resource/aws_sqs_queue: Retry queue creation on QueueDeletedRecently error

### LINKED ISSUE #831: SQS recreate fails due to required AWS timeout
_This issue was originally opened by @batkuip as hashicorp/terraform#15139. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version
0.9.6

### Affected Resource(s)
aws_sqs_queue

### Terraform Configuration Files
```hcl
resource "aws_sqs_queue" "etl_deadletter" {
  name = "${var.prefix}-etl-deadletter"
}
```

### Debug Output
```
* aws_sqs_queue.etl_deadletter: Error creating SQS queue: AWS.SimpleQueueService.QueueDeletedRecently: You must wait 60 seconds after deleting a queue before you can create another with the same name.
```

### Expected Behavior
Recreation of the queue

### Actual Behavior
Blocked due to 60 seconds required delay on AWS side

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Tried to use 'name-prefix' as used by others but that wouldn't work for sqs queue.  That would be a nice easy fix.

### PR DESCRIPTION
**Pull request by bflad**
Closes #831 

Failing test before implementation:
```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSSQSQueue_queueDeletedRecently'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSSQSQueue_queueDeletedRecently -timeout 120m
=== RUN   TestAccAWSSQSQueue_queueDeletedRecently
--- FAIL: TestAccAWSSQSQueue_queueDeletedRecently (14.98s)
	testing.go:513: Step 2 error: Error applying: 1 error(s) occurred:

		* aws_sqs_queue.queue: 1 error(s) occurred:

		* aws_sqs_queue.queue: Error creating SQS queue: AWS.SimpleQueueService.QueueDeletedRecently: You must wait 60 seconds after deleting a queue before you can create another with the same name.
			status code: 400, request id: 8f81b2fe-c49a-5819-abb2-e01f98ce0b03
FAIL
exit status 1
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	15.024s
make: *** [testacc] Error 1
```

Passing test after implementation:
```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSSQSQueue_queueDeletedRecently'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSSQSQueue_queueDeletedRecently -timeout 120m
=== RUN   TestAccAWSSQSQueue_queueDeletedRecently
--- PASS: TestAccAWSSQSQueue_queueDeletedRecently (83.52s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	83.572s
```

### CODE REVIEW

File: aws/resource_aws_sqs_queue.go [hunk 1]
```diff
@@ -187,7 +188,18 @@ func resourceAwsSqsQueueCreate(d *schema.ResourceData, meta interface{}) error {
 		req.Attributes = attributes
 	}
 
-	output, err := sqsconn.CreateQueue(req)
+	var output *sqs.CreateQueueOutput
+	err := resource.Retry(1*time.Minute, func() *resource.RetryError {
+		var err error
+		output, err = sqsconn.CreateQueue(req)
+		if err != nil {
+			if isAWSErr(err, sqs.ErrCodeQueueDeletedRecently, "You must wait 60 seconds after deleting a queue before you can create another with the same name.") {
```
Comment (radeksimko) [inline aws/resource_aws_sqs_queue.go]: Nitpick, but I'd perhaps loosen the match here a little bit, just in case they raise the limit from 60 secs, i.e.

`after deleting a queue before you can create another with the same name.`

or maybe even

`You must wait `

Comment (bflad) [reply aws/resource_aws_sqs_queue.go]: If they change the limit, then we should adjust our retry threshold to match it. Our daily acceptance testing will start failing since this conditional will always return a `NonRetryableError`

Comment (radeksimko) [reply aws/resource_aws_sqs_queue.go]: Ah, very good point 👌   - ignore me then! 😅

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.8.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#180-january-29-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
