### PR TITLE
Fix ES domain creation when transient errors occur

### LINKED ISSUE #7725: aws_elasticsearch_domain failed with ValidationException: Authentication error status code: 400
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

- terraform version: 0.11.10
- aws provider version: 1.43.2

### Affected Resource(s)

* aws_elasticsearch_domain

### Terraform Configuration Files

```hcl
resource "aws_elasticsearch_domain" "logs" {
  domain_name           = "logs"
  elasticsearch_version = "5.6"

  cluster_config {
    instance_type = "t2.medium.elasticsearch"
  }

  ebs_options {
    ebs_enabled = true
    volume_type = "gp2"
    volume_size = "10"
  }

  advanced_options {
    "rest.action.multi.allow_explicit_index" = "true"
  }

  vpc_options {
    subnet_ids         = [...]
    security_group_ids = [...]
  }

  access_policies = "${data.aws_iam_policy_document.es-logs-policy.json}"

  tags {
    Domain = "logs"
  }
}
```

### Debug Output

This is a one time issue and we don't have debug outputs

### Error Output

```
aws_elasticsearch_domain.logs: Creating...
  access_policies:                                         "" => "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Sid\": \"\",\n      \"Effect\": \"Allow\",\n      \"Action\": [\n        \"es:ESHttpPut\",\n        \"es:ESHttpPost\",\n        \"es:ESHttpHead\",\n        \"es:ESHttpGet\",\n        \"es:ESHttpDelete\"\n      ],\n      \"Resource\": \"arn:aws:es:eu-west-1:609892909616:domain/logs/*\",\n      \"Principal\": {\n        \"AWS\": \"*\"\n      }\n    },\n    {\n      \"Sid\": \"\",\n      \"Effect\": \"Allow\",\n      \"Action\": \"es:*\",\n      \"Resource\": \"arn:aws:es:eu-west-1:609892909616:domain/logs/*\",\n      \"Principal\": {\n        \"AWS\": \"arn:aws:iam::609892909616:user/terraform\"\n      }\n    }\n  ]\n}"
  advanced_options.%:                                      "" => "1"
  advanced_options.rest.action.multi.allow_explicit_index: "" => "true"
  arn:                                                     "" => "<computed>"
  cluster_config.#:                                        "" => "1"
  cluster_config.0.dedicated_master_enabled:               "" => "false"
  cluster_config.0.instance_count:                         "" => "1"
  cluster_config.0.instance_type:                          "" => "t2.medium.elasticsearch"
  domain_id:                                               "" => "<computed>"
  domain_name:                                             "" => "logs"
  ebs_options.#:                                           "" => "1"
  ebs_options.0.ebs_enabled:                               "" => "true"
  ebs_options.0.volume_size:                               "" => "10"
  ebs_options.0.volume_type:                               "" => "gp2"
  elasticsearch_version:                                   "" => "5.6"
  encrypt_at_rest.#:                                       "" => "<computed>"
  endpoint:                                                "" => "<computed>"
  kibana_endpoint:                                         "" => "<computed>"
  node_to_node_encryption.#:                               "" => "<computed>"
  tags.%:                                                  "" => "1"
  tags.Domain:                                             "" => "logs"
  vpc_options.#:                                           "" => "1"
  vpc_options.0.availability_zones.#:                      "" => "<computed>"
  vpc_options.0.security_group_ids.#:                      "" => "1"
  vpc_options.0.security_group_ids.4135710086:             "" => "sg-0d0b5d18902b695de"
  vpc_options.0.subnet_ids.#:                              "" => "1"
  vpc_options.0.subnet_ids.870623161:                      "" => "subnet-0f5978a9a8e37b888"
  vpc_options.0.vpc_id:                                    "" => "<computed>"
...
Releasing state lock. This may take a few moments...

Error: Error applying plan:

1 error(s) occurred:

* aws_elasticsearch_domain.logs: 1 error(s) occurred:

* aws_elasticsearch_domain.logs: ValidationException: Authentication error
	status code: 400, request id: 423f50f6-3960-11e9-85cb-8f4ed15bd4e2
```

### Expected Behavior

No error

### Actual Behavior

```
* aws_elasticsearch_domain.logs: ValidationException: Authentication error
	status code: 400, request id: 423f50f6-3960-11e9-85cb-8f4ed15bd4e2
```

### Steps to Reproduce

random

### Important Factoids

Usually works well

### References

### PR DESCRIPTION
**Pull request by obourdon**
Fix for issue #7725

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #7725 

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
BUG FIXES:
* aws_elasticsearch_domain failed with ValidationException: Authentication error status code: 400
```

Output from acceptance testing:

```
$ $ AWS_DEFAULT_REGION=eu-west-1 AWS_PROFILE=scratch gmake testacc TEST=./aws TESTARGS='-run=TestAccAWSElasticSearchDomain'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSElasticSearchDomain -timeout 120m
=== RUN   TestAccAWSElasticSearchDomainPolicy_basic
=== PAUSE TestAccAWSElasticSearchDomainPolicy_basic
=== RUN   TestAccAWSElasticSearchDomain_basic
=== PAUSE TestAccAWSElasticSearchDomain_basic
=== RUN   TestAccAWSElasticSearchDomain_ClusterConfig_ZoneAwarenessConfig
=== PAUSE TestAccAWSElasticSearchDomain_ClusterConfig_ZoneAwarenessConfig
=== RUN   TestAccAWSElasticSearchDomain_withDedicatedMaster
=== PAUSE TestAccAWSElasticSearchDomain_withDedicatedMaster
=== RUN   TestAccAWSElasticSearchDomain_duplicate
=== PAUSE TestAccAWSElasticSearchDomain_duplicate
=== RUN   TestAccAWSElasticSearchDomain_v23
=== PAUSE TestAccAWSElasticSearchDomain_v23
=== RUN   TestAccAWSElasticSearchDomain_complex
=== PAUSE TestAccAWSElasticSearchDomain_complex
=== RUN   TestAccAWSElasticSearchDomain_vpc
=== PAUSE TestAccAWSElasticSearchDomain_vpc
=== RUN   TestAccAWSElasticSearchDomain_vpc_update
=== PAUSE TestAccAWSElasticSearchDomain_vpc_update
=== RUN   TestAccAWSElasticSearchDomain_internetToVpcEndpoint
=== PAUSE TestAccAWSElasticSearchDomain_internetToVpcEndpoint
=== RUN   TestAccAWSElasticSearchDomain_LogPublishingOptions
=== PAUSE TestAccAWSElasticSearchDomain_LogPublishingOptions
=== RUN   TestAccAWSElasticSearchDomain_CognitoOptionsCreateAndRemove
=== PAUSE TestAccAWSElasticSearchDomain_CognitoOptionsCreateAndRemove
=== RUN   TestAccAWSElasticSearchDomain_CognitoOptionsUpdate
=== PAUSE TestAccAWSElasticSearchDomain_CognitoOptionsUpdate
=== RUN   TestAccAWSElasticSearchDomain_policy
=== PAUSE TestAccAWSElasticSearchDomain_policy
=== RUN   TestAccAWSElasticSearchDomain_encrypt_at_rest_default_key
=== PAUSE TestAccAWSElasticSearchDomain_encrypt_at_rest_default_key
=== RUN   TestAccAWSElasticSearchDomain_encrypt_at_rest_specify_key
=== PAUSE TestAccAWSElasticSearchDomain_encrypt_at_rest_specify_key
=== RUN   TestAccAWSElasticSearchDomain_NodeToNodeEncryption
=== PAUSE TestAccAWSElasticSearchDomain_NodeToNodeEncryption
=== RUN   TestAccAWSElasticSearchDomain_tags
=== PAUSE TestAccAWSElasticSearchDomain_tags
=== RUN   TestAccAWSElasticSearchDomain_update
=== PAUSE TestAccAWSElasticSearchDomain_update
=== RUN   TestAccAWSElasticSearchDomain_update_volume_type
=== PAUSE TestAccAWSElasticSearchDomain_update_volume_type
=== RUN   TestAccAWSElasticSearchDomain_update_version
=== PAUSE TestAccAWSElasticSearchDomain_update_version
=== CONT  TestAccAWSElasticSearchDomainPolicy_basic
=== CONT  TestAccAWSElasticSearchDomain_CognitoOptionsCreateAndRemove
=== CONT  TestAccAWSElasticSearchDomain_LogPublishingOptions
=== CONT  TestAccAWSElasticSearchDomain_policy
=== CONT  TestAccAWSElasticSearchDomain_v23
=== CONT  TestAccAWSElasticSearchDomain_withDedicatedMaster
=== CONT  TestAccAWSElasticSearchDomain_CognitoOptionsUpdate
=== CONT  TestAccAWSElasticSearchDomain_update_version
=== CONT  TestAccAWSElasticSearchDomain_complex
=== CONT  TestAccAWSElasticSearchDomain_update
=== CONT  TestAccAWSElasticSearchDomain_vpc_update
=== CONT  TestAccAWSElasticSearchDomain_internetToVpcEndpoint
=== CONT  TestAccAWSElasticSearchDomain_vpc
=== CONT  TestAccAWSElasticSearchDomain_encrypt_at_rest_default_key
=== CONT  TestAccAWSElasticSearchDomain_NodeToNodeEncryption
=== CONT  TestAccAWSElasticSearchDomain_encrypt_at_rest_specify_key
=== CONT  TestAccAWSElasticSearchDomain_duplicate
=== CONT  TestAccAWSElasticSearchDomain_ClusterConfig_ZoneAwarenessConfig
=== CONT  TestAccAWSElasticSearchDomain_tags
=== CONT  TestAccAWSElasticSearchDomain_update_volume_type
--- PASS: TestAccAWSElasticSearchDomain_duplicate (500.07s)
=== CONT  TestAccAWSElasticSearchDomain_basic
--- PASS: TestAccAWSElasticSearchDomain_tags (819.89s)
--- PASS: TestAccAWSElasticSearchDomain_encrypt_at_rest_default_key (839.54s)
--- PASS: TestAccAWSElasticSearchDomain_policy (1075.47s)
--- PASS: TestAccAWSElasticSearchDomain_complex (1098.33s)
--- PASS: TestAccAWSElasticSearchDomain_v23 (1104.13s)
--- PASS: TestAccAWSElasticSearchDomain_LogPublishingOptions (1185.27s)
--- PASS: TestAccAWSElasticSearchDomain_encrypt_at_rest_specify_key (1257.04s)
--- PASS: TestAccAWSElasticSearchDomain_basic (884.73s)
--- PASS: TestAccAWSElasticSearchDomainPolicy_basic (1414.86s)
--- PASS: TestAccAWSElasticSearchDomain_NodeToNodeEncryption (1446.40s)
--- PASS: TestAccAWSElasticSearchDomain_vpc (1650.59s)
--- PASS: TestAccAWSElasticSearchDomain_CognitoOptionsUpdate (1812.42s)
--- PASS: TestAccAWSElasticSearchDomain_internetToVpcEndpoint (2266.66s)
--- PASS: TestAccAWSElasticSearchDomain_CognitoOptionsCreateAndRemove (2341.65s)
--- PASS: TestAccAWSElasticSearchDomain_update (2789.07s)
--- PASS: TestAccAWSElasticSearchDomain_vpc_update (2904.30s)
--- PASS: TestAccAWSElasticSearchDomain_withDedicatedMaster (3019.82s)
--- PASS: TestAccAWSElasticSearchDomain_update_version (3148.25s)
--- PASS: TestAccAWSElasticSearchDomain_update_volume_type (3173.39s)
--- PASS: TestAccAWSElasticSearchDomain_ClusterConfig_ZoneAwarenessConfig (4686.86s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	4686.955s
$
```

### CODE REVIEW

File: aws/resource_aws_elasticsearch_domain.go [hunk 1]
```diff
@@ -472,6 +473,21 @@ func resourceAwsElasticSearchDomainCreate(d *schema.ResourceData, meta interface
 			if isAWSErr(err, "ValidationException", "The passed role has not propagated yet") {
 				return resource.RetryableError(err)
 			}
+			if isAWSErr(err, "ValidationException", "Authentication error") ||
+				isAWSErr(err, "ValidationException", "Unauthorized Operation: Elasticsearch must be authorised to describeVpcs") ||
+				isAWSErr(err, "ValidationException", "Unauthorized Operation: Elasticsearch must be authorised to describeSubnets") ||
+				isAWSErr(err, "ValidationException", "Before you can proceed, you must enable a service-linked role to give Amazon ES permissions to access your VPC") {
+				log.Printf("[DEBUG] Retrying creation of ElasticSearch domain %s (transient error)", aws.StringValue(input.DomainName))
+				return resource.RetryableError(err)
+			}
```
Comment (bflad) [inline aws/resource_aws_elasticsearch_domain.go]: Can you please split these into separate conditionals? The third parameter is also uses `strings.Contains()`, so messages can be consolidated as well. The `enable a service-linked role` error is already handled on line 463.

```go
			if isAWSErr(err, "ValidationException", "Authentication error") {
				return resource.RetryableError(err)
			}
			// Example: ValidationException: Unauthorized Operation: Elasticsearch must be authorised to describeSubnets
			// Example: ValidationException: Unauthorized Operation: Elasticsearch must be authorised to describeVpcs
			if isAWSErr(err, "ValidationException", "Unauthorized Operation: Elasticsearch must be authorised")  {
				return resource.RetryableError(err)
			}
```

We also have an additional error condition to retry on if you could add it as well please:

```
--- FAIL: TestAccAWSElasticSearchDomain_CognitoOptionsCreateAndRemove (17.30s)
    testing.go:635: Step 0 error: errors during apply:
        
        Error: Error creating ElasticSearch domain: ValidationException: The passed role must authorize Amazon Elasticsearch to describeUserPool
```

```go
			// Example: ValidationException: The passed role must authorize Amazon Elasticsearch to describeUserPool
			if isAWSErr(err, "ValidationException", "The passed role must authorize") {
				return resource.RetryableError(err)
			}
```

It is a shame the Elasticsearch API does not use a separate error code to signal IAM issues instead. 😅

File: aws/resource_aws_elasticsearch_domain.go [hunk 2]
```diff
@@ -472,6 +473,21 @@ func resourceAwsElasticSearchDomainCreate(d *schema.ResourceData, meta interface
...
+			// New transient AWS error
+			var awsErr awserr.Error
+			if errors.As(err, &awsErr) {
+				if awsErr.Code() == "ValidationException" && len(awsErr.Message()) == 0 {
+					log.Printf("[DEBUG] Empty ValidationException ElasticSearch domain %s (transient error)", aws.StringValue(input.DomainName))
+					return resource.RetryableError(err)
+				}
+			}
```
Comment (bflad) [inline aws/resource_aws_elasticsearch_domain.go]: This error handling is unnecessary as it was caused by https://github.com/terraform-providers/terraform-provider-aws/issues/11682, which has been resolved.

Comment (obourdon) [reply aws/resource_aws_elasticsearch_domain.go]: Totally agree

File: aws/resource_aws_elasticsearch_domain.go (hunk 1 above)
Comment (obourdon) [reply aws/resource_aws_elasticsearch_domain.go]: @bflad currently implementing the requested changes. Many thanks for this review
BTW if you or someone could also have a look at #11671 that would be awesome

**Comment by obourdon** [comment]
Strangely I got this error running acceptance tests on eu-west-1 zone:

```
--- FAIL: TestAccAWSElasticSearchDomain_update_version (1461.03s)
    testing.go:640: Step 2 error: Check failed: Check 3/3 error: aws_elasticsearch_domain.test: Attribute 'elasticsearch_version' expected "5.6", got "5.5"
```

**Comment by bflad** [comment]
@obourdon that one has occasionally shown up in our daily acceptance testing from us-west-2 as well -- we should probably create a GitHub issue to capture it for eventual fixing.

**Comment by obourdon** [comment]
Oops, I now know that this error sometimes occurs (see comment above) but it seems like
version numbers are not that predictible :-( 

```
--- FAIL: TestAccAWSElasticSearchDomain_update_version (3614.61s)
    testing.go:640: Step 3 error: Check failed: Check 3/3 error: aws_elasticsearch_domain.test: Attribute 'elasticsearch_version' expected "6.3", got "5.6"
```

**Comment by obourdon** [comment]
Oops, I now know that this error sometimes occurs (see comment above) but it seems like
version numbers are not that predictible :-( 

```
--- FAIL: TestAccAWSElasticSearchDomain_update_version (3614.61s)
    testing.go:640: Step 3 error: Check failed: Check 3/3 error: aws_elasticsearch_domain.test: Attribute 'elasticsearch_version' expected "6.3", got "5.6"
```

**Comment by obourdon** [comment]
Horray!!!!
```
$ AWS_DEFAULT_REGION=eu-west-1 AWS_PROFILE=dev gmake testacc TEST=./aws TESTARGS='-run=TestAccAWSElasticSearchDomain'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSElasticSearchDomain -timeout 120m
=== RUN   TestAccAWSElasticSearchDomainPolicy_basic
=== PAUSE TestAccAWSElasticSearchDomainPolicy_basic
=== RUN   TestAccAWSElasticSearchDomain_basic
=== PAUSE TestAccAWSElasticSearchDomain_basic
=== RUN   TestAccAWSElasticSearchDomain_ClusterConfig_ZoneAwarenessConfig
=== PAUSE TestAccAWSElasticSearchDomain_ClusterConfig_ZoneAwarenessConfig
=== RUN   TestAccAWSElasticSearchDomain_withDedicatedMaster
=== PAUSE TestAccAWSElasticSearchDomain_withDedicatedMaster
=== RUN   TestAccAWSElasticSearchDomain_duplicate
=== PAUSE TestAccAWSElasticSearchDomain_duplicate
=== RUN   TestAccAWSElasticSearchDomain_v23
=== PAUSE TestAccAWSElasticSearchDomain_v23
=== RUN   TestAccAWSElasticSearchDomain_complex
=== PAUSE TestAccAWSElasticSearchDomain_complex
=== RUN   TestAccAWSElasticSearchDomain_vpc
=== PAUSE TestAccAWSElasticSearchDomain_vpc
=== RUN   TestAccAWSElasticSearchDomain_vpc_update
=== PAUSE TestAccAWSElasticSearchDomain_vpc_update
=== RUN   TestAccAWSElasticSearchDomain_internetToVpcEndpoint
=== PAUSE TestAccAWSElasticSearchDomain_internetToVpcEndpoint
=== RUN   TestAccAWSElasticSearchDomain_LogPublishingOptions
=== PAUSE TestAccAWSElasticSearchDomain_LogPublishingOptions
=== RUN   TestAccAWSElasticSearchDomain_CognitoOptionsCreateAndRemove
=== PAUSE TestAccAWSElasticSearchDomain_CognitoOptionsCreateAndRemove
=== RUN   TestAccAWSElasticSearchDomain_CognitoOptionsUpdate
=== PAUSE TestAccAWSElasticSearchDomain_CognitoOptionsUpdate
=== RUN   TestAccAWSElasticSearchDomain_policy
=== PAUSE TestAccAWSElasticSearchDomain_policy
=== RUN   TestAccAWSElasticSearchDomain_encrypt_at_rest_default_key
=== PAUSE TestAccAWSElasticSearchDomain_encrypt_at_rest_default_key
=== RUN   TestAccAWSElasticSearchDomain_encrypt_at_rest_specify_key
=== PAUSE TestAccAWSElasticSearchDomain_encrypt_at_rest_specify_key
=== RUN   TestAccAWSElasticSearchDomain_NodeToNodeEncryption
=== PAUSE TestAccAWSElasticSearchDomain_NodeToNodeEncryption
=== RUN   TestAccAWSElasticSearchDomain_tags
=== PAUSE TestAccAWSElasticSearchDomain_tags
=== RUN   TestAccAWSElasticSearchDomain_update
=== PAUSE TestAccAWSElasticSearchDomain_update
=== RUN   TestAccAWSElasticSearchDomain_update_volume_type
=== PAUSE TestAccAWSElasticSearchDomain_update_volume_type
=== RUN   TestAccAWSElasticSearchDomain_update_version
=== PAUSE TestAccAWSElasticSearchDomain_update_version
=== CONT  TestAccAWSElasticSearchDomainPolicy_basic
=== CONT  TestAccAWSElasticSearchDomain_update_volume_type
=== CONT  TestAccAWSElasticSearchDomain_encrypt_at_rest_specify_key
=== CONT  TestAccAWSElasticSearchDomain_encrypt_at_rest_default_key
=== CONT  TestAccAWSElasticSearchDomain_update
=== CONT  TestAccAWSElasticSearchDomain_tags
=== CONT  TestAccAWSElasticSearchDomain_NodeToNodeEncryption
=== CONT  TestAccAWSElasticSearchDomain_v23
=== CONT  TestAccAWSElasticSearchDomain_ClusterConfig_ZoneAwarenessConfig
=== CONT  TestAccAWSElasticSearchDomain_vpc_update
=== CONT  TestAccAWSElasticSearchDomain_vpc
=== CONT  TestAccAWSElasticSearchDomain_complex
=== CONT  TestAccAWSElasticSearchDomain_CognitoOptionsCreateAndRemove
=== CONT  TestAccAWSElasticSearchDomain_update_version
=== CONT  TestAccAWSElasticSearchDomain_LogPublishingOptions
=== CONT  TestAccAWSElasticSearchDomain_internetToVpcEndpoint
=== CONT  TestAccAWSElasticSearchDomain_duplicate
=== CONT  TestAccAWSElasticSearchDomain_policy
=== CONT  TestAccAWSElasticSearchDomain_withDedicatedMaster
=== CONT  TestAccAWSElasticSearchDomain_CognitoOptionsUpdate
--- PASS: TestAccAWSElasticSearchDomain_duplicate (493.34s)
=== CONT  TestAccAWSElasticSearchDomain_basic
--- PASS: TestAccAWSElasticSearchDomain_v23 (732.88s)
--- PASS: TestAccAWSElasticSearchDomain_LogPublishingOptions (818.37s)
--- PASS: TestAccAWSElasticSearchDomain_NodeToNodeEncryption (885.62s)
--- PASS: TestAccAWSElasticSearchDomain_complex (1060.34s)
--- PASS: TestAccAWSElasticSearchDomain_encrypt_at_rest_specify_key (1172.39s)
--- PASS: TestAccAWSElasticSearchDomain_tags (1186.26s)
--- PASS: TestAccAWSElasticSearchDomain_encrypt_at_rest_default_key (1203.41s)
--- PASS: TestAccAWSElasticSearchDomain_vpc (1316.60s)
--- PASS: TestAccAWSElasticSearchDomainPolicy_basic (1579.99s)
--- PASS: TestAccAWSElasticSearchDomain_basic (1225.71s)
--- PASS: TestAccAWSElasticSearchDomain_internetToVpcEndpoint (1860.72s)
--- PASS: TestAccAWSElasticSearchDomain_policy (1897.85s)
--- PASS: TestAccAWSElasticSearchDomain_update (2099.56s)
--- PASS: TestAccAWSElasticSearchDomain_CognitoOptionsCreateAndRemove (2730.13s)
--- PASS: TestAccAWSElasticSearchDomain_CognitoOptionsUpdate (2916.41s)
--- PASS: TestAccAWSElasticSearchDomain_update_volume_type (3118.60s)
--- PASS: TestAccAWSElasticSearchDomain_vpc_update (3160.84s)
--- PASS: TestAccAWSElasticSearchDomain_withDedicatedMaster (3217.15s)
--- PASS: TestAccAWSElasticSearchDomain_update_version (3525.03s)
--- PASS: TestAccAWSElasticSearchDomain_ClusterConfig_ZoneAwarenessConfig (5415.92s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	5416.012s
```

**Comment by obourdon** [comment]
@bflad many thanks for integrating this
