### PR TITLE
Fix ALB listener rule update regression

### LINKED ISSUE #11323: Error: Only one of field, host_header, http_header, http_request_method, path_pattern, query_string or source_ip can be set in a condition block
I think after merging https://github.com/terraform-providers/terraform-provider-aws/pull/8268 existing (now deprecated) `condition` blocks are broken.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.12.18
+ provider.aws v2.42.0
```
### Affected Resource(s)

* `aws_alb_listener_rule`

### Terraform Configuration Files

```hcl
resource "aws_alb_listener_rule" "infrastructure_version_info" {
  listener_arn = "..."
  condition {
    field  = "path-pattern"
    values = ["/infrastructure-version"]
  }
  action {
    type = "fixed-response"

    fixed_response {
      content_type = "text/html"
      message_body = "blah blah version 1"
      status_code  = "200"
    }
  }
  priority = 2
}
```

### Expected Behavior

When `message_body` is edited and thus we try to apply following plan:

```

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_alb_listener_rule.infrastructure_version_info will be updated in-place
  ~ resource "aws_alb_listener_rule" "infrastructure_version_info" {
        arn          = "arn:aws:xxxxx"
        id           = "arn:aws:xxxxxx"
        listener_arn = "arn:xxxxxx"
        priority     = 2

      ~ action {
            order = 1
            type  = "fixed-response"

          ~ fixed_response {
                content_type = "text/html"
              ~ message_body = "blah blah version 1" -> "blah blah version 2"
                status_code  = "200"
            }
        }

        condition {
            field  = "path-pattern"
            values = [
                "/infrastructure-version",
            ]

            path_pattern {
                values = [
                    "/infrastructure-version",
                ]
            }
        }
    }

```

we should update the listener rule correctly.

### Actual behavior

An error occurs:
```
Error: Only one of field, host_header, http_header, http_request_method, path_pattern, query_string or source_ip can be set in a condition block
```

### Additional information
Changing to not-deprecated version:
```hcl
  condition {
    path_pattern {
      values = ["/infrastructure-version"]
    }
  }
```
does not help.

### LINKED ISSUE #11362: aws_alb_listener_rule can not be modified when using new coniditions
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.18
+ provider.aws v2.42.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
```

### Affected Resource(s)

* aws_alb_listener_rule

### Terraform Configuration Files

```hcl
resource aws_alb_listener_rule "oidc_auth_rules" {
  count = length(var.oidc_settings)

  listener_arn = aws_alb_listener.alb_listener_user.arn
  action {
    type = "authenticate-oidc"

    authenticate_oidc {
      authorization_endpoint = "${var.oidc_settings[count.index].issuer}/authorize"
      client_id              = var.oidc_settings[count.index].client_id
      client_secret          = var.oidc_settings[count.index].client_secret
      issuer                 = "${var.oidc_settings[count.index].issuer}/"
      token_endpoint         = "${var.oidc_settings[count.index].issuer}/oauth/token"
      user_info_endpoint     = "${var.oidc_settings[count.index].issuer}/userinfo"
      session_cookie_name    = var.oidc_settings[count.index].cookie
      scope                  = "openid email profile"

      authentication_request_extra_params = {
        audience   = "${var.oidc_settings[count.index].issuer}/userinfo"
        connection = "main-tenant-oidc"
        prompt     = "login"
      }
    }
  }

  condition {
    query_string {
      key   = "profile"
      value = var.oidc_settings[count.index].profile_match
    }
  }
```

### Expected Behavior

Modifying a aws_alb_listener_rule should update the listener rule as `planned`
```
  # aws_alb_listener_rule.oidc_auth_rules[0] will be updated in-place
  ~ resource "aws_alb_listener_rule" "oidc_auth_rules" {
      ....
          ~ authenticate_oidc {
             ...

                on_unauthenticated_request          = "authenticate"
              ~ scope                               = "openid email profile" -> "openid profile"
            }
        }
       ....

        condition {
            field  = "query-string"
            values = []

            query_string {
                key   = "profile"
                value = "MPM.Search"
            }
        }
    }
```
### Actual Behavior

> Error: Both field and values must be set in a condition block
> 
>   on load_balancer.tf line 40, in resource "aws_alb_listener_rule" "oidc_auth_rules":
>   40: resource aws_alb_listener_rule "oidc_auth_rules" {

### Steps to Reproduce

1. Create a aws_alb
2. Create a aws_alb_listener
3. Create a aws_alb_listener_rule that contains a condition of type `query string`
4. `terraform apply`
5. Modify the aws_alb_listener_rule to trigger a inplace update (changing the scope for example)
6. `terraform apply`

### References

* #8268 (Feature added very recently)

### PR DESCRIPTION
**Pull request by dpiddockcmp**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #11323
Closes #11362

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_lb_listener_rule: fixes regression when updating a rule without modifying condition
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSLBListenerRule'
--- PASS: TestAccAWSLBListenerRule_multipleConditionThrowsError (3.89s)
--- PASS: TestAccAWSLBListenerRule_conditionAttributesCount (52.92s)
--- PASS: TestAccAWSLBListenerRule_basic (252.07s)
--- PASS: TestAccAWSLBListenerRule_Action_Order_Recreates (253.87s)
--- PASS: TestAccAWSLBListenerRule_conditionHostHeader (272.30s)
--- PASS: TestAccAWSLBListenerRule_Action_Order (395.72s)
--- PASS: TestAccAWSLBListenerRule_cognito (243.62s)
--- PASS: TestAccAWSLBListenerRule_oidc (294.04s)
--- PASS: TestAccAWSLBListenerRule_conditionHttpRequestMethod (295.31s)
--- PASS: TestAccAWSLBListenerRule_conditionHttpHeader_invalid (3.26s)
--- PASS: TestAccAWSLBListenerRule_priority (575.85s)
--- PASS: TestAccAWSLBListenerRule_conditionUpdatePathPattern_deprecated (388.26s)
--- PASS: TestAccAWSLBListenerRule_conditionPathPattern_deprecated (445.48s)
--- PASS: TestAccAWSLBListenerRule_conditionUpdateMultiple (314.38s)
--- PASS: TestAccAWSLBListenerRule_conditionMultiple (262.48s)
--- PASS: TestAccAWSLBListenerRule_conditionHttpHeader (413.04s)
--- PASS: TestAccAWSLBListenerRule_conditionUpdateMixed (357.01s)
--- PASS: TestAccAWSLBListenerRule_conditionSourceIp (261.76s)
--- PASS: TestAccAWSLBListenerRule_conditionQueryString (265.65s)
--- PASS: TestAccAWSLBListenerRule_conditionPathPattern (251.04s)
--- PASS: TestAccAWSLBListenerRule_redirect (263.37s)
--- PASS: TestAccAWSLBListenerRule_fixedResponse (308.00s)
--- PASS: TestAccAWSLBListenerRule_conditionHostHeader_deprecated (242.03s)
--- PASS: TestAccAWSLBListenerRule_updateFixedResponse (318.64s)
--- PASS: TestAccAWSLBListenerRule_changeListenerRuleArnForcesNew (366.77s)
--- PASS: TestAccAWSLBListenerRule_updateRulePriority (311.55s)
--- PASS: TestAccAWSLBListenerRuleBackwardsCompatibility (250.93s)
```

### CODE REVIEW

File: aws/resource_aws_lb_listener_rule.go [hunk 1]
```diff
@@ -1264,14 +1264,30 @@ func lbListenerRuleConditions(conditions []interface{}) ([]*elbv2.RuleCondition,
 		}
 
 		// Deprecated backwards compatibility
-		if cmField, ok := conditionMap["field"].(string); ok && cmField != "" {
-			field = cmField
-			attrs += 1
-			values := conditionMap["values"].([]interface{})
-			if len(values) == 0 {
-				return nil, errors.New("Both field and values must be set in a condition block")
+		// This code is also hit during an update when the condition has not been modified. Issues: GH-11232 and GH-11362
```
Comment (gdavison) [inline aws/resource_aws_lb_listener_rule.go]: Nit: the first issue GH-11323
