### PR TITLE
provider: Prevent panic when setting endpoints configuration

### LINKED ISSUE #8214: Issues creating tables: panic: assignment to entry in nil map
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
2019/04/05 12:38:38 [INFO] Terraform version: 0.11.8  7a5c1d221ac209bbac66947c369815cd9ca70ed5
2019/04/05 12:38:38 [INFO] Go runtime version: go1.10.1
```

(Also tried with 0.11.13, same behaviour)

### Affected Resource(s)

* aws_v2.5.0, `aws_dynamodb_table`

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "eu-west-2"
  version = "~> 2.5.0"

  endpoints {
    dynamodb = "http://dynamo:8000"
  }
}

resource "aws_dynamodb_table" "logins-dynamodb-table" {
  name           = "logins"
  hash_key       = "username"
  read_capacity  = "1"
  write_capacity = "1"

  attribute {
    name = "username"
    type = "S"
  }
}
```

### Debug Output

https://gist.github.com/textbook/74ae81de86d1a4d9f19a4c89ff637d2c

### Panic Output

```
2019-04-05T12:38:39.071Z [DEBUG] plugin.terraform-provider-aws_v2.5.0_x4: 2019/04/05 12:38:39 [INFO] No assume_role block read from configuration
2019-04-05T12:38:39.082Z [DEBUG] plugin.terraform-provider-aws_v2.5.0_x4: panic: assignment to entry in nil map
2019-04-05T12:38:39.082Z [DEBUG] plugin.terraform-provider-aws_v2.5.0_x4: 
2019-04-05T12:38:39.082Z [DEBUG] plugin.terraform-provider-aws_v2.5.0_x4: goroutine 34 [running]:
2019-04-05T12:38:39.082Z [DEBUG] plugin.terraform-provider-aws_v2.5.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.providerConfigure(0xc000954770, 0x0, 0xc00063a6e0, 0xc000954770, 0x0)
2019-04-05T12:38:39.082Z [DEBUG] plugin.terraform-provider-aws_v2.5.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/provider.go:1010 +0xda9
2019-04-05T12:38:39.082Z [DEBUG] plugin.terraform-provider-aws_v2.5.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Configure(0xc0009544d0, 0xc00094b470, 0x7f249d3f6000, 0x0)
2019-04-05T12:38:39.082Z [DEBUG] plugin.terraform-provider-aws_v2.5.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:264 +0xcd
2019-04-05T12:38:39.082Z [DEBUG] plugin.terraform-provider-aws_v2.5.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Configure(0xc000129ee0, 0xc00094b470, 0xc000ae81f8, 0x0, 0x0)
2019-04-05T12:38:39.082Z [DEBUG] plugin.terraform-provider-aws_v2.5.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:517 +0x3e
2019-04-05T12:38:39.082Z [DEBUG] plugin.terraform-provider-aws_v2.5.0_x4: reflect.Value.call(0xc00011f1a0, 0xc000ae8008, 0x13, 0x3cd8565, 0x4, 0xc0009faf18, 0x3, 0x3, 0xc000127ac0, 0x413257, ...)
2019-04-05T12:38:39.082Z [DEBUG] plugin.terraform-provider-aws_v2.5.0_x4: 	/opt/goenv/versions/1.11.5/src/reflect/value.go:447 +0x454
2019-04-05T12:38:39.082Z [DEBUG] plugin.terraform-provider-aws_v2.5.0_x4: reflect.Value.Call(0xc00011f1a0, 0xc000ae8008, 0x13, 0xc00038d718, 0x3, 0x3, 0x12a05f200, 0xc00038d710, 0xc00038d7b8)
2019-04-05T12:38:39.082Z [DEBUG] plugin.terraform-provider-aws_v2.5.0_x4: 	/opt/goenv/versions/1.11.5/src/reflect/value.go:308 +0xa4
2019-04-05T12:38:39.082Z [DEBUG] plugin.terraform-provider-aws_v2.5.0_x4: net/rpc.(*service).call(0xc00007a0c0, 0xc000ab8000, 0xc00031c060, 0xc00031c070, 0xc00010a680, 0xc00063a020, 0x3a53d60, 0xc00094b470, 0x16, 0x2f40820, ...)
2019-04-05T12:38:39.082Z [DEBUG] plugin.terraform-provider-aws_v2.5.0_x4: 	/opt/goenv/versions/1.11.5/src/net/rpc/server.go:384 +0x14e
2019-04-05T12:38:39.082Z [DEBUG] plugin.terraform-provider-aws_v2.5.0_x4: created by net/rpc.(*Server).ServeCodec
2019-04-05T12:38:39.082Z [DEBUG] plugin.terraform-provider-aws_v2.5.0_x4: 	/opt/goenv/versions/1.11.5/src/net/rpc/server.go:481 +0x47e
```

### Expected Behavior

Table gets created as required (and as works fine in 2.4.0).

### Steps to Reproduce

1. `terraform apply -auto-approve`

### Important Factoids

Running this against the `amazon/dynamodb-local` container image in a network defined by Docker Compose.

### LINKED ISSUE #8265: version 2.5: unexpected EOF during plan in China region
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.10.8

### Affected Resource(s)

* aws_spot_fleet_request
* aws_security_group
* terraform plan

### Terraform Configuration Files

```hcl
provider "aws" {
  region              = "cn-north-1"
  profile             = "my-china-profile"
  allowed_account_ids = ["00000000"]

  #https://github.com/terraform-providers/terraform-provider-aws/issues/4690
  #https://github.com/terraform-providers/terraform-provider-aws/issues/4967

  # this is not picked up
  endpoints = {
    autoscaling = "https://autoscaling.cn-north-1.amazonaws.com.cn"
  }

  # so we need this for the hack in the etc hosts
  insecure = true
}
```

### Debug Output

https://gist.github.com/kdubmartins/772ec7ac1b87c74bebb645662371b51f

### Expected Behavior

A successful `terraform plan` output.

### Actual Behavior

```
Error: Error refreshing state: 2 error(s) occurred:

* module.nomad_sg.provider.aws: unexpected EOF
* module.nomad.provider.aws: unexpected EOF
```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

Adding a constraint to `version = "~> 2.4"` fixes the issue and the plan runs just fine.
Also, it does not happen in other AWS regions like eu-west-1 or us-east-1.

### PR DESCRIPTION
**Pull request by bflad**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Fixes #8214
Closes #8265

Output from acceptance testing before code change:

```
=== CONT  TestAccAWSProvider_Endpoints
panic: assignment to entry in nil map

goroutine 614 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.providerConfigure(0xc000c2fd50, 0x0, 0xc00098e300, 0xc000c2fd50, 0x0)
	/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/provider.go:1011 +0xde1
github.com/hashicorp/terraform/helper/schema.(*Provider).Configure(0xc000af7650, 0xc0006de000, 0xc, 0x653dec0)
	/Users/bflad/go/pkg/mod/github.com/hashicorp/terraform@v0.11.14-0.20190329073242-44702fa6c163/helper/schema/provider.go:264 +0xcd
github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).ConfigureProvider(0xc000a31860, 0xc00142c880, 0xc, 0xc0006de000, 0x0, 0x31)
	/Users/bflad/go/pkg/mod/github.com/hashicorp/terraform@v0.11.14-0.20190329073242-44702fa6c163/terraform/eval_context_builtin.go:136 +0x14a
github.com/hashicorp/terraform/terraform.(*EvalConfigProvider).Eval(0xc0009a4b40, 0x6543da0, 0xc000a31860, 0x2, 0x2, 0x59a0521, 0x4)
	/Users/bflad/go/pkg/mod/github.com/hashicorp/terraform@v0.11.14-0.20190329073242-44702fa6c163/terraform/eval_provider.go:48 +0x53
github.com/hashicorp/terraform/terraform.EvalRaw(0x645b160, 0xc0009a4b40, 0x6543da0, 0xc000a31860, 0xc000114000, 0x2, 0xc000660150, 0x2b)
	/Users/bflad/go/pkg/mod/github.com/hashicorp/terraform@v0.11.14-0.20190329073242-44702fa6c163/terraform/eval.go:53 +0x11a
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc0009a4b60, 0x6543da0, 0xc000a31860, 0x2, 0x2, 0x59a0521, 0x4)
	/Users/bflad/go/pkg/mod/github.com/hashicorp/terraform@v0.11.14-0.20190329073242-44702fa6c163/terraform/eval_sequence.go:14 +0x9c
github.com/hashicorp/terraform/terraform.EvalRaw(0x645b560, 0xc0009a4b60, 0x6543da0, 0xc000a31860, 0x2b, 0x0, 0x0, 0x2b)
	/Users/bflad/go/pkg/mod/github.com/hashicorp/terraform@v0.11.14-0.20190329073242-44702fa6c163/terraform/eval.go:53 +0x11a
github.com/hashicorp/terraform/terraform.(*EvalOpFilter).Eval(0xc00142f560, 0x6543da0, 0xc000a31860, 0x2, 0x2, 0x59a0521, 0x4)
	/Users/bflad/go/pkg/mod/github.com/hashicorp/terraform@v0.11.14-0.20190329073242-44702fa6c163/terraform/eval_filter_operation.go:37 +0x4c
github.com/hashicorp/terraform/terraform.EvalRaw(0x645b440, 0xc00142f560, 0x6543da0, 0xc000a31860, 0x0, 0x0, 0x0, 0x0)
	/Users/bflad/go/pkg/mod/github.com/hashicorp/terraform@v0.11.14-0.20190329073242-44702fa6c163/terraform/eval.go:53 +0x11a
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc0009a4b80, 0x6543da0, 0xc000a31860, 0x2, 0x2, 0x59a0521, 0x4)
	/Users/bflad/go/pkg/mod/github.com/hashicorp/terraform@v0.11.14-0.20190329073242-44702fa6c163/terraform/eval_sequence.go:14 +0x9c
github.com/hashicorp/terraform/terraform.EvalRaw(0x645b560, 0xc0009a4b80, 0x6543da0, 0xc000a31860, 0x50696e0, 0x9b05605, 0x4c8c7a0, 0xc00142b700)
	/Users/bflad/go/pkg/mod/github.com/hashicorp/terraform@v0.11.14-0.20190329073242-44702fa6c163/terraform/eval.go:53 +0x11a
github.com/hashicorp/terraform/terraform.Eval(0x645b560, 0xc0009a4b80, 0x6543da0, 0xc000a31860, 0xc0009a4b80, 0x645b560, 0xc0009a4b80, 0xc000075db0)
	/Users/bflad/go/pkg/mod/github.com/hashicorp/terraform@v0.11.14-0.20190329073242-44702fa6c163/terraform/eval.go:34 +0x4d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x571f240, 0xc00143e098, 0x0, 0x0)
	/Users/bflad/go/pkg/mod/github.com/hashicorp/terraform@v0.11.14-0.20190329073242-44702fa6c163/terraform/graph.go:126 +0xbc2
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc001431810, 0x571f240, 0xc00143e098, 0xc00063c180)
	/Users/bflad/go/pkg/mod/github.com/hashicorp/terraform@v0.11.14-0.20190329073242-44702fa6c163/dag/walk.go:387 +0x33b
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/Users/bflad/go/pkg/mod/github.com/hashicorp/terraform@v0.11.14-0.20190329073242-44702fa6c163/dag/walk.go:310 +0xa4f
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	3.940s
```

Output from acceptance testing after code change:

```
--- PASS: TestAccAWSProvider_Endpoints (1.68s)
```

### CODE REVIEW

**Comment by bflad** [comment]
The new acceptance testing here will now also check each AWS service client `Config.Endpoint` value to ensure it matches the test configuration.

File: aws/config.go [hunk 1]
```diff
@@ -354,7 +354,7 @@ func (c *Config) Client() (interface{}, error) {
 		codedeployconn:                      codedeploy.New(sess.Copy(&aws.Config{Endpoint: aws.String(c.Endpoints["codedeploy"])})),
 		codepipelineconn:                    codepipeline.New(sess.Copy(&aws.Config{Endpoint: aws.String(c.Endpoints["codepipeline"])})),
 		cognitoconn:                         cognitoidentity.New(sess.Copy(&aws.Config{Endpoint: aws.String(c.Endpoints["cognitoidentity"])})),
-		cognitoidpconn:                      cognitoidentityprovider.New(sess.Copy(&aws.Config{Endpoint: aws.String(c.Endpoints["cognitoidentityprovider"])})),
```
Comment (bflad) [inline aws/config.go]: This was a bug discovered by the new acceptance testing. 👍

File: aws/provider_test.go [hunk 2]
```diff
@@ -355,3 +357,212 @@ func testSweepSkipSweepError(err error) bool {
...
+					endpoint = "serverlessapplicationrepository"
+				case "servicecatalog":
+					endpoint = "sc"
+				case "servicediscovery":
+					endpoint = "sd"
+				case "stepfunctions":
+					endpoint = "sfn"
+				}
+
+				switch name {
```
Comment (nywilken) [inline aws/provider_test.go]: Thought about recommending an if statement here, but the multiple `||` is too much, and I don't feel strongly enough to say use a regex match :100:

**Comment by nywilken** [comment]
FWIW I tested against the reported issues and confirmed that the fix works as expected.

File: aws/provider_test.go [hunk 3]
```diff
@@ -355,3 +357,212 @@ func testSweepSkipSweepError(err error) bool {
...
+				Config: testAccAWSProviderConfigEndpoints(endpointsDeprecated.String()),
+				Check: resource.ComposeTestCheckFunc(
+					testAccCheckAWSProviderEndpointsDeprecated(&providers),
+				),
+			},
+		},
+	})
+}
+
+func testAccCheckAWSProviderEndpoints(providers *[]*schema.Provider) resource.TestCheckFunc {
```
[the remark this answers is not in the document]
Comment (bflad) [reply aws/provider_test.go]: Indeed it is a little bizarre! Dealing with pointers here so we can instantiate the slice during runtime. See also: `testAccCheckEbsSnapshotCopyExistsWithProviders`

File: aws/config.go (hunk 1 above)
Comment (nywilken) [reply aws/config.go]: :+1:

**Comment by bflad** [comment]
This has been released in [version 2.6.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#260-april-10-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
