### PR TITLE
r/aws_athena_database: validate athena db name with regex as per docs

### LINKED ISSUE #4128: Error Creating Athena Database
### Terraform Version
Terraform 0.11.3
aws 1.14.0

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_athena_database

### Terraform Configuration Files
```hcl
resource "aws_athena_database" "pccp_datalake" {
  name          = "PccpDevDatalake"
  bucket        = "${aws_s3_bucket.pccp_datalake.bucket}"
  force_destroy = true
}
```

### Debug Output
https://gist.github.com/andrewmichael/4d1b1e5bf035b1e35264cd81111723c0

### Expected Behavior
Athena database is created, and subsequent plan / apply commands operate correctly.

### Actual Behavior
Plan output:-
```
Terraform will perform the following actions:

  + aws_athena_database.pccp_datalake
      id:            <computed>
      bucket:        "pccp-dev-datalake"
      force_destroy: "true"
      name:          "PccpDevDatalake"


Plan: 1 to add, 0 to change, 0 to destroy.
```
Apply end in error:-
```
Error: Error applying plan:

1 error(s) occurred:

* aws_athena_database.pccp_datalake: 1 error(s) occurred:

* aws_athena_database.pccp_datalake: [ERROR] Athena not found database: PccpDevDatalake, query result: default
pccpdevdatalake
```
Subsequent plan / apply fails.
```
Error: Error refreshing state: 1 error(s) occurred:

* aws_athena_database.pccp_datalake: 1 error(s) occurred:

* aws_athena_database.pccp_datalake: aws_athena_database.pccp_datalake: [ERROR] Athena not found database: PccpDevDatalake, query result: default
pccpdevdatalake
```
Observing the AWS console the database appears to have been created.
The only way out of this now is to manually deleting the Athena database, then revert to the previous version of remote state in S3.

Just reverting remote state, results in the following error:-
```
Error: Error applying plan:

1 error(s) occurred:

* aws_athena_database.pccp_datalake: 1 error(s) occurred:

* aws_athena_database.pccp_datalake: reason: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. Database PccpDevDatalake already exists

```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
1. `terraform apply`

### Important Factoids
IAM user has admin permissions
remote state is persisted in s3

### PR DESCRIPTION
**Pull request by appilon**
Fix #4128 

Validate athena db name with regex as per docs (also wrap name in SQL syntax with `` to support leading underscore as per docs)

https://docs.aws.amazon.com/athena/latest/ug/tables-databases-columns-names.html

Also simplify config to 1 function

### CODE REVIEW

File: aws/resource_aws_athena_database_test.go [hunk 1]
```diff
@@ -81,7 +117,7 @@ func testAccCheckAWSAthenaDatabaseDestroy(s *terraform.State) error {
 		}
 
 		rInt := acctest.RandInt()
-		bucketName := fmt.Sprintf("tf-athena-db-%s-%d", rs.Primary.Attributes["name"], rInt)
```
Comment (appilon) [inline aws/resource_aws_athena_database_test.go]: In the case where I had an `_` in the db name, creating a bucket with that name in it caused an error, the random integer should be sufficient in ensuring a unique bucketName
