### PR TITLE
resource/aws_iam_group_policy: Properly handle generated policy name updates

### LINKED ISSUE #4377: aws_iam_group_policy updates without name field leave orphaned attached policies
### Terraform Version
Terraform v0.11.7
Provider aws 1.16.0

### Affected Resource(s)
- `aws_iam_group_policy`

Potentially also `aws_iam_role_policy` and `aws_iam_user_policy` as well, however I haven't tested yet.

### Terraform Configuration Files
```hcl
resource "aws_iam_group" "network_admins" {
  name = "NetworkAdministrators"
}

resource "aws_iam_group_policy" "network_admins" {
  group = "${aws_iam_group.network_admin.id}"
  policy = "${file("network-admins.policy.json")}"
}
```

### Expected Behavior
When a policy is updated, I expect that the policy attached to the group would be replaced.

### Actual Behavior
A new policy is attached to the group, and the old policy is left orphaned. The reason appears to be that it writes the policy with a newly generated `name`, rather than writing with the existing. Leaving `name` blank will generate i.e. `terraform-20180417120515577200000001`.

This is somewhat a security concern; if you are updating the policy to revoke permissions, since it will actually leave the old policy document attached, the group will still have the permissions you wanted to remove. You also don't have any visibility of this from Terraform.

You can get around the issue just by setting the `name` field. I have also noticed that removing `name` and running `terraform plan` shows no changes; even though I would expect it to want to replace the policy with a new computed name - this isn't really a concern though.

### Steps to Reproduce
1. Change the `policy` field - any change.
2. `terraform apply`

### PR DESCRIPTION
**Pull request by bflad**
Fixes #4377

After testing updates but before code changes:

```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSIAMGroupPolicy_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSIAMGroupPolicy_ -timeout 120m
=== RUN   TestAccAWSIAMGroupPolicy_basic
--- PASS: TestAccAWSIAMGroupPolicy_basic (123.65s)
=== RUN   TestAccAWSIAMGroupPolicy_namePrefix
--- FAIL: TestAccAWSIAMGroupPolicy_namePrefix (66.59s)
	testing.go:518: Step 1 error: Check failed: Check 2/2 error: IAM Group Policy name did not match
	testing.go:579: Error destroying resource! WARNING: Dangling resources
		may exist. The full state and error is shown below.

		Error: Error applying: 1 error(s) occurred:

		* aws_iam_group.test (destroy): 1 error(s) occurred:

		* aws_iam_group.test: Error deleting IAM Group test_group_6453479404941257412: DeleteConflict: Cannot delete entity, must delete policies first.
			status code: 409, request id: 4197118c-4a18-11e8-a475-37a7836ae511

		State: aws_iam_group.test:
		  ID = test_group_6453479404941257412
		  provider = provider.aws
		  arn = arn:aws:iam::187416307283:group/test_group_6453479404941257412
		  name = test_group_6453479404941257412
		  path = /
		  unique_id = AGPAIVYQCFZDGLRBR3NXS
=== RUN   TestAccAWSIAMGroupPolicy_generatedName
--- FAIL: TestAccAWSIAMGroupPolicy_generatedName (101.27s)
	testing.go:518: Step 1 error: Check failed: Check 2/2 error: IAM Group Policy name did not match
	testing.go:579: Error destroying resource! WARNING: Dangling resources
		may exist. The full state and error is shown below.

		Error: Error applying: 1 error(s) occurred:

		* aws_iam_group.test (destroy): 1 error(s) occurred:

		* aws_iam_group.test: Error deleting IAM Group test_group_4300747935912896569: DeleteConflict: Cannot delete entity, must delete policies first.
			status code: 409, request id: 7df6644f-4a18-11e8-bf04-d919114d6f8f

		State: aws_iam_group.test:
		  ID = test_group_4300747935912896569
		  provider = provider.aws
		  arn = arn:aws:iam::187416307283:group/test_group_4300747935912896569
		  name = test_group_4300747935912896569
		  path = /
		  unique_id = AGPAJN2FJ6BIMRBYTKK2E
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	291.541s
make: *** [testacc] Error 1
```

After code changes:

```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSIAMGroupPolicy_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSIAMGroupPolicy_ -timeout 120m
=== RUN   TestAccAWSIAMGroupPolicy_basic
--- PASS: TestAccAWSIAMGroupPolicy_basic (102.28s)
=== RUN   TestAccAWSIAMGroupPolicy_namePrefix
--- PASS: TestAccAWSIAMGroupPolicy_namePrefix (80.25s)
=== RUN   TestAccAWSIAMGroupPolicy_generatedName
--- PASS: TestAccAWSIAMGroupPolicy_generatedName (71.56s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	254.121s
```

### CODE REVIEW

**Comment by bflad** [comment]
IAM Role policy was fine, but added additional testing as well that passes:

```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSIAMRolePolicy_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSIAMRolePolicy_ -timeout 120m
=== RUN   TestAccAWSIAMRolePolicy_importBasic
--- PASS: TestAccAWSIAMRolePolicy_importBasic (11.28s)
=== RUN   TestAccAWSIAMRolePolicy_basic
--- PASS: TestAccAWSIAMRolePolicy_basic (26.58s)
=== RUN   TestAccAWSIAMRolePolicy_namePrefix
--- PASS: TestAccAWSIAMRolePolicy_namePrefix (17.46s)
=== RUN   TestAccAWSIAMRolePolicy_generatedName
--- PASS: TestAccAWSIAMRolePolicy_generatedName (15.94s)
=== RUN   TestAccAWSIAMRolePolicy_invalidJSON
--- PASS: TestAccAWSIAMRolePolicy_invalidJSON (0.91s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	72.204s
```

**Comment by bflad** [comment]
Updated to just the `d.Set()` required changes. (Sorry out of office today)

```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSIAMGroupPolicy_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSIAMGroupPolicy_ -timeout 120m
=== RUN   TestAccAWSIAMGroupPolicy_basic
--- PASS: TestAccAWSIAMGroupPolicy_basic (15.43s)
=== RUN   TestAccAWSIAMGroupPolicy_namePrefix
--- PASS: TestAccAWSIAMGroupPolicy_namePrefix (15.89s)
=== RUN   TestAccAWSIAMGroupPolicy_generatedName
--- PASS: TestAccAWSIAMGroupPolicy_generatedName (15.01s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	46.376s

 make testacc TEST=./aws TESTARGS='-run=TestAccAWSIAMRolePolicy_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSIAMRolePolicy_ -timeout 120m
=== RUN   TestAccAWSIAMRolePolicy_importBasic
--- PASS: TestAccAWSIAMRolePolicy_importBasic (12.33s)
=== RUN   TestAccAWSIAMRolePolicy_basic
--- PASS: TestAccAWSIAMRolePolicy_basic (21.37s)
=== RUN   TestAccAWSIAMRolePolicy_namePrefix
--- PASS: TestAccAWSIAMRolePolicy_namePrefix (20.19s)
=== RUN   TestAccAWSIAMRolePolicy_generatedName
--- PASS: TestAccAWSIAMRolePolicy_generatedName (16.81s)
=== RUN   TestAccAWSIAMRolePolicy_invalidJSON
--- PASS: TestAccAWSIAMRolePolicy_invalidJSON (0.96s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	71.704s
```

File: aws/resource_aws_iam_group_policy_test.go [hunk 1]
```diff
@@ -142,6 +174,28 @@ func testAccCheckIAMGroupPolicy(
...
+
+		return nil
+	}
+}
+
+func testAccCheckAWSIAMGroupPolicyNameMatches(i, j *iam.GetGroupPolicyOutput) resource.TestCheckFunc {
+	return func(s *terraform.State) error {
+		if aws.StringValue(i.PolicyName) != aws.StringValue(j.PolicyName) {
+			return errors.New("IAM Group Policy name did not match")
+		}
```
Comment (tombuildsstuff) [inline aws/resource_aws_iam_group_policy_test.go]: both of these ignore casings, but that's probably fine

Comment (bflad) [reply aws/resource_aws_iam_group_policy_test.go]: I'm pretty sure in terms of the acceptance testing we can allow it to be more strict, but if it presents some sort of problem we can certainly implement the `strings.ToLower()` calls 👍

**Comment by bflad** [comment]
This has been released in [version 1.17.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1170-may-02-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
