### PR TITLE
aws_kms_ciphertext into new resource keeping datasource

### LINKED ISSUE #960: aws_kms_ciphertext 'unstable' output
### Terraform Version
Terraform v0.9.8

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_kms_ciphertext

### Terraform Configuration Files
```hcl
data "aws_caller_identity" "current" {}

provider "aws" {
    region = "eu-west-1"
}

resource "aws_iam_role" "LambdaBackend_master_lambda" {
    name               = "LambdaBackend_master_lambda"
    path               = "/"
    assume_role_policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
POLICY
}

resource "aws_iam_role_policy_attachment" "LambdaBackend_master_lambda_AmazonS3ReadOnlyAccess" {
    role       = "${aws_iam_role.LambdaBackend_master_lambda.name}"
    policy_arn = "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
}

resource "aws_iam_role_policy_attachment" "LambdaBackend_master_lambda_AmazonDynamoDBFullAccess" {
    role       = "${aws_iam_role.LambdaBackend_master_lambda.name}"
    policy_arn = "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"
}

resource "aws_iam_role_policy_attachment" "LambdaBackend_master_lambda_CloudWatchFullAccess" {
    role       = "${aws_iam_role.LambdaBackend_master_lambda.name}"
    policy_arn = "arn:aws:iam::aws:policy/CloudWatchFullAccess"
}

resource "aws_lambda_function" "LambdaBackend_lambda" {
  filename         = "email_lambda.zip"
  function_name    = "SpikeLambda"
  role             = "${aws_iam_role.LambdaBackend_master_lambda.arn}"
  handler          = "index.handler"
  source_code_hash = "${base64sha256(file("email_lambda.zip"))}"
  runtime          = "nodejs6.10"
  timeout          = 15
  publish          = true

  environment {
    variables = {
      apikey = "${data.aws_kms_ciphertext.apikey.ciphertext_blob}"
    }
  }
}

resource "aws_kms_key" "config" {
  description = "env config"
  is_enabled = true
  policy                  = <<POLICY
{
  "Version" : "2012-10-17",
  "Id" : "key-consolepolicy-3",
  "Statement" : [ {
    "Sid" : "Enable IAM User Permissions",
    "Effect" : "Allow",
    "Principal" : {
      "AWS" : "arn:aws:iam::${data.aws_caller_identity.current.account_id}:root"
    },
    "Action" : "kms:*",
    "Resource" : "*"
  }, {
    "Sid" : "Allow use of the key",
    "Effect" : "Allow",
    "Principal" : {
      "AWS" : "${aws_iam_role.LambdaBackend_master_lambda.arn}"
    },
    "Action" : [ "kms:Encrypt", "kms:Decrypt", "kms:ReEncrypt*", "kms:GenerateDataKey*", "kms:DescribeKey" ],
    "Resource" : "*"
  }, {
    "Sid" : "Allow attachment of persistent resources",
    "Effect" : "Allow",
    "Principal" : {
      "AWS" : "${aws_iam_role.LambdaBackend_master_lambda.arn}"
    },
    "Action" : [ "kms:CreateGrant", "kms:ListGrants", "kms:RevokeGrant" ],
    "Resource" : "*",
    "Condition" : {
      "Bool" : {
        "kms:GrantIsForAWSResource" : "true"
      }
    }
  } ]
}
POLICY
}

data "aws_kms_ciphertext" "apikey" {
  key_id = "${aws_kms_key.config.key_id}"
  plaintext = "hunter2"
}
```

### Debug Output
Run 1: https://gist.github.com/OliverCole/5feb1409f098a5ad5de523ed907cf93a
Run 2: https://gist.github.com/OliverCole/74ee789489a4582b6548a24cb180c07e

### Expected/Desired Behavior
Ciphertext data source should be static, resulting in no changes to downstream dependencies.

### Actual Behavior
```
λ terraform plan

...

~ aws_lambda_function.LambdaBackend_lambda
    environment.0.variables.apikey: "AQICAHhrx94Wb5zY2paCTEFBiotjAnNA5JkowPRTlnNgFDShRwEwemJy4XaanTNiJw/c4f5nAAAAazBpBgkqhkiG9w0BBwagXDBaAgEAMFUGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMNrQujwxAygW7NzoxAgEQgCjhQxFc+GZco8upPiXoqg7tBbyI+UmQvTX7Rk4Zrx+7mwGpcH0S8tlM" => "AQICAHhrx94Wb5zY2paCTEFBiotjAnNA5JkowPRTlnNgFDShRwGg+4IumuMxfn0LhPLisPCNAAAAZTBjBgkqhkiG9w0BBwagVjBUAgEAME8GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMCWnWVlL7BZdI9/QcAgEQgCIJrOrW56mdVTpYGt6k/rhqvgF+0EMx2gwxx5JB1dzsegQ/"


Plan: 0 to add, 1 to change, 0 to destroy.

λ terraform plan

...

~ aws_lambda_function.LambdaBackend_lambda
    environment.0.variables.apikey: "AQICAHhrx94Wb5zY2paCTEFBiotjAnNA5JkowPRTlnNgFDShRwEwemJy4XaanTNiJw/c4f5nAAAAazBpBgkqhkiG9w0BBwagXDBaAgEAMFUGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMNrQujwxAygW7NzoxAgEQgCjhQxFc+GZco8upPiXoqg7tBbyI+UmQvTX7Rk4Zrx+7mwGpcH0S8tlM" => "AQICAHhrx94Wb5zY2paCTEFBiotjAnNA5JkowPRTlnNgFDShRwEsP80A7AA1DNwPeQjBwUQfAAAAZTBjBgkqhkiG9w0BBwagVjBUAgEAME8GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM8S3Dt92qSVRXrEeAAgEQgCLiwJB1lND0Md3fKEr23kBmTj3rRkXUg/EcbXY191xLwsY5"


Plan: 0 to add, 1 to change, 0 to destroy.
```

Calls to `data.aws_kms_ciphertext.apikey.ciphertext_blob` in `terraform console` are stable and match the `...0S8tlM` value above.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### References
@apparentlymart - https://groups.google.com/forum/#!topic/terraform-tool/7K4dLBmMrik

### PR DESCRIPTION
**Pull request by cperilla-rival**
Fixes #960

As a resource, the encryption is performed on create only.

Changing any of the input forces a new resource.

Rework of PR#2568

### CODE REVIEW

File: aws/resource_aws_kms_ciphertext.go [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+
+func resourceAwsKmsCiphertext() *schema.Resource {
+
+	return &schema.Resource{
+		Create: resourceAwsKmsCiphertextCreate,
+		Read:   resourceAwsKmsCiphertextRead,
+		Delete: resourceAwsKmsCiphertextDelete,
+
+		Schema: map[string]*schema.Schema{
+			"plaintext": {
```
Comment (gazoakley) [inline aws/resource_aws_kms_ciphertext.go]: It might be worth specifying `Sensitive: true,` here: https://github.com/hashicorp/terraform/blob/86e6481cc661b2ba694d353aab6d11838c066c7c/helper/schema/schema.go#L200

File: website/docs/r/kms_ciphertext.html.markdown [hunk 2]
```diff
@@ -0,0 +1,49 @@
+---
+layout: "aws"
+page_title: "AWS: aws_kms_ciphertext"
+sidebar_current: "docs-aws-resource-kms-ciphertext"
+description: |-
+    Provides ciphertext encrypted using a KMS key
+---
+
+# Data Source: aws_kms_ciphertext
```
Comment (gazoakley) [inline website/docs/r/kms_ciphertext.html.markdown]: This isn't a data source 😄.

File: aws/resource_aws_kms_ciphertext.go (hunk 1 above)
Comment (cperilla-rival) [reply aws/resource_aws_kms_ciphertext.go]: Good, thanks fixing.

File: website/docs/r/kms_ciphertext.html.markdown (hunk 2 above)
Comment (cperilla-rival) [reply website/docs/r/kms_ciphertext.html.markdown]: Good catch, thank you for your review.

**Comment by jbergknoff-rival** [comment]
@gazoakley would you please re-review when you have a chance?

File: aws/resource_aws_kms_ciphertext.go [hunk 3]
```diff
@@ -0,0 +1,86 @@
...
+	"github.com/aws/aws-sdk-go/aws"
+	"github.com/aws/aws-sdk-go/service/kms"
+	"github.com/hashicorp/terraform/helper/schema"
+)
+
+func resourceAwsKmsCiphertext() *schema.Resource {
+
+	return &schema.Resource{
+		Create: resourceAwsKmsCiphertextCreate,
+		Read:   resourceAwsKmsCiphertextRead,
```
Comment (bflad) [inline aws/resource_aws_kms_ciphertext.go]: Nit: I believe we can replace the empty custom functions with `schema.Noop` 👍

File: aws/resource_aws_kms_ciphertext_test.go [hunk 4]
```diff
@@ -0,0 +1,136 @@
...
+					resource.TestCheckResourceAttr(
+						"aws_kms_secret.foo", "plaintext", "Super secret data"),
+				),
+			},
+		},
+	})
+}
+
+const testAccResourceAwsKmsCiphertextConfig_basic = `
+provider "aws" {
```
Comment (bflad) [inline aws/resource_aws_kms_ciphertext_test.go]: Nit: Including the `provider` configurations for most acceptance testing is extraneous

File: website/docs/r/kms_ciphertext.html.markdown [hunk 5]
```diff
@@ -0,0 +1,49 @@
...
+layout: "aws"
+page_title: "AWS: aws_kms_ciphertext"
+sidebar_current: "docs-aws-resource-kms-ciphertext"
+description: |-
+    Provides ciphertext encrypted using a KMS key
+---
+
+# Resource: aws_kms_ciphertext
+
+The KMS ciphertext resource allows you to encrypt plaintext into ciphertext
```
Comment (bflad) [inline website/docs/r/kms_ciphertext.html.markdown]: Nit: We should include a cross referencing link to the `aws_kms_ciphertext` data source and explain the difference between the two.

File: aws/resource_aws_kms_ciphertext_test.go [hunk 6]
```diff
@@ -0,0 +1,136 @@
...
+  region = "us-west-2"
+}
+
+resource "aws_kms_key" "foo" {
+  description = "tf-test-acc-data-source-aws-kms-ciphertext-basic"
+  is_enabled = true
+}
+
+data "aws_kms_ciphertext" "foo" {
```
Comment (bflad) [inline aws/resource_aws_kms_ciphertext_test.go]: These test configurations should reference the `resource` not `data` source.

**Comment by bflad** [comment]
This has been released in [version 2.4.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#240-march-29-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
