### PR TITLE
Fixes #8173

### LINKED ISSUE #8173: resource/aws_glue_catalog_table: Prevent EntityNotFoundException when deleted outside of terraform
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.11.13
+ provider.aws v2.4.0
```

### Affected Resource(s)

* aws_glue_catalog_table

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "us-west-2"
}

resource "aws_glue_catalog_database" "aws_glue_catalog_database" {
  name = "tvendettamycatalogdatabase"
}

resource "aws_glue_catalog_table" "aws_glue_catalog_table" {
  name          = "mycatalogtable"
  database_name = "tvendettamycatalogdatabase"
}
```

### Output

https://gist.github.com/thomasv314/9f2f61f1b741511f5101eaef7153f0f6

### Expected Behavior

Terraform should recreate a manually deleted aws_glue_catalog table

### Actual Behavior

Terraform throws an EntityNotFound exception

### Steps to Reproduce

1. `terraform apply`
2. Delete the AWS Glue Catalog Table manually in the console
3. `terraform plan`

### References

* #5136

### PR DESCRIPTION
**Pull request by thomasv314**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Fixes #8173 

Changes proposed in this pull request:

* Recreate an aws_glue_catalog_table if it's been deleted manually outside of Terraform

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSGlueCatalogTable_recreates'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSGlueCatalogTable_recreates -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSGlueCatalogTable_recreates
--- PASS: TestAccAWSGlueCatalogTable_recreates (29.02s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       29.063s

```

### CODE REVIEW

File: aws/resource_aws_glue_catalog_table.go [hunk 1]
```diff
@@ -16,6 +16,7 @@ func resourceAwsGlueCatalogTable() *schema.Resource {
 		Read:   resourceAwsGlueCatalogTableRead,
 		Update: resourceAwsGlueCatalogTableUpdate,
 		Delete: resourceAwsGlueCatalogTableDelete,
+		Exists: resourceAwsGlueCatalogTableExists,
```
Comment (bflad) [inline aws/resource_aws_glue_catalog_table.go]: Sorry this might not be clear since we have a few resources that implement it, but we are preferring to skip implementing the `Exists` function in this provider. Could you remove this? It usually introduces unnecessary logic duplication as the beginning of each resource `Read` function should handle the "existence" testing logic and triggering recreation via the `d.SetId("")` and `return nil` pattern. Thanks!

File: aws/resource_aws_glue_catalog_table.go [hunk 2]
```diff
@@ -265,6 +266,7 @@ func resourceAwsGlueCatalogTableRead(d *schema.ResourceData, meta interface{}) e
 		if isAWSErr(err, glue.ErrCodeEntityNotFoundException, "") {
 			log.Printf("[WARN] Glue Catalog Table (%s) not found, removing from state", d.Id())
 			d.SetId("")
+			return nil
```
Comment (bflad) [inline aws/resource_aws_glue_catalog_table.go]: 💯 this should be the only fix required here.

File: aws/resource_aws_glue_catalog_table_test.go [hunk 3]
```diff
@@ -12,6 +12,41 @@ import (
 	"github.com/hashicorp/terraform/terraform"
 )
 
+func TestAccAWSGlueCatalogTable_recreates(t *testing.T) {
+	resourceName := "aws_glue_catalog_table.test"
+	rInt := acctest.RandInt()
+
+	resource.Test(t, resource.TestCase{
```
Comment (bflad) [inline aws/resource_aws_glue_catalog_table_test.go]: We prefer to use the [`resource.ParallelTest()`](https://godoc.org/github.com/hashicorp/terraform/helper/resource#ParallelTest) function in this provider. 👍 

```suggestion
	resource.ParallelTest(t, resource.TestCase{
```

**Comment by bflad** [comment]
This has been released in [version 2.6.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#260-april-10-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
