### PR TITLE
Intermittent error when updating Capacity Providers on ECS Cluster

### LINKED ISSUE #11285: Intermittent error when updating Capacity Providers on ECS Cluster
There is an intermittent failure when updating the capacity providers on an ECS cluster when the cluster status is not `ACTIVE`.

This was first seen during acceptance testing of the feature.

```
--- FAIL: TestAccAWSEcsCluster_CapacityProvidersUpdate (26.05s)
    testing.go:635: Step 2 error: errors during apply:
        
        Error: error changing ECS cluster capacity provider settings (arn:aws:ecs:us-west-2:*******:cluster/tf-acc-test-1227245030962262513): ClientException: Cluster was not ACTIVE.
        	status code: 400, request id: b6cf25c3-7d49-4fad-876d-387b2c2a688b
```

The provider should both:
* wait for the cluster to be in `ACTIVE` state on creation and update
* retry the above exception when updating

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `aws_ecs_cluster`

### References

* #11151

### PR DESCRIPTION
**Pull request by gdavison**
Fixes an intermittent failure when updating the capacity providers on an ECS cluster when the cluster status is not `ACTIVE`.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #11285 

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_ecs_cluster: fixes intermittent failures on update when cluster dependencies are updating.
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSEcsCluster_'

--- PASS: TestAccAWSEcsCluster_disappears (14.50s)
--- PASS: TestAccAWSEcsCluster_basic (18.39s)
--- PASS: TestAccAWSEcsCluster_containerInsights (39.06s)
--- PASS: TestAccAWSEcsCluster_Tags (40.84s)
--- PASS: TestAccAWSEcsCluster_CapacityProviders (47.33s)
--- PASS: TestAccAWSEcsCluster_CapacityProvidersUpdate (51.29s)
--- PASS: TestAccAWSEcsCluster_SingleCapacityProvider (86.14s)
```

### CODE REVIEW

File: aws/resource_aws_ecs_cluster.go [hunk 1]
```diff
@@ -14,6 +14,12 @@ import (
 	"github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags"
 )
 
+const (
+	timeoutCreate = 10 * time.Minute
+	timeoutDelete = 10 * time.Minute
+	timeoutUpdate = 10 * time.Minute
```
Comment (bflad) [inline aws/resource_aws_ecs_cluster.go]: Nit: These are global constants across all resources and should likely be more explicitly named:

```go
	ecsClusterTimeoutCreate = 10 * time.Minute
	ecsClusterTimeoutDelete = 10 * time.Minute
	ecsClusterTimeoutUpdate = 10 * time.Minute
```
