### PR TITLE
Only set associate_public_ip_address if it's explicitly set

### LINKED ISSUE #6777: aws_launch_template network interfaces associate_public_ip_address default should not be set
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.10
+ provider.aws v1.51.0

### Affected Resource(s)

* aws_launch_template

### Terraform Configuration Files

```hcl
variable "sandbox_id" {}
variable "owner" {}
variable "key_name" {}

provider "aws" {
  region = "eu-west-1"
}

data "aws_availability_zones" "available" {}

locals {
  timestamp =  "${timestamp()}"  
}

resource "aws_vpc" "vpc" {
  cidr_block = "10.0.0.0/16"
  tags = {
    Name = "${var.sandbox_id}-vpc"
    Owner = "${var.owner}"
  }
}

resource "aws_subnet" "public-subnet1" {
  vpc_id = "${aws_vpc.vpc.id}"
  cidr_block = "10.0.0.0/24"
  map_public_ip_on_launch = true
  availability_zone = "${data.aws_availability_zones.available.names[0]}"
  tags = {
    Name = "${var.sandbox_id}-public-subnet1"
    Owner = "${var.owner}"
  }
}

resource "aws_subnet" "public-subnet2" {
  vpc_id = "${aws_vpc.vpc.id}"
  cidr_block = "10.0.1.0/24"
  map_public_ip_on_launch = true
  availability_zone = "${data.aws_availability_zones.available.names[1]}"
  tags = {
    Name = "${var.sandbox_id}-public-subnet2"
    Owner = "${var.owner}"
  }
}

resource "aws_internet_gateway" "igw" {
  vpc_id = "${aws_vpc.vpc.id}"
  tags = {
    Name = "${var.sandbox_id}-public-igw"
    Owner = "${var.owner}"
  }
}

resource "aws_route_table" "route_table" {
  vpc_id = "${aws_vpc.vpc.id}"
  route = {
    gateway_id = "${aws_internet_gateway.igw.id}"
    cidr_block = "0.0.0.0/0"
  }
  tags = {
    Name = "${var.sandbox_id}-rt"
    Owner = "${var.owner}"
  }
}

resource "aws_route_table_association" "rta_subnet1" {
  route_table_id = "${aws_route_table.route_table.id}"
  subnet_id = "${aws_subnet.public-subnet1.id}"
}

resource "aws_route_table_association" "rta_subnet2" {
  route_table_id = "${aws_route_table.route_table.id}"
  subnet_id = "${aws_subnet.public-subnet2.id}"
}

resource "aws_security_group" "sg_ssh" {
  name = "ssh_sg"
  description = "Enable SSH access via port 22"
  vpc_id = "${aws_vpc.vpc.id}"

  ingress {
    protocol = "tcp"
    from_port = 22
    to_port = 22
    cidr_blocks = ["0.0.0.0/0"]
  }
  egress {
    protocol = "-1"
    from_port = 0
    to_port = 0
    cidr_blocks = ["0.0.0.0/0"]
  }
  tags = {
    Name = "${var.sandbox_id}-ssh-sg"
    Owner = "${var.owner}"
  }
}

resource "aws_network_interface" "nic" {
  subnet_id = "${aws_subnet.public-subnet1.id}"
  security_groups = ["${aws_security_group.sg_ssh.id}"]
}

resource "aws_eip" "eip" {
  vpc = true
  network_interface = "${aws_network_interface.nic.id}"
}

resource "aws_launch_template" "launch_template" {
  name     = "${var.sandbox_id}-lt"
  key_name = "${var.key_name}"
  image_id = "ami-0773391ae604c49a4"
  
  instance_market_options {
    spot_options {
      spot_instance_type = "persistent"
    }
    market_type="spot"
  }
  
  network_interfaces {
    device_index = 0
    network_interface_id = "${aws_network_interface.nic.id}"
  }
  network_interfaces {
    device_index = 1
    subnet_id = "${aws_subnet.public-subnet1.id}"
  }
  
  # user_data = "${base64encode()}"
  
  tag_specifications {
    resource_type = "instance"
    tags {
      Name = "${var.sandbox_id}-instance"
      Owner = "${var.owner}"
    }
  }
}

resource "aws_ec2_fleet" "fleet" {
  launch_template_config {
    launch_template_specification {
      launch_template_id = "${aws_launch_template.launch_template.id}"
      version            = "${aws_launch_template.launch_template.latest_version}"
    }
    # allow to choose from several instance types if there is no spot capacity for some type
    override {
      instance_type = "t2.micro"
    }
    override {
      instance_type = "t3.micro"
    }
    override {
      instance_type = "t3.small"
    }
  }

  target_capacity_specification {
    default_target_capacity_type = "spot"
    total_target_capacity = 1
  }
}

output "instance_public_ip" {
  value = "${aws_eip.eip.public_ip}"
}

output "describe_fleet_history" {
  value = "aws ec2 describe-fleet-history --fleet-id ${aws_ec2_fleet.fleet.id} --start-time "
}
```

### Debug Output

https://gist.github.com/stanb/d2a7bf361727b224d9be497554b576b7#file-debug-log
### Expected Behavior

Launch template created with two network interfaces definitions: 
device 0 - attached to predefined network interface;
device 1 - attached to subnet
Both network interfaces **should not** have Auto-assign public IP set at all.
When EC2 fleet created it should succeed to launch instance from this launch template.

### Actual Behavior

Launch template created with two network interfaces but device 1 nic have Auto-assign public IP set to false.
When EC2 spot fleet starts it fails to launch instance with following error:
The associatePublicIPAddress parameter cannot be specified when launching with multiple network interfaces

### Steps to Reproduce

1. `terraform apply -var "sandbox_id=test1" -var "owner=<_owner_>" -var "key_name=<_key-name_>"`
key-name is a name of key-pair, the pem file located at ~/.aws/ direcory

2. copy and run describe_fleet_history output   
for example:
`aws ec2 describe-fleet-history --fleet-id fleet-ed51ab81-feea-42f5-a322-0697c461ca35 --start-time 2018-12-08T10:58:27.000Z`

### References

* It behaves same with aws cloudformation  
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-networkinterface.html#cfn-ec2-launchtemplate-networkinterface-associatepublicipaddress
You should not specify AssociatePublicIpAddress in definition of network interface for launch template with several network interfaces. Otherwise the fleet will fail to launch instances with same error: The associatePublicIPAddress parameter cannot be specified when launching with multiple network interfaces.

### PR DESCRIPTION
**Pull request by ryndaniels**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #6777 

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
BUG FIXES:
* resource/aws_launch_template: Only set associate_public_ip_address on network interfaces if it's explicitly set to avoid problems with multiple network interfaces
```

Output from acceptance testing:

```
Test to catch this problem - commented out because of problems with TF destroy when it passes

$ make testacc TESTARGS="-run=TestAccAWSEc2Fleet_TemplateMultipleNetworkInterfaces"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSEc2Fleet_TemplateMultipleNetworkInterfaces -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSEc2Fleet_TemplateMultipleNetworkInterfaces
=== PAUSE TestAccAWSEc2Fleet_TemplateMultipleNetworkInterfaces
=== CONT  TestAccAWSEc2Fleet_TemplateMultipleNetworkInterfaces
fleet id: fleet-b7d98d6c-bc90-4ef2-b246-70449d1a395b
--- FAIL: TestAccAWSEc2Fleet_TemplateMultipleNetworkInterfaces (203.10s)
    testing.go:569: Step 0 error: Check failed: Check 3/3 error: Error The associatePublicIPAddress parameter cannot be specified when launching with multiple network interfaces found in fleet history event
FAIL
FAIL    github.com/terraform-providers/terraform-provider-aws/aws       204.383s
make: *** [testacc] Error 1

All other tests with the new code:

make testacc TESTARGS="-run=TestAccAWSEc2Fleet_"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSEc2Fleet_ -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSEc2Fleet_basic
=== PAUSE TestAccAWSEc2Fleet_basic
=== RUN   TestAccAWSEc2Fleet_disappears
=== PAUSE TestAccAWSEc2Fleet_disappears
=== RUN   TestAccAWSEc2Fleet_ExcessCapacityTerminationPolicy
=== PAUSE TestAccAWSEc2Fleet_ExcessCapacityTerminationPolicy
=== RUN   TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_LaunchTemplateId
=== PAUSE TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_LaunchTemplateId
=== RUN   TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_LaunchTemplateName
=== PAUSE TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_LaunchTemplateName
=== RUN   TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_Version
=== PAUSE TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_Version
=== RUN   TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_AvailabilityZone
=== PAUSE TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_AvailabilityZone
=== RUN   TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_InstanceType
=== PAUSE TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_InstanceType
=== RUN   TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_MaxPrice
--- SKIP: TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_MaxPrice (0.00s)
    resource_aws_ec2_fleet_test.go:337: EC2 API is not correctly returning MaxPrice override
=== RUN   TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_Priority
=== PAUSE TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_Priority
=== RUN   TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_Priority_Multiple
=== PAUSE TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_Priority_Multiple
=== RUN   TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_SubnetId
=== PAUSE TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_SubnetId
=== RUN   TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_WeightedCapacity
=== PAUSE TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_WeightedCapacity
=== RUN   TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_WeightedCapacity_Multiple
=== PAUSE TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_WeightedCapacity_Multiple
=== RUN   TestAccAWSEc2Fleet_OnDemandOptions_AllocationStrategy
=== PAUSE TestAccAWSEc2Fleet_OnDemandOptions_AllocationStrategy
=== RUN   TestAccAWSEc2Fleet_ReplaceUnhealthyInstances
=== PAUSE TestAccAWSEc2Fleet_ReplaceUnhealthyInstances
=== RUN   TestAccAWSEc2Fleet_SpotOptions_AllocationStrategy
=== PAUSE TestAccAWSEc2Fleet_SpotOptions_AllocationStrategy
=== RUN   TestAccAWSEc2Fleet_SpotOptions_InstanceInterruptionBehavior
=== PAUSE TestAccAWSEc2Fleet_SpotOptions_InstanceInterruptionBehavior
=== RUN   TestAccAWSEc2Fleet_SpotOptions_InstancePoolsToUseCount
=== PAUSE TestAccAWSEc2Fleet_SpotOptions_InstancePoolsToUseCount
=== RUN   TestAccAWSEc2Fleet_Tags
=== PAUSE TestAccAWSEc2Fleet_Tags
=== RUN   TestAccAWSEc2Fleet_TargetCapacitySpecification_DefaultTargetCapacityType
=== PAUSE TestAccAWSEc2Fleet_TargetCapacitySpecification_DefaultTargetCapacityType
=== RUN   TestAccAWSEc2Fleet_TargetCapacitySpecification_DefaultTargetCapacityType_OnDemand
=== PAUSE TestAccAWSEc2Fleet_TargetCapacitySpecification_DefaultTargetCapacityType_OnDemand
=== RUN   TestAccAWSEc2Fleet_TargetCapacitySpecification_DefaultTargetCapacityType_Spot
=== PAUSE TestAccAWSEc2Fleet_TargetCapacitySpecification_DefaultTargetCapacityType_Spot
=== RUN   TestAccAWSEc2Fleet_TargetCapacitySpecification_TotalTargetCapacity
=== PAUSE TestAccAWSEc2Fleet_TargetCapacitySpecification_TotalTargetCapacity
=== RUN   TestAccAWSEc2Fleet_TerminateInstancesWithExpiration
=== PAUSE TestAccAWSEc2Fleet_TerminateInstancesWithExpiration
=== RUN   TestAccAWSEc2Fleet_Type
=== PAUSE TestAccAWSEc2Fleet_Type
=== CONT  TestAccAWSEc2Fleet_basic
=== CONT  TestAccAWSEc2Fleet_OnDemandOptions_AllocationStrategy
=== CONT  TestAccAWSEc2Fleet_TargetCapacitySpecification_DefaultTargetCapacityType
=== CONT  TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_WeightedCapacity_Multiple
=== CONT  TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_WeightedCapacity
=== CONT  TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_SubnetId
=== CONT  TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_Priority_Multiple
=== CONT  TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_Priority
=== CONT  TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_InstanceType
=== CONT  TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_AvailabilityZone
=== CONT  TestAccAWSEc2Fleet_TargetCapacitySpecification_DefaultTargetCapacityType_OnDemand
=== CONT  TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_Version
=== CONT  TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_LaunchTemplateName
=== CONT  TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_LaunchTemplateId
=== CONT  TestAccAWSEc2Fleet_ExcessCapacityTerminationPolicy
=== CONT  TestAccAWSEc2Fleet_Type
=== CONT  TestAccAWSEc2Fleet_TerminateInstancesWithExpiration
=== CONT  TestAccAWSEc2Fleet_TargetCapacitySpecification_TotalTargetCapacity
=== CONT  TestAccAWSEc2Fleet_disappears
=== CONT  TestAccAWSEc2Fleet_TargetCapacitySpecification_DefaultTargetCapacityType_Spot
--- PASS: TestAccAWSEc2Fleet_disappears (52.44s)
=== CONT  TestAccAWSEc2Fleet_SpotOptions_AllocationStrategy
--- PASS: TestAccAWSEc2Fleet_Type (52.68s)
=== CONT  TestAccAWSEc2Fleet_Tags
--- PASS: TestAccAWSEc2Fleet_TargetCapacitySpecification_DefaultTargetCapacityType_OnDemand (53.23s)
=== CONT  TestAccAWSEc2Fleet_ReplaceUnhealthyInstances
--- PASS: TestAccAWSEc2Fleet_basic (53.27s)
=== CONT  TestAccAWSEc2Fleet_SpotOptions_InstancePoolsToUseCount
--- PASS: TestAccAWSEc2Fleet_TargetCapacitySpecification_DefaultTargetCapacityType_Spot (53.37s)
=== CONT  TestAccAWSEc2Fleet_SpotOptions_InstanceInterruptionBehavior
--- PASS: TestAccAWSEc2Fleet_TargetCapacitySpecification_DefaultTargetCapacityType (92.85s)
--- PASS: TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_InstanceType (94.09s)
--- PASS: TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_LaunchTemplateName (94.43s)
--- PASS: TestAccAWSEc2Fleet_TerminateInstancesWithExpiration (94.54s)
--- PASS: TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_Priority_Multiple (94.68s)
--- PASS: TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_LaunchTemplateId (95.14s)
--- PASS: TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_WeightedCapacity (95.57s)
--- PASS: TestAccAWSEc2Fleet_OnDemandOptions_AllocationStrategy (95.57s)
--- PASS: TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_WeightedCapacity_Multiple (95.58s)
--- PASS: TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_AvailabilityZone (95.63s)
--- PASS: TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_Priority (96.97s)
--- PASS: TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_Version (97.10s)
--- PASS: TestAccAWSEc2Fleet_ExcessCapacityTerminationPolicy (124.79s)
--- PASS: TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_SubnetId (130.06s)
--- PASS: TestAccAWSEc2Fleet_Tags (93.38s)
--- PASS: TestAccAWSEc2Fleet_SpotOptions_AllocationStrategy (94.62s)
--- PASS: TestAccAWSEc2Fleet_SpotOptions_InstancePoolsToUseCount (93.88s)
--- PASS: TestAccAWSEc2Fleet_SpotOptions_InstanceInterruptionBehavior (93.79s)
--- PASS: TestAccAWSEc2Fleet_ReplaceUnhealthyInstances (94.10s)
--- PASS: TestAccAWSEc2Fleet_TargetCapacitySpecification_TotalTargetCapacity (497.61s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       499.024s

make testacc TESTARGS="-run=TestAccAWSLaunchTemplate_"   ==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSLaunchTemplate_ -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSLaunchTemplate_importBasic
=== PAUSE TestAccAWSLaunchTemplate_importBasic
=== RUN   TestAccAWSLaunchTemplate_importData
=== PAUSE TestAccAWSLaunchTemplate_importData
=== RUN   TestAccAWSLaunchTemplate_basic
=== PAUSE TestAccAWSLaunchTemplate_basic
=== RUN   TestAccAWSLaunchTemplate_disappears
=== PAUSE TestAccAWSLaunchTemplate_disappears
=== RUN   TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS
=== PAUSE TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS
=== RUN   TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS_DeleteOnTermination
=== PAUSE TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS_DeleteOnTermination
=== RUN   TestAccAWSLaunchTemplate_EbsOptimized
=== PAUSE TestAccAWSLaunchTemplate_EbsOptimized
=== RUN   TestAccAWSLaunchTemplate_ElasticInferenceAccelerator
=== PAUSE TestAccAWSLaunchTemplate_ElasticInferenceAccelerator
=== RUN   TestAccAWSLaunchTemplate_data
=== PAUSE TestAccAWSLaunchTemplate_data
=== RUN   TestAccAWSLaunchTemplate_description
=== PAUSE TestAccAWSLaunchTemplate_description
=== RUN   TestAccAWSLaunchTemplate_update
=== PAUSE TestAccAWSLaunchTemplate_update
=== RUN   TestAccAWSLaunchTemplate_tags
=== PAUSE TestAccAWSLaunchTemplate_tags
=== RUN   TestAccAWSLaunchTemplate_capacityReservation_preference
=== PAUSE TestAccAWSLaunchTemplate_capacityReservation_preference
=== RUN   TestAccAWSLaunchTemplate_capacityReservation_target
=== PAUSE TestAccAWSLaunchTemplate_capacityReservation_target
=== RUN   TestAccAWSLaunchTemplate_creditSpecification_nonBurstable
=== PAUSE TestAccAWSLaunchTemplate_creditSpecification_nonBurstable
=== RUN   TestAccAWSLaunchTemplate_creditSpecification_t2
=== PAUSE TestAccAWSLaunchTemplate_creditSpecification_t2
=== RUN   TestAccAWSLaunchTemplate_creditSpecification_t3
=== PAUSE TestAccAWSLaunchTemplate_creditSpecification_t3
=== RUN   TestAccAWSLaunchTemplate_IamInstanceProfile_EmptyConfigurationBlock
=== PAUSE TestAccAWSLaunchTemplate_IamInstanceProfile_EmptyConfigurationBlock
=== RUN   TestAccAWSLaunchTemplate_networkInterface
=== PAUSE TestAccAWSLaunchTemplate_networkInterface
=== RUN   TestAccAWSLaunchTemplate_networkInterface_ipv6Addresses
=== PAUSE TestAccAWSLaunchTemplate_networkInterface_ipv6Addresses
=== RUN   TestAccAWSLaunchTemplate_networkInterface_ipv6AddressCount
=== PAUSE TestAccAWSLaunchTemplate_networkInterface_ipv6AddressCount
=== RUN   TestAccAWSLaunchTemplate_instanceMarketOptions
=== PAUSE TestAccAWSLaunchTemplate_instanceMarketOptions
=== RUN   TestAccAWSLaunchTemplate_licenseSpecification
=== PAUSE TestAccAWSLaunchTemplate_licenseSpecification
=== CONT  TestAccAWSLaunchTemplate_importBasic
=== CONT  TestAccAWSLaunchTemplate_licenseSpecification
=== CONT  TestAccAWSLaunchTemplate_update
=== CONT  TestAccAWSLaunchTemplate_tags
=== CONT  TestAccAWSLaunchTemplate_IamInstanceProfile_EmptyConfigurationBlock
=== CONT  TestAccAWSLaunchTemplate_creditSpecification_t3
=== CONT  TestAccAWSLaunchTemplate_instanceMarketOptions
=== CONT  TestAccAWSLaunchTemplate_creditSpecification_t2
=== CONT  TestAccAWSLaunchTemplate_networkInterface_ipv6AddressCount
=== CONT  TestAccAWSLaunchTemplate_creditSpecification_nonBurstable
=== CONT  TestAccAWSLaunchTemplate_networkInterface_ipv6Addresses
=== CONT  TestAccAWSLaunchTemplate_capacityReservation_target
=== CONT  TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS_DeleteOnTermination
=== CONT  TestAccAWSLaunchTemplate_description
=== CONT  TestAccAWSLaunchTemplate_data
=== CONT  TestAccAWSLaunchTemplate_capacityReservation_preference
=== CONT  TestAccAWSLaunchTemplate_EbsOptimized
=== CONT  TestAccAWSLaunchTemplate_disappears
=== CONT  TestAccAWSLaunchTemplate_networkInterface
=== CONT  TestAccAWSLaunchTemplate_ElasticInferenceAccelerator
--- PASS: TestAccAWSLaunchTemplate_disappears (21.94s)
=== CONT  TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS
--- PASS: TestAccAWSLaunchTemplate_networkInterface_ipv6AddressCount (26.70s)
=== CONT  TestAccAWSLaunchTemplate_basic
--- PASS: TestAccAWSLaunchTemplate_IamInstanceProfile_EmptyConfigurationBlock (26.82s)
=== CONT  TestAccAWSLaunchTemplate_importData
--- PASS: TestAccAWSLaunchTemplate_creditSpecification_t2 (26.94s)
--- PASS: TestAccAWSLaunchTemplate_data (27.11s)
--- PASS: TestAccAWSLaunchTemplate_creditSpecification_t3 (27.13s)
--- PASS: TestAccAWSLaunchTemplate_networkInterface_ipv6Addresses (27.13s)
--- PASS: TestAccAWSLaunchTemplate_creditSpecification_nonBurstable (27.35s)
--- PASS: TestAccAWSLaunchTemplate_capacityReservation_preference (27.38s)
--- PASS: TestAccAWSLaunchTemplate_licenseSpecification (30.62s)
--- PASS: TestAccAWSLaunchTemplate_importBasic (31.55s)
--- PASS: TestAccAWSLaunchTemplate_capacityReservation_target (37.52s)
--- PASS: TestAccAWSLaunchTemplate_description (45.69s)
--- PASS: TestAccAWSLaunchTemplate_ElasticInferenceAccelerator (49.20s)
--- PASS: TestAccAWSLaunchTemplate_tags (49.21s)
--- PASS: TestAccAWSLaunchTemplate_basic (26.33s)
--- PASS: TestAccAWSLaunchTemplate_importData (27.91s)
--- PASS: TestAccAWSLaunchTemplate_networkInterface (61.59s)
--- PASS: TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS (51.53s)
--- PASS: TestAccAWSLaunchTemplate_update (82.10s)
--- PASS: TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS_DeleteOnTermination (83.31s)
--- PASS: TestAccAWSLaunchTemplate_instanceMarketOptions (92.07s)
--- PASS: TestAccAWSLaunchTemplate_EbsOptimized (109.33s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       110.236s
```

### CODE REVIEW

**Comment by bflad** [comment]
Hey @ryndaniels 👋 This resource has been a good candidate for highlighting some limitations in the Terraform Plugin SDK type system. In EC2 Launch Templates, many of the boolean type fields actually have three states:

* enabled (`true`)
* disabled (`false`)
* unset (for example, determined by upstream AMI and unable to be determined by the SDK `TypeBool`)

To work around this limitation, we introduced a workaround with `TypeString` (https://github.com/terraform-providers/terraform-provider-aws/pull/5632), e.g.

https://github.com/terraform-providers/terraform-provider-aws/blob/1963850753be507dd4f6fa1f2238ed3e4b6c9385/aws/resource_aws_launch_template.go#L92-L101

Is this type of workaround more appropriate in this case? Removing the ability to specify `false` does not necessarily feel right in this case. While the [EC2 API Reference](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_LaunchTemplateInstanceNetworkInterfaceSpecificationRequest.html) doesn't necessarily clue into this too well, the EC2 web console does tend to show these enabled/disabled/unset configurations so it might be good verifying there if `false` and "unset" are valid.

For acceptance testing here, we should try to ensure there is covering of all attribute states (using `ExpectError` in the test framework if necessary). 👍

**Comment by ryndaniels** [comment]
@bflad it took a minute but I think I've got this working using the `TypeString` workaround now, with an additional couple more tests!

File: aws/resource_aws_launch_template_test.go [hunk 1]
```diff
@@ -1077,6 +1125,80 @@ resource "aws_launch_template" "test" {
 }
 `
 
+const testAccAWSLaunchTemplateConfig_associatePublicIpAddressTrue = `
```
Comment (bflad) [inline aws/resource_aws_launch_template_test.go]: Nit: This can be simplified into a single test configuration function by passing in the parameter, e.g.

```go
func testAccAWSLaunchTemplateConfig_associatePublicIpAddress(associatePublicIpAddress string) string {
  return fmt.Sprintf(`
# ...
resource "aws_launch_template" "test" {
  name = "network-interface-launch-template"

  network_interfaces {
    associate_public_ip_address = %[1]s
    network_interface_id        = "${aws_network_interface.test.id}"
    ipv4_address_count          = 2
  }
}
`, associatePublicIpAddress)
```

Where that is populated via:

```go
Config: testAccAWSLaunchTemplateConfig_associatePublicIpAddress("true"),
Config: testAccAWSLaunchTemplateConfig_associatePublicIpAddress("false"),
Config: testAccAWSLaunchTemplateConfig_associatePublicIpAddress("null"),
```

File: aws/resource_aws_launch_template_test.go [hunk 2]
```diff
@@ -1077,6 +1125,80 @@ resource "aws_launch_template" "test" {
...
+  vpc_id = "${aws_vpc.test.id}"
+  cidr_block = "10.1.0.0/24"
+}
+
+resource "aws_network_interface" "test" {
+  subnet_id = "${aws_subnet.test.id}"
+}
+
+resource "aws_launch_template" "test" {
+  name = "network-interface-launch-template"
```
Comment (bflad) [inline aws/resource_aws_launch_template_test.go]: This name needs to be randomized to prevent issues like:

```
--- FAIL: TestAccAWSLaunchTemplate_networkInterface (23.50s)
    testing.go:635: Step 0 error: errors during apply:

        Error: InvalidLaunchTemplateName.AlreadyExistsException: Launch template name already in use.
```

Combining with the suggested update above:

```go
func testAccAWSLaunchTemplateConfig_associatePublicIpAddress(rName, associatePublicIpAddress string) string {
  return fmt.Sprintf(`
# ...
resource "aws_launch_template" "test" {
  name = %[1]q

  network_interfaces {
    associate_public_ip_address = %[2]s
    network_interface_id        = "${aws_network_interface.test.id}"
    ipv4_address_count          = 2
  }
}
`, rName, associatePublicIpAddress)
```
