### PR TITLE
r/launch_template: exclude associate_public_ip_address when not set

### LINKED ISSUE #5293: No ability to exclude associate_public_ip_address from launch_template
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.10.8

### Affected Resource(s)

* `aws_launch_template`

### Terraform Configuration Files

Setting a network interface ID in a launch template and trying to exclude the `associate_public_ip_address` argument. AWS doesn't let you specify the `associatePublicIPAddress` on a defined network interface. 

e.g.
```
resource "aws_launch_template" "test" {
  name_prefix   = "test-"
  image_id      = "${data.aws_ami.coreos.image_id}"
  instance_type = "${var.instance_type}"

  network_interfaces {
    associate_public_ip_address = "null"
    network_interface_id = "${aws_network_interface.eth0.id}"
    device_index = "0"
  }
}
```

or 
```
resource "aws_launch_template" "test" {
  name_prefix   = "test-"
  image_id      = "${data.aws_ami.coreos.image_id}"
  instance_type = "${var.instance_type}"

  network_interfaces {
    network_interface_id = "${aws_network_interface.eth0.id}"
    device_index = "0"
  }
}
```

### Expected Behavior

Terraform would of excluded the `associatePublicIPAddress` setting from the launch template and then AWS would let you launch an instance or autoscaling group using it.

### Actual Behavior

> You must use a valid fully-formed launch template. The associatePublicIPAddress parameter cannot be specified for a network interface with an ID.

### Steps to Reproduce

1. `terraform apply`

### PR DESCRIPTION
**Pull request by kl4w**
Fixes #5293

Changes proposed in this pull request:

* exclude associate_public_ip_address when not set

Output from acceptance testing:

```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSLaunchTemplate_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSLaunchTemplate_ -timeout 120m
=== RUN   TestAccAWSLaunchTemplate_importBasic
--- PASS: TestAccAWSLaunchTemplate_importBasic (14.91s)
=== RUN   TestAccAWSLaunchTemplate_importData
--- PASS: TestAccAWSLaunchTemplate_importData (13.61s)
=== RUN   TestAccAWSLaunchTemplate_basic
--- PASS: TestAccAWSLaunchTemplate_basic (11.87s)
=== RUN   TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS
--- PASS: TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS (15.51s)
=== RUN   TestAccAWSLaunchTemplate_data
--- PASS: TestAccAWSLaunchTemplate_data (10.97s)
=== RUN   TestAccAWSLaunchTemplate_update
--- PASS: TestAccAWSLaunchTemplate_update (22.20s)
=== RUN   TestAccAWSLaunchTemplate_tags
--- PASS: TestAccAWSLaunchTemplate_tags (22.98s)
=== RUN   TestAccAWSLaunchTemplate_nonBurstable
--- PASS: TestAccAWSLaunchTemplate_nonBurstable (11.16s)
=== RUN   TestAccAWSLaunchTemplate_networkInterface
--- PASS: TestAccAWSLaunchTemplate_networkInterface (29.52s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	152.755s
```

### CODE REVIEW

**Comment by kl4w** [comment]
during some manual testing, found that `associate_public_ip_address` conflicts with `network_interface_id`. Is there any to put a `ConflictsWith` here given that you can have multiple network interfaces? Is that worth it?

**Comment by bflad** [comment]
> Is there any to put a `ConflictsWith` here given that you can have multiple network interfaces?

The current implementation of [`Schema.ConflictsWith`](https://godoc.org/github.com/hashicorp/terraform/helper/schema#Schema) is limited to static attribute keys from the root of the resource, which would not help in this case or be very readable. 🙁 

>    // ConflictsWith is a set of schema keys that conflict with this schema.
>    // This will only check that they're set in the _config_. This will not
>    // raise an error for a malfunctioning resource that sets a conflicting
>    // key.
>    ConflictsWith []string

In the [upcoming Terraform 0.12 release](https://www.hashicorp.com/blog/terraform-0-1-2-preview), we will however support `null` arguments.

File: aws/resource_aws_launch_template.go [hunk 1]
```diff
@@ -984,9 +984,14 @@ func readNetworkInterfacesFromConfig(ni map[string]interface{}) *ec2.LaunchTempl
 	var ipv4Addresses []*ec2.PrivateIpAddressSpecification
 	var ipv6Addresses []*ec2.InstanceIpv6AddressRequest
 	var privateIpAddress string
-	networkInterface := &ec2.LaunchTemplateInstanceNetworkInterfaceSpecificationRequest{
-		AssociatePublicIpAddress: aws.Bool(ni["associate_public_ip_address"].(bool)),
-		DeleteOnTermination:      aws.Bool(ni["delete_on_termination"].(bool)),
+	networkInterface := &ec2.LaunchTemplateInstanceNetworkInterfaceSpecificationRequest{}
+
+	if v, ok := ni["associate_public_ip_address"]; ok && v.(bool) {
```
Comment (bflad) [inline aws/resource_aws_launch_template.go]: I believe setting `false` should be a valid value (at least it is in the EC2 console from the options of don't set / disable / enable) -- I think we need to cover both cases of ignoring this attribute when `network_interface_id` is set, as well as allowing `false`.

File: aws/resource_aws_launch_template.go [hunk 2]
```diff
@@ -984,9 +984,14 @@ func readNetworkInterfacesFromConfig(ni map[string]interface{}) *ec2.LaunchTempl
...
+		networkInterface.AssociatePublicIpAddress = aws.Bool(v.(bool))
+	}
+
+	if v, ok := ni["delete_on_termination"]; ok && v.(bool) {
```
Comment (bflad) [inline aws/resource_aws_launch_template.go]: Same here -- I believe setting `false` should be a valid value (at least it is in the EC2 console from the options of don't set / off / on).

**Comment by kl4w** [comment]
@bflad made changes as requested, output of tests:

```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSLaunchTemplate_'
gofmt -w $(find . -name '*.go' |grep -v vendor)
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSLaunchTemplate_ -timeout 120m
=== RUN   TestAccAWSLaunchTemplate_importBasic
--- PASS: TestAccAWSLaunchTemplate_importBasic (14.69s)
=== RUN   TestAccAWSLaunchTemplate_importData
--- PASS: TestAccAWSLaunchTemplate_importData (13.00s)
=== RUN   TestAccAWSLaunchTemplate_basic
--- PASS: TestAccAWSLaunchTemplate_basic (12.40s)
=== RUN   TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS
--- PASS: TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS (15.28s)
=== RUN   TestAccAWSLaunchTemplate_data
--- PASS: TestAccAWSLaunchTemplate_data (11.15s)
=== RUN   TestAccAWSLaunchTemplate_update
--- PASS: TestAccAWSLaunchTemplate_update (21.79s)
=== RUN   TestAccAWSLaunchTemplate_tags
--- PASS: TestAccAWSLaunchTemplate_tags (23.41s)
=== RUN   TestAccAWSLaunchTemplate_nonBurstable
--- PASS: TestAccAWSLaunchTemplate_nonBurstable (11.11s)
=== RUN   TestAccAWSLaunchTemplate_networkInterface
--- PASS: TestAccAWSLaunchTemplate_networkInterface (36.63s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	159.516s
```

**Comment by bflad** [comment]
This has been released in [version 1.30.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1300-august-02-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
