### PR TITLE
resource/aws_db_event_subscription: Fix tag ARN handling

### LINKED ISSUE #4138: Problem with tags in aws_db_event_subscription
_This issue was originally opened by @phirivet as hashicorp/terraform#17822. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version

```
Terraform v0.11.6
+ provider.aws v1.14.0
```

### Terraform Configuration Files

```
resource "aws_db_event_subscription" "exemple-db-event" {
   name             = "exemple-dev-db-event"
   enabled          = true
   sns_topic        = "${data.aws_sns_topic.supervision.arn}"
   source_ids       = ["${aws_db_instance.exemple-db.id}"]
   source_type      = "db-instance"
   event_categories = [
      "availability",
      "failure",
      "low storage",
      "maintenance",
      "notification"
   ]
   tags {
      Name        = "exemple-dev-db-event"
      Environment = "Dev"
   }
}
```

### Debug Output

```
aws_db_event_subscription.exemple-db-event: Modifying... (ID: exemple-dev-db-event)
  tags.%:           "0" => "2"
  tags.Environment: "" => "Dev"
  tags.Name:        "" => "exemple-dev-db-event"

Error: Error applying plan:

1 error(s) occurred:

* aws_db_event_subscription.exemple-db-event: 1 error(s) occurred:

* aws_db_event_subscription.exemple-db-event: InvalidParameterValue: Unable to find a subnet group matching the resource name: arn:aws:rds:eu-central-1:XXXXXXXXXXXX:subgrp:exemple-dev-db-event
	status code: 400, request id: 290be018-cf86-4340-b192-a66bd8dd82fd

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.


ERROR: Job failed: exit code 1
```
### Expected Behavior

Once the aws_db_event_subscription is created the tags must be reported in the status file.

### Actual Behavior

First time the "terraform apply" is executed the resource is created with the tags. The tags can be checked in the AWS console. But the "terraform show" reports no tag and if the "terraform apply" command is executed again it tries to set the tags and failed with a strange error message:

aws_db_event_subscription.exemple-db-event: InvalidParameterValue: Unable to find a subnet group matching the resource name: arn:aws:rds:eu-central-1:XXXXXXXXXXXX:subgrp:exemple-dev-db-event

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. `terraform show`
4. `terraform apply`

### Additional Context

This resource worked fine with Terraform 0.11.3 and + provider.aws v1.11.0

### PR DESCRIPTION
**Pull request by bflad**
Additional updates:
* Add arn attribute
* Support configurable timeouts
* Use `isAWSErr()`
* Skip returning an error when deleting a non-existent subscription

The regression occurred during #4053, which was merged in for release in v1.14.0 of the AWS provider.

Fixes #4138 and the following testing:

```
=== RUN   TestAccAWSDBEventSubscription_basicUpdate
--- FAIL: TestAccAWSDBEventSubscription_basicUpdate (168.94s)
    testing.go:518: Step 0 error: Check failed: Check 5/5 error: aws_db_event_subscription.bar: Attribute 'tags.Name' not found

=== RUN   TestAccAWSDBEventSubscription_categoryUpdate
--- FAIL: TestAccAWSDBEventSubscription_categoryUpdate (617.09s)
    testing.go:518: Step 0 error: After applying this step, the plan was not empty:
        
        DIFF:
        
        UPDATE: aws_db_event_subscription.bar
          tags.%:    "0" => "1"
          tags.Name: "" => "name"

=== RUN   TestAccAWSDBEventSubscription_importBasic
--- FAIL: TestAccAWSDBEventSubscription_importBasic (769.86s)
    testing.go:518: Step 0 error: After applying this step, the plan was not empty:
        
        DIFF:
        
        UPDATE: aws_db_event_subscription.bar
          tags.%:    "0" => "1"
          tags.Name: "" => "name"

=== RUN   TestAccAWSDBEventSubscription_withSourceIds
--- FAIL: TestAccAWSDBEventSubscription_withSourceIds (166.35s)
    testing.go:518: Step 0 error: After applying this step, the plan was not empty:
        
        DIFF:
        
        UPDATE: aws_db_event_subscription.bar
          tags.%:    "0" => "1"
          tags.Name: "" => "name"
```

```
4 tests passed (all tests)
=== RUN   TestAccAWSDBEventSubscription_importBasic
--- PASS: TestAccAWSDBEventSubscription_importBasic (750.01s)
=== RUN   TestAccAWSDBEventSubscription_withSourceIds
--- PASS: TestAccAWSDBEventSubscription_withSourceIds (755.63s)
=== RUN   TestAccAWSDBEventSubscription_basicUpdate
--- PASS: TestAccAWSDBEventSubscription_basicUpdate (1235.63s)
=== RUN   TestAccAWSDBEventSubscription_categoryUpdate
--- PASS: TestAccAWSDBEventSubscription_categoryUpdate (1235.67s)
```

### CODE REVIEW

File: aws/resource_aws_db_event_subscription.go [hunk 1]
```diff
@@ -95,19 +101,25 @@ func resourceAwsDbEventSubscriptionCreate(d *schema.ResourceData, meta interface
...
 	log.Println("[DEBUG] Create RDS Event Subscription:", request)
 
-	_, err := rdsconn.CreateEventSubscription(request)
-	if err != nil {
+	output, err := conn.CreateEventSubscription(request)
+	if err != nil || output.EventSubscription == nil {
 		return fmt.Errorf("Error creating RDS Event Subscription %s: %s", name, err)
 	}
 
+	d.SetId(aws.StringValue(output.EventSubscription.CustSubscriptionId))
```
Comment (catsby) [inline aws/resource_aws_db_event_subscription.go]: nit: `d.SetId` should handle pointers fine (unlike `d.Set`, IIRC)

Comment (bflad) [reply aws/resource_aws_db_event_subscription.go]: I'd like to do some out of scope testing, but at first look `d.SetId()` does not have the same nil value reflection as `d.Set()`:

https://github.com/hashicorp/terraform/blob/2dc7241df0245b2be005946b4bc903dfab496c71/helper/schema/resource_data.go#L246-L249

https://github.com/hashicorp/terraform/blob/2dc7241df0245b2be005946b4bc903dfab496c71/helper/schema/resource_data.go#L171-L187

`InstanceState.ID` is `string` so it'd likely cause an interface panic still if I'm understanding the code correctly.

https://github.com/hashicorp/terraform/blob/2dc7241df0245b2be005946b4bc903dfab496c71/terraform/state.go#L1614

**Comment by bflad** [comment]
This has been released in [version 1.14.1 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1141-april-11-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
