### PR TITLE
tests/provider: Fix unparam Linting Issues and Enable in TravisCI Testing

### LINKED ISSUE #6336: Tech Debt: Fix unparam Linting Issues and Enable in TravisCI
And the beat goes on... 🎉 

- [ ] Fix existing `gometalinter --disable-all --enable unparam ./aws` issues

```
aws/autoscaling_tags.go:265:35:warning: parameter key always receives "key" (unparam)
aws/awserr.go:27:47:warning: parameter message always receives "send request failed" (unparam)
aws/awserr.go:27:34:warning: parameter code always receives "RequestError" (unparam)
aws/awserr.go:51:70:warning: parameter result 0 (interface{}) is never used (unparam)
aws/ecs_task_definition_equivalency.go:16:84:warning: parameter result 1 (error) is never used (unparam)
aws/resource_aws_api_gateway_stage.go:414:23:warning: parameter prefix always receives "/variables/" (unparam)
aws/resource_aws_athena_database.go:178:52:warning: parameter d is unused (unparam)
aws/resource_aws_athena_database.go:204:50:warning: parameter d is unused (unparam)
aws/resource_aws_batch_job_queue.go:165:43:warning: parameter timeout always receives 600000000000 (unparam)
aws/resource_aws_batch_job_queue.go:186:44:warning: parameter timeout always receives 600000000000 (unparam)
aws/resource_aws_cloudwatch_event_rule.go:284:32:warning: parameter length always receives 2048 (unparam)
aws/resource_aws_codedeploy_app.go:170:50:warning: parameter result 0 (string) is never used (unparam)
aws/resource_aws_directory_service_directory.go:493:108:warning: parameter timeout always receives 3600000000000 (unparam)
aws/resource_aws_elasticache_cluster.go:631:28:warning: parameter d is unused (unparam)
aws/resource_aws_elasticache_replication_group.go:778:95:warning: parameter givenState is unused (unparam)
aws/resource_aws_elasticache_replication_group.go:825:67:warning: parameter timeout always receives 2400000000000 (unparam)
aws/resource_aws_emr_cluster.go:1096:43:warning: parameter typ always receives "CORE" (unparam)
aws/resource_aws_emr_cluster.go:1352:78:warning: parameter result 1 (error) is never used (unparam)
aws/resource_aws_iam_policy_attachment.go:267:57:warning: parameter meta is unused (unparam)
aws/resource_aws_iam_policy_attachment.go:289:57:warning: parameter meta is unused (unparam)
aws/resource_aws_iam_policy_attachment.go:311:58:warning: parameter meta is unused (unparam)
aws/resource_aws_kms_grant.go:471:50:warning: parameter sep always receives "-" (unparam)
aws/resource_aws_launch_template.go:928:54:warning: parameter meta is unused (unparam)
aws/resource_aws_opsworks_instance.go:913:69:warning: parameter wait always receives true (unparam)
aws/resource_aws_opsworks_instance.go:951:84:warning: parameter meta is unused (unparam)
aws/resource_aws_opsworks_instance.go:951:31:warning: parameter d is unused (unparam)
aws/resource_aws_proxy_protocol_policy.go:262:56:warning: parameter result 0 (string) is never used (unparam)
aws/resource_aws_redshift_cluster.go:915:92:warning: parameter result 0 (interface{}) is never used (unparam)
aws/resource_aws_ses_receipt_rule.go:601:47:warning: parameter meta is unused (unparam)
aws/resource_aws_vpn_gateway.go:296:65:warning: parameter expected is unused (unparam)
aws/structure.go:1895:65:warning: parameter listName always receives "layer_ids" (unparam)
aws/structure.go:1968:49:warning: parameter key always receives "access" (unparam)
aws/validators.go:697:49:warning: parameter k always receives "name" (unparam)
aws/validators.go:709:46:warning: parameter k always receives "name" (unparam)
aws/validators.go:1680:53:warning: parameter k always receives "roles" (unparam)
aws/waf_token_handlers.go:47:35:warning: parameter region always receives "global" (unparam)
```

- [ ] Enable `unparam` in TravisCI via `.gometalinter.json` configuration

### PR DESCRIPTION
**Pull request by bflad**
Closes #6336 
Reference #5983 

Changes proposed in this pull request:

* Fixing straightforward `unparam` linting issues such as unused parameters
* Exporting functions flagged by `unparam` that will eventually be migrated into their own packages (ones that should keep their same function signature)
* Removing `getStringPtrList()` which is part of #5983 👍 

Output from acceptance testing:

```
--- PASS: TestAccAWSAutoScalingGroup_VpcUpdates (45.41s)
--- PASS: TestAccAWSAutoScalingGroup_namePrefix (47.51s)
--- PASS: TestAccAWSElasticTranscoderPipeline_basic (7.63s)
--- PASS: TestAccAWSAutoScalingGroup_emptyAvailabilityZones (63.25s)
--- PASS: TestAccAWSElasticTranscoderPipeline_notifications (12.13s)
--- PASS: TestAccAWSAutoScalingGroup_autoGeneratedName (77.29s)
--- PASS: TestAccAWSAutoScalingGroup_classicVpcZoneIdentifier (80.07s)
--- PASS: TestAccAWSElasticTranscoderPipeline_kmsKey (25.72s)
--- PASS: TestAccAWSAutoScalingGroup_launchTemplate (81.66s)
--- PASS: TestAccAWSElasticTranscoderPipeline_withPermissions (6.60s)
--- PASS: TestAccAWSElasticTranscoderPipeline_withContentConfig (12.30s)
--- PASS: TestAccAWSAutoScalingGroup_withMetrics (87.92s)
--- PASS: TestAccAWSAutoScalingGroup_ALB_TargetGroups (87.87s)
--- PASS: TestAccAWSAutoScalingGroup_LaunchTemplate_IAMInstanceProfile (58.59s)
--- PASS: TestAccAWSAutoScalingGroup_terminationPolicies (105.01s)
--- PASS: TestAccAWSAutoScalingGroup_withPlacementGroup (138.59s)
--- PASS: TestAccAWSAutoScalingGroup_enablingMetrics (167.31s)
--- PASS: TestAccAWSAutoScalingGroup_importBasic (168.45s)
--- PASS: TestAccAWSAutoScalingGroup_launchTemplate_update (198.27s)
--- PASS: TestAccAWSAutoScalingGroup_serviceLinkedRoleARN (198.89s)
--- PASS: TestAccAWSAutoScalingGroup_initialLifecycleHook (233.74s)
--- PASS: TestAccAWSAutoScalingGroup_basic (262.05s)
--- PASS: TestAccAWSAutoScalingGroup_tags (265.68s)
--- PASS: TestAccAWSAutoScalingGroup_suspendingProcesses (287.56s)
--- PASS: TestAccAWSAutoScalingGroup_ALB_TargetGroups_ELBCapacity (290.00s)
--- PASS: TestAccAWSEMRCluster_additionalInfo (342.91s)
--- PASS: TestAccAWSEMRCluster_basic (372.71s)
--- PASS: TestAccAWSEMRCluster_security_config (385.79s)
--- PASS: TestAccAWSEMRCluster_configurationsJson (414.18s)
--- PASS: TestAccAWSEMRCluster_instance_group_EBSVolumeType_st1 (419.35s)
--- PASS: TestAccAWSEMRCluster_Step_Basic (428.42s)
--- PASS: TestAccAWSEMRCluster_instance_group (453.19s)
--- PASS: TestAccAWSAutoScalingGroup_WithLoadBalancer (541.96s)
--- PASS: TestAccAWSEMRCluster_bootstrap_ordering (421.97s)
--- PASS: TestAccAWSEMRCluster_keepJob (393.11s)
--- PASS: TestAccAWSEMRCluster_Kerberos_ClusterDedicatedKdc (487.94s)
--- PASS: TestAccAWSEMRCluster_terminationProtected (467.78s)
--- PASS: TestAccAWSEMRCluster_Step_Multiple (530.79s)
--- PASS: TestAccAWSEMRCluster_s3Logging (597.50s)
--- PASS: TestAccAWSEMRCluster_tags (612.83s)
--- PASS: TestAccAWSEMRCluster_custom_ami_id (586.37s)
--- PASS: TestAccAWSEMRCluster_visibleToAllUsers (746.05s)
--- PASS: TestAccAWSEMRCluster_root_volume_size (705.99s)
```

### CODE REVIEW

File: aws/resource_aws_emr_cluster.go [hunk 1]
```diff
@@ -1298,12 +1302,23 @@ func expandInstanceGroupConfigs(instanceGroupConfigs []interface{}) []*emr.Insta
...
 		applyEbsConfig(configAttributes, config)
-		applyAutoScalingPolicy(configAttributes, config)
+
+		if v, ok := configAttributes["autoscaling_policy"]; ok {
+			var autoScalingPolicy *emr.AutoScalingPolicy
+
+			err := json.Unmarshal([]byte(v.(string)), &autoScalingPolicy)
+
+			if err != nil {
+				return []*emr.InstanceGroupConfig{}, fmt.Errorf("error parsing EMR Auto Scaling Policy JSON: %s", err)
```
Comment (bflad) [inline aws/resource_aws_emr_cluster.go]: Surfacing this error is showing some test failures that will need to be investigated:

```
--- FAIL: TestAccAWSEMRCluster_instance_group (19.17s)
    testing.go:538: Step 0 error: Error applying: 1 error occurred:
        	* aws_emr_cluster.tf-test-cluster: 1 error occurred:
        	* aws_emr_cluster.tf-test-cluster: error parsing EMR instance groups configuration: error parsing EMR Auto Scaling Policy JSON: unexpected end of JSON input
--- FAIL: TestAccAWSEMRCluster_instance_group_EBSVolumeType_st1 (18.81s)
    testing.go:538: Step 0 error: Error applying: 1 error occurred:
        	* aws_emr_cluster.tf-test-cluster: 1 error occurred:
        	* aws_emr_cluster.tf-test-cluster: error parsing EMR instance groups configuration: error parsing EMR Auto Scaling Policy JSON: unexpected end of JSON input
```

Comment (bflad) [reply aws/resource_aws_emr_cluster.go]: This has been fixed, forgot to exclude `""` 😉
