### PR TITLE
Use ParameterFilters instead of regular Filters on SSM parameter

### LINKED ISSUE #5281: New aws provider slow aws_ssm_parameter calls when running terraform plan
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_ssm_parameter

### Terraform Configuration Files

Add upwards of 100 parameter store values.
```hcl
resource "aws_ssm_parameter" "service-s3-bucket" {
  name      = "/${var.service}/${var.environment}/S3_BUCKET"
  type      = "String"
  value     = "${aws_s3_bucket.service-messages.id}"
  overwrite = true
}
```
### Expected Behavior

Better performance on newer versions of the provider

### Actual Behavior

A `terraform plan` is taking significantly longer on aws_ssm_parameter state refresh

### Steps to Reproduce

1. Set provider to:
```hcl
provider "aws" {
  region  = "${var.region}"
  version = "1.9.0"
}
```
2. Run `terraform plan` -> takes about 2 minutes to run in our case
3. Set provider to:
```hcl
provider "aws" {
  region  = "${var.region}"
  version = "1.28.0"
}
```
4. Run `terraform init`
5. Run `terraform plan` -> takes 10+ minutes now

### Important Factoids

Abnormally large amount of param store variables in our aws account(s)

### PR DESCRIPTION
**Pull request by julienduchesne**
Fixes #5281 

Changes proposed in this pull request:

* No need to paginate calls. DescribeParameters always returns the parameters asked for in the first page when using the `ParameterFilters` with the `Equals` option.

Output from acceptance testing:

```
TESTARGS='-run=TestAccAWSSSMParameter'  make testacc
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -run=TestAccAWSSSMParameter -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSSSMParameter_importBasic
--- PASS: TestAccAWSSSMParameter_importBasic (29.13s)
=== RUN   TestAccAWSSSMParameter_basic
--- PASS: TestAccAWSSSMParameter_basic (24.64s)
=== RUN   TestAccAWSSSMParameter_disappears
--- PASS: TestAccAWSSSMParameter_disappears (15.99s)
=== RUN   TestAccAWSSSMParameter_update
--- PASS: TestAccAWSSSMParameter_update (43.75s)
=== RUN   TestAccAWSSSMParameter_updateDescription
--- PASS: TestAccAWSSSMParameter_updateDescription (42.34s)
=== RUN   TestAccAWSSSMParameter_changeNameForcesNew
--- PASS: TestAccAWSSSMParameter_changeNameForcesNew (43.64s)
=== RUN   TestAccAWSSSMParameter_fullPath
--- PASS: TestAccAWSSSMParameter_fullPath (50.61s)
=== RUN   TestAccAWSSSMParameter_secure
--- PASS: TestAccAWSSSMParameter_secure (28.46s)
=== RUN   TestAccAWSSSMParameter_secure_with_key
--- PASS: TestAccAWSSSMParameter_secure_with_key (57.85s)
=== RUN   TestAccAWSSSMParameter_secure_keyUpdate
--- PASS: TestAccAWSSSMParameter_secure_keyUpdate (78.78s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       415.196s
```

### CODE REVIEW

File: aws/resource_aws_ssm_parameter.go [hunk 1]
```diff
@@ -105,30 +105,20 @@ func resourceAwsSsmParameterRead(d *schema.ResourceData, meta interface{}) error
...
 		return fmt.Errorf("error describing SSM parameter: %s", err)
 	}
-	if len(detailedParameters) == 0 {
-		log.Printf("[WARN] SSM Param %q not found, removing from state", d.Id())
-		d.SetId("")
-		return nil
-	}
 
-	detail := detailedParameters[0]
+	detail := describeResp.Parameters[0]
```
Comment (bflad) [inline aws/resource_aws_ssm_parameter.go]: To prevent potential panics, we should perform a `nil` check on `describeResp` and `len()` check on `describeResp.Parameters` before attempting to reference, e.g.

```go
if describeResp == nil || len(describeResp.Parameters) == 0 || describeResp.Parameters[0] == nil {
  log.Printf("[WARN] SSM Parameter %q not found, removing from state", d.Id())
  d.SetId("")
  return nil
}
detail := describeResp.Parameters[0]
```

**Comment by bflad** [comment]
This has been released in [version 1.29.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1290-july-26-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
