### PR TITLE
Addresses a number of issues with blocks in `aws_codedeploy_deployment_group`

### LINKED ISSUE #10836: aws_codedeploy_deployment_group issues with load_balancer_info
<!--- Please keep this note for the community --->

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

<!--- Thank you for keeping this note for the community --->

### Terraform Version

❯ terraform -v
Terraform v0.12.13
+ provider.aws v2.35.0

### Affected Resource(s)

* aws_codedeploy_deployment_group

### Terraform Configuration Files

Here's a direct cut and paste from my resource.  Originally I was using the dynamic hack as you can see below (commented out).  In order to rule this out I added a direct load_balancer_info{} block to make sure it wasn't that.

```hcl
resource "aws_codedeploy_deployment_group" "app" {                                                                                          
  app_name              = "${aws_codedeploy_app.app.name}"                                                                                  
  deployment_group_name = var.role                                                                                                          
  service_role_arn      = "${aws_iam_role.codedeploy.arn}"                                                                                  
  # If we only have a single instance, use the AllAtOnce config                                                                             
  deployment_config_name = var.instance_count == 1 ? "CodeDeployDefault.AllAtOnce" : "${aws_codedeploy_deployment_config.app.id}"           
                                                                                                                                            
  autoscaling_groups = ["${aws_autoscaling_group.service.name}"]                                                                            
                                                                                                                                            
  auto_rollback_configuration {                                                                                                             
    enabled = true                                                                                                                          
    events  = ["DEPLOYMENT_FAILURE"]                                                                                                        
  }                                                                                                                                         
                                                                                                                                            
  # This is intended to be a conditional block (using a language hack)                                                                      
  # in order to do nothing for the case of load_balancer == None                                                                            
  #dynamic "load_balancer_info" {                                                                                                           
  #  for_each = var.load_balancer_type == "none" ? [] : [1]                                                                                 
  #  content {                                                                                                                              
  #    target_group_info {                                                                                                                  
  #      name = aws_lb_target_group.service[0].name                                                                                         
  #    }                                                                                                                                    
  #  }                                                                                                                                      
  #}                                                                                                                                        
  load_balancer_info {                                                                                                                      
    target_group_info {                                                                                                                     
      name = aws_lb_target_group.service[0].name                                                                                            
    }                                                                                                                                       
  }                                                                                                                                         
}                                                  
```

### Debug Output

Sorry, the full output has a bunch of stuff I can't paste, but I assume this is the heart of what's going on:

2019/11/11 09:37:05 [WARN] Provider "aws" produced an invalid plan for module.web.aws_codedeploy_deployment_group.app, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .deployment_style: block count in plan (1) disagrees with count in config (0)

I can provide the full output privately if needed.

### Expected Behavior

When I run this I expect it to associate the target group with the codedeploy group but this step is always skipped, no matter how much I mess around and tweak the config.  Originally (I think?) this worked, I am pretty sure I manually verified this when I originally wrote this terraform, but somewhere along the way it stopped working.

I can no longer associate target groups with codedeploy, no matter what I do.  Adding it by hand does not inspire terraform to try and remove it either, it completely ignores this block.

### Actual Behavior

Nothing, a terraform plan is blank.

### Steps to Reproduce

I'm hoping you can simply create a target group and attempt to associate it with codedeploy in any way and see it fail.

1. `terraform apply`

### Important Factoids

Nothing that I can think of, this is all new stuff.

* #0000

### PR DESCRIPTION
**Pull request by gdavison**
Unexpected behaviour occurs with some block attributes of `aws_codedeploy_deployment_group` when blocks are updated or deleted.

This PR now:
* Actually deletes `load_balancer_info` via the API and state when the block is removed from the resource configuration. This would also previously prevent setting values on `load_balancer_info` if it had been removed from the configuration. See #10836
* Now resets `deployment_style` to defaults if it is removed from configuration. Previously, this would do nothing to the resource in AWS.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #10836

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_codedeploy_deployment_group: Fixes unexpected behaviour when removing block attributes
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSCodeDeployDeploymentGroup_'

--- PASS: TestAccAWSCodeDeployDeploymentGroup_deploymentStyle_default (47.18s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_loadBalancerInfo_targetGroupInfo_create (49.10s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_loadBalancerInfo_targetGroupInfo_delete (49.55s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_blueGreenDeployment_complete (53.70s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_triggerConfiguration_multiple (53.85s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_deploymentStyle_delete (56.37s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_deploymentStyle_create (58.31s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_loadBalancerInfo_update (61.30s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_loadBalancerInfo_delete (62.70s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_in_place_deployment_with_traffic_control_create (62.74s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_loadBalancerInfo_targetGroupInfo_update (62.94s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_autoRollbackConfiguration_disable (62.96s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_loadBalancerInfo_create (65.49s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_basic (69.96s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_alarmConfiguration_update (71.69s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_blueGreenDeploymentConfiguration_delete (73.06s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_disappears (38.72s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_alarmConfiguration_disable (87.97s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_deploymentStyle_update (87.97s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_in_place_deployment_with_traffic_control_update (89.99s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_alarmConfiguration_delete (49.61s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_alarmConfiguration_create (43.70s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_autoRollbackConfiguration_create (47.37s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_onPremiseTag (53.27s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_blueGreenDeploymentConfiguration_update (44.53s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_triggerConfiguration_basic (64.19s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_basic_tagSet (53.30s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_autoRollbackConfiguration_update (61.17s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_autoRollbackConfiguration_delete (64.07s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_blueGreenDeploymentConfiguration_create (137.16s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_blueGreenDeploymentConfiguration_update_with_asg (177.98s)
--- PASS: TestAccAWSCodeDeployDeploymentGroup_ECS_BlueGreen (308.25s)
```

### CODE REVIEW

File: aws/resource_aws_codedeploy_deployment_group_test.go [hunk 1]
```diff
@@ -42,6 +42,9 @@ func TestAccAWSCodeDeployDeploymentGroup_basic(t *testing.T) {
 						"aws_codedeploy_deployment_group.foo", "service_role_arn",
 						regexp.MustCompile("arn:aws:iam::[0-9]{12}:role/foo_role_.*")),
 
+					resource.TestCheckResourceAttr(
+						"aws_codedeploy_deployment_group.foo", "blue_green_deployment_config.#", "0"),
```
Comment (aeschright) [inline aws/resource_aws_codedeploy_deployment_group_test.go]: Since you're in here, you can clean up those `foo` bits to be our standard `test` naming.
