### PR TITLE
resource/aws_appautoscaling_policy: Support additional predefined metric types in validation

### LINKED ISSUE #3112: ECS Target Tracking AutoScaling
### Terraform Version
```
Terraform v0.11.2
+ provider.aws v1.7.1
+ provider.template v1.0.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_appautoscaling_policy

### Terraform Configuration Files
```hcl
resource "aws_appautoscaling_target" "ecs_target" {
  max_capacity       = 5
  min_capacity       = 2
  resource_id        = "service/ecs-cluster/ecs-service"
  scalable_dimension = "ecs:service:DesiredCount"
  service_namespace  = "ecs"
}

resource "aws_appautoscaling_policy" "ecs_targettracking" {
  name               = "ECSServiceAverageCPUUtilization:${aws_appautoscaling_target.ecs_target.resource_id}"
  policy_type        = "TargetTrackingScaling"
  resource_id        = "${aws_appautoscaling_target.ecs_target.resource_id}"
  scalable_dimension = "${aws_appautoscaling_target.ecs_target.scalable_dimension}"
  service_namespace  = "${aws_appautoscaling_target.ecs_target.service_namespace}"

  target_tracking_scaling_policy_configuration {
    predefined_metric_specification {
      predefined_metric_type = "ECSServiceAverageCPUUtilization"
    }

    target_value = 50
  }
}
```

### Expected Behavior
Create a target tracking scaling policy for the ECS service

### Actual Behavior
Validation error: `Error: aws_appautoscaling_policy.ecs_targettracking: "target_tracking_scaling_policy_configuration.0.predefined_metric_specification.0.predefined_metric_type" contains an invalid metric "ECSServiceAverageCPUUtilization". Valid metric are ["DynamoDBReadCapacityUtilization" "DynamoDBWriteCapacityUtilization"].`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### API/CLI Reference
https://docs.aws.amazon.com/autoscaling/application/APIReference/API_PredefinedMetricSpecification.html

#### Command
`aws application-autoscaling put-scaling-policy --cli-input-json file://scale-cli.json`

##### Payload
```json
{
  "PolicyName": "ECSServiceAverageCPUUtilization:service/ecs-cluster/ecs-service",
  "ServiceNamespace": "ecs",
  "ResourceId": "service/ecs-cluster/ecs-service",
  "ScalableDimension": "ecs:service:DesiredCount",
  "PolicyType": "TargetTrackingScaling",
  "TargetTrackingScalingPolicyConfiguration": {
    "PredefinedMetricSpecification": {
      "PredefinedMetricType": "ECSServiceAverageCPUUtilization"
    },
    "TargetValue": 50
  }
}
```

#### Response
```json
{
    "PolicyARN": "arn:aws:autoscaling:us-east-1:821452665997:scalingPolicy:a0d9cc4b-0f5e-4a4a-88bb-1b549bea1ebb:resource/ecs/service/ecs-cluster/ecs-service:policyName/ECSServiceAverageCPUUtilization:service/ecs-cluster/ecs-service",
    "Alarms": [
        {
            "AlarmName": "TargetTracking-service/ecs-cluster/ecs-service-AlarmHigh-adaa1f5f-bb37-4da6-ae26-0b7829fdb747",
            "AlarmARN": "arn:aws:cloudwatch:us-east-1:821452665997:alarm:TargetTracking-service/ecs-cluster/ecs-service-AlarmHigh-adaa1f5f-bb37-4da6-ae26-0b7829fdb747"
        },
        {
            "AlarmName": "TargetTracking-service/ecs-cluster/ecs-service-AlarmLow-88535a41-70d2-4cf6-9a21-37aaa24ba103",
            "AlarmARN": "arn:aws:cloudwatch:us-east-1:821452665997:alarm:TargetTracking-service/ecs-cluster/ecs-service-AlarmLow-88535a41-70d2-4cf6-9a21-37aaa24ba103"
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by bflad**
Closes #3112 

Validation of the attributes for `aws_appautoscaling_policy` has been a mixed bag of requests for the validation at plan time and issues like this where the validation is not up to date. Ideally, we would perform some type of compile time reflection of these `applicationautoscaling.MetricType*` constants instead, but this at least brings us up to all the currently supported predefined metrics types and adds unit testing.

```
make test TEST=./aws TESTARGS='-run=TestValidateAppautoscalingPredefinedMetricSpecification'
==> Checking that code complies with gofmt requirements...
go test ./aws -timeout=30s -parallel=4
ok  	github.com/terraform-providers/terraform-provider-aws/aws	1.800s
```

### CODE REVIEW

File: aws/validators.go [hunk 1]
```diff
@@ -1125,8 +1126,16 @@ func validateAppautoscalingCustomizedMetricSpecificationStatistic(v interface{},
...
+		applicationautoscaling.MetricTypeAlbrequestCountPerTarget,
+		applicationautoscaling.MetricTypeDynamoDbreadCapacityUtilization,
+		applicationautoscaling.MetricTypeDynamoDbwriteCapacityUtilization,
+		applicationautoscaling.MetricTypeEc2spotFleetRequestAverageCpuutilization,
+		applicationautoscaling.MetricTypeEc2spotFleetRequestAverageNetworkIn,
+		applicationautoscaling.MetricTypeEc2spotFleetRequestAverageNetworkOut,
+		applicationautoscaling.MetricTypeEcsserviceAverageCpuutilization,
+		applicationautoscaling.MetricTypeEcsserviceAverageMemoryUtilization,
+		applicationautoscaling.MetricTypeRdsreaderAverageCpuutilization,
+		applicationautoscaling.MetricTypeRdsreaderAverageDatabaseConnections,
```
Comment (radeksimko) [inline aws/validators.go]: Something tells me this list is going to continue to grow and we just shouldn't be validating it at all, instead of playing catch up with Amazon... 🤔

Comment (bflad) [reply aws/validators.go]: I agree with you for the most part. Its a challenge of better user experience (plan-time validation and requiring provider updates) vs development time (SDK not providing a quick way to get the full list of them). Since this PR is approved and we're planning on releasing today, I'll bring this one in as-is to at least fix the current state of the world, then will followup with a PR to remove the validation completely. We'll see if it lands in time for today as well.

As a separate pet project I will likely try to automatically `go generate` these from the SDK as I personally have found the plan-time validation to helpful and this type of generation would be applicable in a few other places. Then again I also always kept my AWS provider up to date in my environments.

Comment (bflad) [reply aws/validators.go]: As noted, followup PR to remove validation (if we want to): #3141

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.8.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#180-january-29-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
