### PR TITLE
Fixes website_endpoint and website_domain attributes in Chinese regions

### LINKED ISSUE #9378: Wrong S3 bucket website_endpoint and website_domain attributes in China regions
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.4
provider.aws v2.19.0

### Affected Resource(s)

* aws_s3_bucket

### Terraform Configuration Files

A simple bucket:

```hcl
provider "aws" {
    region      = "cn-northwest-1"
}

resource "aws_s3_bucket" "website_build" {
    bucket = local.bucket_name
    policy = data.template_file.policy_bucket_public.rendered

    website {
        index_document = "index.html"
    }

    tags = {
        Name = "${var.prefix}-website-build"
    }
}
```

### Expected Behavior

The proper endpoint is `http://<bucket>.s3-website.cn-northwest-1.amazonaws.com.cn`

### Actual Behavior

```
$ terraform.exe console
?[J> aws_s3_bucket.website_build.website_endpoint
<bucket>.s3-website.cn-northwest-1.amazonaws.com

?[J> aws_s3_bucket.website_build.website_domain
s3-website.cn-northwest-1.amazonaws.com

?[J> aws_s3_bucket.website_build.bucket_regional_domain_name
<bucket>.s3.cn-northwest-1.amazonaws.com.cn
```

Terraform is missing the .cn at the end of the domain for the website_endpoint and website_domain attributes. For comparison - bucket_regional_domain_name has a proper value.

### Steps to Reproduce

1. `terraform apply`

### PR DESCRIPTION
**Pull request by antonio-osorio**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Fixes #9378

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
BUG FIXES:
* resource/aws_s3_bucket: Fixes website_endpoint and website_domain attribute for Chinese regions 
```

### CODE REVIEW

**Comment by antonio-osorio** [comment]
```
go test ./... -timeout=30s -parallel=4
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
# github.com/terraform-providers/terraform-provider-aws/aws [github.com/terraform-providers/terraform-provider-aws/aws.test]
fatal error: runtime: cannot allocate memory
```

File: aws/resource_aws_s3_bucket.go [hunk 1]
```diff
@@ -1589,11 +1589,15 @@ func WebsiteEndpoint(bucket string, region string) *S3Website {
...
 
-	// New regions uses different syntax for website endpoints
-	// http://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteEndpoints.html
+	// Different regions have different syntax for website endpoints
+	// https://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteEndpoints.html
+	// https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_website_region_endpoints
 	if isOldRegion(region) {
 		return fmt.Sprintf("s3-website-%s.amazonaws.com", region)
 	}
+	if isChineseRegion(region) {
```
Comment (bflad) [inline aws/resource_aws_s3_bucket.go]: Hi @antonio-osorio 👋 Thanks for submitting this. Instead of performing our own custom logic here, can you please switch this to using the AWS Go SDK `endpoints` package?

```suggestion
	if partition, ok := endpoints.PartitionForRegion(endpoints.DefaultPartitions(), region); ok && partition.ID() == endpoints.AwsCnPartitionID {
```

This will automatically update the AWS China regions with AWS Go SDK updates as well as attempt regular expression lookups if the region name cannot be directly found. Thanks!

I have submitted an upstream feature request in the AWS to directly provide the DNS suffix information, which can help prevent us from hardcoding these cases in the future: https://github.com/aws/aws-sdk-go/issues/2710

Comment (antonio-osorio) [reply aws/resource_aws_s3_bucket.go]: Updated.

**Comment by antonio-osorio** [comment]
@bflad Updated the PR to incorporate your changes.

**Comment by bflad** [comment]
This has been released in [version 2.21.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2210-july-25-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

For further feature requests, documentation updates, or bug reports with this functionality, please create a [new GitHub issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new/choose) following the template for triage. Thanks!
