### PR TITLE
Fixing global rds by allowing for optional parameters on cluster

### LINKED ISSUE #7212: aws_rds_cluser global database support fails when second region is added
https://www.terraform.io/docs/providers/aws/r/rds_global_cluster.html

second region requires a username and password.  

aws fails to add the second region because the second region can't have master_username or master_password specified.  

i noticed the tests here https://github.com/terraform-providers/terraform-provider-aws/issues/6846 
only test a single region

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

success

### Actual Behavior

```* module.rds_uw2_global.aws_rds_cluster.global_aurora: 1 error(s) occurred:

* aws_rds_cluster.global_aurora: error creatingRDS cluster: InvalidParameterCombination: Cannot specify database name for cross region replication cluster
        status code: 400, request id: b86e8e5a-4919-47b9-8b22-735e0bd25f73```

```* module.rds_uw2_global.aws_rds_cluster.global_aurora: 1 error(s) occurred:

* aws_rds_cluster.global_aurora: provider.aws: aws_rds_cluster: : "master_password": required field is not set```
### Steps to Reproduce
 
create a aws global cluster with two regions like this 

terraform apply

### Important Factoids
 2 regions required to repro

### References

<!---
Information about referencing Github Issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests

Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Vendor documentation? For example:
--->

* #0000

### PR DESCRIPTION
**Pull request by bculberson**
Fixes #7212 and  #7020

TBD: Add global acc test

Changes proposed in this pull request:

* Change 1
Allow username and password to be optional when using a global cluster identifier
* Change 2
Allow source region and global cluster identifier to be set for secondary region to come online

Output from acceptance testing:

```
make testacc TESTARGS='-run=TestAccAWSRDSCluster_GlobalClusterIdentifier'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSRDSCluster_GlobalClusterIdentifier -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSRDSCluster_GlobalClusterIdentifier
=== PAUSE TestAccAWSRDSCluster_GlobalClusterIdentifier
=== RUN   TestAccAWSRDSCluster_GlobalClusterIdentifier_Add
=== PAUSE TestAccAWSRDSCluster_GlobalClusterIdentifier_Add
=== RUN   TestAccAWSRDSCluster_GlobalClusterIdentifier_Remove
=== PAUSE TestAccAWSRDSCluster_GlobalClusterIdentifier_Remove
=== RUN   TestAccAWSRDSCluster_GlobalClusterIdentifier_Update
=== PAUSE TestAccAWSRDSCluster_GlobalClusterIdentifier_Update
=== CONT  TestAccAWSRDSCluster_GlobalClusterIdentifier
=== CONT  TestAccAWSRDSCluster_GlobalClusterIdentifier_Update
=== CONT  TestAccAWSRDSCluster_GlobalClusterIdentifier_Remove
=== CONT  TestAccAWSRDSCluster_GlobalClusterIdentifier_Add
--- PASS: TestAccAWSRDSCluster_GlobalClusterIdentifier_Add (218.57s)
--- PASS: TestAccAWSRDSCluster_GlobalClusterIdentifier_Update (218.81s)
--- PASS: TestAccAWSRDSCluster_GlobalClusterIdentifier (243.67s)
--- PASS: TestAccAWSRDSCluster_GlobalClusterIdentifier_Remove (250.19s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	250.852s

...
```

### CODE REVIEW

**Comment by bculberson** [comment]
This is unnecessary, I was able to bring up the other region using a replication_source_identifier which should be the correct step.

**Comment by adamscharf** [comment]
I'd really like to see this merged as I'm facing the issues outline in #7212

File: aws/resource_aws_rds_cluster.go [hunk 1]
```diff
@@ -712,25 +712,34 @@ func resourceAwsRDSClusterCreate(d *schema.ResourceData, meta interface{}) error
...
 	} else {
-		if _, ok := d.GetOk("master_password"); !ok {
-			return fmt.Errorf(`provider.aws: aws_rds_cluster: %s: "master_password": required field is not set`, d.Get("database_name").(string))
-		}
 
-		if _, ok := d.GetOk("master_username"); !ok {
-			return fmt.Errorf(`provider.aws: aws_rds_cluster: %s: "master_username": required field is not set`, d.Get("database_name").(string))
+		if _, ok := d.GetOk("global_cluster_identifier"); !ok {
+			if _, ok := d.GetOk("master_password"); !ok {
+				return fmt.Errorf(`provider.aws: aws_db_instance: %s: "master_password": required field is not set`, d.Get("name").(string))
```
Comment (bflad) [inline aws/resource_aws_rds_cluster.go]: `name` is not an attribute in this resource's schema, so can cause a panic as found by the acceptance testing:

```
=== CONT  TestAccAWSRDSCluster_missingUserNameCausesError

------- Stderr: -------
panic: interface conversion: interface {} is nil, not string

goroutine 137 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsRDSClusterCreate(0xc000349260, 0x3c28320, 0xc0001adc00, 0xc000349260, 0x0)
	/opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_rds_cluster.go:718 +0x6d9d
```

Will fix this on merge.

File: aws/resource_aws_rds_cluster_test.go [hunk 2]
```diff
@@ -2250,6 +2250,22 @@ resource "aws_rds_cluster" "test" {
 `, rName, deletionProtection)
 }
 
+func testAccAWSRDSClusterConfig_GlobalEngineMode(rName string) string {
+	return fmt.Sprintf(`
+%s
+
+resource "aws_rds_cluster" "test" {
+  depends_on		   = ["aws_db_subnet_group.dbsubnet"]
```
Comment (bflad) [inline aws/resource_aws_rds_cluster_test.go]: Instead of using `depends_on` here, a direct reference can be used below instead:

```hcl
  db_subnet_group_name = "${aws_db_subnet_group.dbsubnet.name}"
```

File: aws/resource_aws_rds_cluster_test.go [hunk 3]
```diff
@@ -2262,40 +2278,76 @@ resource "aws_rds_cluster" "test" {
...
 func testAccAWSRDSClusterConfig_GlobalClusterIdentifier(rName string) string {
 	return fmt.Sprintf(`
+%s
+
 resource "aws_rds_global_cluster" "test" {
   global_cluster_identifier = %q
 }
 
 resource "aws_rds_cluster" "test" {
+  depends_on				= ["aws_db_subnet_group.dbsubnet"]
```
Comment (bflad) [inline aws/resource_aws_rds_cluster_test.go]: `depends_on` is extraneous here as there is already a direct reference below.

File: aws/resource_aws_rds_cluster_test.go [hunk 4]
```diff
@@ -2262,40 +2278,76 @@ resource "aws_rds_cluster" "test" {
...
 }
 
+func testAccAWSRDSClusterConfig_GlobalNetwork(rName string) string {
+	return fmt.Sprintf(`
+data "aws_availability_zones" "azs" { }
+
+resource "aws_vpc" "vpc" {
+  cidr_block = "10.0.0.0/16"
+  tags = {
+  	Name = "terraform-acctest-rds-cluster-global-cross-region"
```
Comment (bflad) [inline aws/resource_aws_rds_cluster_test.go]: Setting up cross-region acceptance testing is a pretty complicated undertaking (see also: `TestAccAWSRDSCluster_EncryptedCrossRegionReplication`). 😅 Since the implementation in 9b7a9b0d0861b46d84ad10d35de32950a6142822 is only halfway there and has a few other little issues, opting to merge this pull request, but revert that commit until we can get a full, new test setup, preferably separate from the existing ones.

**Comment by bflad** [comment]
This has been released in [version 1.60.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1600-february-22-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by typez** [comment]
Unfortunately, it looks like this change hadn't actually fixed the problem. I had no luck at all trying to create a global RDS cluster via Terraform. There is a new related issues with all the details - https://github.com/terraform-providers/terraform-provider-aws/issues/10188

**Comment by diprochatterjee** [comment]
Unfortunately this is still an issue. I have the same issue with creating a rds global cluster. The rds global cluster gets created but when I try to create an rds cluster as the primary cluster for the global cluster, it fails with error - * aws_rds_cluster.primary: error creating RDS cluster: InvalidParameterValue: The engine mode global you requested is currently unavailable. I am using Terraform version 0.11.11
