### PR TITLE
tests/provider: Add precheck (KinesisVideo)

### LINKED ISSUE #15868: tests/provider: Kinesis Video not supported in GovCloud
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

These tests fails on GovCloud:

```
TestAccAWSKinesisVideoStream_basic
TestAccAWSKinesisVideoStream_disappears
TestAccAWSKinesisVideoStream_options
TestAccAWSKinesisVideoStream_Tags
```

With this error: `no such host`.

### New or Affected Resource(s)

* aws_kinesis_video_stream

### Terraform Configuration Files

Example config:

```hcl
resource "aws_kinesis_video_stream" "default" {
  name = "terraform-kinesis-video-stream-test-%d"

  tags = {
    name = "yak-stream"
  }
}
```

### Debug Output

```
TestAccAWSKinesisVideoStream_basic: resource_aws_kinesis_video_stream_test.go:23: Step 1/3 error: Error running apply: 2020/10/27 13:18:25 [DEBUG] Using modified User-Agent: Terraform/0.12.29 HashiCorp-terraform-exec/0.10.0
        
        Error: Error creating Kinesis Video Stream: RequestError: send request failed
        caused by: Post "https://kinesisvideo.us-gov-west-1.amazonaws.com/createStream": dial tcp: lookup kinesisvideo.us-gov-west-1.amazonaws.com on 192.168.22.2:53: no such host

--- FAIL: TestAccAWSKinesisVideoStream_basic (25.23s)
```

### References

* #15869

### PR DESCRIPTION
**Pull request by YakDriver**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #15868

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Output from acceptance testing (GovCloud):

```
    provider_test.go:545: skipping tests; partition aws-us-gov does not support kinesisvideo service
--- SKIP: TestAccAWSKinesisVideoStream_options (1.55s)
--- SKIP: TestAccAWSKinesisVideoStream_Tags (1.56s)
--- SKIP: TestAccAWSKinesisVideoStream_basic (1.56s)
--- SKIP: TestAccAWSKinesisVideoStream_disappears (1.56s)
```

Output from acceptance testing (commercial):

```
--- PASS: TestAccAWSKinesisVideoStream_disappears (93.72s)
--- PASS: TestAccAWSKinesisVideoStream_options (128.51s)
--- PASS: TestAccAWSKinesisVideoStream_Tags (142.80s)
--- PASS: TestAccAWSKinesisVideoStream_basic (193.16s)
```

### CODE REVIEW

File: aws/resource_aws_kinesis_video_stream_test.go [hunk 1]
```diff
@@ -21,7 +21,7 @@ func TestAccAWSKinesisVideoStream_basic(t *testing.T) {
 	rInt2 := acctest.RandInt()
 
 	resource.ParallelTest(t, resource.TestCase{
-		PreCheck:     func() { testAccPreCheck(t) },
+		PreCheck:     func() { testAccPreCheck(t); testAccPartitionHasServicePreCheck("kinesisvideo", t) },
```
Comment (bflad) [inline aws/resource_aws_kinesis_video_stream_test.go:24]: Nit: If you want!

```suggestion
		PreCheck:     func() { testAccPreCheck(t); testAccPartitionHasServicePreCheck(kinesisvideo.EndpointsID, t) },
```

File: aws/resource_aws_kinesis_video_stream_test.go [hunk 2]
```diff
@@ -62,7 +62,7 @@ func TestAccAWSKinesisVideoStream_options(t *testing.T) {
 	rName2 := acctest.RandString(8)
 
 	resource.ParallelTest(t, resource.TestCase{
-		PreCheck:     func() { testAccPreCheck(t) },
+		PreCheck:     func() { testAccPreCheck(t); testAccPartitionHasServicePreCheck("kinesisvideo", t) },
```
Comment (bflad) [inline aws/resource_aws_kinesis_video_stream_test.go:65]:
```suggestion
		PreCheck:     func() { testAccPreCheck(t); testAccPartitionHasServicePreCheck(kinesisvideo.EndpointsID, t) },
```

File: aws/resource_aws_kinesis_video_stream_test.go [hunk 3]
```diff
@@ -103,7 +103,7 @@ func TestAccAWSKinesisVideoStream_Tags(t *testing.T) {
 	rInt := acctest.RandInt()
 
 	resource.ParallelTest(t, resource.TestCase{
-		PreCheck:     func() { testAccPreCheck(t) },
+		PreCheck:     func() { testAccPreCheck(t); testAccPartitionHasServicePreCheck("kinesisvideo", t) },
```
Comment (bflad) [inline aws/resource_aws_kinesis_video_stream_test.go:106]:
```suggestion
		PreCheck:     func() { testAccPreCheck(t); testAccPartitionHasServicePreCheck(kinesisvideo.EndpointsID, t) },
```

File: aws/resource_aws_kinesis_video_stream_test.go [hunk 4]
```diff
@@ -148,7 +148,7 @@ func TestAccAWSKinesisVideoStream_disappears(t *testing.T) {
...
```
Comment (bflad) [inline aws/resource_aws_kinesis_video_stream_test.go:151]:
```suggestion
		PreCheck:     func() { testAccPreCheck(t); testAccPartitionHasServicePreCheck(kinesisvideo.EndpointsID, t) },
```

**Review by bflad — APPROVED** [review]
Looks good 🚀 

Output from acceptance testing in AWS Commercial:

```
--- PASS: TestAccAWSKinesisVideoStream_basic (191.65s)
--- PASS: TestAccAWSKinesisVideoStream_disappears (92.55s)
--- PASS: TestAccAWSKinesisVideoStream_options (125.67s)
--- PASS: TestAccAWSKinesisVideoStream_Tags (139.90s)
```

Output from acceptance testing in AWS GovCloud (US):

```
--- SKIP: TestAccAWSKinesisVideoStream_basic (1.33s)
--- SKIP: TestAccAWSKinesisVideoStream_disappears (1.32s)
--- SKIP: TestAccAWSKinesisVideoStream_options (1.33s)
--- SKIP: TestAccAWSKinesisVideoStream_Tags (1.33s)
```

File: aws/resource_aws_kinesis_video_stream_test.go (hunk 2 above)
Comment (YakDriver) [reply aws/resource_aws_kinesis_video_stream_test.go]: Yes, much better!
