### PR TITLE
resource/aws_lb_listener: Retry CertificateNotFound errors on update for IAM eventual consistency

### LINKED ISSUE #2053: aws_lb_listener can't find just created aws_iam_server_certificate - error:CertificateNotFound
_This issue was originally opened by @amsq as hashicorp/terraform#16446. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

Hi There,

I am trying to recreate a test certificate attached to my aws_lb_listener every time we run Terraform.

After Terraform creates the tls_self_signed_cert resource and the new aws_iam_server_certificate and they both complete successfully Terraform tries to modify the aws_lb_listener resource with the new just generate ARN of the aws_iam_server_certificate but it fails saying CertificateNotFound.

The logs show something like this
```
tls_self_signed_cert.dev_ssc: Creating...
tls_self_signed_cert.dev_ssc: Creation complete after 0s
aws_iam_server_certificate.dev_certificate: Creating...
aws_iam_server_certificate.dev_certificate: Creation complete after 2s
aws_lb_listener.front_end_ssl: Modifying... 
certificate_arn: "arn:aws:iam::xxxxxxx:server-certificate/dev-ssc-cert-20171025091035486000000001" => "arn:aws:iam::xxxxxxx:server-certificate/dev-ssc-cert-20171025092313434000000001"

Releasing state lock. This may take a few moments...
Error modifying LB Listener: CertificateNotFound: Certificate 'arn:aws:iam::xxxxxxx:server-certificate/dev-ssc-cert-20171025092313434000000001' not found
```

Terraform version its v0.10.7

### PR DESCRIPTION
**Pull request by bflad**
Closes #2053

Tests
```
pending
```

### CODE REVIEW

File: aws/resource_aws_lb_listener.go [hunk 1]
```diff
@@ -127,16 +127,12 @@ func resourceAwsLbListenerCreate(d *schema.ResourceData, meta interface{}) error
 		var err error
 		log.Printf("[DEBUG] Creating LB listener for ARN: %s", d.Get("load_balancer_arn").(string))
 		resp, err = elbconn.CreateListener(params)
-		if awsErr, ok := err.(awserr.Error); ok {
-			if awsErr.Code() == "CertificateNotFound" {
-				log.Printf("[WARN] Got an error while trying to create LB listener for ARN: %s: %s", lbArn, err)
+		if err != nil {
+			if isAWSErr(err, elbv2.ErrCodeCertificateNotFoundException, "") {
```
Comment (radeksimko) [inline aws/resource_aws_lb_listener.go]: Nitpick: Do you mind making a similar change in `isListenerNotFound` at the bottom of this file, so we can get rid of the `awserr` package import? 🙂

**Comment by bflad** [comment]
This has been released in [version 1.13.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1130-march-28-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
