### PR TITLE
Fix AWS EMR Instance Group Deletion Errors

### LINKED ISSUE #1355: aws_emr_instance_group can't be destroyed
Given a definition like below:

```
resource "aws_emr_instance_group" "querying-task-nodes" {
  name                      = "task"
  cluster_id                = "${aws_emr_cluster.querying.id}"
  instance_type             = "m4.xlarge"
  instance_count            = 5
}
```

If the EMR cluster is being destroyed successfully the instance group is getting into a limbo and can't be destroyed via terraform, giving the following error:

```
* aws_emr_instance_group.querying-task-nodes: ValidationException: An instance group may only be modified when the cluster is running or waiting.
	status code: 400, request id: d9555f4d-791e-11e7-b51e-cf8d28f27320
```

From what I can gather the issue is with the IG not being removed before the cluster is destroyed.

Using latest terraform (Terraform v0.10.0)

### LINKED ISSUE #9400: [EMR] ValidationException: An instance group may only be modified when the cluster is running or waiting
_This issue was originally opened by @hdryx as hashicorp/terraform#22116. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._
    
<hr>
    

### Terraform Version
v0.12.3

### Terraform Configuration Files

```hcl
resource "aws_emr_cluster" "cluster" {
  name          = "${var.project}-${var.cluster_name}-${var.environment}"
  release_label = "${var.emr_release_label}"
  applications  = "${var.emr_application}"

  ec2_attributes {
    subnet_id                         = "${data.aws_subnet.private_1.id}"
    emr_managed_master_security_group = "${data.aws_security_group.sg_emr_master.id}"
    emr_managed_slave_security_group  = "${data.aws_security_group.sg_emr_slave.id}"
    instance_profile                  = "${data.aws_iam_instance_profile.iam_emr_instance_profile.arn}"


    # Because we are launching the EMR in a private subnet we should use a service_access_security_group
    # service_access_security_group = "${aws_security_group.emr_service_access.id}"
    service_access_security_group = "${data.aws_security_group.sg_emr_service_access.id}"
  }
  master_instance_group {
    instance_type = "${var.master_instance_type}"
    bid_price      = "${var.spot_core_bid_price}"
    
    ebs_config {
      size                 = "${var.ebs_config_size}"
      type                 = "${var.ebs_config_type}"
      volumes_per_instance = "${var.ebs_config_volume_per_instance}"
    }
  }


  core_instance_group {
    instance_type  = "${var.core_instance_type}"
    instance_count = "${var.core_instance_count}"
    bid_price      = "${var.spot_core_bid_price}"

    ebs_config {
      size                 = "${var.ebs_config_size}"
      type                 = "${var.ebs_config_type}"
      volumes_per_instance = "${var.ebs_config_volume_per_instance}"
    }
  }

  ebs_root_volume_size = "${var.ebs_root_volume_size}"

  tags = "${merge(var.resource_tagging, map("Name", "${var.project}-${var.environment}-emr-cluster"))}"

  lifecycle {
    create_before_destroy = true
  }

  log_uri = "s3://${data.aws_s3_bucket.logs.id}/emr"

  # Terminate cluster when steps are done
  keep_job_flow_alive_when_no_steps = "${var.keep_job_no_steps}"

  bootstrap_action {
    path = "s3://${data.aws_s3_bucket.sources.id}/src/shell/${var.bootstrap_file}"
    name = "${var.bootstrap_name}"
    args = "${var.bootstrap_args}"
  }

  # Configuration of the cluster
  configurations_json = "${var.configuration_file != "" ? file("config/${var.configuration_file}") : ""}"

  # Role for the cluster
  service_role = "${data.aws_iam_role.iam_emr_service_role.arn}"


  # Steps to be executed by the cluster
  dynamic "step" {
    # for_each = jsondecode(templatefile("${path.module}/steps/${var.step_file}", {
    for_each = jsondecode(templatefile("../03_emr/steps/${var.step_file}", {
      # General Variables
      s3_sources      = "${data.aws_s3_bucket.sources.id}"
    }))

    content {
      action_on_failure = step.value.action_on_failure
      name              = step.value.name
      hadoop_jar_step {
        jar  = step.value.hadoop_jar_step.jar
        args = step.value.hadoop_jar_step.args
      }
    }
  }

}


resource "aws_emr_instance_group" "task" {
  name           = "${var.project}-${var.cluster_name}-instance-${var.environment}"
  cluster_id     = "${aws_emr_cluster.cluster.id}"
  instance_count = "${var.spot_core_instance_count}"
  instance_type  = "${var.spot_core_instance_type}"
  bid_price      = "${var.spot_core_bid_price}"

  depends_on = ["aws_emr_cluster.cluster"]
}

...
```

### Crash Output
Error: error draining EMR Instance Group (ig-24CP9QNA1THDI): ValidationException: An instance group may only be modified when the cluster is running or waiting.
        status code: 400, request id: f6b923cc-a935-11e9-97e8-993b41767f35

### Expected Behavior
I expected that the Task Group should be created and added to the EMR

### Actual Behavior
EMR is launched but the Task Group is not created (see error above)

### PR DESCRIPTION
**Pull request by joelthompson**
In situations where Terraform needs to replace an aws_emr_cluster
resource that has aws_emr_instance_group resources associated with it,
Terraform tries to execute a destroy on the instance group, but it fails
as the notion of a "destroy" on an instance group is to set the number
of instances to zero, but AWS doesn't let you modify the count of
instances in an instance group on an EMR cluster. This fixes the issue
by treating an instance group that has been terminated as no longer
existing, so Terraform won't try to execute a "destroy" and not error
out.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #1355
Closes #9400

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
Gracefully handle deletion of aws_emr_instance_group resources when the underlying cluster has been terminated.
```

Output from acceptance testing:

Note that one test failed due to EC2 resource limits in my test account but succeeded on a retry:

```
$ make testacc TESTARGS='-run=TestAccAWSEMRInstanceGroup'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -count 1 -parallel 20 -run=TestAccAWSEMRInstanceGroup -timeout 120m
go: finding github.com/terraform-providers/terraform-provider-tls v2.1.1+incompatible
go: finding github.com/terraform-providers/terraform-provider-tls v2.1.1+incompatible
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSEMRInstanceGroup_basic
=== PAUSE TestAccAWSEMRInstanceGroup_basic
=== RUN   TestAccAWSEMRInstanceGroup_BidPrice
=== PAUSE TestAccAWSEMRInstanceGroup_BidPrice
=== RUN   TestAccAWSEMRInstanceGroup_AutoScalingPolicy
=== PAUSE TestAccAWSEMRInstanceGroup_AutoScalingPolicy
=== RUN   TestAccAWSEMRInstanceGroup_InstanceCount
=== PAUSE TestAccAWSEMRInstanceGroup_InstanceCount
=== RUN   TestAccAWSEMRInstanceGroup_EbsConfig_EbsOptimized
=== PAUSE TestAccAWSEMRInstanceGroup_EbsConfig_EbsOptimized
=== CONT  TestAccAWSEMRInstanceGroup_basic
=== CONT  TestAccAWSEMRInstanceGroup_EbsConfig_EbsOptimized
=== CONT  TestAccAWSEMRInstanceGroup_InstanceCount
=== CONT  TestAccAWSEMRInstanceGroup_BidPrice
=== CONT  TestAccAWSEMRInstanceGroup_AutoScalingPolicy
--- FAIL: TestAccAWSEMRInstanceGroup_BidPrice (6.17s)
    testing.go:569: Step 0 error: errors during apply:
        
        Error: Error creating VPC: VpcLimitExceeded: The maximum number of VPCs has been reached.
                status code: 400, request id: ea160175-440a-4c9f-899b-4420e0b0d07e
        
          on /tmp/tf-test382298782/main.tf line 28:
          (source code not available)
        
        
--- PASS: TestAccAWSEMRInstanceGroup_EbsConfig_EbsOptimized (558.46s)
--- PASS: TestAccAWSEMRInstanceGroup_basic (565.65s)
--- PASS: TestAccAWSEMRInstanceGroup_AutoScalingPolicy (589.18s)
--- PASS: TestAccAWSEMRInstanceGroup_InstanceCount (852.11s)
FAIL
FAIL    github.com/terraform-providers/terraform-provider-aws/aws       852.157s
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/flatmap      0.003s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags 0.006s [no tests to run]
FAIL
make: *** [testacc] Error 1

$ make testacc TESTARGS='-run=TestAccAWSEMRInstanceGroup_BidPrice'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -count 1 -parallel 20 -run=TestAccAWSEMRInstanceGroup_BidPrice -timeout 120m
go: finding github.com/terraform-providers/terraform-provider-tls v2.1.1+incompatible
go: finding github.com/terraform-providers/terraform-provider-tls v2.1.1+incompatible
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSEMRInstanceGroup_BidPrice
=== PAUSE TestAccAWSEMRInstanceGroup_BidPrice
=== CONT  TestAccAWSEMRInstanceGroup_BidPrice
--- PASS: TestAccAWSEMRInstanceGroup_BidPrice (549.58s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       549.608s
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/flatmap      0.002s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags 0.004s [no tests to run]
```

### CODE REVIEW

File: aws/resource_aws_emr_instance_group.go [hunk 1]
```diff
@@ -177,6 +177,12 @@ func resourceAwsEMRInstanceGroupRead(d *schema.ResourceData, meta interface{}) e
 		return fmt.Errorf("error reading EMR Instance Group (%s): %s", d.Id(), err)
 	}
 
+	if *ig.Status.State == "TERMINATED" {
```
Comment (bflad) [inline aws/resource_aws_emr_instance_group.go]: To prevent potential panics, can you please add `nil` checking here and use some of the AWS Go SDK goodies? 😄 

```suggestion
	if ig.Status != nil && aws.StringValue(ig.Status.State) == emr.InstanceGroupStateTerminated {
```

**Comment by joelthompson** [comment]
Hey @bflad -- great to see you at HashiConf and catch up! And I appreciate the really helpful suggestions!

Also a quick note -- I'm being a bit conservative here and only implementing the one known state that we've run into. There could be other states that should trigger ignoring the instance group (e.g., TERMINATING -- see https://github.com/aws/aws-sdk-go/blob/master/service/emr/api.go#L11030 for the complete list of states), but I'd be hesitant to be more speculative and treat other states as effectively being deleted when they actually aren't which could cause Terraform to leak resources. Thoughts? Does this make sense?

Anyway, I've implemented the suggestions and verified the two tests pass as expected:

```
$ make testacc TESTARGS='-run=TestAccAWSEMRCluster_disappears'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -count 1 -parallel 20 -run=TestAccAWSEMRCluster_disappears -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSEMRCluster_disappears
=== PAUSE TestAccAWSEMRCluster_disappears
=== CONT  TestAccAWSEMRCluster_disappears
--- PASS: TestAccAWSEMRCluster_disappears (441.29s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       441.315s
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/flatmap      0.002s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags 0.026s [no tests to run]

$ make testacc TESTARGS='-run=TestAccAWSEMRInstanceGroup_EmrClusterDisappears'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -count 1 -parallel 20 -run=TestAccAWSEMRInstanceGroup_EmrClusterDisappears -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSEMRInstanceGroup_EmrClusterDisappears
=== PAUSE TestAccAWSEMRInstanceGroup_EmrClusterDisappears
=== CONT  TestAccAWSEMRInstanceGroup_EmrClusterDisappears
--- PASS: TestAccAWSEMRInstanceGroup_EmrClusterDisappears (378.58s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       378.608s
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/flatmap      0.002s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags 0.004s [no tests to run]
```

**Comment by bflad** [comment]
> There could be other states that should trigger ignoring the instance group (e.g., TERMINATING

We go either which way on implementing these -- usually we'll automatically remove things on states like `TERMINATING` since its likely that the operator would want to recreate it since the API is telling us its about to disappear, but its also such an edge case that likely does not matter too much.

**Comment by joelthompson** [comment]
> > There could be other states that should trigger ignoring the instance group (e.g., TERMINATING
> 
> We go either which way on implementing these -- usually we'll automatically remove things on states like `TERMINATING` since its likely that the operator would want to recreate it since the API is telling us its about to disappear, but its also such an edge case that likely does not matter too much.

This would be **so** much easier if AWS would just post the state machine that they promise to abide by and we wouldn't have to speculate on things like this. OK, I know, I sometimes have wild and unrealistic fantasies. I personally tend to be overly paranoid and worry about things like, "Is it possible to cancel a termination?" At least with `TERMINATING`, it should eventually go into `TERMINATED` and thus will get cleaned if we just look for `TERMINATED`.

Anyway, I'll go ahead and add just `TERMINATING` and leave the others for now.

File: aws/resource_aws_emr_instance_group.go (hunk 1 above)
Comment (joelthompson) [reply aws/resource_aws_emr_instance_group.go]: Sigh, all these pointers are really annoying. Though, I suppose, this does leave the question of how to treat `ig.Status` being `nil` -- is it an error condition? Does it mean the IG doesn't exist? Something else?

**Comment by joelthompson** [comment]
> Anyway, I'll go ahead and add just `TERMINATING` and leave the others for now.

OK, done. Not sure if there's a good way to test for `TERMINATING` (versus `TERMINATED)`, though.

```
$ make testacc TESTARGS='-run=TestAccAWSEMRInstanceGroup_EmrClusterDisappears'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -count 1 -parallel 20 -run=TestAccAWSEMRInstanceGroup_EmrClusterDisappears -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSEMRInstanceGroup_EmrClusterDisappears
=== PAUSE TestAccAWSEMRInstanceGroup_EmrClusterDisappears
=== CONT  TestAccAWSEMRInstanceGroup_EmrClusterDisappears
--- PASS: TestAccAWSEMRInstanceGroup_EmrClusterDisappears (358.62s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       358.647s
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/flatmap      0.007s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags 0.005s [no tests to run]
```

**Comment by joelthompson** [comment]
Thanks so much @bflad :)
