### PR TITLE
Use placement group in spot fleet requests when it is specified

### LINKED ISSUE #6713: placement_group not being used in resource_aws_spot_fleet_request.go
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.10
+ provider.aws v1.50.0
+ provider.null v1.0.0
+ provider.template v1.0.0
```

### Affected Resource(s)

* the launch specification in aws_spot_fleet_request. referenced in [resource_aws_spot_fleet_request.go](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_spot_fleet_request.go#L221) 

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

I would expect, by placing a placement_group name in the launch specification, the instances in the spot fleet get placed into a placement group. 

### Actual Behavior

placement_group setting isn't set at all, basically ignore. I also don't see `placement_group` being used at all in the provider. 

### Steps to Reproduce

launch specification: 
```
launch_specification {
    ami                      = "${var.ecs_instance_ami}"
    instance_type            = "${var.spot_fleet_instance_type2}"
    iam_instance_profile_arn = "${var.iam_instance_profile_arn}"
    key_name                 = "${var.key_name}"
    user_data                = "${var.user_data}"
    subnet_id                = "${element(var.subnet_ids, 0)}"
    vpc_security_group_ids   = ["${var.security_groups}"]
    placement_group          = "${var.placement_group_name}"

    tags {
      Name            = "${var.asg_name}"
      Environment     = "${var.environment}"
      ...
      RetentionPeriod = "14"
    }
  }
```

### References

* #0000

### PR DESCRIPTION
**Pull request by ryndaniels**
Looking at [the API](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#SpotPlacement), this probably should get set if it is present in the schema.  

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #6713

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
BUG FIXES:
* resource/aws_spot_fleet_request: Placement group names in launch specifications no longer get ignored
```

Output from acceptance testing:

```
$ make testacc TESTARGS="-run=TestAccAWSSpotFleetRequest_"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSSpotFleetRequest_ -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSSpotFleetRequest_basic
=== PAUSE TestAccAWSSpotFleetRequest_basic
=== RUN   TestAccAWSSpotFleetRequest_associatePublicIpAddress
=== PAUSE TestAccAWSSpotFleetRequest_associatePublicIpAddress
=== RUN   TestAccAWSSpotFleetRequest_instanceInterruptionBehavior
=== PAUSE TestAccAWSSpotFleetRequest_instanceInterruptionBehavior
=== RUN   TestAccAWSSpotFleetRequest_fleetType
=== PAUSE TestAccAWSSpotFleetRequest_fleetType
=== RUN   TestAccAWSSpotFleetRequest_iamInstanceProfileArn
=== PAUSE TestAccAWSSpotFleetRequest_iamInstanceProfileArn
=== RUN   TestAccAWSSpotFleetRequest_changePriceForcesNewRequest
=== PAUSE TestAccAWSSpotFleetRequest_changePriceForcesNewRequest
=== RUN   TestAccAWSSpotFleetRequest_updateTargetCapacity
=== PAUSE TestAccAWSSpotFleetRequest_updateTargetCapacity
=== RUN   TestAccAWSSpotFleetRequest_updateExcessCapacityTerminationPolicy
=== PAUSE TestAccAWSSpotFleetRequest_updateExcessCapacityTerminationPolicy
=== RUN   TestAccAWSSpotFleetRequest_lowestPriceAzOrSubnetInRegion
=== PAUSE TestAccAWSSpotFleetRequest_lowestPriceAzOrSubnetInRegion
=== RUN   TestAccAWSSpotFleetRequest_lowestPriceAzInGivenList
=== PAUSE TestAccAWSSpotFleetRequest_lowestPriceAzInGivenList
=== RUN   TestAccAWSSpotFleetRequest_lowestPriceSubnetInGivenList
=== PAUSE TestAccAWSSpotFleetRequest_lowestPriceSubnetInGivenList
=== RUN   TestAccAWSSpotFleetRequest_multipleInstanceTypesInSameAz
=== PAUSE TestAccAWSSpotFleetRequest_multipleInstanceTypesInSameAz
=== RUN   TestAccAWSSpotFleetRequest_multipleInstanceTypesInSameSubnet
=== PAUSE TestAccAWSSpotFleetRequest_multipleInstanceTypesInSameSubnet
=== RUN   TestAccAWSSpotFleetRequest_overriddingSpotPrice
=== PAUSE TestAccAWSSpotFleetRequest_overriddingSpotPrice
=== RUN   TestAccAWSSpotFleetRequest_withoutSpotPrice
=== PAUSE TestAccAWSSpotFleetRequest_withoutSpotPrice
=== RUN   TestAccAWSSpotFleetRequest_diversifiedAllocation
=== PAUSE TestAccAWSSpotFleetRequest_diversifiedAllocation
=== RUN   TestAccAWSSpotFleetRequest_multipleInstancePools
=== PAUSE TestAccAWSSpotFleetRequest_multipleInstancePools
=== RUN   TestAccAWSSpotFleetRequest_withWeightedCapacity
=== PAUSE TestAccAWSSpotFleetRequest_withWeightedCapacity
=== RUN   TestAccAWSSpotFleetRequest_withEBSDisk
=== PAUSE TestAccAWSSpotFleetRequest_withEBSDisk
=== RUN   TestAccAWSSpotFleetRequest_LaunchSpecification_EbsBlockDevice_KmsKeyId
=== PAUSE TestAccAWSSpotFleetRequest_LaunchSpecification_EbsBlockDevice_KmsKeyId
=== RUN   TestAccAWSSpotFleetRequest_LaunchSpecification_RootBlockDevice_KmsKeyId
=== PAUSE TestAccAWSSpotFleetRequest_LaunchSpecification_RootBlockDevice_KmsKeyId
=== RUN   TestAccAWSSpotFleetRequest_withTags
=== PAUSE TestAccAWSSpotFleetRequest_withTags
=== RUN   TestAccAWSSpotFleetRequest_placementTenancyAndGroup
=== PAUSE TestAccAWSSpotFleetRequest_placementTenancyAndGroup
=== RUN   TestAccAWSSpotFleetRequest_WithELBs
=== PAUSE TestAccAWSSpotFleetRequest_WithELBs
=== RUN   TestAccAWSSpotFleetRequest_WithTargetGroups
=== PAUSE TestAccAWSSpotFleetRequest_WithTargetGroups
=== CONT  TestAccAWSSpotFleetRequest_basic
=== CONT  TestAccAWSSpotFleetRequest_multipleInstanceTypesInSameSubnet
=== CONT  TestAccAWSSpotFleetRequest_overriddingSpotPrice
=== CONT  TestAccAWSSpotFleetRequest_WithTargetGroups
=== CONT  TestAccAWSSpotFleetRequest_WithELBs
=== CONT  TestAccAWSSpotFleetRequest_placementTenancyAndGroup
=== CONT  TestAccAWSSpotFleetRequest_withTags
=== CONT  TestAccAWSSpotFleetRequest_LaunchSpecification_RootBlockDevice_KmsKeyId
=== CONT  TestAccAWSSpotFleetRequest_LaunchSpecification_EbsBlockDevice_KmsKeyId
=== CONT  TestAccAWSSpotFleetRequest_withEBSDisk
=== CONT  TestAccAWSSpotFleetRequest_withWeightedCapacity
=== CONT  TestAccAWSSpotFleetRequest_multipleInstancePools
=== CONT  TestAccAWSSpotFleetRequest_diversifiedAllocation
=== CONT  TestAccAWSSpotFleetRequest_updateTargetCapacity
=== CONT  TestAccAWSSpotFleetRequest_multipleInstanceTypesInSameAz
=== CONT  TestAccAWSSpotFleetRequest_lowestPriceSubnetInGivenList
=== CONT  TestAccAWSSpotFleetRequest_lowestPriceAzInGivenList
=== CONT  TestAccAWSSpotFleetRequest_lowestPriceAzOrSubnetInRegion
=== CONT  TestAccAWSSpotFleetRequest_changePriceForcesNewRequest
=== CONT  TestAccAWSSpotFleetRequest_withoutSpotPrice
--- PASS: TestAccAWSSpotFleetRequest_placementTenancyAndGroup (78.75s)
=== CONT  TestAccAWSSpotFleetRequest_updateExcessCapacityTerminationPolicy
--- PASS: TestAccAWSSpotFleetRequest_LaunchSpecification_EbsBlockDevice_KmsKeyId (160.24s)
=== CONT  TestAccAWSSpotFleetRequest_fleetType
--- PASS: TestAccAWSSpotFleetRequest_LaunchSpecification_RootBlockDevice_KmsKeyId (161.63s)
=== CONT  TestAccAWSSpotFleetRequest_associatePublicIpAddress
--- PASS: TestAccAWSSpotFleetRequest_lowestPriceSubnetInGivenList (274.85s)
=== CONT  TestAccAWSSpotFleetRequest_iamInstanceProfileArn
--- PASS: TestAccAWSSpotFleetRequest_multipleInstanceTypesInSameSubnet (274.91s)
=== CONT  TestAccAWSSpotFleetRequest_instanceInterruptionBehavior
--- PASS: TestAccAWSSpotFleetRequest_WithELBs (320.21s)
--- PASS: TestAccAWSSpotFleetRequest_lowestPriceAzOrSubnetInRegion (332.26s)
--- PASS: TestAccAWSSpotFleetRequest_withWeightedCapacity (334.06s)
--- PASS: TestAccAWSSpotFleetRequest_withoutSpotPrice (335.68s)
--- PASS: TestAccAWSSpotFleetRequest_withTags (337.31s)
--- PASS: TestAccAWSSpotFleetRequest_diversifiedAllocation (406.59s)
--- PASS: TestAccAWSSpotFleetRequest_fleetType (249.62s)
--- PASS: TestAccAWSSpotFleetRequest_associatePublicIpAddress (250.12s)
--- PASS: TestAccAWSSpotFleetRequest_withEBSDisk (413.81s)
--- PASS: TestAccAWSSpotFleetRequest_overriddingSpotPrice (414.89s)    
--- PASS: TestAccAWSSpotFleetRequest_changePriceForcesNewRequest (465.94s)
--- PASS: TestAccAWSSpotFleetRequest_WithTargetGroups (451.52s)
--- PASS: TestAccAWSSpotFleetRequest_multipleInstancePools (477.37s)
--- PASS: TestAccAWSSpotFleetRequest_lowestPriceAzInGivenList (479.62s)
--- PASS: TestAccAWSSpotFleetRequest_multipleInstanceTypesInSameAz (480.14s)
--- PASS: TestAccAWSSpotFleetRequest_basic (487.09s)
--- PASS: TestAccAWSSpotFleetRequest_iamInstanceProfileArn (267.28s)
--- PASS: TestAccAWSSpotFleetRequest_updateExcessCapacityTerminationPolicy (465.85s)
--- PASS: TestAccAWSSpotFleetRequest_instanceInterruptionBehavior (270.67s)
--- PASS: TestAccAWSSpotFleetRequest_updateTargetCapacity (882.71s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       883.867s
```

### CODE REVIEW

File: aws/resource_aws_spot_fleet_request_test.go [hunk 1]
```diff
@@ -620,7 +620,7 @@ func TestAccAWSSpotFleetRequest_withTags(t *testing.T) {
 	})
 }
 
-func TestAccAWSSpotFleetRequest_placementTenancy(t *testing.T) {
+func TestAccAWSSpotFleetRequest_placementTenancyAndGroup(t *testing.T) {
```
Comment (bflad) [inline aws/resource_aws_spot_fleet_request_test.go]: Nit: It is generally preferable to create new testing rather than modify existing tests to ensure we do not introduce regressions (even if it is very verbose to do so). 👍
