### PR TITLE
fix tagging for default route table

### LINKED ISSUE #12839: aws_default_route_table doesn't apply tags at initial apply
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.24
+ provider.aws v2.57.0

### Affected Resource(s)

aws_default_route_table

### Terraform Configuration Files

N/A

### Debug Output

terraform_debug-1stApply.log
terraform_debug-2ndApply.log

https://gist.github.com/nibrahv/4d10a417ab65f7efe967c48603c0e449

### Panic Output

N/A

### Expected Behavior

Provisioning new AWS VPC and using "aws_default_route_table" resource to identify default route table created during VPC creation.  Expectation is to set "Name" and other tags during "terraform apply".  

### Actual Behavior

Initial "terraform apply" completes without error, however no tags are set on the default route table resource.  When running "apply" a second time, it identifies the missing tags and sets them appropriately:

(Terraform output)
Terraform will perform the following actions:

  # aws_default_route_table.rtb_VMC will be updated in-place
  ~ resource "aws_default_route_table" "rtb_VMC" {
        default_route_table_id = "rtb-027da73bf0fd77b78"
        id                     = "rtb-027da73bf0fd77b78"
        owner_id               = "############"
        propagating_vgws       = []
        route                  = []
      ~ tags                   = {
          + "Name" = "rtb_VMC"
          + "foo"  = "bar"
          + "foo1" = "1bar"
          + "foo2" = "2bar"
          + "foo3" = "3bar"
        }
        vpc_id                 = "vpc-0bafc004395a089ae"
    }

Plan: 0 to add, **1 to change**, 0 to destroy.
(Terraform output)

### Steps to Reproduce

Code:
resource "aws_vpc" "default_vmc_vpc" {
   cidr_block = "10.1.0.0/16"
}

resource "aws_default_route_table" "rtb_VMC" {
   default_route_table_id =  aws_vpc.default_vmc_vpc.default_route_table_id
   tags = {
      Name = "rtb_VMC"
      foo = "bar"
      foo1 = "1bar"
      foo2 = "2bar"
      foo3 = "3bar"
      }
}

1. `terraform apply`
(note missing tags in AWS management console)

2. 'terraform apply'
(note actions to perform in execution plan, "1 to change")

### Important Factoids

OS: CentOS Linux release 7.7.1908 

### References

N/A

* #0000

### PR DESCRIPTION
**Pull request by DrFaust92**
+ add plan time validation

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #12839

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource_aws_route_table: add plan time validation to `cidr_block` and `ipv6_cidr_block`
resource_aws_default_route_table: add plan time validation to `cidr_block` and `ipv6_cidr_block`
resource_aws_default_route_table: fix tag on create
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSDefaultRouteTable_'
--- PASS: TestAccAWSDefaultRouteTable_disappears_Vpc (40.32s)
--- PASS: TestAccAWSDefaultRouteTable_Route (168.88s)
--- PASS: TestAccAWSDefaultRouteTable_swap (137.80s)
--- PASS: TestAccAWSDefaultRouteTable_Route_TransitGatewayID (319.80s)
--- PASS: TestAccAWSDefaultRouteTable_vpc_endpoint (89.90s)
--- PASS: TestAccAWSDefaultRouteTable_tags (153.86s)
```

```
$ make testacc TESTARGS='-run=TestAccAWSRouteTable_'
--- PASS: TestAccAWSRouteTable_basic (147.88s)
--- PASS: TestAccAWSRouteTable_instance (187.01s)
--- PASS: TestAccAWSRouteTable_tags (115.74s)
--- PASS: TestAccAWSRouteTable_panicEmptyRoute (46.56s)
--- PASS: TestAccAWSRouteTable_Route_ConfigMode (201.41s)
--- PASS: TestAccAWSRouteTable_Route_TransitGatewayID (389.70s)
--- PASS: TestAccAWSRouteTable_vgwRoutePropagation (97.22s)

both of these failed because i lack permissions to run these
--- FAIL: TestAccAWSRouteTable_ipv6 (40.87s)
--- FAIL: TestAccAWSRouteTable_vpcPeering (59.77s)
```

### CODE REVIEW

File: aws/resource_aws_default_route_table_test.go [hunk 1]
```diff
@@ -455,39 +498,82 @@ resource "aws_default_route_table" "test" {
...
 }
 
 resource "aws_vpc_endpoint" "s3" {
-    vpc_id = "${aws_vpc.test.id}"
-    service_name = "com.amazonaws.us-west-2.s3"
-    route_table_ids = [
-        "${aws_vpc.test.default_route_table_id}"
-    ]
+    vpc_id          = "${aws_vpc.test.id}"
+    service_name    = "com.amazonaws.us-west-2.s3"
```
Comment (ewbankkit) [inline aws/resource_aws_default_route_table_test.go:518]: Can you make this test region independent using the [`aws_region`](https://www.terraform.io/docs/providers/aws/d/region.html) data source?

Comment (DrFaust92) [reply aws/resource_aws_default_route_table_test.go:518]: good catch, i was thinking about it and forgot when commiting

Comment (DrFaust92) [reply aws/resource_aws_default_route_table_test.go]: done

**Comment by ewbankkit** [comment]
Verified acceptance tests (in non-default region):

```console
$ AWS_DEFAULT_REGION=eu-west-1 make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSDefaultRouteTable_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -count 1 -parallel 3 -run=TestAccAWSDefaultRouteTable_ -timeout 120m
=== RUN   TestAccAWSDefaultRouteTable_basic
=== PAUSE TestAccAWSDefaultRouteTable_basic
=== RUN   TestAccAWSDefaultRouteTable_disappears_Vpc
=== PAUSE TestAccAWSDefaultRouteTable_disappears_Vpc
=== RUN   TestAccAWSDefaultRouteTable_Route
=== PAUSE TestAccAWSDefaultRouteTable_Route
=== RUN   TestAccAWSDefaultRouteTable_swap
=== PAUSE TestAccAWSDefaultRouteTable_swap
=== RUN   TestAccAWSDefaultRouteTable_Route_TransitGatewayID
=== PAUSE TestAccAWSDefaultRouteTable_Route_TransitGatewayID
=== RUN   TestAccAWSDefaultRouteTable_vpc_endpoint
=== PAUSE TestAccAWSDefaultRouteTable_vpc_endpoint
=== RUN   TestAccAWSDefaultRouteTable_tags
=== PAUSE TestAccAWSDefaultRouteTable_tags
=== CONT  TestAccAWSDefaultRouteTable_basic
=== CONT  TestAccAWSDefaultRouteTable_Route_TransitGatewayID
=== CONT  TestAccAWSDefaultRouteTable_tags
--- PASS: TestAccAWSDefaultRouteTable_basic (51.74s)
=== CONT  TestAccAWSDefaultRouteTable_vpc_endpoint
--- PASS: TestAccAWSDefaultRouteTable_tags (87.83s)
=== CONT  TestAccAWSDefaultRouteTable_Route
--- PASS: TestAccAWSDefaultRouteTable_vpc_endpoint (60.64s)
=== CONT  TestAccAWSDefaultRouteTable_swap
--- PASS: TestAccAWSDefaultRouteTable_Route (101.34s)
=== CONT  TestAccAWSDefaultRouteTable_disappears_Vpc
--- PASS: TestAccAWSDefaultRouteTable_swap (81.21s)
--- PASS: TestAccAWSDefaultRouteTable_disappears_Vpc (24.97s)
--- PASS: TestAccAWSDefaultRouteTable_Route_TransitGatewayID (328.26s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	328.326s
```

File: aws/resource_aws_route_table_test.go [hunk 2]
```diff
@@ -252,9 +251,9 @@ func TestAccAWSRouteTable_tags(t *testing.T) {
 			{
 				Config: testAccRouteTableConfigTags,
 				Check: resource.ComposeTestCheckFunc(
-					testAccCheckRouteTableExists(resourceName, &route_table),
+					testAccCheckRouteTableExists(resourceName, &routeTable),
 					resource.TestCheckResourceAttr(resourceName, "tags.%", "1"),
-					resource.TestCheckResourceAttr(resourceName, "tags.foo", "bar"),
+					resource.TestCheckResourceAttr(resourceName, "tags.test", "bar"),
```
Comment (bflad) [inline aws/resource_aws_route_table_test.go:256]: It appears the test configuration wasn't changed here:

```
--- FAIL: TestAccAWSRouteTable_tags (33.75s)
testing.go:669: Step 0 error: Check failed: Check 3/3 error: aws_route_table.test: Attribute 'tags.test' not found
```

```suggestion
					resource.TestCheckResourceAttr(resourceName, "tags.foo", "bar"),
```

Comment (DrFaust92) [reply aws/resource_aws_route_table_test.go]: fixed
