### PR TITLE
resource/rds_cluster: update delete timeout and add additional retry condition

### LINKED ISSUE #13126: Error Destroying Aurora Global Cluster with Primary and Secondary Regional Clusters
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.24

### Affected Resource(s)

* aws__rds_global_cluster

### Terraform Configuration Files

```hcl
resource "aws_rds_global_cluster" "global" {
  provider                  = aws.pri
  global_cluster_identifier = "test-cluster"
```

### Actual Behavior

Aurora Global Clusters with one regional cluster work fine with changes from #12499. They can be created and destroyed, but a global cluster is created with primary and secondary regional clusters the error from #12499 persists: 

```
* aws_rds_cluster.this: error deleting RDS Cluster (dbtfmodules-aurora-mysql-global-test-secondary): InvalidDBClusterStateFault: This cluster is a part of a global cluster, please remove it from globalcluster first
	status code: 400, request id: fc9e7a36-b486-4f0b-8418-3a81de125289
```
### Steps to Reproduce

After trying and failing the first `destroy`, a second`destroy` works as expected. 
### Important Factoids

In the destroy debug.log, the secondary cluster was removed from the global cluster (RemoveFromGlobalCluster request) and then tried to DeleteDBCluster and resulted in error.

The time between this two requests is very short and maybe the unlink is not applied when it performs the DeleteDBCluster request. 

Using either like waitForState  function to detect the cluster is unlinked  or something like thread.Sleep could potentially fix the issue.

### References

* #12499

### PR DESCRIPTION
**Pull request by anGie44**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #13126

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/rds_cluster: update delete timeout and add additional retry condition
```

Output from acceptance testing:

```
--- PASS: TestAccAWSRDSCluster_MultipleClustersInGlobalCluster (1828.70s) 😨 
```

### CODE REVIEW

File: aws/resource_aws_rds_cluster_test.go [hunk 1]
```diff
@@ -3518,3 +3545,105 @@ resource "aws_rds_cluster" "test" {
...
+func testAccAWSRDSClusterConfig_MultipleClustersInGlobalCluster(rNamePrimary, rNameSecondary, rNameGlobal string) string {
+	return fmt.Sprintf(`
+provider "aws" {
+  region = "us-west-2"
+}
+
+provider "aws" {
+  alias  = "alternate"
+  region = "us-east-2"
+}
```
Comment (anGie44) [inline aws/resource_aws_rds_cluster_test.go:3558]: needs re-working

**Comment by bflad** [comment]
(If you see awsproviderlint failures, I _just_ fixed it on master)

File: aws/resource_aws_rds_cluster_test.go [hunk 2]
```diff
@@ -3518,3 +3546,100 @@ resource "aws_rds_cluster" "test" {
...
+
+resource "aws_rds_cluster" "primary" {
+  cluster_identifier              = "%[2]s"
+  database_name                   = "mydb"
+  master_username                 = "foo"
+  master_password                 = "barbarbar"
+  skip_final_snapshot             = true
+  global_cluster_identifier       = aws_rds_global_cluster.test.id
+  engine                          = "aurora-mysql"
+  engine_version                  = "5.7.mysql_aurora.2.07.1"
```
Comment (bflad) [inline aws/resource_aws_rds_cluster_test.go:3580]: Nit: Might simplify maintenance down the road to reference these from the `aws_rds_global_cluster` resource directly.

```suggestion
  engine                          = aws_rds_global_cluster.test.engine
  engine_version                  = aws_rds_global_cluster.test.engine_version
```

Similarly with all the hardcoded ones below as well, e.g. switching the instance below to reference `aws_rds_cluster.primary.engine` etc. 👍

File: aws/resource_aws_rds_cluster_test.go [hunk 3]
```diff
@@ -3518,3 +3546,100 @@ resource "aws_rds_cluster" "test" {
...
+  global_cluster_identifier     = aws_rds_global_cluster.test.id
+  engine                        = "aurora-mysql"
+  engine_version                = "5.7.mysql_aurora.2.07.1"
+  depends_on                    = [aws_rds_cluster_instance.primary]
+
+  lifecycle {
+    ignore_changes = [
+      replication_source_identifier,
+    ]
+  }
```
Comment (bflad) [inline aws/resource_aws_rds_cluster_test.go:3633]: I'm curious about this, is the API automatically adding it? 😄  If so, we may want to mark it as `Computed: true` in a separate change.

File: aws/resource_aws_rds_cluster_test.go (hunk 2 above)
Comment (anGie44) [reply aws/resource_aws_rds_cluster_test.go:3580]: yes totally agree! forgot these references make things so much easier 😅

File: aws/resource_aws_rds_cluster_test.go (hunk 3 above)
Comment (anGie44) [reply aws/resource_aws_rds_cluster_test.go:3633]: in the original issue's description, i didn't see a workaround to this behavior so i thought maybe the test configuration is a little off? took me a bit of experimenting to get the right combination of primary/secondary rds_clusters 😅

Comment (bflad) [reply aws/resource_aws_rds_cluster_test.go:3633]: Interesting! For what its worth, I think we're going to mark `global_cluster_identifier` as `Computed: true` anyways for https://github.com/terraform-providers/terraform-provider-aws/issues/10965

Comment (anGie44) [reply aws/resource_aws_rds_cluster_test.go:3633]: nice, that issue def looks similar to what i ran into here

Comment (anGie44) [reply aws/resource_aws_rds_cluster_test.go]: ah looks like there's already an issue related to this block: https://github.com/terraform-providers/terraform-provider-aws/issues/10150

**Comment by anGie44** [comment]
ready for re-review/test run 👍
