### PR TITLE
d/aws_kms_alias: Add target_key_arn attribute

### LINKED ISSUE #2009: Support ARNs for existing KMS keys
There is currently no way to directly retrieve an ARN for a pre-existing KMS Key. This makes it difficult / unnecessarily complicated to assign existing KMS keys to newly created resources.

### Terraform Version
0.10.7

### Affected Resource(s)
- `aws_kms_alias`
- `aws_lambda_function`
- Any resource which accepts a `kms_key_arn` argument

### Terraform Configuration Files
```hcl
data "aws_kms_alias" "existing_cmk" {                                                                                                                                                                         
  name = "alias/MyPreExistingKey"                                                                                                                                                                        
}

resource "aws_lambda_function" "new_function" {
  /* other arguments ommitted */
  kms_key_arn = "${data.aws_kms_alias.existing_cmk.arn}"
}  
```
### Expected Behavior
The newly created Lambda function would have the `MyPreExisting` KMS key set.

### Actual Behavior
The Lambda function gets assigned either no KMS key, or the default `aws/lambda` key.

### Important Factoids
After failing to have the expected KMS key assigned, I looked at the plan output and saw that the value of `${data.aws_kms_alias.existing_cmk.arn}` was in the format of 

```arn:aws:kms:eu-west-1:123456789012:alias/MyExistingKey```

This is the ARN of the alias, not the key itself, which are seemingly not analogous. Logically this makes sense, but as there is no `aws_kms_key` data provider, there is no way to directly retrieve an ARN for an existing key.

You *can* indirectly solve this by using some substitution, but it would be nice not to have to do this:

```hcl
locals {                                                                                                                                                                                                    
  kms_arn = "${replace(data.aws_kms_alias.existing_cmk.arn, data.aws_kms_alias.existing_cmk.name, "key/${data.aws_kms_alias.existing_cmk.target_key_id}")}"                                                       
}  
```

### PR DESCRIPTION
**Pull request by bflad**
This is an alternate implementation to #2224. Closes #2009. 

KMS keys and aliases are bound to the same AWS partition, account, and region so it is safe to assemble the target key ARN from the alias ARN and target key ID. Reference: http://docs.aws.amazon.com/sdk-for-go/api/service/kms/#KMS.CreateAlias

> The alias and the CMK it is mapped to must be in the same AWS account and the same region. You cannot perform this operation on an alias in a different AWS account.

```
make testacc TEST=./aws TESTARGS='-run=TestAccDataSourceAwsKmsAlias'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccDataSourceAwsKmsAlias -timeout 120m
=== RUN   TestAccDataSourceAwsKmsAlias
--- PASS: TestAccDataSourceAwsKmsAlias (41.76s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	41.791s
```

### CODE REVIEW

File: aws/data_source_aws_kms_alias_test.go [hunk 1]
```diff
@@ -47,6 +48,19 @@ func testAccDataSourceAwsKmsAliasCheck(name string) resource.TestCheckFunc {
...
+			kmsKeyRs.Primary.Attributes["name"],
+			fmt.Sprintf("key/%s", kmsKeyRs.Primary.Attributes["target_key_id"]),
+			1)
+		if attr["target_key_arn"] != targetKeyArn {
+			return fmt.Errorf(
+				"target_key_arn is %s; want %s",
+				attr["target_key_arn"],
+				targetKeyArn,
+			)
+		}
```
Comment (radeksimko) [inline aws/data_source_aws_kms_alias_test.go]: How do you feel about `regexp` matching with `$` here? It seems that would be a little bit cleaner approach compared to modification of the original attribute.

Comment (starlton-eb) [reply aws/data_source_aws_kms_alias_test.go]: This would be awesome to have right now. I racked by brain all day wondering why my aws_efs_file_system instances were being recreated and discovered that it was due to a recent update to our stack that includes looking up a kms key:

**Comment by bflad** [comment]
I'll update and merge this PR after we release v1.7.1 (hopefully tomorrow). 🚀

**Comment by bflad** [comment]
Rebased and updated if you'd like to give another look
```
make testacc TEST=./aws TESTARGS='-run=TestAccDataSourceAwsKmsAlias'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccDataSourceAwsKmsAlias -timeout 120m
=== RUN   TestAccDataSourceAwsKmsAlias
--- PASS: TestAccDataSourceAwsKmsAlias (40.72s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	40.769s
```

**Comment by ColinHebert** [comment]
Helps/fixes #3019

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.8.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#180-january-29-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
