### PR TITLE
AWS Workspaces fix for issue 13558

### LINKED ISSUE #13558: aws_workspaces_workspace can't apply with "ALWAYS_ON" running_mode
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.13
+ provider.aws v2.63.0

### Affected Resource(s)

* aws_workspaces_workspace

### Terraform Configuration Files

```hcl
data "aws_workspaces_directory" "directory" {}

resource "aws_workspaces_workspace" "workspace" {
  directory_id = data.aws_workspaces_directory.directory.id
  bundle_id    = "wsb-bh8rsxt14" # Value with Windows 10 (English)
  user_name    = "test.user"

  root_volume_encryption_enabled = true
  user_volume_encryption_enabled = true
  volume_encryption_key          = "aws/workspaces"

  workspace_properties {
    compute_type_name                         = "VALUE"
    root_volume_size_gib                      = 80
    user_volume_size_gib                      = 175
    running_mode                              = "ALWAYS_ON"
    // running_mode_auto_stop_timeout_in_minutes NOT set
  }
}
```

### Expected Behavior

Workspace is deployed with `ALWAYS_ON` running mode.
### Actual Behavior

Workspace fails apply because `running_mode_auto_stop_timeout_in_minutes` is always computed, even when not configured.

```hcl
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_workspaces_workspace.workspace will be created
  + resource "aws_workspaces_workspace" "workspace" {
      + bundle_id                      = "wsb-bh8rsxt14"
      + computer_name                  = (known after apply)
      + directory_id                   = "<directory_id>"
      + id                             = (known after apply)
      + ip_address                     = (known after apply)
      + root_volume_encryption_enabled = true
      + state                          = (known after apply)
      + user_name                      = "test.user"
      + user_volume_encryption_enabled = true
      + volume_encryption_key          = "aws/workspaces"

      + workspace_properties {
          + compute_type_name                         = "VALUE"
          + root_volume_size_gib                      = 80
          + running_mode                              = "ALWAYS_ON"
   ---->  + running_mode_auto_stop_timeout_in_minutes = (known after apply) <----
          + user_volume_size_gib                      = 175
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_workspaces_workspace.workspace: Creating...

Error: workspace creation failed: RunningModeAutoStopTimeoutInMinutes is not applicable for WorkSpace with running mode set to ALWAYS_ON

  on main.tf line 32, in resource "aws_workspaces_workspace" "workspace":
  32: resource "aws_workspaces_workspace" "workspace" {
```
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### PR DESCRIPTION
**Pull request by ianbinder**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #13558

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```
This is my first submission to any project, ever. Please forgive sloppiness. I appreciate any feedback. I just made some small changes to the existing document to allow workspaces with the ALWAYS_ON to be created and updated. These changes include skipping updating the running_mode_auto_stop_timeout_in_minutes property if the running_mode is set to ALWAYS_ON and removing running_mode_auto_stop_timeout_in_minutes from the extended properties used in creation if the running_mode is set to ALWAYS_ON.

```

Test results:

ian@UbuntuNUC:~/development/terraform-providers/terraform-provider-aws$ make testacc TEST=./aws TESTARGS='-run=TestAccAwsWorkspacesWorkspace*'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsWorkspacesWorkspace* -timeout 120m
=== RUN   TestAccAwsWorkspacesWorkspace_basic
=== PAUSE TestAccAwsWorkspacesWorkspace_basic
=== RUN   TestAccAwsWorkspacesWorkspace_tags
=== PAUSE TestAccAwsWorkspacesWorkspace_tags
=== RUN   TestAccAwsWorkspacesWorkspace_workspaceProperties
=== PAUSE TestAccAwsWorkspacesWorkspace_workspaceProperties
=== RUN   TestAccAwsWorkspacesWorkspace_validateRootVolumeSize
=== PAUSE TestAccAwsWorkspacesWorkspace_validateRootVolumeSize
=== RUN   TestAccAwsWorkspacesWorkspace_validateUserVolumeSize
=== PAUSE TestAccAwsWorkspacesWorkspace_validateUserVolumeSize
=== CONT  TestAccAwsWorkspacesWorkspace_basic
=== CONT  TestAccAwsWorkspacesWorkspace_validateRootVolumeSize
=== CONT  TestAccAwsWorkspacesWorkspace_workspaceProperties
=== CONT  TestAccAwsWorkspacesWorkspace_validateUserVolumeSize
=== CONT  TestAccAwsWorkspacesWorkspace_tags
--- PASS: TestAccAwsWorkspacesWorkspace_validateRootVolumeSize (2.83s)
--- PASS: TestAccAwsWorkspacesWorkspace_validateUserVolumeSize (2.84s)
--- PASS: TestAccAwsWorkspacesWorkspace_tags (1820.33s)
--- PASS: TestAccAwsWorkspacesWorkspace_basic (1833.78s)
--- PASS: TestAccAwsWorkspacesWorkspace_workspaceProperties (1928.77s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	1928.844s

### CODE REVIEW

**Comment by cwebster2** [comment]
Any word on when this will be merged?  Just ran into this bug and is blocking our use of terraform to manage workspaces.

File: aws/resource_aws_workspaces_workspace.go [hunk 1]
```diff
@@ -366,12 +366,21 @@ func expandWorkspaceProperties(properties []interface{}) *workspaces.WorkspacePr
...
+			UserVolumeSizeGib: aws.Int64(int64(p["user_volume_size_gib"].(int))),
+		}
+	} else {
+		return &workspaces.WorkspaceProperties{
+			ComputeTypeName:                     aws.String(p["compute_type_name"].(string)),
+			RootVolumeSizeGib:                   aws.Int64(int64(p["root_volume_size_gib"].(int))),
+			RunningMode:                         aws.String(p["running_mode"].(string)),
+			RunningModeAutoStopTimeoutInMinutes: aws.Int64(int64(p["running_mode_auto_stop_timeout_in_minutes"].(int))),
+			UserVolumeSizeGib:                   aws.Int64(int64(p["user_volume_size_gib"].(int))),
+		}
```
Comment (anGie44) [inline aws/resource_aws_workspaces_workspace.go:383]: Nit: since both conditions set similar attributes in the `WorkspacesProperties` object, we could initialize the object first and then run through the if/else logic e.g.
```suggestion
        workspaceProperties := &workspaces.WorkspaceProperties{
			ComputeTypeName:   aws.String(p["compute_type_name"].(string)),
			RootVolumeSizeGib: aws.Int64(int64(p["root_volume_size_gib"].(int))),
			RunningMode:       aws.String(p["running_mode"].(string)),
			UserVolumeSizeGib: aws.Int64(int64(p["user_volume_size_gib"].(int))),
	}
	if p["running_mode"] == workspaces.RunningModeAlwaysOn {
	    workspaceProperties.RunningModeAutoStopTimeoutInMinutes = aws.Int64(int64(p["running_mode_auto_stop_timeout_in_minutes"].(int)))
        }
```

**Comment by anGie44** [comment]
Hi @ianbinder 👋 thanks again for this PR! Just dropping a note here that I've added a commit to continue the work here, as our general response time from community PRs is 2 weeks, and hope to get these changes into an upcoming release of the provider :) if you have any questions, please let us know!

**Comment by anGie44** [comment]
Output of new acceptance test:
```
--- PASS: TestAccAwsWorkspacesWorkspace_workspaceProperties_runningModeAlwaysOn (1824.24s)
```

**Comment by ianbinder** [comment]
Sorry that I didn't get back to you sooner; a bit busy at work here. Thanks
for taking care of this. I am just excited to start using the feature. I
appreciate all of the work you guys do.

**Comment by anGie44** [comment]
Related: https://github.com/terraform-providers/terraform-provider-aws/issues/14950
