### PR TITLE
resource/aws_sqs_queue: Skip SQS ListQueueTags in aws-us-gov partition

### LINKED ISSUE #2534: SQS queues in govcloud don't support ListQueueTags
Hi there,

### Terraform Version

Terraform v0.11.1
+ provider.aws v1.5.0
+ provider.consul v1.0.0
+ provider.nomad v1.0.0
+ provider.template v1.0.0
+ provider.vault v1.0.0

### Affected Resource(s)
aws_sqs_queue

### Debug Output
Here's the super truncated version from the debug log.
https://gist.github.com/dotspec/d6663e4b7bc34690b9c037fba361fa8c

### Expected Behavior
What should have happened?

The plan should execute successfully.

### Actual Behavior
Like a lot of things in govcloud the SQS endpoint is lagging behind and queues in govcloud don't yet support tags causing any run with this resource to error.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

1) Create an aws_sqs_queue resource with the aws provider pointing to us-gov-west-1
2) 'terraform plan'
3) Sadness

### Important Factoids
Pinning my AWS provider version to 1.1.0 gets me past the error.

### PR DESCRIPTION
**Pull request by bflad**
Closes #2534 It seems there are other eventual consistency issues in us-gov-west-1 (we are correctly calling SetQueueAttributes), but this at least allows the resource to be usable for folks.

Previously:
```
 make testacc TEST=./aws TESTARGS='-run=TestAccAWSSQSQueue_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSSQSQueue_basic -timeout 120m
=== RUN   TestAccAWSSQSQueue_basic
--- FAIL: TestAccAWSSQSQueue_basic (9.42s)
	testing.go:513: Step 0 error: Error applying: 1 error(s) occurred:

		* aws_sqs_queue.queue: 1 error(s) occurred:

		* aws_sqs_queue.queue: InvalidAction: The action ListQueueTags is not valid for this endpoint.
			status code: 400, request id: dd0b3da4-12e0-51c8-82d6-6f5a40467820
```

```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSSQSQueue_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSSQSQueue_basic -timeout 120m
=== RUN   TestAccAWSSQSQueue_basic
--- FAIL: TestAccAWSSQSQueue_basic (29.12s)
	testing.go:513: Step 1 error: After applying this step, the plan was not empty:

		DIFF:

		UPDATE: aws_sqs_queue.queue
		  delay_seconds:              "0" => "90"
		  max_message_size:           "262144" => "2048"
		  message_retention_seconds:  "345600" => "86400"
		  receive_wait_time_seconds:  "0" => "10"
		  visibility_timeout_seconds: "30" => "60"
```

### CODE REVIEW

File: aws/resource_aws_sqs_queue.go [hunk 1]
```diff
@@ -311,13 +311,17 @@ func resourceAwsSqsQueueRead(d *schema.ResourceData, meta interface{}) error {
 	d.Set("fifo_queue", d.Get("fifo_queue").(bool))
 	d.Set("content_based_deduplication", d.Get("content_based_deduplication").(bool))
 
-	listTagsOutput, err := sqsconn.ListQueueTags(&sqs.ListQueueTagsInput{
-		QueueUrl: aws.String(d.Id()),
-	})
-	if err != nil {
-		return err
+	tags := make(map[string]string)
+	if !meta.(*AWSClient).IsGovCloud() {
```
Comment (radeksimko) [inline aws/resource_aws_sqs_queue.go]: Nitpick: You could cast `meta` once and then use `client.sqsconn` above and `client.IsGovCloud()` here, totally no big deal though. 👌

File: aws/resource_aws_sqs_queue.go [hunk 2]
```diff
@@ -311,13 +311,17 @@ func resourceAwsSqsQueueRead(d *schema.ResourceData, meta interface{}) error {
...
+		listTagsOutput, err := sqsconn.ListQueueTags(&sqs.ListQueueTagsInput{
+			QueueUrl: aws.String(d.Id()),
+		})
+		if err != nil {
+			return err
+		}
+		tags = tagsToMapGeneric(listTagsOutput.Tags)
 	}
-	d.Set("tags", tagsToMapGeneric(listTagsOutput.Tags))
+	d.Set("tags", tags)
```
Comment (radeksimko) [inline aws/resource_aws_sqs_queue.go]: I would argue we probably shouldn't be setting tags at all in such case, is there any reason to do that?

**Comment by bflad** [comment]
This has been released in [version 1.10.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1100-february-24-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
