### PR TITLE
resource/security_group: fix rule gathering with description included

### LINKED ISSUE #2018: terraform plan incorrectly wants to blank a security group ingress description
### Terraform Version

> Terraform v0.10.7
> `2017/10/23 11:52:51 [DEBUG] found provider "terraform-provider-aws_v1.1.0_x4"`

If I knew how to use a `master` build of this provider, I would report if this has been fixed since 1.1.0

### Affected Resource(s)
* `aws_security_group` (specifically an `ingress` block)

### Terraform Configuration Files

```hcl
resource "aws_security_group" "jenkins-sg" {
  name        = "jenkins-sg"
  description = "SG for jenkins"
  vpc_id      = "${var.vpc_id}"

  ingress {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["10.2.0.0/16"]
  }

  ingress {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    description = "blah blah message"
    cidr_blocks = ["10.5.0.0/16"]
  }

  ingress {
    from_port   = 8080
    to_port     = 8080
    protocol    = "tcp"
    cidr_blocks = ["10.2.0.0/16", "10.4.0.0/16"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags {
    Name = "jenkins-sg"
  }
}
```

### Debug Output

I'll be glad to create a gist of the entire run, but I would have to scrub it, so I would only want to do that if this plan output -- which I feel is very clear, when taken with the AWS EC2 api response -- isn't sufficient

In the following output, I moved the `426799852` creation text next to its `1365611918` destruction text to make that relationship more obvious; the `3854841948` "copy" action at the bottom is **correct**, it's the `ingress.1365611918.description` change that is wrong -- the EC2 `IpRange` "10.2.0.0/16" has no description to begin with, and thus does not need it blanked

```
  ~ module.jenkins.aws_security_group.jenkins-sg
      ingress.1365611918.cidr_blocks.#:      "1" => "0"
      ingress.1365611918.cidr_blocks.0:      "10.2.0.0/16" => ""
      ingress.1365611918.description:        "blah blah message" => ""
      ingress.1365611918.from_port:          "22" => "0"
      ingress.1365611918.ipv6_cidr_blocks.#: "0" => "0"
      ingress.1365611918.protocol:           "tcp" => ""
      ingress.1365611918.security_groups.#:  "0" => "0"
      ingress.1365611918.self:               "false" => "false"
      ingress.1365611918.to_port:            "22" => "0"

      ingress.426799852.cidr_blocks.#:       "0" => "1"
      ingress.426799852.cidr_blocks.0:       "" => "10.2.0.0/16"
      ingress.426799852.description:         "" => ""
      ingress.426799852.from_port:           "" => "22"
      ingress.426799852.ipv6_cidr_blocks.#:  "0" => "0"
      ingress.426799852.protocol:            "" => "tcp"
      ingress.426799852.security_groups.#:   "0" => "0"
      ingress.426799852.self:                "" => "false"
      ingress.426799852.to_port:             "" => "22"

      ingress.1706960236.cidr_blocks.#:      "2" => "2"
      ingress.1706960236.cidr_blocks.0:      "10.2.0.0/16" => "10.2.0.0/16"
      ingress.1706960236.cidr_blocks.1:      "10.4.0.0/16" => "10.4.0.0/16"
      ingress.1706960236.description:        "" => ""
      ingress.1706960236.from_port:          "8080" => "8080"
      ingress.1706960236.ipv6_cidr_blocks.#: "0" => "0"
      ingress.1706960236.protocol:           "tcp" => "tcp"
      ingress.1706960236.security_groups.#:  "0" => "0"
      ingress.1706960236.self:               "false" => "false"
      ingress.1706960236.to_port:            "8080" => "8080"

      ingress.3854841948.cidr_blocks.#:      "1" => "1"
      ingress.3854841948.cidr_blocks.0:      "10.5.0.0/16" => "10.5.0.0/16"
      ingress.3854841948.description:        "blah blah message" => "blah blah message"
      ingress.3854841948.from_port:          "22" => "22"
      ingress.3854841948.ipv6_cidr_blocks.#: "0" => "0"
      ingress.3854841948.protocol:           "tcp" => "tcp"
      ingress.3854841948.security_groups.#:  "0" => "0"
      ingress.3854841948.self:               "false" => "false"
      ingress.3854841948.to_port:            "22" => "22"
```

### Expected Behavior

The `plan` output should have indicated no changes required

### Actual Behavior

The `plan` output proposed modifying the security group, specifically its `ingress` block

### Steps to Reproduce

1. Create an AWS security group, `sg-abcdef`
1. In that SG, add an Inbound rule of Type SSH, Protocol TCP, Port Range 22, Source "10.2.0.0/16" with **no** Description
1. In that SG, add an Inbound rule of Type SSH, Protocol TCP, Port Range 22, Source "10.5.0.0/16" with a Description of "blah blah message"
1. Place the above HCL into `blah.tf`
1. Correctly configure your AWS provider, etc, etc
1. `terraform plan`

### Important Factoids

There are three interesting observations:

* modifying input `.tf`
* modifying `.tfstate` file
* observing the output from `ec2 describe-security-groups` (which 100% matches the `--debug` traffic from `terraform-provider-aws`)

First, I tried manually distinguishing where the `description` should go by splitting out the with-description ingress from the without-description ingress by creating two separate `resource "aws_security_group_rule" "jenkins-sg_10-5_22"` but it didn't help (and made the problem **much worse**)

Then, I thought maybe it was just a `.tfstate` problem, and updated the `attributes` block to correctly describe the `"description": "blah blah message",`, but this also did not help

The output from `aws ec2 describe-security-groups --filters 'Name=tag-value,Values=jenkins-sg'` demonstrates that AWS itself is rolling up those `ingress` blocks and pushing the `description` down onto the actual CIDR `IpRange`, whereas it seems `terraform-provider-aws` is erroneously recombining them at some step, resulting in a mismatch with the tfstate (and actual) situation

This is the output from that `describe-security-groups` and matches (as one might expect) the debug-level `<DescribeSecurityGroupsResponse` from AWS
```json
{
  "SecurityGroups": [
    {
      "IpPermissionsEgress": [
        {
          "IpProtocol": "-1",
          "PrefixListIds": [],
          "IpRanges": [
            {
              "CidrIp": "0.0.0.0/0"
            }
          ],
          "UserIdGroupPairs": [],
          "Ipv6Ranges": []
        }
      ],
      "Description": "SG for jenkins",
      "Tags": [
        {
          "Value": "jenkins-sg",
          "Key": "Name"
        }
      ],
      "IpPermissions": [
        {
          "PrefixListIds": [],
          "FromPort": 8080,
          "IpRanges": [
            {
              "CidrIp": "10.2.0.0/16"
            },
            {
              "CidrIp": "10.4.0.0/16"
            }
          ],
          "ToPort": 8080,
          "IpProtocol": "tcp",
          "UserIdGroupPairs": [],
          "Ipv6Ranges": []
        },
        {
          "PrefixListIds": [],
          "FromPort": 22,
          "IpRanges": [
            {
              "CidrIp": "10.2.0.0/16"
            },
            {
              "Description": "blah blah message",
              "CidrIp": "10.5.0.0/16"
            }
          ],
          "ToPort": 22,
          "IpProtocol": "tcp",
          "UserIdGroupPairs": [],
          "Ipv6Ranges": []
        }
      ],
      "GroupName": "jenkins-sg",
      "VpcId": "vpc-deadbeef",
      "OwnerId": "XXXXXXXXXXXX",
      "GroupId": "sg-cafebabe"
    }
  ]
}
```

### References

* #1940 
* #1943

### LINKED ISSUE #2069: Get error when updating SG embedded ingress rules with description
Hi,

I am using terraform v0.10.8 and aws provider 1.1.0 and I am getting the following error when updating a security group ingress rules adding description field.
I am able to update the SG, but needed to remove all rules manually. Then terraform works and updates the SG. When I try to update the SG again, the error happens.
This error does not happen if the SG does not have any rules with description field.

terraform command line
$ terraform apply -target <sg id>

=== output of terraform
Error: Error applying plan:

1 error(s) occurred:

* aws_security_group.client-demo-sg-devops: 1 error(s) occurred:

* aws_security_group.****: Error revoking security group ingress rules: InvalidPermission.NotFound: The specified rule does not exist in this security group.
        status code: 400, request id: 2bfe24f7-a980-4bbc-a58d-54e5935f57a6

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

### LINKED ISSUE #2379: aws_security_group:  using same port/protocol in multiple inline rules causes state problems
### Terraform Version
0.10.3

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_security_group

### Terraform Configuration Files
```hcl
resource "aws_security_group" "rds-private-replica" {
  name        = "blah"
  description = "blah"
  vpc_id      = "${aws_vpc.primary.id}"
  
  ingress {
    from_port       = 5432
    to_port         = 5432
    protocol        = "tcp"
    security_groups = ["${aws_security_group.ecs_sg.id}", "${aws_security_group.console_cluster.id}"]
    description     = "ECS Clusters"
  }

  ingress { 
    from_port       = 5432
    to_port         = 5432
    protocol        = "tcp"
    security_groups = ["${module.ecs-openvpn.ecs_sg}"]
    description     = "Eng VPN"
  }
```

### Expected Behavior
Two rules should be created.

### Actual Behavior
The rules are created, but Terraform detects a diff during every plan/apply and tries to apply changes.

### References
It sounds like this was a known bug and was once fixed, but we are seeing this problem in 0.10.3.  See the following issues:

* https://github.com/hashicorp/terraform/issues/2471
* https://github.com/hashicorp/terraform/issues/3066
* https://github.com/hashicorp/terraform/pull/5100

### LINKED ISSUE #2879: Error revoking security group ingress rules: InvalidPermission.NotFound
_This issue was originally opened by @djgrubson as hashicorp/terraform#17042. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

-terraform version 
0.11.1

-this is happening in custom created VPC
each terraform apply generate update in place even no changes are made with sg-caci-all-ip SG;

-plan output
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ module.bastion.aws_security_group.sg-caci-all-ip
      ingress.1228639923.cidr_blocks.#:      "0" => "1"
      ingress.1228639923.cidr_blocks.0:      "" => "195.1.1.1/26"
      ingress.1228639923.description:        "" => "CACI Proxy"
      ingress.1228639923.from_port:          "" => "0"
      ingress.1228639923.ipv6_cidr_blocks.#: "0" => "0"
      ingress.1228639923.protocol:           "" => "tcp"
      ingress.1228639923.security_groups.#:  "0" => "0"
      ingress.1228639923.self:               "" => "false"
      ingress.1228639923.to_port:            "" => "65535"
      ingress.1455026123.cidr_blocks.#:      "0" => "1"
      ingress.1455026123.cidr_blocks.0:      "" => "195.1.1.2/32"
      ingress.1455026123.description:        "" => "LDS CACI"
      ingress.1455026123.from_port:          "" => "0"
...
  security_groups.#:                     "0" => "1" (forces new resource)
   security_groups.3062004935:            "" => "sg-01efd77a" (forces new resource)

- terraform apply ending with error 
1 error(s) occurred:

* module.bastion.aws_security_group.sg-caci-all-ip: 1 error(s) occurred:

* aws_security_group.sg-caci-all-ip: Error revoking security group ingress rules: InvalidPermission.NotFound: The specified rule does not exist in this security group.
	status code: 400, request id: 298dde37-c18f-4fd7-aa77-8e772a8bb517

-config file to reproduce from bastion module

locals {
    default_tags = {
    Owner       = "coop"
    Environment = "stage"
    Terraform = "true"
    }
}

resource "aws_security_group" "sg-caci-all-ip" {
    name = "caci-all"
    description = "Internal IP for TEST Networks"
    vpc_id = "${var.vpc_id}"

    ingress {
        from_port = 0
        to_port = 65535
        protocol = "tcp"
        cidr_blocks = ["195.1.1.1/32"]
        description = "KV TEST"
    }
    ingress {
        from_port = 0
        to_port = 65535
        protocol = "tcp"
        cidr_blocks = ["195.1.1.2/32"]
        description = "KV TEST"
    }
    ingress {
        from_port = 0
        to_port = 65535
        protocol = "tcp"
        cidr_blocks = ["195.1.1.3/32"]
        description = "KV TEST"
    }
    ingress {
        from_port = 0
        to_port = 65535
        protocol = "tcp"
        cidr_blocks = ["195.1.1.3/32"]
        description = "LDS TEST"
    }
    ingress {
        from_port = 0
        to_port = 65535
        protocol = "tcp"
        cidr_blocks = ["195.1.1.4/32"]
        description = "LDS TEST"
    }
    ingress {
        from_port = 0
        to_port = 65535
        protocol = "tcp"
        cidr_blocks = ["195.1.1.5/29"]
        description = "TEST Proxy"
    }
    ingress {
        from_port = 0
        to_port = 65535
        protocol = "tcp"
        cidr_blocks = ["195.1.1.6/26"]
        description = "TEST Proxy"
    }
    ingress {
        from_port = 0
        to_port = 65535
        protocol = "tcp"
        cidr_blocks = ["195.1.1.7/29"]
        description = "TEST Proxy"
    }
    ingress {
        from_port = 0
        to_port = 65535
        protocol = "tcp"
        cidr_blocks = [195.1.1.8/32"]
        description = "KV TEST"
    }

# outbound internet access
    egress {
      from_port   = 0
      to_port     = 0
      protocol    = "-1"
      cidr_blocks = ["0.0.0.0/0"]
    }
}

resource "aws_instance" "bastion" {
    ami = "${var.ami}"
    availability_zone = "${var.az-1}"
    instance_type = "${var.bastion_instance_type}"
    key_name = "${var.key_name}"
    vpc_security_group_ids = ["${aws_security_group.sg-caci-all-ip.id}"]
    subnet_id = "${var.subnet-az-1-public_id}"
    associate_public_ip_address = true

    tags = "${merge(
    local.default_tags,
    map(
       "Name", "coop-bastion",
    )
  )}"
}

### LINKED ISSUE #3139: Changes to resources that have not been changed
_This issue was originally opened by @VTRyo as hashicorp/terraform#17204. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

# terraform version

```
 % terraform -v
Terraform v0.11.2
```

# terraform aws_plugin version

```
* provider.aws: version = "~> 1.7"
```

# Circumstances

When executing plan again without changing the resource created at the time of the initial apply, "update in-place" is output

# Wrote a description in security_group.tf

https://gist.github.com/VTRyo/1cf480e654661bf84923698aff499dd6

```
resource "aws_security_group" "infra" {
  name                    = "infra"
  description             = "infra SSH"
  vpc_id                  = "${aws_vpc.xxx_vpc.id}"

  ingress {
    from_port               = 22
    to_port                 = 22
    protocol                = "tcp"
    cidr_blocks             = ["xxx.xxx.xxx.xx/xx"]
    description             = "xxxx-host01"
  }

  ingress {
    from_port               = 22
    to_port                 = 22
    protocol                = "tcp"
    cidr_blocks             = ["xxx.xxx.xxx.xx/xx"]
    description             = "office"
  }

  egress {
    from_port               = 0
    to_port                 = 0
    protocol                = "-1"
    cidr_blocks             = ["0.0.0.0/0"]
  }

  egress {
    from_port               = 0
    to_port                 = 0
    protocol                = "-1"
    ipv6_cidr_blocks        = ["::/0"]
  }

  tags {
    Name                    = "infra"
  }
}
```

## Error 

```
Error: Error applying plan:

1 error(s) occurred:

* aws_security_group.infra: 1 error(s) occurred:

* aws_security_group.infra: Error revoking security group ingress rules: InvalidPermission.NotFound: The specified rule does not exist in this security group.
        status code: 400, request id: xxxxxxxxxxxxxxxxxxxxxxxxxxxx


Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

# Do not write description in security_group.tf

https://gist.github.com/VTRyo/1eb94a2d9c3f8c8d7a034f743e7fb826

```
resource "aws_security_group" "infra" {
  name                    = "infra"
  description             = "infra SSH"
  vpc_id                  = "${aws_vpc.xxx_vpc.id}"

  ingress {
    from_port               = 22
    to_port                 = 22
    protocol                = "tcp"
    cidr_blocks             = ["xxx.xxx.xxx.xx/xx"]
  }

  ingress {
    from_port               = 22
    to_port                 = 22
    protocol                = "tcp"
    cidr_blocks             = ["xxx.xxx.xxx.xx/xx"]
  }

  egress {
    from_port               = 0
    to_port                 = 0
    protocol                = "-1"
    cidr_blocks             = ["0.0.0.0/0"]
  }

  egress {
    from_port               = 0
    to_port                 = 0
    protocol                = "-1"
    ipv6_cidr_blocks        = ["::/0"]
  }

  tags {
    Name                    = "infra"
  }
}
```

## Result

```
 %terraform plan -target=aws_security_group.infra
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

aws_vpc.xxxx_vpc: Refreshing state... (ID: xxxxxxxxx)
aws_security_group.infra: Refreshing state... (ID: xxxxxxxx)

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

# Is this a bug?

Is it a bug that behavior varies with description?

### LINKED ISSUE #3202: Bug in aws_security_group with descriptions
_This issue was originally opened by @Heiko-san as hashicorp/terraform#17240. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

Hi,

there seems to be some kind of bug in aws_security_group if you provide description with the rules.
See example configuration below. If the commented out descriptions stay commented everything works fine. If you uncomment them the following error occures.

It seems terraform gets confused with the self and from-loadbalancer rule.
Of course since the rule it wants to change doesn't exist in that form, the rollout breaks.
```
terraform --version
Terraform v0.11.2
+ provider.aws v1.8.0
```

```
terraform apply -var-file=config.tfvars
data.terraform_remote_state.vpc: Refreshing state...
aws_security_group.loadbalancer: Refreshing state... (ID: sg-66e81e1f)
aws_security_group.cp-nodes: Refreshing state... (ID: sg-86ea1cff)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ aws_security_group.cp-nodes
      ingress.1248900448.cidr_blocks.#:              "1" => "1"
      ingress.1248900448.cidr_blocks.0:              "0.0.0.0/0" => "0.0.0.0/0"
      ingress.1248900448.description:                "Allow SSH" => "Allow SSH"
      ingress.1248900448.from_port:                  "22" => "22"
      ingress.1248900448.ipv6_cidr_blocks.#:         "0" => "0"
      ingress.1248900448.protocol:                   "tcp" => "tcp"
      ingress.1248900448.security_groups.#:          "0" => "0"
      ingress.1248900448.self:                       "false" => "false"
      ingress.1248900448.to_port:                    "22" => "22"
      ingress.1452055129.cidr_blocks.#:              "0" => "0"
      ingress.1452055129.description:                "Allow from loadbalancer" => ""
      ingress.1452055129.from_port:                  "0" => "0"
      ingress.1452055129.ipv6_cidr_blocks.#:         "0" => "0"
      ingress.1452055129.protocol:                   "-1" => ""
      ingress.1452055129.security_groups.#:          "0" => "0"
      ingress.1452055129.self:                       "true" => "false"
      ingress.1452055129.to_port:                    "0" => "0"
      ingress.2376006187.cidr_blocks.#:              "0" => "0"
      ingress.2376006187.description:                "Allow from loadbalancer" => "Allow from loadbalancer"
      ingress.2376006187.from_port:                  "0" => "0"
      ingress.2376006187.ipv6_cidr_blocks.#:         "0" => "0"
      ingress.2376006187.protocol:                   "-1" => "-1"
      ingress.2376006187.security_groups.#:          "1" => "1"
      ingress.2376006187.security_groups.1773931791: "sg-66e81e1f" => "sg-66e81e1f"
      ingress.2376006187.self:                       "false" => "false"
      ingress.2376006187.to_port:                    "0" => "0"
      ingress.3860202429.cidr_blocks.#:              "0" => "0"
      ingress.3860202429.description:                "" => "Allow from self"
      ingress.3860202429.from_port:                  "" => "0"
      ingress.3860202429.ipv6_cidr_blocks.#:         "0" => "0"
      ingress.3860202429.protocol:                   "" => "-1"
      ingress.3860202429.security_groups.#:          "0" => "0"
      ingress.3860202429.self:                       "" => "true"
      ingress.3860202429.to_port:                    "" => "0"
      ingress.4011289784.cidr_blocks.#:              "1" => "1"
      ingress.4011289784.cidr_blocks.0:              "0.0.0.0/0" => "0.0.0.0/0"
      ingress.4011289784.description:                "Allow HTTPS" => "Allow HTTPS"
      ingress.4011289784.from_port:                  "443" => "443"
      ingress.4011289784.ipv6_cidr_blocks.#:         "0" => "0"
      ingress.4011289784.protocol:                   "tcp" => "tcp"
      ingress.4011289784.security_groups.#:          "0" => "0"
      ingress.4011289784.self:                       "false" => "false"
      ingress.4011289784.to_port:                    "443" => "443"
      ingress.4081731457.cidr_blocks.#:              "1" => "1"
      ingress.4081731457.cidr_blocks.0:              "0.0.0.0/0" => "0.0.0.0/0"
      ingress.4081731457.description:                "Allow HTTP" => "Allow HTTP"
      ingress.4081731457.from_port:                  "80" => "80"
      ingress.4081731457.ipv6_cidr_blocks.#:         "0" => "0"
      ingress.4081731457.protocol:                   "tcp" => "tcp"
      ingress.4081731457.security_groups.#:          "0" => "0"
      ingress.4081731457.self:                       "false" => "false"
      ingress.4081731457.to_port:                    "80" => "80"
      ingress.615916193.cidr_blocks.#:               "1" => "1"
      ingress.615916193.cidr_blocks.0:               "0.0.0.0/0" => "0.0.0.0/0"
      ingress.615916193.description:                 "Allow ping" => "Allow ping"
      ingress.615916193.from_port:                   "-1" => "-1"
      ingress.615916193.ipv6_cidr_blocks.#:          "0" => "0"
      ingress.615916193.protocol:                    "icmp" => "icmp"
      ingress.615916193.security_groups.#:           "0" => "0"
      ingress.615916193.self:                        "false" => "false"
      ingress.615916193.to_port:                     "-1" => "-1"


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_security_group.cp-nodes: Modifying... (ID: sg-86ea1cff)
  ingress.1248900448.cidr_blocks.#:              "1" => "1"
  ingress.1248900448.cidr_blocks.0:              "0.0.0.0/0" => "0.0.0.0/0"
  ingress.1248900448.description:                "Allow SSH" => "Allow SSH"
  ingress.1248900448.from_port:                  "22" => "22"
  ingress.1248900448.ipv6_cidr_blocks.#:         "0" => "0"
  ingress.1248900448.protocol:                   "tcp" => "tcp"
  ingress.1248900448.security_groups.#:          "0" => "0"
  ingress.1248900448.self:                       "false" => "false"
  ingress.1248900448.to_port:                    "22" => "22"
  ingress.1452055129.cidr_blocks.#:              "0" => "0"
  ingress.1452055129.description:                "Allow from loadbalancer" => ""
  ingress.1452055129.from_port:                  "0" => "0"
  ingress.1452055129.ipv6_cidr_blocks.#:         "0" => "0"
  ingress.1452055129.protocol:                   "-1" => ""
  ingress.1452055129.security_groups.#:          "0" => "0"
  ingress.1452055129.self:                       "true" => "false"
  ingress.1452055129.to_port:                    "0" => "0"
  ingress.2376006187.cidr_blocks.#:              "0" => "0"
  ingress.2376006187.description:                "Allow from loadbalancer" => "Allow from loadbalancer"
  ingress.2376006187.from_port:                  "0" => "0"
  ingress.2376006187.ipv6_cidr_blocks.#:         "0" => "0"
  ingress.2376006187.protocol:                   "-1" => "-1"
  ingress.2376006187.security_groups.#:          "1" => "1"
  ingress.2376006187.security_groups.1773931791: "sg-66e81e1f" => "sg-66e81e1f"
  ingress.2376006187.self:                       "false" => "false"
  ingress.2376006187.to_port:                    "0" => "0"
  ingress.3860202429.cidr_blocks.#:              "0" => "0"
  ingress.3860202429.description:                "" => "Allow from self"
  ingress.3860202429.from_port:                  "" => "0"
  ingress.3860202429.ipv6_cidr_blocks.#:         "0" => "0"
  ingress.3860202429.protocol:                   "" => "-1"
  ingress.3860202429.security_groups.#:          "0" => "0"
  ingress.3860202429.self:                       "" => "true"
  ingress.3860202429.to_port:                    "" => "0"
  ingress.4011289784.cidr_blocks.#:              "1" => "1"
  ingress.4011289784.cidr_blocks.0:              "0.0.0.0/0" => "0.0.0.0/0"
  ingress.4011289784.description:                "Allow HTTPS" => "Allow HTTPS"
  ingress.4011289784.from_port:                  "443" => "443"
  ingress.4011289784.ipv6_cidr_blocks.#:         "0" => "0"
  ingress.4011289784.protocol:                   "tcp" => "tcp"
  ingress.4011289784.security_groups.#:          "0" => "0"
  ingress.4011289784.self:                       "false" => "false"
  ingress.4011289784.to_port:                    "443" => "443"
  ingress.4081731457.cidr_blocks.#:              "1" => "1"
  ingress.4081731457.cidr_blocks.0:              "0.0.0.0/0" => "0.0.0.0/0"
  ingress.4081731457.description:                "Allow HTTP" => "Allow HTTP"
  ingress.4081731457.from_port:                  "80" => "80"
  ingress.4081731457.ipv6_cidr_blocks.#:         "0" => "0"
  ingress.4081731457.protocol:                   "tcp" => "tcp"
  ingress.4081731457.security_groups.#:          "0" => "0"
  ingress.4081731457.self:                       "false" => "false"
  ingress.4081731457.to_port:                    "80" => "80"
  ingress.615916193.cidr_blocks.#:               "1" => "1"
  ingress.615916193.cidr_blocks.0:               "0.0.0.0/0" => "0.0.0.0/0"
  ingress.615916193.description:                 "Allow ping" => "Allow ping"
  ingress.615916193.from_port:                   "-1" => "-1"
  ingress.615916193.ipv6_cidr_blocks.#:          "0" => "0"
  ingress.615916193.protocol:                    "icmp" => "icmp"
  ingress.615916193.security_groups.#:           "0" => "0"
  ingress.615916193.self:                        "false" => "false"
  ingress.615916193.to_port:                     "-1" => "-1"

Error: Error applying plan:

1 error(s) occurred:

* aws_security_group.cp-nodes: 1 error(s) occurred:

* aws_security_group.cp-nodes: Error revoking security group ingress rules: InvalidPermission.NotFound: The specified rule does not exist in this security group.
	status code: 400, request id: 03ee0b69-7b14-4a42-b7c5-4928244cb2b5

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Terraform Configuration Files

```hcl
resource "aws_security_group" "cp-nodes" {
    name        = "${var.name}-${var.stage}-sg-nodes"
    description = "My SG"
    vpc_id      = "${data.terraform_remote_state.vpc.vpc_id}"
    tags {
        Name = "${var.name}-${var.stage}-sg-nodes"
        Stage = "${var.stage}"
    }

    egress {
        from_port       = 0
        to_port         = 0
        protocol        = "-1"
        cidr_blocks     = ["0.0.0.0/0"]
    }

    ingress {
        protocol    = "-1"
        from_port   = 0
        to_port     = 0
        self        = true
#        description = "Allow from self"
    }

    ingress {
        protocol    = "-1"
        from_port   = 0
        to_port     = 0
        security_groups = ["${aws_security_group.loadbalancer.id}"]
#        description = "Allow from loadbalancer"
    }

    ingress {
        protocol    = "icmp"
        from_port   = -1
        to_port     = -1
        cidr_blocks = ["0.0.0.0/0"]
        description = "Allow ping"
    }

    ingress {
        protocol    = "tcp"
        from_port   = 22
        to_port     = 22
        cidr_blocks = ["0.0.0.0/0"]
        description = "Allow SSH"
    }

    ingress {
        protocol    = "tcp"
        from_port   = 80
        to_port     = 80
        cidr_blocks = ["0.0.0.0/0"]
        description = "Allow HTTP"
    }

    ingress {
        protocol    = "tcp"
        from_port   = 443
        to_port     = 443
        cidr_blocks = ["0.0.0.0/0"]
        description = "Allow HTTPS"
    }
}
```

### Expected Behavior

Apply doesn't change anything because there are no changes.

### Actual Behavior

First apply rolls out everything as expected, second apply (without any changes) show the above failure.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. `terraform apply`

### LINKED ISSUE #3204: aws_security_group module : can't use multiple ingress blobs with same ports/protocols
### Terraform Version
Terraform v0.11.2
+ provider.aws v1.8.0

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_security_group

While it's possible to have multiple ingress blobs in a sec group resource that have duplicate from_port, to_port and protocol fields, TF has trouble processing when you try to apply multiple times. The first time is great and it creates the security group perfectly, but in subsequent plan/apply cycles, it determines that there has been a change and tries to update the security group. 

The issue, I believe is that only those 3 fields are required so I'm assuming that some key/hash is being created from those 3 fields. So if you have other discriminating fields like cidr_blocks or description, they aren't considered when TF is checking for idempotentcy.

This makes creating complex security groups difficult since you need to collect all cidr_blocks together for each port pair and you can't add descriptions to different blocks.

### LINKED ISSUE #3261: `InvalidPermission.NotFound` when creating security group rules with overlapping port ranges
With Terraform 0.11.2 and version 1.8.0 of the AWS provider, the following code applies cleanly on the first run, but subsequently fails:

```
resource "aws_vpc" "main" {
  cidr_block = "10.0.0.0/16"
}

resource "aws_security_group" "dummy" {
  vpc_id = "${aws_vpc.main.id}"
  count  = 2
}

resource "aws_security_group" "test" {
  vpc_id = "${aws_vpc.main.id}"

  ingress {
    description     = "A"
    from_port       = 80
    to_port         = 80
    protocol        = "tcp"
    security_groups = ["${aws_security_group.dummy.*.id[0]}"]
  }

  ingress {
    description     = "B"
    from_port       = 80
    to_port         = 80
    protocol        = "tcp"
    security_groups = ["${aws_security_group.dummy.*.id[1]}"]
  }
}
```

After applying the change for the first time, a subsequent plan shows the following changes to be made:

```
  ~ aws_security_group.test
      ingress.1195428013.cidr_blocks.#:              "0" => "0"
      ingress.1195428013.description:                "A" => ""
      ingress.1195428013.from_port:                  "80" => "0"
      ingress.1195428013.ipv6_cidr_blocks.#:         "0" => "0"
      ingress.1195428013.protocol:                   "tcp" => ""
      ingress.1195428013.security_groups.#:          "1" => "0"
      ingress.1195428013.security_groups.2302967246: "sg-731ce90a" => ""
      ingress.1195428013.self:                       "false" => "false"
      ingress.1195428013.to_port:                    "80" => "0"
      ingress.1819122542.cidr_blocks.#:              "0" => "0"
      ingress.1819122542.description:                "" => "B"
      ingress.1819122542.from_port:                  "" => "80"
      ingress.1819122542.ipv6_cidr_blocks.#:         "0" => "0"
      ingress.1819122542.protocol:                   "" => "tcp"
      ingress.1819122542.security_groups.#:          "0" => "1"
      ingress.1819122542.security_groups.2302967246: "" => "sg-731ce90a"
      ingress.1819122542.self:                       "" => "false"
      ingress.1819122542.to_port:                    "" => "80"
      ingress.2787947209.cidr_blocks.#:              "0" => "0"
      ingress.2787947209.description:                "A" => "A"
      ingress.2787947209.from_port:                  "80" => "80"
      ingress.2787947209.ipv6_cidr_blocks.#:         "0" => "0"
      ingress.2787947209.protocol:                   "tcp" => "tcp"
      ingress.2787947209.security_groups.#:          "1" => "1"
      ingress.2787947209.security_groups.1574370408: "sg-e91fea90" => "sg-e91fea90"
      ingress.2787947209.self:                       "false" => "false"
      ingress.2787947209.to_port:                    "80" => "80"
```

Attempting to apply these changes fails:

```
* aws_security_group.test: Error revoking security group ingress rules: InvalidPermission.NotFound: The specified rule does not exist in this security group.
	status code: 400, request id: 31ae42d3-92d5-4d8a-9a89-df10ddfa0d20
```

I believe that the issue here is that the two `ingress` rules have the same port ranges and so the AWS API merges them, which Terraform sees as a change.

### LINKED ISSUE #3346: issues with aws_security_group and multiple ingress blocks
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_security_group

### Terraform Configuration Files
```hcl
resource "aws_security_group" "issue" {
    name = "terraform issue"
    description = "ECS ALB access"
    vpc_id = "${var.aws_vpc_id}"

    ingress {
        from_port = 80
        to_port = 80
        protocol = "tcp"
        description = "WORK"
        cidr_blocks = [ "8.8.8.8/32" ]
    }
    
    ingress {
    from_port = 80
    to_port = 80
    protocol = "tcp"
    description = "HOME"
    cidr_blocks = [ "9.8.7.6/32" ]
    }

    egress {
        from_port = 0
        to_port = 0
        protocol = "-1"
        cidr_blocks = ["0.0.0.0/0"]
    }
}


# resource "aws_security_group_rule" "ingress_work" {
#   type            = "ingress"
#   from_port       = 80
#   to_port         = 80
#   protocol        = "tcp"
#   cidr_blocks     = ["8.8.8.8/32"]
#   security_group_id = "${aws_security_group.issue.id}"
#   description = "WORK"
# }
# 
# resource "aws_security_group_rule" "ingress_home" {
#   type            = "ingress"
#   from_port       = 80
#   to_port         = 80
#   protocol        = "tcp"
#   cidr_blocks     = ["9.8.7.6/32"]
#   security_group_id = "${aws_security_group.issue.id}"
#   description = "HOME"
# }
```

### Expected Behavior
This should idempotently create a security group with 2 rules ONCE, then consider it unchanged

### Actual Behavior
It tries to update the rules every time, and fails (perhaps trying to add a conflicting rule before removing? not totally sure.)

### Steps to Reproduce
Run the above config (multiple times)- only variable is a VPC ID

### Important Factoids
Having separate ingress blocks is how you would define different descriptions- so tha's why I don't just have multiple CIDRs defined in the single rule. 

The separate aws_security_group_rule config commented at the bottom is a workaround that seems to work.

### LINKED ISSUE #4346: Plan wants to modify aws_security_group immediately after creation
### Terraform Version
Terraform v0.11.7
+ provider.aws v1.14.0

### Affected Resource(s)
- aws_security_group

### Terraform Configuration Files
```hcl
resource "aws_vpc" "vpc" {
  cidr_block = "10.13.0.0/16"
  enable_dns_hostnames = true
  enable_dns_support = true
}

resource "aws_security_group" "bastion" {
  name = "bastion.beta"
  vpc_id = "${aws_vpc.vpc.id}"
  description = "Bastion security group"

  ingress {
    description = "SSH access from anywhere"
    protocol    = "tcp"
    from_port   = 22
    to_port     = 22
    cidr_blocks = ["0.0.0.0/0"]
  }
  ingress {
    description = "Pingable from within the VPC"
    protocol    = "icmp"
    from_port   = 7
    to_port     = 7
    cidr_blocks = ["10.13.0.0/16"]
  }
  egress {
    description = "Full outgoing access"
    protocol    = -1
    from_port   = 0
    to_port     = 0
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_security_group" "nginx" {
  name        = "nginx"
  vpc_id      = "${aws_vpc.vpc.id}"
  description = "nginx security group"

  ingress {
    description = "Web traffic from cloudfront"
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
  ingress {
    description = "Full access from bastion"
    from_port   = 0
    to_port     = 0
    protocol    = -1
    security_groups = ["${aws_security_group.bastion.id}"]
  }
  egress {
    description = "Full outgoing access"
    from_port   = 0
    to_port     = 0
    protocol    = -1
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_security_group" "private" {
  name        = "private"
  vpc_id      = "${aws_vpc.vpc.id}"
  description = "Internal security group"

  ingress {
    description = "Full access from bastion"
    protocol    = -1
    from_port   = 0
    to_port     = 0
    security_groups = ["${aws_security_group.bastion.id}"]
  }
  ingress {
    description = "MID traffic from nginx"
    protocol    = "tcp"
    from_port   = 8282
    to_port     = 8282
    security_groups = ["${aws_security_group.nginx.id}"]
  }
  ingress {
    description = "REST traffic from nginx"
    protocol    = "tcp"
    from_port   = 5000
    to_port     = 5000
    security_groups = ["${aws_security_group.nginx.id}"]
  }
  ingress {
    description = "Private subnet traffic"
    protocol    = -1
    from_port   = 0
    to_port     = 0
    self        = true
  }
  egress {
    description = "Full outgoing access"
    from_port   = 0
    to_port     = 0
    protocol    = -1
    cidr_blocks = ["0.0.0.0/0"]
  }
}
```

### Debug Output
[gist](https://gist.github.com/twall/63b01bfd5731c140362b8d95f6e81f2b#file-gistfile1-txt)

### Expected Behavior
After creation, the security group should not require any additional changes.

### Actual Behavior
`terraform plan` always wants to alter the resource, eventually failing as it tries to reconcile 5 security group rules that it _thinks_ exists with the 4 that actually exist.

The command ends up failing with the following:
```
Error: Error applying plan:

1 error(s) occurred:

* module.network.aws_security_group.private: 1 error(s) occurred:

* aws_security_group.private: Error revoking security group ingress rules: InvalidPermission.NotFound: The specified rule does not exist in this security group.
	status code: 400, request id: 6894b3ae-100a-4106-bdc9-6036925874b9
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform plan`

### State file relevant section
```
                "aws_security_group.private": {
                    "type": "aws_security_group",
                    "depends_on": [
                        "aws_security_group.bastion",
                        "aws_security_group.nginx",
                        "aws_vpc.vpc"
                    ],
                    "primary": {
                        "id": "sg-4c1c4b05",
                        "attributes": {
                            "arn": "arn:aws:ec2:us-east-1:443155816678:security-group/sg-4c1c4b05",
                            "description": "Internal security group",
                            "egress.#": "1",
                            "egress.1043278264.cidr_blocks.#": "1",
                            "egress.1043278264.cidr_blocks.0": "0.0.0.0/0",
                            "egress.1043278264.description": "Full outgoing access",
                            "egress.1043278264.from_port": "0",
                            "egress.1043278264.ipv6_cidr_blocks.#": "0",
                            "egress.1043278264.prefix_list_ids.#": "0",
                            "egress.1043278264.protocol": "-1",
                            "egress.1043278264.security_groups.#": "0",
                            "egress.1043278264.self": "false",
                            "egress.1043278264.to_port": "0",
                            "id": "sg-4c1c4b05",
                            "ingress.#": "4",
                            "ingress.1037983234.cidr_blocks.#": "0",
                            "ingress.1037983234.description": "Full access from bastion",
                            "ingress.1037983234.from_port": "0",
                            "ingress.1037983234.ipv6_cidr_blocks.#": "0",
                            "ingress.1037983234.protocol": "-1",
                            "ingress.1037983234.security_groups.#": "0",
                            "ingress.1037983234.self": "true",
                            "ingress.1037983234.to_port": "0",
                            "ingress.1869596649.cidr_blocks.#": "0",
                            "ingress.1869596649.description": "Full access from bastion",
                            "ingress.1869596649.from_port": "0",
                            "ingress.1869596649.ipv6_cidr_blocks.#": "0",
                            "ingress.1869596649.protocol": "-1",
                            "ingress.1869596649.security_groups.#": "1",
                            "ingress.1869596649.security_groups.1225174371": "sg-d08cd899",
                            "ingress.1869596649.self": "false",
                            "ingress.1869596649.to_port": "0",
                            "ingress.2720822744.cidr_blocks.#": "0",
                            "ingress.2720822744.description": "MID traffic from nginx",
                            "ingress.2720822744.from_port": "8282",
                            "ingress.2720822744.ipv6_cidr_blocks.#": "0",
                            "ingress.2720822744.protocol": "tcp",
                            "ingress.2720822744.security_groups.#": "1",
                            "ingress.2720822744.security_groups.2097596583": "sg-ce1b4c87",
                            "ingress.2720822744.self": "false",
                            "ingress.2720822744.to_port": "8282",
                            "ingress.3645042310.cidr_blocks.#": "0",
                            "ingress.3645042310.description": "REST traffic from nginx",
                            "ingress.3645042310.from_port": "5000",
                            "ingress.3645042310.ipv6_cidr_blocks.#": "0",
                            "ingress.3645042310.protocol": "tcp",
                            "ingress.3645042310.security_groups.#": "1",
                            "ingress.3645042310.security_groups.2097596583": "sg-ce1b4c87",
                            "ingress.3645042310.self": "false",
                            "ingress.3645042310.to_port": "5000",
                            "name": "private",
                            "owner_id": "443155816678",
                            "revoke_rules_on_delete": "false",
                            "tags.%": "3",
                            "tags.Cell": "beta",
                            "tags.Environment": "dev",
                            "tags.Name": "beta-private",
                            "vpc_id": "vpc-3516584e"
                        },
                        "meta": {
                            "e2bfb730-ecaa-11e6-8f88-34363bc7c4c0": {
                                "create": 600000000000,
                                "delete": 600000000000
                            },
                            "schema_version": "1"
                        },
                        "tainted": false
                    },
                    "deposed": [],
                    "provider": "provider.aws"
                }
```
### Plan output
```
Terraform will perform the following actions:

  ~ module.network.aws_security_group.private
      ingress.1037983234.cidr_blocks.#:              "0" => "0"
      ingress.1037983234.description:                "Full access from bastion" => ""
      ingress.1037983234.from_port:                  "0" => "0"
      ingress.1037983234.ipv6_cidr_blocks.#:         "0" => "0"
      ingress.1037983234.protocol:                   "-1" => ""
      ingress.1037983234.security_groups.#:          "0" => "0"
      ingress.1037983234.self:                       "true" => "false"
      ingress.1037983234.to_port:                    "0" => "0"
      ingress.1869596649.cidr_blocks.#:              "0" => "0"
      ingress.1869596649.description:                "Full access from bastion" => "Full access from bastion"
      ingress.1869596649.from_port:                  "0" => "0"
      ingress.1869596649.ipv6_cidr_blocks.#:         "0" => "0"
      ingress.1869596649.protocol:                   "-1" => "-1"
      ingress.1869596649.security_groups.#:          "1" => "1"
      ingress.1869596649.security_groups.1225174371: "sg-d08cd899" => "sg-d08cd899"
      ingress.1869596649.self:                       "false" => "false"
      ingress.1869596649.to_port:                    "0" => "0"
      ingress.2720822744.cidr_blocks.#:              "0" => "0"
      ingress.2720822744.description:                "MID traffic from nginx" => "MID traffic from nginx"
      ingress.2720822744.from_port:                  "8282" => "8282"
      ingress.2720822744.ipv6_cidr_blocks.#:         "0" => "0"
      ingress.2720822744.protocol:                   "tcp" => "tcp"
      ingress.2720822744.security_groups.#:          "1" => "1"
      ingress.2720822744.security_groups.2097596583: "sg-ce1b4c87" => "sg-ce1b4c87"
      ingress.2720822744.self:                       "false" => "false"
      ingress.2720822744.to_port:                    "8282" => "8282"
      ingress.308491569.cidr_blocks.#:               "0" => "0"
      ingress.308491569.description:                 "" => "Private subnet traffic"
      ingress.308491569.from_port:                   "" => "0"
      ingress.308491569.ipv6_cidr_blocks.#:          "0" => "0"
      ingress.308491569.protocol:                    "" => "-1"
      ingress.308491569.security_groups.#:           "0" => "0"
      ingress.308491569.self:                        "" => "true"
      ingress.308491569.to_port:                     "" => "0"
      ingress.3645042310.cidr_blocks.#:              "0" => "0"
      ingress.3645042310.description:                "REST traffic from nginx" => "REST traffic from nginx"
      ingress.3645042310.from_port:                  "5000" => "5000"
      ingress.3645042310.ipv6_cidr_blocks.#:         "0" => "0"
      ingress.3645042310.protocol:                   "tcp" => "tcp"
      ingress.3645042310.security_groups.#:          "1" => "1"
      ingress.3645042310.security_groups.2097596583: "sg-ce1b4c87" => "sg-ce1b4c87"
      ingress.3645042310.self:                       "false" => "false"
      ingress.3645042310.to_port:                    "5000" => "5000"


Plan: 0 to add, 1 to change, 0 to destroy.
```

Note that "plan" thinks that there are five rules when there are only four, both in the configuration and actually extant on the security group itself.  This ultimately results in a failure when terraform attempts to delete a fifth, nonexistent rule.

### LINKED ISSUE #4410: Terraform applys security group rules, but doesnt remember
When applying security group changes, such as description. everything applys fine. if you make no changes and run terraform apply again it comes up with 400 errors.

### Terraform Version
11.7

### Affected Resource(s)
- aws_security_group

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "aws_security_group" "nfs_sg" {
  vpc_id = "${var.vpc_id}"

  ingress {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["${var.vpn_ip}"] #VPN IP address
    description = "SSH Managment Port"
  }

  ingress {
    from_port   = 111
    to_port     = 111
    protocol    = "tcp"
    cidr_blocks = ["${var.nfs_ip}", "${var.nifi_ip}/32", "${var.node_1_ip}/32"]
    description = "NFS port"
  }

  ingress {
    from_port   = 2049
    to_port     = 2049
    protocol    = "tcp"
    cidr_blocks = ["${var.nfs_ip}", "${var.nifi_ip}/32", "${var.node_1_ip}/32"]
    description = "NFS port"
  }

  ingress {
    from_port   = 9100
    to_port     = 9100
    protocol    = "tcp"
    cidr_blocks = ["10.0.0.0/8"]
    description = "node exporter"
  }

  ingress {
    from_port   = 20048
    to_port     = 20048
    protocol    = "tcp"
    cidr_blocks = ["${var.nfs_ip}", "${var.nifi_ip}/32"]
  }

  ingress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["${var.sr_security_instance}"]
    description = "Nessus"
  }

  ingress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["${var.nessus_ips}"]
    description = "Nessus"
  }

  ingress {
    from_port   = 4118
    to_port     = 4118
    protocol    = "tcp"
    cidr_blocks = ["${var.trend_agent_ips}"]
    description = "Trend Port"
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
    description = "No Outbound Restrictions"
  }

  tags {
    Name        = "blah-nfs-${var.Environment}"
    product     = "${var.product}"
    Terraform   = "true"
    Environment = "${var.Environment}"
  }

  count = "${var.nfs}"
}
```

### Expected Behavior
Security group no update because nothing has changed

### Actual Behavior
* module.nfs.aws_security_group.nfs_sg: 1 error(s) occurred:

* aws_security_group.nfs_sg: Error revoking security group ingress rules: InvalidPermission.NotFound: The specified rule does not exist in this security group.
	status code: 400, request id: 65c1395d-a55d-460f-8ad3-d4688f2cc415

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform apply`

### PR DESCRIPTION
**Pull request by loivis**
fix #2018 
fix #2069 
fix #2379 
fix #2879 
fix #3139
fix #3202
fix #3204
fix #3261 
fix #3346
fix #4346
fix #4410 

There have been a few issues regarding rules with the same `protocol`, `from_port` and `to_port` but different `description`. The last `description` will eventually override previous ones and next `plan` shows changes to apply.

One simple example could be:
```
resource "aws_vpc" "test" {
  cidr_block = "10.0.0.0/16"

  tags {
    Name = "tf-test"
  }
}

resource "aws_security_group" "test" {
  name        = "tf-test"
  vpc_id      = "${aws_vpc.test.id}"

  ingress {
    protocol         = "tcp"
    from_port        = 80
    to_port          = 80
    ipv6_cidr_blocks = ["0.0.0.0/0"]
    description      = "ingress from all ipv4"
  }

  ingress {
    protocol         = "tcp"
    from_port        = 80
    to_port          = 80
    ipv6_cidr_blocks = ["::/0"]
    description      = "ingress from all ipv6"
  }
}
```

### CODE REVIEW

**Comment by loivis** [comment]
before:
```
=== RUN   TestAccAWSSecurityGroup_uniqueRule
--- FAIL: TestAccAWSSecurityGroup_uniqueRule (46.70s)
	testing.go:518: Step 0 error: After applying this step, the plan was not empty:

		DIFF:

		UPDATE: aws_security_group.test
		  egress.2760422146.cidr_blocks.#:               "0" => "0"
		  egress.2760422146.description:                 "" => "egress for all ipv6"
		  egress.2760422146.from_port:                   "" => "0"
		  egress.2760422146.ipv6_cidr_blocks.#:          "0" => "1"
		  egress.2760422146.ipv6_cidr_blocks.0:          "" => "::/0"
		  egress.2760422146.prefix_list_ids.#:           "0" => "0"
		  egress.2760422146.protocol:                    "" => "-1"
		  egress.2760422146.security_groups.#:           "0" => "0"
		  egress.2760422146.self:                        "" => "false"
		  egress.2760422146.to_port:                     "" => "0"
		  egress.2821619876.cidr_blocks.#:               "1" => "0"
		  egress.2821619876.cidr_blocks.0:               "0.0.0.0/0" => ""
		  egress.2821619876.description:                 "egress for vpc endpoints" => ""
		  egress.2821619876.from_port:                   "0" => "0"
		  egress.2821619876.ipv6_cidr_blocks.#:          "0" => "0"
		  egress.2821619876.prefix_list_ids.#:           "0" => "0"
		  egress.2821619876.protocol:                    "-1" => ""
		  egress.2821619876.security_groups.#:           "0" => "0"
		  egress.2821619876.self:                        "false" => "false"
		  egress.2821619876.to_port:                     "0" => "0"
		  egress.2973493247.cidr_blocks.#:               "0" => "0"
		  egress.2973493247.description:                 "egress for vpc endpoints" => ""
		  egress.2973493247.from_port:                   "0" => "0"
		  egress.2973493247.ipv6_cidr_blocks.#:          "1" => "0"
		  egress.2973493247.ipv6_cidr_blocks.0:          "::/0" => ""
		  egress.2973493247.prefix_list_ids.#:           "0" => "0"
		  egress.2973493247.protocol:                    "-1" => ""
		  egress.2973493247.security_groups.#:           "0" => "0"
		  egress.2973493247.self:                        "false" => "false"
		  egress.2973493247.to_port:                     "0" => "0"
		  egress.2981002505.cidr_blocks.#:               "0" => "0"
		  egress.2981002505.description:                 "egress for vpc endpoints" => "egress for vpc endpoints"
		  egress.2981002505.from_port:                   "0" => "0"
		  egress.2981002505.ipv6_cidr_blocks.#:          "0" => "0"
		  egress.2981002505.prefix_list_ids.#:           "1" => "1"
		  egress.2981002505.prefix_list_ids.0:           "pl-6da54004" => "pl-6da54004"
		  egress.2981002505.protocol:                    "-1" => "-1"
		  egress.2981002505.security_groups.#:           "0" => "0"
		  egress.2981002505.self:                        "false" => "false"
		  egress.2981002505.to_port:                     "0" => "0"
		  egress.3161496341.cidr_blocks.#:               "0" => "1"
		  egress.3161496341.cidr_blocks.0:               "" => "0.0.0.0/0"
		  egress.3161496341.description:                 "" => "egress for all ipv4"
		  egress.3161496341.from_port:                   "" => "0"
		  egress.3161496341.ipv6_cidr_blocks.#:          "0" => "0"
		  egress.3161496341.prefix_list_ids.#:           "0" => "0"
		  egress.3161496341.protocol:                    "" => "-1"
		  egress.3161496341.security_groups.#:           "0" => "0"
		  egress.3161496341.self:                        "" => "false"
		  egress.3161496341.to_port:                     "" => "0"
		  ingress.#:                                     "3" => "5"
		  ingress.1274017860.cidr_blocks.#:              "0" => "1"
		  ingress.1274017860.cidr_blocks.0:              "" => "192.168.0.0/16"
		  ingress.1274017860.description:                "" => "ingress from 192.168.0.0/16"
		  ingress.1274017860.from_port:                  "" => "80"
		  ingress.1274017860.ipv6_cidr_blocks.#:         "0" => "0"
		  ingress.1274017860.protocol:                   "" => "tcp"
		  ingress.1274017860.security_groups.#:          "0" => "0"
		  ingress.1274017860.self:                       "" => "false"
		  ingress.1274017860.to_port:                    "" => "80"
		  ingress.1396402051.cidr_blocks.#:              "0" => "0"
		  ingress.1396402051.description:                "" => "ingress from all ipv6"
		  ingress.1396402051.from_port:                  "" => "80"
		  ingress.1396402051.ipv6_cidr_blocks.#:         "0" => "1"
		  ingress.1396402051.ipv6_cidr_blocks.0:         "" => "::/0"
		  ingress.1396402051.protocol:                   "" => "tcp"
		  ingress.1396402051.security_groups.#:          "0" => "0"
		  ingress.1396402051.self:                       "" => "false"
		  ingress.1396402051.to_port:                    "" => "80"
		  ingress.1687249332.cidr_blocks.#:              "2" => "0"
		  ingress.1687249332.cidr_blocks.0:              "10.0.0.0/24" => ""
		  ingress.1687249332.cidr_blocks.1:              "10.0.1.0/24" => ""
		  ingress.1687249332.description:                "ingress from other security groups" => ""
		  ingress.1687249332.from_port:                  "80" => "0"
		  ingress.1687249332.ipv6_cidr_blocks.#:         "0" => "0"
		  ingress.1687249332.protocol:                   "tcp" => ""
		  ingress.1687249332.security_groups.#:          "0" => "0"
		  ingress.1687249332.self:                       "true" => "false"
		  ingress.1687249332.to_port:                    "80" => "0"
		  ingress.1889111182.cidr_blocks.#:              "0" => "2"
		  ingress.1889111182.cidr_blocks.0:              "" => "10.0.2.0/24"
		  ingress.1889111182.cidr_blocks.1:              "" => "10.0.3.0/24"
		  ingress.1889111182.description:                "" => "ingress from 10.0.0.0/16"
		  ingress.1889111182.from_port:                  "" => "80"
		  ingress.1889111182.ipv6_cidr_blocks.#:         "0" => "0"
		  ingress.1889111182.protocol:                   "" => "tcp"
		  ingress.1889111182.security_groups.#:          "0" => "0"
		  ingress.1889111182.self:                       "" => "false"
		  ingress.1889111182.to_port:                    "" => "80"
		  ingress.2038285407.cidr_blocks.#:              "0" => "2"
		  ingress.2038285407.cidr_blocks.0:              "" => "10.0.0.0/24"
		  ingress.2038285407.cidr_blocks.1:              "" => "10.0.1.0/24"
		  ingress.2038285407.description:                "" => ""
		  ingress.2038285407.from_port:                  "" => "80"
		  ingress.2038285407.ipv6_cidr_blocks.#:         "0" => "0"
		  ingress.2038285407.protocol:                   "" => "tcp"
		  ingress.2038285407.security_groups.#:          "0" => "0"
		  ingress.2038285407.self:                       "" => "true"
		  ingress.2038285407.to_port:                    "" => "80"
		  ingress.2768612695.cidr_blocks.#:              "0" => "0"
		  ingress.2768612695.description:                "ingress from other security groups" => "ingress from other security groups"
		  ingress.2768612695.from_port:                  "80" => "80"
		  ingress.2768612695.ipv6_cidr_blocks.#:         "0" => "0"
		  ingress.2768612695.protocol:                   "tcp" => "tcp"
		  ingress.2768612695.security_groups.#:          "2" => "2"
		  ingress.2768612695.security_groups.1695808062: "sg-08ad8693d0c90a1de" => "sg-08ad8693d0c90a1de"
		  ingress.2768612695.security_groups.2580594009: "sg-00633325aa9519f24" => "sg-00633325aa9519f24"
		  ingress.2768612695.self:                       "false" => "false"
		  ingress.2768612695.to_port:                    "80" => "80"
		  ingress.4193023394.cidr_blocks.#:              "3" => "0"
		  ingress.4193023394.cidr_blocks.0:              "10.0.3.0/24" => ""
		  ingress.4193023394.cidr_blocks.1:              "10.0.2.0/24" => ""
		  ingress.4193023394.cidr_blocks.2:              "192.168.0.0/16" => ""
		  ingress.4193023394.description:                "ingress from other security groups" => ""
		  ingress.4193023394.from_port:                  "80" => "0"
		  ingress.4193023394.ipv6_cidr_blocks.#:         "1" => "0"
		  ingress.4193023394.ipv6_cidr_blocks.0:         "::/0" => ""
		  ingress.4193023394.protocol:                   "tcp" => ""
		  ingress.4193023394.security_groups.#:          "0" => "0"
		  ingress.4193023394.self:                       "false" => "false"
		  ingress.4193023394.to_port:                    "80" => "0"
```

after:
```
TF_ACC=1 go test ./aws -v -run=TestAccAWSSecurityGroup_uniqueRule -timeout 120m
=== RUN   TestAccAWSSecurityGroup_uniqueRule
--- PASS: TestAccAWSSecurityGroup_uniqueRule (54.67s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	54.713s
```

**Comment by loivis** [comment]
It really takes some time to run all tests 😓 . Some unrelated errors remain.

```
⎇  make fmt; and echo > aws/debug.log ; and make testacc TEST=./aws TESTARGS='-run=TestAccAWSSecurityGroup_'
gofmt -w $(find . -name '*.go' |grep -v vendor)
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSSecurityGroup_ -timeout 120m
=== RUN   TestAccAWSSecurityGroup_importBasic
--- PASS: TestAccAWSSecurityGroup_importBasic (37.67s)
=== RUN   TestAccAWSSecurityGroup_importIpv6
--- PASS: TestAccAWSSecurityGroup_importIpv6 (29.66s)
=== RUN   TestAccAWSSecurityGroup_importSelf
--- PASS: TestAccAWSSecurityGroup_importSelf (34.46s)
=== RUN   TestAccAWSSecurityGroup_importSourceSecurityGroup
--- PASS: TestAccAWSSecurityGroup_importSourceSecurityGroup (40.55s)
=== RUN   TestAccAWSSecurityGroup_importIPRangeAndSecurityGroupWithSameRules
--- PASS: TestAccAWSSecurityGroup_importIPRangeAndSecurityGroupWithSameRules (36.30s)
=== RUN   TestAccAWSSecurityGroup_importIPRangesWithSameRules
--- PASS: TestAccAWSSecurityGroup_importIPRangesWithSameRules (38.69s)
=== RUN   TestAccAWSSecurityGroup_importPrefixList
--- FAIL: TestAccAWSSecurityGroup_importPrefixList (14.10s)
	testing.go:518: Step 0 error: Error applying: 1 error(s) occurred:

		* aws_vpc_endpoint.s3-us-west-2: 1 error(s) occurred:

		* aws_vpc_endpoint.s3-us-west-2: Error creating VPC Endpoint: InvalidServiceName: The Vpc Endpoint Service 'com.amazonaws.us-west-2.s3' does not exist
			status code: 400, request id: 75996839-4665-4276-a6d9-c6c43ee06860
=== RUN   TestAccAWSSecurityGroup_basic
--- PASS: TestAccAWSSecurityGroup_basic (34.93s)
=== RUN   TestAccAWSSecurityGroup_ruleGathering
--- PASS: TestAccAWSSecurityGroup_ruleGathering (56.94s)
=== RUN   TestAccAWSSecurityGroup_forceRevokeRules_true

--- PASS: TestAccAWSSecurityGroup_forceRevokeRules_true (721.61s)
=== RUN   TestAccAWSSecurityGroup_forceRevokeRules_false
--- PASS: TestAccAWSSecurityGroup_forceRevokeRules_false (680.14s)
=== RUN   TestAccAWSSecurityGroup_basicRuleDescription
--- PASS: TestAccAWSSecurityGroup_basicRuleDescription (31.57s)
=== RUN   TestAccAWSSecurityGroup_ipv6
--- PASS: TestAccAWSSecurityGroup_ipv6 (30.55s)
=== RUN   TestAccAWSSecurityGroup_tagsCreatedFirst
--- PASS: TestAccAWSSecurityGroup_tagsCreatedFirst (25.44s)
=== RUN   TestAccAWSSecurityGroup_namePrefix
--- PASS: TestAccAWSSecurityGroup_namePrefix (24.91s)
=== RUN   TestAccAWSSecurityGroup_self
--- PASS: TestAccAWSSecurityGroup_self (31.27s)
=== RUN   TestAccAWSSecurityGroup_vpc
--- PASS: TestAccAWSSecurityGroup_vpc (33.94s)
=== RUN   TestAccAWSSecurityGroup_vpcNegOneIngress
--- PASS: TestAccAWSSecurityGroup_vpcNegOneIngress (30.42s)
=== RUN   TestAccAWSSecurityGroup_vpcProtoNumIngress
--- PASS: TestAccAWSSecurityGroup_vpcProtoNumIngress (30.79s)
=== RUN   TestAccAWSSecurityGroup_MultiIngress
--- PASS: TestAccAWSSecurityGroup_MultiIngress (37.59s)
=== RUN   TestAccAWSSecurityGroup_Change
--- PASS: TestAccAWSSecurityGroup_Change (56.22s)
=== RUN   TestAccAWSSecurityGroup_ChangeRuleDescription
--- PASS: TestAccAWSSecurityGroup_ChangeRuleDescription (77.33s)
=== RUN   TestAccAWSSecurityGroup_generatedName
--- PASS: TestAccAWSSecurityGroup_generatedName (34.31s)
=== RUN   TestAccAWSSecurityGroup_DefaultEgress_VPC
--- PASS: TestAccAWSSecurityGroup_DefaultEgress_VPC (29.85s)
=== RUN   TestAccAWSSecurityGroup_DefaultEgress_Classic
--- PASS: TestAccAWSSecurityGroup_DefaultEgress_Classic (28.48s)
=== RUN   TestAccAWSSecurityGroup_drift
--- FAIL: TestAccAWSSecurityGroup_drift (4.70s)
	testing.go:518: Step 0 error: Error applying: 1 error(s) occurred:

		* aws_security_group.web: 1 error(s) occurred:

		* aws_security_group.web: Error creating Security Group: VPCIdNotSpecified: No default VPC for this user
			status code: 400, request id: 4fc65c80-2a26-4162-8050-aa8922e066b4
=== RUN   TestAccAWSSecurityGroup_drift_complex
--- PASS: TestAccAWSSecurityGroup_drift_complex (38.48s)
=== RUN   TestAccAWSSecurityGroup_invalidCIDRBlock
--- PASS: TestAccAWSSecurityGroup_invalidCIDRBlock (1.64s)
=== RUN   TestAccAWSSecurityGroup_tags
--- PASS: TestAccAWSSecurityGroup_tags (52.42s)
=== RUN   TestAccAWSSecurityGroup_CIDRandGroups
--- PASS: TestAccAWSSecurityGroup_CIDRandGroups (38.03s)
=== RUN   TestAccAWSSecurityGroup_ingressWithCidrAndSGs
--- PASS: TestAccAWSSecurityGroup_ingressWithCidrAndSGs (35.97s)
=== RUN   TestAccAWSSecurityGroup_ingressWithCidrAndSGs_classic
--- FAIL: TestAccAWSSecurityGroup_ingressWithCidrAndSGs_classic (28.64s)
	testing.go:518: Step 0 error: Error applying: 1 error(s) occurred:

		* aws_security_group.web: 1 error(s) occurred:

		* aws_security_group.web: Error authorizing security group ingress rules: InvalidGroupId.Malformed: Invalid id: "tf_other_acc_tests" (expecting "sg-...")
			status code: 400, request id: 8c1edee0-80ae-4143-ba1b-23d6aa945ab6
=== RUN   TestAccAWSSecurityGroup_egressWithPrefixList
--- FAIL: TestAccAWSSecurityGroup_egressWithPrefixList (19.03s)
	testing.go:518: Step 0 error: Error applying: 1 error(s) occurred:

		* aws_vpc_endpoint.s3-us-west-2: 1 error(s) occurred:

		* aws_vpc_endpoint.s3-us-west-2: Error creating VPC Endpoint: InvalidServiceName: The Vpc Endpoint Service 'com.amazonaws.us-west-2.s3' does not exist
			status code: 400, request id: d3a27287-e81b-4ff4-a93b-e6b774a3dc8c
=== RUN   TestAccAWSSecurityGroup_emptyRuleDescription
--- PASS: TestAccAWSSecurityGroup_emptyRuleDescription (33.43s)
=== RUN   TestAccAWSSecurityGroup_ipv4andipv6Egress
--- PASS: TestAccAWSSecurityGroup_ipv4andipv6Egress (32.28s)
=== RUN   TestAccAWSSecurityGroup_failWithDiffMismatch
--- PASS: TestAccAWSSecurityGroup_failWithDiffMismatch (39.12s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	2551.544s
```
```
TF_ACC=1 go test ./aws -v -run=TestAccAWSSecurityGroup_importPrefixList -timeout 120m
=== RUN   TestAccAWSSecurityGroup_importPrefixList
--- PASS: TestAccAWSSecurityGroup_importPrefixList (50.96s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	51.009s
```
```
TF_ACC=1 go test ./aws -v -run=TestAccAWSSecurityGroup_egressWithPrefixList -timeout 120m
=== RUN   TestAccAWSSecurityGroup_egressWithPrefixList
--- PASS: TestAccAWSSecurityGroup_egressWithPrefixList (51.42s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	51.468s
```

File: aws/resource_aws_security_group.go [hunk 1]
```diff
@@ -1339,3 +1300,27 @@ func networkInterfaceAttachedRefreshFunc(conn *ec2.EC2, id string) resource.Stat
...
+
+func initSecurityGroupRule(ruleMap map[string]map[string]interface{}, perm *ec2.IpPermission, desc string) map[string]interface{} {
+	var fromPort, toPort int64
+	if v := perm.FromPort; v != nil {
+		fromPort = *v
+	}
+	if v := perm.ToPort; v != nil {
+		toPort = *v
+	}
+	k := fmt.Sprintf("%s-%d-%d-%s", *perm.IpProtocol, fromPort, toPort, desc)
```
Comment (bflad) [inline aws/resource_aws_security_group.go]: This was previously: `k := fmt.Sprintf("%s-%d-%d", *perm.IpProtocol, fromPort, toPort)`

Doesn't the addition of `-%s` need to be based on `desc != ""` to prevent differences when upgrading?

Comment (bflad) [reply aws/resource_aws_security_group.go]: It looks like this map key doesn't appear to be used in the downstream code, so I think its actually okay. 👍

Comment (loivis) [reply aws/resource_aws_security_group.go]: yes, `k` is more of an intermediate variable

**Comment by bflad** [comment]
This has been released in [version 1.19.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1190-may-16-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by zioalex** [comment]
@bflad  the issue #2879 doesn't seem to be fix by this. 
Here the error
```
aws_security_group.private: Modifying... (ID: sg-e3327a99)
  ingress.#:                             "4" => "3"
  ingress.1004056048.cidr_blocks.#:      "1" => "1"
  ingress.1004056048.cidr_blocks.0:      "10.123.248.0/22" => "10.123.248.0/22"
  ingress.1004056048.description:        "" => ""
  ingress.1004056048.from_port:          "0" => "0"
  ingress.1004056048.ipv6_cidr_blocks.#: "0" => "0"
  ingress.1004056048.protocol:           "-1" => "-1"
  ingress.1004056048.security_groups.#:  "0" => "0"
  ingress.1004056048.self:               "false" => "false"
  ingress.1004056048.to_port:            "0" => "0"
  ingress.1098541575.cidr_blocks.#:      "1" => "0"
  ingress.1098541575.cidr_blocks.0:      "10.0.0.0/8" => ""
  ingress.1098541575.description:        "" => ""
  ingress.1098541575.from_port:          "3306" => "0"
  ingress.1098541575.ipv6_cidr_blocks.#: "0" => "0"
  ingress.1098541575.protocol:           "tcp" => ""
  ingress.1098541575.security_groups.#:  "0" => "0"
  ingress.1098541575.self:               "false" => "false"
  ingress.1098541575.to_port:            "3306" => "0"
  ingress.179083333.cidr_blocks.#:       "1" => "1"
  ingress.179083333.cidr_blocks.0:       "10.0.0.0/8" => "10.0.0.0/8"
  ingress.179083333.description:         "" => ""
  ingress.179083333.from_port:           "22" => "22"
  ingress.179083333.ipv6_cidr_blocks.#:  "0" => "0"
  ingress.179083333.protocol:            "TCP" => "tcp"
  ingress.179083333.security_groups.#:   "0" => "0"
  ingress.179083333.self:                "false" => "false"
  ingress.179083333.to_port:             "22" => "22"
  ingress.2030155270.cidr_blocks.#:      "1" => "1"
  ingress.2030155270.cidr_blocks.0:      "10.117.240.0/20" => "10.117.240.0/20"
  ingress.2030155270.description:        "" => ""
  ingress.2030155270.from_port:          "0" => "0"
  ingress.2030155270.ipv6_cidr_blocks.#: "0" => "0"
  ingress.2030155270.protocol:           "TCP" => "tcp"
  ingress.2030155270.security_groups.#:  "0" => "0"
  ingress.2030155270.self:               "false" => "false"
  ingress.2030155270.to_port:            "65535" => "65535"
module.db_password_setup.aws_security_group_rule.db_internal_allow_mariadb_net: Destruction complete after 0s

Error: Error applying plan:

1 error(s) occurred:

* aws_security_group.private: 1 error(s) occurred:

* aws_security_group.private: Error revoking security group ingress rules: InvalidPermission.NotFound: The specified rule does not exist in this security group.
	status code: 400, request id: 2c781f0c-5e3f-40fa-be0a-e0892520ecde

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

But the resource has been deleted and the next plan is clear.
There are the actual versions:
```
terraform -version
Using AWS_* Environment variables.Terraform v0.11.7
+ provider.aws v1.19.0
+ provider.null v1.0.0
```

**Comment by zioalex** [comment]
@bflad  I recreated all the resources with lower case "tcp" but it didn't help.
But I found the trick here. I was using a SG defined with ingress and egress rules defined inline. 
I switched to a SG Rule Resource and not it is ok. Thanks
