### PR TITLE
r/aws_eip fix case when aws returns multiple eips from read request

### LINKED ISSUE #5330: EIP scope change incorrectly detected
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform version
Terraform v0.11.7
+ provider.aws v1.28.0
```

### Affected Resource(s)

```
-/+ aws_eip.sandbox_infrastructure_zappi_it_us_east_1b (new resource required)
      id:                                                     "eipalloc-8b296e83" => <computed> (forces new resource)
      allocation_id:                                          "" => <computed>
      association_id:                                         "" => <computed>
      domain:                                                 "standard" => <computed>
      instance:                                               "i-ac10f68c" => <computed>
      network_interface:                                      "" => <computed>
      private_ip:                                             "" => <computed>
      public_ip:                                              "23.21.180.181" => <computed>
      tags.%:                                                 "0" => "4"
      tags.Environment:                                       "" => "sandbox"
      tags.Infrastructure:                                    "" => "kubernetes"
      tags.Name:                                              "" => "us-east-1b.sandbox.infrastructure.zappi.it"
      tags.Role:                                              "" => "operations"
      vpc:                                                    "false" => "true" (forces new resource)
```

### Terraform Configuration Files

```hcl
resource "aws_eip" "sandbox_infrastructure_zappi_it_us_east_1b" {
  vpc = true

  depends_on = [
    "aws_internet_gateway.sandbox_infrastructure_zappi_it"
  ]

  tags = {
    Name            = "us-east-1b.sandbox.infrastructure.zappi.it"
    Environment     = "sandbox"
    Infrastructure  = "kubernetes"
    Role            = "operations"
  }
}
```

### Expected Behavior

Terraform should not incorrectly detect that the VPC scope has changed when it has not, as per the screenshot below:

image

### Actual Behavior

Terraform incorrectly detects that the VPC scope has changed from `false` to `true`.

The example above was not the first incident, but just a more concrete example. Below is the first case we identified:
```
-/+ aws_eip.us-east-1b-uat-kubernetes-zappi-it (new resource required)
      id:                                                 "eipalloc-855eacb4" => <computed> (forces new resource)
      allocation_id:                                      "" => <computed>
      association_id:                                     "" => <computed>
      domain:                                             "standard" => <computed>
      instance:                                           "i-ac10f68c" => <computed>
      network_interface:                                  "" => <computed>
      private_ip:                                         "" => <computed>
      public_ip:                                          "23.21.180.181" => <computed>
      tags.%:                                             "0" => "3"
      tags.KubernetesCluster:                             "" => "uat.kubernetes.zappi.it"
      tags.Name:                                          "" => "us-east-1b.uat.kubernetes.zappi.it"
      tags.kubernetes.io/cluster/uat.kubernetes.zappi.it: "" => "owned"
      vpc:                                                "false" => "true" (forces new resource)

-/+ aws_nat_gateway.us-east-1b-uat-kubernetes-zappi-it (new resource required)
      id:                                                 "nat-050bee284fbf24f25" => <computed> (forces new resource)
      allocation_id:                                      "eipalloc-855eacb4" => "${aws_eip.us-east-1b-uat-kubernetes-zappi-it.id}" (forces new resource)
      network_interface_id:                               "eni-8ff31264" => <computed>
      private_ip:                                         "10.81.2.116" => <computed>
      public_ip:                                          "34.193.141.134" => <computed>
      subnet_id:                                          "subnet-68d74754" => "subnet-68d74754"
      tags.%:                                             "3" => "3"
      tags.KubernetesCluster:                             "uat.kubernetes.zappi.it" => "uat.kubernetes.zappi.it"
      tags.Name:                                          "us-east-1b.uat.kubernetes.zappi.it" => "us-east-1b.uat.kubernetes.zappi.it"
      tags.kubernetes.io/cluster/uat.kubernetes.zappi.it: "owned" => "owned"

  ~ aws_route.private-us-east-1b-0-0-0-0--0
      nat_gateway_id:                                     "nat-050bee284fbf24f25" => "${aws_nat_gateway.us-east-1b-uat-kubernetes-zappi-it.id}"
```

Error during apply:
```
Applying uat terraform plan...
aws_nat_gateway.us-east-1b-uat-kubernetes-zappi-it: Destroying... (ID: nat-050bee284fbf24f25)
aws_nat_gateway.us-east-1b-uat-kubernetes-zappi-it: Still destroying... (ID: nat-050bee284fbf24f25, 10s elapsed)
aws_nat_gateway.us-east-1b-uat-kubernetes-zappi-it: Still destroying... (ID: nat-050bee284fbf24f25, 20s elapsed)
aws_nat_gateway.us-east-1b-uat-kubernetes-zappi-it: Still destroying... (ID: nat-050bee284fbf24f25, 30s elapsed)
aws_nat_gateway.us-east-1b-uat-kubernetes-zappi-it: Still destroying... (ID: nat-050bee284fbf24f25, 40s elapsed)
aws_nat_gateway.us-east-1b-uat-kubernetes-zappi-it: Still destroying... (ID: nat-050bee284fbf24f25, 50s elapsed)
aws_nat_gateway.us-east-1b-uat-kubernetes-zappi-it: Destruction complete after 50s
aws_eip.us-east-1b-uat-kubernetes-zappi-it: Destroying... (ID: eipalloc-855eacb4)

Error: Error applying plan:

1 error(s) occurred:

* aws_eip.us-east-1b-uat-kubernetes-zappi-it (destroy): 1 error(s) occurred:

* aws_eip.us-east-1b-uat-kubernetes-zappi-it: InvalidParameterValue: Invalid value 'eipalloc-855eacb4' for PublicIp. Not a valid IPv4 address.
    status code: 400, request id: 9a2c55d3-aa28-4503-b4f0-51e607f5dd07
```

This behaviour started today at ~08:45 AM UTC for 1 of 3 availability zones for one environment initially. 

However, in subsequent `terraform plan` executions a few minutes later, all of our environments are now affected.

### Steps to Reproduce

We use the following during our CI runs:
1. `terraform init`
2. `terraform plan -no-color --out="${environment}.plan" | tee "${environment}.report"`
3. `terraform apply "${environment}.plan"`

Don't have an isolated reproducible case yet, but will provide if necessary.

### Important Factoids

Running in VPC.
Terraform is run in CI.

### PR DESCRIPTION
**Pull request by rv-aburdine**
Fixes #5330

Changes proposed in this pull request:

* instead of just checking the first element in the addresses response, loop through all of them to see if the one we want is returned

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSAvailabilityZones'

...
```

Wasn't entirely sure how to add an acceptance test for this, given that the acceptance tests hit the AWS api, and the bug in question seems like an inconsistency in AWS's api rather than what terraform itself is doing. If there's a good way to test this via an acceptance test please let me know though 😄

### CODE REVIEW

File: aws/resource_aws_eip.go [hunk 1]
```diff
@@ -181,16 +181,20 @@ func resourceAwsEipRead(d *schema.ResourceData, meta interface{}) error {
...
-		domain == "vpc" && *describeAddresses.Addresses[0].AllocationId != id ||
-		*describeAddresses.Addresses[0].PublicIp != id {
-		if err != nil {
-			return fmt.Errorf("Unable to find EIP: %#v", describeAddresses.Addresses)
+	var address *ec2.Address
+
+	// Sometimes AWS returns EIPs that *aren't* the EIP we're looking for
+	// so we loop over the returned addresses to see if it's in the list of results
+	for _, addr := range describeAddresses.Addresses {
+		if (domain == "vpc" && *addr.AllocationId == id) || *address.PublicIp == id {
```
Comment (bflad) [inline aws/resource_aws_eip.go]: This new logic can cause Terraform to crash due to a typo:

```
=== RUN   TestAccAWSEIP_importEc2Classic

------- Stderr: -------
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1ec009b]

goroutine 215 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsEipRead(0xc420a6f8f0, 0x307b000, 0xc420592c00, 0x2f3d4e0, 0xc420952600)
	/opt/teamcity-agent/work/7be301907ad6c6ab/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_eip.go:189 +0x3bb
```

While we're fixing this, we should also switch the `*` dereferencing to the SDK provided `aws.StringValue()` function to further prevent panics:

```go
if (domain == "vpc" && aws.StringValue(addr.AllocationId) == id) || aws.StringValue(addr.PublicIp) == id {
```

File: aws/resource_aws_eip.go [hunk 2]
```diff
@@ -181,16 +181,20 @@ func resourceAwsEipRead(d *schema.ResourceData, meta interface{}) error {
...
+			address = addr
+			break
 		}
 	}
 
-	address := describeAddresses.Addresses[0]
+	if address == nil {
+		return fmt.Errorf("Unable to find EIP: %#v", describeAddresses.Addresses)
```
Comment (bflad) [inline aws/resource_aws_eip.go]: Instead of returning an error in these cases, we generally prefer to remove the resource from the Terraform state to trigger a resource recreation:

```go
if address == nil {
	log.Printf("[WARN] EIP %q not found, removing from state", d.Id())
	d.SetId("")
	return nil
}
```

**Comment by rv-aburdine** [comment]
@bflad sorry for the delay! Made the changes you requested.

**Comment by bflad** [comment]
This has been released in [version 1.30.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1300-august-02-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
