### PR TITLE
resource/aws_batch_compute_environment: Remove resource from Terraform state when not found instead of returning error

### LINKED ISSUE #12337: Error: One compute environment is expected, but AWS return no compute environment
Cannot create an aws batch environment with the following script. Was working perfectly before I made some changes in the name of the environment.

```
resource "aws_batch_compute_environment" "metaflow_batch" {

  compute_environment_name = "${var.namespace}-metaflow-batch"

  compute_resources {
    instance_role = aws_iam_instance_profile.ecs_instance_role.arn

    instance_type = [
      var.instances.type
    ]

    max_vcpus     = var.instances.max_vcpus
    desired_vcpus = var.instances.desired_vcpus
    min_vcpus     = var.instances.min_vcpus

    security_group_ids = [aws_security_group.db_sg.id]

    subnets = var.vpc_config.subnets


    type = "EC2"
  }

  service_role = aws_iam_role.aws_batch_service_role.arn
  type         = "MANAGED"
  depends_on   = [aws_iam_role_policy_attachment.aws_batch_service_role]
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.21
+ provider.aws v2.52.0

### Affected Resource(s)
AWS BATCH

* aws_XXXXX

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Panic Output

Error: One compute environment is expected, but AWS return no compute environment

### Expected Behavior

Batch environment should have been created

### Actual Behavior

Error: One compute environment is expected, but AWS return no compute environment

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### PR DESCRIPTION
**Pull request by bflad**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Reference: https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/contributing/running-and-writing-acceptance-tests.md#disappears-acceptance-tests
Closes #12337
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/13826

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
* resource/aws_batch_compute_environment: Remove resource from Terraform state when not found instead of returning error
```

Previously:

```
=== CONT  TestAccAWSBatchComputeEnvironment_disappears
    TestAccAWSBatchComputeEnvironment_disappears: testing.go:684: Step 0 error: errors during follow-up refresh:

        Error: One compute environment is expected, but AWS return no compute environment

    TestAccAWSBatchComputeEnvironment_disappears: testing.go:745: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: errors during refresh: One compute environment is expected, but AWS return no compute environment

        State: <nil>
--- FAIL: TestAccAWSBatchComputeEnvironment_disappears (59.70s)
```

Output from acceptance testing:

```
--- PASS: TestAccAWSBatchComputeEnvironment_createEc2WithoutComputeResources (35.53s)
--- PASS: TestAccAWSBatchComputeEnvironment_createSpotWithoutBidPercentage (35.72s)
--- PASS: TestAccAWSBatchComputeEnvironment_createWithNamePrefix (64.40s)
--- PASS: TestAccAWSBatchComputeEnvironment_createUnmanagedWithComputeResources (67.27s)
--- PASS: TestAccAWSBatchComputeEnvironment_createUnmanaged (67.28s)
--- PASS: TestAccAWSBatchComputeEnvironment_disappears (71.92s)
--- PASS: TestAccAWSBatchComputeEnvironment_launchTemplate (72.52s)
--- PASS: TestAccAWSBatchComputeEnvironment_createSpot (72.67s)
--- PASS: TestAccAWSBatchComputeEnvironment_createSpotWithAllocationStrategy (74.33s)
--- PASS: TestAccAWSBatchComputeEnvironment_createEc2 (80.45s)
--- PASS: TestAccAWSBatchComputeEnvironment_createEc2WithTags (81.01s)
--- PASS: TestAccAWSBatchComputeEnvironment_updateState (93.78s)
--- PASS: TestAccAWSBatchComputeEnvironment_updateInstanceType (105.25s)
--- PASS: TestAccAWSBatchComputeEnvironment_updateComputeEnvironmentName (114.21s)
--- PASS: TestAccAWSBatchComputeEnvironment_UpdateLaunchTemplate (114.41s)
--- PASS: TestAccAWSBatchComputeEnvironment_ComputeResources_MaxVcpus (135.46s)
--- PASS: TestAccAWSBatchComputeEnvironment_ComputeResources_DesiredVcpus_Computed (171.29s)
--- PASS: TestAccAWSBatchComputeEnvironment_ComputeResources_MinVcpus (216.35s)
```

### CODE REVIEW

File: aws/resource_aws_batch_compute_environment.go [hunk 1]
```diff
@@ -332,13 +332,17 @@ func resourceAwsBatchComputeEnvironmentRead(d *schema.ResourceData, meta interfa
...
 	if err != nil {
-		return err
+		return fmt.Errorf("error reading Batch Compute Environment (%s): %w", d.Id(), err)
 	}
 
 	if len(result.ComputeEnvironments) == 0 {
-		return fmt.Errorf("One compute environment is expected, but AWS return no compute environment")
+		log.Printf("[WARN] Batch Compute Environment (%s) not found, removing from state", d.Id())
+		d.SetId("")
+		return nil
```
Comment (anGie44) [inline aws/resource_aws_batch_compute_environment.go:343]: Oooo haven't seen this type of disappears case before where it's not caught by an `isAWSErr` 😎
