### PR TITLE
Fix to not return err when instance is already terminated

### LINKED ISSUE #445: Terraform should clean up state when deposed instances already terminated
_This issue was originally opened by @kojiromike as hashicorp/terraform#10905. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version
0.8.2

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance

### Debug Output
```Error applying plan:

3 error(s) occurred:

* aws_instance.apps (deposed #0): Error terminating instance: InvalidInstanceID.NotFound: The instance ID 'i-b4f898ac' does not exist
        status code: 400, request id: 47dc08fc-78f0-4efc-96d5-2c9d84f7b4a7
* aws_instance.apps (deposed #0): Error terminating instance: InvalidInstanceID.NotFound: The instance ID 'i-b7f898af' does not exist
        status code: 400, request id: 371d0501-ba5b-43b6-a61a-01a0b4d3ff6c
* aws_instance.symq (deposed #0): Error terminating instance: InvalidInstanceID.NotFound: The instance ID 'i-86f89e9e' does not exist
        status code: 400, request id: 9ad8ff69-cbe5-47ee-8c7e-19e65e214236
```

### Expected Behavior
If tf is trying to destroy instances, and those instances don't exist, this should not be a fatal error.

### Actual Behavior
TF halted after it couldn't destroy the nonexistent deposed instances.

### PR DESCRIPTION
**Pull request by kterada0509**
Fixes #445 (?)

Changes proposed in this pull request:

* Add error handling for instance delete step
* Add test for disappears resource
* Split waiting delete method.

Output from acceptance testing:

```
$  make testacc TESTARGS='-run=TestAccAWSInstance_disappears'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSInstance_disappears -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSInstance_disappears
=== PAUSE TestAccAWSInstance_disappears
=== CONT  TestAccAWSInstance_disappears
--- PASS: TestAccAWSInstance_disappears (137.68s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	137.738s
...
```

### CODE REVIEW

File: aws/resource_aws_instance.go [hunk 1]
```diff
@@ -1925,9 +1925,16 @@ func awsTerminateInstance(conn *ec2.EC2, id string, timeout time.Duration) error
 		InstanceIds: []*string{aws.String(id)},
 	}
 	if _, err := conn.TerminateInstances(req); err != nil {
+		if ec2err, ok := err.(awserr.Error); ok && ec2err.Code() == "InvalidInstanceID.NotFound" {
```
Comment (bflad) [inline aws/resource_aws_instance.go]: Nit: We have a helper function for these, e.g. `isAWSErr(err, "InvalidInstanceID.NotFound", "")`, definitely not a blocker though

File: aws/resource_aws_instance_test.go [hunk 2]
```diff
@@ -1942,6 +1942,27 @@ func TestAccAWSInstance_creditSpecification_unlimitedCpuCredits_t2Tot3Taint(t *t
 	})
 }
 
+func TestAccAWSInstance_disappears(t *testing.T) {
```
Comment (bflad) [inline aws/resource_aws_instance_test.go]: ❤️

**Comment by bflad** [comment]
This has been released in [version 1.55.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1550-january-10-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
