### PR TITLE
Suppress task definition diffs for equivalent port mappings.

### LINKED ISSUE #3401: aws_ecs_task_definition needs updating even if nothing changes (look at "portMappings")
### Terraform Version
Terraform v0.11.3
+ provider.aws v1.8.0
+ provider.template v1.0.0

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_ecs_task_definition

### Terraform Configuration Files
```hcl
resource "aws_ecs_task_definition" "main" {
  container_definitions = <<EOF
[
    {
        "name": "thename",
        "image": "theimage",
        "cpu": 10,
        "memory": 250,
        "links": [],
        "portMappings": [
            {
                "containerPort": 8888
            }
        ],
        "essential": true,
        "entryPoint": [],
        "command": [],
        "environment" : [
          { "name" : "PORT", "value" : "8888" }
        ],
        "mountPoints": [],
        "volumesFrom": []
    }
]
EOF
  family                = "${basename("${path.cwd}")}"
  network_mode          = "awsvpc"

  volume {
    name      = "shared"
    host_path = "/mnt/efs1/shared"
  }

}
```

### Debug Output
I will paste upon request. Too lazy to edit out sensitive data.

### Panic Output
no panic output

### Expected Behavior
`aws_ecs_task_definition` did not change, so it needs no update

### Actual Behavior
`aws_ecs_task_definition` needed an update

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
I am 99% certain the `portMappings` is to blame. If I delete settings in `portMappings` area, the task does not need an update.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? 
#2339

### PR DESCRIPTION
**Pull request by jmcarp**
When using the `awsvpc` networking mode, aws assigns the value of
`containerPort` to the `hostPort` for each item in `portMappings`. This
leads to spurious diffs if the user doesn't set `hostPort`. This patch
suppresses diffs when using `awsvpc` networking and the `hostPort` field
is unset.

[Fixes #3401]

```
$ make testacc TESTARGS='-run=TestAccAWSAvailabilityZones'
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSEcsTaskDefinition_basic
--- PASS: TestAccAWSEcsTaskDefinition_basic (10.81s)
=== RUN   TestAccAWSEcsTaskDefinition_withScratchVolume
--- PASS: TestAccAWSEcsTaskDefinition_withScratchVolume (5.30s)
=== RUN   TestAccAWSEcsTaskDefinition_withEcsService
--- PASS: TestAccAWSEcsTaskDefinition_withEcsService (47.95s)
=== RUN   TestAccAWSEcsTaskDefinition_withTaskRoleArn
--- PASS: TestAccAWSEcsTaskDefinition_withTaskRoleArn (8.24s)
=== RUN   TestAccAWSEcsTaskDefinition_withNetworkMode
--- PASS: TestAccAWSEcsTaskDefinition_withNetworkMode (6.14s)
=== RUN   TestAccAWSEcsTaskDefinition_constraint
--- PASS: TestAccAWSEcsTaskDefinition_constraint (5.36s)
=== RUN   TestAccAWSEcsTaskDefinition_changeVolumesForcesNewResource
--- PASS: TestAccAWSEcsTaskDefinition_changeVolumesForcesNewResource (10.78s)
=== RUN   TestAccAWSEcsTaskDefinition_arrays
--- PASS: TestAccAWSEcsTaskDefinition_arrays (4.83s)
=== RUN   TestAccAWSEcsTaskDefinition_Fargate
--- PASS: TestAccAWSEcsTaskDefinition_Fargate (7.27s)
=== RUN   TestAccAWSEcsTaskDefinition_ExecutionRole
--- PASS: TestAccAWSEcsTaskDefinition_ExecutionRole (6.29s)
=== RUN   TestAccAWSEcsTaskDefinition_Inactive
--- PASS: TestAccAWSEcsTaskDefinition_Inactive (11.15s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       124.882s
...
```

### CODE REVIEW

File: aws/resource_aws_ecs_task_definition_test.go [hunk 1]
```diff
@@ -649,7 +654,7 @@ TASK_DEFINITION
 `, tdName)
 }
 
-func testAccAWSEcsTaskDefinitionFargate(tdName string) string {
+func testAccAWSEcsTaskDefinitionFargate(tdName, portMappings string) string {
```
Comment (bflad) [inline aws/resource_aws_ecs_task_definition_test.go]: Nitpick: It'd be much better if this was a separate test and test configuration as it does not pertain to the basic functionality of the resource with Fargate

**Comment by bflad** [comment]
This has been released in [version 1.36.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1360-september-13-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
