### PR TITLE
r/aws_eip: Do not disassociate on tags-only update

### LINKED ISSUE #2968: Disassociating EIP when adding tags
### Terraform Version
Terraform v0.11.1
+ provider.aws v1.7.0
+ provider.null v1.0.0
+ provider.template v1.0.0

### Affected Resource(s)
- aws_eip

### Terraform Configuration Files
```hcl
resource "aws_eip" "nat-az-0" {
  vpc = true

  tags {
    Name        = "example"
  }
}

resource "aws_nat_gateway" "az-0" {
  allocation_id = "${aws_eip.nat-az-0.id}"
  subnet_id     = "${aws_subnet.dmz-az-0.id}"
}
```

### Debug Output
https://gist.github.com/williamlord/3618c58363da6a1383f4206b76ce047d

### Expected Behavior
Add tags.

### Actual Behavior
Attempted to disassociate EIP, AWS returned 400 Bad Request, 

### Steps to Reproduce
1. Create EIP without tags and NAT Gateway.
2. Add tags

### References
Attempting to use after https://github.com/terraform-providers/terraform-provider-aws/pull/2768.

### PR DESCRIPTION
**Pull request by bflad**
Fixes #2968 

```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSEIP'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSEIP -timeout 120m
=== RUN   TestAccAWSEIPAssociation_basic
--- PASS: TestAccAWSEIPAssociation_basic (129.19s)
=== RUN   TestAccAWSEIPAssociation_ec2Classic
--- SKIP: TestAccAWSEIPAssociation_ec2Classic (1.24s)
	provider_test.go:69: This test can only run in EC2 Classic, platforms available in us-east-1: ["VPC"]
=== RUN   TestAccAWSEIPAssociation_disappears
--- PASS: TestAccAWSEIPAssociation_disappears (119.98s)
=== RUN   TestAccAWSEIP_importEc2Classic
--- SKIP: TestAccAWSEIP_importEc2Classic (1.02s)
	provider_test.go:69: This test can only run in EC2 Classic, platforms available in us-east-1: ["VPC"]
=== RUN   TestAccAWSEIP_importVpc
--- PASS: TestAccAWSEIP_importVpc (42.70s)
=== RUN   TestAccAWSEIP_basic
--- PASS: TestAccAWSEIP_basic (11.04s)
=== RUN   TestAccAWSEIP_instance
--- PASS: TestAccAWSEIP_instance (283.45s)
=== RUN   TestAccAWSEIP_network_interface
--- PASS: TestAccAWSEIP_network_interface (43.12s)
=== RUN   TestAccAWSEIP_twoEIPsOneNetworkInterface
--- PASS: TestAccAWSEIP_twoEIPsOneNetworkInterface (44.22s)
=== RUN   TestAccAWSEIP_associated_user_private_ip
--- PASS: TestAccAWSEIP_associated_user_private_ip (148.83s)
=== RUN   TestAccAWSEIP_classic_disassociate
--- SKIP: TestAccAWSEIP_classic_disassociate (1.35s)
	provider_test.go:69: This test can only run in EC2 Classic, platforms available in us-west-2: ["VPC"]
=== RUN   TestAccAWSEIP_disappears
--- PASS: TestAccAWSEIP_disappears (8.40s)
=== RUN   TestAccAWSEIPAssociate_not_associated
--- PASS: TestAccAWSEIPAssociate_not_associated (144.82s)
=== RUN   TestAccAWSEIP_tags
--- PASS: TestAccAWSEIP_tags (19.69s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	999.115s
```

### CODE REVIEW

File: aws/resource_aws_eip.go [hunk 1]
```diff
@@ -231,13 +231,27 @@ func resourceAwsEipUpdate(d *schema.ResourceData, meta interface{}) error {
 
 	// If we are updating an EIP that is not newly created, and we are attached to
 	// an instance or interface, detach first.
-	if (d.Get("instance").(string) != "" || d.Get("association_id").(string) != "") && !d.IsNewResource() {
+	disassociate := false
+	if !d.IsNewResource() {
+		if (d.Get("instance").(string) != "") && d.HasChange("instance") {
```
Comment (radeksimko) [inline aws/resource_aws_eip.go]: Nitpicks: The brackets here are unnecessary + I think it would make a bit more sense (when trying to read the code) if it was reversed, i.e.

```go
if d.HasChange("instance") && d.Get("instance").(string) != "" {
```

File: aws/resource_aws_eip.go [hunk 2]
```diff
@@ -231,13 +231,27 @@ func resourceAwsEipUpdate(d *schema.ResourceData, meta interface{}) error {
...
+			disassociate = true
+		} else if (d.Get("association_id").(string) != "") && (d.HasChange("network_interface") || d.HasChange("associate_with_private_ip")) {
```
Comment (radeksimko) [inline aws/resource_aws_eip.go]: Nitpicks: As above - I'd omit the brackets and reverse ordering of `HasChange` and `Get`.

File: aws/resource_aws_eip.go [hunk 3]
```diff
@@ -231,13 +231,27 @@ func resourceAwsEipUpdate(d *schema.ResourceData, meta interface{}) error {
...
 		if err := disassociateEip(d, meta); err != nil {
 			return err
 		}
 	}
 
-	if ok_instance || ok_interface {
+	associate := false
+	if ok_instance && d.HasChange("instance") {
+		associate = true
+	} else if ok_interface && (d.HasChange("network_interface") || d.HasChange("associate_with_private_ip")) {
```
Comment (radeksimko) [inline aws/resource_aws_eip.go]: Nitpicks: In addition to what I already mentioned above would you mind moving the two variable definitions closer to where they're being actually used (meaning `ok_instance` & `ok_interface` in this context).

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.7.1](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#171-january-19-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
