### PR TITLE
[wafregional_web_acl] Add support for ApiGateway

### LINKED ISSUE #6441: Attaching Regional WAF to API Gateway re-applies every update
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform version 0.11.8
AWS Provider version: 1.43.2

### Affected Resource(s)

* aws_wafregional_web_acl_association

### Terraform Configuration Files

I haven't got a simple example that I can share currently, however the aws_wafregional_web_acl_association was originally designed for attaching a regional WAF to an application load balancer. The resource works for an API Gateway, however on refresh it fails to detect that the WAF is associated with the API gateway and re-associates it. 

This appears to be because the aws API check for ListResourcesForWebACL only returns application load balancer results by default, and would require an additional call (passing resource type = API_GATEWAY ) to check for the API Gateway association. 

### Expected Behavior

With no changes, a terraform plan should return nothing to do.

### Actual Behavior

Wants to perform the association on every plan/apply:

+ module.automation_infrastructure.module.module-name-goes-here.aws_wafregional_web_acl_association.waf_association
      id:           <computed>
      resource_arn: "arn:aws:apigateway:ap-southeast-2::/restapis/abqmyzzv6d/stages/dev"
      web_acl_id:   "ebe3ecfd-e4a0-4ec3-ae85-a6c21146c232"

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Testing the ListResourcesForWebACL call:

```
$ aws waf-regional list-resources-for-web-acl --web-acl-id "ebe3ecfd-e4a0-4ec3-ae85-a6c21146c232"
{
    "ResourceArns": []
}
$ aws waf-regional list-resources-for-web-acl --web-acl-id "ebe3ecfd-e4a0-4ec3-ae85-a6c21146c232" --resource-type APPLICATION_LOAD_BALANCER
{
    "ResourceArns": []
}
$ aws waf-regional list-resources-for-web-acl --web-acl-id "ebe3ecfd-e4a0-4ec3-ae85-a6c21146c232" --resource-type API_GATEWAY
{
    "ResourceArns": [
        "arn:aws:apigateway:ap-southeast-2::/restapis/abqmyzzv6d/stages/dev"
    ]
}
```

### References

It doesn't actually specify that the ListResourcesForWebACL call only returns APPLICATION_LOAD_BALANCER results when no resource type is specified, but my testing appears to demonstrate that this is the case.
[AWS ListResourcesForWebACL Documentation](https://docs.aws.amazon.com/waf/latest/APIReference/API_regional_ListResourcesForWebACL.html)

### PR DESCRIPTION
**Pull request by dankolbrs**
Add support for API Gateway to `wafregional_web_acl_association`
by including list of resource types to query for association.

Default behavior of `ListResourcesForWebACL` is to only
return associations of type `APPLICATION_LOAD_BALANCER`. Associations
for API Gateways require explicitly requesting `API_GATEWAY`
resourcetype.

Fixes #6441

Changes proposed in this pull request:

* Iterate through list of ResourceTypes for possible web acl associations to enable API Gateway type in `ListResourcesForWebACL`

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSAvailabilityZones'
==> Checking that code complies with gofmt requirements...
gofmt needs running on the following files:
./aws/resource_aws_kinesis_analytics_application.go
./aws/resource_aws_rds_cluster_parameter_group.go
./aws/resource_aws_rds_cluster_instance.go
./aws/resource_aws_lb_listener.go
./aws/resource_aws_glue_security_configuration.go
./aws/resource_aws_s3_bucket.go
./aws/resource_aws_security_group_migrate_test.go
./aws/resource_aws_sns_topic.go
./aws/provider.go
./aws/resource_aws_swf_domain.go
./aws/resource_aws_neptune_cluster_instance.go
./aws/resource_aws_vpc.go
./aws/resource_aws_guardduty_detector.go
./aws/resource_aws_lb_listener_rule.go
./aws/resource_aws_gamelift_fleet.go
./aws/resource_aws_codedeploy_deployment_group_test.go
./aws/resource_aws_cloudfront_origin_access_identity.go
./aws/resource_aws_spot_fleet_request.go
./aws/resource_aws_db_instance.go
./aws/resource_aws_s3_bucket_inventory.go
./aws/opsworks_layers.go
./aws/resource_aws_neptune_cluster_parameter_group.go
./aws/resource_aws_docdb_cluster_parameter_group.go
./aws/resource_aws_ec2_fleet.go
./aws/resource_aws_ssm_patch_baseline.go
./aws/resource_aws_route53_record.go
./aws/resource_aws_licensemanager_license_configuration.go
./aws/data_source_aws_cloudformation_export_test.go
./aws/resource_aws_s3_bucket_notification.go
./aws/resource_aws_redshift_cluster.go
./aws/resource_aws_ssm_maintenance_window.go
./aws/resource_aws_ram_resource_share.go
./aws/resource_aws_spot_instance_request.go
./aws/resource_aws_emr_security_configuration.go
./aws/resource_aws_dms_replication_instance.go
./aws/resource_aws_instance.go
./aws/resource_aws_organizations_test.go
./aws/resource_aws_api_gateway_integration.go
./aws/validators_test.go
./aws/resource_aws_acmpca_certificate_authority.go
./aws/resource_aws_instance_migrate_test.go
./aws/resource_aws_db_security_group.go
You can use the command: `make fmt` to reformat code.
make: *** [GNUmakefile:28: fmtcheck] Error 1...
```
*Only modified `aws/resource_aws_wafregional_web_acl_association.go` in this PR*

### CODE REVIEW

**Comment by dankolbrs** [comment]
@bflad , Apologies for the direct ping, but I'm not sure what else is needed for a review on this. Is there anything additional needed on this PR?

**Comment by tgwilliams63** [comment]
Does anyone know when this might end up getting merged in?

**Comment by andreafalzetti** [comment]
Is it possible to merge this?

**Comment by salasrod** [comment]
We just ran into this. Is there anything needed for this to be merged?

File: aws/resource_aws_wafregional_web_acl_association.go [hunk 1]
```diff
@@ -74,21 +74,31 @@ func resourceAwsWafRegionalWebAclAssociationRead(d *schema.ResourceData, meta in
...
-		if resourceArn == *listResourceArn {
-			found = true
+	RESOURCE_TYPES := []string{"APPLICATION_LOAD_BALANCER", "API_GATEWAY"}
+	for _, resource := range RESOURCE_TYPES {
+		// List all resources for Web ACL of resource type to see if theres a match
+		params := &wafregional.ListResourcesForWebACLInput{
+			WebACLId:     aws.String(webAclId),
+			ResourceType: aws.String(resource),
+		}
+		resp, err := conn.ListResourcesForWebACL(params)
```
Comment (bflad) [inline aws/resource_aws_wafregional_web_acl_association.go]: Instead of using the `ListResourcesForWebACL` API call, which can be expensive for large environments, is it possible to use [`GetWebACLForResource`](https://docs.aws.amazon.com/sdk-for-go/api/service/wafregional/#WAFRegional.GetWebACLForResource)? Its seems this could perform the lookup without looping through results.

**Comment by bflad** [comment]
Hi again @dankolbrs 👋 Since we haven't heard anything in awhile here we have opted to finish this up in a commit after yours (96a1cd22b08d8d29fb9973d604868e06e40e25b8) that includes acceptance testing with API Gateway resources. The `GetWebACLForResource` API call did in fact work in this scenario so this resource will now use that going forward, which has a few benefits:

* Always a single API call, no looping through associated resources required
* Terraform will show the Web ACL ID of a new association before triggering reassociation, if the association is changed outside of Terraform

Output from acceptance testing:

```
--- PASS: TestAccAWSWafRegionalWebAclAssociation_ResourceArn_ApiGatewayStage (48.06s)
--- PASS: TestAccAWSWafRegionalWebAclAssociation_basic (198.71s)
--- PASS: TestAccAWSWafRegionalWebAclAssociation_multipleAssociations (214.16s)
```

Thanks again for getting this started.

**Comment by bflad** [comment]
This has been released in [version 2.6.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#260-april-10-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by dankolbrs** [comment]
Missed the updates, sorry for the wait. Thanks for finishing it up!
