### PR TITLE
r/ecs_task_definition - fix hash differences for efs volume

### LINKED ISSUE #12190: aws_ecs_task_definition does not detect changes to efs_volume_configuration block
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform -v
Terraform v0.12.12
+ provider.aws v2.50.0
```

### Affected Resource(s)

* aws_ecs_task_definition

### Terraform Configuration Files

```hcl
# main.tf

provider "aws" {
  version = "~> 2.50.0"
  region  = "us-east-1"
}

resource "aws_ecs_task_definition" "main" {
  container_definitions    = file("${path.module}/container-definitions.json")
  family                   = "efs-test"
  network_mode             = "bridge"
  requires_compatibilities = ["EC2"]

  volume {
    name = "efs"

    efs_volume_configuration {
      file_system_id = "fs-12345678"
      root_directory = "/foo/bar"
    }
  }
}
```

```json
[
  {
    "cpu": 0,
    "essential": true,
    "image": "nginx",
    "memory": 2048,
    "memoryReservation": 1024,
    "mountPoints": [{
      "containerPath": "/data",
      "sourceVolume": "efs"
    }],
    "name": "nginx",
    "portMappings": [
      {
        "containerPort": 80,
        "hostPort": 0,
        "protocol": "tcp"
      }
    ],
    "ulimits": [
      {
        "name": "core",
        "softLimit": 0,
        "hardLimit": 0
      }
    ],
    "volumesFrom": []
  }
]
```

### Expected Behavior

Terraform should detect changes to the `efs_volume_configuration` block and update/replace the Task Definition accordingly.

### Actual Behavior

Changes to attributes in the `efs_volume_configuration` block are ignored and `terraform plan` returns clean.

### Steps to Reproduce

1. `terraform apply` the above configuration
2. modify the `root_directory` or `file_system_id` attributes of the `efs_volume_configuration` block
3. `terraform plan`

### PR DESCRIPTION
**Pull request by DrFaust92**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #12190

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource_aws_ecs_task_definition - fix hash differences for `volume` block
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSEcsTaskDefinition_'
--- PASS: TestAccAWSEcsTaskDefinition_basic (73.09s)
--- PASS: TestAccAWSEcsTaskDefinition_withScratchVolume (43.74s)
--- PASS: TestAccAWSEcsTaskDefinition_withDockerVolume (42.88s)
--- PASS: TestAccAWSEcsTaskDefinition_withDockerVolumeMinimalConfig (49.40s)
--- PASS: TestAccAWSEcsTaskDefinition_withEFSVolumeMinimal (62.29s)
--- PASS: TestAccAWSEcsTaskDefinition_withEFSVolume (63.41s)
--- PASS: TestAccAWSEcsTaskDefinition_withEcsService (149.76s)
--- PASS: TestAccAWSEcsTaskDefinition_withTaskRoleArn (48.86s)
--- PASS: TestAccAWSEcsTaskDefinition_withNetworkMode (49.80s)
--- PASS: TestAccAWSEcsTaskDefinition_withIPCMode (48.08s)
--- PASS: TestAccAWSEcsTaskDefinition_withPidMode (49.61s)
--- PASS: TestAccAWSEcsTaskDefinition_constraint (42.94s)
--- PASS: TestAccAWSEcsTaskDefinition_changeVolumesForcesNewResource (72.84s)
--- PASS: TestAccAWSEcsTaskDefinition_arrays (43.73s)
--- PASS: TestAccAWSEcsTaskDefinition_Fargate (59.03s)
--- PASS: TestAccAWSEcsTaskDefinition_ExecutionRole (51.76s)
--- PASS: TestAccAWSEcsTaskDefinition_Inactive (68.68s)
--- PASS: TestAccAWSEcsTaskDefinition_Tags (107.83s)
--- PASS: TestAccAWSEcsTaskDefinition_ProxyConfiguration (56.15s)
--- PASS: TestAccAWSEcsTaskDefinition_inferenceAccelerator (41.28s)
```
As a note to maintainers if possible to merge #12571 prior to this one that would be great

### CODE REVIEW

**Comment by ewbankkit** [comment]
Verified acceptance tests:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSEcsTaskDefinition_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -count 1 -parallel 20 -run=TestAccAWSEcsTaskDefinition_ -timeout 120m
=== RUN   TestAccAWSEcsTaskDefinition_basic
=== PAUSE TestAccAWSEcsTaskDefinition_basic
=== RUN   TestAccAWSEcsTaskDefinition_withScratchVolume
=== PAUSE TestAccAWSEcsTaskDefinition_withScratchVolume
=== RUN   TestAccAWSEcsTaskDefinition_withDockerVolume
=== PAUSE TestAccAWSEcsTaskDefinition_withDockerVolume
=== RUN   TestAccAWSEcsTaskDefinition_withDockerVolumeMinimalConfig
=== PAUSE TestAccAWSEcsTaskDefinition_withDockerVolumeMinimalConfig
=== RUN   TestAccAWSEcsTaskDefinition_withEFSVolumeMinimal
=== PAUSE TestAccAWSEcsTaskDefinition_withEFSVolumeMinimal
=== RUN   TestAccAWSEcsTaskDefinition_withEFSVolume
=== PAUSE TestAccAWSEcsTaskDefinition_withEFSVolume
=== RUN   TestAccAWSEcsTaskDefinition_withTaskScopedDockerVolume
=== PAUSE TestAccAWSEcsTaskDefinition_withTaskScopedDockerVolume
=== RUN   TestAccAWSEcsTaskDefinition_withEcsService
=== PAUSE TestAccAWSEcsTaskDefinition_withEcsService
=== RUN   TestAccAWSEcsTaskDefinition_withTaskRoleArn
=== PAUSE TestAccAWSEcsTaskDefinition_withTaskRoleArn
=== RUN   TestAccAWSEcsTaskDefinition_withNetworkMode
=== PAUSE TestAccAWSEcsTaskDefinition_withNetworkMode
=== RUN   TestAccAWSEcsTaskDefinition_withIPCMode
=== PAUSE TestAccAWSEcsTaskDefinition_withIPCMode
=== RUN   TestAccAWSEcsTaskDefinition_withPidMode
=== PAUSE TestAccAWSEcsTaskDefinition_withPidMode
=== RUN   TestAccAWSEcsTaskDefinition_constraint
=== PAUSE TestAccAWSEcsTaskDefinition_constraint
=== RUN   TestAccAWSEcsTaskDefinition_changeVolumesForcesNewResource
=== PAUSE TestAccAWSEcsTaskDefinition_changeVolumesForcesNewResource
=== RUN   TestAccAWSEcsTaskDefinition_arrays
=== PAUSE TestAccAWSEcsTaskDefinition_arrays
=== RUN   TestAccAWSEcsTaskDefinition_Fargate
=== PAUSE TestAccAWSEcsTaskDefinition_Fargate
=== RUN   TestAccAWSEcsTaskDefinition_ExecutionRole
=== PAUSE TestAccAWSEcsTaskDefinition_ExecutionRole
=== RUN   TestAccAWSEcsTaskDefinition_Inactive
=== PAUSE TestAccAWSEcsTaskDefinition_Inactive
=== RUN   TestAccAWSEcsTaskDefinition_Tags
=== PAUSE TestAccAWSEcsTaskDefinition_Tags
=== RUN   TestAccAWSEcsTaskDefinition_ProxyConfiguration
=== PAUSE TestAccAWSEcsTaskDefinition_ProxyConfiguration
=== RUN   TestAccAWSEcsTaskDefinition_inferenceAccelerator
=== PAUSE TestAccAWSEcsTaskDefinition_inferenceAccelerator
=== CONT  TestAccAWSEcsTaskDefinition_basic
=== CONT  TestAccAWSEcsTaskDefinition_withPidMode
=== CONT  TestAccAWSEcsTaskDefinition_inferenceAccelerator
=== CONT  TestAccAWSEcsTaskDefinition_withIPCMode
=== CONT  TestAccAWSEcsTaskDefinition_withNetworkMode
=== CONT  TestAccAWSEcsTaskDefinition_ProxyConfiguration
=== CONT  TestAccAWSEcsTaskDefinition_withTaskRoleArn
=== CONT  TestAccAWSEcsTaskDefinition_Tags
=== CONT  TestAccAWSEcsTaskDefinition_withEcsService
=== CONT  TestAccAWSEcsTaskDefinition_withTaskScopedDockerVolume
=== CONT  TestAccAWSEcsTaskDefinition_arrays
=== CONT  TestAccAWSEcsTaskDefinition_Inactive
=== CONT  TestAccAWSEcsTaskDefinition_ExecutionRole
=== CONT  TestAccAWSEcsTaskDefinition_withEFSVolume
=== CONT  TestAccAWSEcsTaskDefinition_changeVolumesForcesNewResource
=== CONT  TestAccAWSEcsTaskDefinition_withEFSVolumeMinimal
=== CONT  TestAccAWSEcsTaskDefinition_withDockerVolumeMinimalConfig
=== CONT  TestAccAWSEcsTaskDefinition_withDockerVolume
=== CONT  TestAccAWSEcsTaskDefinition_Fargate
=== CONT  TestAccAWSEcsTaskDefinition_constraint
--- PASS: TestAccAWSEcsTaskDefinition_constraint (27.05s)
=== CONT  TestAccAWSEcsTaskDefinition_withScratchVolume
--- PASS: TestAccAWSEcsTaskDefinition_inferenceAccelerator (27.13s)
--- PASS: TestAccAWSEcsTaskDefinition_withTaskScopedDockerVolume (27.96s)
--- PASS: TestAccAWSEcsTaskDefinition_arrays (27.99s)
--- PASS: TestAccAWSEcsTaskDefinition_withDockerVolumeMinimalConfig (28.06s)
--- PASS: TestAccAWSEcsTaskDefinition_withDockerVolume (28.63s)
--- PASS: TestAccAWSEcsTaskDefinition_withPidMode (28.75s)
--- PASS: TestAccAWSEcsTaskDefinition_withNetworkMode (29.35s)
--- PASS: TestAccAWSEcsTaskDefinition_ExecutionRole (29.35s)
--- PASS: TestAccAWSEcsTaskDefinition_withTaskRoleArn (29.47s)
--- PASS: TestAccAWSEcsTaskDefinition_withIPCMode (29.54s)
--- PASS: TestAccAWSEcsTaskDefinition_ProxyConfiguration (37.57s)
--- PASS: TestAccAWSEcsTaskDefinition_Fargate (37.63s)
--- PASS: TestAccAWSEcsTaskDefinition_withEFSVolume (39.05s)
--- PASS: TestAccAWSEcsTaskDefinition_withEFSVolumeMinimal (39.44s)
--- PASS: TestAccAWSEcsTaskDefinition_basic (43.49s)
--- PASS: TestAccAWSEcsTaskDefinition_Inactive (43.53s)
--- PASS: TestAccAWSEcsTaskDefinition_changeVolumesForcesNewResource (43.65s)
--- PASS: TestAccAWSEcsTaskDefinition_withScratchVolume (22.40s)
--- PASS: TestAccAWSEcsTaskDefinition_Tags (67.59s)
--- PASS: TestAccAWSEcsTaskDefinition_withEcsService (86.42s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	86.513s
```

File: aws/structure.go [hunk 1]
```diff
@@ -699,7 +699,7 @@ func flattenEcsVolumes(list []*ecs.Volume) []map[string]interface{} {
 			l["docker_volume_configuration"] = flattenDockerVolumeConfiguration(volume.DockerVolumeConfiguration)
 		}
 
-		if volume.DockerVolumeConfiguration != nil {
+		if volume.EfsVolumeConfiguration != nil {
```
Comment (deanshelton913) [inline aws/structure.go:702]: I mean, all these changes are cool. but this one is me favorite. ;)

**Comment by DrFaust92** [comment]
As a note to maintainers if possible to merge #12571 prior to this one that would be great
