### PR TITLE
aws_elasticache_replication_group: Implement noop MigrateState for v0..v1

### LINKED ISSUE #8828: aws_elasticache_replication_group: Error: cannot upgrade state, missing MigrateState function
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
2019/05/31 22:24:54 [INFO] Terraform version: 0.12.0  
2019/05/31 22:24:54 [INFO] Go runtime version: go1.12.4
```

### Affected Resource(s)

* aws_elasticache_replication_group

### Actual Behavior

Upon `terraform plan`:

```
2019-05-31T22:20:01.933Z [INFO]  plugin: configuring client automatic mTLS
2019/05/31 22:20:01 [TRACE] vertex "var.cpu_statistic": starting visit (*terraform.NodeRootVariable)
2019-05-31T22:20:01.984Z [INFO]  plugin.terraform-provider-aws_v2.12.0_x4: configuring server automatic mTLS: timestamp=2019-05-31T22:20:01.984Z
aws_elasticache_subnet_group.blah-elasticache: Refreshing state... [id=blah]
aws_sns_topic.blah-elasticache: Refreshing state... [id=blah]
aws_security_group.blah-elasticache: Refreshing state... [id=blah]
aws_security_group_rule.blah-elasticache: Refreshing state... [id=blah]
aws_security_group_rule.blah-elasticache-outbound: Refreshing state... [id=blah]
aws_security_group_rule.blah-elasticache-vpn: Refreshing state... [id=blah]
2019/05/31 22:20:04 [ERROR] <root>: eval: *terraform.EvalReadState, err: cannot upgrade state, missing MigrateState function
2019/05/31 22:20:04 [ERROR] <root>: eval: *terraform.EvalSequence, err: cannot upgrade state, missing MigrateState function
2019/05/31 22:20:04 [TRACE] [walkRefresh] Exiting eval tree: aws_elasticache_replication_group.blah

Error: cannot upgrade state, missing MigrateState function

```

### Steps to Reproduce

For me, `terraform plan`, but you'll likely need a similar state file I assume.

That said I don't expect this to be a non-obvious solution.

The state file in question is from `0.11.7`, so by running this it is updating it in memory.

### PR DESCRIPTION
**Pull request by akatrevorjay**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Fixes #8828 

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
aws_elasticache_replication_group will now migrate v0 resources to v1 in state.
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'
==> Checking that code complies with gofmt requirements...
gofmt needs running on the following files:
./aws/config.go
./aws/data_source_aws_cloudformation_export_test.go
./aws/opsworks_layers.go
./aws/provider.go
./aws/resource_aws_api_gateway_integration.go
./aws/resource_aws_appmesh_virtual_node_migrate_test.go
./aws/resource_aws_cloudfront_origin_access_identity.go
./aws/resource_aws_codedeploy_deployment_group_test.go
./aws/resource_aws_db_instance.go
./aws/resource_aws_db_security_group.go
./aws/resource_aws_dms_replication_instance.go
./aws/resource_aws_docdb_cluster_instance.go
./aws/resource_aws_docdb_cluster_parameter_group.go
./aws/resource_aws_ec2_fleet.go
./aws/resource_aws_emr_security_configuration.go
./aws/resource_aws_gamelift_fleet.go
./aws/resource_aws_glue_security_configuration.go
./aws/resource_aws_guardduty_detector.go
./aws/resource_aws_instance.go
./aws/resource_aws_instance_migrate_test.go
./aws/resource_aws_kinesis_analytics_application.go
./aws/resource_aws_lb_listener.go
./aws/resource_aws_lb_listener_rule.go
./aws/resource_aws_licensemanager_license_configuration.go
./aws/resource_aws_neptune_cluster_instance.go
./aws/resource_aws_neptune_cluster_parameter_group.go
./aws/resource_aws_organizations_test.go
./aws/resource_aws_ram_resource_share.go
./aws/resource_aws_rds_cluster_instance.go
./aws/resource_aws_rds_cluster_parameter_group.go
./aws/resource_aws_redshift_cluster.go
./aws/resource_aws_route53_record.go
./aws/resource_aws_s3_bucket.go
./aws/resource_aws_s3_bucket_inventory.go
./aws/resource_aws_s3_bucket_notification.go
./aws/resource_aws_security_group_migrate_test.go
./aws/resource_aws_sns_topic.go
./aws/resource_aws_spot_fleet_request.go
./aws/resource_aws_spot_instance_request.go
./aws/resource_aws_ssm_maintenance_window.go
./aws/resource_aws_ssm_patch_baseline.go
./aws/resource_aws_swf_domain.go
./aws/resource_aws_vpc.go
./aws/validators_test.go
./aws/resource_aws_acmpca_certificate_authority.go
You can use the command: `make fmt` to reformat code.
make: *** [GNUmakefile:28: fmtcheck] Error 1
...
```

### CODE REVIEW

**Comment by akatrevorjay** [comment]
Hey so, I /think/ that this is fine as a no-op, but please let me know if it's not and I'll update it.

File: aws/resource_aws_elasticache_replication_group.go [hunk 1]
```diff
@@ -223,6 +225,7 @@ func resourceAwsElasticacheReplicationGroup() *schema.Resource {
 			},
 		},
 		SchemaVersion: 1,
+		MigrateState:  resourceAwsElasticacheReplicationGroupMigrateState,
```
Comment (bflad) [inline aws/resource_aws_elasticache_replication_group.go]: Since this is an exceptional case and we want to perform the simplest possible upgrade for compatibility, can you please inline this with the following comments?

```suggestion
		// SchemaVersion: 1 did not include any state changes via MigrateState.
		// Perform a no-operation state upgrade for Terraform 0.12 compatibility.
		// Future state migrations should be performed with StateUpgraders.
		MigrateState: func(v int, inst *terraform.InstanceState, meta interface{}) (*terraform.InstanceState, error) {
			return inst, nil
		},
```

I verified this successfully with a Terraform AWS Provider 1.13.0 `aws_elasticache_replication_group` resource on Terraform 0.12.1. 👍

Comment (akatrevorjay) [reply aws/resource_aws_elasticache_replication_group.go]: Sure, I'll swap over. I do find the replacement more error prone, but either way is fine by me.

Comment (bflad) [reply aws/resource_aws_elasticache_replication_group.go]: Hi @akatrevorjay, the passthrough implementation is not more error prone -- `MigrateState` and dealing with flatmap state migrations in of the Terraform v0.12's Provider SDK has been superseded with JSON state migrations via `StateUpgraders`. In this case, we do not need to worry about doing anything other than passing through the existing `InstanceState` to bypass the Terraform runtime error, which matches the Terraform v0.11 Provider SDK in this situation where `MigrateState` was not implemented alongside a `SchemaVersion` update. We'll be removing the upstream runtime error in the next version of Terraform v0.12 (https://github.com/hashicorp/terraform/pull/21625) to match the old Terraform v0.11 behavior.

Comment (akatrevorjay) [reply aws/resource_aws_elasticache_replication_group.go]: Aha! I didn't see any mention of `StateUpgraders` in the docs at the time of writing this, maybe missed it! Thanks so much for the explanation!
