### PR TITLE
Bug - Fix regex for aws_transfer_user

### LINKED ISSUE #8065: Wrong aws_transfer_user user_name validation
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.7
+ provider.aws v2.3.0
```

### Affected Resource(s)

* aws_transfer_user

### Terraform Configuration Files

```hcl
resource "aws_transfer_user" "user" {
  server_id      = "s-0123456789abcdef0"
  user_name      = "user_name"
  role           = "arn:aws:iam::123456789012:role/transfer"
  home_directory = "/bucket/path"
}
```

### Expected Behavior
Terraform creates the user
```
 + aws_transfer_user.user
      id:             <computed>
      arn:            <computed>
      home_directory: "/bucket/path"
      role:           "arn:aws:iam::123456789012:role/transfer"
      server_id:      "s-0123456789abcdef0"
      user_name:      "user_name"
```

### Actual Behavior
Terraform fails to create users containing an underscore in the name
```
Error: aws_transfer_user.user: "user_name" isn't a valid transfer user name (only lowercase alphanumeric characters are allowed): "user_name"
```

### Steps to Reproduce

1. `terraform plan`

### References
AWS updated their user_name validation. Users with hypens and underscores are valid now.

* https://docs.aws.amazon.com/transfer/latest/userguide/API_CreateUser.html#SFTP-CreateUser-request-UserName

### PR DESCRIPTION
**Pull request by Jukie**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Fixes #8065

Changes proposed in this pull request:

* Allow uppercase, hyphens, and underscores in validation regex
* Add condition for user_name beginning with a hyphen
* Split user_name length validation to separate conditionals

Output from acceptance testing:

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSTransferUserName_validation'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSTransferUserName_validation -timeout 120m
=== RUN   TestAccAWSTransferUserName_validation
=== PAUSE TestAccAWSTransferUserName_validation
=== CONT  TestAccAWSTransferUserName_validation
--- PASS: TestAccAWSTransferUserName_validation (4.36s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	4.466s

...
```

### CODE REVIEW

File: aws/validators.go [hunk 1]
```diff
@@ -117,15 +117,19 @@ func validateTransferServerID(v interface{}, k string) (ws []string, errors []er
...
 	// https://docs.aws.amazon.com/transfer/latest/userguide/API_CreateUser.html
-	pattern := `^[a-z0-9]{3,32}$`
-	if !regexp.MustCompile(pattern).MatchString(value) {
-		errors = append(errors, fmt.Errorf(
-			"%q isn't a valid transfer user name (only lowercase alphanumeric characters are allowed): %q",
-			k, value))
+	if regexp.MustCompile(`[^0-9a-zA-Z_-]`).MatchString(value) {
+		errors = append(errors, fmt.Errorf("%q can only contain alphanumeric characters, underscores, and hyphens", k))
+	}
+	if len(value) < 3 {
```
Comment (charlyx) [inline aws/validators.go]: I would start by checking the length first.
Then the patterns: maybe "cannot begin with a hyphen" first?

File: aws/resource_aws_transfer_user_test.go [hunk 2]
```diff
@@ -125,6 +125,32 @@ func TestAccAWSTransferUser_disappears(t *testing.T) {
...
+				ExpectError: regexp.MustCompile(`"user_name" must be at least 3 characters`),
+			},
+			{
+				Config:      testAccAWSTransferUserName_validation(acctest.RandString(33)),
+				ExpectError: regexp.MustCompile(`"user_name" cannot be more than 32 characters`),
+			},
+			{
+				Config:      testAccAWSTransferUserName_validation("-abcdef"),
+				ExpectError: regexp.MustCompile(`"user_name" cannot begin with a hyphen`),
+			},
```
Comment (charlyx) [inline aws/resource_aws_transfer_user_test.go]: That's cool! You never test that your validation function itself "passes" though.
You might want to add that step.

Comment (dajuke) [reply aws/resource_aws_transfer_user_test.go]: Not sure I understand, is that not what I had already done via below?
```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSTransferUserName_validation'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSTransferUserName_validation -timeout 120m
=== RUN   TestAccAWSTransferUserName_validation
=== PAUSE TestAccAWSTransferUserName_validation
=== CONT  TestAccAWSTransferUserName_validation
--- PASS: TestAccAWSTransferUserName_validation (1.64s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	1.681s

...
```
I'll be sure to add whatever else is required.

File: aws/validators.go (hunk 1 above)
Comment (dajuke) [reply aws/validators.go]: I'll update it now, does this order sound good?

Start with hyphen
Less than 3 characters
More than 32 characters
Regex match

Comment (charlyx) [reply aws/validators.go]: I believe that if the length is not good there is no point checking for characters so I'd start with it.  
Otherwise, you might just use [strings.HasPrefix](https://golang.org/pkg/strings/#HasPrefix) for the "start with hypen" rule.

File: aws/resource_aws_transfer_user_test.go (hunk 2 above)
Comment (charlyx) [reply aws/resource_aws_transfer_user_test.go]: What I meant is that you've tested all the errors but you have no test saying that the name is correct.
They're all expecting errors.

Comment (dajuke) [reply aws/resource_aws_transfer_user_test.go]: Understood, I'll take care of that now.

File: aws/validators.go (hunk 1 above)
Comment (dajuke) [reply aws/validators.go]: Would you rather have a single conditional? I was only concerned about the longer output but if a single is preferred I'll keep that in.

File: aws/resource_aws_transfer_user_test.go (hunk 2 above)
Comment (Jukie) [reply aws/resource_aws_transfer_user_test.go]: @charlyx could you take another look at this?

File: aws/resource_aws_transfer_user_test.go [hunk 3]
```diff
@@ -125,6 +125,37 @@ func TestAccAWSTransferUser_disappears(t *testing.T) {
 	})
 }
 
+func TestAccAWSTransferUserName_validation(t *testing.T) {
```
Comment (bflad) [inline aws/resource_aws_transfer_user_test.go]: Nit: The acceptance test naming format should match: `TestAccAWSTransferUser_XXX` so all testing for the resource can be run with the same prefix and underscore, e.g. `TestAccAWSTransferUser_UserName_Validation`

Otherwise we have this situation (note lack of this new test being run):

```console
$ TF_ACC=1 go test ./aws -v -timeout 120m -parallel 20 -run='TestAccAWSTransferUser_'
=== RUN   TestAccAWSTransferUser_basic
=== PAUSE TestAccAWSTransferUser_basic
=== RUN   TestAccAWSTransferUser_modifyWithOptions
=== PAUSE TestAccAWSTransferUser_modifyWithOptions
=== RUN   TestAccAWSTransferUser_disappears
=== PAUSE TestAccAWSTransferUser_disappears
=== CONT  TestAccAWSTransferUser_basic
=== CONT  TestAccAWSTransferUser_modifyWithOptions
=== CONT  TestAccAWSTransferUser_disappears
--- PASS: TestAccAWSTransferUser_disappears (11.24s)
--- PASS: TestAccAWSTransferUser_basic (12.36s)
--- PASS: TestAccAWSTransferUser_modifyWithOptions (26.95s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	27.993s
```

File: aws/validators.go [hunk 4]
```diff
@@ -117,15 +117,10 @@ func validateTransferServerID(v interface{}, k string) (ws []string, errors []er
 
 func validateTransferUserName(v interface{}, k string) (ws []string, errors []error) {
```
Comment (bflad) [inline aws/validators.go]: Nit: In the future this can be simplified to use Terraform Provider SDK validation functions to show multiple validation errors easier:

```go
ValidateFunc: validation.All(
	validation.StringLenBetween(3, 32),
	validation.StringMatch(regexp.MustCompile(`^[a-zA-Z0-9_]`), "must begin with alphanumeric or underscore character"),
	validation.StringMatch(regexp.MustCompile(`^[a-zA-Z0-9-_]+$`), "must contain only alphanumeric, hyphen, and underscore characters"),
),
```

File: aws/resource_aws_transfer_user_test.go (hunk 3 above)
Comment (Jukie) [reply aws/resource_aws_transfer_user_test.go]: Okay, I'll update and make another PR. Thanks for the review!

File: aws/validators.go (hunk 4 above)
Comment (Jukie) [reply aws/validators.go]: Thanks, I wasn't aware of this. Is there a tech-debt effort to change other validation functions as well in `validators.go`? I'd be happy to help with that.

Comment (bflad) [reply aws/validators.go]: I thought I had created the technical debt issue for that, but apparently not. I'll try to get that created later today.

For now, this is a good start on a similar effort: #7906

Comment (bflad) [reply aws/validators.go]: Here's an initial proposal issue for fixing up `validators.go`: #8424 We should wait until other maintainers submit input to it before beginning any implementation.

**Comment by nywilken** [comment]
This has been released in [version 2.8.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#280-april-26-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
