### PR TITLE
Do not import aws_security_group_rule for associated rules during aws_security_group import

### LINKED ISSUE #6036: All Rules Deleted on Security Group import/apply
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

`Terraform v0.11.8`
`provider.aws v1.38.0`

### Affected Resource(s)

* `aws_security_group`
* `aws_security_group_rule`

### Terraform Configuration Files

```hcl
resource "aws_security_group" "yak-deleterious" {
  name        = "yak-deleterious"
}

resource "aws_security_group_rule" "ingress" {
  security_group_id = "${aws_security_group.yak-deleterious.id}"
  type        = "ingress"
  from_port   = 8000
  to_port     = 8000
  protocol    = "tcp"
  cidr_blocks = ["10.0.3.0/24", "10.0.4.0/24"]
}

resource "aws_security_group_rule" "ingress_2" {
  security_group_id = "${aws_security_group.yak-deleterious.id}"
  type        = "ingress"
  from_port   = 448
  to_port     = 531
  protocol    = "udp"
  ipv6_cidr_blocks = ["2002:db8::/48"]
  self = true
}
```

### Debug Output

https://gist.github.com/YakDriver/b14d8271dc62a181a6820009f8f9c152

### Expected Behavior

The AWS security group rules should _not_ have been deleted.

### Actual Behavior

Both the security group rules were deleted.

### Steps to Reproduce

1. `terraform apply`
1. `terraform state rm aws_security_group.yak-deleterious`
1. `terraform import aws_security_group.yak-deleterious "${sg_id}"`
1. `terraform apply`

### References

* #6027 (PR: Add import functionality for security group rules)
* #4399 (Removing ingress rules from aws_security_group is not detected) - Possibly related
* #2895 (Can't import security_group_rule)
* #3234 (aws_security_group_rule loses track of certain out-of-band changes)
* #1671 (aws_security_group: DependencyViolation: resource sg-XXX has a dependent object) - Possibly related
* #265 - Possibly related
* #5243 (Terraform shows plan changes when inline security group rules are converted to aws_security_group_rule)
* #5631 (similar cause but related to `aws_route_table`)

### PR DESCRIPTION
**Pull request by spavuluri**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #6036
Relates #13408 

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
Do not import `aws_security_group_rule` for associated rules when importing `aws_security_group`
```

<h3>Reason for change</h3>
<p>Automatically importing aws_security_group_rule for associated rules during import of  aws_security_group results in rules being deleted during subsequent apply, unless the configuration is updated to include them. 
Since aws_security_group_rule has support for import functionality, the user has a choice to import  any associated rules.</p>

<h3>Documentation Updates</h3>
There does not seem to be explicit mention of security group rules import as part of security group in the resource documentation.

[Terraform Import Usage](https://www.terraform.io/docs/import/usage.html#complex-imports) has mention of it, a pull request to update will be linked here.

<h3>Acceptance testing</h3>

Output from acceptance testing:
```
$ make testacc TESTARGS='-run=TestAccXXX'

TF_ACC=1 go test ./... -v -count 1 -parallel 1 -run=TestAccAWSSecurityGroup_ -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSSecurityGroup_allowAll
=== PAUSE TestAccAWSSecurityGroup_allowAll
=== RUN   TestAccAWSSecurityGroup_sourceSecurityGroup
=== PAUSE TestAccAWSSecurityGroup_sourceSecurityGroup
=== RUN   TestAccAWSSecurityGroup_IPRangeAndSecurityGroupWithSameRules
=== PAUSE TestAccAWSSecurityGroup_IPRangeAndSecurityGroupWithSameRules
=== RUN   TestAccAWSSecurityGroup_IPRangesWithSameRules
=== PAUSE TestAccAWSSecurityGroup_IPRangesWithSameRules
=== RUN   TestAccAWSSecurityGroup_basic
=== PAUSE TestAccAWSSecurityGroup_basic
=== RUN   TestAccAWSSecurityGroup_egressConfigMode
=== PAUSE TestAccAWSSecurityGroup_egressConfigMode
=== RUN   TestAccAWSSecurityGroup_ingressConfigMode
=== PAUSE TestAccAWSSecurityGroup_ingressConfigMode
=== RUN   TestAccAWSSecurityGroup_ruleGathering
=== PAUSE TestAccAWSSecurityGroup_ruleGathering
=== RUN   TestAccAWSSecurityGroup_forceRevokeRulesTrue
=== PAUSE TestAccAWSSecurityGroup_forceRevokeRulesTrue
=== RUN   TestAccAWSSecurityGroup_forceRevokeRulesFalse
=== PAUSE TestAccAWSSecurityGroup_forceRevokeRulesFalse
=== RUN   TestAccAWSSecurityGroup_ipv6
=== PAUSE TestAccAWSSecurityGroup_ipv6
=== RUN   TestAccAWSSecurityGroup_namePrefix
=== PAUSE TestAccAWSSecurityGroup_namePrefix
=== RUN   TestAccAWSSecurityGroup_self
=== PAUSE TestAccAWSSecurityGroup_self
=== RUN   TestAccAWSSecurityGroup_vpc
=== PAUSE TestAccAWSSecurityGroup_vpc
=== RUN   TestAccAWSSecurityGroup_vpcNegOneIngress
=== PAUSE TestAccAWSSecurityGroup_vpcNegOneIngress
=== RUN   TestAccAWSSecurityGroup_vpcProtoNumIngress
=== PAUSE TestAccAWSSecurityGroup_vpcProtoNumIngress
=== RUN   TestAccAWSSecurityGroup_multiIngress
=== PAUSE TestAccAWSSecurityGroup_multiIngress
=== RUN   TestAccAWSSecurityGroup_change
=== PAUSE TestAccAWSSecurityGroup_change
=== RUN   TestAccAWSSecurityGroup_ruleDescription
=== PAUSE TestAccAWSSecurityGroup_ruleDescription
=== RUN   TestAccAWSSecurityGroup_generatedName
=== PAUSE TestAccAWSSecurityGroup_generatedName
=== RUN   TestAccAWSSecurityGroup_defaultEgressVPC
=== PAUSE TestAccAWSSecurityGroup_defaultEgressVPC
=== RUN   TestAccAWSSecurityGroup_defaultEgressClassic
=== PAUSE TestAccAWSSecurityGroup_defaultEgressClassic
=== RUN   TestAccAWSSecurityGroup_drift
=== PAUSE TestAccAWSSecurityGroup_drift
=== RUN   TestAccAWSSecurityGroup_driftComplex
=== PAUSE TestAccAWSSecurityGroup_driftComplex
=== RUN   TestAccAWSSecurityGroup_invalidCIDRBlock
=== PAUSE TestAccAWSSecurityGroup_invalidCIDRBlock
=== RUN   TestAccAWSSecurityGroup_tags
=== PAUSE TestAccAWSSecurityGroup_tags
=== RUN   TestAccAWSSecurityGroup_CIDRandGroups
=== PAUSE TestAccAWSSecurityGroup_CIDRandGroups
=== RUN   TestAccAWSSecurityGroup_ingressWithCidrAndSGsVPC
=== PAUSE TestAccAWSSecurityGroup_ingressWithCidrAndSGsVPC
=== RUN   TestAccAWSSecurityGroup_ingressWithCidrAndSGsClassic
=== PAUSE TestAccAWSSecurityGroup_ingressWithCidrAndSGsClassic
=== RUN   TestAccAWSSecurityGroup_egressWithPrefixList
=== PAUSE TestAccAWSSecurityGroup_egressWithPrefixList
=== RUN   TestAccAWSSecurityGroup_ingressWithPrefixList
=== PAUSE TestAccAWSSecurityGroup_ingressWithPrefixList
=== RUN   TestAccAWSSecurityGroup_ipv4andipv6Egress
=== PAUSE TestAccAWSSecurityGroup_ipv4andipv6Egress
=== RUN   TestAccAWSSecurityGroup_failWithDiffMismatch
=== PAUSE TestAccAWSSecurityGroup_failWithDiffMismatch
=== RUN   TestAccAWSSecurityGroup_ruleLimitExceededAppend
=== PAUSE TestAccAWSSecurityGroup_ruleLimitExceededAppend
=== RUN   TestAccAWSSecurityGroup_ruleLimitCidrBlockExceededAppend
=== PAUSE TestAccAWSSecurityGroup_ruleLimitCidrBlockExceededAppend
=== RUN   TestAccAWSSecurityGroup_ruleLimitExceededPrepend
=== PAUSE TestAccAWSSecurityGroup_ruleLimitExceededPrepend
=== RUN   TestAccAWSSecurityGroup_ruleLimitExceededAllNew
=== PAUSE TestAccAWSSecurityGroup_ruleLimitExceededAllNew
=== RUN   TestAccAWSSecurityGroup_rulesDropOnError
=== PAUSE TestAccAWSSecurityGroup_rulesDropOnError
=== CONT  TestAccAWSSecurityGroup_allowAll
--- PASS: TestAccAWSSecurityGroup_allowAll (20.61s)
=== CONT  TestAccAWSSecurityGroup_defaultEgressVPC
--- PASS: TestAccAWSSecurityGroup_defaultEgressVPC (28.31s)
=== CONT  TestAccAWSSecurityGroup_rulesDropOnError
--- PASS: TestAccAWSSecurityGroup_rulesDropOnError (30.46s)
=== CONT  TestAccAWSSecurityGroup_ruleLimitExceededAllNew
--- PASS: TestAccAWSSecurityGroup_ruleLimitExceededAllNew (37.80s)
=== CONT  TestAccAWSSecurityGroup_ruleLimitExceededPrepend
--- PASS: TestAccAWSSecurityGroup_ruleLimitExceededPrepend (38.62s)
=== CONT  TestAccAWSSecurityGroup_ruleLimitCidrBlockExceededAppend
--- PASS: TestAccAWSSecurityGroup_ruleLimitCidrBlockExceededAppend (36.57s)
=== CONT  TestAccAWSSecurityGroup_ruleLimitExceededAppend
--- PASS: TestAccAWSSecurityGroup_ruleLimitExceededAppend (33.52s)
=== CONT  TestAccAWSSecurityGroup_failWithDiffMismatch
--- PASS: TestAccAWSSecurityGroup_failWithDiffMismatch (18.89s)
=== CONT  TestAccAWSSecurityGroup_ipv4andipv6Egress
--- PASS: TestAccAWSSecurityGroup_ipv4andipv6Egress (20.83s)
=== CONT  TestAccAWSSecurityGroup_ingressWithPrefixList
--- PASS: TestAccAWSSecurityGroup_ingressWithPrefixList (33.28s)
=== CONT  TestAccAWSSecurityGroup_egressWithPrefixList
--- PASS: TestAccAWSSecurityGroup_egressWithPrefixList (31.57s)
=== CONT  TestAccAWSSecurityGroup_ingressWithCidrAndSGsClassic
--- SKIP: TestAccAWSSecurityGroup_ingressWithCidrAndSGsClassic (0.99s)
    provider_test.go:395: This test can only run in EC2 Classic, platforms available in us-east-1: ["VPC"]
=== CONT  TestAccAWSSecurityGroup_ingressWithCidrAndSGsVPC
--- PASS: TestAccAWSSecurityGroup_ingressWithCidrAndSGsVPC (22.13s)
=== CONT  TestAccAWSSecurityGroup_CIDRandGroups
--- PASS: TestAccAWSSecurityGroup_CIDRandGroups (23.45s)
=== CONT  TestAccAWSSecurityGroup_tags
--- PASS: TestAccAWSSecurityGroup_tags (29.75s)
=== CONT  TestAccAWSSecurityGroup_invalidCIDRBlock
--- PASS: TestAccAWSSecurityGroup_invalidCIDRBlock (1.44s)
=== CONT  TestAccAWSSecurityGroup_driftComplex
--- PASS: TestAccAWSSecurityGroup_driftComplex (23.97s)
=== CONT  TestAccAWSSecurityGroup_drift
--- PASS: TestAccAWSSecurityGroup_drift (16.04s)
=== CONT  TestAccAWSSecurityGroup_defaultEgressClassic
--- SKIP: TestAccAWSSecurityGroup_defaultEgressClassic (1.00s)
    provider_test.go:395: This test can only run in EC2 Classic, platforms available in us-east-1: ["VPC"]
=== CONT  TestAccAWSSecurityGroup_ipv6
--- PASS: TestAccAWSSecurityGroup_ipv6 (36.71s)
=== CONT  TestAccAWSSecurityGroup_generatedName
--- PASS: TestAccAWSSecurityGroup_generatedName (38.59s)
=== CONT  TestAccAWSSecurityGroup_ruleDescription
--- PASS: TestAccAWSSecurityGroup_ruleDescription (129.85s)
=== CONT  TestAccAWSSecurityGroup_change
--- PASS: TestAccAWSSecurityGroup_change (126.89s)
=== CONT  TestAccAWSSecurityGroup_multiIngress
--- PASS: TestAccAWSSecurityGroup_multiIngress (59.63s)
=== CONT  TestAccAWSSecurityGroup_vpcProtoNumIngress
--- PASS: TestAccAWSSecurityGroup_vpcProtoNumIngress (97.20s)
=== CONT  TestAccAWSSecurityGroup_vpcNegOneIngress
--- PASS: TestAccAWSSecurityGroup_vpcNegOneIngress (77.47s)
=== CONT  TestAccAWSSecurityGroup_vpc
--- PASS: TestAccAWSSecurityGroup_vpc (37.32s)
=== CONT  TestAccAWSSecurityGroup_self
--- PASS: TestAccAWSSecurityGroup_self (36.77s)
=== CONT  TestAccAWSSecurityGroup_namePrefix
--- PASS: TestAccAWSSecurityGroup_namePrefix (32.91s)
=== CONT  TestAccAWSSecurityGroup_egressConfigMode
--- PASS: TestAccAWSSecurityGroup_egressConfigMode (82.82s)
=== CONT  TestAccAWSSecurityGroup_forceRevokeRulesFalse
--- PASS: TestAccAWSSecurityGroup_forceRevokeRulesFalse (682.93s)
=== CONT  TestAccAWSSecurityGroup_forceRevokeRulesTrue
--- PASS: TestAccAWSSecurityGroup_forceRevokeRulesTrue (746.88s)
=== CONT  TestAccAWSSecurityGroup_ruleGathering
--- PASS: TestAccAWSSecurityGroup_ruleGathering (67.95s)
=== CONT  TestAccAWSSecurityGroup_ingressConfigMode
--- PASS: TestAccAWSSecurityGroup_ingressConfigMode (74.36s)
=== CONT  TestAccAWSSecurityGroup_IPRangesWithSameRules
--- PASS: TestAccAWSSecurityGroup_IPRangesWithSameRules (45.67s)
=== CONT  TestAccAWSSecurityGroup_basic
--- PASS: TestAccAWSSecurityGroup_basic (40.30s)
=== CONT  TestAccAWSSecurityGroup_IPRangeAndSecurityGroupWithSameRules
--- PASS: TestAccAWSSecurityGroup_IPRangeAndSecurityGroupWithSameRules (43.36s)
=== CONT  TestAccAWSSecurityGroup_sourceSecurityGroup
--- PASS: TestAccAWSSecurityGroup_sourceSecurityGroup (46.78s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	2955.391s
...
```

### CODE REVIEW

**Comment by spavuluri** [comment]
As noted in Documentation Updates above, here's the PR link to the terraform documentation change https://github.com/hashicorp/terraform/pull/24525.

File: aws/resource_aws_security_group_test.go [hunk 1]
```diff
@@ -642,7 +642,7 @@ func TestAccAWSSecurityGroup_IPRangeAndSecurityGroupWithSameRules(t *testing.T)
 			{
 				ResourceName:            resourceName,
 				ImportState:             true,
-				ImportStateCheck:        testAccAWSSecurityGroupImportStateCheckFunc(4),
+				ImportStateCheck:        testAccAWSSecurityGroupImportStateCheckFunc(1),
```
Comment (bflad) [inline aws/resource_aws_security_group_test.go:645]: Drive-by note: For the testing updates, we can remove the `ImportStateCheck` and should ensure the `ImportStateVerify`/`ImportStateVerifyIgnore` are uncommented. 👍

Comment (spavuluri) [reply aws/resource_aws_security_group_test.go]: @bflad  Modified the acceptance tests to remove `ImportStateCheck` and uncommented `ImportStateVerify`/`ImportStateVerifyIgnore`.
Well, in all except 2 cases related to the drift rules. 
In rules with cidr_block drift, import only creates a single ingress rule with the cidr_blocks de-normalized. And during subsequent apply, its normalized to create the 2 ingress rules. So those checks don’t lend themselves to these cases.

**Comment by spavuluri** [comment]
Acceptance test re-run output after testing updates per feedback to remove  `ImportStateCheck` and uncommented `ImportStateVerify`/`ImportStateVerifyIgnore`.

```
$ make testacc TESTARGS='-run=TestAccXXX'
TF_ACC=1 go test ./... -v -count 1 -parallel 1 -run=TestAccAWSSecurityGroup_ -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSSecurityGroup_allowAll
=== PAUSE TestAccAWSSecurityGroup_allowAll
=== RUN   TestAccAWSSecurityGroup_sourceSecurityGroup
=== PAUSE TestAccAWSSecurityGroup_sourceSecurityGroup
=== RUN   TestAccAWSSecurityGroup_IPRangeAndSecurityGroupWithSameRules
=== PAUSE TestAccAWSSecurityGroup_IPRangeAndSecurityGroupWithSameRules
=== RUN   TestAccAWSSecurityGroup_IPRangesWithSameRules
=== PAUSE TestAccAWSSecurityGroup_IPRangesWithSameRules
=== RUN   TestAccAWSSecurityGroup_basic
=== PAUSE TestAccAWSSecurityGroup_basic
=== RUN   TestAccAWSSecurityGroup_egressConfigMode
=== PAUSE TestAccAWSSecurityGroup_egressConfigMode
=== RUN   TestAccAWSSecurityGroup_ingressConfigMode
=== PAUSE TestAccAWSSecurityGroup_ingressConfigMode
=== RUN   TestAccAWSSecurityGroup_ruleGathering
=== PAUSE TestAccAWSSecurityGroup_ruleGathering
=== RUN   TestAccAWSSecurityGroup_forceRevokeRulesTrue
=== PAUSE TestAccAWSSecurityGroup_forceRevokeRulesTrue
=== RUN   TestAccAWSSecurityGroup_forceRevokeRulesFalse
=== PAUSE TestAccAWSSecurityGroup_forceRevokeRulesFalse
=== RUN   TestAccAWSSecurityGroup_ipv6
=== PAUSE TestAccAWSSecurityGroup_ipv6
=== RUN   TestAccAWSSecurityGroup_namePrefix
=== PAUSE TestAccAWSSecurityGroup_namePrefix
=== RUN   TestAccAWSSecurityGroup_self
=== PAUSE TestAccAWSSecurityGroup_self
=== RUN   TestAccAWSSecurityGroup_vpc
=== PAUSE TestAccAWSSecurityGroup_vpc
=== RUN   TestAccAWSSecurityGroup_vpcNegOneIngress
=== PAUSE TestAccAWSSecurityGroup_vpcNegOneIngress
=== RUN   TestAccAWSSecurityGroup_vpcProtoNumIngress
=== PAUSE TestAccAWSSecurityGroup_vpcProtoNumIngress
=== RUN   TestAccAWSSecurityGroup_multiIngress
=== PAUSE TestAccAWSSecurityGroup_multiIngress
=== RUN   TestAccAWSSecurityGroup_change
=== PAUSE TestAccAWSSecurityGroup_change
=== RUN   TestAccAWSSecurityGroup_ruleDescription
=== PAUSE TestAccAWSSecurityGroup_ruleDescription
=== RUN   TestAccAWSSecurityGroup_generatedName
=== PAUSE TestAccAWSSecurityGroup_generatedName
=== RUN   TestAccAWSSecurityGroup_defaultEgressVPC
=== PAUSE TestAccAWSSecurityGroup_defaultEgressVPC
=== RUN   TestAccAWSSecurityGroup_defaultEgressClassic
=== PAUSE TestAccAWSSecurityGroup_defaultEgressClassic
=== RUN   TestAccAWSSecurityGroup_drift
=== PAUSE TestAccAWSSecurityGroup_drift
=== RUN   TestAccAWSSecurityGroup_driftComplex
=== PAUSE TestAccAWSSecurityGroup_driftComplex
=== RUN   TestAccAWSSecurityGroup_invalidCIDRBlock
=== PAUSE TestAccAWSSecurityGroup_invalidCIDRBlock
=== RUN   TestAccAWSSecurityGroup_tags
=== PAUSE TestAccAWSSecurityGroup_tags
=== RUN   TestAccAWSSecurityGroup_CIDRandGroups
=== PAUSE TestAccAWSSecurityGroup_CIDRandGroups
=== RUN   TestAccAWSSecurityGroup_ingressWithCidrAndSGsVPC
=== PAUSE TestAccAWSSecurityGroup_ingressWithCidrAndSGsVPC
=== RUN   TestAccAWSSecurityGroup_ingressWithCidrAndSGsClassic
=== PAUSE TestAccAWSSecurityGroup_ingressWithCidrAndSGsClassic
=== RUN   TestAccAWSSecurityGroup_egressWithPrefixList
=== PAUSE TestAccAWSSecurityGroup_egressWithPrefixList
=== RUN   TestAccAWSSecurityGroup_ingressWithPrefixList
=== PAUSE TestAccAWSSecurityGroup_ingressWithPrefixList
=== RUN   TestAccAWSSecurityGroup_ipv4andipv6Egress
=== PAUSE TestAccAWSSecurityGroup_ipv4andipv6Egress
=== RUN   TestAccAWSSecurityGroup_failWithDiffMismatch
=== PAUSE TestAccAWSSecurityGroup_failWithDiffMismatch
=== RUN   TestAccAWSSecurityGroup_ruleLimitExceededAppend
=== PAUSE TestAccAWSSecurityGroup_ruleLimitExceededAppend
=== RUN   TestAccAWSSecurityGroup_ruleLimitCidrBlockExceededAppend
=== PAUSE TestAccAWSSecurityGroup_ruleLimitCidrBlockExceededAppend
=== RUN   TestAccAWSSecurityGroup_ruleLimitExceededPrepend
=== PAUSE TestAccAWSSecurityGroup_ruleLimitExceededPrepend
=== RUN   TestAccAWSSecurityGroup_ruleLimitExceededAllNew
=== PAUSE TestAccAWSSecurityGroup_ruleLimitExceededAllNew
=== RUN   TestAccAWSSecurityGroup_rulesDropOnError
=== PAUSE TestAccAWSSecurityGroup_rulesDropOnError
=== CONT  TestAccAWSSecurityGroup_allowAll
--- PASS: TestAccAWSSecurityGroup_allowAll (34.76s)
=== CONT  TestAccAWSSecurityGroup_defaultEgressVPC
--- PASS: TestAccAWSSecurityGroup_defaultEgressVPC (29.61s)
=== CONT  TestAccAWSSecurityGroup_rulesDropOnError
--- PASS: TestAccAWSSecurityGroup_rulesDropOnError (32.99s)
=== CONT  TestAccAWSSecurityGroup_ruleLimitExceededAllNew
--- PASS: TestAccAWSSecurityGroup_ruleLimitExceededAllNew (38.98s)
=== CONT  TestAccAWSSecurityGroup_ruleLimitExceededPrepend
--- PASS: TestAccAWSSecurityGroup_ruleLimitExceededPrepend (43.21s)
=== CONT  TestAccAWSSecurityGroup_ruleLimitCidrBlockExceededAppend
--- PASS: TestAccAWSSecurityGroup_ruleLimitCidrBlockExceededAppend (40.11s)
=== CONT  TestAccAWSSecurityGroup_ruleLimitExceededAppend
--- PASS: TestAccAWSSecurityGroup_ruleLimitExceededAppend (33.99s)
=== CONT  TestAccAWSSecurityGroup_failWithDiffMismatch
--- PASS: TestAccAWSSecurityGroup_failWithDiffMismatch (46.84s)
=== CONT  TestAccAWSSecurityGroup_ipv4andipv6Egress
--- PASS: TestAccAWSSecurityGroup_ipv4andipv6Egress (25.68s)
=== CONT  TestAccAWSSecurityGroup_ingressWithPrefixList
--- PASS: TestAccAWSSecurityGroup_ingressWithPrefixList (36.50s)
=== CONT  TestAccAWSSecurityGroup_egressWithPrefixList
--- PASS: TestAccAWSSecurityGroup_egressWithPrefixList (31.11s)
=== CONT  TestAccAWSSecurityGroup_ingressWithCidrAndSGsClassic
--- SKIP: TestAccAWSSecurityGroup_ingressWithCidrAndSGsClassic (1.05s)
    provider_test.go:395: This test can only run in EC2 Classic, platforms available in us-east-1: ["VPC"]
=== CONT  TestAccAWSSecurityGroup_ingressWithCidrAndSGsVPC
--- PASS: TestAccAWSSecurityGroup_ingressWithCidrAndSGsVPC (40.30s)
=== CONT  TestAccAWSSecurityGroup_CIDRandGroups
--- PASS: TestAccAWSSecurityGroup_CIDRandGroups (30.86s)
=== CONT  TestAccAWSSecurityGroup_tags
--- PASS: TestAccAWSSecurityGroup_tags (25.26s)
=== CONT  TestAccAWSSecurityGroup_invalidCIDRBlock
--- PASS: TestAccAWSSecurityGroup_invalidCIDRBlock (1.41s)
=== CONT  TestAccAWSSecurityGroup_driftComplex
--- PASS: TestAccAWSSecurityGroup_driftComplex (66.59s)
=== CONT  TestAccAWSSecurityGroup_drift
--- PASS: TestAccAWSSecurityGroup_drift (14.38s)
=== CONT  TestAccAWSSecurityGroup_defaultEgressClassic
--- SKIP: TestAccAWSSecurityGroup_defaultEgressClassic (1.06s)
    provider_test.go:395: This test can only run in EC2 Classic, platforms available in us-east-1: ["VPC"]
=== CONT  TestAccAWSSecurityGroup_ipv6
--- PASS: TestAccAWSSecurityGroup_ipv6 (47.28s)
=== CONT  TestAccAWSSecurityGroup_generatedName
--- PASS: TestAccAWSSecurityGroup_generatedName (37.97s)
=== CONT  TestAccAWSSecurityGroup_ruleDescription
--- PASS: TestAccAWSSecurityGroup_ruleDescription (140.14s)
=== CONT  TestAccAWSSecurityGroup_change
--- PASS: TestAccAWSSecurityGroup_change (87.88s)
=== CONT  TestAccAWSSecurityGroup_multiIngress
--- PASS: TestAccAWSSecurityGroup_multiIngress (40.89s)
=== CONT  TestAccAWSSecurityGroup_vpcProtoNumIngress
--- PASS: TestAccAWSSecurityGroup_vpcProtoNumIngress (35.75s)
=== CONT  TestAccAWSSecurityGroup_vpcNegOneIngress
--- PASS: TestAccAWSSecurityGroup_vpcNegOneIngress (56.10s)
=== CONT  TestAccAWSSecurityGroup_vpc
--- PASS: TestAccAWSSecurityGroup_vpc (40.00s)
=== CONT  TestAccAWSSecurityGroup_self
--- PASS: TestAccAWSSecurityGroup_self (36.50s)
=== CONT  TestAccAWSSecurityGroup_namePrefix
--- PASS: TestAccAWSSecurityGroup_namePrefix (36.72s)
=== CONT  TestAccAWSSecurityGroup_egressConfigMode
--- PASS: TestAccAWSSecurityGroup_egressConfigMode (103.38s)
=== CONT  TestAccAWSSecurityGroup_forceRevokeRulesFalse
--- PASS: TestAccAWSSecurityGroup_forceRevokeRulesFalse (692.40s)
=== CONT  TestAccAWSSecurityGroup_forceRevokeRulesTrue
--- PASS: TestAccAWSSecurityGroup_forceRevokeRulesTrue (723.41s)
=== CONT  TestAccAWSSecurityGroup_ruleGathering
--- PASS: TestAccAWSSecurityGroup_ruleGathering (57.32s)
=== CONT  TestAccAWSSecurityGroup_ingressConfigMode
--- PASS: TestAccAWSSecurityGroup_ingressConfigMode (69.48s)
=== CONT  TestAccAWSSecurityGroup_IPRangesWithSameRules
--- PASS: TestAccAWSSecurityGroup_IPRangesWithSameRules (41.54s)
=== CONT  TestAccAWSSecurityGroup_basic
--- PASS: TestAccAWSSecurityGroup_basic (42.58s)
=== CONT  TestAccAWSSecurityGroup_IPRangeAndSecurityGroupWithSameRules
--- PASS: TestAccAWSSecurityGroup_IPRangeAndSecurityGroupWithSameRules (44.21s)
=== CONT  TestAccAWSSecurityGroup_sourceSecurityGroup
--- PASS: TestAccAWSSecurityGroup_sourceSecurityGroup (44.01s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	2954.103s
```

File: aws/import_aws_security_group.go [hunk 2]
```diff
@@ -9,9 +9,6 @@ import (
 	"github.com/terraform-providers/terraform-provider-aws/aws/internal/naming"
 )
 
-// Security group import fans out to multiple resources due to the
-// security group rules. Instead of creating one resource with nested
-// rules, we use the best practices approach of one resource per rule.
 func resourceAwsSecurityGroupImportState(
```
Comment (anGie44) [inline aws/import_aws_security_group.go:12]: Hi @spavuluri! In following with the convention we now more commonly use for single resource import, we can remove functionality described in this file and move to using the `schema.ImportStatePassthrough` reference in the `resource_aws_security_group.go` file's `Importer` field since only the GroupID is needed. At import time, the resource will still undergo the staterefresh via `SGStateRefreshFunc` in the `Read` function but the only additional step we need to add to the resource's `Read` function will be to set the `name_prefix` as done in this file via 
```
d.Set("name_prefix", aws.StringValue(naming.NamePrefixFromName(aws.StringValue(sg.GroupName)))

```

File: aws/resource_aws_security_group_test.go [hunk 3]
```diff
@@ -1648,7 +1632,11 @@ func TestAccAWSSecurityGroup_driftComplex(t *testing.T) {
...
 				ResourceName:     resourceName,
 				ImportState:      true,
-				ImportStateCheck: testAccAWSSecurityGroupImportStateCheckFunc(5),
+				ImportStateCheck: testAccAWSSecurityGroupImportStateCheckFunc(1),
+				// Below checks commented out, but will check state count.
+				// In rules with cidr_block drift, import only creates a single ingress
+				// rule with the cidr_blocks de-normalized. During subsequent apply, its
+				// normalized to create the 2 ingress rules seen in checks above.
 				//ImportStateVerify:       true,
 				//ImportStateVerifyIgnore: []string{"revoke_rules_on_delete"},
```
Comment (anGie44) [inline aws/resource_aws_security_group_test.go:1641]: In cases like these, we can remove the state count check and uncomment the `ImportStateVerify` and `ImportStateVerifyIgnore` fields and but also add the `ingress` and `egress` attributes to this string array as we expect there to be a non-empty plan. I'd leave the comments you have though to describe this expectation in behavior.

File: aws/resource_aws_security_group_test.go [hunk 4]
```diff
@@ -1581,7 +1561,11 @@ func TestAccAWSSecurityGroup_drift(t *testing.T) {
...
 				ImportState:      true,
-				ImportStateCheck: testAccAWSSecurityGroupImportStateCheckFunc(2),
+				ImportStateCheck: testAccAWSSecurityGroupImportStateCheckFunc(1),
+				// Below checks commented out, but will check state count.
+				// In rules with cidr_block drift, import only creates a single ingress
+				// rule with the cidr_blocks de-normalized. During subsequent apply, its
+				// normalized to create the 2 ingress rules seen in checks above.
 				//ImportStateVerify:       true,
 				//ImportStateVerifyIgnore: []string{"revoke_rules_on_delete"},
 			},
```
Comment (anGie44) [inline aws/resource_aws_security_group_test.go:1571]: similar comment as below

**Comment by spavuluri** [comment]
@anGie44 good info, thanks for the review and feedback. Will address these soon as I get a chance.

**Comment by spavuluri** [comment]
Acceptance test run after re-working per feedback provided.

```
TF_ACC=1 go test ./... -v -count 1 -parallel 1 -run=TestAccAWSSecurityGroup_ -timeout 120m

=== RUN   TestAccAWSSecurityGroup_allowAll
=== PAUSE TestAccAWSSecurityGroup_allowAll
=== RUN   TestAccAWSSecurityGroup_sourceSecurityGroup
=== PAUSE TestAccAWSSecurityGroup_sourceSecurityGroup
=== RUN   TestAccAWSSecurityGroup_IPRangeAndSecurityGroupWithSameRules
=== PAUSE TestAccAWSSecurityGroup_IPRangeAndSecurityGroupWithSameRules
=== RUN   TestAccAWSSecurityGroup_IPRangesWithSameRules
=== PAUSE TestAccAWSSecurityGroup_IPRangesWithSameRules
=== RUN   TestAccAWSSecurityGroup_basic
=== PAUSE TestAccAWSSecurityGroup_basic
=== RUN   TestAccAWSSecurityGroup_egressConfigMode
=== PAUSE TestAccAWSSecurityGroup_egressConfigMode
=== RUN   TestAccAWSSecurityGroup_ingressConfigMode
=== PAUSE TestAccAWSSecurityGroup_ingressConfigMode
=== RUN   TestAccAWSSecurityGroup_ruleGathering
=== PAUSE TestAccAWSSecurityGroup_ruleGathering
=== RUN   TestAccAWSSecurityGroup_forceRevokeRulesTrue
=== PAUSE TestAccAWSSecurityGroup_forceRevokeRulesTrue
=== RUN   TestAccAWSSecurityGroup_forceRevokeRulesFalse
=== PAUSE TestAccAWSSecurityGroup_forceRevokeRulesFalse
=== RUN   TestAccAWSSecurityGroup_ipv6
=== PAUSE TestAccAWSSecurityGroup_ipv6
=== RUN   TestAccAWSSecurityGroup_namePrefix
=== PAUSE TestAccAWSSecurityGroup_namePrefix
=== RUN   TestAccAWSSecurityGroup_self
=== PAUSE TestAccAWSSecurityGroup_self
=== RUN   TestAccAWSSecurityGroup_vpc
=== PAUSE TestAccAWSSecurityGroup_vpc
=== RUN   TestAccAWSSecurityGroup_vpcNegOneIngress
=== PAUSE TestAccAWSSecurityGroup_vpcNegOneIngress
=== RUN   TestAccAWSSecurityGroup_vpcProtoNumIngress
=== PAUSE TestAccAWSSecurityGroup_vpcProtoNumIngress
=== RUN   TestAccAWSSecurityGroup_multiIngress
=== PAUSE TestAccAWSSecurityGroup_multiIngress
=== RUN   TestAccAWSSecurityGroup_change
=== PAUSE TestAccAWSSecurityGroup_change
=== RUN   TestAccAWSSecurityGroup_ruleDescription
=== PAUSE TestAccAWSSecurityGroup_ruleDescription
=== RUN   TestAccAWSSecurityGroup_generatedName
=== PAUSE TestAccAWSSecurityGroup_generatedName
=== RUN   TestAccAWSSecurityGroup_defaultEgressVPC
=== PAUSE TestAccAWSSecurityGroup_defaultEgressVPC
=== RUN   TestAccAWSSecurityGroup_defaultEgressClassic
=== PAUSE TestAccAWSSecurityGroup_defaultEgressClassic
=== RUN   TestAccAWSSecurityGroup_drift
=== PAUSE TestAccAWSSecurityGroup_drift
=== RUN   TestAccAWSSecurityGroup_driftComplex
=== PAUSE TestAccAWSSecurityGroup_driftComplex
=== RUN   TestAccAWSSecurityGroup_invalidCIDRBlock
=== PAUSE TestAccAWSSecurityGroup_invalidCIDRBlock
=== RUN   TestAccAWSSecurityGroup_tags
=== PAUSE TestAccAWSSecurityGroup_tags
=== RUN   TestAccAWSSecurityGroup_CIDRandGroups
=== PAUSE TestAccAWSSecurityGroup_CIDRandGroups
=== RUN   TestAccAWSSecurityGroup_ingressWithCidrAndSGsVPC
=== PAUSE TestAccAWSSecurityGroup_ingressWithCidrAndSGsVPC
=== RUN   TestAccAWSSecurityGroup_ingressWithCidrAndSGsClassic
=== PAUSE TestAccAWSSecurityGroup_ingressWithCidrAndSGsClassic
=== RUN   TestAccAWSSecurityGroup_egressWithPrefixList
=== PAUSE TestAccAWSSecurityGroup_egressWithPrefixList
=== RUN   TestAccAWSSecurityGroup_ingressWithPrefixList
=== PAUSE TestAccAWSSecurityGroup_ingressWithPrefixList
=== RUN   TestAccAWSSecurityGroup_ipv4andipv6Egress
=== PAUSE TestAccAWSSecurityGroup_ipv4andipv6Egress
=== RUN   TestAccAWSSecurityGroup_failWithDiffMismatch
=== PAUSE TestAccAWSSecurityGroup_failWithDiffMismatch
=== RUN   TestAccAWSSecurityGroup_ruleLimitExceededAppend
=== PAUSE TestAccAWSSecurityGroup_ruleLimitExceededAppend
=== RUN   TestAccAWSSecurityGroup_ruleLimitCidrBlockExceededAppend
=== PAUSE TestAccAWSSecurityGroup_ruleLimitCidrBlockExceededAppend
=== RUN   TestAccAWSSecurityGroup_ruleLimitExceededPrepend
=== PAUSE TestAccAWSSecurityGroup_ruleLimitExceededPrepend
=== RUN   TestAccAWSSecurityGroup_ruleLimitExceededAllNew
=== PAUSE TestAccAWSSecurityGroup_ruleLimitExceededAllNew
=== RUN   TestAccAWSSecurityGroup_rulesDropOnError
=== PAUSE TestAccAWSSecurityGroup_rulesDropOnError
=== CONT  TestAccAWSSecurityGroup_allowAll
--- PASS: TestAccAWSSecurityGroup_allowAll (10.95s)
=== CONT  TestAccAWSSecurityGroup_defaultEgressVPC
--- PASS: TestAccAWSSecurityGroup_defaultEgressVPC (8.68s)
=== CONT  TestAccAWSSecurityGroup_rulesDropOnError
--- PASS: TestAccAWSSecurityGroup_rulesDropOnError (15.89s)
=== CONT  TestAccAWSSecurityGroup_ruleLimitExceededAllNew
--- PASS: TestAccAWSSecurityGroup_ruleLimitExceededAllNew (20.41s)
=== CONT  TestAccAWSSecurityGroup_ruleLimitExceededPrepend
--- PASS: TestAccAWSSecurityGroup_ruleLimitExceededPrepend (26.37s)
=== CONT  TestAccAWSSecurityGroup_ruleLimitCidrBlockExceededAppend
--- PASS: TestAccAWSSecurityGroup_ruleLimitCidrBlockExceededAppend (22.27s)
=== CONT  TestAccAWSSecurityGroup_ruleLimitExceededAppend
--- PASS: TestAccAWSSecurityGroup_ruleLimitExceededAppend (20.13s)
=== CONT  TestAccAWSSecurityGroup_failWithDiffMismatch
--- PASS: TestAccAWSSecurityGroup_failWithDiffMismatch (10.53s)
=== CONT  TestAccAWSSecurityGroup_ipv4andipv6Egress
--- PASS: TestAccAWSSecurityGroup_ipv4andipv6Egress (9.05s)
=== CONT  TestAccAWSSecurityGroup_ingressWithPrefixList
--- PASS: TestAccAWSSecurityGroup_ingressWithPrefixList (22.72s)
=== CONT  TestAccAWSSecurityGroup_egressWithPrefixList
--- PASS: TestAccAWSSecurityGroup_egressWithPrefixList (24.78s)
=== CONT  TestAccAWSSecurityGroup_ingressWithCidrAndSGsClassic
--- SKIP: TestAccAWSSecurityGroup_ingressWithCidrAndSGsClassic (0.24s)
    provider_test.go:460: This test can only run in EC2 Classic, platforms available in us-east-1: ["VPC"]
=== CONT  TestAccAWSSecurityGroup_ingressWithCidrAndSGsVPC
--- PASS: TestAccAWSSecurityGroup_ingressWithCidrAndSGsVPC (12.83s)
=== CONT  TestAccAWSSecurityGroup_CIDRandGroups
--- PASS: TestAccAWSSecurityGroup_CIDRandGroups (12.06s)
=== CONT  TestAccAWSSecurityGroup_tags
--- PASS: TestAccAWSSecurityGroup_tags (15.69s)
=== CONT  TestAccAWSSecurityGroup_invalidCIDRBlock
--- PASS: TestAccAWSSecurityGroup_invalidCIDRBlock (1.18s)
=== CONT  TestAccAWSSecurityGroup_driftComplex
--- PASS: TestAccAWSSecurityGroup_driftComplex (11.73s)
=== CONT  TestAccAWSSecurityGroup_drift
--- PASS: TestAccAWSSecurityGroup_drift (5.37s)
=== CONT  TestAccAWSSecurityGroup_defaultEgressClassic
--- SKIP: TestAccAWSSecurityGroup_defaultEgressClassic (0.20s)
    provider_test.go:460: This test can only run in EC2 Classic, platforms available in us-east-1: ["VPC"]
=== CONT  TestAccAWSSecurityGroup_ipv6
--- PASS: TestAccAWSSecurityGroup_ipv6 (25.03s)
=== CONT  TestAccAWSSecurityGroup_generatedName
--- PASS: TestAccAWSSecurityGroup_generatedName (23.32s)
=== CONT  TestAccAWSSecurityGroup_ruleDescription
--- PASS: TestAccAWSSecurityGroup_ruleDescription (60.23s)
=== CONT  TestAccAWSSecurityGroup_change
--- PASS: TestAccAWSSecurityGroup_change (42.99s)
=== CONT  TestAccAWSSecurityGroup_multiIngress
--- PASS: TestAccAWSSecurityGroup_multiIngress (30.51s)
=== CONT  TestAccAWSSecurityGroup_vpcProtoNumIngress
--- PASS: TestAccAWSSecurityGroup_vpcProtoNumIngress (24.98s)
=== CONT  TestAccAWSSecurityGroup_vpcNegOneIngress
--- PASS: TestAccAWSSecurityGroup_vpcNegOneIngress (25.87s)
=== CONT  TestAccAWSSecurityGroup_vpc
--- PASS: TestAccAWSSecurityGroup_vpc (25.93s)
=== CONT  TestAccAWSSecurityGroup_self
--- PASS: TestAccAWSSecurityGroup_self (25.06s)
=== CONT  TestAccAWSSecurityGroup_namePrefix
--- PASS: TestAccAWSSecurityGroup_namePrefix (30.02s)
=== CONT  TestAccAWSSecurityGroup_egressConfigMode
--- PASS: TestAccAWSSecurityGroup_egressConfigMode (56.84s)
=== CONT  TestAccAWSSecurityGroup_forceRevokeRulesFalse
--- PASS: TestAccAWSSecurityGroup_forceRevokeRulesFalse (655.68s)
=== CONT  TestAccAWSSecurityGroup_forceRevokeRulesTrue
--- PASS: TestAccAWSSecurityGroup_forceRevokeRulesTrue (681.08s)
=== CONT  TestAccAWSSecurityGroup_ruleGathering
--- PASS: TestAccAWSSecurityGroup_ruleGathering (44.40s)
=== CONT  TestAccAWSSecurityGroup_ingressConfigMode
--- PASS: TestAccAWSSecurityGroup_ingressConfigMode (47.35s)
=== CONT  TestAccAWSSecurityGroup_IPRangesWithSameRules
--- PASS: TestAccAWSSecurityGroup_IPRangesWithSameRules (27.52s)
=== CONT  TestAccAWSSecurityGroup_basic
--- PASS: TestAccAWSSecurityGroup_basic (23.96s)
=== CONT  TestAccAWSSecurityGroup_sourceSecurityGroup
--- PASS: TestAccAWSSecurityGroup_sourceSecurityGroup (26.52s)
=== CONT  TestAccAWSSecurityGroup_IPRangeAndSecurityGroupWithSameRules
--- PASS: TestAccAWSSecurityGroup_IPRangeAndSecurityGroupWithSameRules (31.73s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	2162.090s
```

**Comment by spavuluri** [comment]
Hi @anGie44, updated PR per your feedback, rebased, reverified acceptance tests and updated docs. This is ready for review.

**Comment by anGie44** [comment]
thank you @spavuluri, changes looks great! just waiting on acceptance tests to finish up on our end
