### PR TITLE
Remove CodePipeline GitHub environment variable

### LINKED ISSUE #2796: Putting GITHUB_TOKEN in terraform config for aws_codepipeline
When using AWS CodePipeline, if you want to fetch your source code from GitHub, you need to run `terraform apply` with the environment variable `GITHUB_TOKEN` (whose value should be a previously generated OAuth token).

This kinda goes against Terraform's philosophy. Would it be more sensible to have a parameter for the resource `aws_codepipeline` to set that token? Is there a compelling reason to use an environment variable instead?

I'm starting the discussion. If we end up deciding on a parameter I'm willing to have a go at a PR.

### LINKED ISSUE #4768: Codepipeline OAuthToken property inside source configuration should be sensitive
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
+ provider.aws v1.22.0

### Affected Resource(s)

* aws_codepipeline

### Terraform Configuration Files

```hcl
resource "aws_codepipeline" "pipeline" {
  # ...
  stage {
    name = "Source"

    action {
      name             = "Source"
      category         = "Source"
      owner            = "ThirdParty"
      provider         = "GitHub"
      version          = "1"
      output_artifacts = ["code"]

      configuration {
        Owner                = "owner"
        Repo                 = "repo"
        Branch               = "master"
        PollForSourceChanges = false
        OAuthToken           = "<REDACTED>"
      }
    }
  }
}
```

### Expected Behavior

`stage.0.action.0.configuration.OAuthToken` should appear as sensitive in terraform plan and apply

### Actual Behavior

`stage.0.action.0.configuration.OAuthToken` value is shown in plan and apply.

### Steps to Reproduce

1. `terraform plan -out=plan`
2. `terraform apply plan`

### References

* #4261 : Related to this issue, but for codepipeline

### PR DESCRIPTION
**Pull request by gdavison**
Removes the previously required `GITHUB_TOKEN` environment variable for CodePipeline. The authentication token is now passed as the `OAuthToken` field in the action configuration.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #2796 
Closes #4768

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_codepipeline: Removes `GITHUB_TOKEN` environment variable
```

Output from acceptance testing in commercial partition:

```
$ make testacc TESTARGS='-run=TestAccAWSCodePipeline_'

--- PASS: TestAccAWSCodePipeline_disappears (35.93s)
--- PASS: TestAccAWSCodePipeline_emptyStageArtifacts (40.89s)
--- PASS: TestAccAWSCodePipeline_multiregion_basic (48.58s)
--- PASS: TestAccAWSCodePipeline_deployWithServiceRole (55.08s)
--- PASS: TestAccAWSCodePipeline_WithNamespace (58.69s)
--- PASS: TestAccAWSCodePipeline_basic (63.80s)
--- PASS: TestAccAWSCodePipeline_tags (75.56s)
--- PASS: TestAccAWSCodePipeline_multiregion_Update (79.32s)
--- PASS: TestAccAWSCodePipeline_multiregion_ConvertSingleRegion (94.63s)
```

Output from acceptance testing in GovCloud partition:

```
--- SKIP: TestAccAWSCodePipeline_multiregion_ConvertSingleRegion (2.37s)
--- SKIP: TestAccAWSCodePipeline_multiregion_basic (2.38s)
--- SKIP: TestAccAWSCodePipeline_multiregion_Update (2.39s)
--- PASS: TestAccAWSCodePipeline_disappears (24.64s)
--- PASS: TestAccAWSCodePipeline_emptyStageArtifacts (30.55s)
--- PASS: TestAccAWSCodePipeline_WithNamespace (32.72s)
--- PASS: TestAccAWSCodePipeline_deployWithServiceRole (35.85s)
--- PASS: TestAccAWSCodePipeline_basic (46.98s)
--- PASS: TestAccAWSCodePipeline_tags (57.72s)
```

### CODE REVIEW

File: aws/resource_aws_codepipeline_test.go [hunk 1]
```diff
@@ -488,10 +592,29 @@ func testAccPreCheckAWSCodePipeline(t *testing.T) {
 	}
 }
 
+func testAccPreCheckAWSCodePipelineAlternateRegion(t *testing.T) {
+	// There isn't a way to get the alternate region provider at PreCheck time, so hardcode it
+	if testAccGetAlternateRegion() == "us-gov-east-1" {
```
Comment (gdavison) [inline aws/resource_aws_codepipeline_test.go:597]: Not sure, but this might be better as a check on `testAccGetAlternateRegionPartition() == "aws-us-gov"` instead…

File: aws/resource_aws_codepipeline.go [hunk 2]
```diff
@@ -331,31 +340,23 @@ func expandAwsCodePipelineStages(d *schema.ResourceData) []*codepipeline.StageDe
...
-func expandAwsCodePipelineActions(s []interface{}) []*codepipeline.ActionDeclaration {
+func expandAwsCodePipelineActions(a []interface{}) []*codepipeline.ActionDeclaration {
 	actions := []*codepipeline.ActionDeclaration{}
-	for _, config := range s {
+	for _, config := range a {
 		data := config.(map[string]interface{})
 
 		conf := expandAwsCodePipelineStageActionConfiguration(data["configuration"].(map[string]interface{}))
-		if data["provider"].(string) == "GitHub" {
-			githubToken := os.Getenv("GITHUB_TOKEN")
```
Comment (bflad) [inline aws/resource_aws_codepipeline.go:353]: Can you please add information to the Version 3 Upgrade Guide (`website/docs/guides/version-3-upgrade.html.md`) as part of this change?

File: aws/resource_aws_codepipeline.go [hunk 3]
```diff
@@ -605,8 +610,33 @@ func resourceAwsCodePipelineDelete(d *schema.ResourceData, meta interface{}) err
...
+		hash := hashCodePipelineGitHubToken(new)
+		return old == hash
+	}
+
+	return false
+}
+
+const codePipelineGitHubTokenHashPrefix = "hash-"
+
+func hashCodePipelineGitHubToken(token string) string {
```
Comment (bflad) [inline aws/resource_aws_codepipeline.go:635]: We are actively in the process of [removing the few other instances of hashed state storage](https://github.com/terraform-providers/terraform-provider-aws/issues/13406), however Terraform in general doesn't handle `TypeMap` and `Sensitive: true` in a meaningful way without making the entire map sensitive, if I remember correctly. 😖 

It would be a bummer to introduce this technical debt in, but otherwise we could also be forced down the road of what I think you were suggesting the other day of potentially going against the API design slightly and implementing bespoke Terraform schema so we can control it better (and in this situation, actually implement a single sensitive attribute). We do have some slight precedence of this class of user experience enhancement with resources like `aws_sns_platform_application` and I believe `aws_sns_topic`.

---

I think this leaves us in a tough spot. 🙁   We can try to quickly design something better for this situation to squeeze it in for this major release in the next two weeks, which is fairly risky in my opinion, or punt on this for now and spend later cycles on this issue in general (potentially changing the Core/SDK sensitive map abilities and/or ensuring we get good feedback on a new resource design). What do you think?

File: aws/resource_aws_codepipeline_test.go [hunk 4]
```diff
@@ -488,10 +592,29 @@ func testAccPreCheckAWSCodePipeline(t *testing.T) {
 	}
 }
 
+func testAccPreCheckAWSCodePipelineAlternateRegion(t *testing.T) {
```
Comment (bflad) [inline aws/resource_aws_codepipeline_test.go:595]: Ah its a bummer we cannot reuse logic similar to `testAccPreCheckAWSCodePipeline` here (using a real API call to automatically enable/skip the test), but I see the problem is that we don't initialize an "alternate" global instance of the provider in the testing similar to `testAccProvider`. I think this is okay as-is for now until we can figure out things as part of https://github.com/terraform-providers/terraform-provider-aws/issues/8983 / https://github.com/terraform-providers/terraform-provider-aws/issues/8316

File: aws/resource_aws_codepipeline_test.go (hunk 1 above)
Comment (bflad) [reply aws/resource_aws_codepipeline_test.go:597]: Wow this is annoying (on the AWS side), I'm fine with either, to be honest.

File: aws/resource_aws_codepipeline.go (hunk 3 above)
Comment (gdavison) [reply aws/resource_aws_codepipeline.go:635]: I think the environment variable is a huge pain-point for practitioners, and waiting until 4.0 to remove it would be less than ideal. If we don't want to hash the value, would setting the `TypeMap` to `Sensitive` be a better option at this point? And then we could come up with a better solution.

File: aws/resource_aws_codepipeline_test.go (hunk 4 above)
Comment (gdavison) [reply aws/resource_aws_codepipeline_test.go:595]: Yeah, I briefly considered the option of rolling my own connection to test the API, but I figured the hard-coded option was quicker. Though it actually might not be that complicated

File: aws/resource_aws_codepipeline.go (hunk 3 above)
Comment (bflad) [reply aws/resource_aws_codepipeline.go:639]: Our potential path forward will be:

* Removing the state hashing handling
* Marking the `configuration` attribute `Sensitive: true` and `Computed: true`
* Adding a new `github`/`github_configuration` configuration block so we can properly show a difference with only the `oauth` attribute sensitive

These will require apply-time validation to ensure they aren't both defined since `ConflictsWith` does not support relative references. The other configuration blocks will need to be filled in later due to time. The documentation and upgrade guide should recommend using the new configuration block(s) over the map.

**Comment by bflad** [comment]
Once these pending items are commented/addressed, will provide another review:

* Fixing merge conflicts
* Adding a new `github`/`github_configuration` configuration block so we can properly show a difference with only the `oauth` attribute sensitive
