### PR TITLE
resource/ecr_repository_policy: Support import

### LINKED ISSUE #5921: Resource aws_ecs_repository_policy doesn't support import
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
0.11.8
provider.aws v1.35.0

### Affected Resource(s)
aws_ecs_service

### Terraform Configuration Files
```hcl
Not relevant
```

### Debug Output
Error: aws_ecr_repository_policy.cross-account-pull (import id: *****): import aws_ecr_repository_policy.cross-account-pull (id: *****): resource aws_ecr_repository_policy doesn't support import

### Expected Behavior
import succeeds without error

### Actual Behavior
Error as above

### Steps to Reproduce
try to import aws_ecs_service_policy

### PR DESCRIPTION
**Pull request by atsushi-ishibashi**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #5921

Changes proposed in this pull request:

* Support import

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSEcrRepositoryPolicy_'
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSEcrRepositoryPolicy_ -timeout 120m
=== RUN   TestAccAWSEcrRepositoryPolicy_basic
=== PAUSE TestAccAWSEcrRepositoryPolicy_basic
=== RUN   TestAccAWSEcrRepositoryPolicy_iam
=== PAUSE TestAccAWSEcrRepositoryPolicy_iam
=== CONT  TestAccAWSEcrRepositoryPolicy_basic
=== CONT  TestAccAWSEcrRepositoryPolicy_iam
--- PASS: TestAccAWSEcrRepositoryPolicy_basic (35.12s)
--- PASS: TestAccAWSEcrRepositoryPolicy_iam (47.19s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	47.238s
```

### CODE REVIEW

File: aws/resource_aws_ecr_repository_policy.go [hunk 1]
```diff
@@ -78,7 +81,6 @@ func resourceAwsEcrRepositoryPolicyRead(d *schema.ResourceData, meta interface{}
 
 	log.Printf("[DEBUG] Reading repository policy %s", d.Id())
 	out, err := conn.GetRepositoryPolicy(&ecr.GetRepositoryPolicyInput{
-		RegistryId:     aws.String(d.Get("registry_id").(string)),
```
Comment (bflad) [inline aws/resource_aws_ecr_repository_policy.go]: I believe the intention here is that ECR may eventually support more than one registry per AWS account, but that is not currently supported nor does the `aws_ecr_repository` resource import require the leading registry ID (e.g. AWS account ID). So this seems okay.

File: aws/resource_aws_ecr_repository_policy_test.go [hunk 2]
```diff
@@ -84,11 +96,6 @@ func testAccCheckAWSEcrRepositoryPolicyExists(name string) resource.TestCheckFun
 
 func testAccAWSEcrRepositoryPolicy(randString string) string {
 	return fmt.Sprintf(`
-# ECR initially only available in us-east-1
-# https://aws.amazon.com/blogs/aws/ec2-container-registry-now-generally-available/
-provider "aws" {
```
Comment (bflad) [inline aws/resource_aws_ecr_repository_policy_test.go]: ❤️ thanks for fixing this

**Comment by bflad** [comment]
This has been released in [version 2.3.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#230-march-21-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
