### PR TITLE
resource/aws_cloudfront_distribution: Adjust TypeSet and TypeList attributes for better difference handling

### LINKED ISSUE #416: Bug with aws_cloudfront_distribution
_This issue was originally opened by @gsaslis as hashicorp/terraform#10598. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

Hi there,

Opening this cause terraform itself told me to. 
(see, humans are already following machine instructions... ) 

### Terraform Version
`Terraform Version: 0.7.13`

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_cloudfront_distribution

### Debug Output
https://gist.github.com/gsaslis/dbf4a5f908eaf312bf041d85731e7974

### LINKED ISSUE #824: Error during apply of aws_cloudfront_distribution using aws_cloudfront_origin_access_identity
_This issue was originally opened by @billyboingo as hashicorp/terraform#15028. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version
0.9.6

### Affected Resource(s)
- aws_cloudfront_distribution

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
data "aws_route53_zone" "hosted_zone" {
  name = "${var.hosted_zone_name}"
}

resource "aws_cloudfront_distribution" "distribution" {
  origin {
    domain_name = "${var.bucket_domain_name}"
    origin_id   = "S3-${var.bucket_name}"

    s3_origin_config {
      origin_access_identity = "${var.origin_access_identity == "" ? "" : "origin-access-identity/cloudfront/${var.origin_access_identity}"}"
    }
  }

  enabled             = true
  is_ipv6_enabled     = true
  comment             = "Distribution for ${var.bucket_name} S3 Bucket."
  default_root_object = "${var.default_object}"

  aliases = ["${var.host_name}.${var.hosted_zone_name}"]

  price_class = "${var.price_class}"

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  viewer_certificate {
    cloudfront_default_certificate = false
    acm_certificate_arn            = "${module.ssl_cert.arn}"
    minimum_protocol_version       = "TLSv1"
    ssl_support_method             = "sni-only"
  }

  default_cache_behavior {
    allowed_methods  = ["GET", "HEAD"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = "S3-${var.bucket_name}"

    forwarded_values {
      query_string            = true
      query_string_cache_keys = ["version"]

      cookies {
        forward = "none"
      }
    }

    viewer_protocol_policy = "redirect-to-https"
    min_ttl                = 0
    default_ttl            = 3600
    max_ttl                = 86400
  }

  cache_behavior {
    path_pattern     = "/data/*"
    allowed_methods  = ["GET", "HEAD", "OPTIONS"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = "S3-${var.bucket_name}"
    trusted_signers  = ["self"]

    forwarded_values {
      query_string            = true
      query_string_cache_keys = ["version"]

      cookies {
        forward = "none"
      }
    }

    viewer_protocol_policy = "redirect-to-https"
    min_ttl                = 0
    default_ttl            = 60
    max_ttl                = 31536000
  }
}

resource "aws_route53_record" "dns_record" {
  zone_id = "${data.aws_route53_zone.hosted_zone.zone_id}"
  name    = "${var.host_name}.${var.hosted_zone_name}"
  type    = "A"

  alias {
    name                   = "${aws_cloudfront_distribution.distribution.domain_name}"
    zone_id                = "Z2FDTNDATAQYW2"
    evaluate_target_health = false
  }
}
```

### Debug Output
https://gist.github.com/billyboingo/73982918f56eba123fd389113cff4455

### Panic Output
Remain calm and carry on.

### Expected Behavior
A new cloudfront distribution should have been created with restricted access to an S3 bucket via the origin access identity.

### Actual Behavior
It blows up with the provided output.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
This looks like it could be a regression of the issue referenced below...

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-6527

### LINKED ISSUE #1194: Cloudfront Distribution after import attempts to make changes [0.9.8]
_This issue was originally opened by @ahharu as hashicorp/terraform#15600. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

# PROVIDER ISSUES

After importing a resource in terraform using terraform import and having into our tf files a configuration that matches remote config in AWS it wants to delete and then add the configuration.

------

### Terraform Version

0.9.8

### Debug Output

```
~ aws_cloudfront_distribution.statics
    cache_behavior.#:                                                                                    "0" => "2"
    cache_behavior.322762713.allowed_methods.#:                                                          "0" => "2"
    cache_behavior.322762713.allowed_methods.0:                                                          "" => "GET"
    cache_behavior.322762713.allowed_methods.1:                                                          "" => "HEAD"
    cache_behavior.322762713.cached_methods.#:                                                           "0" => "2"
    cache_behavior.322762713.cached_methods.0:                                                           "" => "GET"
    cache_behavior.322762713.cached_methods.1:                                                           "" => "HEAD"
    cache_behavior.322762713.compress:                                                                   "" => "false"
    cache_behavior.322762713.default_ttl:                                                                "" => "86400"
    cache_behavior.322762713.forwarded_values.#:                                                         "0" => "1"
    cache_behavior.322762713.forwarded_values.563318458.cookies.#:                                       "0" => "1"
    cache_behavior.322762713.forwarded_values.563318458.cookies.2625240281.forward:                      "" => "none"
    cache_behavior.322762713.forwarded_values.563318458.cookies.2625240281.whitelisted_names.#:          "0" => "0"
    cache_behavior.322762713.forwarded_values.563318458.headers.#:                                       "0" => "1"
    cache_behavior.322762713.forwarded_values.563318458.headers.0:                                       "" => "Origin"
    cache_behavior.322762713.forwarded_values.563318458.query_string:                                    "" => "false"
    cache_behavior.322762713.forwarded_values.563318458.query_string_cache_keys.#:                       "0" => "0"
    cache_behavior.322762713.lambda_function_association.#:                                              "0" => "0"
    cache_behavior.322762713.max_ttl:                                                                    "" => "31536000"
    cache_behavior.322762713.min_ttl:                                                                    "" => "0"
    cache_behavior.322762713.path_pattern:                                                               "" => "eviewer/*"
    cache_behavior.322762713.smooth_streaming:                                                           "" => "false"
    cache_behavior.322762713.target_origin_id:                                                           "" => "S3-ofertia-static-content"
    cache_behavior.322762713.trusted_signers.#:                                                          "0" => "0"
    cache_behavior.322762713.viewer_protocol_policy:                                                     "" => "allow-all"
    cache_behavior.4105325411.allowed_methods.#:                                                         "0" => "2"
    cache_behavior.4105325411.allowed_methods.0:                                                         "" => "GET"
    cache_behavior.4105325411.allowed_methods.1:                                                         "" => "HEAD"
    cache_behavior.4105325411.cached_methods.#:                                                          "0" => "2"
    cache_behavior.4105325411.cached_methods.0:                                                          "" => "GET"
    cache_behavior.4105325411.cached_methods.1:                                                          "" => "HEAD"
    cache_behavior.4105325411.compress:                                                                  "" => "false"
    cache_behavior.4105325411.default_ttl:                                                               "" => "86400"
    cache_behavior.4105325411.forwarded_values.#:                                                        "0" => "1"
    cache_behavior.4105325411.forwarded_values.563318458.cookies.#:                                      "0" => "1"
    cache_behavior.4105325411.forwarded_values.563318458.cookies.2625240281.forward:                     "" => "none"
    cache_behavior.4105325411.forwarded_values.563318458.cookies.2625240281.whitelisted_names.#:         "0" => "0"
    cache_behavior.4105325411.forwarded_values.563318458.headers.#:                                      "0" => "1"
    cache_behavior.4105325411.forwarded_values.563318458.headers.0:                                      "" => "Origin"
    cache_behavior.4105325411.forwarded_values.563318458.query_string:                                   "" => "false"
    cache_behavior.4105325411.forwarded_values.563318458.query_string_cache_keys.#:                      "0" => "0"
    cache_behavior.4105325411.lambda_function_association.#:                                             "0" => "0"
    cache_behavior.4105325411.max_ttl:                                                                   "" => "31536000"
    cache_behavior.4105325411.min_ttl:                                                                   "" => "0"
    cache_behavior.4105325411.path_pattern:                                                              "" => "web/*"
    cache_behavior.4105325411.smooth_streaming:                                                          "" => "false"
    cache_behavior.4105325411.target_origin_id:                                                          "" => "S3-ofertia-static-content"
    cache_behavior.4105325411.trusted_signers.#:                                                         "0" => "0"
    cache_behavior.4105325411.viewer_protocol_policy:                                                    "" => "allow-all"
    default_cache_behavior.1805859333.allowed_methods.#:                                                 "2" => "0"
    default_cache_behavior.1805859333.allowed_methods.0:                                                 "HEAD" => ""
    default_cache_behavior.1805859333.allowed_methods.1:                                                 "GET" => ""
    default_cache_behavior.1805859333.cached_methods.#:                                                  "2" => "0"
    default_cache_behavior.1805859333.cached_methods.0:                                                  "HEAD" => ""
    default_cache_behavior.1805859333.cached_methods.1:                                                  "GET" => ""
    default_cache_behavior.1805859333.compress:                                                          "false" => "false"
    default_cache_behavior.1805859333.default_ttl:                                                       "86400" => "0"
    default_cache_behavior.1805859333.forwarded_values.#:                                                "1" => "0"
    default_cache_behavior.1805859333.forwarded_values.563318458.cookies.#:                              "1" => "0"
    default_cache_behavior.1805859333.forwarded_values.563318458.cookies.2625240281.forward:             "none" => ""
    default_cache_behavior.1805859333.forwarded_values.563318458.cookies.2625240281.whitelisted_names.#: "0" => "0"
    default_cache_behavior.1805859333.forwarded_values.563318458.headers.#:                              "1" => "0"
    default_cache_behavior.1805859333.forwarded_values.563318458.headers.0:                              "Origin" => ""
    default_cache_behavior.1805859333.forwarded_values.563318458.query_string:                           "false" => "false"
    default_cache_behavior.1805859333.forwarded_values.563318458.query_string_cache_keys.#:              "0" => "0"
    default_cache_behavior.1805859333.lambda_function_association.#:                                     "0" => "0"
    default_cache_behavior.1805859333.max_ttl:                                                           "31536000" => "0"
    default_cache_behavior.1805859333.min_ttl:                                                           "604800" => "0"
    default_cache_behavior.1805859333.smooth_streaming:                                                  "false" => "false"
    default_cache_behavior.1805859333.target_origin_id:                                                  "S3-ofertiadk-static-content" => ""
    default_cache_behavior.1805859333.trusted_signers.#:                                                 "0" => "0"
    default_cache_behavior.1805859333.viewer_protocol_policy:                                            "allow-all" => ""
    default_cache_behavior.983534757.allowed_methods.#:                                                  "0" => "2"
    default_cache_behavior.983534757.allowed_methods.0:                                                  "" => "GET"
    default_cache_behavior.983534757.allowed_methods.1:                                                  "" => "HEAD"
    default_cache_behavior.983534757.cached_methods.#:                                                   "0" => "2"
    default_cache_behavior.983534757.cached_methods.0:                                                   "" => "GET"
    default_cache_behavior.983534757.cached_methods.1:                                                   "" => "HEAD"
    default_cache_behavior.983534757.compress:                                                           "" => "false"
    default_cache_behavior.983534757.default_ttl:                                                        "" => "86400"
    default_cache_behavior.983534757.forwarded_values.#:                                                 "0" => "1"
    default_cache_behavior.983534757.forwarded_values.563318458.cookies.#:                               "0" => "1"
    default_cache_behavior.983534757.forwarded_values.563318458.cookies.2625240281.forward:              "" => "none"
    default_cache_behavior.983534757.forwarded_values.563318458.cookies.2625240281.whitelisted_names.#:  "0" => "0"
    default_cache_behavior.983534757.forwarded_values.563318458.headers.#:                               "0" => "1"
    default_cache_behavior.983534757.forwarded_values.563318458.headers.0:                               "" => "Origin"
    default_cache_behavior.983534757.forwarded_values.563318458.query_string:                            "" => "false"
    default_cache_behavior.983534757.forwarded_values.563318458.query_string_cache_keys.#:               "0" => "0"
    default_cache_behavior.983534757.lambda_function_association.#:                                      "0" => "0"
    default_cache_behavior.983534757.max_ttl:                                                            "" => "31536000"
    default_cache_behavior.983534757.min_ttl:                                                            "" => "0"
    default_cache_behavior.983534757.smooth_streaming:                                                   "" => "false"
    default_cache_behavior.983534757.target_origin_id:                                                   "" => "S3-ofertiadk-static-content"
    default_cache_behavior.983534757.trusted_signers.#:                                                  "0" => "0"
    default_cache_behavior.983534757.viewer_protocol_policy:                                             "" => "allow-all"
    origin.#:                                                                                            "1" => "2"
    origin.2237230307.custom_header.#:                                                                   "0" => "0"
    origin.2237230307.custom_origin_config.#:                                                            "0" => "0"
    origin.2237230307.domain_name:                                                                       "" => "ofertia-static-content.s3.amazonaws.com"
    origin.2237230307.origin_id:                                                                         "" => "S3-ofertia-static-content"
    origin.2237230307.origin_path:                                                                       "" => "/dk"
    origin.2237230307.s3_origin_config.#:                                                                "0" => "0"
    origin.3712337220.custom_header.#:                                                                   "0" => "0"
    origin.3712337220.custom_origin_config.#:                                                            "0" => "0"
    origin.3712337220.domain_name:                                                                       "ofertiadk-static-content.s3.amazonaws.com" => "ofertiadk-static-content.s3.amazonaws.com"
    origin.3712337220.origin_id:                                                                         "S3-ofertiadk-static-content" => "S3-ofertiadk-static-content"
    origin.3712337220.origin_path:                                                                       "" => ""
    origin.3712337220.s3_origin_config.#:                                                                "0" => "0"
```

### Expected Behavior

Should detect it and show no changes

### Steps to Reproduce

terraform import a cloudfront distribution

terraform plan

### LINKED ISSUE #3256: aws_cloudfront_distribution attribute mismatch: diffs didn't  match during apply.
```
An execution plan has been generated and is shown below.                                  
Resource actions are indicated with the following symbols:
  + create                                              
  ~ update in-place
                             
Terraform will perform the following actions:               
                                                                          
  ~ aws_cloudfront_distribution.static-facebook                                                          
      origin.2528787734.custom_header.#:        "0" => "0"                                               
      origin.2528787734.custom_origin_config.#: "0" => "0"                                               
      origin.2528787734.domain_name:            "facebook.babylonhealth.com.s3.amazonaws.com" => ""      
      origin.2528787734.origin_id:              "facebook.babylonhealth.com" => ""                       
      origin.2528787734.origin_path:            "" => ""                                                 
      origin.2528787734.s3_origin_config.#:     "0" => "0"                                               
      origin.3355674526.custom_header.#:        "0" => "0"                                               
      origin.3355674526.custom_origin_config.#: "0" => "0"                                               
      origin.3355674526.domain_name:            "" => "facebook.babylonhealth.com"                       
      origin.3355674526.origin_id:              "" => "facebook.babylonhealth.com"                       
      origin.3355674526.origin_path:            "" => ""                                                 
      origin.3355674526.s3_origin_config.#:     "0" => "0"                                               
                                                                                                         
  + aws_route53_record.facebook-static-prod                                                              
      id:                                       <computed>                                               
      fqdn:                                     <computed>                                               
      name:                                     "facebook.babylonhealth.com"                             
      records.#:                                "1"                                                      
      records.2327122678:                       "drd5xh28nit1u.cloudfront.net"                           
      ttl:                                      "30"                                                     
      type:                                     "CNAME"                                                  
      zone_id:                                  "Z2ULNG6JQKRJR0"                                         
                                                                                                         
  ~ aws_s3_bucket.facebook-babylonhealth                                                                 
      website_domain:                           "s3-website.eu-west-2.amazonaws.com" => "facebook.babylon
health.com"                                                                                              


Plan: 1 to add, 2 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes
                          
1 error(s) occurred:                                                                                     
                                                                                                         
* aws_cloudfront_distribution.static-facebook: aws_cloudfront_distribution.static-facebook: diffs didn't 
match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.               
                                                                                                         
Please include the following information in your report:                                                 
                          
    Terraform Version: 0.11.3                       
    Resource ID: aws_cloudfront_distribution.static-facebook                                             
    Mismatch reason: attribute mismatch: origin.3355674526.custom_header.#                               
            Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"origin.2528787734.s3_origin_config.#":*terraform.ResourceAttrDiff{O
ld:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sens
itive:false, Type:0x0}, "origin.2528787734.custom_header.#":*terraform.ResourceAttrDiff{Old:"0", New:"0",
 NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Typ
e:0x0}, "origin.3355674526.domain_name":*terraform.ResourceAttrDiff{Old:"", New:"facebook.babylonhealth.c
om", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false,
 Type:0x0}, "origin.2528787734.custom_origin_config.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewC
omputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0
}, "origin.3355674526.custom_header.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, N
ewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.33556
74526.origin_path":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:false, NewEx
tra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.3355674526.s3_origin_config
.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface
 {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.3355674526.custom_origin_config.#":*terr
aform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil),
 RequiresNew:false, Sensitive:false, Type:0x0}, "origin.3355674526.origin_id":*terraform.ResourceAttrDiff
{Old:"", New:"facebook.babylonhealth.com", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil
), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.2528787734.domain_name":*terraform.ResourceAttr
Diff{Old:"facebook.babylonhealth.com.s3.amazonaws.com", New:"", NewComputed:false, NewRemoved:true, NewEx
tra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.2528787734.origin_id":*terr
aform.ResourceAttrDiff{Old:"facebook.babylonhealth.com", New:"", NewComputed:false, NewRemoved:true, NewE
xtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.2528787734.origin_path":*t
erraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil),
 RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:fals
e, Meta:map[string]interface {}(nil)}
              Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:m
ap[string]*terraform.ResourceAttrDiff{"origin.2528787734.custom_header.#":*terraform.ResourceAttrDiff{Old
:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensit
ive:false, Type:0x0}, "origin.1376845673.origin_path":*terraform.ResourceAttrDiff{Old:"", New:"", NewComp
uted:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, 
"origin.2528787734.custom_origin_config.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:fals
e, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.2
528787734.origin_path":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:true, Ne
wExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.1376845673.s3_origin_con
fig.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interf
ace {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.2528787734.domain_name":*terraform.Re
sourceAttrDiff{Old:"facebook.babylonhealth.com.s3.amazonaws.com", New:"", NewComputed:false, NewRemoved:t
rue, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.2528787734.s3_ori
gin_config.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra
:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.1376845673.origin_id":*terrafo
rm.ResourceAttrDiff{Old:"", New:"facebook.babylonhealth.com", NewComputed:false, NewRemoved:false, NewExt
ra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.1376845673.custom_header.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.1376845673.custom_origin_config.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface{}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.1376845673.domain_name":*terraform.ResourceAttrDiff{Old:"", New:"s3-website.eu-west-2.amazonaws.com", NewComputed:false, NewRemoved:false, NewExtra:interface{}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.2528787734.origin_id":*terraform.ResourceAttrDiff{Old:"facebook.babylonhealth.com", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface{}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}                    
```

### Expected Behavior
Plan should be applied

### Actual Behavior
Result shown above. Terraform believes that it is out of sync with AWS, but everything seems to be working as expected.

### Steps to Reproduce
1. `terraform apply`

### LINKED ISSUE #3766: Terraform 0.11.3 crash during apply
_This issue was originally opened by @nicwise as hashicorp/terraform#17574. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version

```
terraform -v
Terraform v0.11.3
+ provider.aws v1.11.0

```

### Terraform Configuration Files

```hcl

resource "aws_s3_bucket" "static_bucket" {
  bucket = "xx-${var.environment}-static-site"
  acl    = "public-read"

  website {
    index_document = "index.html"
  }

  tags {
    Name        = "xx-${var.environment}-static-site"
    Environment = "${var.environment}"
  }


}

output bucket_domain_name {
  value = "${aws_s3_bucket.static_bucket.website_domain}"
}



resource "aws_cloudfront_distribution" "static_site_distribution" {

  enabled = true
  #origin for static content
  origin {
    domain_name = "${var.static_content_bucket_domain}" #web url of the bucket
    origin_id   = "${var.origin_id}_static"

    s3_origin_config {
      origin_access_identity = ""
    }
  }

  default_cache_behavior {
    allowed_methods  = ["GET", "HEAD"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = "${var.origin_id}_static"
    compress         = true

    forwarded_values {
      query_string = true

      cookies {
        forward = "all"
      }
    }

    viewer_protocol_policy = "redirect-to-https"
    min_ttl                = 0
    default_ttl            = 0
    max_ttl                = 0
  }



  price_class = "PriceClass_100"

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  viewer_certificate {
    cloudfront_default_certificate = true
    minimum_protocol_version       = "TLSv1"
  }

  tags {
    Name        = "${var.environment}-${var.role_name}"
    Environment = "${var.environment}"
    App         = "${var.role_name}"
  }
}
```

### Crash Output
Error: Error applying plan:

1 error(s) occurred:

* module.cloudfront.aws_cloudfront_distribution.static_site_distribution: aws_cloudfront_distribution.static_site_distribution: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:
```
    Terraform Version: 0.11.3
    Resource ID: aws_cloudfront_distribution.static_site_distribution
    Mismatch reason: attribute mismatch: origin.3487601949.custom_header.#
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"origin.714713060.origin_id":*terraform.ResourceAttrDiff{Old:"staticcontent_static", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.714713060.custom_header.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.714713060.custom_origin_config.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.3487601949.s3_origin_config.#":*terraform.ResourceAttrDiff{Old:"0", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.714713060.domain_name":*terraform.ResourceAttrDiff{Old:"xx-wordpress-static-site.s3.amazonaws.com", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.714713060.origin_path":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.3487601949.custom_header.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.3487601949.custom_origin_config.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.714713060.s3_origin_config.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.3487601949.s3_origin_config.2547889144.origin_access_identity":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.3487601949.domain_name":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.3487601949.origin_id":*terraform.ResourceAttrDiff{Old:"", New:"staticcontent_static", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.3487601949.origin_path":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"origin.4033925426.domain_name":*terraform.ResourceAttrDiff{Old:"", New:"s3-website-us-west-2.amazonaws.com", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.714713060.s3_origin_config.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.714713060.custom_origin_config.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.714713060.custom_header.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.4033925426.s3_origin_config.2547889144.origin_access_identity":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.714713060.origin_path":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.4033925426.custom_header.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.4033925426.origin_path":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.714713060.domain_name":*terraform.ResourceAttrDiff{Old:"xx-wordpress-static-site.s3.amazonaws.com", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.4033925426.s3_origin_config.#":*terraform.ResourceAttrDiff{Old:"0", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.714713060.origin_id":*terraform.ResourceAttrDiff{Old:"staticcontent_static", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.4033925426.custom_origin_config.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.4033925426.origin_id":*terraform.ResourceAttrDiff{Old:"", New:"staticcontent_static", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.
```
### Expected Behavior
plan should have applied

### Actual Behavior
Crash

### Steps to Reproduce
This is the original plan

```
Terraform will perform the following actions:

  ~ module.cloudfront.aws_cloudfront_distribution.static_site_distribution
      origin.3487601949.custom_header.#:                                    "0" => "0"
      origin.3487601949.custom_origin_config.#:                             "0" => "0"
      origin.3487601949.domain_name:                                        "" => ""
      origin.3487601949.origin_id:                                          "" => "staticcontent_static"
      origin.3487601949.origin_path:                                        "" => ""
      origin.3487601949.s3_origin_config.#:                                 "0" => "1"
      origin.3487601949.s3_origin_config.2547889144.origin_access_identity: "" => ""
      origin.714713060.custom_header.#:                                     "0" => "0"
      origin.714713060.custom_origin_config.#:                              "0" => "0"
      origin.714713060.domain_name:                                         "xx-wordpress-static-site.s3.amazonaws.com" => ""
      origin.714713060.origin_id:                                           "staticcontent_static" => ""
      origin.714713060.origin_path:                                         "" => ""
      origin.714713060.s3_origin_config.#:                                  "0" => "0"

  ~ module.s3.aws_s3_bucket.static_bucket
      website.#:                                                            "0" => "1"
      website.0.index_document:                                             "" => "index.html"
```

I had changed the domain name (it's ment to the website domain of the static bucket, but it looks like it's come in blank).

### Additional Context
Very basic Cloudfront -> S3 setup.

### LINKED ISSUE #3842: aws_cloudfront_distribution.main: aws_cloudfront_distribution.main: diffs didn't match during apply
_This issue was originally opened by @vladiim as hashicorp/terraform#17637. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

This happened after:
1. Successfully running `terraform apply` for the first time
2. Adding `  default_root_object = "index.html"` to `resource "aws_cloudfront_distribution" "main" { lotsa stuff ...}`
3. Rerunning `terraform apply`
```
    Terraform Version: 0.11.4
    Resource ID: aws_cloudfront_distribution.main
    Mismatch reason: attribute mismatch: default_cache_behavior.1876600128.allowed_methods.#
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"default_cache_behavior.~2605320941.trusted_signers.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~2605320941.forwarded_values.2759845635.cookies.#":*terraform.ResourceAttrDiff{Old:"0", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.1876600128.forwarded_values.2759845635.cookies.#":*terraform.ResourceAttrDiff{Old:"1", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.1876600128.target_origin_id":*terraform.ResourceAttrDiff{Old:"s3-origin", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.1876600128.lambda_function_association.1058742642.event_type":*terraform.ResourceAttrDiff{Old:"origin-request", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~2605320941.cached_methods.#":*terraform.ResourceAttrDiff{Old:"0", New:"2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~2605320941.default_ttl":*terraform.ResourceAttrDiff{Old:"", New:"3600", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~2605320941.cached_methods.1":*terraform.ResourceAttrDiff{Old:"", New:"HEAD", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.1876600128.lambda_function_association.1058742642.lambda_arn":*terraform.ResourceAttrDiff{Old:"arn:aws:lambda:us-east-1:503586087475:function:laundromap-website-rewrite-urls:1", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~2605320941.forwarded_values.2759845635.cookies.2625240281.forward":*terraform.ResourceAttrDiff{Old:"", New:"none", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~2605320941.forwarded_values.2759845635.headers.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.1876600128.viewer_protocol_policy":*terraform.ResourceAttrDiff{Old:"redirect-to-https", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.1876600128.cached_methods.0":*terraform.ResourceAttrDiff{Old:"HEAD", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~2605320941.max_ttl":*terraform.ResourceAttrDiff{Old:"", New:"86400", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.1876600128.max_ttl":*terraform.ResourceAttrDiff{Old:"86400", New:"0", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~2605320941.forwarded_values.2759845635.query_string_cache_keys.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~2605320941.allowed_methods.1":*terraform.ResourceAttrDiff{Old:"", New:"HEAD", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.1876600128.forwarded_values.2759845635.query_string":*terraform.ResourceAttrDiff{Old:"false", New:"false", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.1876600128.smooth_streaming":*terraform.ResourceAttrDiff{Old:"false", New:"false", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~2605320941.smooth_streaming":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.1876600128.cached_methods.1":*terraform.ResourceAttrDiff{Old:"GET", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.1876600128.compress":*terraform.ResourceAttrDiff{Old:"true", New:"false", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~2605320941.min_ttl":*terraform.ResourceAttrDiff{Old:"", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.1876600128.forwarded_values.2759845635.cookies.2625240281.forward":*terraform.ResourceAttrDiff{Old:"none", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.1876600128.lambda_function_association.#":*terraform.ResourceAttrDiff{Old:"1", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_root_object":*terraform.ResourceAttrDiff{Old:"", New:"index.html", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.1876600128.forwarded_values.2759845635.headers.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~2605320941.allowed_methods.0":*terraform.ResourceAttrDiff{Old:"", New:"GET", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.1876600128.min_ttl":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~2605320941.allowed_methods.#":*terraform.ResourceAttrDiff{Old:"0", New:"2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~2605320941.forwarded_values.2759845635.cookies.2625240281.whitelisted_names.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.1876600128.allowed_methods.#":*terraform.ResourceAttrDiff{Old:"2", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~2605320941.compress":*terraform.ResourceAttrDiff{Old:"", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.1876600128.trusted_signers.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~2605320941.viewer_protocol_policy":*terraform.ResourceAttrDiff{Old:"", New:"redirect-to-https", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.1876600128.forwarded_values.2759845635.query_string_cache_keys.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.1876600128.default_ttl":*terraform.ResourceAttrDiff{Old:"3600", New:"0", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.1876600128.allowed_methods.0":*terraform.ResourceAttrDiff{Old:"HEAD", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~2605320941.cached_methods.0":*terraform.ResourceAttrDiff{Old:"", New:"GET", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~2605320941.forwarded_values.#":*terraform.ResourceAttrDiff{Old:"0", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~2605320941.target_origin_id":*terraform.ResourceAttrDiff{Old:"", New:"s3-origin", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.1876600128.forwarded_values.2759845635.cookies.2625240281.whitelisted_names.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.1876600128.cached_methods.#":*terraform.ResourceAttrDiff{Old:"2", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.1876600128.forwarded_values.#":*terraform.ResourceAttrDiff{Old:"1", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~2605320941.lambda_function_association.~2890672950.event_type":*terraform.ResourceAttrDiff{Old:"", New:"origin-request", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~2605320941.forwarded_values.2759845635.query_string":*terraform.ResourceAttrDiff{Old:"", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.1876600128.allowed_methods.1":*terraform.ResourceAttrDiff{Old:"GET", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~2605320941.lambda_function_association.~2890672950.lambda_arn":*terraform.ResourceAttrDiff{Old:"", New:"${aws_lambda_function.rewrite.qualified_arn}", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~2605320941.lambda_function_association.#":*terraform.ResourceAttrDiff{Old:"0", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"default_root_object":*terraform.ResourceAttrDiff{Old:"", New:"index.html", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
```

### LINKED ISSUE #4338: aws_cloudfront_distribution diff didn't match during apply
### Terraform Version
```
> terraform -v
Terraform v0.11.7
+ provider.archive v1.0.3
+ provider.aws v1.15.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_cloudfront_distribution

### Terraform Configuration Files
```hcl
resource "aws_cloudfront_distribution" "image-resize-server-apigateway" {

  aliases = ["${var.cloudfront_cname_alias}"]

  origin {
    domain_name = "${replace(aws_api_gateway_deployment.image-resize-api.invoke_url, "/^https://(.+)/.+$/", "$1")}"

    origin_path = "/${var.api_gateway_stage}"

    origin_id = "${var.cloudfront_origin_id}"

    custom_origin_config {
      http_port              = "80"
      https_port             = "443"
      origin_protocol_policy = "https-only"
      origin_ssl_protocols   = ["TLSv1.2"]
    }
  }

  enabled         = true
  is_ipv6_enabled = true
  comment         = "Theme Image Resize API distribution CDN"

  default_cache_behavior {
    allowed_methods  = ["GET", "HEAD", "OPTIONS"]
    cached_methods   = ["GET", "HEAD", "OPTIONS"]
    target_origin_id = "${var.cloudfront_origin_id}"

    forwarded_values {
      query_string = true

      cookies {
        forward = "none"
      }
    }

    viewer_protocol_policy = "https-only"

    min_ttl     = 0
    default_ttl = "${var.cloudfront_cache_expire}"
    max_ttl     = "${var.cloudfront_cache_expire}"
  }

  price_class = "PriceClass_200"

  tags {
    Environment = "${var.api_gateway_stage}"
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  viewer_certificate {
    cloudfront_default_certificate = false
    acm_certificate_arn            = "${var.cloudfront_acm_certificate_arn}"
    ssl_support_method             = "sni-only"
    minimum_protocol_version       = "TLSv1.1_2016"
  }
}
```

### Debug Output
https://gist.github.com/krrrr38/45ffa178700006662d6aac1d22acf256

### Panic Output
Nothing

### Expected Behavior
After creating aws_cloudfront_distribution, we can apply id many times.

### Actual Behavior
```
* module.image-resize-server.aws_cloudfront_distribution.image-resize-server-apigateway: aws_cloudfront_distribution.image-resize-server-apigateway: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.
```

details are in debug output.

```
    Terraform Version: 0.11.7
    Resource ID: aws_cloudfront_distribution.image-resize-server-apigateway
    Mismatch reason: attribute mismatch: origin.408149110.custom_header.#
2018-04-25T17:23:34.435+0900 [DEBUG] plugin: plugin process exited: path=/Users/kkaizu/dev/src/gitlab.mydomain-sec.com/infra/mydomain-terraform/envs/root/apps/.terraform/plugins/darwin_amd64/terraform-provider-archive_v1.0.3_x4
2018-04-25T17:23:34.437+0900 [DEBUG] plugin: plugin process exited: path=/Users/kkaizu/dev/src/gitlab.mydomain-sec.com/infra/mydomain-terraform/envs/root/apps/.terraform/plugins/darwin_amd64/terraform-provider-aws_v1.15.0_x4
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"origin.408149110.origin_id":*terraform.ResourceAttrDiff{Old:"mydomain-image-resize-server-dev", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.~3591556650.domain_name":*terraform.ResourceAttrDiff{Old:"", New:"${replace(aws_api_gateway_deployment.image-resize-api.invoke_url, \"/^https://(.+)/.+$/\", \"$1\")}", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.408149110.custom_origin_config.2445681895.origin_keepalive_timeout":*terraform.ResourceAttrDiff{Old:"5", New:"0", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.408149110.custom_origin_config.2445681895.https_port":*terraform.ResourceAttrDiff{Old:"443", New:"0", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.~3591556650.custom_origin_config.2445681895.http_port":*terraform.ResourceAttrDiff{Old:"", New:"80", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.~3591556650.s3_origin_config.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.~3591556650.custom_origin_config.#":*terraform.ResourceAttrDiff{Old:"0", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.~3591556650.custom_origin_config.2445681895.https_port":*terraform.ResourceAttrDiff{Old:"", New:"443", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.408149110.custom_origin_config.2445681895.origin_read_timeout":*terraform.ResourceAttrDiff{Old:"30", New:"0", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.~3591556650.custom_origin_config.2445681895.origin_protocol_policy":*terraform.ResourceAttrDiff{Old:"", New:"https-only", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.408149110.origin_path":*terraform.ResourceAttrDiff{Old:"/dev", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.~3591556650.custom_header.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.~3591556650.custom_origin_config.2445681895.origin_keepalive_timeout":*terraform.ResourceAttrDiff{Old:"", New:"5", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.408149110.custom_origin_config.#":*terraform.ResourceAttrDiff{Old:"1", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.408149110.custom_origin_config.2445681895.origin_protocol_policy":*terraform.ResourceAttrDiff{Old:"https-only", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.408149110.custom_origin_config.2445681895.origin_ssl_protocols.0":*terraform.ResourceAttrDiff{Old:"TLSv1.2", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.~3591556650.custom_origin_config.2445681895.origin_read_timeout":*terraform.ResourceAttrDiff{Old:"", New:"30", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.~3591556650.origin_id":*terraform.ResourceAttrDiff{Old:"", New:"mydomain-image-resize-server-dev", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.~3591556650.origin_path":*terraform.ResourceAttrDiff{Old:"", New:"/dev", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.408149110.custom_header.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.~3591556650.custom_origin_config.2445681895.origin_ssl_protocols.#":*terraform.ResourceAttrDiff{Old:"0", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.408149110.s3_origin_config.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.408149110.custom_origin_config.2445681895.origin_ssl_protocols.#":*terraform.ResourceAttrDiff{Old:"1", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.~3591556650.custom_origin_config.2445681895.origin_ssl_protocols.0":*terraform.ResourceAttrDiff{Old:"", New:"TLSv1.2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.408149110.custom_origin_config.2445681895.http_port":*terraform.ResourceAttrDiff{Old:"80", New:"0", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.408149110.domain_name":*terraform.ResourceAttrDiff{Old:"hsl9zd51n6.execute-api.ap-northeast-1.amazonaws.com", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. terraform apply
2. terraform apply // diff didn't match

### Important Factoids
AWS

### References
Not Found

### LINKED ISSUE #5526: AWS Cloudfront Distribution diffs didnt match during apply
_This issue was originally opened by @vietmyob as hashicorp/terraform#18663. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Crash Output
* module.shell-settings-cdn.aws_cloudfront_distribution.cloudfront: aws_cloudfront_distribution.cloudfront: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.11.7
    Resource ID: aws_cloudfront_distribution.cloudfront
    Mismatch reason: attribute mismatch: origin.2988318433.custom_header.#
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"origin.~191066407.domain_name":*terraform.ResourceAttrDiff{Old:"", New:"${aws_s3_bucket.module.bucket_domain_name}", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.~191066407.s3_origin_config.2190239166.origin_access_identity":*terraform.ResourceAttrDiff{Old:"", New:"origin-access-identity/cloudfront/E1T1CG29ED8V57", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.~191066407.origin_path":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.~191066407.origin_id":*terraform.ResourceAttrDiff{Old:"", New:"bucket_settings-module-dev", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.2988318433.custom_header.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.2988318433.origin_id":*terraform.ResourceAttrDiff{Old:"bucket_settings-module-dev", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.~191066407.custom_header.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.2988318433.domain_name":*terraform.ResourceAttrDiff{Old:"settings-module-dev.s3.amazonaws.com", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.~191066407.s3_origin_config.#":*terraform.ResourceAttrDiff{Old:"0", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.~191066407.custom_origin_config.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.2988318433.s3_origin_config.2190239166.origin_access_identity":*terraform.ResourceAttrDiff{Old:"origin-access-identity/cloudfront/E1T1CG29ED8V57", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.2988318433.custom_origin_config.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.2988318433.origin_path":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.2988318433.s3_origin_config.#":*terraform.ResourceAttrDiff{Old:"1", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
### Steps to Reproduce
I was changing the name of s3 resource which is being referred to in CloudFront distribution. When I run terraform apply, it shows that CloudFront needs to be updated but from the plan, it seems like it is not changing anything since s3 bucket name is not actually changing - only the name of the s3 resource is being changed.

After this error, I try to terraform plan but it shows no changes to be made. Does that mean everything is fine?
### References

### LINKED ISSUE #7709: resource/aws_cloudfront_distribution: Convert all TypeSet + MaxItems: 1 to TypeList
## Description

There are a _ton_ of reports of `diffs didn't match during apply` bug and plan output confusion with the `aws_cloudfront_distribution` Terraform resource: https://github.com/terraform-providers/terraform-provider-aws/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Aservice%2Fcloudfront+label%3Abug+

Output like [this report](https://github.com/terraform-providers/terraform-provider-aws/issues/1112#issuecomment-378877927) is pretty unreadable:

```
  ~ module.xxx_files.aws_cloudfront_distribution.files_distribution
      default_cache_behavior.2621983866.allowed_methods.#:                                                  "0" => "3"
      default_cache_behavior.2621983866.allowed_methods.0:                                                  "" => "GET"
      default_cache_behavior.2621983866.allowed_methods.1:                                                  "" => "HEAD"
      default_cache_behavior.2621983866.allowed_methods.2:                                                  "" => "OPTIONS"
      default_cache_behavior.2621983866.cached_methods.#:                                                   "0" => "2"
      default_cache_behavior.2621983866.cached_methods.0:                                                   "" => "GET"
      default_cache_behavior.2621983866.cached_methods.1:                                                   "" => "HEAD"
      default_cache_behavior.2621983866.compress:                                                           "" => "true"
      default_cache_behavior.2621983866.default_ttl:                                                        "" => "30"
      default_cache_behavior.2621983866.forwarded_values.#:                                                 "0" => "1"
      default_cache_behavior.2621983866.forwarded_values.2555876073.cookies.#:                              "0" => "1"
      default_cache_behavior.2621983866.forwarded_values.2555876073.cookies.2625240281.forward:             "" => "none"
      default_cache_behavior.2621983866.forwarded_values.2555876073.cookies.2625240281.whitelisted_names.#: "0" => "0"
      default_cache_behavior.2621983866.forwarded_values.2555876073.headers.#:                              "0" => "0"
      default_cache_behavior.2621983866.forwarded_values.2555876073.query_string:                           "" => "true"
      default_cache_behavior.2621983866.forwarded_values.2555876073.query_string_cache_keys.#:              "0" => "0"
      default_cache_behavior.2621983866.lambda_function_association.#:                                      "0" => "0"
      default_cache_behavior.2621983866.max_ttl:                                                            "" => "86400"
      default_cache_behavior.2621983866.min_ttl:                                                            "" => "0"
      default_cache_behavior.2621983866.smooth_streaming:                                                   "" => ""
      default_cache_behavior.2621983866.target_origin_id:                                                   "" => "s3_files_bucket"
      default_cache_behavior.2621983866.trusted_signers.#:                                                  "0" => "1"
      default_cache_behavior.2621983866.trusted_signers.0:                                                  "" => "731459125315"
      default_cache_behavior.2621983866.viewer_protocol_policy:                                             "" => "https-only"
      default_cache_behavior.4147833275.allowed_methods.#:                                                  "3" => "0"
      default_cache_behavior.4147833275.allowed_methods.0:                                                  "HEAD" => ""
      default_cache_behavior.4147833275.allowed_methods.1:                                                  "GET" => ""
      default_cache_behavior.4147833275.allowed_methods.2:                                                  "OPTIONS" => ""
      default_cache_behavior.4147833275.cached_methods.#:                                                   "2" => "0"
      default_cache_behavior.4147833275.cached_methods.0:                                                   "HEAD" => ""
      default_cache_behavior.4147833275.cached_methods.1:                                                   "GET" => ""
      default_cache_behavior.4147833275.compress:                                                           "true" => "false"
      default_cache_behavior.4147833275.default_ttl:                                                        "30" => "0"
      default_cache_behavior.4147833275.forwarded_values.#:                                                 "1" => "0"
      default_cache_behavior.4147833275.forwarded_values.2555876073.cookies.#:                              "1" => "0"
      default_cache_behavior.4147833275.forwarded_values.2555876073.cookies.2625240281.forward:             "none" => ""
      default_cache_behavior.4147833275.forwarded_values.2555876073.cookies.2625240281.whitelisted_names.#: "0" => "0"
      default_cache_behavior.4147833275.forwarded_values.2555876073.headers.#:                              "0" => "0"
      default_cache_behavior.4147833275.forwarded_values.2555876073.query_string:                           "true" => "false"
      default_cache_behavior.4147833275.forwarded_values.2555876073.query_string_cache_keys.#:              "0" => "0"
      default_cache_behavior.4147833275.lambda_function_association.#:                                      "0" => "0"
      default_cache_behavior.4147833275.max_ttl:                                                            "86400" => "0"
      default_cache_behavior.4147833275.min_ttl:                                                            "0" => "0"
      default_cache_behavior.4147833275.smooth_streaming:                                                   "false" => "false"
      default_cache_behavior.4147833275.target_origin_id:                                                   "s3_files_bucket" => ""
      default_cache_behavior.4147833275.trusted_signers.#:                                                  "1" => "0"
      default_cache_behavior.4147833275.trusted_signers.0:                                                  "self" => ""
      default_cache_behavior.4147833275.viewer_protocol_policy:                                             "https-only" => ""
```

While Terraform 0.12 will have slightly better plan output for this scenario, the TypeSet usage is extraneous in many cases as using a TypeList for the "container" attribute would simplify everything. Ideally this can be slotted in with our version 2.0.0 release work since its pretty invasive.

### PR DESCRIPTION
**Pull request by bflad**
Closes #7709
Closes #5526
Closes #4338
Closes #3842
Closes #3766
Closes #3256
Closes #1194
Closes #824
Closes #416

The usage of `TypeSet` for single container block attributes can cause unnecessary problems with Terraform's difference logic and makes plan output unnecessarily more difficult to read. Here we adjust these to `TypeList`.

Converted the following from `Type: schema.TypeSet` and `MaxItems: 1` to `Type: schema.TypeList`:

* `default_cache_behavior` configuration block
* `default_cache_behavior` configuration block `forwarded_values` configuration block
* `default_cache_behavior` configuration block `forwarded_values` configuration block `cookies` configuration block
* `logging_config` configuration block
* `origin` configuration block `custom_origin_config` configuration block
* `origin` configuration block `s3_origin_config` configuration block
* `ordered_cache_behavior` configuration block `forwarded_values` configuration block
* `ordered_cache_behavior` configuration block `forwarded_values` configuration block `cookies` configuration block
* `restrictions` configuration block
* `restrictions` configuration block `geo_restriction` configuration block
* `viewer_certificate` configuration block

The usage of `TypeList` for arguments where ordering does not matter causes unnecessary hassle for operators to match their configuration to the CloudFront API. Here we replace these with `TypeSet` to ignore ordering.

Converted the following from `Type: schema.TypeList` to `Type: schema.TypeSet`:

* `default_cache_behavior` configuration block `allowed_methods` argument
* `default_cache_behavior` configuration block `cached_methods` argument
* `origin` configuration block `custom_origin_config` configuration block `origin_ssl_protocols` argument
* `restrictions` configuration block `geo_restriction` configuration block `locations` argument

This change was verified with a live configuration outside the acceptance testing framework with Terraform 0.11 as effectively a no-op for the most common use case configurations that do not later reference these attributes.

```console
$ terraform apply
...
aws_cloudfront_distribution.test: Creating...
  active_trusted_signers.%:                                                                             "" => "<computed>"
  arn:                                                                                                  "" => "<computed>"
  caller_reference:                                                                                     "" => "<computed>"
  default_cache_behavior.#:                                                                             "0" => "1"
  default_cache_behavior.1848826977.allowed_methods.#:                                                  "0" => "7"
  default_cache_behavior.1848826977.allowed_methods.0:                                                  "" => "DELETE"
  default_cache_behavior.1848826977.allowed_methods.1:                                                  "" => "GET"
  default_cache_behavior.1848826977.allowed_methods.2:                                                  "" => "HEAD"
  default_cache_behavior.1848826977.allowed_methods.3:                                                  "" => "OPTIONS"
  default_cache_behavior.1848826977.allowed_methods.4:                                                  "" => "PATCH"
  default_cache_behavior.1848826977.allowed_methods.5:                                                  "" => "POST"
  default_cache_behavior.1848826977.allowed_methods.6:                                                  "" => "PUT"
  default_cache_behavior.1848826977.cached_methods.#:                                                   "0" => "2"
  default_cache_behavior.1848826977.cached_methods.0:                                                   "" => "GET"
  default_cache_behavior.1848826977.cached_methods.1:                                                   "" => "HEAD"
  default_cache_behavior.1848826977.compress:                                                           "" => "false"
  default_cache_behavior.1848826977.default_ttl:                                                        "" => "100"
  default_cache_behavior.1848826977.field_level_encryption_id:                                          "" => ""
  default_cache_behavior.1848826977.forwarded_values.#:                                                 "0" => "1"
  default_cache_behavior.1848826977.forwarded_values.2510654351.cookies.#:                              "0" => "1"
  default_cache_behavior.1848826977.forwarded_values.2510654351.cookies.1870923232.forward:             "" => "all"
  default_cache_behavior.1848826977.forwarded_values.2510654351.cookies.1870923232.whitelisted_names.#: "0" => "0"
  default_cache_behavior.1848826977.forwarded_values.2510654351.headers.#:                              "0" => "0"
  default_cache_behavior.1848826977.forwarded_values.2510654351.query_string:                           "" => "false"
  default_cache_behavior.1848826977.forwarded_values.2510654351.query_string_cache_keys.#:              "0" => "0"
  default_cache_behavior.1848826977.lambda_function_association.#:                                      "0" => "0"
  default_cache_behavior.1848826977.max_ttl:                                                            "" => "100"
  default_cache_behavior.1848826977.min_ttl:                                                            "" => "100"
  default_cache_behavior.1848826977.smooth_streaming:                                                   "" => "true"
  default_cache_behavior.1848826977.target_origin_id:                                                   "" => "myCustomOrigin"
  default_cache_behavior.1848826977.trusted_signers.#:                                                  "0" => "0"
  default_cache_behavior.1848826977.viewer_protocol_policy:                                             "" => "allow-all"
  domain_name:                                                                                          "" => "<computed>"
  enabled:                                                                                              "" => "true"
  etag:                                                                                                 "" => "<computed>"
  hosted_zone_id:                                                                                       "" => "<computed>"
  http_version:                                                                                         "" => "http2"
  in_progress_validation_batches:                                                                       "" => "<computed>"
  is_ipv6_enabled:                                                                                      "" => "false"
  last_modified_time:                                                                                   "" => "<computed>"
  ordered_cache_behavior.#:                                                                             "0" => "2"
  ordered_cache_behavior.0.allowed_methods.#:                                                           "0" => "7"
  ordered_cache_behavior.0.allowed_methods.1012961568:                                                  "" => "POST"
  ordered_cache_behavior.0.allowed_methods.1040875975:                                                  "" => "GET"
  ordered_cache_behavior.0.allowed_methods.1445840968:                                                  "" => "HEAD"
  ordered_cache_behavior.0.allowed_methods.1741119464:                                                  "" => "PATCH"
  ordered_cache_behavior.0.allowed_methods.348445828:                                                   "" => "DELETE"
  ordered_cache_behavior.0.allowed_methods.3982006612:                                                  "" => "OPTIONS"
  ordered_cache_behavior.0.allowed_methods.4024585617:                                                  "" => "PUT"
  ordered_cache_behavior.0.cached_methods.#:                                                            "0" => "2"
  ordered_cache_behavior.0.cached_methods.1040875975:                                                   "" => "GET"
  ordered_cache_behavior.0.cached_methods.1445840968:                                                   "" => "HEAD"
  ordered_cache_behavior.0.compress:                                                                    "" => "false"
  ordered_cache_behavior.0.default_ttl:                                                                 "" => "50"
  ordered_cache_behavior.0.forwarded_values.#:                                                          "0" => "1"
  ordered_cache_behavior.0.forwarded_values.2555876073.cookies.#:                                       "0" => "1"
  ordered_cache_behavior.0.forwarded_values.2555876073.cookies.2625240281.forward:                      "" => "none"
  ordered_cache_behavior.0.forwarded_values.2555876073.cookies.2625240281.whitelisted_names.#:          "0" => "0"
  ordered_cache_behavior.0.forwarded_values.2555876073.headers.#:                                       "0" => "0"
  ordered_cache_behavior.0.forwarded_values.2555876073.query_string:                                    "" => "true"
  ordered_cache_behavior.0.forwarded_values.2555876073.query_string_cache_keys.#:                       "0" => "0"
  ordered_cache_behavior.0.max_ttl:                                                                     "" => "50"
  ordered_cache_behavior.0.min_ttl:                                                                     "" => "50"
  ordered_cache_behavior.0.path_pattern:                                                                "" => "images1/*.jpg"
  ordered_cache_behavior.0.target_origin_id:                                                            "" => "myCustomOrigin"
  ordered_cache_behavior.0.viewer_protocol_policy:                                                      "" => "allow-all"
  ordered_cache_behavior.1.allowed_methods.#:                                                           "0" => "7"
  ordered_cache_behavior.1.allowed_methods.1012961568:                                                  "" => "POST"
  ordered_cache_behavior.1.allowed_methods.1040875975:                                                  "" => "GET"
  ordered_cache_behavior.1.allowed_methods.1445840968:                                                  "" => "HEAD"
  ordered_cache_behavior.1.allowed_methods.1741119464:                                                  "" => "PATCH"
  ordered_cache_behavior.1.allowed_methods.348445828:                                                   "" => "DELETE"
  ordered_cache_behavior.1.allowed_methods.3982006612:                                                  "" => "OPTIONS"
  ordered_cache_behavior.1.allowed_methods.4024585617:                                                  "" => "PUT"
  ordered_cache_behavior.1.cached_methods.#:                                                            "0" => "2"
  ordered_cache_behavior.1.cached_methods.1040875975:                                                   "" => "GET"
  ordered_cache_behavior.1.cached_methods.1445840968:                                                   "" => "HEAD"
  ordered_cache_behavior.1.compress:                                                                    "" => "false"
  ordered_cache_behavior.1.default_ttl:                                                                 "" => "51"
  ordered_cache_behavior.1.forwarded_values.#:                                                          "0" => "1"
  ordered_cache_behavior.1.forwarded_values.2555876073.cookies.#:                                       "0" => "1"
  ordered_cache_behavior.1.forwarded_values.2555876073.cookies.2625240281.forward:                      "" => "none"
  ordered_cache_behavior.1.forwarded_values.2555876073.cookies.2625240281.whitelisted_names.#:          "0" => "0"
  ordered_cache_behavior.1.forwarded_values.2555876073.headers.#:                                       "0" => "0"
  ordered_cache_behavior.1.forwarded_values.2555876073.query_string:                                    "" => "true"
  ordered_cache_behavior.1.forwarded_values.2555876073.query_string_cache_keys.#:                       "0" => "0"
  ordered_cache_behavior.1.max_ttl:                                                                     "" => "51"
  ordered_cache_behavior.1.min_ttl:                                                                     "" => "51"
  ordered_cache_behavior.1.path_pattern:                                                                "" => "images2/*.jpg"
  ordered_cache_behavior.1.target_origin_id:                                                            "" => "myCustomOrigin"
  ordered_cache_behavior.1.viewer_protocol_policy:                                                      "" => "allow-all"
  origin.#:                                                                                             "0" => "1"
  origin.1857972443.custom_header.#:                                                                    "0" => "0"
  origin.1857972443.custom_origin_config.#:                                                             "0" => "1"
  origin.1857972443.custom_origin_config.3832794885.http_port:                                          "" => "80"
  origin.1857972443.custom_origin_config.3832794885.https_port:                                         "" => "443"
  origin.1857972443.custom_origin_config.3832794885.origin_keepalive_timeout:                           "" => "5"
  origin.1857972443.custom_origin_config.3832794885.origin_protocol_policy:                             "" => "http-only"
  origin.1857972443.custom_origin_config.3832794885.origin_read_timeout:                                "" => "30"
  origin.1857972443.custom_origin_config.3832794885.origin_ssl_protocols.#:                             "0" => "2"
  origin.1857972443.custom_origin_config.3832794885.origin_ssl_protocols.0:                             "" => "SSLv3"
  origin.1857972443.custom_origin_config.3832794885.origin_ssl_protocols.1:                             "" => "TLSv1"
  origin.1857972443.domain_name:                                                                        "" => "www.example.com"
  origin.1857972443.origin_id:                                                                          "" => "myCustomOrigin"
  origin.1857972443.origin_path:                                                                        "" => ""
  origin.1857972443.s3_origin_config.#:                                                                 "0" => "0"
  price_class:                                                                                          "" => "PriceClass_All"
  restrictions.#:                                                                                       "0" => "1"
  restrictions.811065190.geo_restriction.#:                                                             "0" => "1"
  restrictions.811065190.geo_restriction.1303118592.locations.#:                                        "0" => "4"
  restrictions.811065190.geo_restriction.1303118592.locations.0:                                        "" => "US"
  restrictions.811065190.geo_restriction.1303118592.locations.1:                                        "" => "CA"
  restrictions.811065190.geo_restriction.1303118592.locations.2:                                        "" => "GB"
  restrictions.811065190.geo_restriction.1303118592.locations.3:                                        "" => "DE"
  restrictions.811065190.geo_restriction.1303118592.restriction_type:                                   "" => "whitelist"
  retain_on_delete:                                                                                     "" => "false"
  status:                                                                                               "" => "<computed>"
  viewer_certificate.#:                                                                                 "0" => "1"
  viewer_certificate.69840937.acm_certificate_arn:                                                      "" => ""
  viewer_certificate.69840937.cloudfront_default_certificate:                                           "" => "true"
  viewer_certificate.69840937.iam_certificate_id:                                                       "" => ""
  viewer_certificate.69840937.minimum_protocol_version:                                                 "" => "TLSv1"
  viewer_certificate.69840937.ssl_support_method:                                                       "" => ""
aws_cloudfront_distribution.test: Creation complete after 0s (ID: E3K1GJF3SSNJRN)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

$ cp ~/go/bin/terraform-provider-aws .terraform/plugins/darwin_amd64/terraform-provider-aws_v1.60.0_x4; terraform init # this binary is an updated Terraform AWS Provider built with these changes

$ terraform apply # Here we see no state migration required
aws_cloudfront_distribution.test: Refreshing state... (ID: E3K1GJF3SSNJRN)

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

$ terraform state show aws_cloudfront_distribution.test # Here we see a successful state refresh with the new layout
id                                                                        = E3K1GJF3SSNJRN
active_trusted_signers.%                                                  = 2
active_trusted_signers.enabled                                            = false
active_trusted_signers.items.#                                            = 0
aliases.#                                                                 = 0
arn                                                                       = arn:aws:cloudfront::187416307283:distribution/E3K1GJF3SSNJRN
caller_reference                                                          = 2019-02-25T14:51:42.674464-05:00
custom_error_response.#                                                   = 0
default_cache_behavior.#                                                  = 1
default_cache_behavior.0.allowed_methods.#                                = 7
default_cache_behavior.0.allowed_methods.1012961568                       = POST
default_cache_behavior.0.allowed_methods.1040875975                       = GET
default_cache_behavior.0.allowed_methods.1445840968                       = HEAD
default_cache_behavior.0.allowed_methods.1741119464                       = PATCH
default_cache_behavior.0.allowed_methods.348445828                        = DELETE
default_cache_behavior.0.allowed_methods.3982006612                       = OPTIONS
default_cache_behavior.0.allowed_methods.4024585617                       = PUT
default_cache_behavior.0.cached_methods.#                                 = 2
default_cache_behavior.0.cached_methods.1040875975                        = GET
default_cache_behavior.0.cached_methods.1445840968                        = HEAD
default_cache_behavior.0.compress                                         = false
default_cache_behavior.0.default_ttl                                      = 100
default_cache_behavior.0.field_level_encryption_id                        =
default_cache_behavior.0.forwarded_values.#                               = 1
default_cache_behavior.0.forwarded_values.0.cookies.#                     = 1
default_cache_behavior.0.forwarded_values.0.cookies.0.forward             = all
default_cache_behavior.0.forwarded_values.0.cookies.0.whitelisted_names.# = 0
default_cache_behavior.0.forwarded_values.0.headers.#                     = 0
default_cache_behavior.0.forwarded_values.0.query_string                  = false
default_cache_behavior.0.forwarded_values.0.query_string_cache_keys.#     = 0
default_cache_behavior.0.lambda_function_association.#                    = 0
default_cache_behavior.0.max_ttl                                          = 100
default_cache_behavior.0.min_ttl                                          = 100
default_cache_behavior.0.smooth_streaming                                 = true
default_cache_behavior.0.target_origin_id                                 = myCustomOrigin
default_cache_behavior.0.trusted_signers.#                                = 0
default_cache_behavior.0.viewer_protocol_policy                           = allow-all
default_root_object                                                       =
domain_name                                                               = dot6h04nf0cmx.cloudfront.net
enabled                                                                   = true
etag                                                                      = E33ZADXZHBHVXT
hosted_zone_id                                                            = Z2FDTNDATAQYW2
http_version                                                              = http2
in_progress_validation_batches                                            = 0
is_ipv6_enabled                                                           = false
last_modified_time                                                        = 2019-02-26 02:22:40.558 +0000 UTC
logging_config.#                                                          = 0
ordered_cache_behavior.#                                                  = 2
ordered_cache_behavior.0.allowed_methods.#                                = 7
ordered_cache_behavior.0.allowed_methods.1012961568                       = POST
ordered_cache_behavior.0.allowed_methods.1040875975                       = GET
ordered_cache_behavior.0.allowed_methods.1445840968                       = HEAD
ordered_cache_behavior.0.allowed_methods.1741119464                       = PATCH
ordered_cache_behavior.0.allowed_methods.348445828                        = DELETE
ordered_cache_behavior.0.allowed_methods.3982006612                       = OPTIONS
ordered_cache_behavior.0.allowed_methods.4024585617                       = PUT
ordered_cache_behavior.0.cached_methods.#                                 = 2
ordered_cache_behavior.0.cached_methods.1040875975                        = GET
ordered_cache_behavior.0.cached_methods.1445840968                        = HEAD
ordered_cache_behavior.0.compress                                         = false
ordered_cache_behavior.0.default_ttl                                      = 50
ordered_cache_behavior.0.field_level_encryption_id                        =
ordered_cache_behavior.0.forwarded_values.#                               = 1
ordered_cache_behavior.0.forwarded_values.0.cookies.#                     = 1
ordered_cache_behavior.0.forwarded_values.0.cookies.0.forward             = none
ordered_cache_behavior.0.forwarded_values.0.cookies.0.whitelisted_names.# = 0
ordered_cache_behavior.0.forwarded_values.0.headers.#                     = 0
ordered_cache_behavior.0.forwarded_values.0.query_string                  = true
ordered_cache_behavior.0.forwarded_values.0.query_string_cache_keys.#     = 0
ordered_cache_behavior.0.lambda_function_association.#                    = 0
ordered_cache_behavior.0.max_ttl                                          = 50
ordered_cache_behavior.0.min_ttl                                          = 50
ordered_cache_behavior.0.path_pattern                                     = images1/*.jpg
ordered_cache_behavior.0.smooth_streaming                                 = false
ordered_cache_behavior.0.target_origin_id                                 = myCustomOrigin
ordered_cache_behavior.0.trusted_signers.#                                = 0
ordered_cache_behavior.0.viewer_protocol_policy                           = allow-all
ordered_cache_behavior.1.allowed_methods.#                                = 7
ordered_cache_behavior.1.allowed_methods.1012961568                       = POST
ordered_cache_behavior.1.allowed_methods.1040875975                       = GET
ordered_cache_behavior.1.allowed_methods.1445840968                       = HEAD
ordered_cache_behavior.1.allowed_methods.1741119464                       = PATCH
ordered_cache_behavior.1.allowed_methods.348445828                        = DELETE
ordered_cache_behavior.1.allowed_methods.3982006612                       = OPTIONS
ordered_cache_behavior.1.allowed_methods.4024585617                       = PUT
ordered_cache_behavior.1.cached_methods.#                                 = 2
ordered_cache_behavior.1.cached_methods.1040875975                        = GET
ordered_cache_behavior.1.cached_methods.1445840968                        = HEAD
ordered_cache_behavior.1.compress                                         = false
ordered_cache_behavior.1.default_ttl                                      = 51
ordered_cache_behavior.1.field_level_encryption_id                        =
ordered_cache_behavior.1.forwarded_values.#                               = 1
ordered_cache_behavior.1.forwarded_values.0.cookies.#                     = 1
ordered_cache_behavior.1.forwarded_values.0.cookies.0.forward             = none
ordered_cache_behavior.1.forwarded_values.0.cookies.0.whitelisted_names.# = 0
ordered_cache_behavior.1.forwarded_values.0.headers.#                     = 0
ordered_cache_behavior.1.forwarded_values.0.query_string                  = true
ordered_cache_behavior.1.forwarded_values.0.query_string_cache_keys.#     = 0
ordered_cache_behavior.1.lambda_function_association.#                    = 0
ordered_cache_behavior.1.max_ttl                                          = 51
ordered_cache_behavior.1.min_ttl                                          = 51
ordered_cache_behavior.1.path_pattern                                     = images2/*.jpg
ordered_cache_behavior.1.smooth_streaming                                 = false
ordered_cache_behavior.1.target_origin_id                                 = myCustomOrigin
ordered_cache_behavior.1.trusted_signers.#                                = 0
ordered_cache_behavior.1.viewer_protocol_policy                           = allow-all
origin.#                                                                  = 1
origin.1857972443.custom_header.#                                         = 0
origin.1857972443.custom_origin_config.#                                  = 1
origin.1857972443.custom_origin_config.0.http_port                        = 80
origin.1857972443.custom_origin_config.0.https_port                       = 443
origin.1857972443.custom_origin_config.0.origin_keepalive_timeout         = 5
origin.1857972443.custom_origin_config.0.origin_protocol_policy           = http-only
origin.1857972443.custom_origin_config.0.origin_read_timeout              = 30
origin.1857972443.custom_origin_config.0.origin_ssl_protocols.#           = 2
origin.1857972443.custom_origin_config.0.origin_ssl_protocols.1162609714  = TLSv1
origin.1857972443.custom_origin_config.0.origin_ssl_protocols.2159350162  = SSLv3
origin.1857972443.domain_name                                             = www.example.com
origin.1857972443.origin_id                                               = myCustomOrigin
origin.1857972443.origin_path                                             =
origin.1857972443.s3_origin_config.#                                      = 0
price_class                                                               = PriceClass_All
restrictions.#                                                            = 1
restrictions.0.geo_restriction.#                                          = 1
restrictions.0.geo_restriction.0.locations.#                              = 4
restrictions.0.geo_restriction.0.locations.3034033770                     = DE
restrictions.0.geo_restriction.0.locations.3047936762                     = US
restrictions.0.geo_restriction.0.locations.3589570027                     = CA
restrictions.0.geo_restriction.0.locations.4191192820                     = GB
restrictions.0.geo_restriction.0.restriction_type                         = whitelist
retain_on_delete                                                          = false
status                                                                    = Deployed
tags.%                                                                    = 0
viewer_certificate.#                                                      = 1
viewer_certificate.0.acm_certificate_arn                                  =
viewer_certificate.0.cloudfront_default_certificate                       = true
viewer_certificate.0.iam_certificate_id                                   =
viewer_certificate.0.minimum_protocol_version                             = TLSv1
viewer_certificate.0.ssl_support_method                                   =
web_acl_id                                                                =
```

Output from acceptance testing:

```
--- PASS: TestAccAWSCloudFrontDistribution_Origin_EmptyOriginID (1.04s)
--- PASS: TestAccAWSCloudFrontDistribution_Origin_EmptyDomainName (1.12s)
--- PASS: TestAccAWSCloudFrontDistribution_orderedCacheBehavior (1082.43s)
--- PASS: TestAccAWSCloudFrontDistribution_HTTP11Config (1082.47s)
--- PASS: TestAccAWSCloudFrontDistribution_noCustomErrorResponseConfig (1083.16s)
--- PASS: TestAccAWSCloudFrontDistribution_noOptionalItemsConfig (1083.56s)
--- PASS: TestAccAWSCloudFrontDistribution_S3OriginWithTags (1084.20s)
--- PASS: TestAccAWSCloudFrontDistribution_IsIPV6EnabledConfig (1089.11s)
--- PASS: TestAccAWSCloudFrontDistribution_S3Origin (1090.38s)
--- PASS: TestAccAWSCloudFrontDistribution_customOrigin (1092.54s)
--- PASS: TestAccAWSCloudFrontDistribution_multiOrigin (1093.67s)
```

### CODE REVIEW

File: aws/cloudfront_distribution_configuration_structure.go [hunk 1]
```diff
@@ -266,54 +180,51 @@ func flattenCacheBehaviors(cbs *cloudfront.CacheBehaviors) []interface{} {
...
 	}
 	if v, ok := m["allowed_methods"]; ok {
-		cb.AllowedMethods = expandAllowedMethodsDeprecated(v.([]interface{}))
+		dcb.AllowedMethods = expandAllowedMethods(v.(*schema.Set))
 	}
 	if v, ok := m["cached_methods"]; ok {
-		cb.AllowedMethods.CachedMethods = expandCachedMethodsDeprecated(v.([]interface{}))
-	}
-	if v, ok := m["path_pattern"]; ok {
-		cb.PathPattern = aws.String(v.(string))
```
Comment (bflad) [inline aws/cloudfront_distribution_configuration_structure.go]: [`PathPattern` is not a struct field in `DefaultCacheBehavior`](https://docs.aws.amazon.com/sdk-for-go/api/service/cloudfront/#DefaultCacheBehavior) so is removed here.

File: aws/cloudfront_distribution_configuration_structure.go [hunk 2]
```diff
@@ -43,33 +33,26 @@ func (p StringPtrSlice) Swap(i, j int)      { p[i], p[j] = p[j], p[i] }
...
-	if v, ok := d.GetOk("caller_reference"); !ok {
-		distributionConfig.CallerReference = aws.String(time.Now().Format(time.RFC3339Nano))
-	} else {
+	if v, ok := d.GetOk("caller_reference"); ok {
 		distributionConfig.CallerReference = aws.String(v.(string))
 	}
-	if v, ok := d.GetOk("comment"); ok {
-		distributionConfig.Comment = aws.String(v.(string))
-	} else {
-		distributionConfig.Comment = aws.String("")
```
Comment (bflad) [inline aws/cloudfront_distribution_configuration_structure.go]: The if/else logic here was extraneous as `d.Get("ATTR").(string)` will return the zero value (`""`), so moved above into `DistributionConfig` struct creation above.

File: aws/cloudfront_distribution_configuration_structure.go [hunk 3]
```diff
@@ -341,40 +252,38 @@ func expandCacheBehavior(m map[string]interface{}) *cloudfront.CacheBehavior {
...
-
-	m["compress"] = *cb.Compress
-	m["field_level_encryption_id"] = aws.StringValue(cb.FieldLevelEncryptionId)
-	m["viewer_protocol_policy"] = *cb.ViewerProtocolPolicy
-	m["target_origin_id"] = *cb.TargetOriginId
-	m["forwarded_values"] = schema.NewSet(forwardedValuesHash, []interface{}{flattenForwardedValues(cb.ForwardedValues)})
-	m["min_ttl"] = int(*cb.MinTTL)
+func flattenCloudFrontDefaultCacheBehavior(dcb *cloudfront.DefaultCacheBehavior) map[string]interface{} {
+	m := map[string]interface{}{
+		"compress":                  aws.BoolValue(dcb.Compress),
```
Comment (bflad) [inline aws/cloudfront_distribution_configuration_structure.go]: Using AWS Go SDK functions for `nil` deference safety.

File: aws/cloudfront_distribution_configuration_structure.go [hunk 4]
```diff
@@ -341,40 +252,38 @@ func expandCacheBehavior(m map[string]interface{}) *cloudfront.CacheBehavior {
...
 	}
-	if cb.AllowedMethods != nil {
-		m["allowed_methods"] = flattenAllowedMethodsDeprecated(cb.AllowedMethods)
+	if dcb.AllowedMethods != nil {
+		m["allowed_methods"] = flattenAllowedMethods(dcb.AllowedMethods)
 	}
-	if cb.AllowedMethods.CachedMethods != nil {
-		m["cached_methods"] = flattenCachedMethodsDeprecated(cb.AllowedMethods.CachedMethods)
-	}
-	if cb.PathPattern != nil {
```
Comment (bflad) [inline aws/cloudfront_distribution_configuration_structure.go]: Same note about `PathPattern` here.

File: aws/cloudfront_distribution_configuration_structure.go [hunk 5]
```diff
@@ -763,15 +606,15 @@ func originHash(v interface{}) int {
 		buf.WriteString(fmt.Sprintf("%d-", customHeadersHash(v.(*schema.Set))))
 	}
 	if v, ok := m["custom_origin_config"]; ok {
-		if s := v.(*schema.Set).List(); len(s) > 0 {
+		if s := v.([]interface{}); len(s) > 0 && s[0] != nil {
```
Comment (bflad) [inline aws/cloudfront_distribution_configuration_structure.go]: `nil` checks specifically added here as I was able to coerce a panic during testing.

File: aws/cloudfront_distribution_configuration_structure_test.go [hunk 6]
```diff
@@ -585,9 +574,6 @@ func TestCloudFrontStructure_flattenOrigin(t *testing.T) {
 	if out["origin_path"] != "/" {
 		t.Fatalf("Expected out[origin_path] to be /, got %v", out["origin_path"])
 	}
-	if !out["custom_origin_config"].(*schema.Set).Equal(in["custom_origin_config"].(*schema.Set)) {
```
Comment (bflad) [inline aws/cloudfront_distribution_configuration_structure_test.go]: `custom_origin_config` itself contains the `origin_ssl_protocols` set, which are not stable to test in this manner.

File: aws/cloudfront_distribution_configuration_structure_test.go [hunk 7]
```diff
@@ -860,8 +836,8 @@ func TestCloudFrontStructure_expandGeoRestriction_whitelist(t *testing.T) {
 	if *gr.Quantity != 3 {
 		t.Fatalf("Expected Quantity to be 3, got %v", *gr.Quantity)
 	}
-	if !reflect.DeepEqual(gr.Items, aws.StringSlice([]string{"CA", "GB", "US"})) {
-		t.Fatalf("Expected Items be [CA, GB, US], got %v", gr.Items)
+	if !reflect.DeepEqual(aws.StringValueSlice(gr.Items), []string{"GB", "US", "CA"}) {
```
Comment (bflad) [inline aws/cloudfront_distribution_configuration_structure_test.go]: The previous resource logic sorted the slice, which is no longer the case for TypeSet usage.

File: aws/resource_aws_cloudfront_distribution.go [hunk 8]
```diff
@@ -67,14 +67,12 @@ func resourceAwsCloudFrontDistribution() *schema.Resource {
 						"forwarded_values": {
 							Type:     schema.TypeSet,
 							Required: true,
-							Set:      forwardedValuesHash,
```
Comment (bflad) [inline aws/resource_aws_cloudfront_distribution.go]: Missed during conversion of `Deprecated` to `Removed` in previous pull request.

File: aws/resource_aws_cloudfront_distribution_test.go [hunk 9]
```diff
@@ -75,29 +75,6 @@ func testSweepCloudFrontDistributions(region string) error {
 	return nil
 }
 
-func TestAccAWSCloudFrontDistribution_importBasic(t *testing.T) {
```
Comment (bflad) [inline aws/resource_aws_cloudfront_distribution_test.go]: Moved import state verification to all acceptance tests to ensure we are consistently reading into the Terraform state from all API responses.
