### PR TITLE
tests/provider: Fix hardcoded ARN (DB*)

### LINKED ISSUE #15770: tests/provider: DB Instance InvalidParameterValue (GovCloud)
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This test fails on GovCloud:

```
TestAccAWSDBOptionGroup_OracleOptionsUpdate
```

With this error: `Error modifying DB Option Group: InvalidParameterValue: Version 12.1.0.4.v1 is invalid for OEM_AGENT option. Valid versions are 13.2.0.0.v1,13.2.0.0.v2,13.2.0.0.v3,13.3.0.0.v1,13.3.0.0.v2`.

### New or Affected Resource(s)

* aws_db_option_group

### Terraform Configuration Files

Initial config:

```hcl
resource "aws_db_option_group" "bar" {
  name                     = "yakdriver"
  option_group_description = "Test option group for terraform issue 748"
  engine_name              = "oracle-ee"
  major_engine_version     = "12.1"

  option {
    option_name = "OEM_AGENT"
    port        = "3872"
    version     = "12.1.0.4.v1"

    vpc_security_group_memberships = [aws_security_group.foo.id]

    option_settings {
      name  = "OMS_PORT"
      value = "4903"
    }

    option_settings {
      name  = "OMS_HOST"
      value = "oem.host.value"
    }

    option_settings {
      name  = "AGENT_REGISTRATION_PASSWORD"
      value = "password"
    }
  }
}
```

Second config:

```hcl
resource "aws_db_option_group" "bar" {
  name                     = "yakdriver"
  option_group_description = "Test option group for terraform issue 748"
  engine_name              = "oracle-ee"
  major_engine_version     = "12.1"

  option {
    option_name = "OEM_AGENT"
    port        = "3872"
    version     = "12.1.0.5.v1"

    vpc_security_group_memberships = [aws_security_group.foo.id]

    option_settings {
      name  = "OMS_PORT"
      value = "4903"
    }

    option_settings {
      name  = "OMS_HOST"
      value = "oem.host.value"
    }

    option_settings {
      name  = "AGENT_REGISTRATION_PASSWORD"
      value = "password"
    }
  }
}
```

### Debug Output

```
TestAccAWSDBOptionGroup_OracleOptionsUpdate: resource_aws_db_option_group_test.go:357: Step 1/3 error: Error
running apply: 2020/10/20 19:43:54 [DEBUG] Using modified User-Agent: Terraform/0.12.29
HashiCorp-terraform-exec/0.10.0
        
        Error: Error modifying DB Option Group: InvalidParameterValue: Version 12.1.0.4.v1 is invalid for
OEM_AGENT option. Valid versions are 13.2.0.0.v1,13.2.0.0.v2,13.2.0.0.v3,13.3.0.0.v1,13.3.0.0.v2
        	status code: 400, request id: 1971537f-ae82-4a66-b8c2-2d32ab4dd153

--- FAIL: TestAccAWSDBOptionGroup_OracleOptionsUpdate (5.12s)
```

### References

* #15733
* #15662

### LINKED ISSUE #15772: tests/provider: DB Instance CAC failure (GovCloud)
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This test fails on GovCloud:

```
TestAccAWSDBInstance_CACertificateIdentifier
TestAccAWSDBInstance_ReplicateSourceDb_CACertificateIdentifier
```

With this error: `CertificateNotFound: Certificate not found`.

It appears to be a testing environment/account issue.

### New or Affected Resource(s)

* aws_db_instance

### Terraform Configuration Files

Initial config:

```hcl
resource "aws_db_instance" "bar" {
  allocated_storage   = 10
  apply_immediately   = true
  ca_cert_identifier  = "rds-ca-2019"
  engine              = data.aws_rds_orderable_db_instance.test.engine
  instance_class      = data.aws_rds_orderable_db_instance.test.instance_class
  name                = "baz"
  password            = "barbarbarbar"
  skip_final_snapshot = true
  username            = "foo"
}
```

### Debug Output

```
 TestAccAWSDBInstance_CACertificateIdentifier: resource_aws_db_instance_test.go:2982: Step 1/1 error: Error running apply: 2020/10/20 19:40:03 [DEBUG] Using modified User-Agent: Terraform/0.12.29 HashiCorp-terraform-exec/0.10.0
        
        Error: error modifying DB Instance (terraform-20201020194004422400000001): CertificateNotFound: Certificate not found: rds-ca-2019
        	status code: 404, request id: ada72859-7aad-4770-8e5d-2bcf95022114

--- FAIL: TestAccAWSDBInstance_CACertificateIdentifier (438.48s)
```

### References

* #15733
* #15662

### PR DESCRIPTION
**Pull request by YakDriver**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #15662, #15737, #15775
Fixes #15770
Fixes #15772

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Output from acceptance testing (GovCloud) (no regressions, 13 preexisting fails):

```
--- FAIL: TestAccAWSDbInstanceDataSource_ec2Classic (0.00s)                             (************** See 8.)
--- PASS: TestProvider_impl (0.48s)
--- PASS: TestProvider (1.26s)
--- PASS: TestAccAWSProvider_Region_AwsGovCloudUs (34.77s)
--- PASS: TestAccAWSProvider_Region_AwsCommercial (36.27s)
--- PASS: TestAccAWSProvider_Region_AwsChina (38.03s)
--- PASS: TestAccAWSProvider_IgnoreTags_Keys_Multiple (44.48s)
--- PASS: TestAccAWSProvider_IgnoreTags_KeyPrefixes_Multiple (45.18s)
--- PASS: TestAccAWSProvider_IgnoreTags_KeyPrefixes_One (45.61s)
--- PASS: TestAccAWSProvider_IgnoreTags_Keys_One (46.12s)
--- PASS: TestAccAWSProvider_IgnoreTags_KeyPrefixes_None (46.18s)
--- PASS: TestAccAWSProvider_AssumeRole_Empty (46.05s)
--- PASS: TestAccAWSProvider_IgnoreTags_EmptyConfigurationBlock (46.55s)
--- PASS: TestAccAWSProvider_Endpoints (47.59s)
--- PASS: TestAccAWSProvider_IgnoreTags_Keys_None (47.71s)
--- FAIL: TestAccAWSDBInstance_DbSubnetGroupName_RamShared (2.06s)                      (************** See 4.)
--- PASS: TestAccAWSDBInstance_optionGroup (404.18s)
--- PASS: TestAccAWSDBInstance_basic (451.06s)
--- PASS: TestAccAWSDBInstance_namePrefix (469.27s)
--- PASS: TestAccAWSDBInstance_generatedName (455.57s)
--- PASS: TestAccAWSDBInstance_DbSubnetGroupName (466.11s)
--- PASS: TestAccAWSDbInstanceDataSource_basic (524.74s)
--- PASS: TestAccAWSDBInstance_iamAuth (484.25s)
--- PASS: TestAccAWSDBInstance_AllowMajorVersionUpgrade (501.75s)
--- PASS: TestAccAWSDBInstance_IsAlreadyBeingDeleted (506.06s)
--- PASS: TestAccAWSDBInstance_DbSubnetGroupName_VpcSecurityGroupIds (546.38s)
--- PASS: TestAccAWSDBInstance_kmsKey (556.99s)
--- FAIL: TestAccAWSDBInstance_ReplicateSourceDb_DbSubnetGroupName_RamShared (0.39s)    (************** See 4.)
--- FAIL: TestAccAWSDBInstance_ReplicateSourceDb_DbSubnetGroupName (11.71s)             (*********** See 6, 7.)
--- SKIP: TestAccAWSDBInstance_ReplicateSourceDb_DeletionProtection (0.00s)
--- FAIL: TestAccAWSDBInstance_ReplicateSourceDb_DbSubnetGroupName_VpcSecurityGroupIds (11.76s) (*** See 6, 7.)
--- PASS: TestAccAWSDBInstance_DeletionProtection (561.04s)
--- PASS: TestAccAWSDBInstance_FinalSnapshotIdentifier_SkipFinalSnapshot (583.75s)
--- PASS: TestAccAWSDBInstance_FinalSnapshotIdentifier (845.96s)
--- PASS: TestAccAWSDBInstance_Password (487.25s)
--- PASS: TestAccAWSDBInstance_MaxAllocatedStorage (583.25s)
--- PASS: TestAccAWSDBInstance_subnetGroup (1024.31s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb (1332.78s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_AvailabilityZone (1312.25s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_AutoMinorVersionUpgrade (1362.72s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_BackupWindow (1352.11s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_MaintenanceWindow (1322.71s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_AllowMajorVersionUpgrade (1473.76s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_IamDatabaseAuthenticationEnabled (1443.12s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_MaxAllocatedStorage (1463.76s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_BackupRetentionPeriod (1625.18s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_Monitoring (1585.15s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_AllocatedStorage (1767.03s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_ParameterGroupName (1402.62s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_VpcSecurityGroupIds (1332.38s)
--- FAIL: TestAccAWSDBInstance_SnapshotIdentifier_DbSubnetGroupName_RamShared (0.55s)   (************** See 4.)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_Port (1453.40s)
--- FAIL: TestAccAWSDBInstance_S3Import (660.38s)                                       (************** See 5.)
--- FAIL: TestAccAWSDBInstance_ReplicateSourceDb_CACertificateIdentifier (711.06s)      (************** See 2.)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier (1078.66s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_AvailabilityZone (998.15s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_AutoMinorVersionUpgrade (1119.72s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_MultiAZ (2362.14s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_AllocatedStorage (1422.48s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_BackupWindow (1109.44s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_DbSubnetGroupName (1109.73s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_Io1Storage (1613.88s)
--- SKIP: TestAccAWSDBInstance_SnapshotIdentifier_Tags_Unset (0.00s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_BackupRetentionPeriod (1382.55s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_IamDatabaseAuthenticationEnabled (1090.92s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_DbSubnetGroupName_VpcSecurityGroupIds (1201.07s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_DeletionProtection (1169.32s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_MaintenanceWindow (1211.20s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_BackupRetentionPeriod_Unset (1624.23s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_AllowMajorVersionUpgrade (1957.95s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_MaxAllocatedStorage (1160.40s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_Monitoring (1260.76s)
--- PASS: TestAccAWSDBInstance_MonitoringRoleArn_EnabledToDisabled (772.61s)
--- PASS: TestAccAWSDBInstance_MonitoringRoleArn_EnabledToRemoved (813.71s)
--- PASS: TestAccAWSDBInstance_portUpdate (530.06s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_Port (1119.84s)
--- FAIL: TestAccAWSDBInstance_ec2Classic (0.00s)                                       (************** See 8.)
--- PASS: TestAccAWSDBInstance_MonitoringRoleArn_RemovedToEnabled (762.64s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_Tags (1060.32s)
--- PASS: TestAccAWSDBInstance_separateIopsUpdate (794.05s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_ParameterGroupName (1322.79s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_VpcSecurityGroupIds (1110.02s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_VpcSecurityGroupIds_Tags (1099.81s)
--- SKIP: TestAccAWSDBInstance_PerformanceInsightsEnabled_DisabledToEnabled (0.00s)
--- SKIP: TestAccAWSDBInstance_PerformanceInsightsEnabled_EnabledToDisabled (0.00s)
--- SKIP: TestAccAWSDBInstance_PerformanceInsightsKmsKeyId (0.00s)
--- SKIP: TestAccAWSDBInstance_PerformanceInsightsRetentionPeriod (0.00s)
--- SKIP: TestAccAWSDBInstance_ReplicateSourceDb_PerformanceInsightsEnabled (0.00s)
--- SKIP: TestAccAWSDBInstance_SnapshotIdentifier_PerformanceInsightsEnabled (0.00s)
--- PASS: TestAccAWSDBInstance_MonitoringInterval (1181.10s)
--- PASS: TestAccAWSDBOptionGroup_basic (7.81s)
--- PASS: TestAccAWSDBOptionGroup_timeoutBlock (7.75s)
--- PASS: TestAccAWSDBOptionGroup_namePrefix (8.03s)
--- PASS: TestAccAWSDBOptionGroup_generatedName (7.81s)
--- PASS: TestAccAWSDBOptionGroupConfig_OptionGroupDescription (7.54s)
--- PASS: TestAccAWSDBInstance_cloudwatchLogsExportConfiguration (355.58s)
--- PASS: TestAccAWSDBOptionGroup_Option_OptionSettings (14.99s)
--- PASS: TestAccAWSDBOptionGroup_Option_OptionSettings_IAMRole (16.93s)
--- PASS: TestAccAWSDBOptionGroup_sqlServerOptionsUpdate (13.67s)
--- PASS: TestAccAWSDBOptionGroup_OracleOptionsUpdate (40.64s)                          (************** See 3.)
--- PASS: TestAccAWSDBInstance_MinorVersion (422.23s)
--- PASS: TestAccAWSDBOptionGroup_multipleOptions (9.65s)
--- PASS: TestAccAWSDBOptionGroup_Option_OptionSettings_MultipleNonDefault (16.99s)
--- PASS: TestAccAWSDBOptionGroup_Tags (23.14s)
--- PASS: TestAccAWSDBOptionGroup_Tags_WithOptions (23.05s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_MultiAZ (1787.18s)
--- PASS: TestAccAWSDBInstance_CACertificateIdentifier (554.03s)                        (************** See 2.)
--- PASS: TestAccAWSDBInstance_EnabledCloudwatchLogsExports_Postgresql (495.88s)
--- PASS: TestAccAWSDBInstance_EnabledCloudwatchLogsExports_MSSQL (656.02s)
--- PASS: TestAccAWSDBInstance_NoDeleteAutomatedBackups (594.71s)
--- PASS: TestAccAWSDBInstance_EnabledCloudwatchLogsExports_MySQL (770.88s)
--- PASS: TestAccAWSDBInstance_EnabledCloudwatchLogsExports_Oracle (706.67s)
--- PASS: TestAccAWSDBOptionGroup_basicDestroyWithInstance (533.70s)
--- PASS: TestAccAWSDBInstance_MSSQL_TZ (1615.04s)
--- PASS: TestAccAWSDBInstance_MySQL_SnapshotRestoreWithEngineVersion (1766.50s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_MultiAZ_SQLServer (3738.62s)
--- FAIL: TestAccAWSDBInstance_MSSQL_DomainSnapshotRestore (4770.82s)                   (************** See 1.)
--- FAIL: TestAccAWSDBInstance_MSSQL_Domain (4980.84s)                                  (************** See 1.)
```

Output from acceptance testing (commercial) (no regressions, 1 flaky fail, 4 preexisting conditions):

```
--- PASS: TestProvider_impl (0.89s)
--- PASS: TestProvider (1.73s)
--- SKIP: TestAccAWSDbInstanceDataSource_ec2Classic (0.00s)
--- PASS: TestAccAWSProvider_Region_AwsChina (40.77s)
--- PASS: TestAccAWSProvider_Region_AwsGovCloudUs (41.77s)
--- PASS: TestAccAWSProvider_Region_AwsCommercial (41.85s)
--- FAIL: TestAccAWSDBInstance_DbSubnetGroupName_RamShared (2.34s)                      (************** See 4.)
--- PASS: TestAccAWSProvider_IgnoreTags_KeyPrefixes_One (49.12s)
--- PASS: TestAccAWSProvider_IgnoreTags_Keys_Multiple (51.61s)
--- PASS: TestAccAWSProvider_IgnoreTags_Keys_One (52.16s)
--- PASS: TestAccAWSProvider_Endpoints (52.32s)
--- PASS: TestAccAWSProvider_IgnoreTags_KeyPrefixes_None (52.52s)
--- PASS: TestAccAWSProvider_IgnoreTags_EmptyConfigurationBlock (52.75s)
--- PASS: TestAccAWSProvider_IgnoreTags_KeyPrefixes_Multiple (53.16s)
--- PASS: TestAccAWSProvider_IgnoreTags_Keys_None (54.12s)
--- PASS: TestAccAWSProvider_AssumeRole_Empty (57.21s)
--- PASS: TestAccAWSDBInstance_optionGroup (399.17s)
--- PASS: TestAccAWSDBInstance_kmsKey (402.14s)
--- PASS: TestAccAWSDBInstance_iamAuth (450.05s)
--- PASS: TestAccAWSDBInstance_generatedName (460.28s)
--- PASS: TestAccAWSDBInstance_DeletionProtection (431.92s)
--- PASS: TestAccAWSDBInstance_DbSubnetGroupName (454.49s)
--- FAIL: TestAccAWSDBInstance_ReplicateSourceDb_DbSubnetGroupName_RamShared (1.15s)    (************** See 4.)
--- PASS: TestAccAWSDBInstance_namePrefix (498.91s)
--- SKIP: TestAccAWSDBInstance_ReplicateSourceDb_DeletionProtection (0.00s)
--- PASS: TestAccAWSDBInstance_basic (501.81s)
--- PASS: TestAccAWSDBInstance_Password (463.42s)
--- PASS: TestAccAWSDBInstance_FinalSnapshotIdentifier_SkipFinalSnapshot (478.09s)
--- PASS: TestAccAWSDBInstance_DbSubnetGroupName_VpcSecurityGroupIds (502.43s)
--- PASS: TestAccAWSDBInstance_IsAlreadyBeingDeleted (557.76s)
--- PASS: TestAccAWSDBInstance_AllowMajorVersionUpgrade (622.69s)
--- PASS: TestAccAWSDBInstance_MaxAllocatedStorage (643.86s)
--- PASS: TestAccAWSDBInstance_subnetGroup (830.50s)
--- PASS: TestAccAWSDbInstanceDataSource_basic (853.77s)
--- PASS: TestAccAWSDBInstance_FinalSnapshotIdentifier (802.83s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb (1408.33s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_AllowMajorVersionUpgrade (1464.04s)
--- FAIL: TestAccAWSDBInstance_S3Import (724.00s)                                       (************** See 5.)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_AvailabilityZone (1227.38s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_AutoMinorVersionUpgrade (1445.40s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_BackupRetentionPeriod (1449.45s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_MaxAllocatedStorage (1387.07s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_IamDatabaseAuthenticationEnabled (1409.56s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_Monitoring (1418.95s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_Port (1293.02s)
--- FAIL: TestAccAWSDBInstance_SnapshotIdentifier_DbSubnetGroupName_RamShared (1.20s)   (************** See 4.)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_AllocatedStorage (1910.96s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier (1116.56s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_BackupWindow (1529.86s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_VpcSecurityGroupIds (1338.58s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_MaintenanceWindow (1550.73s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_CACertificateIdentifier (1369.73s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_ParameterGroupName (1762.40s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_MultiAZ (1954.61s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_DbSubnetGroupName_VpcSecurityGroupIds (2140.26s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_DbSubnetGroupName (2218.38s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_AutoMinorVersionUpgrade (1176.02s)
--- SKIP: TestAccAWSDBInstance_SnapshotIdentifier_Tags_Unset (0.00s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_AllocatedStorage (1479.96s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_IamDatabaseAuthenticationEnabled (1034.34s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_BackupWindow (1135.84s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_DbSubnetGroupName_VpcSecurityGroupIds (1105.74s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_DbSubnetGroupName (1115.88s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_Io1Storage (1559.96s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_BackupRetentionPeriod (1186.15s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_AvailabilityZone (1287.17s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_MaxAllocatedStorage (1144.67s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_Monitoring (1146.83s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_MaintenanceWindow (1226.45s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_DeletionProtection (1267.59s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_BackupRetentionPeriod_Unset (1528.81s)
--- SKIP: TestAccAWSDBInstance_ec2Classic (0.00s)
--- PASS: TestAccAWSDBInstance_portUpdate (549.77s)
--- PASS: TestAccAWSDBInstance_MonitoringRoleArn_RemovedToEnabled (613.25s)
--- PASS: TestAccAWSDBInstance_MinorVersion (488.76s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_ParameterGroupName (1255.18s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_Port (1144.84s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_AllowMajorVersionUpgrade (2224.43s)
--- PASS: TestAccAWSDBInstance_MonitoringRoleArn_EnabledToRemoved (757.82s)
--- PASS: TestAccAWSDBInstance_MonitoringRoleArn_EnabledToDisabled (777.77s)
--- PASS: TestAccAWSDBInstance_separateIopsUpdate (782.19s)
--- PASS: TestAccAWSDBInstance_MonitoringInterval (933.13s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_Tags (1266.21s)
--- PASS: TestAccAWSDBInstance_cloudwatchLogsExportConfiguration (575.42s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_VpcSecurityGroupIds (1247.73s)
--- PASS: TestAccAWSDBOptionGroup_basic (12.72s)
--- PASS: TestAccAWSDBOptionGroup_timeoutBlock (12.42s)
--- PASS: TestAccAWSDBOptionGroup_namePrefix (12.62s)
--- PASS: TestAccAWSDBOptionGroup_generatedName (13.86s)
--- PASS: TestAccAWSDBOptionGroupConfig_OptionGroupDescription (12.45s)
--- FAIL: TestAccAWSDBInstance_EnabledCloudwatchLogsExports_MySQL (543.23s)             (************** See 7.)
--- PASS: TestAccAWSDBOptionGroup_Option_OptionSettings (24.40s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_MultiAZ (2023.39s)
--- PASS: TestAccAWSDBOptionGroup_Option_OptionSettings_IAMRole (33.44s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_VpcSecurityGroupIds_Tags (1306.24s)
--- PASS: TestAccAWSDBOptionGroup_sqlServerOptionsUpdate (23.31s)
--- PASS: TestAccAWSDBOptionGroup_multipleOptions (15.62s)
--- PASS: TestAccAWSDBOptionGroup_OracleOptionsUpdate (32.48s)                          (************** See 3.)
--- PASS: TestAccAWSDBOptionGroup_Option_OptionSettings_MultipleNonDefault (28.42s)
--- PASS: TestAccAWSDBOptionGroup_Tags (41.22s)
--- PASS: TestAccAWSDBOptionGroup_Tags_WithOptions (41.48s)
--- PASS: TestAccAWSDBInstance_EnabledCloudwatchLogsExports_Postgresql (572.35s)
--- PASS: TestAccAWSDBInstance_CACertificateIdentifier (497.61s)                        (************** See 2.)
--- PASS: TestAccAWSDBInstance_NoDeleteAutomatedBackups (620.06s)
--- PASS: TestAccAWSDBInstance_EnabledCloudwatchLogsExports_MSSQL (813.21s)
--- PASS: TestAccAWSDBInstance_PerformanceInsightsEnabled_DisabledToEnabled (721.34s)
--- PASS: TestAccAWSDBInstance_EnabledCloudwatchLogsExports_Oracle (826.52s)
--- PASS: TestAccAWSDBOptionGroup_basicDestroyWithInstance (558.31s)
--- PASS: TestAccAWSDBInstance_PerformanceInsightsEnabled_EnabledToDisabled (900.09s)
--- PASS: TestAccAWSDBInstance_PerformanceInsightsRetentionPeriod (897.75s)
--- PASS: TestAccAWSDBInstance_MSSQL_TZ (1664.03s)
--- PASS: TestAccAWSDBInstance_PerformanceInsightsKmsKeyId (1091.60s)
--- PASS: TestAccAWSDBInstance_MySQL_SnapshotRestoreWithEngineVersion (1902.27s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_PerformanceInsightsEnabled (1488.92s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_PerformanceInsightsEnabled (1893.37s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_MultiAZ_SQLServer (3831.45s)
--- PASS: TestAccAWSDBInstance_MSSQL_DomainSnapshotRestore (3136.66s)
--- PASS: TestAccAWSDBInstance_MSSQL_Domain (3693.04s)
```

1. (GovCloud only) Preexisting & unrelated, tracked in #15775
2. (GovCloud only) This PR partially fixes (fixed after TC run) (issue #15772) (`TestAccAWSDBInstance_ReplicateSourceDb_CACertificateIdentifier` has new, unrelated issue on GovCloud; no regression in commercial)
3. (GovCloud only) This PR fixes (fixed after TC run) (issue #15770) (no regression in commercial)
4. Preexisting & unrelated, tracked in #15767
5. Preexisting & unrelated, tracked in #13391
6. (GovCloud only) Preexisting & unrelated, tracked in #15777
7. Appears flaky
8. Preexisting & unrelated, tracked in #15737 (see also #8316)

### CODE REVIEW

File: aws/provider_test.go [hunk 1]
```diff
@@ -498,6 +498,14 @@ func testAccGetThirdRegionPartition() string {
...
 }
 
+func testAccRDSCACertificateID() string {
+	v := os.Getenv("AWS_RDS_CA_CERTIFICATE_IDENTIFIER")
+	if v == "" {
+		return "rds-ca-2019"
+	}
+	return v
+}
+
```
Comment (bflad) [inline aws/provider_test.go:508]: Longterm we can consider https://github.com/terraform-providers/terraform-provider-aws/issues/15221 -- maybe I'll just create that right now. Otherwise, we will want to at least ensure this is documented in the Maintaining Guide: https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/MAINTAINING.md#environment-variable-dictionary

Comment (bflad) [reply aws/provider_test.go:508]: Submitted this for now or later: https://github.com/terraform-providers/terraform-provider-aws/pull/15789

File: aws/data_source_aws_db_instance_test.go [hunk 2]
```diff
@@ -42,8 +42,11 @@ func TestAccAWSDbInstanceDataSource_basic(t *testing.T) {
 }
 
 func TestAccAWSDbInstanceDataSource_ec2Classic(t *testing.T) {
+	hardcodedRegion := "us-east-1" // lintignore:AWSAT003
+	testAccReachableRegionPreCheck(hardcodedRegion, t)
+
 	oldvar := os.Getenv("AWS_DEFAULT_REGION")
-	os.Setenv("AWS_DEFAULT_REGION", "us-east-1")
+	os.Setenv("AWS_DEFAULT_REGION", hardcodedRegion)
 	defer os.Setenv("AWS_DEFAULT_REGION", oldvar)
```
Comment (gdavison) [inline aws/data_source_aws_db_instance_test.go:50]: `us-east-1` is not the only region that supports EC2-Classic, and it is even supported in GovCloud. I've written up #15791, which could be used here and in other EC2-Classic-related tests

File: aws/provider_test.go (hunk 1 above)
Comment (YakDriver) [reply aws/provider_test.go]: Done!

File: aws/data_source_aws_db_instance_test.go (hunk 2 above)
Comment (YakDriver) [reply aws/data_source_aws_db_instance_test.go]: Deferring for another PR

**Comment by YakDriver** [comment]
Commercial:
```
--- PASS: TestAccAWSDBInstance_CACertificateIdentifier (441.12s)
--- PASS: TestAccAWSRDSClusterInstance_CACertificateIdentifier (483.88s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_CACertificateIdentifier (1533.86s)
```

File: aws/resource_aws_db_instance.go [hunk 3]
```diff
@@ -38,7 +38,7 @@ func resourceAwsDbInstance() *schema.Resource {
 		Timeouts: &schema.ResourceTimeout{
 			Create: schema.DefaultTimeout(40 * time.Minute),
 			Update: schema.DefaultTimeout(80 * time.Minute),
-			Delete: schema.DefaultTimeout(40 * time.Minute),
+			Delete: schema.DefaultTimeout(60 * time.Minute),
```
Comment (bflad) [inline aws/resource_aws_db_instance.go:41]: Please note that the timeouts documentation needs to be updated in `website/docs/r/db_instance.html.markdown` for this change. 👍  Running acceptance testing now.

Comment (YakDriver) [reply aws/resource_aws_db_instance.go:41]: Fixed

**Review by bflad — APPROVED** [review]
Looks good 🚀 

Output from acceptance testing in AWS Commercial:

```
--- PASS: TestAccAWSDBInstance_CACertificateIdentifier (459.03s)
--- PASS: TestAccAWSDBInstance_MonitoringInterval (1075.27s)
--- PASS: TestAccAWSDBInstance_MonitoringRoleArn_EnabledToDisabled (775.98s)
--- PASS: TestAccAWSDBInstance_MonitoringRoleArn_EnabledToRemoved (787.71s)
--- PASS: TestAccAWSDBInstance_MonitoringRoleArn_RemovedToEnabled (513.43s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_CACertificateIdentifier (1451.98s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_Monitoring (1461.24s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_Monitoring (1398.57s)

--- PASS: TestAccAWSDBOptionGroup_basic (50.56s)
--- PASS: TestAccAWSDBOptionGroup_basicDestroyWithInstance (586.37s)
--- PASS: TestAccAWSDBOptionGroup_generatedName (48.22s)
--- PASS: TestAccAWSDBOptionGroup_multipleOptions (47.64s)
--- PASS: TestAccAWSDBOptionGroup_namePrefix (50.90s)
--- PASS: TestAccAWSDBOptionGroup_Option_OptionSettings (73.19s)
--- PASS: TestAccAWSDBOptionGroup_Option_OptionSettings_IAMRole (65.71s)
--- PASS: TestAccAWSDBOptionGroup_Option_OptionSettings_MultipleNonDefault (72.71s)
--- PASS: TestAccAWSDBOptionGroup_OracleOptionsUpdate (72.68s)
--- PASS: TestAccAWSDBOptionGroup_sqlServerOptionsUpdate (70.31s)
--- PASS: TestAccAWSDBOptionGroup_Tags (45.41s)
--- PASS: TestAccAWSDBOptionGroup_Tags_WithOptions (45.18s)
--- PASS: TestAccAWSDBOptionGroup_timeoutBlock (49.17s)

--- PASS: TestAccAWSRDSClusterInstance_CACertificateIdentifier (617.30s)
```

Output from acceptance testing in AWS GovCloud (US):

```
--- PASS: TestAccAWSDBInstance_CACertificateIdentifier (534.04s)
--- PASS: TestAccAWSDBInstance_MonitoringInterval (1208.86s)
--- PASS: TestAccAWSDBInstance_MonitoringRoleArn_EnabledToDisabled (807.63s)
--- PASS: TestAccAWSDBInstance_MonitoringRoleArn_EnabledToRemoved (808.37s)
--- PASS: TestAccAWSDBInstance_MonitoringRoleArn_RemovedToEnabled (711.45s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_CACertificateIdentifier (1517.33s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_Monitoring (1579.70s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_Monitoring (1331.32s)

--- PASS: TestAccAWSDBOptionGroup_basic (26.82s)
--- PASS: TestAccAWSDBOptionGroup_basicDestroyWithInstance (536.04s)
--- PASS: TestAccAWSDBOptionGroup_generatedName (26.55s)
--- PASS: TestAccAWSDBOptionGroup_multipleOptions (23.07s)
--- PASS: TestAccAWSDBOptionGroup_namePrefix (26.60s)
--- PASS: TestAccAWSDBOptionGroup_Option_OptionSettings (47.33s)
--- PASS: TestAccAWSDBOptionGroup_Option_OptionSettings_IAMRole (38.00s)
--- PASS: TestAccAWSDBOptionGroup_Option_OptionSettings_MultipleNonDefault (44.27s)
--- PASS: TestAccAWSDBOptionGroup_OracleOptionsUpdate (48.95s)
--- PASS: TestAccAWSDBOptionGroup_sqlServerOptionsUpdate (43.52s)
--- PASS: TestAccAWSDBOptionGroup_Tags (59.45s)
--- PASS: TestAccAWSDBOptionGroup_Tags_WithOptions (59.94s)
--- PASS: TestAccAWSDBOptionGroup_timeoutBlock (26.70s)

--- PASS: TestAccAWSRDSClusterInstance_CACertificateIdentifier (727.13s)
```
