### PR TITLE
Fix for ebs_block_devices disappearing in data source, and fix instan…

### LINKED ISSUE #7198: Data sources don't return more than one TypeSet's
### Terraform Version

0.11.11

### Affected Resource(s)

* aws_instance data source
* aws_launch_configuration data source

### Terraform Configuration Files

```hcl
data "aws_ami" "ubuntu" {
  most_recent = true

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["099720109477"] # Canonical
}

resource "aws_instance" "test" {
  ami           = "${data.aws_ami.ubuntu.id}"
  instance_type = "t2.micro"

  tags = {
    Name = "kshcherban-test"
  }

  ebs_block_device {
     device_name = "/dev/sdf"
     volume_size = 10
   }
   ebs_block_device {
     device_name = "/dev/sdg"
     volume_size = 20
     volume_type = "gp2"
   }
}

data "aws_instance" "test" {
  instance_id = "${aws_instance.test.id}"
}

output "instance" {
  value = "${aws_instance.test.ebs_block_device}"
}

output "data" {
  value = "${data.aws_instance.test.ebs_block_device}"
}
```

### Debug Output

```
Outputs:

data = [
    {
        delete_on_termination = 1,
        device_name = /dev/sdg,
        encrypted = 0,
        iops = 100,
        snapshot_id = ,
        volume_id = vol-014032926148b41b2,
        volume_size = 20,
        volume_type = gp2
    }
]

instance = [
    {
        delete_on_termination = 1,
        device_name = /dev/sdf,
        encrypted = 0,
        iops = 0,
        snapshot_id = ,
        volume_id = vol-061fe03c49cda6742,
        volume_size = 10,
        volume_type = standard
    },
    {
        delete_on_termination = 1,
        device_name = /dev/sdg,
        encrypted = 0,
        iops = 100,
        snapshot_id = ,
        volume_id = vol-014032926148b41b2,
        volume_size = 20,
        volume_type = gp2
    }
]
```

### Expected Behavior

data source should return the same amount of block devices

### Actual Behavior

data source returns only one device of two

### Important Factoids

Test are written incorrectly:

* https://github.com/terraform-providers/terraform-provider-aws/blob/3f3977866dc3c682fbf8bb584d5263849e00135f/aws/data_source_aws_launch_configuration_test.go#L27 - `ebs_block_device.#` must be `2`
* https://github.com/terraform-providers/terraform-provider-aws/blob/3f3977866dc3c682fbf8bb584d5263849e00135f/aws/data_source_aws_instance_test.go#L101 - data source should be checked, not the resource.

There are only two cases found. I assume there are more, and this pattern should be revised for other data sources or resources.

### PR DESCRIPTION
**Pull request by ryndaniels**
…ce data source tests

Note that this is in addition to the [upstream fix](https://github.com/hashicorp/terraform/pull/22719). 

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #7198

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
BUG FIXES:
* data_source/aws_instance: Fixes a bug where multiple EBS volumes would get collapsed and only one would return
```

Output from acceptance testing:

```
$ make testacc TESTARGS="-run=TestAccAWSInstanceDataSource_"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSInstanceDataSource_ -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSInstanceDataSource_basic
=== PAUSE TestAccAWSInstanceDataSource_basic
=== RUN   TestAccAWSInstanceDataSource_tags
=== PAUSE TestAccAWSInstanceDataSource_tags
=== RUN   TestAccAWSInstanceDataSource_AzUserData
=== PAUSE TestAccAWSInstanceDataSource_AzUserData
=== RUN   TestAccAWSInstanceDataSource_gp2IopsDevice
=== PAUSE TestAccAWSInstanceDataSource_gp2IopsDevice
=== RUN   TestAccAWSInstanceDataSource_blockDevices
=== PAUSE TestAccAWSInstanceDataSource_blockDevices
=== RUN   TestAccAWSInstanceDataSource_rootInstanceStore
=== PAUSE TestAccAWSInstanceDataSource_rootInstanceStore
=== RUN   TestAccAWSInstanceDataSource_getPasswordData_trueToFalse
=== PAUSE TestAccAWSInstanceDataSource_getPasswordData_trueToFalse
=== RUN   TestAccAWSInstanceDataSource_getPasswordData_falseToTrue
=== PAUSE TestAccAWSInstanceDataSource_getPasswordData_falseToTrue
=== RUN   TestAccAWSInstanceDataSource_GetUserData
=== PAUSE TestAccAWSInstanceDataSource_GetUserData
=== CONT  TestAccAWSInstanceDataSource_basic
=== CONT  TestAccAWSInstanceDataSource_tags
=== CONT  TestAccAWSInstanceDataSource_gp2IopsDevice
=== CONT  TestAccAWSInstanceDataSource_GetUserData
=== CONT  TestAccAWSInstanceDataSource_getPasswordData_falseToTrue
=== CONT  TestAccAWSInstanceDataSource_getPasswordData_trueToFalse
=== CONT  TestAccAWSInstanceDataSource_rootInstanceStore
=== CONT  TestAccAWSInstanceDataSource_AzUserData
=== CONT  TestAccAWSInstanceDataSource_blockDevices

--- PASS: TestAccAWSInstanceDataSource_gp2IopsDevice (115.32s)
--- PASS: TestAccAWSInstanceDataSource_rootInstanceStore (116.65s)
--- PASS: TestAccAWSInstanceDataSource_blockDevices (138.49s)
--- PASS: TestAccAWSInstanceDataSource_tags (148.29s)
--- PASS: TestAccAWSInstanceDataSource_AzUserData (160.36s)
--- PASS: TestAccAWSInstanceDataSource_getPasswordData_falseToTrue (195.22s)
--- PASS: TestAccAWSInstanceDataSource_getPasswordData_trueToFalse (222.29s)
--- PASS: TestAccAWSInstanceDataSource_basic (237.58s)
--- PASS: TestAccAWSInstanceDataSource_GetUserData (273.19s)


make testacc TESTARGS="-run=TestAccAWSInstanceDataSource_EbsBlockDevice_KmsKeyId"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSInstanceDataSource_EbsBlockDevice_KmsKeyId -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSInstanceDataSource_EbsBlockDevice_KmsKeyId
=== PAUSE TestAccAWSInstanceDataSource_EbsBlockDevice_KmsKeyId
=== CONT  TestAccAWSInstanceDataSource_EbsBlockDevice_KmsKeyId
--- PASS: TestAccAWSInstanceDataSource_EbsBlockDevice_KmsKeyId (149.66s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       150.558s

make testacc TESTARGS="-run=TestAccAWSInstanceDataSource_RootBlockDevice_KmsKeyId"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSInstanceDataSource_RootBlockDevice_KmsKeyId -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSInstanceDataSource_RootBlockDevice_KmsKeyId
=== PAUSE TestAccAWSInstanceDataSource_RootBlockDevice_KmsKeyId
=== CONT  TestAccAWSInstanceDataSource_RootBlockDevice_KmsKeyId
--- PASS: TestAccAWSInstanceDataSource_RootBlockDevice_KmsKeyId (161.15s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       162.033s

make testacc TESTARGS="-run=TestAccAWSInstanceDataSource_GetUserData_NoUserData"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSInstanceDataSource_GetUserData_NoUserData -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSInstanceDataSource_GetUserData_NoUserData
=== PAUSE TestAccAWSInstanceDataSource_GetUserData_NoUserData
=== CONT  TestAccAWSInstanceDataSource_GetUserData_NoUserData
--- PASS: TestAccAWSInstanceDataSource_GetUserData_NoUserData (248.82s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       249.792s

make testacc TESTARGS="-run=TestAccAWSInstanceDataSource_PlacementGroup"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSInstanceDataSource_PlacementGroup -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSInstanceDataSource_PlacementGroup
=== PAUSE TestAccAWSInstanceDataSource_PlacementGroup
=== CONT  TestAccAWSInstanceDataSource_PlacementGroup
--- PASS: TestAccAWSInstanceDataSource_PlacementGroup (142.39s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       143.360s

make testacc TESTARGS="-run=TestAccAWSInstanceDataSource_VPC"==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSInstanceDataSource_VPC -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSInstanceDataSource_VPC
=== PAUSE TestAccAWSInstanceDataSource_VPC
=== RUN   TestAccAWSInstanceDataSource_VPCSecurityGroups
=== PAUSE TestAccAWSInstanceDataSource_VPCSecurityGroups
=== CONT  TestAccAWSInstanceDataSource_VPC
=== CONT  TestAccAWSInstanceDataSource_VPCSecurityGroups
--- PASS: TestAccAWSInstanceDataSource_VPCSecurityGroups (143.59s)
--- PASS: TestAccAWSInstanceDataSource_VPC (146.47s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       147.350s

make testacc TESTARGS="-run=TestAccAWSInstanceDataSource_privateIP"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSInstanceDataSource_privateIP -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSInstanceDataSource_privateIP
=== PAUSE TestAccAWSInstanceDataSource_privateIP
=== CONT  TestAccAWSInstanceDataSource_privateIP
--- PASS: TestAccAWSInstanceDataSource_privateIP (146.75s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       147.850s

make testacc TESTARGS="-run=TestAccAWSInstanceDataSource_creditSpecification"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSInstanceDataSource_creditSpecification -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSInstanceDataSource_creditSpecification
=== PAUSE TestAccAWSInstanceDataSource_creditSpecification
=== CONT  TestAccAWSInstanceDataSource_creditSpecification
--- PASS: TestAccAWSInstanceDataSource_creditSpecification (154.20s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       155.101s

make testacc TESTARGS="-run=TestAccAWSInstanceDataSource_SecurityGroups"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSInstanceDataSource_SecurityGroups -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSInstanceDataSource_SecurityGroups
=== PAUSE TestAccAWSInstanceDataSource_SecurityGroups
=== CONT  TestAccAWSInstanceDataSource_SecurityGroups
--- PASS: TestAccAWSInstanceDataSource_SecurityGroups (136.43s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       137.346s

make testacc TESTARGS="-run=TestAccAWSInstanceDataSource_keyPair"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSInstanceDataSource_keyPair -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSInstanceDataSource_keyPair
=== PAUSE TestAccAWSInstanceDataSource_keyPair
=== CONT  TestAccAWSInstanceDataSource_keyPair
--- PASS: TestAccAWSInstanceDataSource_keyPair (103.46s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       104.426s
```

### CODE REVIEW

File: aws/data_source_aws_instance_test.go [hunk 1]
```diff
@@ -841,7 +885,7 @@ data "aws_ami" "amzn-ami-minimal-hvm-ebs" {
 
 resource "aws_vpc" "test" {
   cidr_block = "172.16.0.0/16"
-
+
```
Comment (aeschright) [inline aws/data_source_aws_instance_test.go]: Looks like some whitespace got added here and below on 897, 941, 950
