### PR TITLE
resource/aws_route53_record: Suppress uppercase alias name diff

### LINKED ISSUE #361: route 53 changes detected even though there are no changes
_This issue was originally opened by @tomstachura as hashicorp/terraform#10007. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

I submitted a similar problem report with the previous version and I think some of it was supposed to be solved, but I am still getting the following differences with the 7.7.10 version. 

The environment has just been created with apply and a plan has been run right after. It should be showing no changes, but it shows all the following:

```
~ module.tst1.aws_route53_record.r53_record
    alias.2190465367.evaluate_target_health: "true" => "false"
    alias.2190465367.name:                   "prod-web-1529429951.us-west-2.elb.amazonaws.com" => ""
    alias.2190465367.zone_id:                "Z1H1FL5HABSF5" => ""
    alias.2700809793.evaluate_target_health: "" => "true"
    alias.2700809793.name:                   "" => "PROD-WEB-1529429951.us-west-2.elb.amazonaws.com"
    alias.2700809793.zone_id:                "" => "Z1H1FL5HABSF5"

~ module.tst1.aws_security_group.admin
    ingress.#:                            "3" => "1"
    ingress.1938540428.cidr_blocks.#:     "1" => "0"
    ingress.1938540428.cidr_blocks.0:     "199.58.192.98/32" => ""
    ingress.1938540428.from_port:         "8091" => "0"
    ingress.1938540428.protocol:          "tcp" => ""
    ingress.1938540428.security_groups.#: "0" => "0"
    ingress.1938540428.self:              "false" => "false"
    ingress.1938540428.to_port:           "8091" => "0"
    ingress.3897505941.cidr_blocks.#:     "3" => "0"
    ingress.3897505941.cidr_blocks.0:     "199.58.192.98/32" => ""
    ingress.3897505941.cidr_blocks.1:     "35.160.166.68/32" => ""
    ingress.3897505941.cidr_blocks.2:     "35.161.227.236/32" => ""
    ingress.3897505941.from_port:         "22" => "0"
    ingress.3897505941.protocol:          "tcp" => ""
    ingress.3897505941.security_groups.#: "0" => "0"
    ingress.3897505941.self:              "false" => "false"
    ingress.3897505941.to_port:           "22" => "0"
    ingress.4282511762.cidr_blocks.#:     "1" => "1"
    ingress.4282511762.cidr_blocks.0:     "10.5.101.236/32" => "10.5.101.236/32"
    ingress.4282511762.from_port:         "22" => "22"
    ingress.4282511762.protocol:          "tcp" => "tcp"
    ingress.4282511762.security_groups.#: "0" => "0"
    ingress.4282511762.self:              "false" => "false"
    ingress.4282511762.to_port:           "22" => "22"

~ module.tst1.lb_id.aws_route53_record.r53_record
    alias.1412314257.evaluate_target_health: "true" => "false"
    alias.1412314257.name:                   "prod-id-1538439218.us-west-2.elb.amazonaws.com" => ""
    alias.1412314257.zone_id:                "Z1H1FL5HABSF5" => ""
    alias.1713183629.evaluate_target_health: "" => "true"
    alias.1713183629.name:                   "" => "PROD-ID-1538439218.us-west-2.elb.amazonaws.com"
    alias.1713183629.zone_id:                "" => "Z1H1FL5HABSF5"

~ module.tst1.lb_solr.aws_route53_record.r53_record
    alias.1351171064.evaluate_target_health: "" => "true"
    alias.1351171064.name:                   "" => "internal-PROD-SOLR-236462827.us-west-2.elb.amazonaws.com"
    alias.1351171064.zone_id:                "" => "Z1H1FL5HABSF5"
    alias.907506756.evaluate_target_health:  "true" => "false"
    alias.907506756.name:                    "internal-prod-solr-236462827.us-west-2.elb.amazonaws.com" => ""
    alias.907506756.zone_id:                 "Z1H1FL5HABSF5" => ""

~ module.tst1.lb_ui.aws_route53_record.r53_record
    alias.2037855967.evaluate_target_health: "" => "true"
    alias.2037855967.name:                   "" => "PROD-UI-85055216.us-west-2.elb.amazonaws.com"
    alias.2037855967.zone_id:                "" => "Z1H1FL5HABSF5"
    alias.884876570.evaluate_target_health:  "true" => "false"
    alias.884876570.name:                    "prod-ui-85055216.us-west-2.elb.amazonaws.com" => ""
    alias.884876570.zone_id:                 "Z1H1FL5HABSF5" => ""

~ module.tst1.lb_web.aws_route53_record.r53_record
    alias.2190465367.evaluate_target_health: "true" => "false"
    alias.2190465367.name:                   "prod-web-1529429951.us-west-2.elb.amazonaws.com" => ""
    alias.2190465367.zone_id:                "Z1H1FL5HABSF5" => ""
    alias.2700809793.evaluate_target_health: "" => "true"
    alias.2700809793.name:                   "" => "PROD-WEB-1529429951.us-west-2.elb.amazonaws.com"
    alias.2700809793.zone_id:                "" => "Z1H1FL5HABSF5"
```

### LINKED ISSUE #439: Unstable plan when combining aws_route53_record, data.aws_alb, and aws_elastic_beanstalk_environment
_This issue was originally opened by @jffry as hashicorp/terraform#10869. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

Application load balancers created by Elastic Beanstalk have uppercase letters in their `dns_name` property (at least they do when referenced via `data.aws_alb`). When trying to point an `aws_route53_record` alias to that load balancer, Terraform ends up with an unstable plan that always has changes left after any number of invocations of `terraform apply`.

Repro and workaround included below.

### Terraform Version
Terraform `v0.8.1`

### Affected Resource(s)
Please list the resources as a list, for example:
- `aws_route53_record`
- `aws_elastic_beanstalk_environment`
- `data.aws_alb`

### Terraform Configuration Files
The following Terraform config should be sufficient to reproduce the behavior:

```hcl
#most of this is fluff to set up a Beanstalk Environment
#the real "problem" starts with line 61 (data.aws_alb.ref)
provider "aws" {
  region = "us-east-1"
}

#creates a service role for Beanstalk
data "aws_iam_policy_document" "beanstalk_can_AssumeRole" {
  statement {
    effect = "Allow"
    actions = ["sts:AssumeRole"]
    principals = {
      type = "Service"
      identifiers = ["elasticbeanstalk.amazonaws.com"]
    }
  }
}
resource "aws_iam_role" "service_role" {
  name = "service-role"
  assume_role_policy = "${data.aws_iam_policy_document.beanstalk_can_AssumeRole.json}"
}
resource "aws_iam_role_policy_attachment" "service1" {
  role = "${aws_iam_role.service_role.name}"
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkService"
}
resource "aws_iam_role_policy_attachment" "service2" {
  role = "${aws_iam_role.service_role.name}"
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkEnhancedHealth"
}

#creates a load-balanced beanstalk application
resource "aws_elastic_beanstalk_application" "main" {
  name = "test-app"
}
resource "aws_elastic_beanstalk_environment" "main" {
  application = "${aws_elastic_beanstalk_application.main.name}"
  name = "test-env"
  tier = "WebServer"
  solution_stack_name = "64bit Amazon Linux 2016.09 v2.4.0 running Tomcat 8 Java 8"
  #get yourself an application load balanced environment
  setting {
    namespace = "aws:elasticbeanstalk:environment"
    name = "EnvironmentType"
    value = "LoadBalanced"
  }
  setting {
    namespace = "aws:elasticbeanstalk:environment"
    name = "LoadBalancerType"
    value = "application"
  }
  setting {
    #Service role is required for application load balancer type enabled environments.
    namespace = "aws:elasticbeanstalk:environment"
    name = "ServiceRole"
    value = "${aws_iam_role.service_role.name}"
  }
}

#point a Route53 record at our Beanstalk environment's load balancer
data "aws_alb" "ref" {
  arn = "${aws_elastic_beanstalk_environment.main.load_balancers[0]}"
}
resource "aws_route53_zone" "main" {
  name = "terraform-bug-reports.com"
}
resource "aws_route53_record" "unstable" {
  zone_id = "${aws_route53_zone.main.zone_id}"
  type = "A"
  name = "unstable"
  alias {
    name = "${data.aws_alb.ref.dns_name}"
    zone_id = "${data.aws_alb.ref.zone_id}"
    evaluate_target_health = false
  }
}
```

### Expected Behavior
After running `terraform apply`, Terraform will no longer have any changes reflected by `terraform plan`

### Actual Behavior
`terraform refresh`/`terraform plan` yields a plan that will never be stably applicable, because round-tripping the value through AWS API calls winds up returning a lowercased value instead, leading to an unstable plan:

```console
$ terraform plan
Refreshing Terraform state
...

~ aws_route53_record.unstable
    alias.1234554321.evaluate_target_health: "false" => "false"
    alias.1234554321.name:                   "awseb-awseb-1aa1aaaaaa11a-123456789.us-east-1.elb.amazonaws.com" => ""
    alias.1234554321.zone_id:                "XYZ1234XYZ1234" => ""
    alias.9987667899.evaluate_target_health:   "" => "false"
    alias.9987667899.name:                     "" => "awseb-AWSEB-1AA1AAAAAA11A-123456789.us-east-1.elb.amazonaws.com"
    alias.9987667899.zone_id:                  "" => "XYZ1234XYZ1234"
```

### Steps to Reproduce
To reproduce, apply the included HCL (above) and then ask Terraform to run a plan.

1. `terraform apply` - will probably take ~10 minutes
2. `terraform plan` - notice that there's changes to `aws_route53_record.unstable`
3. `terraform apply`
4. `terraform plan` - notice that there's _still_ changes to `aws_route53_record.unstable`
5. `terraform refresh` - maybe this will fix it?
6. `terraform plan` - nope, it didn't fix it

It appears that the `alias` values for `aws_route53_record` get flattened into lowercase by AWS, but the `dns_name` value for application load balancers created via Elastic Beanstalk are not always lowercase, which means this scenario leads to an unstable plan.

I tried creating a simpler case to reproduce - where I simply created an `aws_alb` resource, or referred to an existing one via `data.aws_alb`, but in both of those cases the `dns_name` properties were all lowercase letters and didn't yield this problem.

### Workaround
In the above sample, simply lowercase `data.aws_alb.ref.dns_name` where it gets passed into the `alias` block of `aws_route53_record` - e.g. `name = "${lower(data.aws_alb.ref.dns_name)}"`

### LINKED ISSUE #1005: route53_record alias keeps being recreated when elb dns_name is not entirely lowercase
### Terraform Version
v0.9.8

### Affected Resource(s)
- aws_route53_record
- aws_elb.

### Terraform Configuration Files
```hcl
resource "aws_route53_zone" "internal" {
  name = "elbtest.deleteme"
}

resource "aws_elb" "lb" {

  availability_zones=["eu-west-1a"]
  name = "Test"

  "listener" {
    instance_port = 80
    instance_protocol = "HTTP"
    lb_port = 80
    lb_protocol = "HTTP"
  }
}

// Attach the ELB to domain
resource "aws_route53_record" "elb" {
  name = "test.elbtest.deleteme"
  type = "A"
  zone_id = "${aws_route53_zone.internal.zone_id}"
  alias {
    evaluate_target_health = true
    name = "${aws_elb.lb.dns_name}"
    zone_id = "${aws_elb.lb.zone_id}"
  }
}
```

### Expected Behavior
The alias shouldn't be changed since nothing really changed

### Actual Behavior
The record gets replaced every time

### PR DESCRIPTION
**Pull request by bflad**
Closes #361
Closes #439 
Closes #1005 

Uppercase ALB/ELB names generate an uppercase `dns_name` attribute from AWS which is subsequently saved into Terraform. When these are used for alias Route53 records, Route53 normalizes these to lowercase and only returns the lowercase value.  Most folks have used the workaround (myself included) of using `name = "${lower(aws_elb.X.dns_name)}"`.

I do not believe a state migration should be necessary for this change since uppercase name would have always generated the perpetual diff with the hash and name attribute itself.

Previously:
```
=== RUN   TestAccAWSRoute53Record_aliasUppercase
--- FAIL: TestAccAWSRoute53Record_aliasUppercase (234.96s)
	testing.go:513: Step 0 error: After applying this step, the plan was not empty:

		DIFF:

		UPDATE: aws_route53_record.alias
		  alias.1754141646.evaluate_target_health: "true" => "false"
		  alias.1754141646.name:                   "foobar-terraform-elb-1n1r4g62w0-123456789012.us-west-2.elb.amazonaws.com" => ""
		  alias.1754141646.zone_id:                "ZONEID" => ""
		  alias.561810618.evaluate_target_health:  "" => "true"
		  alias.561810618.name:                    "" => "FOOBAR-TERRAFORM-ELB-1n1r4g62w0-123456789012.us-west-2.elb.amazonaws.com"
		  alias.561810618.zone_id:                 "" => "ZONEID"
```

Passes local testing for me:
```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSRoute53Record'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSRoute53Record -timeout 120m
=== RUN   TestAccAWSRoute53Record_basic
--- PASS: TestAccAWSRoute53Record_basic (146.94s)
=== RUN   TestAccAWSRoute53Record_basic_fqdn
--- PASS: TestAccAWSRoute53Record_basic_fqdn (142.64s)
=== RUN   TestAccAWSRoute53Record_txtSupport
--- PASS: TestAccAWSRoute53Record_txtSupport (146.45s)
=== RUN   TestAccAWSRoute53Record_spfSupport
--- PASS: TestAccAWSRoute53Record_spfSupport (131.89s)
=== RUN   TestAccAWSRoute53Record_caaSupport
--- PASS: TestAccAWSRoute53Record_caaSupport (157.52s)
=== RUN   TestAccAWSRoute53Record_generatesSuffix
--- PASS: TestAccAWSRoute53Record_generatesSuffix (148.82s)
=== RUN   TestAccAWSRoute53Record_wildcard
--- PASS: TestAccAWSRoute53Record_wildcard (192.87s)
=== RUN   TestAccAWSRoute53Record_failover
--- PASS: TestAccAWSRoute53Record_failover (137.64s)
=== RUN   TestAccAWSRoute53Record_weighted_basic
--- PASS: TestAccAWSRoute53Record_weighted_basic (138.17s)
=== RUN   TestAccAWSRoute53Record_alias
--- PASS: TestAccAWSRoute53Record_alias (170.03s)
=== RUN   TestAccAWSRoute53Record_aliasUppercase
--- PASS: TestAccAWSRoute53Record_aliasUppercase (210.80s)
=== RUN   TestAccAWSRoute53Record_s3_alias
--- PASS: TestAccAWSRoute53Record_s3_alias (159.76s)
=== RUN   TestAccAWSRoute53Record_weighted_alias
--- PASS: TestAccAWSRoute53Record_weighted_alias (296.04s)
=== RUN   TestAccAWSRoute53Record_geolocation_basic
--- PASS: TestAccAWSRoute53Record_geolocation_basic (153.61s)
=== RUN   TestAccAWSRoute53Record_latency_basic
--- PASS: TestAccAWSRoute53Record_latency_basic (150.90s)
=== RUN   TestAccAWSRoute53Record_TypeChange
--- PASS: TestAccAWSRoute53Record_TypeChange (168.72s)
=== RUN   TestAccAWSRoute53Record_SetIdentiferChange
--- PASS: TestAccAWSRoute53Record_SetIdentiferChange (250.73s)
=== RUN   TestAccAWSRoute53Record_AliasChange
--- PASS: TestAccAWSRoute53Record_AliasChange (263.28s)
=== RUN   TestAccAWSRoute53Record_empty
--- PASS: TestAccAWSRoute53Record_empty (177.55s)
=== RUN   TestAccAWSRoute53Record_longTXTrecord
--- PASS: TestAccAWSRoute53Record_longTXTrecord (197.82s)
=== RUN   TestAccAWSRoute53Record_multivalue_answer_basic
--- PASS: TestAccAWSRoute53Record_multivalue_answer_basic (209.47s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	3751.723s
```

### CODE REVIEW

File: aws/resource_aws_route53_record.go [hunk 1]
```diff
@@ -101,6 +101,12 @@ func resourceAwsRoute53Record() *schema.Resource {
 							Type:      schema.TypeString,
 							Required:  true,
 							StateFunc: normalizeAwsAliasName,
+							DiffSuppressFunc: func(k, old, new string, d *schema.ResourceData) bool {
+								if strings.ToLower(old) == strings.ToLower(new) {
+									return true
+								}
+								return false
```
Comment (radeksimko) [inline aws/resource_aws_route53_record.go]: The whole function can be reduced to a single line:

```go
return strings.ToLower(old) == strings.ToLower(new)
```

😉

File: aws/resource_aws_route53_record_test.go [hunk 2]
```diff
@@ -968,6 +1005,36 @@ resource "aws_elb" "main" {
 }
 `
 
+const testAccRoute53ElbAliasRecordUppercase = `
+resource "aws_route53_zone" "main" {
+  name = "notexample.com"
```
Comment (radeksimko) [inline aws/resource_aws_route53_record_test.go]: I know other zones are static (so far), but can you randomize the name here, please? We can address others in a separate PR in the future.

File: aws/resource_aws_route53_record.go (hunk 1 above)
Comment (bflad) [reply aws/resource_aws_route53_record.go]: 💯  good catch

File: aws/resource_aws_route53_record_test.go (hunk 2 above)
Comment (bflad) [reply aws/resource_aws_route53_record_test.go]: You got it

Comment (bflad) [reply aws/resource_aws_route53_record_test.go]: Ha! You'll love this. We actually hardcode it in the exists/destroy functions too: https://github.com/terraform-providers/terraform-provider-aws/blob/b-aws_route53_record-alias-name-diffsuppressfunc/aws/resource_aws_route53_record_test.go#L586

Its all or nothing 👎  -- I will get that nitpick merged though 👍

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.8.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#180-january-29-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
