### PR TITLE
Error when data.aws_ecr_repository cannot find repository

### LINKED ISSUE #10071: No exception is thrown for non-existent AWS ECR data resources
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.8
+ provider.aws v2.27.0

### Affected Resource(s)

* aws_ecr

### Terraform Configuration Files

```hcl
data "aws_ecr_repository" "repository" {
  name = "services/x"
}

output "x" {
value = data.aws_ecr_repository.repository
}
```

### Expected Behavior
Terraform should have raised the error that ecr repository is not found, like it does in case of *aws_instance* and *aws_db_instance* data sources.

### Actual Behavior
Terraform does not produce error and produces following output:
```
Outputs:

x = {}
```

### Steps to Reproduce

1. `terraform apply`

### PR DESCRIPTION
**Pull request by tomelliff**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #10071

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note

```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSEcrDataSource_ecrRepository'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -count 1 -parallel 20 -run=TestAccAWSEcrDataSource_ecrRepository -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSEcrDataSource_ecrRepository
=== PAUSE TestAccAWSEcrDataSource_ecrRepository
=== CONT  TestAccAWSEcrDataSource_ecrRepository
--- PASS: TestAccAWSEcrDataSource_ecrRepository (40.51s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	40.535s
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/flatmap	0.087s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags	0.012s [no tests to run]
```

### CODE REVIEW

File: aws/data_source_aws_ecr_repository.go [hunk 1]
```diff
@@ -45,11 +45,6 @@ func dataSourceAwsEcrRepositoryRead(d *schema.ResourceData, meta interface{}) er
 	log.Printf("[DEBUG] Reading ECR repository: %s", params)
 	out, err := conn.DescribeRepositories(params)
 	if err != nil {
-		if isAWSErr(err, ecr.ErrCodeRepositoryNotFoundException, "") {
-			log.Printf("[WARN] ECR Repository %s not found, removing from state", d.Id())
-			d.SetId("")
-			return nil
-		}
```
Comment (anGie44) [inline aws/data_source_aws_ecr_repository.go:52]: let's keep this `if` condition to check for this type of error as it's still applicable and helps a user read through the error messaging but instead of logging the message, setting the ID, and returning nil we can just return on error per #13410 e.g.
```go
if isAWSErr(err, ecr.ErrCodeRepositoryNotFoundException, "") {
    return fmt.Errorf("ECR Repository (%s) not found",  d.Get(name).(string))
}
```

**Comment by anGie44** [comment]
Hi @tomelliff, thank you again for this PR! As we're actively working to complete tasks for the upcoming `v3.0.0` release of the AWS Provider, please note we will continue the work you have here and, where necessary, make appropriate changes from review comments to get your work published. If you have any questions please let me know 😃
