### PR TITLE
Modify Aws Backup Selection Resource

### LINKED ISSUE #8443: Cannot update selection tag in aws_backup_selection
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.11
provider.aws v2.6.0

### Affected Resource(s)

* aws_backup_selection

### Terraform Configuration Files

```hcl
resource "aws_backup_selection" "standard_backup_selection" {
  plan_id      = "${aws_backup_plan.standard_backup_plan.id}"
  name         = "standard_backup_selection"
  iam_role_arn = "..."

  selection_tag {
    type  = "STRINGEQUALS"
    key   = "NEW_TAG"
    value = "NEW_VALUE"
  }
}
```

### Debug Output

```
Terraform will perform the following actions:

  ~ module.backup_vault.aws_backup_selection.standard_backup_selection
      selection_tag.4271826135.key:   "" => "backup.plan"
      selection_tag.4271826135.type:  "" => "STRINGEQUALS"
      selection_tag.4271826135.value: "" => "standard"
      selection_tag.706126364.key:    "backup_plan" => ""
      selection_tag.706126364.type:   "STRINGEQUALS" => ""
      selection_tag.706126364.value:  "standard" => ""


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.backup_vault.aws_backup_selection.standard_backup_selection: Modifying... (ID: 8e3c89b1-50e7-4750-98b5-e2300151af31)
  selection_tag.4271826135.key:   "" => "backup.plan"
  selection_tag.4271826135.type:  "" => "STRINGEQUALS"
  selection_tag.4271826135.value: "" => "standard"
  selection_tag.706126364.key:    "backup_plan" => ""
  selection_tag.706126364.type:   "STRINGEQUALS" => ""
  selection_tag.706126364.value:  "standard" => ""

Error: Error applying plan:

1 error(s) occurred:

* module.backup_vault.aws_backup_selection.standard_backup_selection: 1 error(s) occurred:

* aws_backup_selection.standard_backup_selection: doesn't support update
```

### Expected Behavior

I changed the tag used as the selection for backing up a resource using a backup plan. aws_backup_selection do not support updates, so what should have happened is the old aws_backup_selection should have been deleted and a new resource created.

### Actual Behavior

Terraform plan shows the tag in the aws_backup_selection will be changed, but terraform apply fails because `aws_backup_selection.standard_backup_selection: doesn't support update`

### Steps to Reproduce

1. Create an aws_backup_vault, aws_backup_plan, and a aws_backup_selection where the selection is selecting using a tag
2. `terraform apply`
3. Change the aws_backup_selection tag
4. `terraform apply` again to get the error.

### Important Factoids

None

### References

* None

### PR DESCRIPTION
**Pull request by kterada0509**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Fixes #8443

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
- resource/aws_backup_selection: Add `ForceNew` configuration for `selection_tag` attributes.
- resource/aws_backup_selection: Add resource import support.
```

Output from acceptance testing:

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAwsBackupSelection_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAwsBackupSelection_ -timeout 120m
=== RUN   TestAccAwsBackupSelection_basic
=== PAUSE TestAccAwsBackupSelection_basic
=== RUN   TestAccAwsBackupSelection_disappears
=== PAUSE TestAccAwsBackupSelection_disappears
=== RUN   TestAccAwsBackupSelection_withTags
=== PAUSE TestAccAwsBackupSelection_withTags
=== RUN   TestAccAwsBackupSelection_withResources
=== PAUSE TestAccAwsBackupSelection_withResources
=== RUN   TestAccAwsBackupSelection_updateTag
=== PAUSE TestAccAwsBackupSelection_updateTag
=== CONT  TestAccAwsBackupSelection_basic
=== CONT  TestAccAwsBackupSelection_withResources
=== CONT  TestAccAwsBackupSelection_updateTag
=== CONT  TestAccAwsBackupSelection_withTags
=== CONT  TestAccAwsBackupSelection_disappears
--- PASS: TestAccAwsBackupSelection_disappears (46.77s)
--- PASS: TestAccAwsBackupSelection_withResources (47.35s)
--- PASS: TestAccAwsBackupSelection_basic (47.77s)
--- PASS: TestAccAwsBackupSelection_withTags (47.89s)
--- PASS: TestAccAwsBackupSelection_updateTag (72.42s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	72.491s
```

### CODE REVIEW

File: aws/resource_aws_backup_selection.go [hunk 1]
```diff
@@ -162,6 +169,21 @@ func resourceAwsBackupSelectionDelete(d *schema.ResourceData, meta interface{})
 	return nil
 }
 
+func resourceAwsBackupSelectionImportState(d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
+	idParts := strings.Split(d.Id(), "|")
+	if len(idParts) != 2 || idParts[0] == "" || idParts[1] == "" {
+		return nil, fmt.Errorf("unexpected format of ID (%q), expected <plan-id>:<selection-id>", d.Id())
```
Comment (bflad) [inline aws/resource_aws_backup_selection.go]: The delimiter above is `|` not `:`

```suggestion
		return nil, fmt.Errorf("unexpected format of ID (%q), expected <plan-id>|<selection-id>", d.Id())
```

File: website/docs/r/backup_selection.html.markdown [hunk 2]
```diff
@@ -52,3 +52,11 @@ Tag conditions (`selection_tag`) support the following:
 In addition to all arguments above, the following attributes are exported:
 
 * `id` - Backup Selection identifier
+
+## Import
+
+Backup selection can be imported using the role plan_id and id separated by `|`.
+
+```
+$ terraform import aws_backup_selection.example plan-id/selection-id
```
Comment (bflad) [inline website/docs/r/backup_selection.html.markdown]: The delimiter in the import state function is `|` not `:`

```suggestion
$ terraform import aws_backup_selection.example plan-id|selection-id
```

File: aws/resource_aws_backup_selection_test.go [hunk 3]
```diff
@@ -152,6 +205,31 @@ func testAccCheckAwsBackupSelectionDisappears(selection *backup.GetBackupSelecti
 	}
 }
 
+func testAccCheckAwsBackupSelectionRecreated(t *testing.T,
```
Comment (bflad) [inline aws/resource_aws_backup_selection_test.go]: 💯 Thanks for adding this.

**Comment by bflad** [comment]
This has been released in [version 2.11.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2110-may-17-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
