### PR TITLE
Issue #459 - EBS information required during cluster config change

### LINKED ISSUE #459: Adding new instances on aws_elasticsearch_domain with ebs_volume does not work if ebs_option has not changed
_This issue was originally opened by @SilverXion as hashicorp/terraform#11004. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

When applying change for "instance_count" for an instance type using ebs_volume (ex: t2.medium.elasticsearch), if the ebs_options have not changed, the following error is prompt:

aws_elasticsearch_domain.logs: ValidationException: New cluster configuration has insufficient storage capacity for your current data. The new configuration only supports up to 0.0GB

### Terraform Version
v0.7.9

### Affected Resource(s)
- aws_elasticsearch_domain

### Expected Behavior
Even if the ebs_options have not changed, they should be passed down to aws when adding new instances.

### Actual Behavior
If the ebs_options do not change, the volume_size passed to the new instance seems to be 0.

### Steps to Reproduce
1. `terraform apply`

Initial Configuration:
`
cluster_config {
    instance_type          = "t2.medium.elasticsearch"
    instance_count         = "2"
    zone_awareness_enabled = "true"
  }`
`
ebs_options {
    ebs_enabled = "true"
    volume_type = "standard"
    volume_size = "35}"
  }
`
New Configuration:
`
cluster_config {
    instance_type          = "t2.medium.elasticsearch"
    instance_count         = "4"
    zone_awareness_enabled = "true"
  }`
`
ebs_options {
    ebs_enabled = "true"
    volume_type = "standard"
    volume_size = "35}"
  }
`

### Addiotional Information
The same command will apply correctly if the ebs_options are changed, ex:
`
ebs_options {
    ebs_enabled = "true"
    volume_type = "standard"
    volume_size = "34}"
  }
`

### PR DESCRIPTION
**Pull request by DanKans**
AWS demands to pass information about EBS volume during cluster configuration change like e.g. number of data nodes.

Fixes #459

Debug data from issue:
```
  cluster_config.0.instance_count: "2" => "1"

2017/07/12 12:47:01 [DEBUG] plugin: terraform-provider-aws: 2017/07/12 12:47:01 [DEBUG] [aws-sdk-go] DEBUG: Request es/UpdateElasticsearchDomainConfig Details:
2017/07/12 12:47:01 [DEBUG] plugin: terraform-provider-aws: ---[ REQUEST POST-SIGN ]-----------------------------
2017/07/12 12:47:01 [DEBUG] plugin: terraform-provider-aws: POST /2015-01-01/es/domain/daniel-test/config HTTP/1.1
2017/07/12 12:47:01 [DEBUG] plugin: terraform-provider-aws: Host: es.us-east-1.amazonaws.com
2017/07/12 12:47:01 [DEBUG] plugin: terraform-provider-aws: User-Agent: aws-sdk-go/1.10.8 (go1.8.1; linux; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.9.8
2017/07/12 12:47:01 [DEBUG] plugin: terraform-provider-aws: Content-Length: 150
2017/07/12 12:47:01 [DEBUG] plugin: terraform-provider-aws: Authorization: AWS4-HMAC-SHA256 Credential=/20170712/us-east-1/es/aws4_request, SignedHeaders=content-length;host;x-amz-date, Signature=
2017/07/12 12:47:01 [DEBUG] plugin: terraform-provider-aws: X-Amz-Date: 20170712T114701Z
2017/07/12 12:47:01 [DEBUG] plugin: terraform-provider-aws: Accept-Encoding: gzip
2017/07/12 12:47:01 [DEBUG] plugin: terraform-provider-aws:
2017/07/12 12:47:01 [DEBUG] plugin: terraform-provider-aws: {"ElasticsearchClusterConfig":{"DedicatedMasterEnabled":false,"InstanceCount":2,"InstanceType":"t2.small.elasticsearch","ZoneAwarenessEnabled":false}}
2017/07/12 12:47:01 [DEBUG] plugin: terraform-provider-aws: -----------------------------------------------------
2017/07/12 12:47:02 [DEBUG] plugin: terraform-provider-aws: 2017/07/12 12:47:02 [DEBUG] [aws-sdk-go] DEBUG: Response es/UpdateElasticsearchDomainConfig Details:
2017/07/12 12:47:02 [DEBUG] plugin: terraform-provider-aws: ---[ RESPONSE ]--------------------------------------
2017/07/12 12:47:02 [DEBUG] plugin: terraform-provider-aws: HTTP/1.1 400 Bad Request
2017/07/12 12:47:02 [DEBUG] plugin: terraform-provider-aws: Content-Length: 188
2017/07/12 12:47:02 [DEBUG] plugin: terraform-provider-aws: Content-Type: application/json
2017/07/12 12:47:02 [DEBUG] plugin: terraform-provider-aws: Date: Wed, 12 Jul 2017 11:47:01 GMT
2017/07/12 12:47:02 [DEBUG] plugin: terraform-provider-aws: X-Amzn-Errortype: ValidationException
2017/07/12 12:47:02 [DEBUG] plugin: terraform-provider-aws: X-Amzn-Requestid:
2017/07/12 12:47:02 [DEBUG] plugin: terraform-provider-aws:
2017/07/12 12:47:02 [DEBUG] plugin: terraform-provider-aws:
2017/07/12 12:47:02 [DEBUG] plugin: terraform-provider-aws: -----------------------------------------------------
2017/07/12 12:47:02 [DEBUG] plugin: terraform-provider-aws: 2017/07/12 12:47:02 [DEBUG] [aws-sdk-go] {"message":"New cluster configuration has insufficient storage capacity for your current data. The new configuration only supports up to 0.0GB. Your current Elasticsearch usage is 0.00GB"}
```

Debug data after fix:
```
cluster_config.0.instance_count: "2" => "1"
2017/07/12 13:42:35 [DEBUG] plugin: terraform-provider-aws: 2017/07/12 13:42:35 [DEBUG] [aws-sdk-go] DEBUG: Request es/UpdateElasticsearchDomainConfig Details:
2017/07/12 13:42:35 [DEBUG] plugin: terraform-provider-aws: ---[ REQUEST POST-SIGN ]-----------------------------
2017/07/12 13:42:35 [DEBUG] plugin: terraform-provider-aws: POST /2015-01-01/es/domain/daniel-test/config HTTP/1.1
2017/07/12 13:42:35 [DEBUG] plugin: terraform-provider-aws: Host: es.us-east-1.amazonaws.com
2017/07/12 13:42:35 [DEBUG] plugin: terraform-provider-aws: User-Agent: aws-sdk-go/1.10.8 (go1.8.1; linux; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.9.8
2017/07/12 13:42:35 [DEBUG] plugin: terraform-provider-aws: Content-Length: 218
2017/07/12 13:42:35 [DEBUG] plugin: terraform-provider-aws: Authorization: AWS4-HMAC-SHA256 Credential=/20170712/us-east-1/es/aws4_request, SignedHeaders=content-length;host;x-amz-date, Signature=
2017/07/12 13:42:35 [DEBUG] plugin: terraform-provider-aws: X-Amz-Date: 20170712T124235Z
2017/07/12 13:42:35 [DEBUG] plugin: terraform-provider-aws: Accept-Encoding: gzip
2017/07/12 13:42:35 [DEBUG] plugin: terraform-provider-aws:
2017/07/12 13:42:35 [DEBUG] plugin: terraform-provider-aws: {"EBSOptions":{"EBSEnabled":true,"VolumeSize":10,"VolumeType":"gp2"},"ElasticsearchClusterConfig":{"DedicatedMasterEnabled":false,"InstanceCount":1,"InstanceType":"t2.small.elasticsearch","ZoneAwarenessEnabled":false}}
2017/07/12 13:42:35 [DEBUG] plugin: terraform-provider-aws: -----------------------------------------------------
2017/07/12 13:42:36 [DEBUG] plugin: terraform-provider-aws: 2017/07/12 13:42:36 [DEBUG] [aws-sdk-go] DEBUG: Response es/UpdateElasticsearchDomainConfig Details:
2017/07/12 13:42:36 [DEBUG] plugin: terraform-provider-aws: ---[ RESPONSE ]--------------------------------------
2017/07/12 13:42:36 [DEBUG] plugin: terraform-provider-aws: HTTP/1.1 200 OK
2017/07/12 13:42:36 [DEBUG] plugin: terraform-provider-aws: Content-Length: 1355
2017/07/12 13:42:36 [DEBUG] plugin: terraform-provider-aws: Content-Type: application/json
2017/07/12 13:42:36 [DEBUG] plugin: terraform-provider-aws: Date: Wed, 12 Jul 2017 12:42:36 GMT
2017/07/12 13:42:36 [DEBUG] plugin: terraform-provider-aws: X-Amzn-Requestid:
2017/07/12 13:42:36 [DEBUG] plugin: terraform-provider-aws:
2017/07/12 13:42:36 [DEBUG] plugin: terraform-provider-aws:
2017/07/12 13:42:36 [DEBUG] plugin: terraform-provider-aws: -----------------------------------------------------
2017/07/12 13:42:36 [DEBUG] plugin: terraform-provider-aws: 2017/07/12 13:42:36 [DEBUG] [aws-sdk-go] {"DomainConfig":{"AccessPo...<CUT>
```

Please verify.
Thanks

### CODE REVIEW

File: aws/resource_aws_elasticsearch_domain.go [hunk 1]
```diff
@@ -358,10 +358,10 @@ func resourceAwsElasticSearchDomainUpdate(d *schema.ResourceData, meta interface
 
 	if err := setTagsElasticsearchService(conn, d, d.Id()); err != nil {
 		return err
-	} else {
-		d.SetPartial("tags")
 	}
 
+	d.SetPartial("tags")
+
```
Comment (radeksimko) [inline aws/resource_aws_elasticsearch_domain.go]: What exactly is the reason for this change?

Comment (DanKans) [inline aws/resource_aws_elasticsearch_domain.go]: The reason is purely cosmetic. In case where there is an error, function will `return` from function so there is no need to keep `else`. From other side, by using 'else' we can show that there is a relation between `setTagsElasticsearchService` and `d.SetPartial("tags")`, so if there is any relation between them maybe we should keep `else` :>

Comment (radeksimko) [inline aws/resource_aws_elasticsearch_domain.go]: > In case where there is an error, function will `return` from function so there is no need to keep `else`

Ah, you're right, good point. Early return FTW 👍

**Comment by DanKans** [comment]
Hi @radeksimko,

I've added a simply test to check if number of instances are equal. IMHO there should be some general test for update feature. Please verify and let me know what do you think.

Thanks!
Daniel

File: aws/resource_aws_elasticsearch_domain_test.go [hunk 2]
```diff
@@ -144,6 +144,36 @@ func TestAccAWSElasticSearchDomain_tags(t *testing.T) {
...
+		Providers:    testAccProviders,
+		CheckDestroy: testAccCheckESDomainDestroy,
+		Steps: []resource.TestStep{
+			{
+				Config: testAccESDomainConfig_ClusterUpdate(ri),
+				Check: resource.ComposeTestCheckFunc(
+					testAccCheckESDomainExists("aws_elasticsearch_domain.example", &input),
+					testAccCheckESNumberOfInstances(ri, input.ElasticsearchClusterConfig),
+				),
+			},
```
Comment (radeksimko) [inline aws/resource_aws_elasticsearch_domain_test.go]: > IMHO there should be some general test for update feature.

There's a way to test updates. You just add another `TestStep` into the slice with modified config - then the first step will create resources and second step will modify.

File: aws/resource_aws_elasticsearch_domain_test.go [hunk 3]
```diff
@@ -224,6 +254,38 @@ resource "aws_elasticsearch_domain" "example" {
...
+  }
+
+  ebs_options {
+    ebs_enabled = true
+		volume_size = 10
+		
+  }
+
+  cluster_config {
+    instance_count = %d
```
Comment (radeksimko) [inline aws/resource_aws_elasticsearch_domain_test.go]: This should be certainly static number, we don't want to be spinning up an _unbound_ random number of instances 💸 😃 

Randomization is however certainly desired, but only in places that are unique, like `domain_name` see other tests in this file.

File: aws/resource_aws_elasticsearch_domain_test.go (hunk 2 above)
Comment (radeksimko) [inline aws/resource_aws_elasticsearch_domain_test.go]: Take a look at how we test updates of tags in `TestAccAWSElasticSearchDomain_tags` above. 😉

File: aws/resource_aws_elasticsearch_domain_test.go (hunk 3 above)
Comment (DanKans) [inline aws/resource_aws_elasticsearch_domain_test.go]: Good point. I've also changed instance type to `t2.micro`.

File: aws/resource_aws_elasticsearch_domain_test.go (hunk 2 above)
Comment (DanKans) [inline aws/resource_aws_elasticsearch_domain_test.go]: Thanks! I've added [some code](https://github.com/DanKans/terraform-provider-aws/blob/eaa979576213d81369b4e2954070c71dd072254c/aws/resource_aws_elasticsearch_domain_test.go#L147). Could you please take a look and let me know what do you think?

**Comment by radeksimko** [comment]
I made some enhancements to the test to make it pass.

Thanks for all the efforts. Merging 🎉

**Comment by DanKans** [comment]
I'm looking into your commits in order to learn! 
Thanks @radeksimko!
