### PR TITLE
r/aws_network_interface: Add an update check

### LINKED ISSUE #11273: Redundant ec2:ModifyNetworkInterfaceAttribute call when updating aws_network_interface
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.18
+ provider.archive v1.3.0
+ provider.aws v2.41.0
+ provider.null v2.1.2
+ provider.template v2.1.2
```

### Affected Resource(s)

- aws_network_interface

#### 1st Apply

First, apply the following tf file.

```hcl
module "this_vpc" {
  source = "terraform-aws-modules/vpc/aws"

  name = "eni-test"
  cidr = "192.168.0.0/24"

  azs            = ["ap-northeast-1a"]
  public_subnets = ["192.168.0.0/25"]

  enable_nat_gateway = false
}

resource "aws_network_interface" "eni" {
  subnet_id         = module.this_vpc.public_subnets[0]
  source_dest_check = false
}
```

#### 2nd Apply

Then, add `tags` attribute to `aws_network_interface.eni` and apply.

```hcl
module "this_vpc" {
  source = "terraform-aws-modules/vpc/aws"

  name = "eni-test"
  cidr = "192.168.0.0/24"

  azs            = ["ap-northeast-1a"]
  public_subnets = ["192.168.0.0/25"]

  enable_nat_gateway = false
}

resource "aws_network_interface" "eni" {
  subnet_id         = module.this_vpc.public_subnets[0]
  source_dest_check = false

  tags = {
    "DummyTag" = 1
  }
}
```

### Debug Output

A part of the debug output from 2nd apply (full log not provided for security purpose).
https://gist.github.com/nozaq/b872123c8ceb7961089a8fee0c30ff8a

### Panic Output

Terraform doesn't produce a panic.

### Expected Behavior

On 2nd apply, only [ec2:CreateTags](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateTags.html) is called to update tags on `aws_network_interface.eni`.

### Actual Behavior

On 2nd apply, [ec2:ModifyNetworkInterfaceAttribute](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyNetworkInterfaceAttribute.html) is called with SourceDestCheck paramter before ec2:CreateTags.

ec2:ModifyNetworkInterfaceAttribute call is redundant since SourceDestCheck parameter doesn't change on this apply.

### Steps to Reproduce

1. `terraform apply` with the `1st Apply` code above.
2. `terraform apply` with the `2nd Apply` code above.

### Important Factoids

None

### References

None

### PR DESCRIPTION
**Pull request by nozaq**
Do not call ec2:ModifyNetworkInterfaceAttribute when arguments are not
changed.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #11273 

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_network_interface: Do not call ec2:ModifyNetworkInterfaceAttribute when arguments are not changed.
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSENI_sourceDestCheck'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -count 1 -parallel 20 -run=TestAccAWSENI_sourceDestCheck -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSENI_sourceDestCheck
=== PAUSE TestAccAWSENI_sourceDestCheck
=== CONT  TestAccAWSENI_sourceDestCheck
--- PASS: TestAccAWSENI_sourceDestCheck (65.85s)
PASS                                                             
ok      github.com/terraform-providers/terraform-provider-aws/aws       65.882s
testing: warning: no tests to run                                
PASS                                                             
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/flatmap      0.032s [no tests to run]
testing: warning: no tests to run                                                                                                 
PASS                                                             
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags 0.005s [no tests to run]
```

### CODE REVIEW

File: aws/resource_aws_network_interface.go [hunk 1]
```diff
@@ -323,17 +323,21 @@ func resourceAwsNetworkInterfaceUpdate(d *schema.ResourceData, meta interface{})
 		d.SetPartial("private_ips")
 	}
 
-	request := &ec2.ModifyNetworkInterfaceAttributeInput{
-		NetworkInterfaceId: aws.String(d.Id()),
-		SourceDestCheck:    &ec2.AttributeBooleanValue{Value: aws.Bool(d.Get("source_dest_check").(bool))},
-	}
+	// ModifyNetworkInterfaceAttribute needs to be called after creating an ENI
+	// since CreateNetworkInterface doesn't take SourceDeskCheck paramter.
```
Comment (bflad) [inline aws/resource_aws_network_interface.go]: Fix for linting error:

```suggestion
	// since CreateNetworkInterface doesn't take SourceDeskCheck parameter.
```

**Comment by nozaq** [comment]
@bflad Thanks for your review, just pushed a fix! :+1:
