### PR TITLE
provider: Support AWS C2S/SC2S Regional ARNs in ARN validation

### LINKED ISSUE #11444: func ValidateARN regex check needs to support additional regions
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
 0.12.16

### Affected Resource(s)

* All resources that call func validateArn

### Expected Behavior

Referencing a KMS Key ARN in aws_ami_copy should allow a key to be associated for encryption during the copy.

### Actual Behavior

An error occured stating that "This doesn't look like a valid ARN".  validateARN does not support certain unlisted AWS regions.  The pattern check needs to allow more flexibility in the second tuple for gov regions.  i.e. us-XXXX-east-1.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This is running in an unlisted AWS region.

### References

* #0000

### PR DESCRIPTION
**Pull request by bflad**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #11444

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
* provider: Support AWS C2S/SC2S Regional ARNs in ARN validation
```

Output from acceptance testing: Handled via unit testing

### CODE REVIEW

File: aws/validators.go [hunk 1]
```diff
@@ -21,6 +22,16 @@ import (
 	"github.com/hashicorp/terraform-plugin-sdk/helper/validation"
 )
 
+const (
+	awsAccountIDRegexpPattern = `^(aws|\d{12})$`
+	awsPartitionRegexpPattern = `^aws(-[a-z]+)*$`
+	awsRegionRegexpPattern    = `^[a-z]{2}(-[a-z]+)+-\d$`
```
Comment (PatMyron) [inline aws/validators.go]:
```suggestion
	awsRegionRegexpPattern    = `^[a-z]{2}(-[a-z]+)+-\d+$`
```
could be more future-proof

Comment (bflad) [reply aws/validators.go]: @PatMyron indeed, however this would accept invalid values such as `us-east-01`. It would be more correct to use `-[1-9][0-9]*$` as the pattern suffix. Please feel free to submit a follow up pull request on this, if desired, since this is not a current concern with publicly documented region names.

**Comment by ewbankkit** [comment]
@bflad I think this also closes https://github.com/terraform-providers/terraform-provider-aws/issues/8307.

**Comment by bflad** [comment]
@ewbankkit thanks!!
