### PR TITLE
tests/service/wafv2: Implement sweepers

### LINKED ISSUE #15857: tests/resource/aws_wafv2_regex_pattern_set: Implement Sweeper
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The acceptance testing can leave lingering resources on failed runs (e.g. via coding issues during development or panics). These lingering resources can cause quota limits to be reached, extraneous money to be spent, or in some worst cases leave open security risks in the testing account.

We do not require sweeper implementation during initial resource implementation at this time, but this may change in the future when the process can be simplified and documented better.

We are currently hitting quota limits on this resource in our testing account:

```
=== CONT  TestAccAwsWafv2RegexPatternSet_Minimal
TestAccAwsWafv2RegexPatternSet_Minimal: resource_aws_wafv2_regex_pattern_set_test.go:102: Step 1/1 error: Error running apply: 2020/10/26 16:06:34 [DEBUG] Using modified User-Agent: Terraform/0.12.29 HashiCorp-terraform-exec/0.10.0
Error: Error creating WAFv2 RegexPatternSet: WAFLimitsExceededException: AWS WAF couldn’t perform the operation because you exceeded your resource limit.
--- FAIL: TestAccAwsWafv2RegexPatternSet_Minimal (24.66s)
```

### Definition of Done

* New `aws/resource_aws_wafv2_regex_pattern_set.go` file that has dependencies on any existing `aws_wafv2_rule`, etc. resource sweepers
* Testing account empty of this resource:

```console
$  aws wafv2 list-regex-pattern-sets --scope REGIONAL | jq '.RegexPatternSets | length'
0
```

### References

* [Extending Terraform sweeper documentation](https://www.terraform.io/docs/extend/testing/acceptance-tests/sweepers.html)

### PR DESCRIPTION
**Pull request by bflad**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #15857

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Output from sweeper in AWS Commercial:

```
2020/10/27 14:03:02 [DEBUG] Running Sweepers for region (us-west-2):
2020/10/27 14:03:02 [DEBUG] Running Sweeper (aws_wafv2_web_acl) in region (us-west-2)
2020/10/27 14:03:03 [INFO] Deleting WAFv2 WebACL 3d9b6864-5efc-49ea-9480-1190b5bb9c0d
2020/10/27 14:03:04 [INFO] Deleting WAFv2 WebACL 651429c4-26af-4597-a6a1-451339ea8f05
2020/10/27 14:03:08 [INFO] Deleting WAFv2 WebACL d56756a2-9a39-46e6-a147-9a567e286ee1
2020/10/27 14:03:08 [INFO] Deleting WAFv2 WebACL f3b621d6-19c6-47a6-85d3-f9918c5e45fa
2020/10/27 14:03:10 [INFO] Deleting WAFv2 WebACL d0cd770c-ee13-44dc-a139-63b463c3da63
2020/10/27 14:03:11 [INFO] Deleting WAFv2 WebACL e3b0ff4b-14bc-4a6a-a261-652ae5b0195e
2020/10/27 14:03:12 [INFO] Deleting WAFv2 WebACL f0400dec-5ff3-48cf-9c72-e0e6bdc7d50f
2020/10/27 14:03:13 [INFO] Deleting WAFv2 WebACL 689efa3c-0781-4f58-93c9-8b956ba79e1c
2020/10/27 14:03:15 [INFO] Deleting WAFv2 WebACL 4f9c1abf-a649-420d-9bbf-7fd39de821a0
2020/10/27 14:03:15 [INFO] Deleting WAFv2 WebACL 20a75de0-1533-4bc9-aa89-fcae72499b42
2020/10/27 14:03:16 [INFO] Deleting WAFv2 WebACL 8cce8d86-abd6-4d59-b212-fc016b7dba87
2020/10/27 14:03:20 [INFO] Deleting WAFv2 WebACL 2b515cad-ecf0-44c8-b7bc-bd4659873bdd
2020/10/27 14:03:21 [INFO] Deleting WAFv2 WebACL 0a4f57de-e7d2-45b9-b536-9e96c156ebc5
2020/10/27 14:03:23 [INFO] Deleting WAFv2 WebACL 4edd0599-170d-44ce-bfef-b3aa25cc88f9
2020/10/27 14:03:25 [INFO] Deleting WAFv2 WebACL 25a43cdb-f072-4514-aece-455c52be826f
2020/10/27 14:03:25 [INFO] Deleting WAFv2 WebACL 1084871a-7d76-4776-bc3d-ea35955ff3d8
2020/10/27 14:03:26 [INFO] Deleting WAFv2 WebACL 73f0d7bb-ef48-4d9e-8163-99d07bce6e50
2020/10/27 14:03:36 [INFO] Deleting WAFv2 WebACL d6ba38fd-210e-429e-9fc3-cb3ba0490a62
2020/10/27 14:03:37 [INFO] Deleting WAFv2 WebACL 6a8b6dbe-71c6-482d-8ca2-ceced93fd616
2020/10/27 14:03:37 [ERROR] error deleting WAFv2 Web ACL (6a8b6dbe-71c6-482d-8ca2-ceced93fd616): Error deleting WAFv2 WebACL: WAFNonexistentItemException: AWS WAF couldn’t perform the operation because your resource doesn’t exist.
2020/10/27 14:03:37 [INFO] Deleting WAFv2 WebACL 8fffcb31-fd36-4024-9601-ec030a42eb87
2020/10/27 14:03:38 [INFO] Deleting WAFv2 WebACL aa98061e-d941-4fa5-920d-291f4ef9386a
2020/10/27 14:03:41 [INFO] Deleting WAFv2 WebACL 59d4db17-1c2e-46d4-9d90-839ceb2fc565
2020/10/27 14:03:42 [INFO] Deleting WAFv2 WebACL 56ad6197-60cf-4713-abc2-43c570cf873a
2020/10/27 14:03:43 [INFO] Deleting WAFv2 WebACL 4b8d10fc-bc75-47e3-a50d-12a1d52df468
2020/10/27 14:03:44 [INFO] Deleting WAFv2 WebACL 917a1735-9272-4515-9ce1-a02959345c9f
2020/10/27 14:03:46 [INFO] Deleting WAFv2 WebACL 4bcf76e0-f243-4fe6-8596-33607ebd6041
2020/10/27 14:03:47 [INFO] Deleting WAFv2 WebACL d1dc2e7e-db2e-48f4-9eee-6e27da1166a1
2020/10/27 14:03:49 [INFO] Deleting WAFv2 WebACL 4cbb7bdf-ddd9-4667-b12a-ac04745d71ab
2020/10/27 14:03:50 [INFO] Deleting WAFv2 WebACL 57c7a170-5388-48eb-8e72-d9e13b52384d
2020/10/27 14:03:51 [INFO] Deleting WAFv2 WebACL 5853dfba-66b2-4092-93d4-f64ec44f6cc3
2020/10/27 14:03:51 [INFO] Deleting WAFv2 WebACL ff2f9533-eeec-4c9f-a8a6-b1847d8f6723
2020/10/27 14:03:56 [INFO] Deleting WAFv2 WebACL 98a82c8d-5eaf-4b30-8c74-1167f4f1e973
2020/10/27 14:03:56 [INFO] Deleting WAFv2 WebACL 27d77c82-173c-4588-9e7d-5fac54fc6f9f
2020/10/27 14:03:58 [ERROR] Error running Sweeper (aws_wafv2_web_acl) in region (us-west-2): 1 error occurred:
  * error deleting WAFv2 Web ACL (6a8b6dbe-71c6-482d-8ca2-ceced93fd616): Error deleting WAFv2 WebACL: WAFNonexistentItemException: AWS WAF couldn’t perform the operation because your resource doesn’t exist.

2020/10/27 14:03:58 [ERROR] Error running Sweeper (aws_wafv2_web_acl) in region (us-west-2): 1 error occurred:
  * error deleting WAFv2 Web ACL (6a8b6dbe-71c6-482d-8ca2-ceced93fd616): Error deleting WAFv2 WebACL: WAFNonexistentItemException: AWS WAF couldn’t perform the operation because your resource doesn’t exist.

2020/10/27 14:03:58 [DEBUG] Running Sweeper (aws_wafv2_rule_group) in region (us-west-2)
2020/10/27 14:03:59 [INFO] Deleting WAFv2 RuleGroup 653d7bb5-334d-4af7-a639-3f2b114fd550
2020/10/27 14:03:59 [INFO] Deleting WAFv2 RuleGroup 1fd561a4-f397-4b1e-abae-c45c73d4844b
2020/10/27 14:03:59 [INFO] Deleting WAFv2 RuleGroup 6240860f-8aea-4110-baa1-5c5ff9241142
2020/10/27 14:04:04 [DEBUG] Running Sweeper (aws_wafv2_regex_pattern_set) in region (us-west-2)
2020/10/27 14:04:04 [INFO] Deleting WAFv2 RegexPatternSet 37de22f7-7abd-46e8-b1bb-bbde96e7fa87
2020/10/27 14:04:04 [INFO] Deleting WAFv2 RegexPatternSet 17760c58-f53e-4776-a2f6-b5ec445f481e
2020/10/27 14:04:06 [INFO] Deleting WAFv2 RegexPatternSet 298a3686-5f32-437a-bdda-3774c1b67b88
2020/10/27 14:04:06 [INFO] Deleting WAFv2 RegexPatternSet b2e7f463-7745-4bc9-93b3-978c5249af45
2020/10/27 14:04:08 [INFO] Deleting WAFv2 RegexPatternSet 91cd1be1-d915-4f11-a252-07a3106531e0
2020/10/27 14:04:08 [INFO] Deleting WAFv2 RegexPatternSet 3efcf813-03b9-41bc-89cf-0df0b858047b
2020/10/27 14:04:10 [INFO] Deleting WAFv2 RegexPatternSet 5cd42d41-99c9-4063-b4ee-7af51cabe35b
2020/10/27 14:04:10 [INFO] Deleting WAFv2 RegexPatternSet 0fe4412e-87b0-47fe-bee4-285c192c3175
2020/10/27 14:04:14 [INFO] Deleting WAFv2 RegexPatternSet 206520ce-7b34-4269-a857-5351a598ccc3
2020/10/27 14:04:16 [DEBUG] Running Sweeper (aws_wafv2_ip_set) in region (us-west-2)
2020/10/27 14:04:16 [INFO] Deleting WAFv2 IPSet e6aef222-b6f9-4285-af3f-c9c0a049fed3
2020/10/27 14:04:17 [INFO] Deleting WAFv2 IPSet 1b674530-cad9-4cfc-a07f-507eab411dc3
2020/10/27 14:04:17 [INFO] Deleting WAFv2 IPSet 8d2856c7-c9af-4511-adc4-2f582578f750
2020/10/27 14:04:17 [INFO] Deleting WAFv2 IPSet 1a962592-30b4-42f7-88fa-0fd9559c621f
2020/10/27 14:04:19 [INFO] Deleting WAFv2 IPSet 15cef06b-033d-4441-808d-011381f46ea1
2020/10/27 14:04:21 [INFO] Deleting WAFv2 IPSet 75be2098-26a0-4fbb-8b50-4348115f630e
2020/10/27 14:04:22 [INFO] Deleting WAFv2 IPSet ca7cc6fc-591f-4149-9ea4-8c8229485d3a
2020/10/27 14:04:23 [INFO] Deleting WAFv2 IPSet 042fc9b5-5f26-4ef9-9fbb-a08682cce888
2020/10/27 14:04:24 [INFO] Deleting WAFv2 IPSet f61afd6d-8316-4391-8ce7-d7fa83a21dce
2020/10/27 14:04:24 [INFO] Deleting WAFv2 IPSet c84bd4c8-23c0-4647-8bb7-1206ef218efc
2020/10/27 14:04:26 [INFO] Deleting WAFv2 IPSet 2af3a9e9-6253-44bf-a82b-efbd89822cb6
2020/10/27 14:04:27 [INFO] Deleting WAFv2 IPSet 6d0df7d1-8772-4c30-bfef-30ed6f7be36e
2020/10/27 14:04:28 [INFO] Deleting WAFv2 IPSet ce0467c4-0eba-4113-ab42-244fc208b57b
2020/10/27 14:04:29 [INFO] Deleting WAFv2 IPSet 58512687-764b-4704-b2fb-3b0c21538648
2020/10/27 14:04:32 [INFO] Deleting WAFv2 IPSet f8f2568a-0d88-46f1-8ff5-d0ee58f3e51f
2020/10/27 14:04:34 [INFO] Deleting WAFv2 IPSet 311cca9a-fb5b-49e9-b5c9-30f15fc41a5c
2020/10/27 14:04:35 Sweeper Tests ran successfully:
  - aws_wafv2_rule_group
  - aws_wafv2_regex_pattern_set
  - aws_wafv2_ip_set
2020/10/27 14:04:35 Sweeper Tests ran unsuccessfully:
  - aws_wafv2_web_acl: 1 error occurred:
  * error deleting WAFv2 Web ACL (6a8b6dbe-71c6-482d-8ca2-ceced93fd616): Error deleting WAFv2 WebACL: WAFNonexistentItemException: AWS WAF couldn’t perform the operation because your resource doesn’t exist.

2020/10/27 14:04:35 [DEBUG] Running Sweepers for region (us-east-1):
2020/10/27 14:04:35 [DEBUG] Running Sweeper (aws_wafv2_web_acl) in region (us-east-1)
2020/10/27 14:04:35 [INFO] Deleting WAFv2 WebACL 00fb7435-dd9f-4340-ab7f-b8090bad23f0
2020/10/27 14:04:36 [DEBUG] Running Sweeper (aws_wafv2_rule_group) in region (us-east-1)
2020/10/27 14:04:36 [DEBUG] Running Sweeper (aws_wafv2_ip_set) in region (us-east-1)
2020/10/27 14:04:36 [DEBUG] Running Sweeper (aws_wafv2_regex_pattern_set) in region (us-east-1)
2020/10/27 14:04:36 [INFO] Deleting WAFv2 RegexPatternSet e497e8e2-45a3-4978-8918-5229ea3f56ce
2020/10/27 14:04:36 Sweeper Tests ran successfully:
  - aws_wafv2_web_acl
  - aws_wafv2_rule_group
  - aws_wafv2_ip_set
  - aws_wafv2_regex_pattern_set
FAIL  github.com/terraform-providers/terraform-provider-aws/aws 100.547s
FAIL
```

After adding `WAFNonexistentItemException` error handling to Web ACL deletion function:

Output from sweeper in AWS Commercial:

```
2020/10/27 14:09:36 [DEBUG] Running Sweepers for region (us-west-2):
2020/10/27 14:09:36 [DEBUG] Running Sweeper (aws_wafv2_web_acl) in region (us-west-2)
2020/10/27 14:09:37 [DEBUG] Running Sweeper (aws_wafv2_rule_group) in region (us-west-2)
2020/10/27 14:09:37 [DEBUG] Running Sweeper (aws_wafv2_ip_set) in region (us-west-2)
2020/10/27 14:09:38 [DEBUG] Running Sweeper (aws_wafv2_regex_pattern_set) in region (us-west-2)
2020/10/27 14:09:38 Sweeper Tests ran successfully:
	- aws_wafv2_web_acl
	- aws_wafv2_rule_group
	- aws_wafv2_ip_set
	- aws_wafv2_regex_pattern_set
2020/10/27 14:09:38 [DEBUG] Running Sweepers for region (us-east-1):
2020/10/27 14:09:38 [DEBUG] Running Sweeper (aws_wafv2_web_acl) in region (us-east-1)
2020/10/27 14:09:38 [DEBUG] Running Sweeper (aws_wafv2_rule_group) in region (us-east-1)
2020/10/27 14:09:38 [DEBUG] Running Sweeper (aws_wafv2_regex_pattern_set) in region (us-east-1)
2020/10/27 14:09:39 [DEBUG] Running Sweeper (aws_wafv2_ip_set) in region (us-east-1)
2020/10/27 14:09:39 Sweeper Tests ran successfully:
	- aws_wafv2_web_acl
	- aws_wafv2_rule_group
	- aws_wafv2_regex_pattern_set
	- aws_wafv2_ip_set
ok  	github.com/terraform-providers/terraform-provider-aws/aws	6.462s
```

Output from sweeper in AWS GovCloud (US):

```
2020/10/27 14:04:02 [DEBUG] Running Sweepers for region (us-gov-west-1):
2020/10/27 14:04:02 [DEBUG] Running Sweeper (aws_wafv2_web_acl) in region (us-gov-west-1)
2020/10/27 14:04:03 [INFO] Deleting WAFv2 WebACL 2b3eefde-ed05-42ce-bb52-77764c8a89a2
2020/10/27 14:04:04 [INFO] Deleting WAFv2 WebACL ba77e1ac-5108-4756-83a9-887ef0f268f5
2020/10/27 14:04:04 [INFO] Deleting WAFv2 WebACL 80e81972-5164-43c7-b997-706a234e0d62
2020/10/27 14:04:06 [INFO] Deleting WAFv2 WebACL acf841f8-594b-4398-860d-8b1234548170
2020/10/27 14:04:08 [INFO] Deleting WAFv2 WebACL dc7f3511-4dca-4a4c-bfd1-13c02e8cb527
2020/10/27 14:04:09 [INFO] Deleting WAFv2 WebACL 20f17885-90cf-4517-bf50-4ebbdf8178a5
2020/10/27 14:04:10 [INFO] Deleting WAFv2 WebACL b39832c1-ad39-48d6-98a4-b3ae4086cdd0
2020/10/27 14:04:10 [INFO] Deleting WAFv2 WebACL 73ef91f0-ca9c-446b-98d3-009572572227
2020/10/27 14:04:14 [INFO] Deleting WAFv2 WebACL 350bdc94-a9db-4432-b185-e0a8985c7237
2020/10/27 14:04:14 [INFO] Deleting WAFv2 WebACL 8274495f-4cc8-4048-89b3-ba4042299cd1
2020/10/27 14:04:15 [INFO] Deleting WAFv2 WebACL 10f48bcb-a2d4-4010-87d8-18563123b5d4
2020/10/27 14:04:18 [INFO] Deleting WAFv2 WebACL e5858fd2-05c4-4e40-a4e2-183966c34b37
2020/10/27 14:04:18 [INFO] Deleting WAFv2 WebACL b4cd0e12-f397-45f7-80be-e4d02cc32aa3
2020/10/27 14:04:20 [INFO] Deleting WAFv2 WebACL 95c9d7e2-906a-44c3-b2ed-0b703a544a3e
2020/10/27 14:04:21 [DEBUG] Running Sweeper (aws_wafv2_rule_group) in region (us-gov-west-1)
2020/10/27 14:04:21 [INFO] Deleting WAFv2 RuleGroup 1bbeff11-e180-4cdb-bccc-b1c90eb26bdb
2020/10/27 14:04:22 [DEBUG] Running Sweeper (aws_wafv2_ip_set) in region (us-gov-west-1)
2020/10/27 14:04:22 [INFO] Deleting WAFv2 IPSet c89e8c52-d686-4cda-9fb2-107a468a3f3e
2020/10/27 14:04:23 [INFO] Deleting WAFv2 IPSet 719109ca-9772-4021-973e-e96b69a709d6
2020/10/27 14:04:23 [DEBUG] Running Sweeper (aws_wafv2_regex_pattern_set) in region (us-gov-west-1)
2020/10/27 14:04:24 Sweeper Tests ran successfully:
  - aws_wafv2_ip_set
  - aws_wafv2_regex_pattern_set
  - aws_wafv2_web_acl
  - aws_wafv2_rule_group
ok    github.com/terraform-providers/terraform-provider-aws/aws 24.517s
```

Verification:

```console
$ aws wafv2 list-ip-sets --scope REGIONAL | jq '.IPSets | length'
0
$ aws wafv2 list-regex-pattern-sets --scope REGIONAL | jq '.RegexPatternSets | length'
0
$ aws wafv2 list-rule-groups --scope REGIONAL | jq '.RuleGroups | length'
0
$ aws wafv2 list-web-acls --scope REGIONAL | jq '.WebACLs | length'
0
```

### CODE REVIEW

File: aws/internal/service/wafv2/lister/list.go [hunk 1]
```diff
@@ -0,0 +1,3 @@
+//go:generate go run ../../../generators/listpages/main.go -function=ListIPSets,ListRegexPatternSets,ListRuleGroups,ListWebACLs -paginator=NextMarker github.com/aws/aws-sdk-go/service/wafv2
```
Comment (anGie44) [inline aws/internal/service/wafv2/lister/list.go:1]: 🙌

File: aws/resource_aws_wafv2_web_acl.go [hunk 2]
```diff
@@ -323,6 +324,10 @@ func resourceAwsWafv2WebACLDelete(d *schema.ResourceData, meta interface{}) erro
 		_, err = conn.DeleteWebACL(r)
 	}
 
+	if tfawserr.ErrCodeEquals(err, wafv2.ErrCodeWAFNonexistentItemException) {
```
Comment (anGie44) [inline aws/resource_aws_wafv2_web_acl.go:327]: 👍 👍

**Review by anGie44 — APPROVED** [review]
looks great!
