### PR TITLE
resource/aws_iam_user_policy: Fix updates with generated policy names and validate JSON

### LINKED ISSUE #781: Updating a aws_iam_user_policy causes multiple policies to be attached to an IAM user.
_This issue was originally opened by @poblahblahblah as hashicorp/terraform#14585. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version
```
git:(master*) $ tf -v
Terraform v0.9.5
```

### Affected Resource(s)
- aws_iam_user_policy

### Terraform Configuration Files
module: https://gist.github.com/poblahblahblah/1782bd221059bdeeaa63b814a2260f4a
module template: https://gist.github.com/poblahblahblah/dc324da5e066e9b8d3d92cb37d426219

first module invocation: https://gist.github.com/poblahblahblah/5e68aa9dc074661b8d0ce787cdd5a439

second module invocation: https://gist.github.com/poblahblahblah/71cfc70c165864c35f73c54e89f82670

### Debug Output
At this point the user does not exist, nor does a user policy.

debug output of first tf plan: https://gist.github.com/poblahblahblah/939fda5fae0ce31c7a7fb7c04f524bb0

debug output of first tf apply: https://gist.github.com/poblahblahblah/98e0e663ce86c036dea245eb5182ed2d (this failed because the user was created successfully, but it looks like terraform tried to attach the user policy too quickly, which also looks like a bug)

debug output of second tf apply: https://gist.github.com/poblahblahblah/c9e5de274afa6b77f5878b41f0f5ca37

At this point the user exists and there is a single user policy attached to it. I can confirm this in the UI and through the aws cli. Now I am going to add folders to the module invocation.

debug output of second tf plan: https://gist.github.com/poblahblahblah/a717f037a53d6d6a8c3cdac1caf746e5

debug output of last tf apply: https://gist.github.com/poblahblahblah/6c2e1394b12c62e8f875ba13460bb9f9

And now there are two policies attached. The original that terraform created, and the new one.

### Panic Output
N/A

### Expected Behavior
Terraform should have updated the existing user policy. There should only be a single user policy attached to the user.

### Actual Behavior
Terraform created a 2nd user policy, now there are two user policies attached to the user.

### Steps to Reproduce
I went through this in the Debug output section, but here it is again
1. Create a user and attach an inline policy (We did this via an attached module) and run terraform apply.
1. Update the inline policy (Again, we did this via the attached module) and run terraform apply.

### Important Factoids
We have tried this on three separate AWS accounts - our production account in us-east-1, our test account in us-east-1, and our AWS China account. All environments produced the same behavior.

### References
None that I could find.

### PR DESCRIPTION
**Pull request by bflad**
Replaces bugfix portions of #2450 
Closes #781

This also refactors the acceptance testing to check attributes, test policy updates for name/name_prefix/generated names, and starts to reuse test configurations where possible (e.g `testAccAWSUserConfig` from `aws_iam_user` tests).

```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSIAMUserPolicy'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSIAMUserPolicy -timeout 120m
=== RUN   TestAccAWSIAMUserPolicy_basic
--- PASS: TestAccAWSIAMUserPolicy_basic (14.98s)
=== RUN   TestAccAWSIAMUserPolicy_namePrefix
--- PASS: TestAccAWSIAMUserPolicy_namePrefix (15.72s)
=== RUN   TestAccAWSIAMUserPolicy_generatedName
--- PASS: TestAccAWSIAMUserPolicy_generatedName (13.47s)
=== RUN   TestAccAWSIAMUserPolicy_multiplePolicies
--- PASS: TestAccAWSIAMUserPolicy_multiplePolicies (25.55s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	69.761s
```

### CODE REVIEW

File: aws/resource_aws_iam_user_policy.go [hunk 1]
```diff
@@ -57,7 +59,9 @@ func resourceAwsIamUserPolicyPut(d *schema.ResourceData, meta interface{}) error
 	}
 
 	var policyName string
-	if v, ok := d.GetOk("name"); ok {
+	if d.Id() != "" {
```
Comment (radeksimko) [inline aws/resource_aws_iam_user_policy.go]: Nitpick: For folks who're not familiar with the significance of ID so using `!d.IsNewResource()` may be easier to understand for the reader here.

Comment (bflad) [reply aws/resource_aws_iam_user_policy.go]: Certainly easier to grok! Works like a charm 🚀 
```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSIAMUserPolicy'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSIAMUserPolicy -timeout 120m
=== RUN   TestAccAWSIAMUserPolicy_basic
--- PASS: TestAccAWSIAMUserPolicy_basic (15.01s)
=== RUN   TestAccAWSIAMUserPolicy_namePrefix
--- PASS: TestAccAWSIAMUserPolicy_namePrefix (15.87s)
=== RUN   TestAccAWSIAMUserPolicy_generatedName
--- PASS: TestAccAWSIAMUserPolicy_generatedName (12.56s)
=== RUN   TestAccAWSIAMUserPolicy_multiplePolicies
--- PASS: TestAccAWSIAMUserPolicy_multiplePolicies (26.00s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	69.492s
```
