### PR TITLE
resource/aws_rds_cluster: Prevent `InvalidParameterCombination` error with `engine_version` and `snapshot_identifier` on creation

### LINKED ISSUE #6157: bug version 1.40
issuse:
aws_rds_cluster.default: Failed to modify RDS Cluster (demo): InvalidParameterCombination: The specified new engine version is same as current version: 9.6.9
	status code: 400, request id: 04f08c7a-3aee-4754-96f1-b1e33bcacbe6

it happened when I trying to restore the last snapshot and the snapshot already configured to with rds engine version 9.6.9 it also happens when I trying to upgrade to 10.4.

so, for now, I back to version 1.39

### PR DESCRIPTION
**Pull request by bflad**
Fixes #6157 

This is a similar refactoring to the `aws_db_instance` resource that has occurred recently over a few iterations. The refactoring prevents a class of potential bugs related to unexpected update errors or an extraneous update after restoring from snapshot or S3. Instead we should be left with "requires two applies" type issues, which are more workable.

Changes:
* resource/aws_rds_cluster: Refactor Create function to call ModifyDBCluster directly instead of Update function

Output from acceptance testing:

```
--- PASS: TestAccAWSRDSCluster_BacktrackWindow (177.25s)
--- PASS: TestAccAWSRDSCluster_backupsUpdate (194.40s)
--- PASS: TestAccAWSRDSCluster_basic (123.91s)
--- PASS: TestAccAWSRDSCluster_DeletionProtection (195.88s)
--- PASS: TestAccAWSRDSCluster_encrypted (124.72s)
--- PASS: TestAccAWSRDSCluster_EncryptedCrossRegionReplication (1578.13s)
--- PASS: TestAccAWSRDSCluster_EngineMode (378.92s)
--- PASS: TestAccAWSRDSCluster_EngineMode_ParallelQuery (128.98s)
--- PASS: TestAccAWSRDSCluster_EngineVersion (137.07s)
--- PASS: TestAccAWSRDSCluster_EngineVersionWithPrimaryInstance (1117.06s)
--- PASS: TestAccAWSRDSCluster_generatedName (145.47s)
--- PASS: TestAccAWSRDSCluster_iamAuth (156.83s)
--- PASS: TestAccAWSRDSCluster_importBasic (128.64s)
--- PASS: TestAccAWSRDSCluster_kmsKey (143.46s)
--- PASS: TestAccAWSRDSCluster_missingUserNameCausesError (2.34s)
--- PASS: TestAccAWSRDSCluster_namePrefix (123.69s)
--- PASS: TestAccAWSRDSCluster_Port (297.06s)
--- PASS: TestAccAWSRDSCluster_s3Restore (1391.94s)
--- PASS: TestAccAWSRDSCluster_ScalingConfiguration (281.57s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier (364.76s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_DeletionProtection (490.59s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_EncryptedRestore (426.54s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_EngineMode_ParallelQuery (366.46s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_EngineMode_Provisioned (355.81s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_EngineVersion_Different (386.44s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_EngineVersion_Equal (407.85s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_PreferredBackupWindow (355.70s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_PreferredMaintenanceWindow (386.74s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_Tags (364.61s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_VpcSecurityGroupIds (362.35s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_VpcSecurityGroupIds_Tags (463.75s)
--- PASS: TestAccAWSRDSCluster_takeFinalSnapshot (186.68s)
--- PASS: TestAccAWSRDSCluster_updateCloudwatchLogsExports (163.99s)
--- PASS: TestAccAWSRDSCluster_updateIamRoles (143.56s)
--- PASS: TestAccAWSRDSCluster_updateTags (163.35s)
```

### CODE REVIEW

File: aws/resource_aws_rds_cluster.go [hunk 1]
```diff
@@ -455,23 +477,19 @@ func resourceAwsRDSClusterCreate(d *schema.ResourceData, meta interface{}) error
...
 
-		if attr, ok := d.GetOk("db_cluster_parameter_group_name"); ok {
-			opts.DBClusterParameterGroupName = aws.String(attr.(string))
-		}
-
-		if _, ok := d.GetOk("backup_retention_period"); ok {
-			clusterUpdate = true
+		if attr := d.Get("vpc_security_group_ids").(*schema.Set); attr.Len() > 0 {
+			opts.VpcSecurityGroupIds = expandStringList(attr.List())
+			// requiresModifyDbCluster = true
```
Comment (tombuildsstuff) [inline aws/resource_aws_rds_cluster.go]: is this intentionally commented out?

Comment (bflad) [reply aws/resource_aws_rds_cluster.go]: Great catch! For some reason the old code had it (so it was being set both during create and calling an update) and I was experimenting 🔬 -- experiment was a success! I'll remove it. 👍

**Comment by bflad** [comment]
This has been released in [version 1.43.1 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1431-november-09-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
