### PR TITLE
Fix TestAccAWSELB_swap_subnets

### LINKED ISSUE #14803: resource/aws_elb: TestAccAWSELB_swap_subnets Test Failures
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `TestAccAWSELB_swap_subnets` acceptance test is consistently failing with:

```
=== CONT  TestAccAWSELB_swap_subnets
TestAccAWSELB_swap_subnets: resource_aws_elb_test.go:413: Step 2/2 error: terraform failed: exit status 1
stderr:
Error: Invalid multi-line string
on config854398356/terraform_plugin_test.tf line 36, in resource "aws_subnet" "public_b_one":
36:
37:
Quoted strings may not be split over multiple lines. To produce a multi-line
string, either use the \n escape to represent a newline character or use the
"heredoc" multi-line template syntax.
Error: Unterminated template string
on config854398356/terraform_plugin_test.tf line 36, in resource "aws_subnet" "public_b_one":
36:
37:
No closing marker was found for the string.
Error: Invalid multi-line string
on config854398356/terraform_plugin_test.tf line 37, in resource "aws_subnet" "public_b_one":
37:
38:
Quoted strings may not be split over multiple lines. To produce a multi-line
string, either use the \n escape to represent a newline character or use the
"heredoc" multi-line template syntax.
Error: Invalid multi-line string
....
```

It is likely there was an errant update to the test configuration as part of our Terraform 0.12 syntax updates.

### Affected Resource

* aws_elb

### References

* [Contributing Guide on Running/Writing Acceptance Testing](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/contributing/running-and-writing-acceptance-tests.md)

### PR DESCRIPTION
**Pull request by SatoruItaya**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #14803 

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSELB_swap_subnets'
--- PASS: TestAccAWSELB_swap_subnets (169.42s)
...
```

### CODE REVIEW

File: aws/resource_aws_elb_test.go [hunk 1]
```diff
@@ -1876,7 +1876,7 @@ resource "aws_subnet" "public_a_two" {
 }
 
 resource "aws_elb" "test" {
-  name = "terraform-asg-deployment-example"
+  name = "terraform-asg-deployment-1-1"
```
Comment (bflad) [inline aws/resource_aws_elb_test.go:1879]: Since [`name` is a `ForceNew` attribute](https://github.com/terraform-providers/terraform-provider-aws/blob/cd9ca85fbca8e7dc2be953231b435fd29f1b1394/aws/resource_aws_elb.go#L35-L42), we do not want the resource to be recreated between test steps.

```suggestion
  name = "terraform-asg-deployment-example"
```

File: aws/resource_aws_elb_test.go [hunk 2]
```diff
@@ -1952,7 +1952,7 @@ resource "aws_subnet" "public_a_two" {
 }
 
 resource "aws_elb" "test" {
-  name = "terraform-asg-deployment-example"
+  name = "terraform-asg-deployment-2-1"
```
Comment (bflad) [inline aws/resource_aws_elb_test.go:1955]: Since [`name` is a `ForceNew` attribute](https://github.com/terraform-providers/terraform-provider-aws/blob/cd9ca85fbca8e7dc2be953231b435fd29f1b1394/aws/resource_aws_elb.go#L35-L42), we do not want the resource to be recreated between test steps.

```suggestion
  name = "terraform-asg-deployment-example"
```

**Comment by SatoruItaya** [comment]
@bflad 
Thanks for your review, and I'm sorry that I misunderstand the intention of this test.
But the test fails if ELB name is consistent between the two test configurations.
The error message is as following:
```
resource_aws_elb_test.go:413: Step 1/2 error: terraform failed: exit status 1

stderr:

Error: Error creating ELB: DuplicateLoadBalancerName: Load Balancer named terraform-asg-deployment-example already exists and it is configured with different parameters.
       status code: 400, request id: 8139a082-7eb9-4e7a-9988-3e47dd4ac5eb

--- FAIL: TestAccAWSELB_swap_subnets (52.80s)
```

So, are there any other points to fix?

**Comment by bflad** [comment]
@SatoruItaya does your testing environment already have a `terraform-asg-deployment-example` ELB? If so, it will need to be removed before running the test. Although in this case, it might be easiest to just remove the `name` argument from the two configurations since the `aws_elb` resource supports automatically randomizing the naming on creation if none is provided. Since `resource "aws_elb" "test"` matches between the two configurations, the ELB won't be recreated between test steps.

Otherwise if we wanted to ensure the naming followed a specific pattern, it is a little more involved and the [Contributing Guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/contributing/running-and-writing-acceptance-tests.md#randomized-naming) gets into those details. Since it does not matter too much for the purposes of this specific test though, removing the `name` arguments for these two configurations is fine. 👍

**Comment by SatoruItaya** [comment]
@bflad 
As you said, my environment had ELB whose name was `terraform-asg-deployment-example`.
After removing it, the test has succeeded.
```
--- PASS: TestAccAWSELB_swap_subnets (241.71s)
```
Thanks for your advice.
