### PR TITLE
Retry LB listener methods after timeout

### LINKED ISSUE #8025: aws_lb_listener read taking longer than 1 minute timeout
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I regularly have `terraform plan` fail because it can't refresh an `aws_lb_listener` in a minute. I don't know if this matters but we have a lot of listeners on our account, 16 ALBs, 21 NLBs, and 90 ELB classic (not sure if that affects these sort of describes or not).

When I run 
```
time aws elbv2 describe-listeners --listener-arn arn:aws:elasticloadbalancing:us-east-1:......
```
it almost always completes in less than a second. And most of our `terraform plan` runs work too, but sometimes it doesn't and gets this error.

It'd be nice to have some way to make this longer than a minute

### Terraform Version

terraform 0.11.11
aws provider 1.60.0

### Affected Resource(s)

* aws_lb_listener

### Terraform Configuration Files

Nothing special, this is from the example from [the aws_lb_listener docs](https://www.terraform.io/docs/providers/aws/r/lb_listener.html). I'm not sure that anything in the configuration is causing the problems.

```hcl
resource "aws_lb" "front_end" {
  # ...
}

resource "aws_lb_target_group" "front_end" {
  # ...
}

resource "aws_lb_listener" "front_end" {
  load_balancer_arn = "${aws_lb.front_end.arn}"
  port              = "443"
  protocol          = "HTTPS"
  ssl_policy        = "ELBSecurityPolicy-2016-08"
  certificate_arn   = "arn:aws:iam::187416307283:server-certificate/test_cert_rab3wuqwgja25ct3n4jdj2tzu4"

  default_action {
    type             = "forward"
    target_group_arn = "${aws_lb_target_group.front_end.arn}"
  }
}
```
### Expected Behavior

`terraform plan` or `terraform refresh` can run without timing out

### Actual Behavior

```
Error: Error refreshing state: 1 error(s) occurred:

* aws_lb_listener.foo: 1 error(s) occurred:

* aws_lb_listener.foo: aws_lb_listener.foo: Error retrieving Listener: timeout while waiting for state to become 'success' (timeout: 1m0s)
```

### Steps to Reproduce

1. have the intermittent aws weirdness that makes this slow, _but only sometimes_
2. `terraform plan`

### Important Factoids

When we are running our `terraform plan` we are often running multiple terraform plans, for different workspaces (from different working directories), in parallel. I don't know if the combination of so many describe-listeners requests happening at once is the problem, but it's very difficult to reproduce.

### References

The line of code in question in the `aws_lb_listener` resource:
https://github.com/terraform-providers/terraform-provider-aws/blob/v1.60.0/aws/resource_aws_lb_listener.go#L517

* #2456
* #5167 - PR to fix #2456 where @bflad said in the review that the timeout for read should be hardcoded to 1 minute.

### PR DESCRIPTION
**Pull request by ryndaniels**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Fixes #8025

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
Adds a final retry to LB Listener requests if the requests originally timed out
```

Output from acceptance testing:

```
$ make testacc TESTARGS="-run=TestAccAWSLBListener"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSLBListener -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSLBListenerRule_basic
=== PAUSE TestAccAWSLBListenerRule_basic
=== RUN   TestAccAWSLBListenerRuleBackwardsCompatibility
=== PAUSE TestAccAWSLBListenerRuleBackwardsCompatibility
=== RUN   TestAccAWSLBListenerRule_redirect
=== PAUSE TestAccAWSLBListenerRule_redirect
=== RUN   TestAccAWSLBListenerRule_fixedResponse
=== PAUSE TestAccAWSLBListenerRule_fixedResponse
=== RUN   TestAccAWSLBListenerRule_updateRulePriority
=== PAUSE TestAccAWSLBListenerRule_updateRulePriority
=== RUN   TestAccAWSLBListenerRule_changeListenerRuleArnForcesNew
=== PAUSE TestAccAWSLBListenerRule_changeListenerRuleArnForcesNew
=== RUN   TestAccAWSLBListenerRule_multipleConditionThrowsError
=== PAUSE TestAccAWSLBListenerRule_multipleConditionThrowsError
=== RUN   TestAccAWSLBListenerRule_priority
=== PAUSE TestAccAWSLBListenerRule_priority
=== RUN   TestAccAWSLBListenerRule_cognito
=== PAUSE TestAccAWSLBListenerRule_cognito
=== RUN   TestAccAWSLBListenerRule_oidc
=== PAUSE TestAccAWSLBListenerRule_oidc
=== RUN   TestAccAWSLBListenerRule_Action_Order
=== PAUSE TestAccAWSLBListenerRule_Action_Order
=== RUN   TestAccAWSLBListenerRule_Action_Order_Recreates
=== PAUSE TestAccAWSLBListenerRule_Action_Order_Recreates
=== RUN   TestAccAWSLBListener_basic
=== PAUSE TestAccAWSLBListener_basic
=== RUN   TestAccAWSLBListener_BackwardsCompatibility
=== PAUSE TestAccAWSLBListener_BackwardsCompatibility
=== RUN   TestAccAWSLBListener_https
=== PAUSE TestAccAWSLBListener_https
=== RUN   TestAccAWSLBListener_Protocol_Tls
=== PAUSE TestAccAWSLBListener_Protocol_Tls
=== RUN   TestAccAWSLBListener_redirect
=== PAUSE TestAccAWSLBListener_redirect
=== RUN   TestAccAWSLBListener_fixedResponse
=== PAUSE TestAccAWSLBListener_fixedResponse
=== RUN   TestAccAWSLBListener_cognito
=== PAUSE TestAccAWSLBListener_cognito
=== RUN   TestAccAWSLBListener_oidc
=== PAUSE TestAccAWSLBListener_oidc
=== RUN   TestAccAWSLBListener_DefaultAction_Order
=== PAUSE TestAccAWSLBListener_DefaultAction_Order
=== RUN   TestAccAWSLBListener_DefaultAction_Order_Recreates
=== PAUSE TestAccAWSLBListener_DefaultAction_Order_Recreates
=== CONT  TestAccAWSLBListenerRule_basic
=== CONT  TestAccAWSLBListener_DefaultAction_Order_Recreates
=== CONT  TestAccAWSLBListener_basic
=== CONT  TestAccAWSLBListener_redirect
=== CONT  TestAccAWSLBListenerRule_Action_Order_Recreates
=== CONT  TestAccAWSLBListener_DefaultAction_Order
=== CONT  TestAccAWSLBListener_Protocol_Tls
=== CONT  TestAccAWSLBListener_https
=== CONT  TestAccAWSLBListener_BackwardsCompatibility
=== CONT  TestAccAWSLBListenerRule_Action_Order
=== CONT  TestAccAWSLBListenerRule_oidc
=== CONT  TestAccAWSLBListenerRule_cognito
=== CONT  TestAccAWSLBListenerRule_priority
=== CONT  TestAccAWSLBListenerRule_multipleConditionThrowsError
=== CONT  TestAccAWSLBListenerRule_changeListenerRuleArnForcesNew
=== CONT  TestAccAWSLBListenerRule_updateRulePriority
=== CONT  TestAccAWSLBListenerRule_fixedResponse
=== CONT  TestAccAWSLBListenerRule_redirect
=== CONT  TestAccAWSLBListenerRuleBackwardsCompatibility
=== CONT  TestAccAWSLBListener_cognito
--- PASS: TestAccAWSLBListenerRule_multipleConditionThrowsError (3.36s)
=== CONT  TestAccAWSLBListener_oidc
--- PASS: TestAccAWSLBListenerRuleBackwardsCompatibility (226.95s)
=== CONT  TestAccAWSLBListener_fixedResponse
--- PASS: TestAccAWSLBListenerRule_Action_Order_Recreates (228.69s)
--- PASS: TestAccAWSLBListener_cognito (232.67s)
--- PASS: TestAccAWSLBListener_BackwardsCompatibility (233.78s)
--- PASS: TestAccAWSLBListener_redirect (233.94s)
--- PASS: TestAccAWSLBListener_https (234.14s)
--- PASS: TestAccAWSLBListener_DefaultAction_Order (234.72s)
--- PASS: TestAccAWSLBListenerRule_oidc (235.91s)
--- PASS: TestAccAWSLBListenerRule_cognito (241.32s)
--- PASS: TestAccAWSLBListener_basic (243.72s)
--- PASS: TestAccAWSLBListener_DefaultAction_Order_Recreates (245.55s)
--- PASS: TestAccAWSLBListenerRule_Action_Order (249.00s)
--- PASS: TestAccAWSLBListener_oidc (249.84s)
--- PASS: TestAccAWSLBListenerRule_fixedResponse (257.92s)
--- PASS: TestAccAWSLBListenerRule_changeListenerRuleArnForcesNew (295.45s)
--- PASS: TestAccAWSLBListenerRule_updateRulePriority (306.47s)
--- PASS: TestAccAWSLBListenerRule_redirect (313.82s)
--- PASS: TestAccAWSLBListenerRule_basic (325.63s)
--- PASS: TestAccAWSLBListener_Protocol_Tls (353.97s)
--- PASS: TestAccAWSLBListener_fixedResponse (250.96s)
--- PASS: TestAccAWSLBListenerRule_priority (557.14s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       558.022s
```

### CODE REVIEW

File: aws/resource_aws_lb_listener.go [hunk 1]
```diff
@@ -493,6 +493,14 @@ func resourceAwsLbListenerCreate(d *schema.ResourceData, meta interface{}) error
 		return nil
 	})
 
+	if isResourceTimeoutError(err) {
```
Comment (bflad) [inline aws/resource_aws_lb_listener.go]: When the error is a `resource.TimeoutError` and we hit this condition, its important that we reset the error object so the later error checking logic is not triggered. Otherwise as written this will work like the following:

1. `resource.Retry` sets top level `err` to `resource.TimeoutError`
1. `isResourceTimeoutError(err)` conditional runs `CreateListener` again (great!)
1. If `CreateListener` returns an error, it returns the error
1. If `CreateListener` doesn't return an error, the `isResourceTimeoutError()` conditional exits, but the below error check (`if err != nil`) will still have the original `resource.TimeoutError` error, so it will still return an error

The trick here is using a direct `=` assignment in Go instead of `:=`

This allows us to simplify this logic like the following:

```go
	// ... new logic here ...
	if isResourceTimeoutError(err) {
		_, err = elbconn.CreateListener(params)
	}

	// ... existing error handling below here ...
	if err != nil {
		return fmt.Errorf("Error creating LB Listener: %s", err)
	}

	// ... existing happy path ...
```

You'll now get the outcome you're expecting both ways when `resource.Retry` has a timeout error:

1. `resource.Retry` sets top level `err` to `resource.TimeoutError`
1. `isResourceTimeoutError(err)` conditional runs `CreateListener` again (great!)
1. If `CreateListener` returns an error, it resets the top level error object and the below error check (`if err != nil`) will return _that_ error
1. If `CreateListener` doesn't return an error, the top level error object is reset to `nil` and the below error check (`if err != nil`) will not trigger so the resource will continue on its merry way on the happy path

Hope this helps!

**Comment by bflad** [comment]
I'd also be careful with the PR comment `Fixes #8025` which will close the originating issue -- there are a few hundred of these to clean up. 😄
