### PR TITLE
Fixed remnant CloudWatch Dashboards on each dashboard rename

### LINKED ISSUE #9782: Remnant CloudWatch Dashboards persist on each dashboard rename
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
v0.11.13
```

### Affected Resource(s)

* aws_cloudwatch_dashboard

### Terraform Configuration Files

```hcl
resource "aws_cloudwatch_dashboard" "example" {
  dashboard_name = "dashboard-name-before"

  dashboard_body = <<EOF
    {
      ... some JSON
    }
  EOF
}

```

### Debug Output

N/A - no relevant debug output - the bug only presents itself in the AWS Console

### Panic Output

N/A - no panics

### Expected Behavior

On update of the dashboard resource's `dashboard_name`
✅ The dashboard with the new name should be deployed to AWS
✅ The dashboard with the original name should be destroyed in AWS

### Actual Behavior

On update of the dashboard resource's `dashboard_name`
✅ The dashboard with the new name is deployed to AWS
❌ The dashboard with the original name is not destroyed in AWS

### Steps to Reproduce

1. Deploy a dashboard with some arbitrary `dashboard_body` JSON
2. Check the dashboard exists and has the correct name.
  image
3. Check the terraform state reflects the deployed infrastructure
  ``` json
  {
    "version": 3,
    "terraform_version": "0.11.13",
    "serial": 1,
    "lineage": "cc8370ef-4c74-de56-db09-db767317bb9c",
    "modules": [
      {
        "path": [
          "root"
        ],
        "outputs": {},
        "resources": {
          "aws_cloudwatch_dashboard.main": {
            "type": "aws_cloudwatch_dashboard",
            "depends_on": [],
            "primary": {
              "id": "dashboard-name-before",
              "attributes": {
                "dashboard_arn": "arn:aws:cloudwatch::<ACCOUNT_ID>:dashboard/dashboard-name-before",
                "dashboard_body": " { ... Dashboard Body JSON here... } ",
                "dashboard_name": "dashboard-name-before",
                "id": "dashboard-name-before"
              },
              "meta": {},
              "tainted": false
            },
            "deposed": [],
            "provider": "provider.aws"
          }
        },
        "depends_on": []
      }
    ]
  }
  ```
4. Once deployed, change only the `dashboard_name` property
5. Run `terraform plan` to see the "update-in-place" output:
  ```
  ~ aws_cloudwatch_dashboard.main
      dashboard_name: "dashboard-name-before" => "dashboard-name-after"

  Plan: 0 to add, 1 to change, 0 to destroy.
  ```
6. Run `terraform apply`
7. Check the renamed dashboard exists and has the correct name.
**8. Confirm that the old dashboard still exists**
  image
**9. Confirm that only the new dashboard exists in the terraform state**
  ``` json
  {
    "version": 3,
    "terraform_version": "0.11.13",
    "serial": 2,
    "lineage": "cc8370ef-4c74-de56-db09-db767317bb9c",
    "modules": [
      {
        "path": [
          "root"
        ],
        "outputs": {},
        "resources": {
          "aws_cloudwatch_dashboard.main": {
            "type": "aws_cloudwatch_dashboard",
            "depends_on": [],
            "primary": {
              "id": "dashboard-name-after",
              "attributes": {
                "dashboard_arn": "arn:aws:cloudwatch::<ACCOUNT_ID>:dashboard/dashboard-name-after",
                "dashboard_body": " { ... Dashboard Body JSON here... } ",
                "dashboard_name": "dashboard-name-after",
                "id": "dashboard-name-after"
              },
              "meta": {},
              "tainted": false
            },
            "deposed": [],
            "provider": "provider.aws"
          }
        },
        "depends_on": []
      }
    ]
  }
  ```

### Important Factoids

N/A - reproduced on personal and work account

### References

* N/A

### PR DESCRIPTION
**Pull request by JamesPeiris**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #9782

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Output from acceptance testing:

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSCloudWatchDashboard_updateName'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSCloudWatchDashboard_updateName -timeout 120m
=== RUN   TestAccAWSCloudWatchDashboard_updateName
=== PAUSE TestAccAWSCloudWatchDashboard_updateName
=== CONT  TestAccAWSCloudWatchDashboard_updateName
--- PASS: TestAccAWSCloudWatchDashboard_updateName (35.34s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	35.384s
...
```

FYI:
```
$ make testacc TESTARGS='-run=TestAccXXX'
```
Without the `TEST=./aws` env var also set results in:
```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSCloudWatchDashboard_updateName -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
```
Which hangs until killed.

Thanks in advance!

### CODE REVIEW

**Comment by JamesPeiris** [comment]
Hello @bflad 👋

Thank you for taking the time to look at this, I appreciate that your time must be spread quite thinly!

I have amended the implementation as per your suggestion, which I have tested and works as expected - would you be able to take another look at this please?

Thanks again, and happy new year 🎉

File: aws/resource_aws_cloudwatch_dashboard_test.go [hunk 1]
```diff
@@ -75,6 +75,36 @@ func TestAccAWSCloudWatchDashboard_update(t *testing.T) {
...
+	rInt2 := acctest.RandInt()
+	resource.ParallelTest(t, resource.TestCase{
+		PreCheck:     func() { testAccPreCheck(t) },
+		Providers:    testAccProviders,
+		CheckDestroy: testAccCheckAWSCloudWatchDashboardDestroy,
+		Steps: []resource.TestStep{
+			{
+				Config: testAccAWSCloudWatchDashboardConfig(rInt),
+				Check: resource.ComposeTestCheckFunc(
+					testAccCheckCloudWatchDashboardExists("aws_cloudwatch_dashboard.foobar", &dashboard),
```
Comment (bflad) [inline aws/resource_aws_cloudwatch_dashboard_test.go]: Likely copy-paste from the earlier iteration of this pull request, the test configuration resource name is `aws_cloudwatch_dashboard.test`:

https://github.com/terraform-providers/terraform-provider-aws/blob/e1fc857056e66b257520f73ca5e22dc6facaebef/aws/resource_aws_cloudwatch_dashboard_test.go#L159

Otherwise, this test causes this error:

```
--- FAIL: TestAccAWSCloudWatchDashboard_updateName (5.64s)
    testing.go:640: Step 0 error: Check failed: Check 1/3 error: Not found: aws_cloudwatch_dashboard.foobar
```

Since it is a small testing fix, will do so on merge. 👍

Comment (JamesPeiris) [reply aws/resource_aws_cloudwatch_dashboard_test.go]: Gah, I was so close. Thanks!
