### PR TITLE
Detecting drift on aws_lb_target_group_attachment

### LINKED ISSUE #5605: aws_lb_target_group_attachment does not register the EC2 instance to the target group after manually deregistered
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.8
+ provider.aws v1.32.0
+ provider.template v1.0.0

### Affected Resource(s)

* aws_lb_target_group_attachment

### Terraform Configuration Files

```hcl
resource "aws_lb" "mysetup" {
  name     = "${var.aws["env"]}-mysetup-alb"
  internal           = true 
  load_balancer_type = "application"
  security_groups = ["${var.mysetup["mysetup_lb_sg"]}"]
  subnets  = "${var.subnet_pub_id}"

  enable_deletion_protection = false 

}

resource "aws_lb_target_group" "mysetup" {
  name     = "${var.aws["env"]}-mysetup-lb-tg"
  port     = 3000 
  protocol = "HTTP"
  vpc_id   = "${var.aws["vpc_id"]}"

  deregistration_delay = 20
  target_type = "instance"

  health_check = {
    interval = 7 
    protocol = "HTTP"
    path = "/"
    port = "traffic-port" 
    timeout = 5
    healthy_threshold = 5
    unhealthy_threshold = 2
    matcher = "200,201" 
  }

}


resource "aws_lb_listener" "mysetup" {
  load_balancer_arn = "${aws_lb.mysetup.arn}"
  port              = "3000"
  protocol          = "HTTP"

  default_action {
    target_group_arn = "${aws_lb_target_group.mysetup.arn}"
    type             = "forward"
  }


}

data "template_file" "mysetup_nginx" {
  template = "${file("./cloudinit/mysetup.sh")}"
  vars {
    PUB_KEY = "${file("./cloudinit/public-keys")}"
  }
}


resource "aws_lb_target_group_attachment" "mysetup_grp1" {
  count = "${aws_instance.mysetup_grp1.count}" 
  target_group_arn = "${aws_lb_target_group.mysetup.arn}"
  target_id        = "${element(aws_instance.mysetup_grp1.*.id, count.index)}"
  port             = 3000

}

resource "aws_instance" "mysetup_grp1" {
  count = "${var.mysetup["mysetup_ec2_node_grp1_count"]}"
  ami = "${var.mysetup["mysetup_ec2_ami"]}"
  instance_type        = "${var.mysetup["mysetup_ec2_type"]}"
  user_data            = "${data.template_file.mysetup_nginx.rendered}"
  key_name             = "${var.mysetup["keypair"]}"
  iam_instance_profile = "${var.mysetup["mysetup_ec2_profile"]}"

  vpc_security_group_ids = ["${var.mysetup["mysetup_ec2_sg"]}"]
  subnet_id = "${element(var.subnet_pub_id, count.index)}"
  associate_public_ip_address = true
  root_block_device {
    delete_on_termination = true
    volume_type = "gp2"
    volume_size = 8 
  }

}

```

### Expected Behavior

`terraform plan` should shows there are changes of the resources

### Actual Behavior

`terraform plan`  shows there are no changes of the resources

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan` shows no changes of the resources
3. remove an EC2 instances from the target group
4. `terraform plan` still shows no changes of the resources

### PR DESCRIPTION
**Pull request by Jamian**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #5605

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_lb_target_group_attachment: perform drift detection on lb target group attachments. Target attachments defined in TF that are either unregistered or in the process of being drained will be raised in a plan/apply. Targets that are registered but *not in use* will not be picked up.
```

Output from acceptance testing:

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSLBTargetGroupAttachment'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSLBTargetGroupAttachment -timeout 120m
=== RUN   TestAccAWSLBTargetGroupAttachment_basic
=== PAUSE TestAccAWSLBTargetGroupAttachment_basic
=== RUN   TestAccAWSLBTargetGroupAttachment_missingAttachmentDrift
=== PAUSE TestAccAWSLBTargetGroupAttachment_missingAttachmentDrift
=== RUN   TestAccAWSLBTargetGroupAttachmentBackwardsCompatibility
=== PAUSE TestAccAWSLBTargetGroupAttachmentBackwardsCompatibility
=== RUN   TestAccAWSLBTargetGroupAttachment_withoutPort
=== PAUSE TestAccAWSLBTargetGroupAttachment_withoutPort
=== CONT  TestAccAWSLBTargetGroupAttachment_basic
=== CONT  TestAccAWSLBTargetGroupAttachment_withoutPort
=== CONT  TestAccAWSLBTargetGroupAttachmentBackwardsCompatibility
=== CONT  TestAccAWSLBTargetGroupAttachment_missingAttachmentDrift
--- PASS: TestAccAWSLBTargetGroupAttachment_missingAttachmentDrift (107.79s)
--- PASS: TestAccAWSLBTargetGroupAttachment_withoutPort (109.34s)
--- PASS: TestAccAWSLBTargetGroupAttachmentBackwardsCompatibility (109.73s)
--- PASS: TestAccAWSLBTargetGroupAttachment_basic (111.81s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	111.866s
...
```

### CODE REVIEW

File: aws/resource_aws_lb_target_group_attachment.go [hunk 1]
```diff
@@ -2,12 +2,11 @@ package aws
 
 import (
 	"fmt"
-	"log"
-
 	"github.com/aws/aws-sdk-go/aws"
 	"github.com/aws/aws-sdk-go/service/elbv2"
 	"github.com/hashicorp/terraform/helper/resource"
 	"github.com/hashicorp/terraform/helper/schema"
+	"log"
```
Comment (bflad) [inline aws/resource_aws_lb_target_group_attachment.go]: Nit: Please revert this change. The preferred style for Go `imports` is a section of all standard library imports at the top, a new line, and section(s) of third party imports. Each section alphabetized. See also [Go CodeReviewComments](https://github.com/golang/go/wiki/CodeReviewComments#imports) and tooling like `goimports` that will automatically handle this in your editor. 👍

File: aws/resource_aws_lb_target_group_attachment_test.go [hunk 2]
```diff
@@ -3,14 +3,13 @@ package aws
...
 	"fmt"
-	"strconv"
-	"testing"
-
 	"github.com/aws/aws-sdk-go/aws"
 	"github.com/aws/aws-sdk-go/service/elbv2"
 	"github.com/hashicorp/terraform/helper/acctest"
 	"github.com/hashicorp/terraform/helper/resource"
 	"github.com/hashicorp/terraform/terraform"
+	"strconv"
```
Comment (bflad) [inline aws/resource_aws_lb_target_group_attachment_test.go]: Nit: Same here -- please revert this change. The preferred style for Go `imports` is a section of all standard library imports at the top, a new line, and section(s) of third party imports. Each section alphabetized. See also [Go CodeReviewComments](https://github.com/golang/go/wiki/CodeReviewComments#imports) and tooling like `goimports` that will automatically handle this in your editor. 👍

File: aws/resource_aws_lb_target_group_attachment.go [hunk 3]
```diff
@@ -140,6 +140,19 @@ func resourceAwsLbAttachmentRead(d *schema.ResourceData, meta interface{}) error
 		return fmt.Errorf("Error reading Target Health: %s", err)
 	}
 
+	for _, targetDesc := range resp.TargetHealthDescriptions {
+		if *targetDesc.Target.Id == d.Get("target_id").(string) {
```
Comment (bflad) [inline aws/resource_aws_lb_target_group_attachment.go]: To prevent potential panics we should perform `nil` checking and use the AWS Go SDK provided conversion function instead of directly dereferencing, e.g.

```suggestion
		if targetDesc == nil && targetDesc.Target == nil {
			continue
		}

		if aws.StringValue(targetDesc.Target.Id) == d.Get("target_id").(string) {
```

File: aws/resource_aws_lb_target_group_attachment.go [hunk 4]
```diff
@@ -140,6 +140,19 @@ func resourceAwsLbAttachmentRead(d *schema.ResourceData, meta interface{}) error
...
+			// These will catch targets being removed by hand (draining as we plan) or that have been removed for a while
+			// without trying to re-create ones that are just not in use. For example, a target can be `unused` if the
+			// target group isnt assigned to anything, a scenario where we don't want to continuously recreate the resource.
+			if (*targetDesc.TargetHealth.Reason == "Target.NotRegistered") || (*targetDesc.TargetHealth.Reason == "Target.DeregistrationInProgress") {
```
Comment (bflad) [inline aws/resource_aws_lb_target_group_attachment.go]: Similarly here to prevent potential panics. The AWS Go SDK also provides [constants](https://docs.aws.amazon.com/sdk-for-go/api/service/elbv2/#pkg-constants) we can use instead of our own strings 👍 

```suggestion
			if targetDesc.TargetHealth == nil {
				continue
			}

			reason := aws.StringValue(targetDesc.TargetHealth.Reason)
			if reason == elbv2.TargetHealthReasonEnumTargetNotRegistered || reason == elbv2.TargetHealthReasonEnumTargetDeregistrationInProgress {
```

**Comment by Jamian** [comment]
@bflad I've added updated for the requested changes. Big thanks for the keen review and feedback, this is my first foray into Go.

**Comment by bflad** [comment]
This appears to resolve #5605 so I'm going to mark this pull request description to automatically close the issue.
