### PR TITLE
Validate vpc cidr block

### LINKED ISSUE #6567: Terraform plan does not validate aws.vpc.cidr_block
_This issue was originally opened by @gfysaris as hashicorp/terraform#19452. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version

```
Terraform v0.11.10
+ provider.aws v1.46.0
```

### Terraform Configuration Files

```hcl
resource "aws_vpc" "XXX" {
  cidr_block           = "10.0.0.0/8"
  enable_dns_support   = true
  enable_dns_hostnames = true

  tags {
    Name = "XXX"
  }
}
```

### Expected Behavior

```
Error: Error generating plan
1 error(s) occurred:
* aws_vpc.XXX: 1 error(s) occurred:
* aws_vpc.XXX: Error creating VPC: InvalidVpc.Range: The CIDR '10.0.0.0/8' is invalid.
	status code: 400, request id: 0123456789
```

### Actual Behavior

```
  + aws_vpc.XXX
      id:                                          <computed>
      arn:                                         <computed>
      assign_generated_ipv6_cidr_block:            "false"
      cidr_block:                                  "10.0.0.0/8"
      default_network_acl_id:                      <computed>
      default_route_table_id:                      <computed>
      default_security_group_id:                   <computed>
      dhcp_options_id:                             <computed>
      enable_classiclink:                          <computed>
      enable_classiclink_dns_support:              <computed>
      enable_dns_hostnames:                        "true"
      enable_dns_support:                          "true"
      instance_tenancy:                            "default"
      ipv6_association_id:                         <computed>
      ipv6_cidr_block:                             <computed>
      main_route_table_id:                         <computed>
      tags.%:                                      "1"
      tags.Name:                                   "XXX"


Plan: 1 to add, 0 to change, 0 to destroy.
```

### Steps to Reproduce

```
terraform init
terraform apply
```

### Additional Context

```
 Block sizes must be between a /16 netmask and /28 netmask.
```

### PR DESCRIPTION
**Pull request by sunilkumarmohanty**
Fixes #6567

Changes proposed in this pull request:

* Validates VPC CIDR block sizes to be between 16 and 28

Test run against the validators.go

### CODE REVIEW

File: aws/resource_aws_vpc.go [hunk 1]
```diff
@@ -33,7 +33,7 @@ func resourceAwsVpc() *schema.Resource {
 				Type:         schema.TypeString,
 				Required:     true,
 				ForceNew:     true,
-				ValidateFunc: validateCIDRNetworkAddress,
+				ValidateFunc: validateVPCCIDRNetworkAddress,
```
Comment (bflad) [inline aws/resource_aws_vpc.go]: We should use the available Terraform provider SDK validation function instead of implementing our own. 😄 
 https://godoc.org/github.com/hashicorp/terraform/helper/validation#CIDRNetwork

https://github.com/hashicorp/terraform/blob/9ada53547faa5b913c8b95d07bb47c0dbad476c5/helper/validation/validation.go#L204-L236

```suggestion
				ValidateFunc: validation.CIDRNetwork(16, 28),
```

Comment (sunilkumarmohanty) [reply aws/resource_aws_vpc.go]: Thanks @bflad 👍

**Comment by bflad** [comment]
This was released (4 days ago) in [version 1.47.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1470-november-26-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
