### PR TITLE
d/ecr_repository- make `registry_id` optional to allow to filter by account + add missing attributes

### LINKED ISSUE #14327: The `aws_ecr_repository` data source doesn't work across accounts
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `aws_ecr_repository` data source doesn't work for cross account repositories, as it has no way to specify the account ID. The `aws_ecr_image` object does allow this, but doesn't have a way to get the repository out of it.

### New or Affected Resource(s)

* aws_ecr_repository

### Potential Terraform Configuration

```hcl
data "aws_ecr_repository" "service" {
  name = "ecr-repository"
  registry_id = "394802378"
}
```

### References

* #9947

### PR DESCRIPTION
**Pull request by DrFaust92**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #14327

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
data_source_aws_ecr_repository - make `registry_id` optional to allow to filter by account
data_source_aws_ecr_repository - add `image_scanning_configuration`, `image_tag_mutability` attributes
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSEcrDataSource_'
--- PASS: TestAccAWSEcrDataSource_ecrImage (42.83s)
--- PASS: TestAccAWSEcrDataSource_ecrRepository (53.71s)
--- PASS: TestAccAWSEcrDataSource_nonExistent (7.93s)
```

### CODE REVIEW

File: aws/data_source_aws_ecr_repository.go [hunk 1]
```diff
@@ -25,12 +25,28 @@ func dataSourceAwsEcrRepository() *schema.Resource {
 			},
 			"registry_id": {
 				Type:     schema.TypeString,
-				Computed: true,
+				Optional: true,
```
Comment (bflad) [inline aws/data_source_aws_ecr_repository.go:28]: This argument needs to keep `Computed` if `d.Set()` is being called on it, see also: https://github.com/terraform-providers/terraform-provider-aws/pull/14412

```suggestion
				Optional: true,
				Computed: true,
```

These types of errors will start showing when we switch the Terraform binary testing framework in SDK v2 and configure it for 0.13.

File: aws/data_source_aws_ecr_repository_test.go [hunk 2]
```diff
@@ -25,6 +25,8 @@ func TestAccAWSEcrDataSource_ecrRepository(t *testing.T) {
 					resource.TestCheckResourceAttrPair(resourceName, "registry_id", dataSourceName, "registry_id"),
 					resource.TestCheckResourceAttrPair(resourceName, "repository_url", dataSourceName, "repository_url"),
 					resource.TestCheckResourceAttrPair(resourceName, "tags", dataSourceName, "tags"),
+					resource.TestCheckResourceAttrPair(resourceName, "image_scanning_configuration", dataSourceName, "image_scanning_configuration"),
```
Comment (bflad) [inline aws/data_source_aws_ecr_repository_test.go:28]: If I recall correctly, checking the attribute name of a list/set doesn't return anything so this passing will always be a false positive. Instead the number of elements needs to be checked:

```suggestion
					resource.TestCheckResourceAttrPair(resourceName, "image_scanning_configuration.#", dataSourceName, "image_scanning_configuration.#"),
```

**Comment by DrFaust92** [comment]
@bflad, addressed the changes. i also noticed the test names were not specific to the data source so i change them as well and ran test again.
