### PR TITLE
fix kinesis firehose input creation

### LINKED ISSUE #7394: Unable to create Kinesis Analytics application: InvalidArgumentException
This is the same problem as listed in https://github.com/terraform-providers/terraform-provider-aws/issues/7032 with the exception that it is being raised when a `kinesis_firehose` is used as an input.

### Terraform Version
```
Terraform v0.11.11
+ provider.aws v1.56.0
```

### Affected Resource(s)

* aws_kinesis_analytics_application

### Terraform Configuration Files

```hcl
resource "aws_kinesis_firehose_delivery_stream" "firehose_stream" {
  name        = "${local.firehose_stream_name}"
  ..
}

data "aws_iam_policy_document" "kinesis_analytics" {
  statement {
    actions = [
      "firehose:DescribeDeliveryStream",
      "firehose:Get*",
    ]

    resources = [
      "${aws_kinesis_firehose_delivery_stream.firehose_stream.arn}"
    ]
  }
}

resource "aws_kinesis_analytics_application" "test" {
  name = "example"

  inputs {
    kinesis_firehose {
      resource_arn = "${aws_kinesis_firehose_delivery_stream.firehose_stream.arn}"
      role_arn     = "${module.kinesis_analytics_role.role_arn}"
    }
    ..
  }
}
```

### Debug Output

```
aws_kinesis_analytics_application.logs: Unable to create Kinesis Analytics application: InvalidArgumentException: Kinesis Analytics doesn't have sufficient privileges to the Delivery Stream using assumed role. Please check the DeliveryStreamARN: 'arn:aws:firehose:eu-west-1:00000000:deliverystream/test_stream' and the roleARN: 'arn:aws:iam::00000000:role/kinesis_analytics_test'.
```

### Expected Behavior

Creation without errors 

### Actual Behavior

Creation of Kinesis Application gets failed after the first execution. When I apply the same scripts second time - everyting gets created.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### PR DESCRIPTION
**Pull request by kl4w**
Fixes #7394

Changes proposed in this pull request:

* fix kinesis firehose input creation

Output from acceptance testing:

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSKinesisAnalyticsApplication_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSKinesisAnalyticsApplication_ -timeout 120m
=== RUN   TestAccAWSKinesisAnalyticsApplication_basic
=== PAUSE TestAccAWSKinesisAnalyticsApplication_basic
=== RUN   TestAccAWSKinesisAnalyticsApplication_update
=== PAUSE TestAccAWSKinesisAnalyticsApplication_update
=== RUN   TestAccAWSKinesisAnalyticsApplication_addCloudwatchLoggingOptions
=== PAUSE TestAccAWSKinesisAnalyticsApplication_addCloudwatchLoggingOptions
=== RUN   TestAccAWSKinesisAnalyticsApplication_updateCloudwatchLoggingOptions
=== PAUSE TestAccAWSKinesisAnalyticsApplication_updateCloudwatchLoggingOptions
=== RUN   TestAccAWSKinesisAnalyticsApplication_inputsKinesisFirehose
=== PAUSE TestAccAWSKinesisAnalyticsApplication_inputsKinesisFirehose
=== RUN   TestAccAWSKinesisAnalyticsApplication_inputsKinesisStream
=== PAUSE TestAccAWSKinesisAnalyticsApplication_inputsKinesisStream
=== RUN   TestAccAWSKinesisAnalyticsApplication_inputsAdd
=== PAUSE TestAccAWSKinesisAnalyticsApplication_inputsAdd
=== RUN   TestAccAWSKinesisAnalyticsApplication_inputsUpdateKinesisStream
=== PAUSE TestAccAWSKinesisAnalyticsApplication_inputsUpdateKinesisStream
=== RUN   TestAccAWSKinesisAnalyticsApplication_outputsKinesisStream
=== PAUSE TestAccAWSKinesisAnalyticsApplication_outputsKinesisStream
=== RUN   TestAccAWSKinesisAnalyticsApplication_outputsMultiple
=== PAUSE TestAccAWSKinesisAnalyticsApplication_outputsMultiple
=== RUN   TestAccAWSKinesisAnalyticsApplication_outputsAdd
=== PAUSE TestAccAWSKinesisAnalyticsApplication_outputsAdd
=== RUN   TestAccAWSKinesisAnalyticsApplication_outputsUpdateKinesisStream
=== PAUSE TestAccAWSKinesisAnalyticsApplication_outputsUpdateKinesisStream
=== RUN   TestAccAWSKinesisAnalyticsApplication_Outputs_Lambda_Add
=== PAUSE TestAccAWSKinesisAnalyticsApplication_Outputs_Lambda_Add
=== RUN   TestAccAWSKinesisAnalyticsApplication_Outputs_Lambda_Create
=== PAUSE TestAccAWSKinesisAnalyticsApplication_Outputs_Lambda_Create
=== RUN   TestAccAWSKinesisAnalyticsApplication_referenceDataSource
=== PAUSE TestAccAWSKinesisAnalyticsApplication_referenceDataSource
=== RUN   TestAccAWSKinesisAnalyticsApplication_referenceDataSourceUpdate
=== PAUSE TestAccAWSKinesisAnalyticsApplication_referenceDataSourceUpdate
=== CONT  TestAccAWSKinesisAnalyticsApplication_basic
=== CONT  TestAccAWSKinesisAnalyticsApplication_outputsMultiple
=== CONT  TestAccAWSKinesisAnalyticsApplication_inputsAdd
=== CONT  TestAccAWSKinesisAnalyticsApplication_Outputs_Lambda_Create
=== CONT  TestAccAWSKinesisAnalyticsApplication_referenceDataSourceUpdate
=== CONT  TestAccAWSKinesisAnalyticsApplication_referenceDataSource
=== CONT  TestAccAWSKinesisAnalyticsApplication_inputsKinesisStream
=== CONT  TestAccAWSKinesisAnalyticsApplication_outputsKinesisStream
=== CONT  TestAccAWSKinesisAnalyticsApplication_inputsUpdateKinesisStream
=== CONT  TestAccAWSKinesisAnalyticsApplication_outputsUpdateKinesisStream
=== CONT  TestAccAWSKinesisAnalyticsApplication_Outputs_Lambda_Add
=== CONT  TestAccAWSKinesisAnalyticsApplication_outputsAdd
=== CONT  TestAccAWSKinesisAnalyticsApplication_updateCloudwatchLoggingOptions
=== CONT  TestAccAWSKinesisAnalyticsApplication_inputsKinesisFirehose
=== CONT  TestAccAWSKinesisAnalyticsApplication_addCloudwatchLoggingOptions
=== CONT  TestAccAWSKinesisAnalyticsApplication_update
--- PASS: TestAccAWSKinesisAnalyticsApplication_basic (8.35s)
--- PASS: TestAccAWSKinesisAnalyticsApplication_update (12.82s)
--- PASS: TestAccAWSKinesisAnalyticsApplication_addCloudwatchLoggingOptions (21.44s)
--- PASS: TestAccAWSKinesisAnalyticsApplication_Outputs_Lambda_Create (22.09s)
--- PASS: TestAccAWSKinesisAnalyticsApplication_referenceDataSource (25.56s)
--- PASS: TestAccAWSKinesisAnalyticsApplication_Outputs_Lambda_Add (31.62s)
--- PASS: TestAccAWSKinesisAnalyticsApplication_updateCloudwatchLoggingOptions (32.78s)
--- PASS: TestAccAWSKinesisAnalyticsApplication_referenceDataSourceUpdate (44.93s)
--- PASS: TestAccAWSKinesisAnalyticsApplication_outputsKinesisStream (85.13s)
--- PASS: TestAccAWSKinesisAnalyticsApplication_inputsKinesisStream (85.13s)
--- PASS: TestAccAWSKinesisAnalyticsApplication_outputsMultiple (85.29s)
--- PASS: TestAccAWSKinesisAnalyticsApplication_inputsKinesisFirehose (102.97s)
--- PASS: TestAccAWSKinesisAnalyticsApplication_inputsAdd (103.83s)
--- PASS: TestAccAWSKinesisAnalyticsApplication_outputsAdd (107.01s)
--- PASS: TestAccAWSKinesisAnalyticsApplication_inputsUpdateKinesisStream (167.44s)
--- PASS: TestAccAWSKinesisAnalyticsApplication_outputsUpdateKinesisStream (167.46s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	167.507s
```

### CODE REVIEW

File: aws/resource_aws_kinesis_analytics_application_test.go [hunk 1]
```diff
@@ -567,6 +589,93 @@ resource "aws_kinesis_analytics_application" "test" {
...
+  extended_s3_configuration = {
+    role_arn = "${aws_iam_role.firehose.arn}"
+    bucket_arn = "${aws_s3_bucket.test.arn}"
+  }
+}
+
+resource "aws_kinesis_analytics_application" "test" {
+  name = "testAcc-%d"
+  code = "testCode\n"
+  inputs = {
```
Comment (bflad) [inline aws/resource_aws_kinesis_analytics_application_test.go]: @kl4w FYI in Terraform 0.12, this syntax is no longer valid for configuration blocks and the configuration upgrade tool will fix it to `input {`

(same with other configuration blocks in this test configuration)

**Comment by bflad** [comment]
This has been released in [version 1.60.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1600-february-22-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
