### PR TITLE
resource/aws_cloudwatch_log_stream: Prevent early state removal

### LINKED ISSUE #11611: aws_cloudwatch_log_stream resource produced new value for was present but now absent
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform -v
Terraform v0.12.3
+ provider.aws v2.37.0
```

### Affected Resource(s)

* aws_cloudwatch_log_stream

### Terraform Configuration Files

```hcl
resource "aws_cloudwatch_log_group" "test" {
  name = "/test"
}

resource "aws_cloudwatch_log_stream" "test" {
  name           = "test"
  log_group_name = aws_cloudwatch_log_group.test.name
}
```

### Debug Output

Here's a snippet of the debug log when the error occurs. The problem appears to occur when AWS returns a 200 OK with an empty list of `logStreams` for the stream which has just been created. This may be due to an eventual consistency issue that could be overcome by retrying the `DescribeLogStreams` call some number of times until the resource is available.

```
2019-12-30T22:27:14.323Z [DEBUG] plugin.terraform-provider-aws_v2.37.0_x4: 2019/12/30 22:27:14 [DEBUG] [aws-sdk-go] DEBUG: Request logs/DescribeLogStreams Details:
2019-12-30T22:27:14.323Z [DEBUG] plugin.terraform-provider-aws_v2.37.0_x4: ---[ REQUEST POST-SIGN ]-----------------------------
2019-12-30T22:27:14.323Z [DEBUG] plugin.terraform-provider-aws_v2.37.0_x4: POST / HTTP/1.1
2019-12-30T22:27:14.323Z [DEBUG] plugin.terraform-provider-aws_v2.37.0_x4: Host: logs.us-west-2.amazonaws.com
2019-12-30T22:27:14.323Z [DEBUG] plugin.terraform-provider-aws_v2.37.0_x4: User-Agent: aws-sdk-go/1.25.36 (go1.13.3; linux; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.12.3 (+https://www.terraform.io)
...
2019-12-30T22:27:14.323Z [DEBUG] plugin.terraform-provider-aws_v2.37.0_x4: X-Amz-Target: Logs_20140328.DescribeLogStreams
2019-12-30T22:27:14.323Z [DEBUG] plugin.terraform-provider-aws_v2.37.0_x4: Accept-Encoding: gzip
2019-12-30T22:27:14.323Z [DEBUG] plugin.terraform-provider-aws_v2.37.0_x4: 
2019-12-30T22:27:14.323Z [DEBUG] plugin.terraform-provider-aws_v2.37.0_x4: {"logGroupName":"/test","logStreamNamePrefix":"test"}
...
2019-12-30T22:27:14.644Z [DEBUG] plugin.terraform-provider-aws_v2.37.0_x4: ---[ RESPONSE ]--------------------------------------
2019-12-30T22:27:14.644Z [DEBUG] plugin.terraform-provider-aws_v2.37.0_x4: HTTP/1.1 200 OK
2019-12-30T22:27:14.644Z [DEBUG] plugin.terraform-provider-aws_v2.37.0_x4: Connection: close
2019-12-30T22:27:14.644Z [DEBUG] plugin.terraform-provider-aws_v2.37.0_x4: Content-Length: 17
2019-12-30T22:27:14.644Z [DEBUG] plugin.terraform-provider-aws_v2.37.0_x4: Content-Type: application/x-amz-json-1.1
2019-12-30T22:27:14.644Z [DEBUG] plugin.terraform-provider-aws_v2.37.0_x4: Date: Mon, 30 Dec 2019 22:27:14 GMT
2019-12-30T22:27:14.644Z [DEBUG] plugin.terraform-provider-aws_v2.37.0_x4: X-Amzn-Requestid: XXX
2019-12-30T22:27:14.644Z [DEBUG] plugin.terraform-provider-aws_v2.37.0_x4: 
2019-12-30T22:27:14.644Z [DEBUG] plugin.terraform-provider-aws_v2.37.0_x4: 
2019-12-30T22:27:14.644Z [DEBUG] plugin.terraform-provider-aws_v2.37.0_x4: -----------------------------------------------------
2019-12-30T22:27:14.644Z [DEBUG] plugin.terraform-provider-aws_v2.37.0_x4: 2019/12/30 22:27:14 [DEBUG] [aws-sdk-go] {"logStreams":[]}
2019-12-30T22:27:14.644Z [DEBUG] plugin.terraform-provider-aws_v2.37.0_x4: 2019/12/30 22:27:14 [DEBUG] CloudWatch Stream "test" Not Found. Removing from state
2019/12/30 22:27:14 [DEBUG] aws_cloudwatch_log_stream.test: apply errored, but we're indicating that via the Error pointer rather than returning it: Provider produced inconsistent result after apply: When applying changes to aws_cloudwatch_log_stream.test, provider "aws" produced an unexpected new value for was present, but now absent.
```

### Expected Behavior

The log stream resource should be created without any errors and the `terraform apply` should succeed.

### Actual Behavior

Most of the time, the expected behavior occurs. Intermittently, though, the log stream resource is created in AWS but the `terraform apply` fails with the following error:

```
Error: Provider produced inconsistent result after apply

When applying changes to
aws_cloudwatch_log_stream.test,
provider "aws" produced an unexpected new value for was present, but now
absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

Subsequent `terraform apply` attempts fail with the following error:

```
aws_cloudwatch_log_stream.test: Creating...
Error: Creating CloudWatch Log Stream failed: ResourceAlreadyExistsException: The specified log stream already exists
	status code: 400, request id: XXX
```

### Steps to Reproduce

1. `terraform apply`

### References

* #10549 - The behavior for this case seems similar, only for an `aws_appautoscaling_policy` resource instead of an `aws_cloudwatch_log_stream` one.

### PR DESCRIPTION
**Pull request by camlow325**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #11611

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
* resource/aws_cloudwatch_log_stream: Prevent state removal of resource immediately after creation due to eventual consistency ([#11611](https://github.com/terraform-providers/terraform-provider-aws/issues/11611))
```

The AWS logs service has eventual consistency considerations. The `aws_cloudwatch_log_stream` resource immediately tries to read a stream after creation. If the stream is not found, the logs service returns a 200 OK with an empty list of streams. Since no streams are present, the
`aws_cloudwatch_log_stream` resource removes the created resource from state, leading to a "produced an unexpected new value for was present, but now absent" error.

With the changes in this commit, the empty list of streams in the response for the newly created resource will result in a NotFoundError being returned and a retry of the read request. A subsequent retry should hopefully be successful, leading to the state being preserved.

Output from acceptance testing:

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSCloudWatchLogStream_'
...
--- PASS: TestAccAWSCloudWatchLogStream_disappears_LogGroup (16.77s)
--- PASS: TestAccAWSCloudWatchLogStream_disappears (19.55s)
--- PASS: TestAccAWSCloudWatchLogStream_basic (19.91s)
```

### CODE REVIEW

File: aws/resource_aws_cloudwatch_log_stream.go [hunk 1]
```diff
@@ -60,7 +62,24 @@ func resourceAwsCloudWatchLogStreamRead(d *schema.ResourceData, meta interface{}
 
 	group := d.Get("log_group_name").(string)
 
-	ls, exists, err := lookupCloudWatchLogStream(conn, d.Id(), group, nil)
+	var ls *cloudwatchlogs.LogStream
+	var exists bool
+
+	err := resource.Retry(2*time.Minute, func() *resource.RetryError {
```
Comment (camlow325) [inline aws/resource_aws_cloudwatch_log_stream.go]: I'm not really sure what a good upper bound for the retry timeout would be. In automation today, we do a second Terraform apply after the first one fails and that has always succeeded - probably well under 2 minutes.

File: aws/resource_aws_cloudwatch_log_stream.go [hunk 2]
```diff
@@ -60,7 +62,24 @@ func resourceAwsCloudWatchLogStreamRead(d *schema.ResourceData, meta interface{}
...
+		var err error
+		ls, exists, err = lookupCloudWatchLogStream(conn, d.Id(), group, nil)
+		if err != nil {
+			return resource.NonRetryableError(err)
```
Comment (camlow325) [inline aws/resource_aws_cloudwatch_log_stream.go]: Maybe it would be good to retry for other kinds of error, too - not sure. For the cases we've seen so far that we'd benefit from retrying on, the initial lookup returns a 200 OK so not retrying on failures would be backward compatible.

File: aws/resource_aws_cloudwatch_log_stream.go (hunk 1 above)
Comment (bflad) [reply aws/resource_aws_cloudwatch_log_stream.go]: Two minutes is pretty reasonable 👍 We can/will likely add a constant for this in the future.
