### PR TITLE
resource/aws_redshift_cluster: Send correct values when resizing

### LINKED ISSUE #484: Aws_redshift_cluster can't be resized without changing number_of_nodes
_This issue was originally opened by @wojukasz as hashicorp/terraform#11402. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

I am trying to updated redshift cluster from dc1.large to dc1.8xlarge while maintaining number of nodes (currently set at 2 and previously declared to this value) but I am getting an error that multi-node must be greater than or equal to 2?

**Terraform Version :** 0.8.4
**Affected Resource:** aws_redshift_cluster
**Terraform Configuration:**
_(...)_
_cluster_type = "multi-node"
number_of_nodes = "2"
node_type = "dc1.8xlarge"_  _#only change from dc1.large_
_(...)_

**Expected Behavior:** Be able to change the instance/cluster size without modifying number of nodes in use.

**Actual Behavior:**
_module.redshift_cluster.aws_redshift_cluster.cluster: Modifying...
  node_type: "dc1.large" => "dc1.8xlarge"_

_Error applying plan:_

_1 error(s) occurred:_

_* aws_redshift_cluster.cluster: [WARN] Error modifying Redshift Cluster (redshift-cluster-dev): InvalidParameterCombination: Number of nodes for cluster type multi-node must be greater than or equal to 2_
	_status code: 400, request id: 500f2ce2-e2d2-11e6-b32e-b73a2dabc4c7_

**Steps to Reproduce:** Create dc1.large multi-node cluster with 2 nodes and change the cluster size dc1.8xlarge

Seems to be related to: https://github.com/hashicorp/terraform/issues/6274

### PR DESCRIPTION
**Pull request by chosenken**
When resizing a Redshift cluster, the AWS API is expecting the Cluster
Type, Node Type, and Number of Nodes regardless of which value changed.
If not passed it will error out with
`[WARN] Error modifying Redshift Cluster (navistone-public-cluster):
InvalidParameterCombination: Number of nodes for cluster type multi-node
must be greater than or equal to 2`

Now we send all values if any one of them change.  Closes #484

Signed-off-by: Ken Herner <kherner@navistone.com>

### CODE REVIEW

File: aws/resource_aws_redshift_cluster_test.go [hunk 1]
```diff
@@ -342,6 +342,47 @@ func TestAccAWSRedshiftCluster_updateNodeCount(t *testing.T) {
 					testAccCheckAWSRedshiftClusterExists("aws_redshift_cluster.default", &v),
 					resource.TestCheckResourceAttr(
 						"aws_redshift_cluster.default", "number_of_nodes", "2"),
+					resource.TestCheckResourceAttr(
+						"aws_redshift_cluster.default", "cluster-type", "multi-node"),
```
Comment (bflad) [inline aws/resource_aws_redshift_cluster_test.go]: For all uses in the testing here, the `cluster-type` attribute should be `cluster_type` and `node-type` should be `node_type` to match the resource schema, otherwise testing fails. e.g.:
```
=== RUN   TestAccAWSRedshiftCluster_updateNodeCount
--- FAIL: TestAccAWSRedshiftCluster_updateNodeCount (2421.66s)
    testing.go:513: Step 1 error: Check failed: Check 3/4 error: aws_redshift_cluster.default: Attribute 'cluster-type' not found
=== RUN   TestAccAWSRedshiftCluster_updateNodeType
--- FAIL: TestAccAWSRedshiftCluster_updateNodeType (923.17s)
    testing.go:513: Step 0 error: Check failed: Check 2/2 error: aws_redshift_cluster.default: Attribute 'node-type' not found
```

Comment (chosenken) [reply aws/resource_aws_redshift_cluster_test.go]: Got it, I was having issues getting the test to run locally, so I missed that, thanks!

**Comment by chosenken** [comment]
@bflad Fixed the test cases, thanks for pointing that out.

**Comment by bflad** [comment]
Hmm, I'm getting this strange error when running the acceptance testing now. I will try to look into it later today if I have time.

```
=== RUN   TestAccAWSRedshiftCluster_updateNodeType
--- FAIL: TestAccAWSRedshiftCluster_updateNodeType (773.13s)
    testing.go:513: Step 1 error: Error applying: 1 error(s) occurred:
        
        * aws_redshift_cluster.default: 1 error(s) occurred:
        
        * aws_redshift_cluster.default: [WARN] Error modifying Redshift Cluster (tf-redshift-cluster-2884899450099823142): InvalidParameterCombination: Single-node with dw2.8xlarge is not supported
            status code: 400, request id: c4b7f272-0542-11e8-85c9-afeaf0a03f38
```

**Comment by poflynn** [comment]
My team is hitting this now, FYI, thanks for the effort.

**Comment by danielpops** [comment]
+1 just encountered this. Anything pending to merge this fix, @bflad?

**Comment by chosenken** [comment]
@bflad I should have fixed the acceptance test issue with the node type now, could you retest acceptance?  Thanks!

**Comment by bflad** [comment]
This has been released in [version 1.18.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1180-may-10-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
