### PR TITLE
test_update_rds-ca-2019

### LINKED ISSUE #12854: Update DB Tests for rds-ca-2015
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_db_instance
* aws_rds_cluster_instance

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output
```
=== CONT  TestAccAWSRDSClusterInstance_CACertificateIdentifier
    TestAccAWSRDSClusterInstance_CACertificateIdentifier: testing.go:669: Step 0 error: errors during apply:

        Error: error modifying DB Instance (tf-acc-test-875689410445001198): CertificateNotFound: Certificate not found: rds-ca-2015
                status code: 404, request id: 5fe84721-00b4-4034-ac3c-006c13aee957

          on /tmp/tf-test562506808/main.tf line 9:
          (source code not available)



--- FAIL: TestAccAWSRDSClusterInstance_CACertificateIdentifier (598.55s)
FAIL
FAIL    github.com/terraform-providers/terraform-provider-aws/aws       598.572s
```

As part of the standard maintenance and security best practices for RDS, the SSL/TLS certificates for RDS DB instances and Aurora DB clusters expire and are replaced every five years. The current certificate will expire on March 5, 2020. Your database clients and applications that use SSL/TLS with certificate validation to connect to an RDS DB instance or Aurora cluster will lose connectivity beginning March 5, 2020 if you do not update the SSL/TLS certificate on both the client and the database server.

Additionally, any new RDS DB instances and Aurora DB clusters created after January 14, 2020 will have the new certificates. All RDS DB instances and Aurora DB clusters created prior to that point will have the old certificates. If you wish to temporarily revert new DB instances or Aurora clusters manually to use the old certificate, you can do so using the AWS Management Console, the RDS API, or the AWS CLI. However, as noted above, these and all other DB instances and DB clusters should be updated to use the new certificates by March 5, 2020. DB instances and DB clusters created prior to January 14, 2020 will still use the old certificates.

https://aws.amazon.com/blogs/database/amazon-rds-customers-update-your-ssl-tls-certificates-by-february-5-2020/

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### PR DESCRIPTION
**Pull request by jbarnes7952**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #12854

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note

```

Output from acceptance testing:
https://gist.github.com/jbarnes7952/21cac1b172c3153b14b25299b363b1ce
https://gist.github.com/jbarnes7952/bfa335d899b122c1fa9eeaa8c44a91fc

### CODE REVIEW

File: aws/resource_aws_db_instance_test.go [hunk 1]
```diff
@@ -2981,13 +2981,6 @@ func TestAccAWSDBInstance_CACertificateIdentifier(t *testing.T) {
...
 		CheckDestroy: testAccCheckAWSDBInstanceDestroy,
 		Steps: []resource.TestStep{
-			{
-				Config: fmt.Sprintf(testAccAWSDBInstanceConfigWithCACertificateIdentifier, "rds-ca-2015"),
-				Check: resource.ComposeTestCheckFunc(
-					testAccCheckAWSDBInstanceExists(resourceName, &dbInstance),
-					resource.TestCheckResourceAttr(resourceName, "ca_cert_identifier", "rds-ca-2015"),
-				),
-			},
 			// Ensure we are able to modify the CACertIdentifier
```
Comment (bflad) [inline aws/resource_aws_db_instance_test.go:2984]: Let's also remove this comment, since its no longer accurate. 👍

File: aws/resource_aws_rds_cluster_instance_test.go [hunk 2]
```diff
@@ -852,13 +852,6 @@ func TestAccAWSRDSClusterInstance_CACertificateIdentifier(t *testing.T) {
...
-			{
-				Config: testAccAWSRDSClusterInstanceConfig_CACertificateIdentifier(rName, "rds-ca-2015"),
-				Check: resource.ComposeTestCheckFunc(
-					testAccCheckAWSClusterInstanceExists(resourceName, &dbInstance),
-					resource.TestCheckResourceAttr(resourceName, "ca_cert_identifier", "rds-ca-2015"),
-				),
-			},
 			{
 				ResourceName:      resourceName,
 				ImportState:       true,
```
Comment (bflad) [inline aws/resource_aws_rds_cluster_instance_test.go:857]: ImportState testing cannot be the first TestStep as there is no Terraform state to reference. In the current available of the Terraform Plugin SDK, [this will cause a panic](https://github.com/hashicorp/terraform-plugin-sdk/issues/373). There is also an [open issue in `tfproviderlint` to report this problem](https://github.com/bflad/tfproviderlint/issues/134), e.g. in CI testing.

The `TestStep`s here will need to be:

- Apply rds-ca-2019 (step below this one) first
- ImportState

File: aws/resource_aws_db_instance_test.go (hunk 1 above)
Comment (jbarnes7952) [reply aws/resource_aws_db_instance_test.go]: Thanks, done.

File: aws/resource_aws_rds_cluster_instance_test.go (hunk 2 above)
Comment (jbarnes7952) [reply aws/resource_aws_rds_cluster_instance_test.go]: Thanks, done.
