### PR TITLE
r/sfn_state_machine - iam role eventual consistency + wait for delete + add `arn` attribute

### LINKED ISSUE #7893: Race condition between state machine role creation and use. Long time to propagate the role.
**Terraform Version**
Terraform version 2.1.0

**Problem**: The state machine exec role takes time to propagate and an explicit “depends on” constraint does not help.

**Terraform Configuration Files**
```
data "aws_iam_policy_document" "states_exec_role_document" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["states.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "states_exec_role" {
  name               = "${local.stack_name}-${local.pod}-statesExecRole"
  assume_role_policy = "${data.aws_iam_policy_document.states_exec_role_document.json}"
}

resource "aws_sfn_state_machine" "state_machine" {
 depends_on = ["aws_iam_role.states_exec_role"]
 name       = "${local.stack_name}-${local.pod}-state-machine"
 definition = "${data.template_file.definition.rendered}"
 role_arn   = "${aws_iam_role.states_exec_role.arn}"
}

```
**Crash Output**
"* aws_sfn_state_machine.state_machine: Error creating Step Function State Machine: AccessDeniedException: Neither the global service principal states.amazonaws.com, nor the regional one is authorized to assume the provided role.
    status code: 400, request id: b26b3cc8-442d-11e9-83bb-03aa166dd894"

**Expected Behavior**
Apply complete! Resources: X added, 0 changed, 0 destroyed.

**Actual Behavior**
Fails to apply because iam roles takes time to propagate across regions. Apply succeeds on second application. It takes a few seconds for the IAM role to be available. 

**Steps to Reproduce**
terraform apply

**Additional context**

**Following hack addresses the problem, but this is still a hack.**

```
resource "null_resource" "delay" {
 provisioner "local-exec" {
   command = "sleep 30"
 }
 triggers = {
   "states_exec_role" = "${aws_iam_role.states_exec_role.arn}"
 }
}

resource "aws_sfn_state_machine" "state_machine" {
 name       = "${local.stack_name}-${local.pod}-state-machine"
 definition = "${data.template_file.definition.rendered}"
 role_arn   = "${aws_iam_role.states_exec_role.arn}"
 depends_on = ["null_resource.delay"]
}

Looking for a better solution to address the race condition.

### PR DESCRIPTION
**Pull request by DrFaust92**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #7893
Relates #13624

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource_aws_sfn_state_machine: add `arn` attribute
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSSfnStateMachine_'
--- FAIL: TestAccAWSSfnStateMachine_createUpdate (114.32s)
    testing.go:640: Step 2 error: Check failed: Check 6/7 error: aws_sfn_state_machine.test: Attribute 'definition' didn't match ".*\\\"MaxAttempts\\\": 10.*", got "{\n  \"Comment\": \"A Hello World example of the Amazon States Language using an AWS Lambda Function\",\n  \"StartAt\": \"HelloWorld\",\n  \"States\": {\n    \"HelloWorld\": {\n      \"Type\": \"Task\",\n      \"Resource\": \"arn:aws:lambda:us-west-2:476956259333:function:tf-acc-4347576902814911718\",\n      \"Retry\": [\n        {\n          \"ErrorEquals\": [\"States.ALL\"],\n          \"IntervalSeconds\": 5,\n          \"MaxAttempts\": 5,\n          \"BackoffRate\": 8.0\n        }\n      ],\n      \"End\": true\n    }\n  }\n}\n"


--- PASS: TestAccAWSSfnStateMachine_Tags (147.65s)
--- PASS: TestAccAWSSfnStateMachine_disappears (4732.81s)
```

tests failing due to another eventual consistency issue.

### CODE REVIEW

File: aws/internal/service/sfn/waiter/status.go [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+			StateMachineArn: aws.String(stateMachineArn),
+		}
+
+		output, err := conn.DescribeStateMachine(input)
+
+		if err != nil {
+			return nil, "", err
+		}
+
+		return output, aws.StringValue(output.Status), nil
```
Comment (bflad) [inline aws/internal/service/sfn/waiter/status.go:22]: To prevent panics, this should check `output` before attempting to reference a field inside it:

```suggestion
		if output == nil {
			return nil, "", nil
		}

		return output, aws.StringValue(output.Status), nil
```

File: aws/resource_aws_sfn_state_machine.go [hunk 2]
```diff
@@ -112,15 +120,14 @@ func resourceAwsSfnStateMachineRead(d *schema.ResourceData, meta interface{}) er
 	})
 	if err != nil {
 
-		if awserr, ok := err.(awserr.Error); ok {
-			if awserr.Code() == "NotFoundException" || awserr.Code() == "StateMachineDoesNotExist" {
-				d.SetId("")
-				return nil
-			}
+		if isAWSErr(err, sfn.ErrCodeStateMachineDoesNotExist, "") {
+			d.SetId("")
```
Comment (bflad) [inline aws/resource_aws_sfn_state_machine.go:124]: Nit: We should return a warning log message here:

```suggestion
			log.Printf("[WARN] SFN State Machine (%s) not found, removing from state", d.Id())
			d.SetId("")
```

File: aws/resource_aws_sfn_state_machine_test.go [hunk 3]
```diff
@@ -119,7 +163,7 @@ func testAccCheckAWSSfnStateMachineDestroy(s *terraform.State) error {
 		})
 
 		if err != nil {
-			if wserr, ok := err.(awserr.Error); ok && wserr.Code() == "StateMachineDoesNotExist" {
+			if isAWSErr(err, sfn.ErrCodeStateMachineDoesNotExist, "") {
 				return nil
```
Comment (bflad) [inline aws/resource_aws_sfn_state_machine_test.go:167]: Nit: Should `continue` in `CheckDestroy` functions to verify multiple resources

```suggestion
				continue
```

File: aws/resource_aws_sfn_state_machine_test.go [hunk 4]
```diff
@@ -129,38 +173,14 @@ func testAccCheckAWSSfnStateMachineDestroy(s *terraform.State) error {
 			return fmt.Errorf("Expected AWS Step Function State Machine to be destroyed, but was still found")
 		}
 
-		return nil
+		return err
```
Comment (bflad) [inline aws/resource_aws_sfn_state_machine_test.go:176]: Since `err` is already handled, this should be removed so the loop can continue.

```suggestion
```
