### PR TITLE
resource/aws_network_acl_rule: Properly handle ICMP code and type with IPv6 ICMP (protocol 58)

### LINKED ISSUE #4737: aws_network_acl_rule icmp for IPv6 not working, icmpTypeCode missing
I try to add a ALL IPv6 ICMP Rule with icmp_type and icmp_code set to -1 as stated in the documentation an get the below error. I also can see the the metioned field is empty in the request using cloud trail.

```hcl
resource "aws_network_acl_rule" "private-dev-acl-ingress-icmpv6" {
  network_acl_id  = "${aws_network_acl.private-dev-acl.id}"
  rule_number     = 151
  egress          = false
  protocol        = 58                                      # icmp v6
  icmp_type       = -1
  icmp_code       = -1
  rule_action     = "allow"
  ipv6_cidr_block = "::/0"
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.7
+ provider.aws v1.21.0

### Affected Resource(s)

* aws_network_acl_rule

### Terraform Configuration Files

I am using a s3 bucket state and a special profile. Other rules or task are working fine with this configuration.
```hcl
provider "aws" {
  allowed_account_ids = [
    "########", 
  ]

  profile = "dev"

  region  = "${var.aws_region}"
  version = "~> 1.19"
}
```

### Expected Behavior

ICMP v6 Rule with 

151 | All ICMP - IPv6 | IPv6-ICMP (58) | ALL | ::/0 | ALLOW

### Actual Behavior

```
aws_network_acl_rule.private-dev-acl-ingress-icmpv6: Creating...
  egress:          "" => "false"
  icmp_code:       "" => "-1"
  icmp_type:       "" => "-1"
  ipv6_cidr_block: "" => "::/0"
  network_acl_id:  "" => "acl-XXXXX"
  protocol:        "" => "58"
  rule_action:     "" => "allow"
  rule_number:     "" => "151"

Error: Error applying plan:

1 error(s) occurred:

* aws_network_acl_rule.private-dev-acl-ingress-icmpv6: 1 error(s) occurred:

* aws_network_acl_rule.private-dev-acl-ingress-icmpv6: Error Creating Network Acl Rule: MissingParameter: The request must contain the parameter icmpTypeCode.type
        status code: 400, request id: ae04ee8a-943b-44b6-80a5-25720a4ad77e
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### PR DESCRIPTION
**Pull request by bflad**
Fixes #4737 

Changes proposed in this pull request:

* Allow `protocol` 58 to propagate ICMP code and type configuration

Previously:

```
--- FAIL: TestAccAWSNetworkAclRule_ipv6ICMP (12.47s)
    testing.go:538: Step 0 error: Error applying: 1 error occurred:
        	* aws_network_acl_rule.test: 1 error occurred:
        	* aws_network_acl_rule.test: Error Creating Network Acl Rule: MissingParameter: The request must contain the parameter icmpTypeCode.type
        	status code: 400, request id: a0e8e287-af99-4da9-9b5f-e641e41d3fe7
```

Output from acceptance testing:

```
--- PASS: TestAccAWSNetworkAclRule_ipv6ICMP (24.21s)
```

### CODE REVIEW

File: aws/resource_aws_network_acl_rule.go [hunk 1]
```diff
@@ -139,7 +139,7 @@ func resourceAwsNetworkAclRuleCreate(d *schema.ResourceData, meta interface{}) e
 
 	// Specify additional required fields for ICMP. For the list
 	// of ICMP codes and types, see: https://www.iana.org/assignments/icmp-parameters/icmp-parameters.xhtml
-	if p == 1 {
+	if p == 1 || p == 58 {
```
Comment (tombuildsstuff) [inline aws/resource_aws_network_acl_rule.go]: whilst this is clear in that there's a test for it - IMO we want a comment/constant to explain what these are so it doesn't require a lookup

Comment (bflad) [reply aws/resource_aws_network_acl_rule.go]: I hope https://github.com/terraform-providers/terraform-provider-aws/issues/6302 covers this here as well. Probably best to solve this "globally". 😄
