### PR TITLE
resource/aws_kinesis_firehose_delivery_stream: Retry on additional IAM eventual consistency errors

### LINKED ISSUE #3380: AWS Kinesis Firehose Delivery repeatably fails on first run, success on second run
### Terraform Version
```$ terraform -v
Terraform v0.11.3
+ provider.aws v1.9.0
```
I also tested this on terraform 0.10.8 with the same results. 

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_kinesis_firehose_delivery_stream
- aws_iam_role_policy

This also seems related to a similar issue that was found in aws_ecr_repository and aws_ecr_repository_policy, issue terraform-providers/terraform-provider-aws#545

### Terraform Configuration Files
```hcl
provider "aws" {
  region = "us-east-1"
}

data "aws_region" "current" { }
variable "stream_name" { default = "testing_example" }

resource "random_string" "rand" {
  length = 16
  special = false
}

resource "aws_kinesis_stream" "stream" {
  name             = "${var.stream_name}"
  shard_count      = 1
  retention_period = 24
}

resource "aws_s3_bucket" "bucket" {
  bucket = "${var.stream_name}-${random_string.rand.result}-${data.aws_region.current.name}"
  acl    = "private"
}

resource "aws_iam_role" "firehose-role" {
  name               = "${var.stream_name}_firehose"
  assume_role_policy = <<EOF
{ "Version": "2012-10-17",
  "Statement": [ {
  "Action": "sts:AssumeRole",
  "Principal": { "Service": "firehose.amazonaws.com" },
  "Effect": "Allow",
  "Sid": "" } ]
}
EOF
}

resource "aws_iam_role_policy" "inline-policy" {
  name   = "${var.stream_name}_firehose_inline_policy"
  role   = "${aws_iam_role.firehose-role.id}"
  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:AbortMultipartUpload",
        "s3:GetBucketLocation",
        "s3:GetObject",
        "s3:ListBucket",
        "s3:ListBucketMultipartUploads",
        "s3:PutObject"
      ],
      "Resource": [
        "${aws_s3_bucket.bucket.arn}",
        "${aws_s3_bucket.bucket.arn}/*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "kinesis:DescribeStream",
        "kinesis:GetShardIterator",
        "kinesis:GetRecords"
      ],
      "Resource": "${aws_kinesis_stream.stream.arn}"
    }
  ]
}
EOF
}

resource "aws_kinesis_firehose_delivery_stream" "fh_stream" {
  name        = "${var.stream_name}_firehose"
  destination = "extended_s3"

  kinesis_source_configuration {
    kinesis_stream_arn = "${aws_kinesis_stream.stream.arn}"
    role_arn           = "${aws_iam_role.firehose-role.arn}"
  }

  extended_s3_configuration {
    role_arn        = "${aws_iam_role.firehose-role.arn}"
    bucket_arn      = "${aws_s3_bucket.bucket.arn}"
    buffer_size     = 1
    buffer_interval = 60
  }
}
```

### Debug Output

debug output of first run:  https://gist.github.com/rexroof/f6562cf49d7e308b21ddda4750a549fa
debug output of second run:  https://gist.github.com/rexroof/f62fccb56da2734197252954ad7d372f

### Expected Behavior
creation of kinesis firehose should complete successfully after waiting for iam policy to be applied

### Actual Behavior
apply stopped, this error:

 [WARN] Error creating Kinesis Firehose Delivery Stream: InvalidArgumentException: Role
    arn:aws:iam::702151822554:role/testing_example_firehose is not authorized to perform: kinesis:DescribeStream on resource arn:aws:kinesis:
    us-east-1:702151822554:stream/testing_example.

### Steps to Reproduce
1. `terraform apply`
2. `terraform apply`

### PR DESCRIPTION
**Pull request by bflad**
Fixes #3380 

```
Tests passed: 14
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3InvalidProcessorType
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3InvalidProcessorType (1.97s)
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3InvalidParameterName
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3InvalidParameterName (2.04s)
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3basic
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3basic (117.70s)
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_s3KinesisStreamSource
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_s3KinesisStreamSource (120.45s)
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_s3basic
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_s3basic (122.88s)
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_missingProcessingConfiguration
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_missingProcessingConfiguration (127.04s)
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_importBasic
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_importBasic (127.33s)
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_s3WithCloudwatchLogging
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_s3WithCloudwatchLogging (130.07s)
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3Updates
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3Updates (134.53s)
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3KmsKeyArn
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3KmsKeyArn (145.09s)
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_SplunkConfigUpdates
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_SplunkConfigUpdates (289.59s)
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_s3ConfigUpdates
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_s3ConfigUpdates (376.77s)
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_RedshiftConfigUpdates
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_RedshiftConfigUpdates (923.27s)
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_ElasticsearchConfigUpdates
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ElasticsearchConfigUpdates (1729.43s)
```

### CODE REVIEW

File: aws/resource_aws_kinesis_firehose_delivery_stream.go [hunk 1]
```diff
@@ -1335,10 +1336,7 @@ func resourceAwsKinesisFirehoseDeliveryStreamCreate(d *schema.ResourceData, meta
 		return nil
 	})
 	if err != nil {
-		if awsErr, ok := lastError.(awserr.Error); ok {
-			return fmt.Errorf("[WARN] Error creating Kinesis Firehose Delivery Stream: %s", awsErr.Error())
-		}
-		return err
+		return fmt.Errorf("error creating Kinesis Firehose Delivery Stream: %s", err)
```
Comment (radeksimko) [inline aws/resource_aws_kinesis_firehose_delivery_stream.go]: 👍  Thank you for this
