### PR TITLE
r/subnet - Fix removing ipv6 cidr block from subnet

### LINKED ISSUE #10815: can't remove ipv6_cidr_block from aws_subnet
Removing a previously-applied `ipv6_cidr_block` parameter from `aws_subnet` does not produce the expected behavior of removing the IPv6 CIDR.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.13
+ provider.aws v2.35.0
```

### Affected Resource(s)

* aws_subnet

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "us-west-2"
}

resource "aws_vpc" "vpc" {
  cidr_block = "192.168.0.0/24"
  assign_generated_ipv6_cidr_block = true
}

resource "aws_subnet" "subnet" {
  vpc_id          = aws_vpc.vpc.id
  cidr_block      = "192.168.0.0/26"
  #ipv6_cidr_block = cidrsubnet(aws_vpc.vpc.ipv6_cidr_block, 8, 0)
}

output "subnet" {
  value = aws_subnet.subnet
}
```

### Steps to Reproduce

1. `terraform apply`

   creates the VPC (with IPv6) and subnet (IPv4-only), as expected

2. Uncomment the `ipv6_cidr_block` line

3. `terraform apply`

   updates the subnet in-place to add ipv6_cidr_block, as expected

4. Re-comment the `ipv6_cidr_block` line

5. `terraform apply`

   Expected: should update the subnet to remove ipv6_cidr_block
   Actual: apply completes immediately with no changes, and my subnet still has IPv6

### PR DESCRIPTION
**Pull request by DrFaust92**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #10815

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource_aws_subnet: allow removing IPV6 CIDR Block
resource_aws_subnet: add plan time validation to `cidr_block`, `ipv6_cidr_block`.
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSSubnet_'
--- PASS: TestAccAWSSubnet_ipv6 (220.53s)
--- PASS: TestAccAWSSubnet_ignoreTags (173.26s)
--- PASS: TestAccAWSSubnet_ipv6 (220.53s)
--- PASS: TestAccAWSSubnet_enableIpv6 (191.56s)
--- PASS: TestAccAWSSubnet_availabilityZoneId (83.43s)
--- PASS: TestAccAWSSubnet_disappears (79.87s)
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
Verified acceptance tests:

```console
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSSubnet_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSSubnet_ -timeout 120m
=== RUN   TestAccAWSSubnet_basic
=== PAUSE TestAccAWSSubnet_basic
=== RUN   TestAccAWSSubnet_ignoreTags
=== PAUSE TestAccAWSSubnet_ignoreTags
=== RUN   TestAccAWSSubnet_ipv6
=== PAUSE TestAccAWSSubnet_ipv6
=== RUN   TestAccAWSSubnet_enableIpv6
=== PAUSE TestAccAWSSubnet_enableIpv6
=== RUN   TestAccAWSSubnet_availabilityZoneId
=== PAUSE TestAccAWSSubnet_availabilityZoneId
=== RUN   TestAccAWSSubnet_disappears
=== PAUSE TestAccAWSSubnet_disappears
=== CONT  TestAccAWSSubnet_basic
=== CONT  TestAccAWSSubnet_availabilityZoneId
=== CONT  TestAccAWSSubnet_disappears
=== CONT  TestAccAWSSubnet_ipv6
=== CONT  TestAccAWSSubnet_enableIpv6
=== CONT  TestAccAWSSubnet_ignoreTags
--- PASS: TestAccAWSSubnet_disappears (34.93s)
--- PASS: TestAccAWSSubnet_availabilityZoneId (38.19s)
--- PASS: TestAccAWSSubnet_basic (38.35s)
--- PASS: TestAccAWSSubnet_ignoreTags (70.50s)
--- PASS: TestAccAWSSubnet_enableIpv6 (86.62s)
--- PASS: TestAccAWSSubnet_ipv6 (94.75s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	94.829s
```

**Comment by DrFaust92** [comment]
rebased and added a few changes:

```
--- PASS: TestAccAWSSubnet_basic (69.39s)
--- PASS: TestAccAWSSubnet_ipv6 (181.27s)
--- PASS: TestAccAWSSubnet_enableIpv6 (160.83s)
--- PASS: TestAccAWSSubnet_disappears (64.57s)
--- PASS: TestAccAWSSubnet_availabilityZoneId (70.12s)
```

File: aws/resource_aws_subnet.go [hunk 1]
```diff
@@ -273,14 +272,35 @@ func resourceAwsSubnetUpdate(d *schema.ResourceData, meta interface{}) error {
...
 
 	if d.HasChange("ipv6_cidr_block") {
-		// We need to handle that we disassociate the IPv6 CIDR block before we try and associate the new one
-		// This could be an issue as, we could error out when we try and add the new one
+		// We need to handle that we disassociate the IPv6 CIDR block before we try to associate the new one
+		// This could be an issue as, we could error out when we try to add the new one
 		// We may need to roll back the state and reattach the old one if this is the case
 
-		_, new := d.GetChange("ipv6_cidr_block")
+		_, newIpv6 := d.GetChange("ipv6_cidr_block")
```
Comment (ewbankkit) [inline aws/resource_aws_subnet.go:279]: Should just use `d.Get("ipv6_cidr_block").(string)`: #12085.

File: aws/resource_aws_subnet.go [hunk 2]
```diff
@@ -273,14 +272,35 @@ func resourceAwsSubnetUpdate(d *schema.ResourceData, meta interface{}) error {
...
+		n := newIpv6.(string)
 
 		if v, ok := d.GetOk("ipv6_cidr_block_association_id"); ok {
 
+			_, newIpv6AssignOnCreate := d.GetChange("assign_ipv6_address_on_creation")
```
Comment (ewbankkit) [inline aws/resource_aws_subnet.go:284]: Should just use `d.Get("assign_ipv6_address_on_creation").(bool)`: #12085.

File: aws/resource_aws_subnet.go [hunk 3]
```diff
@@ -273,14 +272,35 @@ func resourceAwsSubnetUpdate(d *schema.ResourceData, meta interface{}) error {
...
+						Value: aws.Bool(false),
+					},
+				}
+
+				log.Printf("[DEBUG] Subnet modify attributes: %#v", modifyOpts)
+
+				_, err := conn.ModifySubnetAttribute(modifyOpts)
+
+				if err != nil {
+					return err
```
Comment (ewbankkit) [inline aws/resource_aws_subnet.go:301]: `return fmt.Errorf("error modifying EC2 Subnet (%s) attribute: %w", d.Id(), err)`

File: aws/resource_aws_subnet.go [hunk 4]
```diff
@@ -292,49 +312,50 @@ func resourceAwsSubnetUpdate(d *schema.ResourceData, meta interface{}) error {
...
-		if err != nil {
-			//The big question here is, do we want to try and reassociate the old one??
-			//If we have a failure here, then we may be in a situation that we have nothing associated
-			return err
-		}
+			resp, err := conn.AssociateSubnetCidrBlock(associatesOpts)
+			if err != nil {
+				//The big question here is, do we want to try to reassociate the old one??
+				//If we have a failure here, then we may be in a situation that we have nothing associated
+				return err
```
Comment (ewbankkit) [inline aws/resource_aws_subnet.go:340]: `return fmt.Errorf("error associating EC2 Subnet (%s) CIDR block: %w", d.Id(), err)`

**Comment by ewbankkit** [comment]
Verified acceptance tests:

```console
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSSubnet_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 2 -run=TestAccAWSSubnet_ -timeout 120m
=== RUN   TestAccAWSSubnet_basic
=== PAUSE TestAccAWSSubnet_basic
=== RUN   TestAccAWSSubnet_ignoreTags
=== PAUSE TestAccAWSSubnet_ignoreTags
=== RUN   TestAccAWSSubnet_ipv6
=== PAUSE TestAccAWSSubnet_ipv6
=== RUN   TestAccAWSSubnet_enableIpv6
=== PAUSE TestAccAWSSubnet_enableIpv6
=== RUN   TestAccAWSSubnet_availabilityZoneId
=== PAUSE TestAccAWSSubnet_availabilityZoneId
=== RUN   TestAccAWSSubnet_disappears
=== PAUSE TestAccAWSSubnet_disappears
=== RUN   TestAccAWSSubnet_outpost
=== PAUSE TestAccAWSSubnet_outpost
=== CONT  TestAccAWSSubnet_basic
=== CONT  TestAccAWSSubnet_availabilityZoneId
--- PASS: TestAccAWSSubnet_basic (25.22s)
=== CONT  TestAccAWSSubnet_outpost
--- PASS: TestAccAWSSubnet_availabilityZoneId (25.94s)
=== CONT  TestAccAWSSubnet_disappears
=== CONT  TestAccAWSSubnet_outpost
    data_source_aws_outposts_outposts_test.go:66: skipping since no Outposts Outpost found
--- SKIP: TestAccAWSSubnet_outpost (1.69s)
=== CONT  TestAccAWSSubnet_ipv6
--- PASS: TestAccAWSSubnet_disappears (22.55s)
=== CONT  TestAccAWSSubnet_enableIpv6
--- PASS: TestAccAWSSubnet_ipv6 (66.58s)
=== CONT  TestAccAWSSubnet_ignoreTags
--- PASS: TestAccAWSSubnet_enableIpv6 (57.08s)
--- PASS: TestAccAWSSubnet_ignoreTags (45.34s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	138.920s
```

**Comment by ewbankkit** [comment]
@DrFaust92 Looking good apart from a few minor tweaks.

**Comment by DrFaust92** [comment]
rebased

File: aws/resource_aws_subnet_test.go [hunk 5]
```diff
@@ -512,10 +544,8 @@ resource "aws_subnet" "test" {
 func testAccSubnetTagsConfig2(rName, tagKey1, tagValue1, tagKey2, tagValue2 string) string {
 	return fmt.Sprintf(`
 resource "aws_vpc" "test" {
-  cidr_block = "10.1.0.0/16"
-
-  tags = {
-    Name = %[1]q
+  cidr_block = "10.1.0.0/16"tags = {
```
Comment (bflad) [inline aws/resource_aws_subnet_test.go:547]: Looks like there's a little configuration typo here 😅 

```
=== CONT  TestAccAWSSubnet_tags
TestAccAWSSubnet_tags: resource_aws_subnet_test.go:177: Step 3/4 error: terraform failed: exit status 1
stderr:
Error: Missing newline after argument
on config633927574/terraform_plugin_test.tf line 3, in resource "aws_vpc" "test":
3:   cidr_block = "10.1.0.0/16"tags = {
An argument definition must end with a newline.
```

```suggestion
  cidr_block = "10.1.0.0/16"

  tags = {
```

File: aws/resource_aws_subnet_test.go [hunk 6]
```diff
@@ -477,7 +509,7 @@ resource "aws_vpc" "test" {
   cidr_block = "10.1.0.0/16"
 
   tags = {
-    Name = "terraform-testacc-subnet"
+  	Name = "terraform-testacc-subnet"
```
Comment (bflad) [inline aws/resource_aws_subnet_test.go:512]: Nit: The two-space formatting previously here and below is expected:

```suggestion
    Name = "terraform-testacc-subnet"
```

File: aws/resource_aws_subnet_test.go [hunk 7]
```diff
@@ -616,12 +646,21 @@ resource "aws_subnet" "test" {
...
 
 const testAccSubnetConfigAvailabilityZoneId = `
+data "aws_availability_zones" "test" {
+  state = "available"
+
+  filter {
+    name   = "opt-in-status"
+    values = ["opt-in-not-required"]
+  }
+}
```
Comment (bflad) [inline aws/resource_aws_subnet_test.go:662]: Let's drop in the standard `composeConfig(testAccAvailableAZsNoOptInConfig(), ...)` here 👍

File: aws/resource_aws_subnet_test.go (hunk 5 above)
Comment (DrFaust92) [reply aws/resource_aws_subnet_test.go]: thanks, missed this in the rebase

File: aws/resource_aws_subnet_test.go (hunk 7 above)
Comment (DrFaust92) [reply aws/resource_aws_subnet_test.go]: done

File: aws/resource_aws_subnet_test.go [hunk 8]
```diff
@@ -616,12 +648,22 @@ resource "aws_subnet" "test" {
...
+	return composeConfig(testAccAvailableAZsNoOptInConfig(), `
+data "aws_availability_zones" "test" {
+  state = "available"
+
+  filter {
+    name   = "opt-in-status"
+    values = ["opt-in-not-required"]
+  }
+}
+
```
Comment (bflad) [inline aws/resource_aws_subnet_test.go:666]:
```suggestion
```

File: aws/resource_aws_subnet_test.go [hunk 9]
```diff
@@ -633,13 +675,14 @@ resource "aws_vpc" "test" {
 resource "aws_subnet" "test" {
   cidr_block           = "10.1.1.0/24"
   vpc_id               = aws_vpc.test.id
-  availability_zone_id = "usw2-az3"
+  availability_zone_id = data.aws_availability_zones.test.zone_ids[0]
```
Comment (bflad) [inline aws/resource_aws_subnet_test.go:678]:
```suggestion
  availability_zone_id = data.aws_availability_zones.available.zone_ids[0]
```

File: aws/resource_aws_subnet_test.go [hunk 10]
```diff
@@ -515,7 +547,7 @@ resource "aws_vpc" "test" {
   cidr_block = "10.1.0.0/16"
 
   tags = {
-    Name = %[1]q
+  	Name = %[1]q
```
Comment (bflad) [inline aws/resource_aws_subnet_test.go:550]:
```suggestion
    Name = %[1]q
```

File: aws/resource_aws_subnet_test.go [hunk 11]
```diff
@@ -537,7 +569,7 @@ resource "aws_vpc" "test" {
   assign_generated_ipv6_cidr_block = true
 
   tags = {
-    Name = "terraform-testacc-subnet-ipv6"
+  	Name = "terraform-testacc-subnet-ipv6"
```
Comment (bflad) [inline aws/resource_aws_subnet_test.go:572]:
```suggestion
    Name = "terraform-testacc-subnet-ipv6"
```

File: aws/resource_aws_subnet_test.go [hunk 12]
```diff
@@ -547,7 +579,7 @@ resource "aws_subnet" "test" {
   map_public_ip_on_launch = true
 
   tags = {
-    Name = "tf-acc-subnet-ipv6"
+  	Name = "tf-acc-subnet-ipv6"
```
Comment (bflad) [inline aws/resource_aws_subnet_test.go:582]:
```suggestion
    Name = "tf-acc-subnet-ipv6"
```

File: aws/resource_aws_subnet_test.go [hunk 13]
```diff
@@ -558,7 +590,7 @@ resource "aws_vpc" "test" {
   assign_generated_ipv6_cidr_block = true
 
   tags = {
-    Name = "terraform-testacc-subnet-ipv6"
+  	Name = "terraform-testacc-subnet-ipv6"
```
Comment (bflad) [inline aws/resource_aws_subnet_test.go:593]:
```suggestion
    Name = "terraform-testacc-subnet-ipv6"
```

File: aws/resource_aws_subnet_test.go [hunk 14]
```diff
@@ -570,7 +602,7 @@ resource "aws_subnet" "test" {
   assign_ipv6_address_on_creation = true
 
   tags = {
-    Name = "tf-acc-subnet-ipv6"
+  	Name = "tf-acc-subnet-ipv6"
```
Comment (bflad) [inline aws/resource_aws_subnet_test.go:605]:
```suggestion
    Name = "tf-acc-subnet-ipv6"
```

File: aws/resource_aws_subnet_test.go [hunk 15]
```diff
@@ -581,7 +613,7 @@ resource "aws_vpc" "test" {
   assign_generated_ipv6_cidr_block = true
 
   tags = {
-    Name = "terraform-testacc-subnet-assign-ipv6-on-creation"
+  	Name = "terraform-testacc-subnet-assign-ipv6-on-creation"
```
Comment (bflad) [inline aws/resource_aws_subnet_test.go:616]:
```suggestion
    Name = "terraform-testacc-subnet-assign-ipv6-on-creation"
```

File: aws/resource_aws_subnet_test.go [hunk 16]
```diff
@@ -593,7 +625,7 @@ resource "aws_subnet" "test" {
   assign_ipv6_address_on_creation = false
 
   tags = {
-    Name = "tf-acc-subnet-assign-ipv6-on-creation"
+  	Name = "tf-acc-subnet-assign-ipv6-on-creation"
```
Comment (bflad) [inline aws/resource_aws_subnet_test.go:628]:
```suggestion
    Name = "tf-acc-subnet-assign-ipv6-on-creation"
```

File: aws/resource_aws_subnet_test.go [hunk 17]
```diff
@@ -604,7 +636,7 @@ resource "aws_vpc" "test" {
   assign_generated_ipv6_cidr_block = true
 
   tags = {
-    Name = "terraform-testacc-subnet-ipv6-update-cidr"
+  	Name = "terraform-testacc-subnet-ipv6-update-cidr"
```
Comment (bflad) [inline aws/resource_aws_subnet_test.go:639]:
```suggestion
    Name = "terraform-testacc-subnet-ipv6-update-cidr"
```

File: aws/resource_aws_subnet_test.go [hunk 18]
```diff
@@ -616,12 +648,22 @@ resource "aws_subnet" "test" {
   assign_ipv6_address_on_creation = false
 
   tags = {
-    Name = "tf-acc-subnet-ipv6-update-cidr"
+  	Name = "tf-acc-subnet-ipv6-update-cidr"
```
Comment (bflad) [inline aws/resource_aws_subnet_test.go:651]:
```suggestion
    Name = "tf-acc-subnet-ipv6-update-cidr"
```
