### PR TITLE
resource/aws_launch_template: Ensure ebs_optimized argument accepts "unspecified" value

### LINKED ISSUE #5458: aws_launch_template.ebs_optimized = false doesn't work
_This issue was originally opened by @cjbottaro as hashicorp/terraform#18605. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version
```
$ terraform -v
Terraform v0.11.7
+ provider.aws v1.30.0
```
### Expected Behavior
Setting
```
ebs_optimized = false
```
for an aws_launch_template resource should set EBS optimized to false in AWS.

See screenshot of plan:
http://storage.stochasticbytes.com.s3.amazonaws.com/CKzjSoHv.png

### Actual Behavior

EBS optimized is set to "not specified" in AWS:
http://storage.stochasticbytes.com.s3.amazonaws.com/m5b1nDN6.png

### PR DESCRIPTION
**Pull request by bjwschaap**
First attempt to contribute, so any guidance is much appreciated.

Fixes #5458 

Output from acceptance testing:
```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSLaunchTemplate'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSLaunchTemplate -timeout 120m
=== RUN   TestAccAWSLaunchTemplate_importBasic
--- PASS: TestAccAWSLaunchTemplate_importBasic (26.03s)
=== RUN   TestAccAWSLaunchTemplate_importData
--- PASS: TestAccAWSLaunchTemplate_importData (23.80s)
=== RUN   TestAccAWSLaunchTemplate_basic
--- PASS: TestAccAWSLaunchTemplate_basic (22.79s)
=== RUN   TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS
--- PASS: TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS (27.85s)
=== RUN   TestAccAWSLaunchTemplate_data
--- PASS: TestAccAWSLaunchTemplate_data (20.99s)
=== RUN   TestAccAWSLaunchTemplate_update
--- PASS: TestAccAWSLaunchTemplate_update (85.40s)
=== RUN   TestAccAWSLaunchTemplate_tags
--- PASS: TestAccAWSLaunchTemplate_tags (41.26s)
=== RUN   TestAccAWSLaunchTemplate_nonBurstable
--- PASS: TestAccAWSLaunchTemplate_nonBurstable (21.50s)
=== RUN   TestAccAWSLaunchTemplate_networkInterface
--- PASS: TestAccAWSLaunchTemplate_networkInterface (56.63s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	326.306s
```

### CODE REVIEW

**Comment by bflad** [comment]
Hi @bjwschaap 👋  Thanks for submitting this.

Do we know for sure that the default for this attribute is `false`? Many of the options for EC2 Launch Templates can have three states for booleans: "unspecified" / `false` / `true`. The unspecified case usually is for designating that the AMI's setting applies to any instances launched (e.g. AMI has EBS optimized set to enabled so launching instances inherit this setting) while `false` / `true` are used to override the AMI setting.

**Comment by blckct** [comment]
It should default to unspecified so the instances that are ebs optimized by default launch with ebs optimization.

**Comment by bflad** [comment]
Its likely that this implementation should instead be similar to: #5632 where we use `TypeString` to allow `""` in addition to true/false. @bjwschaap are you able to update this pull request?

**Comment by bjwschaap** [comment]
@bflad and @blckct thanks for the feedback! I can update the PR, no problem.

So as I far as I can tell from the documentation the default state for a launch template on AWS is indeed "unspecified". I was too quick with jumping to a conclusion with this implementation, based on the conversation in the issue thread. My apologies..

Based on @bflad comment about #5632 I think I have enough pointers to improve this PR.

**Comment by bjwschaap** [comment]
@bflad @blckct I'm hitting an issue when testing. I'm probably missing something obvious here, but I'm a bit stuck at the moment. Maybe you have some pointers for me?

I've added `ebs_optimized = false` to `testAccAWSLaunchTemplateConfig_data` in the test. When running it fails because somehow it finds "0" (or "1" if I set ebs_optimized to true) instead of the string representation for the boolean:

```
=== RUN   TestAccAWSLaunchTemplate_importData
2018/08/21 23:13:45 [INFO] Test: Using us-west-2 as test region
2018/08/21 23:13:45 [INFO] No assume_role block read from configuration
2018/08/21 23:13:45 [INFO] Building AWS region structure
2018/08/21 23:13:45 [INFO] Building AWS auth structure
2018/08/21 23:13:45 [INFO] Setting AWS metadata API timeout to 100ms
2018/08/21 23:13:46 [INFO] Ignoring AWS metadata API endpoint at default location as it doesn't return any instance-id
2018/08/21 23:13:46 [INFO] AWS Auth provider used: "EnvProvider"
2018/08/21 23:13:46 [INFO] Initializing DeviceFarm SDK connection
2018/08/21 23:13:47 [INFO] terraform: building graph: GraphTypeValidate
2018/08/21 23:13:48 [ERROR] root: eval: *terraform.EvalValidateResource, err: Warnings: []. Errors: [expected ebs_optimized to be one of [ false true], got 0]
2018/08/21 23:13:48 [ERROR] root: eval: *terraform.EvalSequence, err: Warnings: []. Errors: [expected ebs_optimized to be one of [ false true], got 0]
2018/08/21 23:13:48 [WARN] Skipping destroy test since there is no state.
--- FAIL: TestAccAWSLaunchTemplate_importData (2.07s)
	testing.go:527: Step 0 error: config is invalid: aws_launch_template.foo: expected ebs_optimized to be one of [ false true], got 0
```
To my understanding `resourceAwsLaunchTemplateRead` is used to fetch the LaunchTemplate from EC2, and copy/transform the data from the ec2 API into the terraform schema (unmarshall). And `buildLaunchTemplateData` the other way around to convert the schema to an ec2 API struct (marshall). Are these assumptions correct? I've double checked that I'm converting the string to bool and back the correct way. So I'm not sure if my implementation is wrong, or the test is broken.

I'll commit and push what I have so far so you can take a look.

**Comment by bflad** [comment]
@bjwschaap I found the fix required for handling booleans in `TypeString`, you can setup this attribute to use the following `DiffSuppressFunc` and `ValidateFunc`:

```go
"ebs_optimized": {
	// Use TypeString to allow an "unspecified" value,
	// since TypeBool only has true/false with false default.
	// The conversion from bare true/false values in
	// configurations to TypeString value is currently safe.
	Type:             schema.TypeString,
	Optional:         true,
	DiffSuppressFunc: suppressEquivalentTypeStringBoolean,
	ValidateFunc:     validateTypeStringNullableBoolean,
},
```

**Comment by bjwschaap** [comment]
```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSLaunchTemplate'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSLaunchTemplate -timeout 120m
=== RUN   TestAccAWSLaunchTemplate_importBasic
--- PASS: TestAccAWSLaunchTemplate_importBasic (24.31s)
=== RUN   TestAccAWSLaunchTemplate_importData
--- PASS: TestAccAWSLaunchTemplate_importData (22.24s)
=== RUN   TestAccAWSLaunchTemplate_basic
--- PASS: TestAccAWSLaunchTemplate_basic (20.45s)
=== RUN   TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS
--- PASS: TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS (54.46s)
=== RUN   TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS_DeleteOnTermination
--- PASS: TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS_DeleteOnTermination (83.05s)
=== RUN   TestAccAWSLaunchTemplate_data
--- PASS: TestAccAWSLaunchTemplate_data (20.53s)
=== RUN   TestAccAWSLaunchTemplate_update
--- PASS: TestAccAWSLaunchTemplate_update (80.70s)
=== RUN   TestAccAWSLaunchTemplate_tags
--- PASS: TestAccAWSLaunchTemplate_tags (37.72s)
=== RUN   TestAccAWSLaunchTemplate_nonBurstable
--- PASS: TestAccAWSLaunchTemplate_nonBurstable (19.63s)
=== RUN   TestAccAWSLaunchTemplate_networkInterface
--- PASS: TestAccAWSLaunchTemplate_networkInterface (56.29s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	419.418s
```

**Comment by bjwschaap** [comment]
Please review @bflad

File: aws/resource_aws_launch_template.go [hunk 1]
```diff
@@ -549,6 +554,10 @@ func resourceAwsLaunchTemplateRead(d *schema.ResourceData, meta interface{}) err
 	d.Set("user_data", ltData.UserData)
 	d.Set("vpc_security_group_ids", aws.StringValueSlice(ltData.SecurityGroupIds))
 
+	if ltData.EbsOptimized != nil {
```
Comment (bflad) [inline aws/resource_aws_launch_template.go]: We should probably additionally call `d.Set("ebs_optimized", "")` before this `if` to handle ensure Terraform catches the scenario where the attribute is set to "unspecified" out of band.

File: aws/resource_aws_launch_template_test.go [hunk 2]
```diff
@@ -122,6 +122,7 @@ func TestAccAWSLaunchTemplate_data(t *testing.T) {
 					resource.TestCheckResourceAttr(resName, "block_device_mappings.#", "1"),
 					resource.TestCheckResourceAttr(resName, "credit_specification.#", "1"),
 					resource.TestCheckResourceAttrSet(resName, "disable_api_termination"),
+					resource.TestCheckResourceAttrSet(resName, "ebs_optimized"),
```
Comment (bflad) [inline aws/resource_aws_launch_template_test.go]: Rather than just testing the attribute being set (to anything) we should ensure its value is correct:

```go
resource.TestCheckResourceAttr(resName, "ebs_optimized", "false"),
```

We should also ensure at least one test whose configuration doesn't include `ebs_optimized` has the correct value as well:

```
resource.TestCheckResourceAttr(resName, "ebs_optimized", ""),
```

**Comment by bjwschaap** [comment]
@bflad Thnx for the feedback. Sorry for the late response on my behalf. I'll try and update with your review comments as soon as I can so we can get this shipped.

**Comment by bflad** [comment]
This has been released in [version 1.36.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1360-september-13-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
