### PR TITLE
Handle duplicate sid in policy document

### LINKED ISSUE #6659: Duplicate sid in policy causes unexpected behavior
_This issue was originally opened by @rgooler as hashicorp/terraform#19513. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version
```
v0.11.10
```

### Terraform Configuration Files
```hcl
resource "aws_iam_policy" "test" {
  name        = "test"
  description = "test role"
  path        = "/service-role/"
  policy      = "${data.aws_iam_policy_document.test.json}"
}

data "aws_iam_policy_document" "test" {
  statement {
    sid    = "ManagedByTerraform"
    effect = "Allow"
    actions = ["rds:DescribeDBInstances" ]
    resources = ["*"]
  }
  statement {
    sid    = "ManagedByTerraform"
    effect = "Allow"
    actions = ["rds:DownloadDBLogFilePortion"]
    resources = ["*"]
  }
}
```

### Expected Behavior
A policy should be created with 2 statements, each granting 1 permission OR a terraform validation error should be triggered preventing terraform apply

### Actual Behavior
A policy is created with only the "rds:DownloadDBLogFilePortion" permission. The duplicate sids cause all but the last matching section to be discarded

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Additional Context
Nothing special about the setup

### References
None

### PR DESCRIPTION
**Pull request by sunilkumarmohanty**
Fixes #6659

Changes proposed in this pull request:

* Checks for duplicate SID

### CODE REVIEW

File: aws/data_source_aws_iam_policy_document.go [hunk 1]
```diff
@@ -114,14 +115,22 @@ func dataSourceAwsIamPolicyDocumentRead(d *schema.ResourceData, meta interface{}
...
+
 		for i, stmtI := range cfgStmtIntf {
 			cfgStmt := stmtI.(map[string]interface{})
 			stmt := &IAMPolicyStatement{
 				Effect: cfgStmt["effect"].(string),
 			}
 
 			if sid, ok := cfgStmt["sid"]; ok {
+				if _, ok := sidMap[sid.(string)]; ok {
+					return fmt.Errorf("Sid should be blank or unique. Change Sid : %s", sid.(string))
```
Comment (bflad) [inline aws/data_source_aws_iam_policy_document.go]: A few things here:
* Can you please add an acceptance test that covers this new behavior by matching against this error (e.g. `ExpectError: regexp.MustCompile()`)
* I would suggest updating the wording slightly here:

```suggestion
					return fmt.Errorf("Found duplicate sid (%s). Either remove the sid or ensure the sid is unique across all statements.", sid.(string))
```

**Comment by sunilkumarmohanty** [comment]
Added Acceptance test
```
 make testacc TEST=./aws TESTARGS='-run=TestAccAWSDataSourceIAMPolicyDocument_duplicateSid'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSDataSourceIAMPolicyDocument_duplicateSid -timeout 120m
=== RUN   TestAccAWSDataSourceIAMPolicyDocument_duplicateSid
=== PAUSE TestAccAWSDataSourceIAMPolicyDocument_duplicateSid
=== CONT  TestAccAWSDataSourceIAMPolicyDocument_duplicateSid
--- PASS: TestAccAWSDataSourceIAMPolicyDocument_duplicateSid (23.93s)
PASS
ok      github.com/sunilkumarmohanty/terraform-provider-aws/aws (cached)
```
