### PR TITLE
resource/aws_acm_certificate_validation: Fix root and wildcard validation_record_fqdns handling

### LINKED ISSUE #3329: aws_acm_certificate_validation.validation_record_fqdns is not checked correctly
### Terraform Version

Terraform v0.11.3

terraform-provider-aws v1.9.0

### Affected Resource(s)

- aws_acm_certificate
- aws_acm_certificate_validation

### Terraform Configuration Files
```hcl
resource "aws_acm_certificate" "example_wildcard" {
    domain_name = "*.example.com"
    validation_method = "DNS"
}

resource "aws_route53_record" "example_wildcard_validation_0" {
    name = "${aws_acm_certificate.example_wildcard.domain_validation_options.0.resource_record_name}"
    type = "${aws_acm_certificate.example_wildcard.domain_validation_options.0.resource_record_type}"
    zone_id = "${aws_route53_zone.example.id}"
    records = ["${aws_acm_certificate.example_wildcard.domain_validation_options.0.resource_record_value}"]
    ttl = 60
}

resource "aws_route53_record" "example_wildcard_validation_1" {
    name = "${aws_acm_certificate.example_wildcard.domain_validation_options.1.resource_record_name}"
    type = "${aws_acm_certificate.example_wildcard.domain_validation_options.1.resource_record_type}"
    zone_id = "${aws_route53_zone.example.id}"
    records = ["${aws_acm_certificate.example_wildcard.domain_validation_options.1.resource_record_value}"]
    ttl = 60
}

resource "aws_acm_certificate_validation" "example_wildcard" {
    certificate_arn = "${aws_acm_certificate.example_wildcard.arn}"
    validation_record_fqdns = ["${aws_route53_record.example_wildcard_validation_0.fqdn}", "${aws_route53_record.example_wildcard_validation_1.fqdn}"]
}

```

### Debug Output

Not relevant.

### Panic Output

None.

### Expected Behavior

I tried to validate an aws_acm_certificate for "*.example.com" domain name with "subject_alternative_names" set to "example.com". This produces two domain_validation_options with the same CNAME. It should either produce a single domain_validation_option or recognise at validation stage that the two are identical.

### Actual Behavior

If I pass one or both to aws_acm_certificate_validation.validation_record_fqdns, it complains that:

Certificate needs [_6a81694b41028a7644a2004feeb763e6.example.com _6a81694b41028a7644a2004feeb763e6.example.com] to be set but only [_6a81694b41028a7644a2004feeb763e6.example.com] was passed to validation_record_fqdns. This is because validation_record_fqdns, but the check is done against a list of duplicates, so 1 != 2.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

None.

### References

None.

### PR DESCRIPTION
**Pull request by bflad**
Fixes #3329 (and heavily augments the ACM testing)

ACM will return the same validation record name across two domain validation objects when creating a certificate for the root domain and wildcard for the same domain. Previously `validation_record_fqdns` (always a set of 1 in this case) was trying to deeply equal the domain validation record names (a list of 2), which is impossible to workaround. This PR makes the domain validation record names a set for the validation. This also updates the error handling.

Previously the error handling returned (this is the bug that was fixed):
```
--- FAIL: TestAccAwsAcmCertificateValidation_validationRecordFqdnsRootAndWildcard (128.89s)
	testing.go:513: Step 0 error: Error applying: 1 error(s) occurred:

		* aws_acm_certificate_validation.cert: 1 error(s) occurred:

		* aws_acm_certificate_validation.cert: Certificate needs [_219c781bc2b7b0e36289413e77c82bbc.example.com _219c781bc2b7b0e36289413e77c82bbc.example.com] to be set but only [_219c781bc2b7b0e36289413e77c82bbc.example.com] was passed to validation_record_fqdns
```

Now returns missing records via multierror along with the associated domain name, which should be very helpful for those with high SAN count:
```
		* aws_acm_certificate_validation.cert: 2 error(s) occurred:

		* missing tf-acc-8703199145279883318.example.com DNS validation record: _b700c37a7e02189fd014362b37e2ba68.tf-acc-8703199145279883318.example.com
		* missing tf-acc-san-8703199145279883318.example.com DNS validation record: _ee97edac7b32d661f2e43e4cbc99eae6.tf-acc-san-8703199145279883318.example.com
```

Passes testing locally:
```
make testacc TEST=./aws TESTARGS='-run=TestAccAwsAcmCertificate_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAwsAcmCertificate_ -timeout 120m
=== RUN   TestAccAwsAcmCertificate_emailValidation
--- PASS: TestAccAwsAcmCertificate_emailValidation (17.08s)
=== RUN   TestAccAwsAcmCertificate_dnsValidation
--- PASS: TestAccAwsAcmCertificate_dnsValidation (16.44s)
=== RUN   TestAccAwsAcmCertificate_root
--- PASS: TestAccAwsAcmCertificate_root (15.04s)
=== RUN   TestAccAwsAcmCertificate_rootAndWildcardSubjectAlternativeName
--- PASS: TestAccAwsAcmCertificate_rootAndWildcardSubjectAlternativeName (19.28s)
=== RUN   TestAccAwsAcmCertificate_subjectAlternativeName
--- PASS: TestAccAwsAcmCertificate_subjectAlternativeName (21.36s)
=== RUN   TestAccAwsAcmCertificate_subjectAlternativeNames
--- PASS: TestAccAwsAcmCertificate_subjectAlternativeNames (18.03s)
=== RUN   TestAccAwsAcmCertificate_wildcard
--- PASS: TestAccAwsAcmCertificate_wildcard (14.93s)
=== RUN   TestAccAwsAcmCertificate_wildcardAndRootSubjectAlternativeName
--- PASS: TestAccAwsAcmCertificate_wildcardAndRootSubjectAlternativeName (19.80s)
=== RUN   TestAccAwsAcmCertificate_tags
--- PASS: TestAccAwsAcmCertificate_tags (40.03s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	182.029s

make testacc TEST=./aws TESTARGS='-run=TestAccAwsAcmCertificateValidation_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAwsAcmCertificateValidation_ -timeout 120m
=== RUN   TestAccAwsAcmCertificateValidation_basic
--- PASS: TestAccAwsAcmCertificateValidation_basic (227.62s)
=== RUN   TestAccAwsAcmCertificateValidation_validationRecordFqdns
--- PASS: TestAccAwsAcmCertificateValidation_validationRecordFqdns (140.92s)
=== RUN   TestAccAwsAcmCertificateValidation_validationRecordFqdnsRoot
--- PASS: TestAccAwsAcmCertificateValidation_validationRecordFqdnsRoot (196.60s)
=== RUN   TestAccAwsAcmCertificateValidation_validationRecordFqdnsRootAndWildcard
--- PASS: TestAccAwsAcmCertificateValidation_validationRecordFqdnsRootAndWildcard (146.92s)
=== RUN   TestAccAwsAcmCertificateValidation_validationRecordFqdnsSan
--- PASS: TestAccAwsAcmCertificateValidation_validationRecordFqdnsSan (212.38s)
=== RUN   TestAccAwsAcmCertificateValidation_validationRecordFqdnsWildcard
--- PASS: TestAccAwsAcmCertificateValidation_validationRecordFqdnsWildcard (171.43s)
=== RUN   TestAccAwsAcmCertificateValidation_validationRecordFqdnsWildcardAndRoot
--- PASS: TestAccAwsAcmCertificateValidation_validationRecordFqdnsWildcardAndRoot (147.40s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	1243.333s
```

### CODE REVIEW

File: aws/resource_aws_acm_certificate_test.go [hunk 1]
```diff
@@ -74,7 +74,13 @@ func TestAccAwsAcmCertificate_dnsValidation(t *testing.T) {
 				Check: resource.ComposeTestCheckFunc(
 					resource.TestMatchResourceAttr("aws_acm_certificate.cert", "arn", certificateArnRegex),
 					resource.TestCheckResourceAttr("aws_acm_certificate.cert", "domain_name", domain),
+					resource.TestCheckResourceAttr("aws_acm_certificate.cert", "domain_validation_options.#", "1"),
+					resource.TestCheckResourceAttr("aws_acm_certificate.cert", "domain_validation_options.0.domain_name", domain),
+					resource.TestCheckResourceAttrSet("aws_acm_certificate.cert", "domain_validation_options.0.resource_record_name"),
+					resource.TestCheckResourceAttr("aws_acm_certificate.cert", "domain_validation_options.0.resource_record_type", "CNAME"),
+					resource.TestCheckResourceAttrSet("aws_acm_certificate.cert", "domain_validation_options.0.resource_record_value"),
 					resource.TestCheckResourceAttr("aws_acm_certificate.cert", "subject_alternative_names.#", "0"),
+					resource.TestCheckResourceAttr("aws_acm_certificate.cert", "validation_emails.#", "0"),
```
Comment (radeksimko) [inline aws/resource_aws_acm_certificate_test.go]: 👍

File: aws/resource_aws_acm_certificate_test.go [hunk 2]
```diff
@@ -87,17 +93,83 @@ func TestAccAwsAcmCertificate_dnsValidation(t *testing.T) {
...
+			resource.TestStep{
+				ResourceName:      "aws_acm_certificate.cert",
+				ImportState:       true,
+				ImportStateVerify: true,
+			},
+		},
+	})
+}
+
+func TestAccAwsAcmCertificate_subjectAlternativeName(t *testing.T) {
```
Comment (radeksimko) [inline aws/resource_aws_acm_certificate_test.go]: Nitpick: I'd perhaps pick different names for `TestAccAwsAcmCertificate_subjectAlternativeName` and `TestAccAwsAcmCertificate_subjectAlternativeNames` below so we can run the first one in isolation if we want to.

e.g. `TestAccAwsAcmCertificate_subjectAlternativeName_single` and `TestAccAwsAcmCertificate_subjectAlternativeName_multiple` or we can shorten `subjectAlternativeName` to `SAN` as it's very common to do so.

File: aws/resource_aws_acm_certificate_validation_test.go [hunk 3]
```diff
@@ -31,64 +25,225 @@ func TestAccAwsAcmCertificateValidation_basic(t *testing.T) {
 		Steps: []resource.TestStep{
 			// Test that validation times out if certificate can't be validated
 			resource.TestStep{
-				Config:      testAccAcmCertificateValidation_basic(domain),
+				Config:      testAccAcmCertificateValidation_timeout(domain),
```
Comment (radeksimko) [inline aws/resource_aws_acm_certificate_validation_test.go]: Nitpick: I'd expect `_basic` test to be _actually_ basic and this timeout logic to be exercised perhaps in a separate test.

File: aws/resource_aws_acm_certificate_validation_test.go [hunk 4]
```diff
@@ -31,64 +25,225 @@ func TestAccAwsAcmCertificateValidation_basic(t *testing.T) {
...
+
+func testAccAcmCertificateValidation_timeout(domainName string) string {
 	return fmt.Sprintf(`
 %s
 
 resource "aws_acm_certificate_validation" "cert" {
   certificate_arn = "${aws_acm_certificate.cert.arn}"
   timeouts {
-    create = "20s"
+    create = "5s"
```
Comment (radeksimko) [inline aws/resource_aws_acm_certificate_validation_test.go]: 👍

File: aws/resource_aws_acm_certificate_test.go [hunk 5]
```diff
@@ -17,16 +17,19 @@ import (
 
 var certificateArnRegex = regexp.MustCompile(`^arn:aws:acm:[^:]+:[^:]+:certificate/.+$`)
 
-func TestAccAwsAcmCertificate_emailValidation(t *testing.T) {
+func testAccAwsAcmCertificateDomainFromEnv(t *testing.T) string {
 	if os.Getenv("ACM_CERTIFICATE_ROOT_DOMAIN") == "" {
 		t.Skip("Environment variable ACM_CERTIFICATE_ROOT_DOMAIN is not set")
 	}
+	return os.Getenv("ACM_CERTIFICATE_ROOT_DOMAIN")
```
Comment (radeksimko) [inline aws/resource_aws_acm_certificate_test.go]: Can you add any brief instructions in a comment on what is this domain in case it's not clear from the ENV variable name?

e.g.

```go
// ACM_CERTIFICATE_ROOT_DOMAIN is a domain that was previously registered
// and successfully verified via ACM either via email or DNS
// See https://us-west-2.console.aws.amazon.com/acm/home
```
Also I assume the verification only needs to be done for the TLD (root) domain (e.g. `terraformtesting.com`), not for SAN or anything else?

File: aws/resource_aws_acm_certificate_test.go (hunk 2 above)
Comment (bflad) [reply aws/resource_aws_acm_certificate_test.go]: I'll do both 😄

File: aws/resource_aws_acm_certificate_validation_test.go (hunk 3 above)
Comment (bflad) [reply aws/resource_aws_acm_certificate_validation_test.go]: Valid point, I'll separate

File: aws/resource_aws_acm_certificate_test.go (hunk 5 above)
Comment (bflad) [reply aws/resource_aws_acm_certificate_test.go]: Unfortunately, its more complicated then that. Its per domain in each certificate request done via email validation. So if I request foo.example.com and bar.example.com with email validation, I will get two approval emails for that single request. If I go to renew them, I have to click the emails again. Hence why everyone was clamoring for DNS validation 😁

Comment (bflad) [reply aws/resource_aws_acm_certificate_test.go]: But I'll definitely add information about the environment variable, its non-descriptive at the moment.

**Comment by bflad** [comment]
This has been released in [version 1.10.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1100-february-24-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
