### PR TITLE
resource/aws_network_interface: Refresh private_ips_count into Terraform state and allow updates from 0 to greater than 0

### LINKED ISSUE #3210: Changing aws_network_interface param private_ips_count has no effect
### Terraform Version
```
Terraform v0.11.2
+ provider.aws v1.8.0
```
### Affected Resource(s)
aws_network_interface

### Terraform Configuration Files
```hcl
resource "aws_network_interface" "privnic" {
  private_ips_count = 3
  ...
```

### Expected Behavior
Once the interface has been created, adding/increasing the private_ips_count parameter should cause the provider to allocate additional IP addresses to that ENI.

### Actual Behavior
When trying to use the expected new IP (as ${aws_network_interface.privnic.private_ips[2]}) Terraform throws an error:
```
Error: Error asking for user input: 1 error(s) occurred:

* local.nsvars: local.nsvars: index 2 out of range for list aws_network_interface.privnic.private_ips (max 2) in:

${aws_network_interface.privnic.private_ips[2]}
```

### Steps to Reproduce
The interface was originally created with private_ips_count = 2. This has now been increased to 3 and the new one cannot be used, as per the actual behavior section.

### PR DESCRIPTION
**Pull request by bflad**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #3210

The Terraform 0.12 Provider SDK acceptance testing was catching that the `private_ips_count` attribute (used to signify _secondary_ private IPs) was not properly being read into the Terraform state during import.

Previous output from Terraform 0.12 Provider SDK acceptance testing:

```
--- FAIL: TestAccAWSENI_importBasic (13.57s)
    testing.go:568: Step 1 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.

        (map[string]string) {
        }

        (map[string]string) (len=1) {
         (string) (len=17) "private_ips_count": (string) (len=1) "0"
        }
```

To fix this particular issue, we prefer to always read this attribute into the Terraform state during `Read`. While looking through previous bug reports for this attribute, came across a report that the resource was not properly updating the count when going from 0 to greater than 0. Added a covering acceptance test and fixed the update logic.

Previous output from acceptance testing before `private_ips_count` update logic changes:

```
--- FAIL: TestAccAWSENI_PrivateIpsCount (82.51s)
    testing.go:568: Step 6 error: Check failed: Check 2/2 error: aws_network_interface.test: Attribute 'private_ips_count' expected "1", got "0"
```

Output from Terraform 0.11 Provider SDK acceptance testing:

```
--- PASS: TestAccAWSENI_computedIPs (33.48s)
--- PASS: TestAccAWSENI_sourceDestCheck (35.03s)
--- PASS: TestAccAWSENI_disappears (36.04s)
--- PASS: TestAccAWSENI_basic (39.30s)
--- PASS: TestAccAWSENI_updatedDescription (64.26s)
--- PASS: TestAccAWSENI_PrivateIpsCount (90.29s)
--- PASS: TestAccAWSENI_ignoreExternalAttachment (119.86s)
--- PASS: TestAccAWSENI_attached (257.95s)
```

Output from Terraform 0.12 Provider SDK acceptance testing:

```
--- PASS: TestAccAWSENI_computedIPs (35.09s)
--- PASS: TestAccAWSENI_sourceDestCheck (36.54s)
--- PASS: TestAccAWSENI_disappears (37.25s)
--- PASS: TestAccAWSENI_basic (39.92s)
--- PASS: TestAccAWSENI_updatedDescription (64.87s)
--- PASS: TestAccAWSENI_PrivateIpsCount (91.51s)
--- PASS: TestAccAWSENI_ignoreExternalAttachment (121.11s)
--- PASS: TestAccAWSENI_attached (261.48s)
```

### CODE REVIEW

File: aws/resource_aws_network_interface.go [hunk 1]
```diff
@@ -165,25 +165,36 @@ func resourceAwsNetworkInterfaceRead(d *schema.ResourceData, meta interface{}) e
...
 
-	if eni.Description != nil {
-		d.Set("description", eni.Description)
+	if err := d.Set("private_ips", flattenNetworkInterfacesPrivateIPAddresses(eni.PrivateIpAddresses)); err != nil {
+		return fmt.Errorf("error setting private_ips: %s", err)
 	}
 
-	// Tags
-	d.Set("tags", tagsToMap(eni.TagSet))
+	d.Set("private_ips_count", len(eni.PrivateIpAddresses)-1)
```
Comment (nywilken) [inline aws/resource_aws_network_interface.go]: Why the need to subtract 1 from the total count?

Comment (nywilken) [reply aws/resource_aws_network_interface.go]: Information documented on https://www.terraform.io/docs/providers/aws/r/network_interface.html#private_ips_count :+1:
