### PR TITLE
resource/aws_dynamodb_table: Refactoring

### LINKED ISSUE #566: DynamoDB index non_key_attributes changes remain unrecognised
_This issue was originally opened by @sebolabs as hashicorp/terraform#12297. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version
0.8.7

### Affected Resource(s)
- aws_dynamodb_table

### Original resource definition
```hcl
resource "aws_dynamodb_table" "my_table" {
  name           = "my_table"
  read_capacity  = "1"
  write_capacity = "1"
  hash_key       = "email"
  range_key      = "firstname"
  attribute {
    name = "id"
    type = "S"
  }
  attribute {
    name = "email"
    type = "S"
  }
  attribute {
    name = "firstname"
    type = "S"
  }
  attribute {
    name = "nickname"
    type = "S"
  }
  global_secondary_index {
    name               = "Index1"
    hash_key           = "nickname"
    read_capacity      = "1"
    write_capacity     = "1"
    projection_type    = "INCLUDE"
    non_key_attributes = [ "id" ]
  }
  global_secondary_index {
    name               = "Index2"
    hash_key           = "id"
    read_capacity      = "1"
    write_capacity     = "1"
    projection_type    = "INCLUDE"
    non_key_attributes = [ "name" ]
  }
```

### Change
Index1:
```
-    non_key_attributes = [ "id" ]
+    non_key_attributes = [ "id", "name" ]
```

### Expected Behavior
Index should be modified or removed/recreated

### Actual Behavior
Terraform does not recognise this change at all.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` original definition
2. apply the change in the code
3. `terraform plan/apply`

### PR DESCRIPTION
**Pull request by radeksimko**
Firstly apologies for the big diff that can be hard to read 🙈 

## Why

Aka what lead me to refactor this resource:

1. Existing LOC in `aws/resource_aws_dynamodb_table.go` - reduced roughly by half (from 1155 to 657)
2. Complex and deeply nested logic for updating `global_secondary_index` inside CRUD. This was extracted into `diffDynamoDbGSI` + is now tested thoroughly, which coincidentally resulted in fixing #566 (acceptance test also attached to verify)
3. Poor readability of the code making it hard to reason about it. Reduced by applying "single responsibility principle" on best-effort basis - i.e. one function does one thing - which also helped reducing the interface of many functions to bare minimum and reuse functions more.
4. Non-standard custom retry logic w/ `time.Sleep` - replaced by `resource.Retry` & `resource.StateConf` per conventions
5. We might need to modify the schema & introduce deprecations at some point to address  https://github.com/terraform-providers/terraform-provider-aws/issues/556 or https://github.com/terraform-providers/terraform-provider-aws/issues/671 which should be much easier after this refactoring as adding backward-compatibility layers will be easier.
6. #1378 was (unfortunately) inspired by some of the code I'd consider non-ideal (like custom retry logic)

## Test results

```
=== RUN   TestAccAWSDynamoDbTable_importBasic
--- PASS: TestAccAWSDynamoDbTable_importBasic (41.27s)
=== RUN   TestAccAWSDynamoDbTable_importTags
--- PASS: TestAccAWSDynamoDbTable_importTags (41.39s)
=== RUN   TestAccAWSDynamoDbTable_importTimeToLive
--- PASS: TestAccAWSDynamoDbTable_importTimeToLive (78.83s)
=== RUN   TestAccAWSDynamoDbTable_tags
--- PASS: TestAccAWSDynamoDbTable_tags (79.44s)
=== RUN   TestAccAWSDynamoDbTable_ttl
--- PASS: TestAccAWSDynamoDbTable_ttl (122.97s)
=== RUN   TestAccAWSDynamoDbTable_gsiUpdateCapacity
--- PASS: TestAccAWSDynamoDbTable_gsiUpdateCapacity (128.27s)
=== RUN   TestAccAWSDynamoDbTable_streamSpecification
--- PASS: TestAccAWSDynamoDbTable_streamSpecification (141.56s)
=== RUN   TestAccAWSDynamoDbTable_gsiUpdateNonKeyAttributes
--- PASS: TestAccAWSDynamoDbTable_gsiUpdateNonKeyAttributes (296.13s)
=== RUN   TestAccAWSDynamoDbTable_basic
--- PASS: TestAccAWSDynamoDbTable_basic (297.49s)
=== RUN   TestAccAWSDynamoDbTable_gsiUpdateOtherAttributes
--- PASS: TestAccAWSDynamoDbTable_gsiUpdateOtherAttributes (606.13s)
```

Fixes #566

### CODE REVIEW

File: aws/resource_aws_dynamodb_table_test.go [hunk 1]
```diff
@@ -103,7 +392,33 @@ func TestAccAWSDynamoDbTable_gsiUpdate(t *testing.T) {
 				),
 			},
 			{
-				Config: testAccAWSDynamoDbConfigGsiUpdated(name),
+				Config: testAccAWSDynamoDbConfigGsiUpdatedOtherAttributes(name),
+				Check: resource.ComposeTestCheckFunc(
```
Comment (bflad) [inline aws/resource_aws_dynamodb_table_test.go]: Should we have additional attribute checks in here and after the update?

```
resource.TestCheckResourceAttr("aws_dynamodb_table.test", "global_secondary_index.####.hash_key", "att4"),
resource.TestCheckResourceAttr("aws_dynamodb_table.test", "global_secondary_index.####.range_key", "att4"),
```

File: aws/resource_aws_dynamodb_table_test.go [hunk 2]
```diff
@@ -103,7 +392,33 @@ func TestAccAWSDynamoDbTable_gsiUpdate(t *testing.T) {
...
+		Steps: []resource.TestStep{
+			{
+				Config: testAccAWSDynamoDbConfigGsiUpdatedOtherAttributes(name),
+				Check: resource.ComposeTestCheckFunc(
+					testAccCheckInitialAWSDynamoDbTableExists("aws_dynamodb_table.test", &conf),
+				),
+			},
+			{
+				Config: testAccAWSDynamoDbConfigGsiUpdatedNonKeyAttributes(name),
 				Check: resource.ComposeTestCheckFunc(
```
Comment (bflad) [inline aws/resource_aws_dynamodb_table_test.go]: Should we have additional attribute checks in here and after the update?

```
resource.TestCheckResourceAttr("aws_dynamodb_table.test", "global_secondary_index.####.non_key_attributes.#", "1"),
resource.TestCheckResourceAttr("aws_dynamodb_table.test", "global_secondary_index.####.non_key_attributes.0", "RandomAttribute"),
```

and

```
resource.TestCheckResourceAttr("aws_dynamodb_table.test", "global_secondary_index.####.non_key_attributes.#", "2"),
resource.TestCheckResourceAttr("aws_dynamodb_table.test", "global_secondary_index.####.non_key_attributes.0", "RandomAttribute"),
resource.TestCheckResourceAttr("aws_dynamodb_table.test", "global_secondary_index.####.non_key_attributes.1", "AnotherAttribute"),
```

File: aws/structure.go [hunk 3]
```diff
@@ -3074,3 +3075,306 @@ func flattenMqBrokerInstances(instances []*mq.BrokerInstance) []interface{} {
...
+				Delete: &dynamodb.DeleteGlobalSecondaryIndexAction{
+					IndexName: aws.String(idxName),
+				},
+			})
+		}
+	}
+	return
+}
+
+func stripCapacityAttributes(in map[string]interface{}) map[string]interface{} {
```
Comment (bflad) [inline aws/structure.go]: Could this be simplified with this and also make it more future proof? (not sure if you need to copy the map first)
```
delete(in, "read_capacity")
delete(in, "write_capacity")
```

File: aws/structure.go [hunk 4]
```diff
@@ -3074,3 +3075,306 @@ func flattenMqBrokerInstances(instances []*mq.BrokerInstance) []interface{} {
...
+}
+
+// Expanders + flatteners
+
+func flattenDynamoDbTtl(ttlDesc *dynamodb.TimeToLiveDescription) []interface{} {
+	m := map[string]interface{}{}
+	if ttlDesc.AttributeName != nil {
+		m["attribute_name"] = *ttlDesc.AttributeName
+		if ttlDesc.TimeToLiveStatus != nil {
+			m["enabled"] = (*ttlDesc.TimeToLiveStatus == dynamodb.TimeToLiveStatusEnabled)
```
Comment (bflad) [inline aws/structure.go]: While this logic as it currently stands is correct for strictly the ENABLED status, I'm not sure if we need to consider setting this to `false` for other scenarios: nil, ENABLING, DISABLING, DISABLED

File: aws/structure.go [hunk 5]
```diff
@@ -3074,3 +3075,306 @@ func flattenMqBrokerInstances(instances []*mq.BrokerInstance) []interface{} {
...
+			"type": *attrdef.AttributeType,
+		}
+		attributes = append(attributes, attribute)
+	}
+
+	d.Set("attribute", attributes)
+	d.Set("name", table.TableName)
+
+	for _, attribute := range table.KeySchema {
+		if *attribute.KeyType == "HASH" {
```
Comment (bflad) [inline aws/structure.go]: Nitpick: `dynamodb.KeyTypeHash` and `dynamodb.KeyTypeRange` constants are available

File: aws/structure.go [hunk 6]
```diff
@@ -3074,3 +3075,306 @@ func flattenMqBrokerInstances(instances []*mq.BrokerInstance) []interface{} {
...
+// TODO: Get rid of keySchemaM - the user should just explicitely define
+// this in the config, we shouldn't magically be setting it like this.
+// Removal will however require config change, hence BC. :/
+func expandDynamoDbLocalSecondaryIndexes(cfg []interface{}, keySchemaM map[string]interface{}) []*dynamodb.LocalSecondaryIndex {
+	indexes := make([]*dynamodb.LocalSecondaryIndex, len(cfg), len(cfg))
+	for i, lsi := range cfg {
+		m := lsi.(map[string]interface{})
+		idxName := m["name"].(string)
+
+		// TODO: Remove this (BC)
```
Comment (bflad) [inline aws/structure.go]: Please create an associated issue and add it to the comment if its important 😄

File: aws/structure.go [hunk 7]
```diff
@@ -3074,3 +3075,306 @@ func flattenMqBrokerInstances(instances []*mq.BrokerInstance) []interface{} {
...
+	return projection
+}
+
+func expandDynamoDbKeySchema(data map[string]interface{}) []*dynamodb.KeySchemaElement {
+	keySchema := []*dynamodb.KeySchemaElement{}
+
+	if v, ok := data["hash_key"]; ok && v != nil && v != "" {
+		keySchema = append(keySchema, &dynamodb.KeySchemaElement{
+			AttributeName: aws.String(v.(string)),
+			KeyType:       aws.String("HASH"),
```
Comment (bflad) [inline aws/structure.go]: Nitpick: Another reminder for `dynamodb.KeyTypeHash` and `dynamodb.KeyTypeRange` 😄

File: aws/resource_aws_dynamodb_table.go [hunk 8]
```diff
@@ -212,943 +197,464 @@ func resourceAwsDynamoDbTable() *schema.Resource {
...
-				if err := createTableTags(d, meta); err != nil {
-					return err
-				}
-			}
+	d.SetId(*output.TableDescription.TableName)
+	d.Set("arn", output.TableDescription.TableArn)
 
-			return resourceAwsDynamoDbTableRead(d, meta)
-		}
+	if err := waitForDynamoDbTableToBeActive(d.Id(), 10*time.Minute, conn); err != nil {
```
[the remark this answers is not in the document]
Comment (radeksimko) [reply aws/resource_aws_dynamodb_table.go]: I had that in the original PR but removed it to keep the PR's scope minimal, ideally no-op. But agreed otherwise.

File: aws/resource_aws_dynamodb_table.go [hunk 9]
```diff
@@ -212,943 +197,464 @@ func resourceAwsDynamoDbTable() *schema.Resource {
...
-		keyschema = append(keyschema, range_schema_element)
-	}
+	log.Printf("[DEBUG] Creating DynamoDB table with key schema: %#v", keySchemaMap)
 
 	req := &dynamodb.CreateTableInput{
-		TableName:             aws.String(name),
-		ProvisionedThroughput: throughput,
-		KeySchema:             keyschema,
+		TableName: aws.String(d.Get("name").(string)),
+		ProvisionedThroughput: &dynamodb.ProvisionedThroughput{
```
[the remark this answers is not in the document]
Comment (radeksimko) [reply aws/resource_aws_dynamodb_table.go]: Good catch - I'll unify that all to `expandDynamoDbProvisionedThroughput` 👍

File: aws/resource_aws_dynamodb_table.go [hunk 10]
```diff
@@ -212,943 +197,464 @@ func resourceAwsDynamoDbTable() *schema.Resource {
...
-	readCapacity := (*data)["read_capacity"].(int)
+	result := tagsToMapDynamoDb(output.Tags)
 
-	key_schema := []*dynamodb.KeySchemaElement{
-		{
-			AttributeName: aws.String((*data)["hash_key"].(string)),
-			KeyType:       aws.String("HASH"),
-		},
-	}
+	// TODO Read NextToken if available
```
[the remark this answers is not in the document]
Comment (radeksimko) [reply aws/resource_aws_dynamodb_table.go]: Well, it's not, really - is it? 🤔  I assume it's something to be addressed eventually so we can handle tables with _many_ tags, but I intentionally left that for a different PR to keep this one focused on refactoring mainly.

File: aws/structure.go (hunk 3 above)
Comment (radeksimko) [reply aws/structure.go]: Yeah, I wanted to avoid copying it, but you're right - the name suggests the function does that, so we should do it. 👌

File: aws/structure.go (hunk 6 above)
Comment (radeksimko) [reply aws/structure.go]: https://github.com/terraform-providers/terraform-provider-aws/issues/3176 Will add that to the comment.

File: aws/structure.go (hunk 4 above)
Comment (radeksimko) [reply aws/structure.go]: Since the field is `TypeBool` it's `false` by default, so we shouldn't need to.
