### PR TITLE
resource/api_gateway_method_settings: keep throttling disabled by default 

### LINKED ISSUE #5690: `aws_api_gateway_method_settings` disable throttling when removing optional attributes
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
→ terraform -v
Terraform v0.11.2
+ provider.aws v1.33.0
```

### Affected Resource(s)

* `aws_api_gateway_method_settings`

### Terraform Configuration Files

Below is a full deployable example. The main part we care about are the throttling attributes in the `aws_api_gateway_method_settings` resource.

```hcl
provider "aws" {
  region = "us-east-1"
}

resource "aws_api_gateway_rest_api" "rest_api" {
  name = "rest-api"
}

resource "aws_api_gateway_method" "rest_api-any-method" {
  rest_api_id   = "${aws_api_gateway_rest_api.rest_api.id}"
  resource_id   = "${aws_api_gateway_resource.rest_api-resource.id}"
  http_method   = "ANY"
  authorization = "NONE"
}

resource "aws_api_gateway_integration" "rest_api-post-integration" {
  rest_api_id             = "${aws_api_gateway_rest_api.rest_api.id}"
  resource_id             = "${aws_api_gateway_resource.rest_api-resource.id}"
  http_method             = "${aws_api_gateway_method.rest_api-any-method.http_method}"
  type                    = "HTTP_PROXY"
  integration_http_method = "${aws_api_gateway_method.rest_api-any-method.http_method}"
  passthrough_behavior    = "WHEN_NO_MATCH"
  uri                     = "https://httpbin.org/get"
}

resource "aws_api_gateway_resource" "rest_api-resource" {
  rest_api_id = "${aws_api_gateway_rest_api.rest_api.id}"
  parent_id   = "${aws_api_gateway_rest_api.rest_api.root_resource_id}"
  path_part   = "gateway"
}

resource "aws_api_gateway_method_settings" "settings" {
  rest_api_id = "${aws_api_gateway_rest_api.rest_api.id}"
  stage_name  = "${aws_api_gateway_stage.stage.stage_name}"
  method_path = "*/*"

  settings = {
    # Set throttling values
    throttling_burst_limit = 1000
    throttling_rate_limit  = 5000

    metrics_enabled = true

    # Actually disable throttling
    #throttling_burst_limit = -1
    #throttling_rate_limit  = -1
  }
}

resource "aws_api_gateway_stage" "stage" {
  stage_name    = "dev"
  rest_api_id   = "${aws_api_gateway_rest_api.rest_api.id}"
  deployment_id = "${aws_api_gateway_deployment.rest_api-deploy.id}"
}

resource "aws_api_gateway_deployment" "rest_api-deploy" {
  rest_api_id = "${aws_api_gateway_rest_api.rest_api.id}"
  stage_name  = ""
}
```

### Debug Output

When removing the `throttling_burst_limit` or `throttling_rate_limit` fields it sets them to zero instead of `-1` to disable them.

```
  ~ aws_api_gateway_method_settings.settings
      settings.0.throttling_burst_limit: "-1" => "0"
      settings.0.throttling_rate_limit:  "-1" => "0"
```

### Panic Output

N/A

### Expected Behavior

When the fields are remove it should set them to `-1` instead to correctly disable them.

### Actual Behavior

When the fields are removed it sets the values to `0`.

### Steps to Reproduce

1. `terraform apply` (I don't have the above example perfectly setup and it has an error the first time. May need to be applied twice to correctly create all resources).
2. `aws apigateway get-stage --rest-api-id <id> --stage-name dev` Get the current settings
3. Remove the throttling fields and `terraform apply`
4. `aws apigateway get-stage --rest-api-id <id> --stage-name dev` Get the current settings

### Important Factoids

The `-1` isn't documented by amazon ☹️. I don't know what the interaction between the two fields if only one is correctly disabled. I assume they should always be disabled together.

### References

* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-stage-methodsetting.html#cfn-apigateway-stage-methodsetting-throttlingburstlimit

### PR DESCRIPTION
**Pull request by anGie44**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #5690 

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/api_gateway_method_settings: default throttling_burst_limit and throttling_rate_limit arguments to -1 to disable throttling
```

Output from acceptance testing:

```
--- PASS: TestAccAWSAPIGatewayMethodSettings_basic (650.25s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_MetricsEnabled (681.00s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_CachingEnabled (681.11s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_CacheTtlInSeconds (681.64s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_LoggingLevel (750.28s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_Multiple (1040.26s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_DataTraceEnabled (1126.60s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_CacheDataEncrypted (1127.94s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_UnauthorizedCacheControlHeaderStrategy (779.89s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_RequireAuthorizationForCacheControl (793.58s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_ThrottlingBurstLimitDisabledByDefault (35.11s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_ThrottlingBurstLimit (35.11s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_ThrottlingRateLimitDisabledByDefault (35.11s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_ThrottlingRateLimit (35.11s)
```

### CODE REVIEW

File: aws/resource_aws_api_gateway_method_settings.go [hunk 1]
```diff
@@ -266,3 +271,18 @@ func resourceAwsApiGatewayMethodSettingsDelete(d *schema.ResourceData, meta inte
 
 	return nil
 }
+
+func resourceAwsApiGatewayMethodSettingsImport(d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
+	idParts := strings.Split(d.Id(), ":")
```
Comment (bflad) [inline aws/resource_aws_api_gateway_method_settings.go:276]: I'd recommend using `/` as the separator with `strings.SplitN()` to match other API Gateway resources 👍

**Comment by anGie44** [comment]
Separator updated to `/`

Output of acceptance tests:
```
--- PASS: TestAccAWSAPIGatewayMethodSettings_basic (586.91s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_ThrottlingRateLimitDisabledByDefault (725.44s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_RequireAuthorizationForCacheControl (757.76s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_ThrottlingBurstLimitDisabledByDefault (757.97s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_CachingEnabled (818.33s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_Multiple (821.91s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_LoggingLevel (884.19s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_ThrottlingBurstLimit (967.64s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_UnauthorizedCacheControlHeaderStrategy (988.92s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_ThrottlingRateLimit (1013.04s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_MetricsEnabled (1216.38s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_CacheDataEncrypted (1256.57s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_DataTraceEnabled (1388.51s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_CacheTtlInSeconds (1694.12s)
```
