### PR TITLE
Fixes root_resource_id not being set on Api Gateway Rest API data source

### LINKED ISSUE #11695: Api Gateway Data Source can fail to set root_resource_id attribute if the API contains more than 25 routes.
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Tested on TF version 0.11.14 and provider version 2.44.0

### Affected Resource(s)

* data.aws_api_gateway_rest_api

### Expected Behavior

The AWS provider should set the root_resource_id regardless of the number of routes on the API.

### Actual Behavior

The GetResources call currently being used in the ApiGateway resource only returns a default 25 routes. It then iterates over those 25 routes looking for the root route ("/") and sets the attribute when found. If there are more than 25 routes on the API it can incorrectly fail to set the root_resource_id.

Code in question: https://github.com/terraform-providers/terraform-provider-aws/blob/v2.45.0/aws/data_source_aws_api_gateway_rest_api.go#L58-L70

Fix is pretty simple as the AWS Go SDK offers a paginated GetResourcePages call. We just paginate through the resources applying the same logic and stop pagination when the root is found. I'll submit a follow up PR after creating the issue, just wanted to get it documented :)

### Steps to Reproduce

This is somewhat tricky to reproduce exactly as I'm not entirely sure how AWS determines in what order to return the routes on the API. However you can create an API with > 25 routes and add a small debug statement in the Code linked above and see it will only ever look through at most 25 routes in its current state.

### PR DESCRIPTION
**Pull request by Jacob-Laverty**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #11695 

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
* Fixes a bug in aws_api_gateway_rest_api data source where root_resource_id attribute would fail to be set for some APIs with more than 25 routes.
```

Output from acceptance testing:

```
make testacc TEST=./aws TESTARGS='-run=TestAccDataSourceAwsApiGatewayRestApi'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccDataSourceAwsApiGatewayRestApi -timeout 120m
=== RUN   TestAccDataSourceAwsApiGatewayRestApi
=== PAUSE TestAccDataSourceAwsApiGatewayRestApi
=== CONT  TestAccDataSourceAwsApiGatewayRestApi
--- PASS: TestAccDataSourceAwsApiGatewayRestApi (15.27s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	15.364s
...
```

### CODE REVIEW

File: aws/data_source_aws_api_gateway_rest_api.go [hunk 1]
```diff
@@ -55,18 +55,22 @@ func dataSourceAwsApiGatewayRestApiRead(d *schema.ResourceData, meta interface{}
...
+		for _, item := range page.Items {
+			if *item.Path == "/" {
+				d.Set("root_resource_id", item.Id)
+				return false
+			}
 		}
+		return !lastPage
+	})
+
+	if err != nil {
```
Comment (avoidik) [inline aws/data_source_aws_api_gateway_rest_api.go]: why not just `return err`? :-)
