### PR TITLE
resource/aws_kinesis_stream: Handle tag additions/removals of more than 10 tags

### LINKED ISSUE #4562: Can't apply more than 10 tags to resource "aws_kinesis_stream"
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.7
+ provider.aws v1.18.0

### Affected Resource(s)
aws_kinesis_stream

### Terraform Configuration Files

```hcl
provider "aws" {
  region  = "us-east-1"
  profile = "develop"
}

resource "aws_kinesis_stream" "kinesis_stream" {
  name             = "terraform_tags_test_stream"
  count            = 1
  shard_count      = 1
  retention_period = 24

  shard_level_metrics = [
    "IncomingBytes",
    "OutgoingRecords",
    "IteratorAgeMilliseconds",
    "IncomingRecords",
    "ReadProvisionedThroughputExceeded",
    "WriteProvisionedThroughputExceeded",
    "OutgoingBytes"
  ]

  tags {
    tag1  = "tag1"
    tag2  = "tag2"
    tag3  = "tag3"
    tag4  = "tag4"
    tag5  = "tag5"
    tag6  = "tag6"
    tag7  = "tag7"
    tag8  = "tag8"
    tag9  = "tag9"
    tag10  = "tag10"
    tag11  = "tag11"
  }
}
```

### Debug Output

https://gist.github.com/ddpalmer/1d403c3516b0de8c0f4abca8dc74144e

### Panic Output

None

### Expected Behavior

aws_kinesis_stream resource created with 11 tags.

### Actual Behavior

Tags create failed with error message: 'tags' failed to satisfy constraint: Member must have length less than or equal to 10

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Nothing special

### References

Per AWS documentation kinesis streams may have up to 50 tags, however only 10 tags may be applied at a time. https://docs.aws.amazon.com/kinesis/latest/APIReference/API_AddTagsToStream.html

* #0000

### PR DESCRIPTION
**Pull request by bflad**
Fixes #4562

Changes proposed in this pull request:

* Batch tag additions into groups of 10 to match API requirement
* Batch tag removals into groups of 10 to match API requirement

Previously:

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSKinesisStream_Tags'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSKinesisStream_Tags -timeout 120m
=== RUN   TestAccAWSKinesisStream_Tags
--- FAIL: TestAccAWSKinesisStream_Tags (26.75s)
	testing.go:518: Step 0 error: Error applying: 1 error(s) occurred:

		* aws_kinesis_stream.test: 1 error(s) occurred:

		* aws_kinesis_stream.test: ValidationException: 1 validation error detected: Value '{tag1=tag1value, tag20=tag20value, tag8=tag8value, tag10=tag10value, tag21=tag21value, tag9=tag9value, tag11=tag11value, tag6=tag6value, tag12=tag12value, tag7=tag7value, tag13=tag13value, tag4=tag4value, tag14=tag14value, tag5=tag5value, tag15=tag15value, tag2=tag2value, tag16=tag16value, tag3=tag3value, tag17=tag17value, tag18=tag18value, tag19=tag19value}' at 'tags' failed to satisfy constraint: Member must have length less than or equal to 10
			status code: 400, request id: dc1bc791-6394-fcfd-8f63-ce1bafcbaf0d
	testing.go:579: Error destroying resource! WARNING: Dangling resources
		may exist. The full state and error is shown below.

		Error: Error refreshing: 1 error(s) occurred:

		* aws_kinesis_stream.test: 1 error(s) occurred:

		* aws_kinesis_stream.test: aws_kinesis_stream.test: [WARN] Error reading Kinesis Stream: "1 validation error(s) found.", code: "InvalidParameter"

		State: <nil>
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	26.797s
make: *** [testacc] Error 1
```

Output from acceptance testing:

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSKinesisStream_Tags'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSKinesisStream_Tags -timeout 120m
=== RUN   TestAccAWSKinesisStream_Tags
--- PASS: TestAccAWSKinesisStream_Tags (108.99s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	109.030s
```

Full run:

```
10 tests passed (all tests)
=== RUN   TestAccAWSKinesisStream_encryptionWithoutKmsKeyThrowsError
--- PASS: TestAccAWSKinesisStream_encryptionWithoutKmsKeyThrowsError (62.80s)
=== RUN   TestAccAWSKinesisStream_basic
--- PASS: TestAccAWSKinesisStream_basic (75.04s)
=== RUN   TestAccAWSKinesisStream_importBasic
--- PASS: TestAccAWSKinesisStream_importBasic (75.87s)
=== RUN   TestAccAWSKinesisStream_Tags
--- PASS: TestAccAWSKinesisStream_Tags (89.73s)
=== RUN   TestAccAWSKinesisStream_retentionPeriod
--- PASS: TestAccAWSKinesisStream_retentionPeriod (122.32s)
=== RUN   TestAccAWSKinesisStream_shardLevelMetrics
--- PASS: TestAccAWSKinesisStream_shardLevelMetrics (142.56s)
=== RUN   TestAccAWSKinesisStream_encryption
--- PASS: TestAccAWSKinesisStream_encryption (190.55s)
=== RUN   TestAccAWSKinesisStreamDataSource
--- PASS: TestAccAWSKinesisStreamDataSource (210.89s)
=== RUN   TestAccAWSKinesisStream_createMultipleConcurrentStreams
--- PASS: TestAccAWSKinesisStream_createMultipleConcurrentStreams (315.24s)
=== RUN   TestAccAWSKinesisStream_shardCount
--- PASS: TestAccAWSKinesisStream_shardCount (363.95s)
```

### CODE REVIEW

File: aws/tags_kinesis.go [hunk 1]
```diff
@@ -24,34 +24,55 @@ func setTagsKinesis(conn *kinesis.Kinesis, d *schema.ResourceData) error {
...
-			}
 
-			_, err := conn.RemoveTagsFromStream(&kinesis.RemoveTagsFromStreamInput{
-				StreamName: aws.String(sn),
-				TagKeys:    k,
-			})
-			if err != nil {
-				return err
+			// Kinesis requires these operations be split into 10 tag batches
+			tagKeysBatchLimit := 10
```
Comment (mbfrahry) [inline aws/tags_kinesis.go]: Thoughts on pulling this out and making it a constant?

File: aws/tags_kinesis.go [hunk 2]
```diff
@@ -24,34 +24,55 @@ func setTagsKinesis(conn *kinesis.Kinesis, d *schema.ResourceData) error {
...
 			}
 		}
 
 		if len(create) > 0 {
-
 			log.Printf("[DEBUG] Creating tags: %#v", create)
-			t := make(map[string]*string)
+
+			// Kinesis requires these operations be split into 10 tag batches
+			tagsBatchLimit := 10
```
Comment (mbfrahry) [inline aws/tags_kinesis.go]: Same as above

File: aws/tags_kinesis.go (hunk 1 above)
Comment (bflad) [reply aws/tags_kinesis.go]: That seems fair -- I'll update 👍

**Comment by bflad** [comment]
Acceptance tests pass after migrating to constant -- merging once TravisCI agrees!

```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSKinesisStream_Tags'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSKinesisStream_Tags -timeout 120m
=== RUN   TestAccAWSKinesisStream_Tags
--- PASS: TestAccAWSKinesisStream_Tags (120.69s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	120.723s
```

**Comment by bflad** [comment]
This has been released in [version 1.20.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1200-may-23-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
