### PR TITLE
resource/aws_batch_job_definition: Prevent extraneous differences with container properties missing environment, mount point, ulimits, and volumes configuration

### LINKED ISSUE #11998: r/aws_batch_job_definition must always be replaced in 2.48
Hi, I got stuck in a bug using the provider in version `2.48`. `aws_batch_job_definition` is always recreated.

Introduced in https://github.com/terraform-providers/terraform-provider-aws/pull/11488

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.12.20
+ provider.aws v2.48.0
```

### Affected Resource(s)

* aws_batch_job_definition

### Terraform Configuration Files

```hcl
terraform {
  backend "local" {
    path = ".terraform/state/terraform.tfstate"
  }
}

provider "aws" {
  region = "eu-central-1"

  version = "~> 2.40"
}

resource "aws_iam_role" "role" {
  name = "test_example_role"

  assume_role_policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
    {
        "Action": "sts:AssumeRole",
        "Effect": "Allow",
        "Principal": {
        "Service": "ecs-tasks.amazonaws.com"
        }
    }
    ]
}
EOF
}

resource "aws_ecr_repository" "ecr" {
  name = "foo_ecr"
}

resource "aws_batch_job_definition" "test" {
  name = "test"
  type = "container"

  container_properties = <<CONTAINER_PROPERTIES
{
    "command": ["start.py", "Ref::S3bucket", "Ref::S3key"],
    "image": "${aws_ecr_repository.ecr.name}:image",
    "memory": 2048,
    "vcpus": 8,
    "jobRoleArn": "${aws_iam_role.role.arn}"
}
CONTAINER_PROPERTIES
}
```

### Debug Output
https://gist.github.com/theophilechevalier/5b0421ef8ca161c0a7ab82fe630b6179

### Expected Behavior

Resource should not be always recreated.

### Actual Behavior
Resource is always recreated.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. `terraform plan`

### Important Factoids

It works as expected with a provider version `<= 2.47`, so it's a regression.

### PR DESCRIPTION
**Pull request by bflad**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #11998
Reference: https://github.com/terraform-providers/terraform-provider-aws/pull/11488

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
* resource/aws_batch_job_definition: Prevent extraneous differences with container properties missing `environment`, `mountPoints`, `ulimits`, and `volumes` configuration
```

Now that this resource is properly refreshing the `container_properties` attribute into the Terraform state, additional cases have been reported where the API canonicalizes the response with empty arrays. Here we account for `environment`, `mountPoints`, `ulimits`, and `volumes`.

Previous output from unit testing (before code update):

```
2020/02/11 12:37:58 [DEBUG] Canonical Batch Container Properties JSON are not equal.
First: {"command":["start.py","Ref::S3bucket","Ref::S3key"],"image":"example:image","jobRoleArn":"arn:aws:iam::123456789012:role/example","memory":2048,"vcpus":8}
Second: {"command":["start.py","Ref::S3bucket","Ref::S3key"],"environment":[],"image":"example:image","jobRoleArn":"arn:aws:iam::123456789012:role/example","memory":2048,"mountPoints":[],"ulimits":[],"vcpus":8,"volumes":[]}
--- FAIL: TestEquivalentBatchContainerPropertiesJSON (0.00s)
    --- FAIL: TestEquivalentBatchContainerPropertiesJSON/empty_environment,_mountPoints,_ulimits,_and_volumes (0.00s)
        container_properties_test.go:226: got false, expected true
```

Previous output from acceptance testing (before code update):

```
--- FAIL: TestAccAWSBatchJobDefinition_basic (13.16s)
    testing.go:640: Step 0 error: After applying this step, the plan was not empty:

        DIFF:

        DESTROY/CREATE: aws_batch_job_definition.test
          arn:                  "arn:aws:batch:us-west-2:--OMITTED--:job-definition/tf-acc-test-118932874341187373:1" => "<computed>"
          container_properties: "{\"command\":[\"echo\",\"test\"],\"environment\":[],\"image\":\"busybox\",\"memory\":128,\"mountPoints\":[],\"resourceRequirements\":[],\"ulimits\":[],\"vcpus\":1,\"volumes\":[]}" => "{\"command\":[\"echo\",\"test\"],\"image\":\"busybox\",\"memory\":128,\"vcpus\":1}" (forces new resource)
          id:                   "arn:aws:batch:us-west-2:--OMITTED--:job-definition/tf-acc-test-118932874341187373:1" => "<computed>"
          name:                 "tf-acc-test-118932874341187373" => "tf-acc-test-118932874341187373"
          retry_strategy.#:     "0" => "0"
          revision:             "1" => "<computed>"
          timeout.#:            "0" => "0"
          type:                 "container" => "container"
```

Output from acceptance testing:

```
--- PASS: TestAccAWSBatchJobDefinition_basic (16.80s)
--- PASS: TestAccAWSBatchJobDefinition_ContainerProperties_Advanced (16.84s)
--- PASS: TestAccAWSBatchJobDefinition_updateForcesNewResource (27.13s)
```

### CODE REVIEW

**Comment by theophilechevalier** [comment]
Following #11998, I compiled the provider against your branch and I can confirm that all our batch stacks are back to normal.
Thanks @bflad 👍

File: aws/internal/service/batch/equivalency/container_properties.go [hunk 1]
```diff
@@ -19,10 +19,26 @@ func (cp *containerProperties) Reduce() error {
 		return aws.StringValue(cp.Environment[i].Name) < aws.StringValue(cp.Environment[j].Name)
 	})
 
+	if len(cp.Environment) == 0 {
```
Comment (paultyng) [inline aws/internal/service/batch/equivalency/container_properties.go]: this is minor, but can you comment why you have to `nil` this out? I'm assuming due to marshaling?

Comment (bflad) [reply aws/internal/service/batch/equivalency/container_properties.go]: I'll put comments on each of these, thanks
