### PR TITLE
resource/waf_rate_based_rule: add rate_limit to the list of possible update changes

### LINKED ISSUE #9659: aws_waf_rate_based_rule doesn't update rate_limit changes
_This issue was originally opened by @vad as hashicorp/terraform#22368. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._
    
<hr>
    

### Terraform Version

```
Terraform v0.12.6
+ provider.aws v2.22.0
...
```

### Terraform Configuration Files

```hcl
provider "aws" {
  region  = "eu-west-1"
}

resource "aws_waf_ipset" "ipset" {
  name = "tfIPSet"

  ip_set_descriptors {
    type  = "IPV4"
    value = "192.0.7.0/24"
  }
}

resource "aws_waf_rate_based_rule" "wafrule" {
  depends_on  = ["aws_waf_ipset.ipset"]
  name        = "tfWAFRule"
  metric_name = "tfWAFRule"

  rate_key   = "IP"
  rate_limit = 4000

  predicates {
    data_id = "${aws_waf_ipset.ipset.id}"
    negated = false
    type    = "IPMatch"
  }
}
...
```

### Debug Output

Relavant part:

https://gist.github.com/vad/3588212535b6a00b186bbd0dd4dd69cd

### Expected Behavior

If if change `rate_limit` value I expect terraform to update the rate based rule. 

### Actual Behavior

Terraform detects the change and actually tells me it update the rule but it didn't:

```
aws_waf_ipset.ipset: Refreshing state... [id=<ID>]
aws_waf_rate_based_rule.wafrule: Refreshing state... [id=<ID>]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_waf_rate_based_rule.wafrule will be updated in-place
  ~ resource "aws_waf_rate_based_rule" "wafrule" {
        id          = "<ID>"
        metric_name = "tfWAFRule"
        name        = "tfWAFRule"
        rate_key    = "IP"
      ~ rate_limit  = 4000 -> 3000

        predicates {
            data_id = "<ID>"
            negated = false
            type    = "IPMatch"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_waf_rate_based_rule.wafrule: Modifying... [id=<ID>]
aws_waf_rate_based_rule.wafrule: Modifications complete after 0s [id=<ID>]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

If I apply again, this repeats.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3.  change `rate_limit`
4. `terraform apply`

### PR DESCRIPTION
**Pull request by anGie44**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #9659

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/waf_rate_based_rule: correctly update rate_limit
```

Output from acceptance testing:

```
--- PASS: TestAccAWSWafRateBasedRule_changeRateLimit (27.66s)
```

### CODE REVIEW

File: aws/resource_aws_waf_rate_based_rule_test.go [hunk 1]
```diff
@@ -156,6 +156,58 @@ func TestAccAWSWafRateBasedRule_changePredicates(t *testing.T) {
...
+		Steps: []resource.TestStep{
+			{
+				Config: testAccAWSWafRateBasedRuleConfig_changeRateLimit(ruleName, 4000),
+				Check: resource.ComposeAggregateTestCheckFunc(
+					testAccCheckAWSWafIPSetExists("aws_waf_ipset.ipset", &ipset),
+					testAccCheckAWSWafRateBasedRuleExists(resourceName, &before),
+					resource.TestCheckResourceAttr(resourceName, "name", ruleName),
+					resource.TestCheckResourceAttr(resourceName, "rate_limit", "4000"),
+					resource.TestCheckResourceAttr(resourceName, "predicates.#", "1"),
+					computeWafRateBasedRulePredicateWithIpSet(&ipset, false, "IPMatch", &idx),
```
Comment (bflad) [inline aws/resource_aws_waf_rate_based_rule_test.go:180]: For follow up: this looks like another one of those test functions to determine TypeSet index which can probably be removed with the awesome new functions. 👍

**Comment by anGie44** [comment]
Merged w/master and removed custom test function to determine TypeSet index.

Output of acceptance tests:
```
--- PASS: TestAccAWSWafRateBasedRule_changeRateLimit (38.17s)
--- PASS: TestAccAWSWafRateBasedRule_changePredicates (44.89s)
--- PASS: TestAccAWSWafRateBasedRule_changeNameForceNew (46.31s)
--- PASS: TestAccAWSWafRateBasedRule_noPredicates (20.85s)
--- PASS: TestAccAWSWafRateBasedRule_Tags (31.40s)
--- PASS: TestAccAWSWafRateBasedRule_disappears (37.98s)
--- PASS: TestAccAWSWafRateBasedRule_basic (39.36s)
