### PR TITLE
resource/aws_network_acl: Properly handle ICMP code and type with IPv6 ICMP (protocol 58)

### LINKED ISSUE #6262: AWS Network ACL Error when creating IPv6 ICMP rule
_This issue was originally opened by @Redw0od as hashicorp/terraform#19188. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version
```
Terraform v0.11.9
+ provider.aws v1.35.0
+ provider.null v1.0.0
```

### Terraform Configuration Files
```
resource "aws_network_acl" "private" {
  count      = "${var.enabled == "true" && var.type == "private" && signum(length(var.private_network_acl_id)) == 0 ? 1 : 0}"
  vpc_id     = "${data.aws_vpc.default.id}"
  subnet_ids = ["${aws_subnet.private.*.id}"]
  egress     = "${var.egress_acl}"
  ingress    = {
    rule_no    = 1001
    action     = "allow"
    ipv6_cidr_block = "::/0"
    icmp_code  = "-1"
    icmp_type  = "-1"
    from_port  = -1
    to_port    = -1
    protocol   = "58"
  }
}
```

### Debug Output
```
Error: Error applying plan:

2 error(s)2018-10-24T11:48:09.705-0700 [DEBUG] plugin: plugin process exited: path=C:\Users\mike\mgmt\.terraform\plugins\windows_amd64\terraform-provider-aws_v1.35.0_x4.exe
 occurred:

* module.pub_subnet.aws_network_acl.public: 1 error(s) occurred:

* aws_network_acl.public: Error creating ingress entry: MissingParameter: The request must contain the parameter icmpTypeCode.type
        status code: 400, request id: acb3d7c0-9207-4227-b862-f892c3b72d56
* module.priv_subnet.aws_network_acl.private: 1 error(s) occurred:

* aws_network_acl.private: Error creating ingress entry: MissingParameter: The request must contain the parameter icmpTypeCode.type
        status code: 400, request id: 08bc85e6-20e8-415f-9c6f-8c664884575a

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```
### Crash Output
No Crash

### Expected Behavior
Creation of proper IPv6 ICMP all types allow rule

### Actual Behavior
Error from AWS

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### PR DESCRIPTION
**Pull request by bflad**
Fixes #6262 

Changes proposed in this pull request:

* Allow `protocol` 58 to propagate ICMP code and type configuration

Previously:

```
--- FAIL: TestAccAWSNetworkAcl_ipv6ICMPRules (12.17s)
    testing.go:538: Step 0 error: Error applying: 1 error occurred:
        	* aws_network_acl.test: 1 error occurred:
        	* aws_network_acl.test: Error creating ingress entry: MissingParameter: The request must contain the parameter icmpTypeCode.type
        	status code: 400, request id: 9551aec6-d3cf-435f-a35d-0d60b8fd2a69
```

Output from acceptance testing:

```
--- PASS: TestAccAWSNetworkAcl_ipv6ICMPRules (17.51s)
```

### CODE REVIEW

File: aws/network_acl_entry.go [hunk 1]
```diff
@@ -43,7 +43,7 @@ func expandNetworkAclEntries(configured []interface{}, entryType string) ([]*ec2
 		}
 
 		// Specify additional required fields for ICMP
-		if p == 1 {
+		if p == 1 || p == 58 {
```
Comment (tombuildsstuff) [inline aws/network_acl_entry.go]: IMO this wants a comment/constant explaining what 1 and 58 represent

Comment (bflad) [reply aws/network_acl_entry.go]: I created a technical debt issue for this: #6302

**Comment by bflad** [comment]
This has been released in [version 1.42.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1420-october-31-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
