### PR TITLE
r/aws_route53_health_check - suppress diff when expanded ipv6 address is the same

### LINKED ISSUE #11069: aws_route53_health_check does not expand IPv6 address leading to wrong check and resource destroyed/created every time
### Terraform Version

$ terraform -v
Terraform v0.12.16
+ provider.aws v2.40.0
+ provider.template v2.1.2

### Affected Resource(s)

aws_route53_health_check

### Terraform Configuration Files

```hcl
resource "aws_route53_health_check" "eu-west-3a-lb-ipv6" {
  ip_address = aws_instance.eu-west-3a-lb.ipv6_addresses[0]
  port = 80
  type = "HTTP"
  resource_path = "/"
  failure_threshold = "5"
  request_interval = "30"
  regions = ["eu-west-1", "us-west-1", "us-east-1"]
}
```
### Debug Output

```
  # aws_route53_health_check.eu-west-3a-lb-ipv6 must be replaced
-/+ resource "aws_route53_health_check" "eu-west-3a-lb-ipv6" {
      - child_health_threshold = 0 -> null
      - child_healthchecks     = [] -> null
      ~ enable_sni             = false -> (known after apply)
        failure_threshold      = 5
      ~ id                     = "xxxxxxxx-xxxx-xxxx-a8c3-6e6f4ac91ac0" -> (known after apply)
      - invert_healthcheck     = false -> null
      ~ ip_address             = "1234:5678:9abc:6811:0:0:0:4" -> "1234:5678:9abc:6811::4" # forces replacement
        measure_latency        = false
        port                   = 80
      - regions                = [] -> null
        request_interval       = 30
        resource_path          = "/"
        type                   = "HTTP"
    }
```

### Expected Behavior

```
      ~ ip_address             = "1234:5678:9abc:6811:0:0:0:4" -> "1234:5678:9abc:6811::4" # forces replacement
```
This should be evaluated as similar.

For info https://github.com/terraform-providers/terraform-provider-dns/pull/13 I don't know if this  issue is exactly similar or if this fix can help.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by DrFaust92**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #11069

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource_aws_route53_health_check: do not recreate health check when using compressed ipv6 address.
resource_aws_route53_health_check: add plan time validation to `insufficient_data_health_status`.
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSRoute53HealthCheck_'
--- PASS: TestAccAWSRoute53HealthCheck_basic (72.75s)
--- PASS: TestAccAWSRoute53HealthCheck_IpConfig (43.30s)
--- PASS: TestAccAWSRoute53HealthCheck_Ipv6Config (44.32s)
--- PASS: TestAccAWSRoute53HealthCheck_CloudWatchAlarmCheck (54.50s)
--- PASS: TestAccAWSRoute53HealthCheck_withSNI (103.25s)
--- PASS: TestAccAWSRoute53HealthCheck_withChildHealthChecks (50.15s)
--- PASS: TestAccAWSRoute53HealthCheck_withHealthCheckRegions (42.71s)
--- PASS: TestAccAWSRoute53HealthCheck_withSearchString (72.53s)
--- PASS: TestAccAWSRoute53HealthCheck_tags (101.66s)
--- PASS: TestAccAWSRoute53HealthCheck_disappears (35.03s)
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
Verified acceptance tests:

```console
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSRoute53HealthCheck_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSRoute53HealthCheck_ -timeout 120m
=== RUN   TestAccAWSRoute53HealthCheck_basic
=== PAUSE TestAccAWSRoute53HealthCheck_basic
=== RUN   TestAccAWSRoute53HealthCheck_tags
=== PAUSE TestAccAWSRoute53HealthCheck_tags
=== RUN   TestAccAWSRoute53HealthCheck_withSearchString
=== PAUSE TestAccAWSRoute53HealthCheck_withSearchString
=== RUN   TestAccAWSRoute53HealthCheck_withChildHealthChecks
=== PAUSE TestAccAWSRoute53HealthCheck_withChildHealthChecks
=== RUN   TestAccAWSRoute53HealthCheck_withHealthCheckRegions
=== PAUSE TestAccAWSRoute53HealthCheck_withHealthCheckRegions
=== RUN   TestAccAWSRoute53HealthCheck_IpConfig
=== PAUSE TestAccAWSRoute53HealthCheck_IpConfig
=== RUN   TestAccAWSRoute53HealthCheck_Ipv6Config
=== PAUSE TestAccAWSRoute53HealthCheck_Ipv6Config
=== RUN   TestAccAWSRoute53HealthCheck_CloudWatchAlarmCheck
=== PAUSE TestAccAWSRoute53HealthCheck_CloudWatchAlarmCheck
=== RUN   TestAccAWSRoute53HealthCheck_withSNI
=== PAUSE TestAccAWSRoute53HealthCheck_withSNI
=== RUN   TestAccAWSRoute53HealthCheck_disappears
=== PAUSE TestAccAWSRoute53HealthCheck_disappears
=== CONT  TestAccAWSRoute53HealthCheck_basic
=== CONT  TestAccAWSRoute53HealthCheck_Ipv6Config
=== CONT  TestAccAWSRoute53HealthCheck_disappears
=== CONT  TestAccAWSRoute53HealthCheck_IpConfig
=== CONT  TestAccAWSRoute53HealthCheck_withHealthCheckRegions
=== CONT  TestAccAWSRoute53HealthCheck_withChildHealthChecks
=== CONT  TestAccAWSRoute53HealthCheck_withSearchString
=== CONT  TestAccAWSRoute53HealthCheck_tags
=== CONT  TestAccAWSRoute53HealthCheck_withSNI
=== CONT  TestAccAWSRoute53HealthCheck_CloudWatchAlarmCheck
--- PASS: TestAccAWSRoute53HealthCheck_disappears (17.66s)
--- PASS: TestAccAWSRoute53HealthCheck_withHealthCheckRegions (22.79s)
--- PASS: TestAccAWSRoute53HealthCheck_IpConfig (23.30s)
--- PASS: TestAccAWSRoute53HealthCheck_withChildHealthChecks (23.91s)
--- PASS: TestAccAWSRoute53HealthCheck_CloudWatchAlarmCheck (28.14s)
--- PASS: TestAccAWSRoute53HealthCheck_Ipv6Config (36.35s)
--- PASS: TestAccAWSRoute53HealthCheck_basic (36.36s)
--- PASS: TestAccAWSRoute53HealthCheck_withSearchString (37.08s)
--- PASS: TestAccAWSRoute53HealthCheck_withSNI (53.14s)
--- PASS: TestAccAWSRoute53HealthCheck_tags (53.26s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	53.292s
```

File: aws/resource_aws_route53_health_check_test.go [hunk 1]
```diff
@@ -185,7 +194,39 @@ func TestAccAWSRoute53HealthCheck_IpConfig(t *testing.T) {
...
+		CheckDestroy: testAccCheckRoute53HealthCheckDestroy,
+		Steps: []resource.TestStep{
+			{
+				Config: testAccRoute53HealthCheckIpv6Config,
+				Check: resource.ComposeTestCheckFunc(
+					testAccCheckRoute53HealthCheckExists(resourceName, &check),
+					resource.TestCheckResourceAttr(resourceName, "ip_address", "1234:5678:9abc:6811:0:0:0:4"),
+				),
+			},
+			{
```
Comment (gdavison) [inline aws/resource_aws_route53_health_check_test.go]: To make the tests explicit, you could add some `plan`-only tests, e.g.
```go
{
  Config:   testAccRoute53HealthCheckIpv6ExpandedConfig,
  PlanOnly: true,
}
```

Comment (DrFaust92) [reply aws/resource_aws_route53_health_check_test.go]: changed and re ran test:

--- PASS: TestAccAWSRoute53HealthCheck_Ipv6Config (59.54s)

File: aws/resource_aws_route53_health_check_test.go [hunk 2]
```diff
@@ -33,17 +36,14 @@ func TestAccAWSRoute53HealthCheck_basic(t *testing.T) {
 			},
 			{
 				Config: testAccRoute53HealthCheckConfigUpdate,
-				Check: resource.ComposeTestCheckFunc(
-					testAccCheckRoute53HealthCheckExists(resourceName),
-					resource.TestCheckResourceAttr(resourceName, "failure_threshold", "5"),
-					resource.TestCheckResourceAttr(resourceName, "invert_healthcheck", "false"),
-				),
+				PlanOnly: true,
```
Comment (gdavison) [inline aws/resource_aws_route53_health_check_test.go]: This test changes values, so leaving it as a `Check` would be good.

Comment (DrFaust92) [reply aws/resource_aws_route53_health_check_test.go]: oops, didnt mean to change that.
