### PR TITLE
r/lb_target_group: fix compatibility with Network Load Balancers

### LINKED ISSUE #1912: lb_target_group not compatible with aws_lb of type network
Using AWS provider 1.1

I cannot create lb_target_goup for aws_lb of type "network"
I want to create a network load balancer to balance some tcp connection, but when i set the aws_lb_target_group protocol to 'tcp' I got the following error: 

> aws_lb_target_group.tg: "protocol" must be either "HTTP" or "HTTPS"

The code:

```
resource "aws_lb" "ecs_lb" {
  name            = "ecs-lb"
  load_balancer_type = "network"
  subnets         = ["${aws_subnet.public.*.id}"]
  security_groups = ["${aws_security_group.lb_sg.id}"]
}

resource "aws_lb_target_group" "application_tg" {
  name     = "application_tg"
  port     = 80
  protocol = "tcp"
  vpc_id   = "${aws_vpc.main.id}"
}
```

### PR DESCRIPTION
**Pull request by catsby**
Supersedes #1884 

- adds a simple error check on setting `health_check`
- add documentation about `stickiness` and Network LBs
- Implement test

Fixes #1912 

------
Test results 

```
TF_ACC=1 go test ./aws -v -run=TestAccAWSLBTargetGroup_ -timeout 120m
=== RUN   TestAccAWSLBTargetGroup_basic
--- PASS: TestAccAWSLBTargetGroup_basic (26.49s)
=== RUN   TestAccAWSLBTargetGroup_networkLB_TargetGroup
--- PASS: TestAccAWSLBTargetGroup_networkLB_TargetGroup (26.17s)
=== RUN   TestAccAWSLBTargetGroup_namePrefix
--- PASS: TestAccAWSLBTargetGroup_namePrefix (25.68s)
=== RUN   TestAccAWSLBTargetGroup_generatedName
--- PASS: TestAccAWSLBTargetGroup_generatedName (24.66s)
=== RUN   TestAccAWSLBTargetGroup_changeNameForceNew
--- PASS: TestAccAWSLBTargetGroup_changeNameForceNew (44.56s)
=== RUN   TestAccAWSLBTargetGroup_changeProtocolForceNew
--- PASS: TestAccAWSLBTargetGroup_changeProtocolForceNew (46.48s)
=== RUN   TestAccAWSLBTargetGroup_changePortForceNew
--- PASS: TestAccAWSLBTargetGroup_changePortForceNew (43.55s)
=== RUN   TestAccAWSLBTargetGroup_changeVpcForceNew
--- PASS: TestAccAWSLBTargetGroup_changeVpcForceNew (40.32s)
=== RUN   TestAccAWSLBTargetGroup_tags
--- PASS: TestAccAWSLBTargetGroup_tags (40.29s)
=== RUN   TestAccAWSLBTargetGroup_updateHealthCheck
--- PASS: TestAccAWSLBTargetGroup_updateHealthCheck (42.46s)
=== RUN   TestAccAWSLBTargetGroup_updateSticknessEnabled
--- PASS: TestAccAWSLBTargetGroup_updateSticknessEnabled (57.63s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       418.337s
```

### CODE REVIEW

**Comment by catsby** [comment]
Hey @DaveBlooman if you have a minute please take a look here! https://github.com/terraform-providers/terraform-provider-aws/pull/2251/commits/5b1b3fcf7d49bf5352c0c7e8707daa61d695ebc0 is my additions to your original PR#1884

**Comment by DaveBlooman** [comment]
@catsby I squashed my commits, so your commit is based on my initial commit, not my latest https://github.com/terraform-providers/terraform-provider-aws/pull/1884/commits/0d9e713d73b8c50c8db0f44f12a60f34ec317c74

**Comment by catsby** [comment]
@DaveBlooman ah thanks for pointing that out, I rebased and should be fixed now

**Comment by catsby** [comment]
We had some failing tests due to a typo, I patched that in c93f98a

**Comment by DaveBlooman** [comment]
@catsby LGTM

File: aws/resource_aws_lb_target_group.go [hunk 1]
```diff
@@ -201,14 +199,17 @@ func resourceAwsLbTargetGroupCreate(d *schema.ResourceData, meta interface{}) er
...
-		params.HealthCheckPath = aws.String(healthCheck["path"].(string))
 		params.HealthCheckPort = aws.String(healthCheck["port"].(string))
 		params.HealthCheckProtocol = aws.String(healthCheck["protocol"].(string))
-		params.HealthCheckTimeoutSeconds = aws.Int64(int64(healthCheck["timeout"].(int)))
 		params.HealthyThresholdCount = aws.Int64(int64(healthCheck["healthy_threshold"].(int)))
-		params.UnhealthyThresholdCount = aws.Int64(int64(healthCheck["unhealthy_threshold"].(int)))
-		params.Matcher = &elbv2.Matcher{
-			HttpCode: aws.String(healthCheck["matcher"].(string)),
+
+		if *params.Protocol != "TCP" {
```
Comment (radeksimko) [inline aws/resource_aws_lb_target_group.go]: I think it would be a bit more future-proof and cleaner if we checked each argument separately regardless of the protocol. That said it would probably require removing all defaults from these fields and making them computed, which introduces some other potential troubles during updates.

The downside of the current solution is that we're _silently_ ignoring certain arguments without ever telling the user which may backfire if AWS decides to support any of these arguments in the future.

File: aws/resource_aws_lb_target_group.go [hunk 2]
```diff
@@ -479,14 +485,19 @@ func flattenAwsLbTargetGroupResource(d *schema.ResourceData, meta interface{}, t
...
 	healthCheck["protocol"] = *targetGroup.HealthCheckProtocol
 	healthCheck["timeout"] = *targetGroup.HealthCheckTimeoutSeconds
 	healthCheck["healthy_threshold"] = *targetGroup.HealthyThresholdCount
 	healthCheck["unhealthy_threshold"] = *targetGroup.UnhealthyThresholdCount
-	healthCheck["matcher"] = *targetGroup.Matcher.HttpCode
-	d.Set("health_check", []interface{}{healthCheck})
+	if *targetGroup.Protocol != "TCP" {
+		healthCheck["path"] = *targetGroup.HealthCheckPath
+		healthCheck["matcher"] = *targetGroup.Matcher.HttpCode
+	}
```
Comment (radeksimko) [inline aws/resource_aws_lb_target_group.go]: Nitpick, but we could do something like this

```go
if targetGroup.HealthCheckPath != nil {
    healthCheck["path"] = *targetGroup.HealthCheckPath
}
if targetGroup.Matcher.HttpCode != nil {
    healthCheck["matcher"] = *targetGroup.Matcher.HttpCode
}
```
I know that HTTP health check arguments will never be supported for TCP LB, but it feels a little bit cleaner 😉

Comment (catsby) [reply aws/resource_aws_lb_target_group.go]: 👍 applied in 33103635

File: aws/resource_aws_lb_target_group.go (hunk 1 above)
Comment (catsby) [reply aws/resource_aws_lb_target_group.go]: Agreed this isn't ideal, but I'm going to go forward as is. Part of me wonders if the real solution would have been to keep ALB and LB as separate resources entirely 🤔

Comment (DaveBlooman) [reply aws/resource_aws_lb_target_group.go]: Agreed on that point, It is a shame to make a breaking change, but as more specific features are added to each type, they will diverge more. Let's see what aws do at re: invent

**Comment by catsby** [comment]
I applied feedback suggested and re-ran tests:

```
=== RUN   TestAccAWSLBTargetGroup_basic
--- PASS: TestAccAWSLBTargetGroup_basic (23.06s)
=== RUN   TestAccAWSLBTargetGroup_networkLB_TargetGroup
--- PASS: TestAccAWSLBTargetGroup_networkLB_TargetGroup (21.93s)
=== RUN   TestAccAWSLBTargetGroup_namePrefix
--- PASS: TestAccAWSLBTargetGroup_namePrefix (22.22s)
=== RUN   TestAccAWSLBTargetGroup_generatedName
--- PASS: TestAccAWSLBTargetGroup_generatedName (21.84s)
=== RUN   TestAccAWSLBTargetGroup_changeNameForceNew
--- PASS: TestAccAWSLBTargetGroup_changeNameForceNew (37.20s)
=== RUN   TestAccAWSLBTargetGroup_changeProtocolForceNew
--- PASS: TestAccAWSLBTargetGroup_changeProtocolForceNew (41.59s)
=== RUN   TestAccAWSLBTargetGroup_changePortForceNew
--- PASS: TestAccAWSLBTargetGroup_changePortForceNew (37.43s)
=== RUN   TestAccAWSLBTargetGroup_changeVpcForceNew
--- PASS: TestAccAWSLBTargetGroup_changeVpcForceNew (33.66s)
=== RUN   TestAccAWSLBTargetGroup_tags
--- PASS: TestAccAWSLBTargetGroup_tags (38.11s)
=== RUN   TestAccAWSLBTargetGroup_updateHealthCheck
--- PASS: TestAccAWSLBTargetGroup_updateHealthCheck (36.82s)
=== RUN   TestAccAWSLBTargetGroup_updateSticknessEnabled
--- PASS: TestAccAWSLBTargetGroup_updateSticknessEnabled (51.31s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       365.186s
```

Going to merge this now

**Comment by dcloud9** [comment]
@catsby - thanks for merging to master, NLB target group TCP proto. 
As 1.3.0 is yet to be released, we can `make build` master branch and move the bin/terraform-provider-aws to .terraform_plugins/ as interim, happy days.

**Comment by catsby** [comment]
@dcloud9 awesome! I believe `v1.3.0` should come out soon

**Comment by AnishAnil** [comment]
This is a critical blocker for our atomation. I'm unable to create a Network LB.
What is the ETA to have this fixed

**Comment by radeksimko** [comment]
@AnishAnil this was shipped yesterday in `1.3.0`

**Comment by wjglerum** [comment]
Today I got this error message on a deploy:
`ValidationError: Health check matcher HTTP code cannot be empty`

After some searching I found this in the changelog:
`resource/aws_lb_target_group: We no longer provide defaults for health_check's path nor matcher in order to support network load balancers where these arguments aren't valid. Creating new ALB will therefore require you to specify these two arguments. Existing deployments are unaffected. (#2251)`

However the documentation still says it is optional:
`matcher (Optional) The HTTP codes to use when checking for a successful response from a target. Defaults to 200. You can specify multiple values (for example, "200,202") or a range of values (for example, "200-299").`

**Comment by wjglerum** [comment]
The same goes for the health_check path which is also not updated in the documentation

**Comment by radeksimko** [comment]
@wjglerum that's tracked under https://github.com/terraform-providers/terraform-provider-aws/issues/2336 and https://github.com/terraform-providers/terraform-provider-aws/issues/2343 - feel free to subscribe to that issue using the button in the right sidebar.

Sorry for the troubles.

**Comment by wjglerum** [comment]
Thanks, didn't see that issue.

**Comment by catsby** [comment]
#2380 is a follow-up PR to this
