### PR TITLE
Set ForceNew for s3_backup_mode in aws_kinesis_firehose_delivery_stream

### LINKED ISSUE #1369: aws_kinesis_firehose_delivery_stream does not manage s3_backup_mode
### Terraform Version
`Terraform v0.10.0`

### Affected Resource(s)
- aws_kinesis_firehose_delivery_stream

### Terraform Configuration Files
```
provider "aws" {
  profile = "terraform"
  region  = "us-west-2"
}

resource "aws_s3_bucket" "firehose" {
  bucket = "mgeggie-firehose"
  acl    = "private"
}

resource "aws_iam_role" "firehose" {
  name = "firehose"
  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "firehose.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}

resource "aws_iam_role_policy" "firehose" {
  name   = "firehose"
  role   = "firehose"
  policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:AbortMultipartUpload",
                "s3:GetBucketLocation",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:ListBucketMultipartUploads",
                "s3:PutObject"
            ],
            "Resource": [
                "${aws_s3_bucket.firehose.arn}",
                "${aws_s3_bucket.firehose.arn}/*"
            ]
        },
        {
           "Effect": "Allow",
           "Action": [
               "es:DescribeElasticsearchDomain",
               "es:DescribeElasticsearchDomains",
               "es:DescribeElasticsearchDomainConfig",
               "es:ESHttpPost",
               "es:ESHttpPut"
           ],
          "Resource": [
              "${aws_elasticsearch_domain.firehose.arn}",
              "${aws_elasticsearch_domain.firehose.arn}/${aws_elasticsearch_domain.firehose.domain_name}/*"
          ]
       },
       {
          "Effect": "Allow",
          "Action": [
              "es:ESHttpGet"
          ],
          "Resource": [
              "${aws_elasticsearch_domain.firehose.arn}/${aws_elasticsearch_domain.firehose.domain_name}/_all/_settings",
              "${aws_elasticsearch_domain.firehose.arn}/${aws_elasticsearch_domain.firehose.domain_name}/_cluster/stats",
              "${aws_elasticsearch_domain.firehose.arn}/${aws_elasticsearch_domain.firehose.domain_name}/index-name*/_mapping/type-name",
              "${aws_elasticsearch_domain.firehose.arn}/${aws_elasticsearch_domain.firehose.domain_name}/_nodes",
              "${aws_elasticsearch_domain.firehose.arn}/${aws_elasticsearch_domain.firehose.domain_name}/_nodes/stats",
              "${aws_elasticsearch_domain.firehose.arn}/${aws_elasticsearch_domain.firehose.domain_name}/_nodes/*/stats",
              "${aws_elasticsearch_domain.firehose.arn}/${aws_elasticsearch_domain.firehose.domain_name}/_stats",
              "${aws_elasticsearch_domain.firehose.arn}/${aws_elasticsearch_domain.firehose.domain_name}/index-name*/_stats"
          ]
       },
       {
          "Effect": "Allow",
          "Action": [
            "logs:CreateLogGroup",
            "logs:CreateLogStream",
            "logs:DescribeLogStreams",
            "logs:PutLogEvents"
          ],
          "Resource": [
              "arn:aws:logs:*"
          ]
       }
    ]
}
EOF
}

resource "aws_kinesis_firehose_delivery_stream" "firehose" {
  name        = "firehose"
  destination = "elasticsearch"
  s3_configuration {
    role_arn   = "${aws_iam_role.firehose.arn}"
    bucket_arn = "${aws_s3_bucket.firehose.arn}"
    prefix     = "/"
    cloudwatch_logging_options {
      enabled = true
      log_group_name  = "firehose"
      log_stream_name = "firehose"
    }
  }
  elasticsearch_configuration {
    domain_arn     = "${aws_elasticsearch_domain.firehose.arn}"
    index_name     = "firehose"
    role_arn       = "${aws_iam_role.firehose.arn}"
    type_name      = "object"
    s3_backup_mode = "ErrorDocumentsOnly"
  }
}

resource "aws_elasticsearch_domain" "firehose" {
  domain_name           = "firehose"
  elasticsearch_version = "5.3"
  cluster_config {
    instance_type = "m4.large.elasticsearch"
  }
  ebs_options {
    ebs_enabled = true
    volume_size = 512
  }
}
```

### Debug Output
https://gist.github.com/mgeggie/f0d776a30ef5f375e7dc5e95abb11ceb

### Panic Output
-- None --

### Expected Behavior
The `S3BackupMode` of the firehose resource should have been changed from  `AllDocuments` to `FailedDocumentsOnly`

### Actual Behavior
The `S3BackupMode` was not changed

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Change `aws_kinesis_firehose_delivery_stream.firehose.elasticsearch_configuration.s3_backup_mode` from `AllDocuments` to `FailedDocumentsOnly`
3. `terraform apply`
4. No change has been made to the firehose.

### Important Factoids
Nothing of note.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- https://github.com/terraform-providers/terraform-provider-aws/issues/385

### PR DESCRIPTION
**Pull request by Hinidu**
Fixes #1369

Changes proposed in this pull request:

* Set `ForceNew: true` for `s3_backup_mode` attribute of `aws_kinesis_firehose_delivery_stream` resource because it can't be changed on existing delivery stream.

### CODE REVIEW

File: aws/resource_aws_kinesis_firehose_delivery_stream.go [hunk 1]
```diff
@@ -1192,6 +1194,7 @@ func resourceAwsKinesisFirehoseDeliveryStream() *schema.Resource {
 
 						"s3_backup_mode": {
 							Type:     schema.TypeString,
+							ForceNew: true,
```
Comment (bflad) [inline aws/resource_aws_kinesis_firehose_delivery_stream.go]: This change is okay. [`ElasticsearchDestinationUpdate`](https://docs.aws.amazon.com/firehose/latest/APIReference/API_ElasticsearchDestinationUpdate.html) does not support updating this parameter 👍

File: aws/resource_aws_kinesis_firehose_delivery_stream.go [hunk 2]
```diff
@@ -1263,6 +1266,7 @@ func resourceAwsKinesisFirehoseDeliveryStream() *schema.Resource {
...
```
Comment (bflad) [inline aws/resource_aws_kinesis_firehose_delivery_stream.go]: Please revert this change. We currently support updates for `splunk_configuration.0.s3_backup_mode` via [`SplunkDestinationUpdate`](https://docs.aws.amazon.com/firehose/latest/APIReference/API_SplunkDestinationUpdate.html):
* Code: https://github.com/terraform-providers/terraform-provider-aws/blob/7f93f3cc123490e8c2ceaee725921a8ab4da8cd7/aws/resource_aws_kinesis_firehose_delivery_stream.go#L1949
* Acceptance testing: This test currently updates `s3_backup_mode` to match the default (`FailedEventsOnly`) but could be updated on lines 645 and 1810 to update to `AllEvents` which would properly test this update https://github.com/terraform-providers/terraform-provider-aws/blob/7f93f3cc123490e8c2ceaee725921a8ab4da8cd7/aws/resource_aws_kinesis_firehose_delivery_stream_test.go#L626

**Comment by Hinidu** [comment]
Hi @bflad! Thank you for review, I've made requested changes.

File: aws/resource_aws_kinesis_firehose_delivery_stream.go [hunk 3]
```diff
@@ -1013,6 +1013,7 @@ func resourceAwsKinesisFirehoseDeliveryStream() *schema.Resource {
...
```
[the remark this answers is not in the document]
Comment (Hinidu) [reply aws/resource_aws_kinesis_firehose_delivery_stream.go]: Done

File: aws/resource_aws_kinesis_firehose_delivery_stream.go [hunk 4]
```diff
@@ -1065,6 +1066,7 @@ func resourceAwsKinesisFirehoseDeliveryStream() *schema.Resource {
...
```
[the remark this answers is not in the document]
Comment (Hinidu) [reply aws/resource_aws_kinesis_firehose_delivery_stream.go]: Done

File: aws/resource_aws_kinesis_firehose_delivery_stream.go (hunk 2 above)
Comment (Hinidu) [reply aws/resource_aws_kinesis_firehose_delivery_stream.go]: Done

**Comment by Hinidu** [comment]
Thanks!
