### PR TITLE
Fix placement group create delete

### LINKED ISSUE #9915: New issues creating/deleting aws_placement_groups
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform: 0.11.14
AWS provider: 2.25.0

### Affected Resource(s)

* aws_placement_group

### Expected Behavior

Until today 2019-08-29 10AM CEST everything was working well when creating/deleting
Placement Group and related/dependant resources. Since today got errors during apply and destroy which tends to prove that AWS API has changed or some states are not taken into account. This reminds me of the recent similar issue #9596

### Actual Behavior

Apply:
```
Error: Error applying plan:

1 error occurred:
	* aws_placement_group.monitor_spread_placement_group: 1 error occurred:
	* aws_placement_group.monitor_spread_placement_group: InvalidPlacementGroup.Unknown: The Placement Groups 'XXX' is unknown.
       status code: 400, request id: ...
```

Destroy:
```
Error: Error applying plan:

1 error occurred:
	* aws_placement_group.monitor_spread_placement_group (destroy): 1 error occurred:
	* aws_placement_group.monitor_spread_placement_group: unexpected state 'available', wanted target 'deleted'. last error: %!s(<nil>)
```

### Steps to Reproduce

Create a placement group and 1 dependant resource. Delete it

### Important Factoids

I am not sure this is 100% reproductible as most "timing/state related issues"

### References

* #9596

### PR DESCRIPTION
**Pull request by obourdon**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #9915 

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
BUG FIXES:
* aws_placement_group.monitor_spread_placement_group: InvalidPlacementGroup.Unknown: The Placement Groups 'XXX' is unknown.
* aws_placement_group.monitor_spread_placement_group: unexpected state 'available', wanted target 'deleted'. last error: %!s(<nil>)
```

Output from acceptance testing:

```
$ AWS_DEFAULT_REGION=eu-west-1 AWS_PROFILE=scratch gmake testacc TEST=./aws TESTARGS='-run=TestAccAWSPlacementGroup'

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSPlacementGroup -timeout 120m
=== RUN   TestAccAWSPlacementGroup_basic
=== PAUSE TestAccAWSPlacementGroup_basic
=== RUN   TestAccAWSPlacementGroup_tags
=== PAUSE TestAccAWSPlacementGroup_tags
=== RUN   TestAccAWSPlacementGroup_disappears
=== PAUSE TestAccAWSPlacementGroup_disappears
=== CONT  TestAccAWSPlacementGroup_basic
=== CONT  TestAccAWSPlacementGroup_tags
=== CONT  TestAccAWSPlacementGroup_disappears
--- PASS: TestAccAWSPlacementGroup_disappears (16.32s)
--- PASS: TestAccAWSPlacementGroup_basic (20.93s)
--- PASS: TestAccAWSPlacementGroup_tags (49.45s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	49.562s
$
```

### CODE REVIEW

File: aws/resource_aws_placement_group.go [hunk 1]
```diff
@@ -74,6 +74,13 @@ func resourceAwsPlacementGroupCreate(d *schema.ResourceData, meta interface{}) e
 			})
 
 			if err != nil {
+				// Fix timing issue where describe is called prior to
+				// create being effectively processed by AWS
+				awsErr := err.(awserr.Error)
+				if awsErr.Code() == "InvalidPlacementGroup.Unknown" {
+					log.Printf("[DEBUG] Resetting error creating EC2 Placement group: %q %v", d.Id(), awsErr)
+					return out, "pending", nil
+				}
```
Comment (bflad) [inline aws/resource_aws_placement_group.go]: We should prefer to use the `isAWSErr()` helper function and available AWS Go SDK constant here. 😄 

```go
				if isAWSErr(err, "InvalidPlacementGroup.Unknown", "") {
					return out, ec2.PlacementGroupStatePending, nil
				}
```

File: aws/resource_aws_placement_group.go [hunk 2]
```diff
@@ -190,6 +197,9 @@ func resourceAwsPlacementGroupDelete(d *schema.ResourceData, meta interface{}) e
 			}
 
 			pg := out.PlacementGroups[0]
+			if *pg.State == "available" {
+				log.Printf("[DEBUG] Accepted status when deleting EC2 Placement group: %q %v", d.Id(), *pg.State)
+			}
```
Comment (bflad) [inline aws/resource_aws_placement_group.go]: We can remove this logging 👍 Otherwise the code here should prevent panics by replacing the raw dereferencing with `aws.StringValue(pg.State)` in case it is `nil`.

Comment (obourdon) [reply aws/resource_aws_placement_group.go]: Agreed and done

File: aws/resource_aws_placement_group.go (hunk 1 above)
Comment (obourdon) [reply aws/resource_aws_placement_group.go]: Sounds perfectly normal

**Comment by obourdon** [comment]
```
$ AWS_DEFAULT_REGION=eu-west-1 AWS_PROFILE=scratch gmake testacc TEST=./aws TESTARGS='-run=TestAccAWSPlacementGroup'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSPlacementGroup -timeout 120m
=== RUN   TestAccAWSPlacementGroup_basic
=== PAUSE TestAccAWSPlacementGroup_basic
=== RUN   TestAccAWSPlacementGroup_tags
=== PAUSE TestAccAWSPlacementGroup_tags
=== RUN   TestAccAWSPlacementGroup_disappears
=== PAUSE TestAccAWSPlacementGroup_disappears
=== CONT  TestAccAWSPlacementGroup_basic
=== CONT  TestAccAWSPlacementGroup_disappears
=== CONT  TestAccAWSPlacementGroup_tags
--- PASS: TestAccAWSPlacementGroup_disappears (15.55s)
--- PASS: TestAccAWSPlacementGroup_basic (19.85s)
--- PASS: TestAccAWSPlacementGroup_tags (45.79s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	45.862s
```

**Comment by obourdon** [comment]
@bflad many thanks for the merge
