### PR TITLE
resource/aws_backup_plan: Prevent the sending of empty lifecycle attributes

### LINKED ISSUE #8151: aws_backup_plan lifecycle cold_storage_after should be optional
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.13
+ provider.aws v2.4.0

### Affected Resource(s)

* aws_backup_plan

### Terraform Configuration Files

```hcl
resource "aws_backup_vault" "example" {
    name = "example-vault"
}

resource "aws_backup_plan" "example" {
    name = "example-plan"
    rule {
        rule_name = "MainRule"
        target_vault_name = "${aws_backup_vault.example.name}"
        schedule = "cron(5 8 * * ? *)"
        lifecycle {
            delete_after = 30
        }
    }
}
```

### Debug Output

https://gist.github.com/sbutler/f9480ef8e86428b054181b94d6221a75

### Expected Behavior

I should be able to create a plan with a rule that only has delete_after and no cold_storage_after.

### Actual Behavior

Plan fails, because the request terraform sends is invalid (delete_after not 90 days after cold_storage_after).

### Steps to Reproduce

1. `terraform apply`

### References

* https://github.com/terraform-providers/terraform-provider-aws/pull/7350#issuecomment-475081418

### PR DESCRIPTION
**Pull request by nywilken**
Closes #8151

Lifecycle policies contain settings for deleting backups, and for moving them to cold storage. A backup with cold storage enabled can not have a deletion value lower then 90 days. So to prevent this AWS allows setting ColdStorageAfter to Never by not setting a value for ColdStorageAfter.

This change adds logic to ensure ColdStorageAfter and DeleteAfter only get sent within the API request if the values are not empty and greater than 0.

Acceptance Test before change
```
=== RUN   TestAccAwsBackupPlan_withLifecycle
=== PAUSE TestAccAwsBackupPlan_withLifecycle
=== RUN   TestAccAwsBackupPlan_withLifecycleDeleteAfterOnly
=== PAUSE TestAccAwsBackupPlan_withLifecycleDeleteAfterOnly
=== RUN   TestAccAwsBackupPlan_withLifecycleColdStorageAfterOnly
=== PAUSE TestAccAwsBackupPlan_withLifecycleColdStorageAfterOnly
=== CONT  TestAccAwsBackupPlan_withLifecycle
=== CONT  TestAccAwsBackupPlan_withLifecycleColdStorageAfterOnly
=== CONT  TestAccAwsBackupPlan_withLifecycleDeleteAfterOnly
--- FAIL: TestAccAwsBackupPlan_withLifecycleColdStorageAfterOnly (10.86s)
    testing.go:538: Step 0 error: Error applying: 1 error occurred:
                * aws_backup_plan.test: 1 error occurred:
                * aws_backup_plan.test: error creating Backup Plan: InvalidParameterValueException: Error in rule tf_acc_test_backup_rule_lifecycle_policy_three : Invalid lifecycle. DeleteAfterDays cannot be less than one day
                status code: 400, request id: 757544c3-4628-4a7e-95fa-416098fe2594

--- FAIL: TestAccAwsBackupPlan_withLifecycleDeleteAfterOnly (11.00s)
    testing.go:538: Step 0 error: Error applying: 1 error occurred:
                * aws_backup_plan.test: 1 error occurred:
                * aws_backup_plan.test: error creating Backup Plan: InvalidParameterValueException: Error in rule tf_acc_test_backup_rule_lifecycle_policy_two : Invalid lifecycle. DeleteAfterDays cannot be less than 90 days apart from MoveToColdStorageAfterDays
                status code: 400, request id: e37c0d06-0cd7-4783-b01a-40e1dc5758f0

--- PASS: TestAccAwsBackupPlan_withLifecycle (18.92s)
FAIL
FAIL    github.com/terraform-providers/terraform-provider-aws/aws       18.948s
GNUmakefile:20: recipe for target 'testacc' failed
```

Acceptance Test after change
```
=== RUN   TestAccAwsBackupPlan_withLifecycle
=== PAUSE TestAccAwsBackupPlan_withLifecycle
=== RUN   TestAccAwsBackupPlan_withLifecycleDeleteAfterOnly
=== PAUSE TestAccAwsBackupPlan_withLifecycleDeleteAfterOnly
=== RUN   TestAccAwsBackupPlan_withLifecycleColdStorageAfterOnly
=== PAUSE TestAccAwsBackupPlan_withLifecycleColdStorageAfterOnly
=== CONT  TestAccAwsBackupPlan_withLifecycle
=== CONT  TestAccAwsBackupPlan_withLifecycleColdStorageAfterOnly
=== CONT  TestAccAwsBackupPlan_withLifecycleDeleteAfterOnly
--- PASS: TestAccAwsBackupPlan_withLifecycleDeleteAfterOnly (18.70s)
--- PASS: TestAccAwsBackupPlan_withLifecycle (19.75s)
--- PASS: TestAccAwsBackupPlan_withLifecycleColdStorageAfterOnly
(20.25s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws
20.266s
```

### CODE REVIEW

File: aws/resource_aws_backup_plan.go [hunk 1]
```diff
@@ -151,8 +151,14 @@ func resourceAwsBackupPlanRead(d *schema.ResourceData, meta interface{}) error {
 
 		if r.Lifecycle != nil {
 			l := make(map[string]interface{})
-			l["delete_after"] = aws.Int64Value(r.Lifecycle.DeleteAfterDays)
-			l["cold_storage_after"] = aws.Int64Value(r.Lifecycle.MoveToColdStorageAfterDays)
+
+			if v := r.Lifecycle.DeleteAfterDays; v != nil {
```
Comment (bflad) [inline aws/resource_aws_backup_plan.go]: Nit: The `nil` checks here and below are extraneous because [`aws.Int64Value()`](https://docs.aws.amazon.com/sdk-for-go/api/aws/#Int64Value) will automatically convert `nil` to `0` and `TypeInt` defaults to `0`.

File: aws/resource_aws_backup_plan_test.go [hunk 2]
```diff
@@ -338,6 +384,48 @@ resource "aws_backup_plan" "test" {
...
+
+resource "aws_backup_plan" "test" {
+  name = "tf_acc_test_backup_plan_%s"
+
+  rule {
+    rule_name          = "tf_acc_test_backup_rule_%s"
+    target_vault_name  = "${aws_backup_vault.test.name}"
+    schedule           = "cron(0 12 * * ? *)"
+    lifecycle {
+        delete_after       = "7"
```
Comment (bflad) [inline aws/resource_aws_backup_plan_test.go]: Nit: Formatting here and below

```suggestion
        delete_after = "7"
```

File: aws/resource_aws_backup_plan_test.go [hunk 3]
```diff
@@ -338,6 +384,48 @@ resource "aws_backup_plan" "test" {
...
+    }
+  }
+}
+`, stringID, stringID, stringID)
```
Comment (bflad) [inline aws/resource_aws_backup_plan_test.go]: Nit: Can use formatter indexing to reduce `fmt.Sprintf()` argument sprawl here and below, e.g.

```go
	return fmt.Sprintf(`
resource "aws_backup_vault" "test" {
  name = "tf_acc_test_backup_vault_%[1]s"
}
resource "aws_backup_plan" "test" {
  name = "tf_acc_test_backup_plan_%[1]s"
  rule {
    rule_name          = "tf_acc_test_backup_rule_%[1]s"
...
`, stringID)
```

File: aws/resource_aws_backup_plan_test.go [hunk 4]
```diff
@@ -165,6 +167,50 @@ func TestAccAwsBackupPlan_withLifecycle(t *testing.T) {
...
+		Providers:    testAccProviders,
+		CheckDestroy: testAccCheckAwsBackupPlanDestroy,
+		Steps: []resource.TestStep{
+			{
+				Config: testAccBackupPlanWithLifecycleDeleteAfterOnly(rStr),
+				Check: resource.ComposeTestCheckFunc(
+					testAccCheckAwsBackupPlanExists("aws_backup_plan.test", &plan),
+					resource.TestCheckResourceAttr("aws_backup_plan.test", "rule.2156287050.lifecycle.#", "1"),
+					resource.TestCheckResourceAttr("aws_backup_plan.test", "rule.2156287050.lifecycle.0.delete_after", "7"),
+					resource.TestCheckResourceAttr("aws_backup_plan.test", "rule.2156287050.lifecycle.0.cold_storage_after", "0"),
```
Comment (dud225) [inline aws/resource_aws_backup_plan_test.go]: I don't speak Go at all so I'm not sure to understand properly what you did.
AFAICT if `MoveToColdStorageAfterDays` is not sent to the AWS API, then this field won't ever appear on the backup plan. Here is an excerpt from a backup plan :
```
                "Lifecycle": {
                    "DeleteAfterDays": 90
                },
```

that has been created with this command : 
```sh
$ aws backup update-backup-plan --backup-plan-id <id> --backup-plan '{"BackupPlanName":"my-
backup", "Rules": [{"RuleName": "dailybackups", "TargetBackupVaultName": "my-vault", "Lifecycle": {"DeleteAfterDays": 90}}]}'
```

So if I understand your tests correctly you shouldn't test if the value is zero, but just ignore the field.


The same thing is true for `DeleteAfterDays`

Comment (dud225) [reply aws/resource_aws_backup_plan_test.go]: OK I think I got it, it is only the TF representation of the backup plan that holds the zero values, the zero values are then filtered out when the plan is sent to the AWS API.

Comment (nywilken) [reply aws/resource_aws_backup_plan_test.go]: > OK I think I got it, it is only the TF representation of the backup plan that holds the zero values, the zero values are then filtered out when the plan is sent to the AWS API.

Hi @dud225 thanks for the review and the question. Your understanding is correct by default the zero value of any Terraform configuration would be assigned within Terraform but we would only send the value to the API if it is a non zero value, in this case some an  int greater than 0. FYI when I say zero value I am referring to the zero values of Go types https://www.callicoder.com/golang-variables-zero-values-type-inference/#zero-values

**Comment by bflad** [comment]
This has been released in [version 2.6.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#260-april-10-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
