### PR TITLE
resource/aws_elasticache_cluster: Migrate from availability_zones TypeSet attribute to preferred_availability_zones TypeList attribute

### LINKED ISSUE #207: Allow creating MultiAZ memcached cluster in a single terraform apply where number nodes > number of AZ's
_This issue was originally opened by @msroest as hashicorp/terraform#7850. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

Currently a aws_elasticache_cluster using MultiAZ setup with num_cache_nodes > then count of availability_zones.

AWS validation will fail with the following error:
 aws_elasticache_cluster.swimlane-memcache: Error creating Elasticache: InvalidParameterCombination: Must specify the same number of preferred availability zones as requested number of nodes.
    status code: 400, request id: 63124b02-54f6-11e6-95b5-3960d6e4870c

It can be done in 2 stages by setting num_cache_nodes to the same as the number of AZ's then after creation is complete change the num_cache_nodes to the final desired number.

It would be nice if terraform would do this itself.

### LINKED ISSUE #374: ElastiCache cluster resource is 'broken'
_This issue was originally opened by @FransUrbo as hashicorp/terraform#10127. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

I can't seem to create a ElastiCache cluster (and I'm not entirely sure why - hence just 'broken').

The parameters is mutually exclusive, but when I try to set them, they don't work. See example resource definition below (with inline comments on different values).

I'm pretty sure this is **documentation**, but I'm not sure..

### Terraform Version
0.7.8 (can't run 0.7.{9-10} because those are 'seriously' broken in other ways - several issues about that already exists).

### Affected Resource(s)
- aws_elasticache_cluster

### Terraform Configuration Files
```hcl
data "aws_availability_zones" "available" {}

resource "aws_elasticache_subnet_group" "main" {
  name                        = "elasticache-subnet-group"
  description                 = "Autoscaling events updating Route53"

  subnet_ids                  = [
    "${aws_subnet.main_0.id}",
    "${aws_subnet.main_1.id}",
    "${aws_subnet.main_2.id}"
  ]
}

# => Use of cache security groups is not permitted in this API version for your account.
#resource "aws_elasticache_security_group" "main" {
#  name                         = "elasticache-security-group"
#  security_group_names         = [
#    "${aws_security_group.main-all.name}"
#  ]
#}

resource "aws_elasticache_cluster" "autoscaling_event_update_route53" {
  cluster_id                    = "asgevnt-route53" # Maximum 16 chars - not documented anywhere in TF.

  engine                        = "redis"
  engine_version                = "3.2.4"
  port                          = 6379
  node_type                     = "cache.t2.micro" # Automatic failover is not supported for T1 and T2 cache node types - not documented anywhere in TF.
# => Must specify the same number of preferred availability zones as requested number of nodes.
#  num_cache_nodes               = "${length(data.aws_availability_zones.available.names)}"
# => Cannot create a Redis cluster with a NumCacheNodes parameter greater than 1.
#  num_cache_nodes               = 1 # According to docs, it can only be one. But when I  DO set it to "1", I get "Must specify the same number of preferred availability zones as requested number of nodes"..

  subnet_group_name             = "${aws_elasticache_subnet_group.main.name}"
# => Use of cache security groups is not permitted in this API version for your account.
#  security_group_ids            = ["${aws_elasticache_security_group.main.name}"]
  security_group_ids            = [
    "${aws_security_group.main-all.id}"
  ]
  parameter_group_name          = "default.redis3.2"

# => should be a list
  availability_zones            = "${data.aws_availability_zones.available.names}" # I thought this was SUPPOSED to be a list! ? But making it a list, gives me "Must specify the same number of preferred availability zones as requested number of nodes."

  apply_immediately             = "true"
  snapshot_arns                 = ["arn:aws:s3:::php-infrastructure-backups/autoscaling_event_update_route53.rdb"]
# => The requested configuration does not support snapshotting. Snapshot window parameter should not be specified.
#  snapshot_window               = "03:00-07:00"
# => The requested configuration does not support snapshotting. Snapshot retention limit parameter should not be specified.
#  snapshot_retention_limit      = "5"

  maintenance_window            = "sun:01:00-sun:02:00"

  tags {
    Name                        = "autoscaling_event_update_route53"
    environment                 = "core"
    service                     = "main"
  }
}
```

### LINKED ISSUE #2658: aws_elasticache_cluster does not allow duplicate availability_zones values
### Terraform Version
< terraform -v
Terraform v0.11.1
+ provider.aws v1.5.0
+ provider.template v1.0.0

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_elasticache_cluster

### Terraform Configuration Files
```hcl
resource "aws_elasticache_cluster" "my_cache" {
  cluster_id           = "..."
  engine               = "memcached"
  node_type            = "cache.r4.2xlarge"
  port                 = 11211
  num_cache_nodes      = "6"
  parameter_group_name = "default.memcached1.4"
  security_group_ids   = ["..."]
  subnet_group_name    = "..."
  availability_zones   = ["us-west-2a", "us-west-2b", "us-west-2c", "us-west-2a", "us-west-2b", "us-west-2c"]
}
```

### Expected Behavior
Create a cluster in 6 AZ.

### Actual Behavior
`InvalidParameterCombination: Must specify the same number of preferred availability zones as requested number of nodes`

### Steps to Reproduce
Create a cluster with the same AZ name multiple times inside `availability_zones`

### Important Factoids
I think something is deduping the `availability_zones` list, when it shouldn't be deduped.  The `plan` step shows

```
  availability_zones.#:          "" => "3"
  availability_zones.2050015877: "" => "us-west-2c"
  availability_zones.221770259:  "" => "us-west-2b"
  availability_zones.2487133097: "" => "us-west-2a"
```

Even though the list size is 6.

Passing in just 3, unique `availability_zones` values will complain that the passed in list size isn't equal to `num_cache_nodes` value (6 in this case).

Or the logic should be smart enough to take a list that is only 3 AZ, but have some knowledge of how to distribute them.

### PR DESCRIPTION
**Pull request by bflad**
Fixes #2658 
Fixes #374
Fixes #207 

Changes proposed in this pull request:

* Deprecate `availability_zones` (TypeSet) attribute in `aws_elasticache_cluster`
* Create `preferred_availability_zones` (TypeList) attribute in `aws_elasticache_cluster`
* Support `NewAvailabilityZones` parameter in `ModifyCacheCluster` when increasing `num_cache_nodes` with `preferred_availability_zones`
* Add acceptance test to cover increasing `num_cache_nodes` while utilizing `preferred_availability_zones`

We must create a new attribute because there is no way to migrate state from TypeSet to TypeList without breaking existing configurations, so we will allow an opt-in upgrade procedure and phase out the old attribute. I'm indifferent with the new attribute naming so suggestions welcome (we've used `ordered_X` for other migrations like this, but `preferred_` here does match the `CreateCacheCluster` parameter `PreferredAvailabilityZones`).

Output from acceptance testing:

```
20 tests passed (all tests)
=== RUN   TestAccAWSElasticacheCluster_ReplicationGroupID_InvalidAttributes
--- PASS: TestAccAWSElasticacheCluster_ReplicationGroupID_InvalidAttributes (3.51s)
=== RUN   TestAccAWSElasticacheCluster_NumCacheNodes_Redis_Ec2Classic
--- PASS: TestAccAWSElasticacheCluster_NumCacheNodes_Redis_Ec2Classic (3.58s)
=== RUN   TestAccAWSElasticacheCluster_AZMode_Memcached_Ec2Classic
--- PASS: TestAccAWSElasticacheCluster_AZMode_Memcached_Ec2Classic (443.83s)
=== RUN   TestAccAWSElasticacheCluster_AZMode_Redis_Ec2Classic
--- PASS: TestAccAWSElasticacheCluster_AZMode_Redis_Ec2Classic (493.62s)
=== RUN   TestAccAWSElasticacheCluster_SecurityGroup
--- PASS: TestAccAWSElasticacheCluster_SecurityGroup (529.19s)
=== RUN   TestAccAWSElasticacheCluster_Engine_Memcached_Ec2Classic
--- PASS: TestAccAWSElasticacheCluster_Engine_Memcached_Ec2Classic (535.47s)
=== RUN   TestAccAWSElasticacheCluster_Engine_Redis_Ec2Classic
--- PASS: TestAccAWSElasticacheCluster_Engine_Redis_Ec2Classic (546.33s)
=== RUN   TestAccAWSElasticacheCluster_Port_Ec2Classic
--- PASS: TestAccAWSElasticacheCluster_Port_Ec2Classic (556.38s)
=== RUN   TestAccAWSElasticacheCluster_vpc
--- PASS: TestAccAWSElasticacheCluster_vpc (829.40s)
=== RUN   TestAccAWSElasticacheCluster_multiAZInVpc
--- PASS: TestAccAWSElasticacheCluster_multiAZInVpc (848.69s)
=== RUN   TestAccAWSElasticacheCluster_NodeTypeResize_Redis_Ec2Classic
--- PASS: TestAccAWSElasticacheCluster_NodeTypeResize_Redis_Ec2Classic (891.39s)
=== RUN   TestAccAWSElasticacheCluster_NodeTypeResize_Memcached_Ec2Classic
--- PASS: TestAccAWSElasticacheCluster_NodeTypeResize_Memcached_Ec2Classic (938.32s)
=== RUN   TestAccAWSElasticacheCluster_NumCacheNodes_Decrease
--- PASS: TestAccAWSElasticacheCluster_NumCacheNodes_Decrease (1093.41s)
=== RUN   TestAccAWSElasticacheCluster_NumCacheNodes_IncreaseWithPreferredAvailabilityZones
--- PASS: TestAccAWSElasticacheCluster_NumCacheNodes_IncreaseWithPreferredAvailabilityZones (1094.63s)
=== RUN   TestAccAWSElasticacheCluster_EngineVersion_Memcached_Ec2Classic
--- PASS: TestAccAWSElasticacheCluster_EngineVersion_Memcached_Ec2Classic (1107.33s)
=== RUN   TestAccAWSElasticacheCluster_ReplicationGroupID_SingleReplica_Ec2Classic
--- PASS: TestAccAWSElasticacheCluster_ReplicationGroupID_SingleReplica_Ec2Classic (1121.69s)
=== RUN   TestAccAWSElasticacheCluster_ReplicationGroupID_MultipleReplica_Ec2Classic
--- PASS: TestAccAWSElasticacheCluster_ReplicationGroupID_MultipleReplica_Ec2Classic (1122.54s)
=== RUN   TestAccAWSElasticacheCluster_EngineVersion_Redis_Ec2Classic
--- PASS: TestAccAWSElasticacheCluster_EngineVersion_Redis_Ec2Classic (1145.84s)
=== RUN   TestAccAWSElasticacheCluster_NumCacheNodes_Increase
--- PASS: TestAccAWSElasticacheCluster_NumCacheNodes_Increase (1174.01s)
=== RUN   TestAccAWSElasticacheCluster_snapshotsWithUpdates
--- PASS: TestAccAWSElasticacheCluster_snapshotsWithUpdates (2146.12s)
```

### CODE REVIEW

File: aws/resource_aws_elasticache_cluster.go [hunk 1]
```diff
@@ -180,6 +180,9 @@ func resourceAwsElasticacheCluster() *schema.Resource {
 		ForceNew: true,
 	}
 
+	resourceSchema["availability_zones"].ConflictsWith = []string{"preferred_availability_zones"}
```
Comment (bflad) [inline aws/resource_aws_elasticache_cluster.go]: I have created #4828 to fully expand the resource schemas rather than continue with this generated approach.

**Comment by bflad** [comment]
This has been released in [version 1.23.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1230-june-14-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
