### PR TITLE
ECS Service enums + eventual consistency for service-role

### LINKED ISSUE #11417: When creating ECS service on a new cluster, the service linked role doesn't exist yet
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.13
+ provider.aws v2.43.0

### Affected Resource(s)

aws_ecs_service

### Expected Behavior

When creating an ECS service immediately after creating a new cluster in the same terraform apply, it should wait for AWS to create the service linked role, and succeed in creating the service.

### Actual Behavior

It tries to create the service before AWS finishes creating the ECS service linked role, and fails with this error.

```
Error: InvalidParameterException: Unable to assume the service linked role. Please verify that the ECS service linked role exists.
	status code: 400, request id: ZZZZZZZ "YYYYYYY"
  on ../../terraform-modules/container_service/ecs_service.tf line 1, in resource "aws_ecs_service" "XXXXX":
   1: resource "aws_ecs_service" "XXXXX" {
```

If terraform apply is run again shortly thereafter, it works.

### Steps to Reproduce

1. have a terraform plan file which creates a new ECS cluster and a service
2. `terraform apply` (fails)
3. Wait a minute or two
4. `terraform apply` (works)

### PR DESCRIPTION
**Pull request by DrFaust92**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #11417

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSEcsService_'
--- PASS: TestAccAWSEcsService_withARN (119.91s)
--- PASS: TestAccAWSEcsService_basicImport (108.86s)
--- PASS: TestAccAWSEcsService_disappears (85.71s)
--- PASS: TestAccAWSEcsService_withUnnormalizedPlacementStrategy (86.39s)
--- PASS: TestAccAWSEcsService_withCapacityProviderStrategy (217.09s)
--- PASS: TestAccAWSEcsService_withMultipleCapacityProviderStrategies (181.20s)
--- PASS: TestAccAWSEcsService_withFamilyAndRevision (113.15s)
--- PASS: TestAccAWSEcsService_withRenamedCluster (144.32s)
--- PASS: TestAccAWSEcsService_healthCheckGracePeriodSeconds (491.93s)
--- PASS: TestAccAWSEcsService_withIamRole (204.28s)
--- PASS: TestAccAWSEcsService_withDeploymentController_Type_CodeDeploy (425.01s)
--- PASS: TestAccAWSEcsService_withDeploymentValues (88.47s)
--- PASS: TestAccAWSEcsService_withDeploymentMinimumZeroMaximumOneHundred (88.05s)
--- PASS: TestAccAWSEcsService_withLbChanges (311.33s)
--- PASS: TestAccAWSEcsService_withEcsClusterName (86.52s)
--- PASS: TestAccAWSEcsService_withAlb (318.14s)
--- PASS: TestAccAWSEcsService_withMultipleTargetGroups (343.37s)
--- PASS: TestAccAWSEcsService_withPlacementStrategy (309.91s)
--- PASS: TestAccAWSEcsService_withPlacementConstraints (97.22s)
--- PASS: TestAccAWSEcsService_withPlacementConstraints_emptyExpression (88.17s)
--- PASS: TestAccAWSEcsService_withLaunchTypeFargate (272.64s)
--- PASS: TestAccAWSEcsService_withLaunchTypeFargateAndPlatformVersion (274.08s)
--- PASS: TestAccAWSEcsService_withLaunchTypeEC2AndNetworkConfiguration (198.85s)
--- PASS: TestAccAWSEcsService_withDaemonSchedulingStrategy (57.49s)
--- PASS: TestAccAWSEcsService_withDaemonSchedulingStrategySetDeploymentMinimum (49.63s)
--- PASS: TestAccAWSEcsService_withReplicaSchedulingStrategy (98.25s)
--- PASS: TestAccAWSEcsService_withServiceRegistries (241.48s)
--- PASS: TestAccAWSEcsService_withServiceRegistries_container (228.24s)
--- FAIL: TestAccAWSEcsService_Tags (24.47s)
    testing.go:640: Step 0 error: errors during apply:
        
        Error: InvalidParameterException: The new ARN and resource ID format must be enabled to add tags to the service. Opt in to the new format and try again.
        	status code: 400, request id: a95f242d-f39d-4a0c-b3d3-77aa58290108 "tf-acc-test-842556518505141709"

--- FAIL: TestAccAWSEcsService_ManagedTags (25.97s)
    testing.go:640: Step 0 error: errors during apply:
        
        Error: InvalidParameterException: The new ARN and resource ID format must be enabled to work with ECS managed tags. Opt in to the new format and try again.
        	status code: 400, request id: 4b45ee96-fb50-49fb-a7fd-362c638e709b "tf-acc-test-842556518505141709"
        
--- FAIL: TestAccAWSEcsService_PropagateTags (26.38s)
    testing.go:640: Step 0 error: errors during apply:
        
        Error: InvalidParameterException: The new ARN and resource ID format must be enabled to work with ECS managed tags. Opt in to the new format and try again.
        	status code: 400, request id: 1d0d6c37-1f1a-43d9-b002-2979eb79009f "tf-acc-test-842556518505141709"
...
```

### CODE REVIEW

File: aws/resource_aws_ecs_service_test.go [hunk 1]
```diff
@@ -336,17 +331,15 @@ func TestAccAWSEcsService_withRenamedCluster(t *testing.T) {
 				Config: testAccAWSEcsServiceWithRenamedCluster(clusterName, tdName, svcName),
 				Check: resource.ComposeTestCheckFunc(
 					testAccCheckAWSEcsServiceExists("aws_ecs_service.ghost", &service),
-					resource.TestMatchResourceAttr(
-						"aws_ecs_service.ghost", "cluster", originalRegexp),
+					testAccCheckResourceAttrRegionalARN("aws_ecs_service.ghost", "cluster", "ecs", "cluster/"+clusterName+"$"),
```
Comment (bflad) [inline aws/resource_aws_ecs_service_test.go]: This acceptance test update is currently failing due to the trailing dollar signs here and below:

```
--- FAIL: TestAccAWSEcsService_withRenamedCluster (49.10s)
    testing.go:640: Step 0 error: Check failed: Check 2/2 error: aws_ecs_service.ghost: Attribute 'cluster' expected "arn:aws:ecs:us-west-2:*******:cluster/tf-acc-cluster-svc-w-rc-qsjtr902$", got "arn:aws:ecs:us-west-2:*******:cluster/tf-acc-cluster-svc-w-rc-qsjtr902"
```

Rather than assembling an ARN to check the value though, its typically easier to use [`resource.TestCheckResourceAttrPair()`](https://godoc.org/github.com/hashicorp/terraform-plugin-sdk/helper/resource#TestCheckResourceAttrPair) to compare state values between two resources, e.g.

```suggestion
					resource.TestCheckResourceAttrPair("aws_ecs_service.ghost", "cluster", "aws_ecs_cluster.default", "arn"),
```

**Comment by DrFaust92** [comment]
> Hi @DrFaust92 👋 Thanks for submitting this. The updates to the acceptance test are currently failing, but otherwise these changes look okay.
> 
> In general, we would prefer if the unrelated changes (the bug fix, technical debt updates to the testing, and validation enhancements) were submitted separately just so we can merge bug fixes first if possible. This also helps us better note operator-facing changes in the CHANGELOG since this would require entries in multiple sections:
> 
> ```
> ENHANCEMENTS:
> 
> * resource/aws_ecs_service: Add plan time validation for `launch_type`, `load_balancer` configuration block `target_group_arn` and `container_port`, and `placement_constraints` configuration block `type` arguments [GH-11423]
> 
> BUG FIXES:
> 
> * resource/aws_ecs_service: Automatically retry IAM Service Linked Role error on creation due to asynchronous creation of role on first usage and IAM eventual consistency [GH-11423]
> ```
> 
> Thanks. 😄

**Comment by DrFaust92** [comment]
@bflad, Sorry about that. will split these up next time.

**Comment by DrFaust92** [comment]
```
--- PASS: TestAccAWSEcsService_withARN (119.39s)
--- PASS: TestAccAWSEcsService_basicImport (80.88s)
--- PASS: TestAccAWSEcsService_disappears (74.58s)
--- PASS: TestAccAWSEcsService_withUnnormalizedPlacementStrategy (81.07s)
--- PASS: TestAccAWSEcsService_withCapacityProviderStrategy (188.70s)
--- PASS: TestAccAWSEcsService_withMultipleCapacityProviderStrategies (168.71s)
--- PASS: TestAccAWSEcsService_withFamilyAndRevision (114.97s)
--- PASS: TestAccAWSEcsService_withRenamedCluster (162.16s)
--- PASS: TestAccAWSEcsService_healthCheckGracePeriodSeconds (396.77s)
--- PASS: TestAccAWSEcsService_withIamRole (140.96s)
--- PASS: TestAccAWSEcsService_withDeploymentController_Type_CodeDeploy (365.29s)
--- PASS: TestAccAWSEcsService_withDeploymentValues (94.20s)
--- PASS: TestAccAWSEcsService_withDeploymentMinimumZeroMaximumOneHundred (83.91s)
--- PASS: TestAccAWSEcsService_withLbChanges (257.87s)
--- PASS: TestAccAWSEcsService_withEcsClusterName (84.84s)
--- PASS: TestAccAWSEcsService_withAlb (361.28s)
--- PASS: TestAccAWSEcsService_withMultipleTargetGroups (356.18s)
--- PASS: TestAccAWSEcsService_withPlacementStrategy (299.61s)
--- PASS: TestAccAWSEcsService_withPlacementConstraints (92.68s)
--- PASS: TestAccAWSEcsService_withPlacementConstraints_emptyExpression (78.63s)
--- PASS: TestAccAWSEcsService_withLaunchTypeFargate (241.87s)
--- PASS: TestAccAWSEcsService_withLaunchTypeFargateAndPlatformVersion (239.29s)
--- PASS: TestAccAWSEcsService_withLaunchTypeEC2AndNetworkConfiguration (169.12s)
--- PASS: TestAccAWSEcsService_withDaemonSchedulingStrategy (48.40s)
--- PASS: TestAccAWSEcsService_withDaemonSchedulingStrategySetDeploymentMinimum (48.88s)
--- PASS: TestAccAWSEcsService_withReplicaSchedulingStrategy (82.39s)
--- PASS: TestAccAWSEcsService_withServiceRegistries (203.61s)
--- PASS: TestAccAWSEcsService_withServiceRegistries_container (204.40s)
--- PASS: TestAccAWSEcsService_Tags (156.22s)
--- PASS: TestAccAWSEcsService_ManagedTags (79.78s)
--- PASS: TestAccAWSEcsService_PropagateTags (208.96s)
```
