### PR TITLE
4701 aws_service_discovery_private_dns_namespace name length limit

### LINKED ISSUE #4701: aws_service_discovery_private_dns_namespace name length limit
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
+ provider.aws v1.20.0

### Affected Resource(s)

aws_service_discovery_private_dns_namespace

### Terraform Configuration Files

```hcl
provider "aws" {
  region  = "us-west-2"
  version = "1.20.0"
}

resource "aws_service_discovery_private_dns_namespace" "fail" {
  name = "this.is.a.really.long.name.i.suppose.but.who.are.you.to.judge"
  vpc  = "vpc-1234"
}

```

### Debug Output

https://gist.github.com/ahl/db1f84f4df6669fec9215cc0b84add10

### Expected Behavior

Should have created the resource.

### Actual Behavior

failed:
```
* aws_service_discovery_private_dns_namespace.fail: InvalidInput: 1 validation error detected: Value 'tf-this.is.a.really.long.name.i.suppose.but.who.are.you.to.judge20180530163701323000000001' at 'creatorRequestId' failed to satisfy constraint: Member must have length less than or equal to 64
```

### Steps to Reproduce

1. `terraform apply`

### PR DESCRIPTION
**Pull request by ahl**
Fixes #4701 aws_service_discovery_private_dns_namespace

Changes proposed in this pull request:

* use a hash of the name if its length exceeds 32 characters

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSServiceDiscoveryPrivateDnsNamespace'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -run=TestAccAWSServiceDiscoveryPrivateDnsNamespace -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSServiceDiscoveryPrivateDnsNamespace_basic
--- PASS: TestAccAWSServiceDiscoveryPrivateDnsNamespace_basic (21.61s)
=== RUN   TestAccAWSServiceDiscoveryPrivateDnsNamespace_longname
--- PASS: TestAccAWSServiceDiscoveryPrivateDnsNamespace_longname (20.86s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	42.513s
```

### CODE REVIEW

File: aws/resource_aws_service_discovery_private_dns_namespace.go [hunk 1]
```diff
@@ -1,6 +1,8 @@
 package aws
 
 import (
+	"crypto/sha1"
```
Comment (bflad) [inline aws/resource_aws_service_discovery_private_dns_namespace.go]: We actually do not need to perform any hashing as `resource.PrefixedUniqueId()` already includes a mutex with a monotonic counter to ensure it is unique even during concurrent operations with the same prefix:

https://github.com/hashicorp/terraform/blob/ad259b2b9569cadd4a24f051e271fa5e669066f2/helper/resource/id.go#L35-L45

We just need to trim the input string 👍

Comment (ahl) [reply aws/resource_aws_service_discovery_private_dns_namespace.go]: That's a lot simpler. Why even bother with a prefix based on the name if it is irrelevant for uniqueness? Why not use "" or "terraform" or "private_dns_namespace"?

Thanks for merging and cleaning up

**Comment by bflad** [comment]
This has been released in [version 1.22.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1220-june-05-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
