### PR TITLE
resource/aws_ecs_service: Add public_assign_ip attribute and fix InvalidParameterException handling

### LINKED ISSUE #85: Terraform unable to create ecs_service if iam_role is set
_This issue was originally opened by @egoldschmidt as hashicorp/terraform#5292. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

I've come across an issue in which an ECS service apparently cannot be created if `iam_role` is set. As you can see from this example I've set it to the ARN of the default ECS service user, but I've tried a custom user to no avil. The only thing that appears to resolve the problem is removing the `iam_role` field altogether. Obviously this is a non-starter because we need ELBs, so any ideas would be appreciated.

```
module.vpn_service.aws_ecs_service.vpn: Creating...
  cluster:                                 "" => "arn:aws:ecs:us-west-2:xxx:cluster/vpn"
  desired_count:                           "" => "1"
  iam_role:                                "" => "arn:aws:iam::xxx:role/ecsServiceRole"
  load_balancer.#:                         "" => "2"
  load_balancer.3901468935.container_name: "" => "vpn"
  load_balancer.3901468935.container_port: "" => "943"
  load_balancer.3901468935.elb_name:       "" => "vpn-elb"
  load_balancer.450980314.container_name:  "" => "vpn"
  load_balancer.450980314.container_port:  "" => "443"
  load_balancer.450980314.elb_name:        "" => "vpn-elb"
  name:                                    "" => "vpn"
  task_definition:                         "" => "arn:aws:ecs:us-west-2:xxx:task-definition/vpn:4"
Error applying plan:

1 error(s) occurred:

* aws_ecs_service.vpn: timeout while waiting for state to become '[success]'
```

### LINKED ISSUE #2873: aws_ecs_service doesn't provide assignPublicIp option in network_configuration
Version: Terraform v0.11.1

Since the `assignPublicIp` option is missing from the `aws_ecs_service` resource, it defaults to DISABLED, which means that a task fails when pulling images from ECR.

You can see the `assignPublicIp` option using the AWS CLI (`aws ecs create-service help`), where it exists alongside the subnet and security group options.

### LINKED ISSUE #3098: ECS service definition is missing AssignPublicIp property
Support for network configuration has been added to aws_ecs_service:
https://github.com/terraform-providers/terraform-provider-aws/pull/2299/files

Only security_groups and subnets were added, but assign_public_ip property is missing:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-awsvpcconfiguration.html#cfn-ecs-service-awsvpcconfiguration-assignpublicip

This is a blocker for Fargate  to pull images from ECR, as it seems that public IP is required (maybe a bug):
https://github.com/aws/amazon-ecs-agent/issues/1128#issuecomment-352090244

### Terraform Version
Terraform v0.11.2

### Affected Resource(s)
aws_ecs_service

### Terraform Configuration Files
```hcl
resource "aws_ecs_service" "myapp" {
  name            = "myapp"
  cluster         = "fargate"
  launch_type     = "FARGATE"
  network_configuration = {
    subnets = ["${aws_subnet.dev_demo.id}"]
    security_groups = ["${aws_security_group.ecs.id}"]
    assign_public_ip = "ENABLED"        <---- NOT SUPPORTED
  }
...
}
```

### Expected Behavior
Auto-assign public IP ENABLED  is applied

### Actual Behavior
Error: aws_ecs_service.myapp: network_configuration.0: invalid or unknown key: assign_public_ip

### PR DESCRIPTION
**Pull request by bflad**
Fixes #85
Closes #2873 
Closes #3098 

This PR is a continuation of #2559, including crash prevention for `nil` `AssignPublicIp` and testing fixes for that PR. While trying to run and fix the acceptance testing, I was having major trouble with the incorrect retry logic that was noted in #85 so fixed that as well on top of the original PR.

```
Tests passed: 15
=== RUN   TestAccAWSEcsService_withDeploymentValues
--- PASS: TestAccAWSEcsService_withDeploymentValues (18.69s)
=== RUN   TestAccAWSEcsService_withIamRole
--- PASS: TestAccAWSEcsService_withIamRole (30.97s)
=== RUN   TestAccAWSEcsService_withEcsClusterName
--- PASS: TestAccAWSEcsService_withEcsClusterName (32.51s)
=== RUN   TestAccAWSEcsService_withUnnormalizedPlacementStrategy
--- PASS: TestAccAWSEcsService_withUnnormalizedPlacementStrategy (34.12s)
=== RUN   TestAccAWSEcsService_withPlacementConstraints
--- PASS: TestAccAWSEcsService_withPlacementConstraints (34.33s)
=== RUN   TestAccAWSEcsService_withARN
--- PASS: TestAccAWSEcsService_withARN (38.19s)
=== RUN   TestAccAWSEcsService_withFamilyAndRevision
--- PASS: TestAccAWSEcsService_withFamilyAndRevision (44.44s)
=== RUN   TestAccAWSEcsService_withRenamedCluster
--- PASS: TestAccAWSEcsService_withRenamedCluster (45.14s)
=== RUN   TestAccAWSEcsService_withPlacementStrategy
--- PASS: TestAccAWSEcsService_withPlacementStrategy (48.49s)
=== RUN   TestAccAWSEcsService_withPlacementConstraints_emptyExpression
--- PASS: TestAccAWSEcsService_withPlacementConstraints_emptyExpression (48.62s)
=== RUN   TestAccAWSEcsService_withLaunchTypeEC2AndNetworkConfiguration
--- PASS: TestAccAWSEcsService_withLaunchTypeEC2AndNetworkConfiguration (50.84s)
=== RUN   TestAccAWSEcsService_withLbChanges
--- PASS: TestAccAWSEcsService_withLbChanges (134.42s)
=== RUN   TestAccAWSEcsService_healthCheckGracePeriodSeconds
--- PASS: TestAccAWSEcsService_healthCheckGracePeriodSeconds (211.31s)
=== RUN   TestAccAWSEcsService_withAlb
--- PASS: TestAccAWSEcsService_withAlb (225.66s)
=== RUN   TestAccAWSEcsService_withLaunchTypeFargate
--- PASS: TestAccAWSEcsService_withLaunchTypeFargate (251.76s)
```

### CODE REVIEW

**Comment by bflad** [comment]
Pulled in #3242 commits:
```
=== RUN   TestAccAWSEcsService_withEcsClusterName
--- PASS: TestAccAWSEcsService_withEcsClusterName (10.88s)
=== RUN   TestAccAWSEcsService_withDeploymentValues
--- PASS: TestAccAWSEcsService_withDeploymentValues (11.12s)
=== RUN   TestAccAWSEcsService_withPlacementConstraints_emptyExpression
--- PASS: TestAccAWSEcsService_withPlacementConstraints_emptyExpression (14.90s)
=== RUN   TestAccAWSEcsService_withPlacementStrategy
--- PASS: TestAccAWSEcsService_withPlacementStrategy (26.64s)
=== RUN   TestAccAWSEcsService_withRenamedCluster
--- PASS: TestAccAWSEcsService_withRenamedCluster (27.79s)
=== RUN   TestAccAWSEcsService_withARN
--- PASS: TestAccAWSEcsService_withARN (38.56s)
=== RUN   TestAccAWSEcsService_withUnnormalizedPlacementStrategy
--- PASS: TestAccAWSEcsService_withUnnormalizedPlacementStrategy (42.26s)
=== RUN   TestAccAWSEcsService_withPlacementConstraints
--- PASS: TestAccAWSEcsService_withPlacementConstraints (42.96s)
=== RUN   TestAccAWSEcsService_withLbChanges
--- PASS: TestAccAWSEcsService_withLbChanges (43.23s)
=== RUN   TestAccAWSEcsService_withFamilyAndRevision
--- PASS: TestAccAWSEcsService_withFamilyAndRevision (49.40s)
=== RUN   TestAccAWSEcsService_withLaunchTypeEC2AndNetworkConfiguration
--- PASS: TestAccAWSEcsService_withLaunchTypeEC2AndNetworkConfiguration (80.44s)
=== RUN   TestAccAWSEcsService_withIamRole
--- PASS: TestAccAWSEcsService_withIamRole (125.37s)
=== RUN   TestAccAWSEcsService_healthCheckGracePeriodSeconds
--- PASS: TestAccAWSEcsService_healthCheckGracePeriodSeconds (201.72s)
=== RUN   TestAccAWSEcsService_withAlb
--- PASS: TestAccAWSEcsService_withAlb (214.05s)
=== RUN   TestAccAWSEcsService_withLaunchTypeFargate
--- PASS: TestAccAWSEcsService_withLaunchTypeFargate (250.18s)
```

File: aws/resource_aws_ecs_service.go [hunk 1]
```diff
@@ -495,24 +503,17 @@ func resourceAwsEcsServiceUpdate(d *schema.ResourceData, meta interface{}) error
...
+	// Retry due to IAM eventual consistency
 	err := resource.Retry(2*time.Minute, func() *resource.RetryError {
 		out, err := conn.UpdateService(&input)
 		if err != nil {
-			awsErr, ok := err.(awserr.Error)
-			if ok && awsErr.Code() == "InvalidParameterException" {
-				log.Printf("[DEBUG] Trying to update ECS service again: %#v", err)
-				return resource.RetryableError(err)
-			}
-			if ok && awsErr.Code() == "ServiceNotFoundException" {
```
Comment (catsby) [inline aws/resource_aws_ecs_service.go]: Here we're losing the retry on `ServiceNotFoundException`, is that intentional?

File: website/docs/r/ecs_service.html.markdown [hunk 2]
```diff
@@ -102,6 +102,7 @@ Guide](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cluster-query
 
 * `subnets` - (Required) The subnets associated with the task or service.
 * `security_groups` - (Optional) The security groups associated with the task or service. If you do not specify a security group, the default security group for the VPC is used.
+* `assign_public_ip` - (Optional) Only valid for `FARGATE` launch type and valid values are `true` or `false`.  Will assign a public IP address to the ENI.  Default value is `false`.
```
Comment (catsby) [inline website/docs/r/ecs_service.html.markdown]: Suggest reword to "Assign a public IP address to the ENI (`Fargate` launch type only). Valid values are `true` or `false`. Default `false`." or similar

File: aws/resource_aws_ecs_service.go (hunk 1 above)
Comment (bflad) [reply aws/resource_aws_ecs_service.go]: @catsby Interestingly enough, I had just assumed it was some sort of typo that it was included and that retrying on a missing service would be undesirable during an update, but turns out we are currently always calling `resourceAwsEcsServiceUpdate` at the end of `resourceAwsEcsServiceCreate`. So that explains why it was in there.

Looking through the parameters set during `resourceAwsEcsServiceUpdate` to `ecs.UpdateServiceInput`, I don't see anything not already handled by `resourceAwsEcsServiceCreate` so I think we should instead return `resourceAwsEcsServiceRead` at the end of `resourceAwsEcsServiceCreate` and keep the `ecs.ErrCodeServiceNotFoundException` retry logic out of `resourceAwsEcsServiceUpdate`. 

Does that sound reasonable?

File: website/docs/r/ecs_service.html.markdown (hunk 2 above)
Comment (bflad) [reply website/docs/r/ecs_service.html.markdown]: Done! 👍

File: aws/resource_aws_ecs_service.go [hunk 3]
```diff
@@ -287,21 +291,12 @@ func resourceAwsEcsServiceCreate(d *schema.ResourceData, meta interface{}) error
...
-			if awsErr.Code() == "InvalidParameterException" {
-				log.Printf("[DEBUG] Trying to create ECS service again: %q",
-					awsErr.Message())
+			if isAWSErr(err, ecs.ErrCodeClusterNotFoundException, "") {
 				return resource.RetryableError(err)
 			}
-			if awsErr.Code() == "ClusterNotFoundException" {
-				log.Printf("[DEBUG] Trying to create ECS service again: %q",
-					awsErr.Message())
+			if isAWSErr(err, ecs.ErrCodeInvalidParameterException, "Please verify that the ECS service role being passed has the proper permissions.") {
```
Comment (radeksimko) [inline aws/resource_aws_ecs_service.go]: I trust you that you ran all ECS related acceptance tests a couple of times to verify that we're not missing any other message/format here. 😃

File: aws/resource_aws_ecs_service.go (hunk 1 above)
Comment (radeksimko) [reply aws/resource_aws_ecs_service.go]: @bflad that sounds like a good idea - as long as all ECS tests still pass 🤷‍♂️

File: aws/resource_aws_ecs_service.go [hunk 4]
```diff
@@ -9,7 +9,6 @@ import (
 	"time"
 
 	"github.com/aws/aws-sdk-go/aws"
-	"github.com/aws/aws-sdk-go/aws/awserr"
```
Comment (radeksimko) [inline aws/resource_aws_ecs_service.go]: ❤️

File: aws/resource_aws_ecs_service_test.go [hunk 5]
```diff
@@ -1448,7 +1492,20 @@ resource "aws_ecs_service" "with_alb" {
...
+		sg1Name, sg2Name, clusterName, tdName, svcName,
+		`"${aws_security_group.allow_all_a.id}", "${aws_security_group.allow_all_b.id}"`,
+	)
+}
+func testAccAWSEcsServiceWithNetworkConfiguration_modified(sg1Name, sg2Name, clusterName, tdName, svcName string) string {
+	return tpl_testAccAWSEcsServiceWithNetworkConfiguration(
+		sg1Name, sg2Name, clusterName, tdName, svcName,
+		`"${aws_security_group.allow_all_a.id}"`,
+	)
+}
```
Comment (radeksimko) [inline aws/resource_aws_ecs_service_test.go]: Passing parts of HCL is a little bit confusing at first I have to say... sometimes duplication is just better than abstraction, IMO.

**Comment by bflad** [comment]
@radeksimko sorry for the delayed response, all tests are passing. I'll run them a few more times to be certain. 🎉  

```
15 tests passed
=== RUN   TestAccAWSEcsService_withEcsClusterName
--- PASS: TestAccAWSEcsService_withEcsClusterName (14.92s)
=== RUN   TestAccAWSEcsService_withRenamedCluster
--- PASS: TestAccAWSEcsService_withRenamedCluster (21.81s)
=== RUN   TestAccAWSEcsService_withFamilyAndRevision
--- PASS: TestAccAWSEcsService_withFamilyAndRevision (34.78s)
=== RUN   TestAccAWSEcsService_withDeploymentValues
--- PASS: TestAccAWSEcsService_withDeploymentValues (35.34s)
=== RUN   TestAccAWSEcsService_withUnnormalizedPlacementStrategy
--- PASS: TestAccAWSEcsService_withUnnormalizedPlacementStrategy (36.29s)
=== RUN   TestAccAWSEcsService_withPlacementConstraints
--- PASS: TestAccAWSEcsService_withPlacementConstraints (37.70s)
=== RUN   TestAccAWSEcsService_withPlacementStrategy
--- PASS: TestAccAWSEcsService_withPlacementStrategy (40.06s)
=== RUN   TestAccAWSEcsService_withPlacementConstraints_emptyExpression
--- PASS: TestAccAWSEcsService_withPlacementConstraints_emptyExpression (44.88s)
=== RUN   TestAccAWSEcsService_withARN
--- PASS: TestAccAWSEcsService_withARN (68.66s)
=== RUN   TestAccAWSEcsService_withLaunchTypeEC2AndNetworkConfiguration
--- PASS: TestAccAWSEcsService_withLaunchTypeEC2AndNetworkConfiguration (74.69s)
=== RUN   TestAccAWSEcsService_withIamRole
--- PASS: TestAccAWSEcsService_withIamRole (124.65s)
=== RUN   TestAccAWSEcsService_withAlb
--- PASS: TestAccAWSEcsService_withAlb (214.91s)
=== RUN   TestAccAWSEcsService_healthCheckGracePeriodSeconds
--- PASS: TestAccAWSEcsService_healthCheckGracePeriodSeconds (221.19s)
=== RUN   TestAccAWSEcsService_withLbChanges
--- PASS: TestAccAWSEcsService_withLbChanges (228.72s)
=== RUN   TestAccAWSEcsService_withLaunchTypeFargate
--- PASS: TestAccAWSEcsService_withLaunchTypeFargate (271.02s)
```

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.9.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#190-february-09-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
