### PR TITLE
Change EC2 Instance root volume size without re-creating

### LINKED ISSUE #105: aws_instance: TF is ignoring the new root_block_device value
_This issue was originally opened by @rafabordon as hashicorp/terraform#5640. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

Terraform version 0.6.12
The AMI used had 30gb by default.We wanted to enlarge the block device to 50gb.'terraform plan' didn´t notice the change.

### LINKED ISSUE #139: aws_instance: root_block_device: Cannot attach root ebs volume correctly on EC2 Windows Instance
_This issue was originally opened by @zhefanlin as hashicorp/terraform#6108. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

Version 0.6.14 and 0.6.13
When using "root_device_block" in aws_instance resource block to create a windows intance, AMI had 40GB by default, I set the root_block device size to 50GB,

"terraform plan" did noticed the root size change, but after "terraform apply", the block device /dev/sda1 on AWS console still 40GB, besides the /dev/sda1, there was another device called xvdco which is 50GB.

image

I log in that instance, found xvdco in windows disk manager as Disk D:, the disk C:\ was still defualt 40GB

image
Note: the two temporary disks are SSD coming with c3.xlarge

image

Cannot reproduce every time, sometimes it works fine...

If I use "ebs_block_device" plus device_name="/dev/sda1" instead of "root_block device", it works fine each time, root disk got attached and mount correctly, but it will recreate instance resource if I want to re-apply without destroy it.

**Below is my code:**
resource "aws_instance" "inst" {
  provider = "aws.windows_instance_${var.num_drive}_drives"
  ami = "${var.ami_id}"
  instance_type = "${var.instance_type}"
  key_name = "${var.key}"
  source_dest_check = false
  associate_public_ip_address = "${var.assoc_public_addr}"
  subnet_id = "${var.subnet_id}"
  security_groups = ["${var.security_group_id}"]

  # C:\ drive
    root_block_device {
    # device_name = "/dev/sda1"
    volume_size = "${element(split(",",var.volume_size), 0)}"
    volume_type = "${var.volume_type}"
    delete_on_termination = true
  }

  user_data = "${template_file.winconfig.rendered}"

  tags {
    Application = "${var.stack_name}"
    Name = "${var.name}"
  }
}

"terraform plan" Output:
image

"terraform apply" Output:
image

### LINKED ISSUE #172: Changes to aws_instance "root_block_device" do not trigger resource update/recreation
_This issue was originally opened by @modax as hashicorp/terraform#6762. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

Hello,

it appears that changes to the aws_instance#root_block_device fields do not trigger resource updates (i.e. diff is not generated for it).

Below you will find a test case which exposes this problem. The schema is based on what's currently in "root_block_device" in `builtin/providers/aws/resource_aws_instance.go`.

Running it results in:

```
$  make test TEST=./helper/schema TESTARGS="-run TestSchemaMap_Diff"
==> Checking that code complies with gofmt requirements...
/home/modax/go/bin/stringer
go generate $(go list ./... | grep -v /vendor/)
2016/05/19 11:25:40 Generated command/internal_plugin_list.go
TF_ACC= go test ./helper/schema -run TestSchemaMap_Diff -timeout=30s -parallel=4
--- FAIL: TestSchemaMap_Diff (0.00s)
        schema_test.go:2505: #"#61 - computed set with some implicit values":

                expected:
                *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"root_block_device.0.delete_on_termination":*terraform.ResourceAttrDiff{Old:"false", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "root_block_device.0.volume_size":*terraform.ResourceAttrDiff{Old:"8", New:"50", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}}, Destroy:false, DestroyTainted:false}

                got:
                <nil>
FAIL
FAIL    github.com/hashicorp/terraform/helper/schema    0.005s
Makefile:37: recipe for target 'test' failed
make: *** [test] Error 1
```

``` diff
--- a/helper/schema/schema_test.go
+++ b/helper/schema/schema_test.go
@@ -2351,6 +2351,87 @@ func TestSchemaMap_Diff(t *testing.T) {
                        Err: false,
                },

+               "#61 - computed set with some implicit values": {
+                       Schema: map[string]*Schema{
+                               "root_block_device": &Schema{
+                                       Type:     TypeSet,
+                                       Optional: true,
+                                       Computed: true,
+                                       Elem: &Resource{
+                                               Schema: map[string]*Schema{
+                                                       "delete_on_termination": &Schema{
+                                                               Type:     TypeBool,
+                                                               Optional: true,
+                                                               Default:  true,
+                                                               ForceNew: true,
+                                                       },
+
+                                                       "iops": &Schema{
+                                                               Type:     TypeInt,
+                                                               Optional: true,
+                                                               Computed: true,
+                                                               ForceNew: true,
+                                                       },
+
+                                                       "volume_size": &Schema{
+                                                               Type:     TypeInt,
+                                                               Optional: true,
+                                                               Computed: true,
+                                                               ForceNew: true,
+                                                       },
+
+                                                       "volume_type": &Schema{
+                                                               Type:     TypeString,
+                                                               Optional: true,
+                                                               Computed: true,
+                                                               ForceNew: true,
+                                                       },
+                                               },
+                                       },
+                                       Set: func(v interface{}) int {
+                                               return 0
+                                       },
+                               },
+                       },
+
+                       State: &terraform.InstanceState{
+                               Attributes: map[string]string{
+                                       "root_block_device.#":                       "1",
+                                       "root_block_device.0.delete_on_termination": "false",
+                                       "root_block_device.0.iops":                  "24",
+                                       "root_block_device.0.volume_size":           "8",
+                                       "root_block_device.0.volume_type":           "gp2",
+                               },
+                       },
+
+                       Config: map[string]interface{}{
+                               "root_block_device": []map[string]interface{}{
+                                       map[string]interface{}{
+                                               "delete_on_termination": "true",
+                                               "volume_size":           50,
+                                               "volume_type":           "gp2",
+                                       },
+                               },
+                       },
+
+                       Diff: &terraform.InstanceDiff{
+                               Attributes: map[string]*terraform.ResourceAttrDiff{
+                                       "root_block_device.0.delete_on_termination": &terraform.ResourceAttrDiff{
+                                               Old:         "false",
+                                               New:         "true",
+                                               RequiresNew: true,
+                                       },
+                                       "root_block_device.0.volume_size": &terraform.ResourceAttrDiff{
+                                               Old:         "8",
+                                               New:         "50",
+                                               RequiresNew: true,
+                                       },
+                               },
+                       },
+
+                       Err: false,
+               },
+
                "Bools can be set with 0/1 in config, still get true/false": {
                        Schema: map[string]*Schema{
                                "one": &Schema{
```

Terraform version 0.6.16 / current master

### LINKED ISSUE #418: Resource recreation needed for aws_instance with root_block_device even though no attributes changed
_This issue was originally opened by @alex-aver as hashicorp/terraform#10625. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version
0.7.13

### Affected Resource(s)
- aws_instance

### Terraform Configuration Files

```
resource "aws_instance" "tableau-main" {
  ami                         = "${var.tableau_ami_id}"
  availability_zone           = "${var.region}a"
  instance_type               = "${var.tableau_instance_type}"
  key_name                    = "${var.tableau_key_name}"
  monitoring                  = true
  vpc_security_group_ids      = "${var.tableau_main_sgs}"
  subnet_id                   = "${var.tableau_main_subnet}"
  iam_instance_profile        = "${var.tableau_iam_profile}"
  tenancy                     = "${var.tableau_tenancy}"

  tags {
    Name               = "tableau-${var.environment-name}"
    ProvisioningGroup  = "tableau-windows"
  }

  root_block_device {
    volume_size = "${volume-size-common}"
  }
}
```

I originally created an instance using the above configuration, although the `volume_size` attribute was hard coded.

I did some refactoring to the module and as a result I removed this instance from Terraform management, then re-imported it. 

Now if I do a terraform plan, Terraform reports that the root block device will have a new resource forced, even though the only attribute that's specified is the `volume_size`, which is not set to be different:

```
    root_block_device.0.delete_on_termination:  "true" => "false" (forces new resource)
    root_block_device.~0.delete_on_termination: "" => "true" (forces new resource)
    root_block_device.~0.iops:                  "" => "<computed>" (forces new resource)
    root_block_device.~0.volume_size:           "" => "<computed>" (forces new resource)
    root_block_device.~0.volume_type:           "" => "<computed>" (forces new resource)
```

You can see from the terraform plan output that even though everything is the same, a new resource is forced.

If I remove the root_block_device block entirely, this problem doesn't occur, but if I want to reuse this module I'm going to need to specify volume_size

### Expected Behavior
Terraform should recognize that the root block device exists and already meets my configuration specifications.

### Actual Behavior
The plan forces a new resource even though nothing appears to have changed.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. have an aws_instance with a root_block_device specified, in my case with only volume_size specified
2. `terraform state rm` that instance
3. `terraform import` that instance back in
4. `terraform plan`

### References
I'd say this is kinda-sorta similar to this:
- GH-1260

### LINKED ISSUE #609: root device volume change forces new resource, ebs device volume size not detected
_This issue was originally opened by @adespain as hashicorp/terraform#12697. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version
Version 0.8.8

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance

### Terraform Configuration Files
```hcl
variable "ubuntu16_encrypted" { default = "ami-8c07b7ec" }
resource "aws_instance" "deleteme" {
  instance_type = "t2.micro"
  ami = "${var.ubuntu16_encrypted}"
  vpc_security_group_ids = ["${aws_security_group.vpn-sg.id}"]
  subnet_id = "subnet-xxxxxxxxx"
  root_block_device {
    volume_type = "gp2"
    volume_size = "12"
  }
  ebs_block_device {
    device_name = "/dev/xvdc"
    volume_size = 14
    volume_type = "gp2"
    encrypted = "true"
  }
  ebs_block_device {
    device_name = "/dev/xvdd"
    volume_size = 5
    volume_type = "gp2"
    encrypted = "true"
  }
  ebs_block_device {
    device_name = "/dev/xvde"
    volume_size = 2
    volume_type = "gp2"
    encrypted = "true"
  }
  ebs_block_device {
    device_name = "/dev/xvdf"
    volume_size = 2
    volume_type = "gp2"
    encrypted = "true"
  }
  ebs_block_device {
    device_name = "/dev/xvdg"
    volume_size = 2
    volume_type = "gp2"
    encrypted = "true"
  }
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
I changed the size of the root block device and ebs block device.  It shouldn't force a new resource, should just change the size of the volumes since 0.8.8 supports elastic volumes.

### Actual Behavior
What actually happened?
The terraform plan said it would force new resource for the root volume, and didn't detect the ebs block volume size change.

terraform plan results snippet:

 root_block_device.0.volume_size:                   "10" => "12" (forces new resource)
    root_block_device.0.volume_type:                   "gp2" => "gp2"
    security_groups.#:                                 "0" => "<computed>"
    source_dest_check:                                 "true" => "true"
    subnet_id:                                         "subnet-bfb3b2d7" => "subnet-bfb3b2d7"
    tags.%:                                            "1" => "1"
    tags.Name:                                         "zionsfx-deleteme" => "zionsfx-deleteme"
    tenancy:                                           "default" => "<computed>"
    vpc_security_group_ids.#:                          "1" => "1"
    vpc_security_group_ids.263195511:                  "sg-a73612c3" => "sg-a73612c3"

Plan: 1 to add, 0 to change, 1 to destroy.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Change the volume_size of the root and ebs block devices and then run `terraform plan`

### Important Factoids
 This is an encrypted ami and encrypted ebs block devices as you can see in the terraform config.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

### LINKED ISSUE #768: Changing root_block_device.volume_size forces new resource (aws_instance)
_This issue was originally opened by @cweagans as hashicorp/terraform#14445. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version
v0.9.5

### Affected Resource(s)
- aws_instance

#### Before:
```hcl
provider "aws" {
  region = "us-east-1"
}

data "aws_ami" "ubuntu" {
  most_recent = true

  filter {
    name = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-*"]
  }

  filter {
    name = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["099720109477"]
}

resource "aws_instance" "test_instance" {
  ami = "${data.aws_ami.ubuntu.id}"
  instance_type = "t2.micro"

  tags {
    Name = "cweagans-test-instance"
  }
}
```

#### After:
```hcl
provider "aws" {
  region = "us-east-1"
}

data "aws_ami" "ubuntu" {
  most_recent = true

  filter {
    name = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-*"]
  }

  filter {
    name = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["099720109477"]
}

resource "aws_instance" "test_instance" {
  ami = "${data.aws_ami.ubuntu.id}"
  instance_type = "t2.micro"

  tags {
    Name = "cweagans-test-instance"
  }

  root_block_device {
    volume_size = "100"
  }
}
```

### Expected Behavior
Root volume should have been resized from the default 8GB to 100GB without deleting the instance in the process.

### Actual Behavior
The instance was deleted and recreated.

### Steps to Reproduce
`terraform apply` the first config above, change config to the second one, and `terraform apply` again.

### LINKED ISSUE #4196: aws_instance - Changing the size of the root block volume on a instance causes the instance to be destroyed and recreated
This issue is detailed at length here (previous to the providers becoming their own repos):

https://github.com/hashicorp/terraform/issues/14445

```
$ terraform --version
Terraform v0.11.7
+ provider.aws v1.14.1
+ provider.null v1.0.0
```

Say you have and instance with a 

```
      root_block_device.#:                       "1" => "1"
      root_block_device.0.delete_on_termination: "false" => "false"
      root_block_device.0.volume_id:             "vol-0d0c01311126965f8" => <computed>
      root_block_device.0.volume_size:           "40" => "41" (forces new resource)
      root_block_device.0.volume_type:           "gp2" => "gp2"
```

This issue is a huge pain if you have servers that cannot be destroyed and recreated at will, especially the Windows based images .  The current work flow now is:

1. Change the size of the root ebs volume outside of terraform
2. Edit the TerraForm files to reflect the new number
3. Apply the new TerraForm file to update the state files

The change does not require or force a reboot.  It does require that you tell the OS to expand the volume.  There is no expectation that TerraForm will be required to tell the OS of the change, just like changing the instance type with TerraForm doesn't force the instance to reboot.

It would be nice to have a root volume size increase not require that extra non-TerraForm step of manually interacting with the AWS console or cli.

### LINKED ISSUE #4219: increase in ebs volume size doesn't work when used in aws_instance
_This issue was originally opened by @amjad489 as hashicorp/terraform#17868. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version

```
Terraform v0.11.4
```

### Terraform Configuration Files

```hcl
resource "aws_instance" "test_instance" {
  ...
  root_block_device {
    volume_type           = "gp2"
    volume_size           = "30"
    delete_on_termination = "false"
  }

....
  ebs_block_device {
    device_name           = "/dev/sdg"
    volume_type           = "gp2"
    volume_size           = "30"
  }

....
}
```

### Expected Behavior

when the template is run for the first time it will create instance with root and ebs volume which is fine. later if we want to increase the ebs volume size it should increase the size
### Actual Behavior

doesn't increase the size
### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. Increase the ebs_volume size
4. `terraform apply`
nothing changes

### LINKED ISSUE #8729: Modifying the root_block_device type from standard to gp2 should not recreate EC2 instance
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS is now supporting on the fly EC2 volume modifications. Terraform should not recreate instances while modifying standard volume to gp2 or iops. Terraform should also accomodate this on the fly modifcation feature.

### New or Affected Resource(s)

* aws_instance

### Potential Terraform Configuration

```hcl
-/+ module.app_server.aws_instance.main[0] (new resource required)
      **id:                                        "xxxxxxx" => <computed> (forces new resource)**
      ami:                                       "ami-bb9a6bc2" => "ami-bb9a6bc2"
      arn:                                       "xxxxxx" => <computed>
      associate_public_ip_address:               "true" => "true"
      availability_zone:                         "eu-west-1a" => "eu-west-1a"
      cpu_core_count:                            "2" => <computed>
      cpu_threads_per_core:                      "1" => <computed>
      disable_api_termination:                   "true" => "true"
      ebs_block_device.#:                        "0" => <computed>
      ebs_optimized:                             "false" => "false"
      ephemeral_block_device.#:                  "0" => <computed>
      get_password_data:                         "false" => "false"
      iam_instance_profile:                      "xxxxxxxxx" => "xxxxxxxxxx"
      instance_initiated_shutdown_behavior:      "stop" => "stop"
      instance_state:                            "running" => <computed>
      instance_type:                             "t2.large" => "t2.large"
      ipv6_address_count:                        "" => <computed>
      ipv6_addresses.#:                          "0" => <computed>
      network_interface.#:                       "0" => <computed>
      network_interface_id:                      "xxxxxxxx" => <computed>
      password_data:                             "" => <computed>
      placement_group:                           "" => <computed>
      primary_network_interface_id:              "xxxxxxxxxxxx" => <computed>
      private_dns:                               "xxxxxxxxxxx" => <computed>
      private_ip:                                "xxxxxxxxx" => <computed>
      public_dns:                                "xxxxxxxxxxxx" => <computed>
      public_ip:                                 "xxxxxxxxxx" => <computed>
      root_block_device.#:                       "1" => "1"
      root_block_device.0.delete_on_termination: "true" => "true"
      root_block_device.0.volume_id:             "xxxxxxxx" => <computed>
      root_block_device.0.volume_size:           "30" => "30"
      **root_block_device.0.volume_type:           "standard" => "gp2" (forces new resource)**
  ....
```

### PR DESCRIPTION
**Pull request by gdavison**
This PR picks up on the work done by @viscat in #1396 to allow changing EC2 instance root volume size without re-creating the instance.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #1396
Closes #768
Closes #8729
Closes #4219
Closes #4196
Closes #609
Closes #418
Closes #172
Closes #139
Closes #105

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_instance: Allow changing root volume size without re-creating resource
resource/aws_instance: Exports `volume_name` for `root_block_device`
data-source/aws_instance: Returns `volume_name` for `root_block_device`
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSInstance_'

--- PASS: TestAccAWSInstance_CreditSpecification_Empty_NonBurstable (279.76s)
--- PASS: TestAccAWSInstance_CreditSpecification_UnspecifiedToEmpty_NonBurstable (66.94s)
--- PASS: TestAccAWSInstance_EbsBlockDevice_KmsKeyArn (97.32s)
--- PASS: TestAccAWSInstance_EbsRootDevice_ModifyAll (122.86s)
--- PASS: TestAccAWSInstance_EbsRootDevice_ModifyDeleteOnTermination (117.01s)
--- PASS: TestAccAWSInstance_EbsRootDevice_ModifyIOPS (125.10s)
--- PASS: TestAccAWSInstance_EbsRootDevice_ModifySize (116.33s)
--- PASS: TestAccAWSInstance_EbsRootDevice_ModifyType (135.45s)
--- PASS: TestAccAWSInstance_EbsRootDevice_MultipleBlockDevices_ModifyDeleteOnTermination (86.46s)
--- PASS: TestAccAWSInstance_EbsRootDevice_MultipleBlockDevices_ModifySize (127.49s)
--- PASS: TestAccAWSInstance_EbsRootDevice_basic (73.44s)
--- PASS: TestAccAWSInstance_GP2IopsDevice (90.68s)
--- PASS: TestAccAWSInstance_GP2WithIopsValue (85.17s)
--- PASS: TestAccAWSInstance_NetworkInstanceRemovingAllSecurityGroups (84.62s)
--- PASS: TestAccAWSInstance_NetworkInstanceSecurityGroups (192.94s)
--- PASS: TestAccAWSInstance_NetworkInstanceVPCSecurityGroupIDs (77.00s)
--- PASS: TestAccAWSInstance_RootBlockDevice_KmsKeyArn (301.24s)
--- PASS: TestAccAWSInstance_UserData_EmptyStringToUnspecified (86.14s)
--- PASS: TestAccAWSInstance_UserData_UnspecifiedToEmptyString (88.58s)
--- PASS: TestAccAWSInstance_addSecondaryInterface (129.52s)
--- PASS: TestAccAWSInstance_addSecurityGroupNetworkInterface (124.41s)
--- PASS: TestAccAWSInstance_associatePublicIPAndPrivateIP (75.43s)
--- PASS: TestAccAWSInstance_associatePublic_defaultPrivate (105.55s)
--- PASS: TestAccAWSInstance_associatePublic_defaultPublic (69.46s)
--- PASS: TestAccAWSInstance_associatePublic_explicitPrivate (86.34s)
--- PASS: TestAccAWSInstance_associatePublic_explicitPublic (71.78s)
--- PASS: TestAccAWSInstance_associatePublic_overridePrivate (89.85s)
--- PASS: TestAccAWSInstance_associatePublic_overridePublic (92.80s)
--- PASS: TestAccAWSInstance_basic (130.01s)
--- PASS: TestAccAWSInstance_blockDevices (80.54s)
--- PASS: TestAccAWSInstance_changeInstanceType (241.52s)
--- PASS: TestAccAWSInstance_creditSpecificationT3_standardCpuCredits (110.11s)
--- PASS: TestAccAWSInstance_creditSpecificationT3_unlimitedCpuCredits (116.89s)
--- PASS: TestAccAWSInstance_creditSpecificationT3_unspecifiedDefaultsToUnlimited (323.91s)
--- PASS: TestAccAWSInstance_creditSpecificationT3_updateCpuCredits (133.02s)
--- PASS: TestAccAWSInstance_creditSpecification_isNotAppliedToNonBurstable (117.66s)
--- PASS: TestAccAWSInstance_creditSpecification_standardCpuCredits (93.15s)
--- PASS: TestAccAWSInstance_creditSpecification_standardCpuCredits_t2Tot3Taint (413.14s)
--- PASS: TestAccAWSInstance_creditSpecification_unknownCpuCredits_t2 (73.28s)
--- PASS: TestAccAWSInstance_creditSpecification_unknownCpuCredits_t3 (314.39s)
--- PASS: TestAccAWSInstance_creditSpecification_unlimitedCpuCredits (97.38s)
--- PASS: TestAccAWSInstance_creditSpecification_unlimitedCpuCredits_t2Tot3Taint (392.44s)
--- PASS: TestAccAWSInstance_creditSpecification_unspecifiedDefaultsToStandard (76.55s)
--- PASS: TestAccAWSInstance_creditSpecification_updateCpuCredits (113.49s)
--- PASS: TestAccAWSInstance_disableApiTermination (116.04s)
--- PASS: TestAccAWSInstance_disappears (224.59s)
--- PASS: TestAccAWSInstance_forceNewAndTagsDrift (243.26s)
--- PASS: TestAccAWSInstance_getPasswordData_falseToTrue (148.03s)
--- PASS: TestAccAWSInstance_getPasswordData_trueToFalse (170.56s)
--- PASS: TestAccAWSInstance_hibernation (365.55s)
--- PASS: TestAccAWSInstance_inDefaultVpcBySgId (83.62s)
--- PASS: TestAccAWSInstance_inDefaultVpcBySgName (64.52s)
--- PASS: TestAccAWSInstance_instanceProfileChange (195.15s)
--- PASS: TestAccAWSInstance_ipv6AddressCountAndSingleAddressCausesError (10.90s)
--- PASS: TestAccAWSInstance_ipv6_supportAddressCount (85.75s)
--- PASS: TestAccAWSInstance_ipv6_supportAddressCountWithIpv4 (75.29s)
--- PASS: TestAccAWSInstance_keyPairCheck (63.96s)
--- PASS: TestAccAWSInstance_metadataOptions (117.30s)
--- PASS: TestAccAWSInstance_multipleRegions (251.16s)
--- PASS: TestAccAWSInstance_noAMIEphemeralDevices (176.35s)
--- PASS: TestAccAWSInstance_placementGroup (58.66s)
--- PASS: TestAccAWSInstance_primaryNetworkInterface (200.28s)
--- PASS: TestAccAWSInstance_primaryNetworkInterfaceSourceDestCheck (80.50s)
--- PASS: TestAccAWSInstance_privateIP (105.85s)
--- PASS: TestAccAWSInstance_rootBlockDeviceMismatch (65.40s)
--- PASS: TestAccAWSInstance_rootInstanceStore (80.19s)
--- PASS: TestAccAWSInstance_sourceDestCheck (135.51s)
--- PASS: TestAccAWSInstance_tags (117.10s)
--- PASS: TestAccAWSInstance_userDataBase64 (131.52s)
--- PASS: TestAccAWSInstance_volumeTags (103.12s)
--- PASS: TestAccAWSInstance_volumeTagsComputed (104.15s)
--- PASS: TestAccAWSInstance_vpc (105.62s)
--- PASS: TestAccAWSInstance_withIamInstanceProfile (116.03s)
```

```
$ make testacc TESTARGS='-run=TestAccAWSInstanceDataSource_'

--- PASS: TestAccAWSInstanceDataSource_AzUserData (127.32s)
--- PASS: TestAccAWSInstanceDataSource_EbsBlockDevice_KmsKeyId (120.33s)
--- PASS: TestAccAWSInstanceDataSource_GetUserData (281.72s)
--- PASS: TestAccAWSInstanceDataSource_GetUserData_NoUserData (121.36s)
--- PASS: TestAccAWSInstanceDataSource_PlacementGroup (91.08s)
--- PASS: TestAccAWSInstanceDataSource_RootBlockDevice_KmsKeyId (129.05s)
--- PASS: TestAccAWSInstanceDataSource_SecurityGroups (252.55s)
--- PASS: TestAccAWSInstanceDataSource_VPC (99.88s)
--- PASS: TestAccAWSInstanceDataSource_VPCSecurityGroups (82.35s)
--- PASS: TestAccAWSInstanceDataSource_basic (239.47s)
--- PASS: TestAccAWSInstanceDataSource_blockDevices (88.09s)
--- PASS: TestAccAWSInstanceDataSource_creditSpecification (94.08s)
--- PASS: TestAccAWSInstanceDataSource_getPasswordData_falseToTrue (145.38s)
--- PASS: TestAccAWSInstanceDataSource_getPasswordData_trueToFalse (158.64s)
--- PASS: TestAccAWSInstanceDataSource_gp2IopsDevice (185.66s)
--- PASS: TestAccAWSInstanceDataSource_keyPair (68.87s)
--- PASS: TestAccAWSInstanceDataSource_metadataOptions (164.02s)
--- PASS: TestAccAWSInstanceDataSource_privateIP (71.22s)
--- PASS: TestAccAWSInstanceDataSource_rootInstanceStore (113.55s)
--- PASS: TestAccAWSInstanceDataSource_tags (238.13s)
```

```
$ make testacc TESTARGS='-run=TestAccAWSSSMAssociation_'

--- PASS: TestAccAWSSSMAssociation_basic (75.04s)
--- PASS: TestAccAWSSSMAssociation_rateControl (19.04s)
--- PASS: TestAccAWSSSMAssociation_withAssociationName (14.00s)
--- PASS: TestAccAWSSSMAssociation_withAssociationNameAndScheduleExpression (14.62s)
--- PASS: TestAccAWSSSMAssociation_withAutomationTargetParamName (34.09s)
--- PASS: TestAccAWSSSMAssociation_withComplianceSeverity (18.50s)
--- PASS: TestAccAWSSSMAssociation_withDocumentVersion (8.35s)
--- PASS: TestAccAWSSSMAssociation_withOutputLocation (30.30s)
--- PASS: TestAccAWSSSMAssociation_withParameters (13.85s)
--- PASS: TestAccAWSSSMAssociation_withScheduleExpression (15.64s)
--- PASS: TestAccAWSSSMAssociation_withTargets (19.89s)
```

```
$ make testacc TESTARGS='-run=TestAccAWSSpotInstanceRequest'

--- PASS: TestAccAWSSpotInstanceRequestInterruptHibernate (300.50s)
--- PASS: TestAccAWSSpotInstanceRequestInterruptStop (280.14s)
--- PASS: TestAccAWSSpotInstanceRequest_NetworkInterfaceAttributes (104.42s)
--- PASS: TestAccAWSSpotInstanceRequest_SubnetAndSGAndPublicIpAddress (104.18s)
--- PASS: TestAccAWSSpotInstanceRequest_basic (117.23s)
--- PASS: TestAccAWSSpotInstanceRequest_getPasswordData (240.54s)
--- PASS: TestAccAWSSpotInstanceRequest_validUntil (99.43s)
--- PASS: TestAccAWSSpotInstanceRequest_vpc (104.18s)
--- PASS: TestAccAWSSpotInstanceRequest_withBlockDuration (109.66s)
--- PASS: TestAccAWSSpotInstanceRequest_withLaunchGroup (59.89s)
--- PASS: TestAccAWSSpotInstanceRequest_withoutSpotPrice (78.79s)
```

### CODE REVIEW

File: aws/resource_aws_instance.go [hunk 1]
```diff
@@ -1260,6 +1254,95 @@ func resourceAwsInstanceUpdate(d *schema.ResourceData, meta interface{}) error {
...
+		if err != nil {
+			return fmt.Errorf("error retrieving volumes for instance %q: %w", d.Id(), err)
+		}
+		rd, ok := blockDevices["root"]
+		if !ok {
+			return fmt.Errorf("root volume no found for instance %q", d.Id())
+		}
+
+		rootDevice := rd.(map[string]interface{})
+		volumeID := rootDevice["volume_id"].(string)
```
Comment (bflad) [inline aws/resource_aws_instance.go:1272]: We should fetch the volume ID and other attributes from state (`d.Get()`) or diff (`d.GetChange()`), rather than using an additional API call 👍

File: aws/resource_aws_instance.go [hunk 2]
```diff
@@ -1260,6 +1254,95 @@ func resourceAwsInstanceUpdate(d *schema.ResourceData, meta interface{}) error {
...
+		input := ec2.ModifyVolumeInput{
+			VolumeId: aws.String(volumeID),
+		}
+		modifyVolume := false
+
+		rbd := d.Get("root_block_device.0").(map[string]interface{})
+		if v, ok := rbd["volume_size"]; ok {
+			currSize := rootDevice["volume_size"].(int64)
+			volumeSize := int64(v.(int))
+			if volumeSize != currSize {
```
Comment (bflad) [inline aws/resource_aws_instance.go:1282]: The existing root block device information can be fetched via `d.GetChange()` or to skip all this for each attribute, you can use `d.HasChange()` with the nested attributes, e.g. `d.HasChange("root_block_device.0.volume_size")`

File: aws/resource_aws_instance.go [hunk 3]
```diff
@@ -1260,6 +1254,95 @@ func resourceAwsInstanceUpdate(d *schema.ResourceData, meta interface{}) error {
...
+			iops := int64(v.(int))
+			if iops != currIOPS {
+				modifyVolume = true
+				input.Iops = aws.Int64(iops)
+			}
+		}
+		if modifyVolume {
+			_, err = conn.ModifyVolume(&input)
+			if err != nil {
+				return err
```
Comment (bflad) [inline aws/resource_aws_instance.go:1306]: Nit: Prefer to return error context here for operators and code maintainers:

```suggestion
				return fmt.Errorf("error modifying EC2 Volume (%s): %w", volumeID, err)
```

File: aws/resource_aws_instance.go [hunk 4]
```diff
@@ -1260,6 +1254,95 @@ func resourceAwsInstanceUpdate(d *schema.ResourceData, meta interface{}) error {
...
+		}
+
+		if v, ok := rbd["delete_on_termination"]; ok {
+			_, err := conn.ModifyInstanceAttribute(&ec2.ModifyInstanceAttributeInput{
+				InstanceId: aws.String(d.Id()),
+				BlockDeviceMappings: []*ec2.InstanceBlockDeviceMappingSpecification{
+					{
+						DeviceName: aws.String(rootDevice["device_name"].(string)),
+						Ebs: &ec2.EbsInstanceBlockDeviceSpecification{
+							// VolumeId:            aws.String(volumeID),
```
Comment (bflad) [inline aws/resource_aws_instance.go:1334]: Nit: Commented code should be removed

```suggestion
```

File: aws/resource_aws_instance.go [hunk 5]
```diff
@@ -1260,6 +1254,95 @@ func resourceAwsInstanceUpdate(d *schema.ResourceData, meta interface{}) error {
...
+							DeleteOnTermination: aws.Bool(v.(bool)),
+						},
+					},
+				},
+			})
+			if err != nil {
+				return err
```
Comment (bflad) [inline aws/resource_aws_instance.go:1341]: Nit:

```suggestion
				return fmt.Errorf("error modifying EC2 Instance (%s) block device (%s) delete on termination attribute: %w", d.Id(), rootDevice["device_name"].(string), err)
```

File: aws/resource_aws_instance.go [hunk 6]
```diff
@@ -1282,35 +1365,54 @@ func resourceAwsInstanceDelete(d *schema.ResourceData, meta interface{}) error {
...
-		if resp == nil || len(resp.Reservations) == 0 || len(resp.Reservations[0].Instances) == 0 {
+		if instance == nil {
 			// Sometimes AWS just has consistency issues and doesn't see
 			// our instance yet. Return an empty state.
 			return nil, "", nil
 		}
 
-		i := resp.Reservations[0].Instances[0]
-		state := *i.State.Name
+		state := *instance.State.Name
```
Comment (bflad) [inline aws/resource_aws_instance.go:1382]: Nit: Should add panic safety here while adjusting

```suggestion
		if instance.State == nil {
			return nil, "", nil
		}

		state := aws.StringValue(instance.State.Name)
```

File: aws/resource_aws_instance.go [hunk 7]
```diff
@@ -1282,35 +1365,54 @@ func resourceAwsInstanceDelete(d *schema.ResourceData, meta interface{}) error {
...
+		if err != nil {
+			if isAWSErr(err, "InvalidVolumeID.NotFound", "does not exist") {
+				return nil, "", nil
+			}
+			log.Printf("Error on VolumeStateRefresh: %s", err)
+			return nil, "", err
+		}
+
+		i := resp.VolumesModifications[0]
+		state := *i.ModificationState
```
Comment (bflad) [inline aws/resource_aws_instance.go:1411]: Nit: Same here about preventing potential panics:

```suggestion
		if resp == nil || len(resp.VolumesModifications) == 0 || resp.VolumesModifications[0] == nil {
			return nil, "", nil
		}

		i := resp.VolumesModifications[0]
		state := aws.StringValue(i.ModificationState)
```

File: aws/resource_aws_instance.go [hunk 8]
```diff
@@ -1282,35 +1365,54 @@ func resourceAwsInstanceDelete(d *schema.ResourceData, meta interface{}) error {
...
+		if state == failState {
+			return i, state, fmt.Errorf("Failed to reach target state. Reason: %s", *i.StatusMessage)
```
Comment (bflad) [inline aws/resource_aws_instance.go:1413]:
```suggestion
			return i, state, fmt.Errorf("Failed to reach target state. Reason: %s", aws.StringValue(i.StatusMessage))
```
