### PR TITLE
fix for dynamodb autoscaling policy import

### LINKED ISSUE #8306: Can the Regex for importing aws_appautoscaling_policy be relaxed to allow `/` symbols.
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.13
+ provider.aws v2.6.0
+ provider.cloudflare v1.12.0
+ provider.datadog v1.7.0
+ provider.template v2.1.1
```

### Affected Resource(s)
* aws_appautoscaling_policy

### Panic Output

```
Error: module.data_global.module.sisyphus_autoscaling_usw2.aws_appautoscaling_policy.dynamodb_table_read_policy (import id: dynamodb/table/sisyphus_userroles_with_team/dynamodb:table:ReadCapacityUnits/dynamodb:table:ReadCapacityUnits/table/sisyphus_userroles_with_team): 1 error(s) occurred:

* import module.data_global.module.test_autoscaling_usw2.aws_appautoscaling_policy.dynamodb_table_read_policy result: test: aws_appautoscaling_policy.dynamodb_table_read_policy: Failed to read scaling policy: Error retrieving scaling policies: ValidationException: 1 validation error detected: Value 'table' at 'scalableDimension' failed to satisfy constraint: Member must satisfy enum value set: [dynamodb:table:ReadCapacityUnits, dynamodb:index:ReadCapacityUnits, rds:cluster:ReadReplicaCount, elasticmapreduce:instancefleet:SpotCapacity, appstream:fleet:DesiredCapacity, dynamodb:index:WriteCapacityUnits, elasticmapreduce:instancefleet:OnDemandCapacity, rds:cluster:Capacity, dynamodb:table:WriteCapacityUnits, custom-resource:ResourceType:Property, sagemaker:variant:DesiredInstanceCount, ec2:spot-fleet-request:TargetCapacity, elasticmapreduce:instancegroup:InstanceCount, ecs:service:DesiredCount]

```

### Expected Behavior

- it should have imported successfully

### Actual Behavior

the required id `<service-namespace>/<resource-id>/<scalable-dimension>/<policy-name>` doesn't validate correctly if `policy-name` also includes `/` 

### Steps to Reproduce

- `terraform import module.data_global.module.sisyphus_autoscaling_usw2.aws_appautoscaling_policy.dynamodb_table_read_policy dynamodb/table/test/dynamodb:table:ReadCapacityUnits/DynamoDBReadCapacityUtilization:table/test`

### PR DESCRIPTION
**Pull request by jdecarli**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Fixes #8306

Changes proposed in this pull request:

* Adds a switch to handle DynamoDB, ECS and RDS application autoscaling policy resource ids when import happens

### CODE REVIEW

**Comment by nywilken** [comment]
@jdecarli thanks for contributing a fix for issue #8306. Quickly looking at the PR, the change looks  reasonable but I’ve not officially verified or tested. 

With that said, the issue states a failure that does not seem to be represented in the tests. Would you please add the accompanying tests to showcase that the following issue has been fixed. 
> Importing aws_appautoscaling_policy fails for DynamoDB policy


See our [contributing guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/CONTRIBUTING.md#enhancementbugfix-to-a-resource) for help with writing tests for the provider. 

Cheers!

**Comment by jdecarli** [comment]
Thanks for your quick response!

Sure @nywilken I'll work on that

**Comment by jdecarli** [comment]
@nywilken I did some refactor and added a unit test specifically for the fix.

Acceptance tests:
```bash
make testacc TEST=./aws/ TESTARGS='-run=Te stValidateAppautoscalingPolicyImportInput'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -parallel 20 -run=TestValidateAppautoscalingPolicyImportInput -timeout 120m
=== RUN   TestValidateAppautoscalingPolicyImportInput
--- PASS: TestValidateAppautoscalingPolicyImportInput (0.00s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       0.137s
```

Please, let me know if anything else is required.

Thanks!

**Comment by jdecarli** [comment]
Hi @nywilken does this pr requires anything else in order for merge? I can add any missing piece

File: aws/resource_aws_appautoscaling_policy_test.go [hunk 1]
```diff
@@ -310,6 +311,44 @@ func TestAccAWSAppautoScalingPolicy_ResourceId_ForceNew(t *testing.T) {
 	})
 }
 
+func TestValidateAppautoscalingPolicyImportInput(t *testing.T) {
```
Comment (nywilken) [inline aws/resource_aws_appautoscaling_policy_test.go]: Thanks for adding this unit test; unit test generally appear before acceptance tests. Please move this test to line 14 above `TestAccAWSAppautoScalingPolicy_basic`


In looking at the implementation I wonder if it makes more sense to have `validateAppautoscalingPolicyImportInput` split the input string and validate that each of the parts exists?

```go
serviceNamespace, resourceId, scalableDimension, policyName := validateAppautoscalingPolicyImportInput(test.input)
```

This would mean that you would have to change the implementation [here](https://github.com/terraform-providers/terraform-provider-aws/pull/8397/files#diff-2a2c001f00e78d15d3dad8c4aba0624dR431) but that will also allow for validating the expected number of parts. 


With that being said, are there any changes that need to be to the `TestAccAWSAppautoScalingPolicy_dynamoDb` test to validate your fix?

File: aws/resource_aws_appautoscaling_policy_test.go [hunk 2]
```diff
@@ -310,6 +311,44 @@ func TestAccAWSAppautoScalingPolicy_ResourceId_ForceNew(t *testing.T) {
...
+		}
+		if scalableDimension != test.expectedScalableDimension {
+			t.Errorf("scalableDimension interpolation error -> %s != %s", test.expectedScalableDimension, scalableDimension)
+		}
+		if policyName != test.expectedPolicyName {
+			t.Errorf("policyName interpolation error -> %s != %s", test.expectedPolicyName, policyName)
+		}
+	}
+}
+
```
Comment (nywilken) [inline aws/resource_aws_appautoscaling_policy_test.go]: Given your implementation details I would expect there being a complimentary change to `testAccCheckAWSAppautoscalingPolicyExists` as well. I will try to reproduce the exact issue to better understand the behaviour. So please let me know if this is an incorrect assumption.

File: aws/resource_aws_appautoscaling_policy.go [hunk 3]
```diff
@@ -430,6 +428,25 @@ func resourceAwsAppautoscalingPolicyImport(d *schema.ResourceData, meta interfac
...
+	var serviceNamespace, resourceId, scalableDimension, policyName string
+
+	switch idParts[0] {
+	case "ecs", "rds":
+		serviceNamespace = idParts[0]
+		resourceId = strings.Join(idParts[1:len(idParts)-2], "/")
+		scalableDimension = idParts[len(idParts)-2]
+		policyName = idParts[len(idParts)-1]
+	case "dynamodb":
+		serviceNamespace = idParts[len(idParts)-6]
```
[the remark this answers is not in the document]
Comment (jdecarli) [reply aws/resource_aws_appautoscaling_policy.go]: It should be `Part[0]` (I originally did it that way, I don't know why I change it while extracting it to the validate function). I'll fix that.

You're right, I'll try to improve that multi-part validation. (`len(idParts)`)

File: aws/resource_aws_appautoscaling_policy_test.go (hunk 1 above)
Comment (jdecarli) [reply aws/resource_aws_appautoscaling_policy_test.go]: I'll move the test to the "unit test" section. (line 14 above `TestAccAWSAppautoScalingPolicy_basic`).

Yes, I do agree it makes sense to have everything related to the validation inside the function. I'll move that inside `validateAppautoscalingPolicyImportInput`.

Yes, the changes required to `TestAccAWSAppautoScalingPolicy_dynamoDb` are related to the input expected on the [import command](https://www.terraform.io/docs/providers/aws/r/appautoscaling_policy.html#import) because the `ResourceId` and `PolicyName` format varies depending on the resource (ECS, RDS or DynamoDB).

File: aws/resource_aws_appautoscaling_policy_test.go (hunk 2 above)
Comment (jdecarli) [reply aws/resource_aws_appautoscaling_policy_test.go]: No, I think `testAccCheckAWSAppautoscalingPolicyExists` is out of scope as its validating the state file. Creation works fine, and the resources are correctly mapped. The problem occurs only while mapping the input in `resourceAwsAppautoscalingPolicyImport` (With my change, I was able to import several DynamoDB policies and continue using them to make changes with no issues)

File: aws/resource_aws_appautoscaling_policy_test.go (hunk 1 above)
Comment (jdecarli) [reply aws/resource_aws_appautoscaling_policy_test.go]: - Unit test moved to line 14
- Addded negative unit test cases
- Refactored to have all validations inside `validateAppautoscalingPolicyImportInput`

```bash
make t estacc TEST=./aws TESTARGS='-run=TestValidateAppautoscalingPolicyImportInput_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestValidateAppautoscalingPolicyImportInput_ -timeout 120m
=== RUN   TestValidateAppautoscalingPolicyImportInput_positiveCases
--- PASS: TestValidateAppautoscalingPolicyImportInput_positiveCases (0.00s)
=== RUN   TestValidateAppautoscalingPolicyImportInput_negativeCases
--- PASS: TestValidateAppautoscalingPolicyImportInput_negativeCases (0.00s)
```

I was not able to run the integration tests to reproduce the error. I'll keep trying and let you know

Comment (jdecarli) [reply aws/resource_aws_appautoscaling_policy_test.go]: Ok, I was able to reproduce and fix the integration test. Below the test results
```bash
make testacc TESTARGS="-run=TestAccAWSAppautoScaling Policy_dynamoDb"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSAppautoScalingPolicy_dynamoDb -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSAppautoScalingPolicy_dynamoDb
=== PAUSE TestAccAWSAppautoScalingPolicy_dynamoDb
=== CONT  TestAccAWSAppautoScalingPolicy_dynamoDb
--- PASS: TestAccAWSAppautoScalingPolicy_dynamoDb (147.54s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       147.597s
```

**Comment by jdecarli** [comment]
@nywilken I think I've addressed all suggested changes.

Changes:
- `serviceNamespace` is taken from `idParts[0]`
- `TestAccAWSAppautoScalingPolicy_basic` unit test moved to line 14
- Added negative unit test
- Refactored to have all validations inside validateAppautoscalingPolicyImportInput
- Fixed `TestAccAWSAppautoScalingPolicy_dynamoDb` integration test

Please let me know if there's anything else needed?

File: aws/resource_aws_appautoscaling_policy.go [hunk 4]
```diff
@@ -430,6 +425,33 @@ func resourceAwsAppautoscalingPolicyImport(d *schema.ResourceData, meta interfac
 	return []*schema.ResourceData{d}, nil
 }
 
+func validateAppautoscalingPolicyImportInput(idParts []string) (string, string, string, string, error) {
+	var serviceNamespace, resourceId, scalableDimension, policyName string
+
+	if len(idParts) < 4 || len(idParts) > 6 {
```
Comment (zarnovican) [inline aws/resource_aws_appautoscaling_policy.go]: just checked the doc (`aws application-autoscaling describe-scaling-policies help`).
* `resourceId` may contain from 0 to 3 "/" characters
* `scalableDimension` seems to be without "/"
* `policyName` can also contain variable number of "/": 0-3

It would be almost better to
* choose different field delimiter
* or, import by `serviceNamespace/policyName` (if it is unique in namespace)
* or, import by ARN

Comment (jdecarli) [reply aws/resource_aws_appautoscaling_policy.go]: Hi @zarnovican

Regarding your suggestions...

### Choose different field delimiter
If you check the [Terraform import documentation](https://www.terraform.io/docs/providers/aws/r/appautoscaling_policy.html#import) you will see the format Terraform chose for the input in all 3 cases (ecs, rds and dynamodb). Acording to that format, I also made 2 unit tests in `TestValidateAppautoscalingPolicyImportInput_positiveCases` and `TestValidateAppautoscalingPolicyImportInput_negativeCases`.

I might be wrong (I'm really new to golang), but as far as I can see the only possible delimiter is `/` (this is the input coming from the import command) and the problem is, as you mention, that it varies depending on the `serviceNamespace`. This is basically the root of the issue this pr tries to resolve.

Another option I found is to leave the code as it is, truncating the last item in the slice `idParts` which is the `tableName` (which also happens to be redundant, because its coming as the third element in the slice). But this will also force us to append this `tableName` element to the policy, and this will look pretty ugly in the code with something like this:

```golang
// truncating last redundant element
if idParts[0] == "dynamodb" {
	idParts = idParts[:len(idParts) -1]
}

serviceNamespace = idParts[0]
resourceId = strings.Join(idParts[1:len(idParts)-2], "/")
scalableDimension = idParts[len(idParts)-2]
policyName =  idParts[len(idParts)-1]

// appending tableName to the policy
if idParts[0] == "dynamodb" {
	policyName = policyName + "/" + idParts[2]
}
```

It removes the need for the switch, but adds the truncating and appending.

### Import by other fields (serviceNamespace/policyName or ARN)
I think this involves design changes that are out of scope for this issue. Seems like a nice suggestion, but I feel is up to the Terraform team to do some analysis on this. Maybe @nywilken can shed some light on this.

**Comment by nywilken** [comment]
@jdecarli I’m catching up with pending reviews - thanks for continuing to push this forward and for sticking with me. Give me a day to review and think about the latest comments.

**Comment by jdecarli** [comment]
> @jdecarli I’m catching up with pending reviews - thanks for continuing to push this forward and for sticking with me. Give me a day to review and think about the latest comments.

Sure, no worries @nywilken . Take your time, and let me know if you want me to make any other change.

**Comment by jdecarli** [comment]
Hi @nywilken 

Sorry for pinging again, I just don't want this pr to drift away too much from the codebase

Do you think we need to add anything else?

**Comment by nywilken** [comment]
We should also rebase on to the latest master.

**Comment by nywilken** [comment]
@jdecarli thanks for pushing this change forward. I went ahead and made the last suggested changes and rebased onto master to get this reviewed and merged. @bflad once the latest changes get pushed and it goes green would you mind take a second look.

**Comment by nywilken** [comment]
The fix to the `aws_appautoscaling_policy` resource, has been released in [version 2.20.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2200-july-19-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

For further feature requests or bug reports with this resource, please create a [new GitHub issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new/choose) following the template for triage. Thanks!
