### PR TITLE
resource/aws_codebuild_project: Prevent crash on empty source buildspec and location

### LINKED ISSUE #2673: aws_codebuild_project: plan crashes with "interface {} is nil, not string", "unexpected EOF", and "connection is shut down"
### Terraform Version
0.10.8, AWS provider 1.5.0

### Debug/Panic Output
https://gist.github.com/davido-bs/52edbd47426b69e5efd10e957ed1c417

### Expected Behavior
Plan should have been created.

### Actual Behavior
Error in the logs: `interface {} is nil, not string`. In the gist provided, it manifests itself as an "unexpected EOF" error.

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
The reproducability of this *may* be due to handling erroneous "stray" values in the state, as we have been doing a fairly large refactor. This is not the first time we've encountered this message though, so I'm putting it out there "for the record".

### PR DESCRIPTION
**Pull request by bflad**
Also simplifies flattenAwsCodebuildProjectSource and moves Set Hash declarations to schema.

Closes #2673 

```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSCodeBuildProject_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSCodeBuildProject_ -timeout 120m
=== RUN   TestAccAWSCodeBuildProject_basic
--- PASS: TestAccAWSCodeBuildProject_basic (39.20s)
=== RUN   TestAccAWSCodeBuildProject_default_build_timeout
--- PASS: TestAccAWSCodeBuildProject_default_build_timeout (36.96s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	76.212s
```

### CODE REVIEW

File: aws/resource_aws_codebuild_project.go [hunk 1]
```diff
@@ -386,10 +388,7 @@ func resourceAwsCodeBuildProjectRead(d *schema.ResourceData, meta interface{}) e
 		return err
 	}
 
-	if err := d.Set("source", flattenAwsCodebuildProjectSource(project.Source)); err != nil {
-		return err
-	}
-
+	d.Set("source", flattenAwsCodebuildProjectSource(project.Source))
```
Comment (radeksimko) [inline aws/resource_aws_codebuild_project.go]: I think the error check can be actually helpful here. 😺 

The convention we tend to follow is to have an error check for any fields which have nested fields under them. Not necessarily simple `[]string` but anything that has a potential of breaking - which is this case IMO.

Comment (bflad) [reply aws/resource_aws_codebuild_project.go]: Makes sense! I'll get that back in there. 🚀

**Comment by bflad** [comment]
Ready for re-review! :shipit: 

```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSCodeBuildProject_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSCodeBuildProject_ -timeout 120m
=== RUN   TestAccAWSCodeBuildProject_basic
--- PASS: TestAccAWSCodeBuildProject_basic (39.06s)
=== RUN   TestAccAWSCodeBuildProject_default_build_timeout
--- PASS: TestAccAWSCodeBuildProject_default_build_timeout (37.37s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	76.488s
```

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.7.1](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#171-january-19-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
