### PR TITLE
Deletes Global Accelerator listeners before accelerator

### LINKED ISSUE #11317: Global Accelerator accelerator test sweeper fails when it has associated listener
The test sweeper for `aws_globalaccelerator_accelerator` returns the error

```
AssociatedListenerFoundException: Cannot delete accelerator <the ARN> because an associated listener was found.
```

when there is an associated listener.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource

* aws_globalaccelerator_accelerator

### PR DESCRIPTION
**Pull request by gdavison**
The test sweeper for `aws_globalaccelerator_accelerator` returns the error

```
AssociatedListenerFoundException: Cannot delete accelerator <the ARN> because an associated listener was found.
```

when there is an associated listener.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #11317 

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Output from acceptance testing:

```
$ SWEEPARGS='-sweep-run=aws_globalaccelerator_accelerator' make sweep

2019/12/16 16:09:02 [DEBUG] Running Sweepers for region (us-east-1):
2019/12/16 16:09:02 [DEBUG] Running Sweeper (aws_globalaccelerator_accelerator) in region (us-east-1)
2019/12/16 16:09:02 [INFO] Building AWS auth structure
2019/12/16 16:09:02 [INFO] Setting AWS metadata API timeout to 100ms
2019/12/16 16:09:03 [INFO] Ignoring AWS metadata API endpoint at default location as it doesn't return any instance-id
2019/12/16 16:09:03 [INFO] AWS Auth provider used: "SharedCredentialsProvider"
2019/12/16 16:09:03 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2019/12/16 16:09:04 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2019/12/16 16:09:05 [INFO] deleting Listeners for Accelerator arn:aws:globalaccelerator::187416307283:accelerator/28d9762b-5082-430d-a507-45ba8dd38c36
2019/12/16 16:09:05 [INFO] deleting Endpoint Groups for Listener arn:aws:globalaccelerator::187416307283:accelerator/28d9762b-5082-430d-a507-45ba8dd38c36/listener/f5edba58
2019/12/16 16:09:06 [INFO] Disabling Global Accelerator Accelerator: arn:aws:globalaccelerator::187416307283:accelerator/28d9762b-5082-430d-a507-45ba8dd38c36
2019/12/16 16:09:06 [DEBUG] Waiting for Global Accelerator accelerator (arn:aws:globalaccelerator::187416307283:accelerator/28d9762b-5082-430d-a507-45ba8dd38c36) availability
2019/12/16 16:09:06 [DEBUG] Waiting for state to become: [DEPLOYED]
2019/12/16 16:09:06 [DEBUG] Global Accelerator accelerator (arn:aws:globalaccelerator::187416307283:accelerator/28d9762b-5082-430d-a507-45ba8dd38c36) status : IN_PROGRESS
2019/12/16 16:09:06 [TRACE] Waiting 200ms before next try
2019/12/16 16:09:06 [DEBUG] Global Accelerator accelerator (arn:aws:globalaccelerator::187416307283:accelerator/28d9762b-5082-430d-a507-45ba8dd38c36) status : IN_PROGRESS
2019/12/16 16:09:06 [TRACE] Waiting 400ms before next try
2019/12/16 16:09:07 [DEBUG] Global Accelerator accelerator (arn:aws:globalaccelerator::187416307283:accelerator/28d9762b-5082-430d-a507-45ba8dd38c36) status : IN_PROGRESS
2019/12/16 16:09:07 [TRACE] Waiting 800ms before next try
2019/12/16 16:09:08 [DEBUG] Global Accelerator accelerator (arn:aws:globalaccelerator::187416307283:accelerator/28d9762b-5082-430d-a507-45ba8dd38c36) status : IN_PROGRESS
2019/12/16 16:09:08 [TRACE] Waiting 1.6s before next try
2019/12/16 16:09:10 [DEBUG] Global Accelerator accelerator (arn:aws:globalaccelerator::187416307283:accelerator/28d9762b-5082-430d-a507-45ba8dd38c36) status : IN_PROGRESS
2019/12/16 16:09:10 [TRACE] Waiting 3.2s before next try
2019/12/16 16:09:13 [DEBUG] Global Accelerator accelerator (arn:aws:globalaccelerator::187416307283:accelerator/28d9762b-5082-430d-a507-45ba8dd38c36) status : IN_PROGRESS
2019/12/16 16:09:13 [TRACE] Waiting 6.4s before next try
2019/12/16 16:09:20 [DEBUG] Global Accelerator accelerator (arn:aws:globalaccelerator::187416307283:accelerator/28d9762b-5082-430d-a507-45ba8dd38c36) status : DEPLOYED
2019/12/16 16:09:20 [INFO] Deleting Global Accelerator Accelerator: arn:aws:globalaccelerator::187416307283:accelerator/28d9762b-5082-430d-a507-45ba8dd38c36
2019/12/16 16:09:21 Sweeper Tests ran successfully:
	- aws_globalaccelerator_accelerator
2019/12/16 16:09:21 [DEBUG] Running Sweepers for region (us-west-2):
2019/12/16 16:09:21 [DEBUG] Running Sweeper (aws_globalaccelerator_accelerator) in region (us-west-2)
2019/12/16 16:09:21 [INFO] Building AWS auth structure
2019/12/16 16:09:21 [INFO] Setting AWS metadata API timeout to 100ms
2019/12/16 16:09:21 [INFO] Ignoring AWS metadata API endpoint at default location as it doesn't return any instance-id
2019/12/16 16:09:21 [INFO] AWS Auth provider used: "SharedCredentialsProvider"
2019/12/16 16:09:21 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2019/12/16 16:09:21 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2019/12/16 16:09:22 Sweeper Tests ran successfully:
	- aws_globalaccelerator_accelerator
ok  	github.com/terraform-providers/terraform-provider-aws/aws	21.466s
```

```
$ make testacc TESTARGS='-run=TestAccAwsGlobalAccelerator'

--- PASS: TestAccAwsGlobalAcceleratorAccelerator_basic (61.91s)
--- PASS: TestAccAwsGlobalAcceleratorAccelerator_attributes (80.06s)
--- PASS: TestAccAwsGlobalAcceleratorAccelerator_update (85.06s)
--- PASS: TestAccAwsGlobalAcceleratorListener_basic (99.62s)
--- PASS: TestAccAwsGlobalAcceleratorListener_update (127.71s)
--- PASS: TestAccAwsGlobalAcceleratorEndpointGroup_basic (138.61s)
--- PASS: TestAccAwsGlobalAcceleratorEndpointGroup_update (177.94s)
```

### CODE REVIEW

File: aws/resource_aws_globalaccelerator_listener.go [hunk 1]
```diff
@@ -244,17 +236,10 @@ func resourceAwsGlobalAcceleratorListenerDelete(d *schema.ResourceData, meta int
...
-		Timeout: 5 * time.Minute,
-	}
-
-	log.Printf("[DEBUG] Waiting for Global Accelerator listener (%s) deletion", d.Id())
-	_, err = stateConf.WaitForState()
+	// }
+	err = resourceAwsGlobalAcceleratorAcceleratorWaitForDeployedState(conn, d.Get("accelerator_arn").(string))
 	if err != nil {
-		return fmt.Errorf("Error waiting for Global Accelerator listener (%s) deletion: %s", d.Id(), err)
+		return err
```
Comment (bflad) [inline aws/resource_aws_globalaccelerator_listener.go]: Same here regarding continuing to return the error context:

```suggestion
		return fmt.Errorf("error waiting for Global Accelerator (%s) deployment: %s", d.Get("accelerator_arn").(string), err)
```

File: aws/resource_aws_globalaccelerator_listener.go [hunk 2]
```diff
@@ -212,17 +212,9 @@ func resourceAwsGlobalAcceleratorListenerUpdate(d *schema.ResourceData, meta int
...
-		Refresh: resourceAwsGlobalAcceleratorAcceleratorStateRefreshFunc(conn, d.Get("accelerator_arn").(string)),
-		Timeout: 5 * time.Minute,
-	}
-
-	log.Printf("[DEBUG] Waiting for Global Accelerator listener (%s) availability", d.Id())
-	_, err = stateConf.WaitForState()
+	err = resourceAwsGlobalAcceleratorAcceleratorWaitForDeployedState(conn, d.Get("accelerator_arn").(string))
 	if err != nil {
-		return fmt.Errorf("Error waiting for Global Accelerator listener (%s) availability: %s", d.Id(), err)
+		return nil
```
Comment (bflad) [inline aws/resource_aws_globalaccelerator_listener.go]: Did you mean to swallow the error here? We should also continue to return the error context for operators and code maintainers:

```suggestion
		return fmt.Errorf("error waiting for Global Accelerator (%s) deployment: %s", d.Get("accelerator_arn").(string), err)
```

Otherwise folks will receive potentially confusing messages such as:

```
Error applying: unexpected state (FAILED), wanted (DEPLOYED), lastError: xxx
```

File: aws/resource_aws_globalaccelerator_accelerator_test.go [hunk 3]
```diff
@@ -95,6 +103,73 @@ func testSweepGlobalAcceleratorAccelerators(region string) error {
 	return sweeperErrs.ErrorOrNil()
 }
 
+func sweepGlobalAcceleratorListeners(conn *globalaccelerator.GlobalAccelerator, acceleratorArn *string) *multierror.Error {
```
Comment (bflad) [inline aws/resource_aws_globalaccelerator_accelerator_test.go]: Nit: This setup is okay given that there is a hard dependency on removing these, however registering the sweepers to each resource allows you to do targeted sweeping `-sweep-run=aws_global_accelerator_listener` in addition to also cleaning up the sub-resources if `aws_global_accelerator_accelerator` has `Dependencies: []string{"aws_global_accelerator_listener"}` added to its sweeper.

File: aws/resource_aws_globalaccelerator_listener.go (hunk 2 above)
Comment (gdavison) [reply aws/resource_aws_globalaccelerator_listener.go]: No, that was an error. We can just pass the `err`, since the formatted error is now coming from `resourceAwsGlobalAcceleratorAcceleratorWaitForDeployedState`

File: aws/resource_aws_globalaccelerator_listener.go (hunk 1 above)
Comment (gdavison) [reply aws/resource_aws_globalaccelerator_listener.go]: This was intended, since the formatted error is now coming from `resourceAwsGlobalAcceleratorAcceleratorWaitForDeployedState`

File: aws/resource_aws_globalaccelerator_accelerator_test.go (hunk 3 above)
Comment (gdavison) [reply aws/resource_aws_globalaccelerator_accelerator_test.go]: Ok, I figured that since every `aws_globalaccelerator_endpoint_group` depends on an `aws_globalaccelerator_listener`, which depends on an `aws_globalaccelerator_accelerator`, it would make sense to do the sweep in one place. Is there an advantage to being able to sweep, e.g. all Endpoint Groups, while leaving the Listeners and Accelerators?

Only the `aws_globalaccelerator_accelerator` is a stand-alone resource, so the `aws_globalaccelerator_endpoint_group` sweeper would be something like the following pseudocode:
```
for _, accelerator := range accelerators {
    for _, listener := range accelerator.Listeners {
        for _, endpointGroup := range listener.EndpointGroups {
            Delete(endpointGroup)
        }
    }
}
```

File: aws/resource_aws_globalaccelerator_listener.go (hunk 1 above)
Comment (bflad) [reply aws/resource_aws_globalaccelerator_listener.go]: Ah, the waiter function takes the approach of having the error context unlike many others. 👍  

In Go 1.12, this presented the problem of not being able to determine the actual underlying error since the context wrapping would hide it (e.g. you cannot check it with `isResourceTimeoutError()`, since the error type is hidden by the wrapping `fmt.Errorf()`). With Go 1.13 and wrapped errors (`%w` in `fmt.Errorf()`), we likely can start letting functions like these add context messaging themselves, but only assuming they are using `%w`.

File: aws/resource_aws_globalaccelerator_accelerator_test.go (hunk 3 above)
Comment (bflad) [reply aws/resource_aws_globalaccelerator_accelerator_test.go]: > Is there an advantage to being able to sweep, e.g. all Endpoint Groups, while leaving the Listeners and Accelerators?

In addition to the targeting flexibility, this may fall under "you don't need it until you need it", such as if other resources needing to declare that specific resource as a sweeper dependency (for now we'd need to declare the top level resource). My only slight point here is more the general practice of not trying to pile all the logic in one sweeper, same as we try to avoid piling multiple resource logic into a single resource. We (of course) also have excellent anti-examples like `aws_iam_user` you recently updated that painstakingly go through dependencies in the top level sweeper. The pseudocode you presented would be the answer here, but honestly any refactoring effort here is not necessary at the moment.
